// "What's new": the update notes, opened once when a player comes in after an update (and
// any time from Settings). Newest first; each has its date and time and a list per language.
import { getLang, t } from './i18n.js';
import { store } from './store.js';
import { esc } from './game.js';

const $ = (id) => document.getElementById(id);
const SEEN = 'darkbags.news.seen';

export const NEWS = [
  {
    id: '2026-10-02d',
    at: '2026-10-02T18:30:00+03:00',
    items: {
      en: ["New mode: Zombies ($0.10). Alone or with up to 3 friends, hold the graveyard against 10 waves of the dead coming from every side, each wave stronger, and a boss on the last. Pick your weapon in the ready room. The time is limited (8 minutes). The further you get, the more XP; clearing it earns titles", "New mode: Gold Rush ($0.10). A quarry map, bags of gold dropping everywhere, random weapons, quick respawns. Grab the most bags in 2:30: only the one winner takes the whole pot as shop credit", "15 new achievements for both modes, among them the titles Zombie Slayer, Top of the Horde, Army of One and Midas"],
      uk: ["Новий режим: Зомбі ($0.10). Сам або з друзями (до 4 гравців) утримуйте цвинтар проти 10 хвиль мерців з усіх боків. Кожна хвиля сильніша, в останній з'являється бос. Зброю обираєте в кімнаті очікування. Час обмежений (8 хвилин). Що далі пройдете, то більше досвіду, а за проходження дають титули", "Новий режим: Золота лихоманка ($0.10). Кар'єр, сумки із золотом падають усюди, зброя випадкова, швидке відродження. Зберіть найбільше сумок за 2:30: тільки один переможець забирає весь банк доларами на покупки в магазині", "15 нових досягнень для обох режимів, серед них титули «Винищувач зомбі», «Перший серед орди», «Армія з одного» та «Мідас»"],
      ru: ["Новый режим: Зомби ($0.10). Один или с друзьями (до 4 игроков) удерживайте кладбище против 10 волн мертвецов со всех сторон. Каждая волна сильнее, в последней появляется босс. Оружие выбираете в комнате ожидания. Время ограничено (8 минут). Чем дальше пройдёте, тем больше опыта, а за прохождение дают титулы", "Новый режим: Золотая лихорадка ($0.10). Карьер, мешки с золотом падают повсюду, оружие случайное, быстрое возрождение. Соберите больше всех мешков за 2:30: только один победитель забирает весь банк долларами на покупки в магазине", "15 новых достижений для обоих режимов, среди них титулы «Истребитель зомби», «Первый среди орды», «Армия из одного» и «Мидас»"],
      es: ["Modo nuevo: Zombis ($0.10). Solo o con hasta 3 amigos, defiende el cementerio de 10 oleadas de muertos que llegan por todos lados, cada una más fuerte, con un jefe en la última. Elige tu arma en la sala. El tiempo es limitado (8 minutos). Cuanto más lejos llegues, más XP; completarlo da títulos", "Modo nuevo: Fiebre del oro ($0.10). Una cantera, bolsas de oro cayendo por todas partes, armas al azar, reaparición rápida. Consigue más bolsas en 2:30: solo el ganador se lleva todo el bote como crédito de tienda", "15 logros nuevos para ambos modos, entre ellos los títulos Cazazombis, Cima de la horda, Ejército de uno y Midas"],
      fr: ["Nouveau mode : Zombies (0,10 $). Seul ou avec jusqu'à 3 amis, tiens le cimetière face à 10 vagues de morts venues de partout, chacune plus forte, avec un boss à la dernière. Choisis ton arme dans la salle. Le temps est limité (8 minutes). Plus tu vas loin, plus tu gagnes d'XP ; finir donne des titres", "Nouveau mode : Ruée vers l'or (0,10 $). Une carrière, des sacs d'or qui tombent partout, armes au hasard, réapparition rapide. Ramasse le plus de sacs en 2:30 : seul le vainqueur rafle tout le pot en crédit boutique", "15 nouveaux succès pour les deux modes, dont les titres Tueur de zombies, Tête de la horde, Armée à moi seul et Midas"],
      pt: ["Modo novo: Zumbis ($0.10). Sozinho ou com até 3 amigos, segure o cemitério contra 10 ondas de mortos vindo de todos os lados, cada uma mais forte, com um chefe na última. Escolha sua arma na sala. O tempo é limitado (8 minutos). Quanto mais longe, mais XP; completar dá títulos", "Modo novo: Corrida do ouro ($0.10). Uma pedreira, sacos de ouro caindo por toda parte, armas aleatórias, renascimento rápido. Pegue mais sacos em 2:30: só o vencedor leva o pote todo como crédito na loja", "15 conquistas novas para os dois modos, entre elas os títulos Matador de zumbis, Topo da horda, Exército de um e Midas"],
      tr: ["Yeni mod: Zombiler (0,10 $). Tek başına ya da en fazla 3 arkadaşla mezarlığı her yönden gelen 10 ölü dalgasına karşı tut; her dalga daha güçlü, sonuncusunda bir boss var. Silahını bekleme odasında seç. Süre sınırlı (8 dakika). Ne kadar ilerlersen o kadar XP; bitirmek unvan kazandırır", "Yeni mod: Altın Hücumu (0,10 $). Bir taş ocağı, her yere düşen altın torbaları, rastgele silahlar, hızlı yeniden doğma. 2:30'da en çok torbayı topla: tüm potu mağaza kredisi olarak yalnızca tek kazanan alır", "İki mod için 15 yeni başarım; aralarında Zombi Avcısı, Ordunun Zirvesi, Tek Kişilik Ordu ve Midas unvanları"],
      zh: ["新模式：僵尸（$0.10）。单人或与最多 3 位好友一起，在墓地抵御从四面八方涌来的 10 波亡灵，每波更强，最后一波有首领。在准备室选择武器。时间有限（8 分钟）。坚持得越久经验越多，通关可获得称号", "新模式：淘金热（$0.10）。采石场地图，金袋随处掉落，武器随机，快速重生。在 2:30 内捡到最多金袋：只有唯一的赢家拿走全部奖池，作为商店余额", "两个模式共 15 个新成就，包括称号「僵尸杀手」「尸群之首」「一人成军」和「点金王」"],
      hi: ["नया मोड: ज़ॉम्बी ($0.10)। अकेले या 3 दोस्तों तक के साथ, हर तरफ़ से आती मुर्दों की 10 लहरों से कब्रिस्तान बचाएँ, हर लहर ज़्यादा ताक़तवर, आख़िरी में बॉस। हथियार तैयारी कक्ष में चुनें। समय सीमित है (8 मिनट)। जितना आगे जाएँगे उतना XP; पूरा करने पर टाइटल", "नया मोड: गोल्ड रश ($0.10)। खदान का नक्शा, हर जगह गिरते सोने के थैले, रैंडम हथियार, तेज़ रीस्पॉन। 2:30 में सबसे ज़्यादा थैले उठाएँ: सिर्फ़ एक विजेता पूरा पॉट दुकान क्रेडिट के रूप में लेता है", "दोनों मोड के लिए 15 नई उपलब्धियाँ, जिनमें ज़ॉम्बी स्लेयर, झुंड का सरताज, अकेली सेना और मिडास टाइटल शामिल हैं"],
      ar: ["وضع جديد: الزومبي (0.10 $). وحدك أو مع حتى 3 أصدقاء، احمِ المقبرة من 10 موجات من الموتى قادمة من كل الجهات، كل موجة أقوى، وزعيم في الأخيرة. اختر سلاحك في غرفة الانتظار. الوقت محدود (8 دقائق). كلما تقدمت زادت الخبرة؛ وإتمامه يمنح ألقابًا", "وضع جديد: حمى الذهب (0.10 $). محجر وأكياس ذهب تتساقط في كل مكان وأسلحة عشوائية وعودة سريعة. اجمع أكثر الأكياس في 2:30: فائز واحد فقط يأخذ الوعاء كله رصيدًا للمتجر", "15 إنجازًا جديدًا للوضعين، منها ألقاب قاتل الزومبي وقمة الحشد وجيش من رجل واحد وميداس"],
    },
  },
  {
    id: '2026-10-02c',
    at: '2026-10-02T13:59:00+03:00',
    items: {
      en: ["Titles now have tiers, from plain to rare, epic, legendary (gold), mythic (rainbow aura) and mystery (secret, violet smoke): over your name in matches, in chat, friends, the ready room and on your player card", "32 new achievements: weapon mastery, deathmatch, duels, teams, hardcore, one-weapon wins, turrets, ranked leagues, cases, skins, the battle pass, season titles, and 4 secret ones"],
      uk: ["Титули тепер мають рівні: звичайний, рідкісний, епічний, легендарний (золото), міфічний (райдужна аура) і таємничий (секретні, фіолетовий дим) — над ніком у матчі, у чаті, друзях, кімнаті очікування та на картці гравця", "32 нові досягнення: майстерність зброї, бій на смерть, дуелі, команди, хардкор, перемоги з однією зброєю, турелі, рейтингові ліги, кейси, скіни, бойовий пропуск, сезонні титули і 4 таємні"],
      ru: ["У титулов теперь есть уровни: обычный, редкий, эпический, легендарный (золото), мифический (радужная аура) и таинственный (секретные, фиолетовый дым) — над ником в матче, в чате, друзьях, комнате ожидания и на карточке игрока", "32 новых достижения: мастерство оружия, бой насмерть, дуэли, команды, хардкор, победы с одним оружием, турели, рейтинговые лиги, кейсы, скины, боевой пропуск, сезонные титулы и 4 тайных"],
      es: ["Los títulos tienen niveles: común, raro, épico, legendario (oro), mítico (aura arcoíris) y misterio (secretos, humo violeta), sobre tu nombre, en el chat, amigos, la sala y tu tarjeta", "32 logros nuevos: maestría de armas, todos contra todos, duelos, equipos, hardcore, un arma, torretas, ligas clasificatorias, cajas, skins, pase, títulos de temporada y 4 secretos"],
      fr: ["Les titres ont des niveaux : commun, rare, épique, légendaire (or), mythique (aura arc-en-ciel) et mystère (secrets, fumée violette), au-dessus de ton nom, dans le chat, les amis, la salle et ta carte", "32 nouveaux succès : maîtrise des armes, deathmatch, duels, équipes, hardcore, une arme, tourelles, ligues classées, caisses, skins, passe, titres de saison et 4 secrets"],
      pt: ["Os títulos têm níveis: comum, raro, épico, lendário (ouro), mítico (aura arco-íris) e mistério (secretos, fumaça violeta), acima do seu nome, no chat, amigos, sala e no seu cartão", "32 conquistas novas: domínio de armas, mata-mata, duelos, equipes, hardcore, uma arma, torretas, ligas ranqueadas, caixas, skins, passe, títulos da temporada e 4 secretas"],
      tr: ["Unvanların artık seviyeleri var: sıradan, nadir, epik, efsanevi (altın), mitik (gökkuşağı aurası) ve gizem (gizli, mor duman); maçta adının üstünde, sohbette, arkadaşlarda, bekleme odasında ve oyuncu kartında", "32 yeni başarım: silah ustalığı, ölüm maçı, düellolar, takımlar, hardcore, tek silah, taretler, dereceli ligler, kasalar, görünümler, savaş bileti, sezon unvanları ve 4 gizli"],
      zh: ["称号现在有等级：普通、稀有、史诗、传说（金色）、神话（彩虹光环）和神秘（隐藏、紫色烟雾），显示在比赛中名字上方、聊天、好友、准备室和玩家卡片上", "32 个新成就：武器精通、死斗、决斗、团队、硬核、单武器、炮塔、排位联赛、箱子、皮肤、通行证、赛季称号，以及 4 个隐藏成就"],
      hi: ["टाइटल के अब स्तर हैं: सामान्य, दुर्लभ, एपिक, लीजेंडरी (सोना), मिथिक (इंद्रधनुषी आभा) और रहस्य (गुप्त, बैंगनी धुआँ) — मैच में नाम के ऊपर, चैट, दोस्तों, रेडी रूम और प्लेयर कार्ड पर", "32 नई उपलब्धियाँ: हथियार महारत, डेथमैच, द्वंद्व, टीमें, हार्डकोर, एक-हथियार, टर्रेट, रैंक्ड लीग, केस, स्किन, बैटल पास, सीज़न टाइटल और 4 गुप्त"],
      ar: ["للألقاب الآن مستويات: عادي، نادر، ملحمي، أسطوري (ذهبي)، خرافي (هالة قوس قزح) وغامض (سرية، دخان بنفسجي) — فوق اسمك في المباراة، في الدردشة، الأصدقاء، غرفة الاستعداد وبطاقة اللاعب", "32 إنجازاً جديداً: إتقان الأسلحة، القتال حتى الموت، المبارزات، الفرق، هاردكور، السلاح الواحد، الأبراج، دوريات المصنّفة، الصناديق، الأشكال، التذكرة، ألقاب الموسم و4 إنجازات سرية"],
    },
  },
  {
    id: '2026-10-02b',
    at: '2026-10-02T13:45:00+03:00',
    items: {
      en: ['Locker: tap your runner to see only what you own, filter and sort by rarity, preview and equip (outfits, weapon skins, turret skins)', 'Health no longer comes back by itself in a match: only Guns + Lasers medkits heal', 'Every enemy still standing shows on the minimap (teammates in green)', 'Enemy names and red health bars in every mode', 'Friends: browse everyone who has ever played (show more), invite players into your guild', 'Smoother menus: the live map behind windows pauses while they are open', 'Stakes: a $100 table, and type your own from $0.10 to $10,000', 'Share cards show your name', "What's new: these notes open after every update (also in Settings)"],
      uk: ['Шафка: натисни на персонажа — лише твої речі, фільтр і сортування за рідкістю, приміряти й екіпірувати (образи, скіни зброї, скіни турелей)', 'Здоров’я в матчі більше не відновлюється само: лікують лише аптечки в «Гармати + Лазери»', 'Усі живі вороги на міні-карті (союзники зеленим)', 'Ніки ворогів і червоні шкали здоров’я в усіх режимах', 'Друзі: усі гравці, які хоч раз грали («Показати ще»), запрошення в гільдію', 'Плавніші меню: жива карта за вікнами стає на паузу, поки вони відкриті', 'Ставки: стіл $100 і своя сума від $0.10 до $10 000', 'На картках «Поділитися» видно твій нік', '«Що нового»: ці нотатки відкриваються після кожного оновлення (також у Налаштуваннях)'],
      ru: ['Шкафчик: нажми на персонажа — только твои вещи, фильтр и сортировка по редкости, примерить и экипировать (образы, скины оружия, скины турелей)', 'Здоровье в матче больше не восстанавливается само: лечат только аптечки в «Пушки + Лазеры»', 'Все живые враги на мини-карте (союзники зелёным)', 'Ники врагов и красные полоски здоровья во всех режимах', 'Друзья: все игроки, кто хоть раз играл («Показать ещё»), приглашения в гильдию', 'Плавнее меню: живая карта за окнами на паузе, пока они открыты', 'Ставки: стол $100 и своя сумма от $0.10 до $10 000', 'На карточках «Поделиться» виден твой ник', '«Что нового»: эти заметки открываются после каждого обновления (также в Настройках)'],
      es: ['Taquilla: toca tu corredor para ver solo lo tuyo, filtra y ordena por rareza, prueba y equipa (atuendos, skins de arma y de torreta)', 'La salud ya no se recupera sola en partida: solo curan los botiquines de Armas + Láseres', 'Todos los enemigos vivos aparecen en el minimapa (aliados en verde)', 'Nombres de enemigos y barras de vida rojas en todos los modos', 'Amigos: todos los que han jugado alguna vez (mostrar más), invita jugadores a tu gremio', 'Menús más fluidos: el mapa en vivo detrás de las ventanas se pausa', 'Apuestas: mesa de $100 y tu propia cantidad de $0.10 a $10.000', 'Las tarjetas para compartir muestran tu nombre', 'Novedades: estas notas se abren tras cada actualización (también en Ajustes)'],
      fr: ['Casier : touche ton coureur pour ne voir que tes objets, filtre et trie par rareté, essaie et équipe (tenues, skins d’arme et de tourelle)', 'La santé ne revient plus seule en match : seuls les médikits de Armes + Lasers soignent', 'Tous les ennemis encore debout sur la mini-carte (alliés en vert)', 'Noms des ennemis et barres de vie rouges dans tous les modes', 'Amis : tous ceux qui ont déjà joué (voir plus), invite des joueurs dans ta guilde', 'Menus plus fluides : la carte en direct derrière les fenêtres se met en pause', 'Mises : une table à 100 $ et ton propre montant de 0,10 $ à 10 000 $', 'Les cartes à partager affichent ton pseudo', "Nouveautés : ces notes s'ouvrent après chaque mise à jour (aussi dans Réglages)"],
      pt: ['Armário: toque no seu corredor para ver só o que é seu, filtre e ordene por raridade, prove e equipe (roupas, skins de arma e de torreta)', 'A vida não volta mais sozinha na partida: só os kits médicos de Armas + Lasers curam', 'Todos os inimigos vivos aparecem no minimapa (aliados em verde)', 'Nomes de inimigos e barras de vida vermelhas em todos os modos', 'Amigos: todos que já jogaram (mostrar mais), convide jogadores para sua guilda', 'Menus mais suaves: o mapa ao vivo atrás das janelas pausa enquanto estão abertas', 'Apostas: mesa de $100 e seu próprio valor de $0,10 a $10.000', 'Os cartões de compartilhar mostram seu nome', 'Novidades: estas notas abrem após cada atualização (também em Ajustes)'],
      tr: ['Dolap: koşucuna dokun, yalnızca senin eşyaların; nadirliğe göre filtrele ve sırala, dene ve kuşan (kıyafetler, silah ve taret görünümleri)', 'Can artık maçta kendiliğinden dolmuyor: yalnızca Silahlar + Lazerler medkitleri iyileştirir', 'Ayakta kalan tüm düşmanlar mini haritada (takım arkadaşları yeşil)', 'Tüm modlarda düşman isimleri ve kırmızı can çubukları', 'Arkadaşlar: bir kez bile oynamış herkes (daha fazla), oyuncuları loncana davet et', 'Daha akıcı menüler: pencereler açıkken arkadaki canlı harita durur', 'Bahisler: $100 masası ve $0.10–$10.000 arası kendi tutarın', 'Paylaşım kartlarında adın görünür', 'Yenilikler: bu notlar her güncellemeden sonra açılır (Ayarlar’da da)'],
      zh: ['储物柜：点击角色只看你拥有的物品，按稀有度筛选和排序，试穿并装备（服装、武器皮肤、炮塔皮肤）', '比赛中生命不再自动恢复：只有「枪械+激光」的医疗包能治疗', '所有存活的敌人显示在小地图上（队友为绿色）', '所有模式中显示敌人名字和红色血条', '好友：浏览所有玩过的玩家（显示更多），邀请玩家加入你的公会', '菜单更流畅：窗口打开时后方的实时地图暂停', '赌注：新增 $100 桌，并可自填 $0.10 至 $10,000', '分享卡片显示你的昵称', '更新内容：每次更新后自动打开（也可在设置中查看）'],
      hi: ['लॉकर: अपने रनर पर टैप करो — सिर्फ़ तुम्हारी चीज़ें, दुर्लभता से फ़िल्टर और सॉर्ट, देखो और पहनो (आउटफ़िट, हथियार और टर्रेट स्किन)', 'मैच में हेल्थ अब अपने-आप वापस नहीं आती: सिर्फ़ गन्स + लेज़र्स के मेडकिट ठीक करते हैं', 'ज़िंदा सभी दुश्मन मिनी-मैप पर (साथी हरे)', 'हर मोड में दुश्मनों के नाम और लाल हेल्थ बार', 'दोस्त: जिसने भी कभी खेला सब (और दिखाओ), खिलाड़ियों को अपनी गिल्ड में बुलाओ', 'स्मूद मेन्यू: विंडो खुली रहने पर पीछे का लाइव मैप रुक जाता है', 'दांव: $100 टेबल, और $0.10 से $10,000 तक अपना दांव लिखो', 'शेयर कार्ड पर तुम्हारा नाम दिखता है', 'नया क्या है: ये नोट हर अपडेट के बाद खुलते हैं (सेटिंग्स में भी)'],
      ar: ['الخزانة: المس عدّاءك لترى ما تملكه فقط، صفِّ ورتّب حسب الندرة، جرّب وجهّز (أزياء، أشكال أسلحة وأبراج)', 'الصحة لم تعد تعود وحدها أثناء المباراة: فقط حقائب الإسعاف في الأسلحة + الليزر تعالج', 'كل الأعداء الأحياء على الخريطة المصغرة (الحلفاء بالأخضر)', 'أسماء الأعداء وأشرطة صحة حمراء في كل الأوضاع', 'الأصدقاء: كل من لعب ولو مرة (عرض المزيد)، وادعُ لاعبين إلى نقابتك', 'قوائم أسلس: الخريطة الحية خلف النوافذ تتوقف أثناء فتحها', 'الرهانات: طاولة 100$ ورهانك الخاص من 0.10$ إلى 10,000$', 'بطاقات المشاركة تعرض اسمك', 'الجديد: تُفتح هذه الملاحظات بعد كل تحديث (وفي الإعدادات أيضاً)'],
    },
  },
  {
    id: '2026-10-02a',
    at: '2026-10-02T01:22:00+03:00',
    items: {
      en: ['Ranked battles: a season rating from Bronze to Neon Legend, a bonus spin, neon season titles with bonus XP, and a leaderboard', 'Battle pass: monthly seasons with armour sets, seasonal weapon and turret skins', '18 new cases and a CS-style opening reel; a full-screen show for every new rank', '7 new guns with magazines and automatic reload; red and green team colours', '7 new music tracks'],
      uk: ['Рейтингові бої: сезонний рейтинг від Бронзи до Неонової легенди, бонусна рулетка, неонові сезонні титули з бонусом XP і таблиця лідерів', 'Бойовий пропуск: щомісячні сезони з бронею, сезонними скінами зброї та турелей', '18 нових кейсів і прокрутка відкриття як у CS; повноекранне вітання з кожним новим рангом', '7 нових стволів із магазинами й автоматичною перезарядкою; червоні й зелені кольори команд', '7 нових музичних треків'],
      ru: ['Рейтинговые бои: сезонный рейтинг от Бронзы до Неоновой легенды, бонусная рулетка, неоновые сезонные титулы с бонусом XP и таблица лидеров', 'Боевой пропуск: ежемесячные сезоны с бронёй, сезонными скинами оружия и турелей', '18 новых кейсов и прокрутка открытия как в CS; полноэкранное поздравление с каждым новым рангом', '7 новых стволов с магазинами и автоматической перезарядкой; красные и зелёные цвета команд', '7 новых музыкальных треков'],
      es: ['Clasificatorias: rango de temporada de Bronce a Leyenda Neón, giro extra, títulos neón con XP extra y tabla de líderes', 'Pase de batalla: temporadas mensuales con armaduras y skins de arma y torreta', '18 cajas nuevas y ruleta de apertura estilo CS; pantalla completa con cada nuevo rango', '7 armas nuevas con cargadores y recarga automática; colores de equipo rojo y verde', '7 temas musicales nuevos'],
      fr: ['Classé : classement de saison de Bronze à Légende Néon, tirage bonus, titres néon avec XP bonus et classement', 'Passe de combat : saisons mensuelles avec armures, skins d’arme et de tourelle', '18 nouvelles caisses et une roulette d’ouverture façon CS ; un écran plein pour chaque nouveau grade', '7 nouvelles armes avec chargeurs et rechargement automatique ; couleurs d’équipe rouge et vert', '7 nouveaux morceaux'],
      pt: ['Ranqueadas: classificação da temporada do Bronze à Lenda Neon, giro bônus, títulos neon com XP extra e ranking', 'Passe de batalha: temporadas mensais com armaduras, skins de arma e torreta', '18 caixas novas e roleta de abertura estilo CS; tela cheia a cada nova patente', '7 armas novas com carregadores e recarga automática; cores de equipe vermelho e verde', '7 músicas novas'],
      tr: ['Dereceli: Bronzdan Neon Efsane’ye sezon puanı, bonus çark, XP bonuslu neon unvanlar ve lider tablosu', 'Savaş bileti: zırh setli, sezonluk silah ve taret görünümlü aylık sezonlar', '18 yeni kasa ve CS tarzı açılış çarkı; her yeni rütbe için tam ekran gösteri', 'Şarjörlü ve otomatik doldurmalı 7 yeni silah; kırmızı ve yeşil takım renkleri', '7 yeni müzik parçası'],
      zh: ['排位赛：从青铜到霓虹传奇的赛季积分、额外转盘、带经验加成的霓虹赛季称号与排行榜', '战斗通行证：每月赛季，含护甲套装、赛季武器与炮塔皮肤', '18 个新箱子与 CS 风格开箱转盘；每次升衔全屏庆祝', '7 把带弹匣和自动换弹的新枪；红绿队伍配色', '7 首新音乐'],
      hi: ['रैंक्ड: ब्रॉन्ज़ से नियॉन लीजेंड तक सीज़न रेटिंग, बोनस स्पिन, बोनस XP वाले नियॉन टाइटल और लीडरबोर्ड', 'बैटल पास: कवच सेट, सीज़नल हथियार और टर्रेट स्किन वाले मासिक सीज़न', '18 नए केस और CS जैसा ओपनिंग रील; हर नई रैंक पर फ़ुल-स्क्रीन जश्न', 'मैगज़ीन और ऑटो रीलोड वाली 7 नई बंदूकें; लाल और हरे टीम रंग', '7 नए म्यूज़िक ट्रैक'],
      ar: ['المصنّفة: تصنيف موسمي من البرونز إلى أسطورة النيون، دورة إضافية، ألقاب نيون بخبرة إضافية، وجدول متصدرين', 'تذكرة المعركة: مواسم شهرية بدروع وأشكال أسلحة وأبراج موسمية', '18 صندوقاً جديداً وعجلة فتح على طريقة CS؛ احتفال بملء الشاشة لكل رتبة جديدة', '7 أسلحة جديدة بمخازن وإعادة تلقيم تلقائية؛ ألوان فرق حمراء وخضراء', '7 مقطوعات موسيقية جديدة'],
    },
  },
];

export function createNews() {
  function render() {
    const lang = getLang();
    const fmt = (iso) => new Date(iso).toLocaleString(lang, { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' });
    $('news-body').innerHTML = NEWS.map((n, i) => `<article class="news-item${i === 0 ? ' latest' : ''}"><time datetime="${n.at}">${esc(fmt(n.at))}</time><ul>${(n.items[lang] ?? n.items.en).map((x) => `<li>${esc(x)}</li>`).join('')}</ul></article>`).join('');
  }
  function open() {
    render();
    $('dlg-news').showModal();
    store.set(SEEN, NEWS[0].id);
  }
  // after an update: once, as the player comes in
  function maybeShow() {
    if (store.get(SEEN, null) !== NEWS[0].id) setTimeout(open, 500);
  }
  const markSeen = () => store.set(SEEN, NEWS[0].id);
  $('news-ok').addEventListener('click', () => $('dlg-news').close());
  return { open, maybeShow, markSeen };
}
