// "What's new": the update notes, opened once when a player comes in after an update (and
// any time from Settings). Newest first; each has its date and time and a list per language.
import { getLang, t } from './i18n.js';
import { store } from './store.js';
import { esc } from './game.js';

const $ = (id) => document.getElementById(id);
const SEEN = 'darkbags.news.seen';

export const NEWS = [
  {
    id: '2026-10-12a',
    at: '2026-10-12T12:00:00+03:00',
    items: {
      en: ["New players: pick a runner name and a region (with live ping) on the first visit", "Nyx, now fully animated, walks you through every part of the game in text, then plays your first match with you", "The game starts in the language of your country; new: Kiswahili"],
      uk: ["Нові гравці: при першому вході — нік і регіон (з живим пінгом)", "Nyx, тепер повністю анімована, текстом проводить по кожній частині гри, а потім грає з тобою перший матч", "Гра стартує мовою твоєї країни; нова мова: суахілі"],
      ru: ["Новые игроки: при первом входе — ник и регион (с живым пингом)", "Nyx, теперь полностью анимированная, текстом проводит по каждой части игры, а потом играет с тобой первый матч", "Игра стартует на языке твоей страны; новый язык: суахили"],
      es: ["Jugadores nuevos: nombre y región (con ping en vivo) al entrar por primera vez", "Nyx, ahora totalmente animada, te guía por todo el juego en texto y juega tu primera partida contigo", "El juego empieza en el idioma de tu país; nuevo: suajili"],
      fr: ["Nouveaux joueurs : pseudo et région (ping en direct) à la première visite", "Nyx, désormais animée, te guide dans tout le jeu en texte puis joue ton premier match avec toi", "Le jeu démarre dans la langue de ton pays ; nouveau : swahili"],
      pt: ["Novos jogadores: nome e região (com ping ao vivo) na primeira visita", "Nyx, agora animada, te guia por todo o jogo em texto e joga sua primeira partida com você", "O jogo começa no idioma do seu país; novo: suaíli"],
      tr: ["Yeni oyuncular: ilk girişte ad ve bölge (canlı ping ile)", "Artık tamamen animasyonlu Nyx, oyunun her bölümünü metinle anlatır ve ilk maçını seninle oynar", "Oyun ülkenin diliyle başlar; yeni: Svahili"],
      zh: ["新玩家：首次进入时设置名字并选择区域（实时延迟）", "全新动画的 Nyx 用文字带你了解游戏的每个部分，并陪你打第一场比赛", "游戏自动使用你所在国家的语言；新增斯瓦希里语"],
      hi: ["नए खिलाड़ी: पहली बार में नाम और रीजन (लाइव पिंग के साथ)", "अब पूरी तरह एनिमेटेड Nyx पूरे खेल को टेक्स्ट में समझाती है और पहला मैच साथ खेलती है", "खेल तुम्हारे देश की भाषा में शुरू होता है; नई भाषा: स्वाहिली"],
      ar: ["لاعبون جدد: اختر اسمًا ومنطقة (مع بينغ مباشر) عند أول دخول", "نيكس، متحركة بالكامل الآن، تشرح كل جزء من اللعبة نصًا ثم تلعب معك مباراتك الأولى", "تبدأ اللعبة بلغة بلدك؛ جديد: السواحيلية"],
      sw: ["Wachezaji wapya: chagua jina la mkimbiaji na eneo (na ping ya moja kwa moja) mara ya kwanza", "Nyx, sasa mwenye uhuishaji kamili, anakuonyesha kila sehemu ya mchezo kwa maandishi, kisha anacheza mechi yako ya kwanza nawe", "Mchezo unaanza kwa lugha ya nchi yako; mpya: Kiswahili"],
    },
  },
  {
    id: '2026-10-11a',
    at: '2026-10-11T12:00:00+03:00',
    items: {
      en: ["The Play tab, rebuilt: today's goals at the top, modes by category, and the chosen mode explained: how you win, a tip, what it pays", "VIP levels 1–10 from real money paid: top-up bonus up to +15%, daily free spins, VIP frames and a badge", "Fixed: typing your own stake no longer gets overwritten"],
      uk: ["Нова вкладка Play: цілі на сьогодні зверху, режими за категоріями й пояснення обраного режиму: як виграти, порада, що дає", "Рівні VIP 1–10 за реальні оплати: бонус до поповнення до +15%, щоденні безкоштовні спіни, VIP-рамки й значок", "Виправлено: власна ставка більше не перезаписується під час введення"],
      ru: ["Новая вкладка Play: цели на сегодня, режимы по категориям и объяснение выбранного режима", "Уровни VIP 1–10 за реальные оплаты: бонус к пополнению до +15%, ежедневные спины, VIP-рамки и значок", "Исправлено: своя ставка больше не перезаписывается при вводе"],
      es: ["Nueva pestaña Jugar: metas de hoy, modos por categoría y explicación del modo elegido", "Niveles VIP 1–10 por dinero real pagado: bono de recarga hasta +15%, giros diarios, marcos VIP", "Arreglado: tu apuesta propia ya no se sobrescribe al escribir"],
      fr: ["Onglet Jouer refait : objectifs du jour, modes par catégorie et explication du mode choisi", "Niveaux VIP 1–10 selon l’argent réel payé : bonus de recharge jusqu’à +15 %, tours quotidiens, cadres VIP", "Corrigé : ta mise perso n’est plus écrasée pendant la saisie"],
      pt: ["Nova aba Jogar: metas de hoje, modos por categoria e explicação do modo escolhido", "Níveis VIP 1–10 por dinheiro real pago: bônus de recarga até +15%, giros diários, molduras VIP", "Corrigido: sua aposta própria não é mais sobrescrita ao digitar"],
      tr: ["Yeni Oyna sekmesi: günün hedefleri, kategorili modlar ve seçili modun açıklaması", "Gerçek ödemelerle VIP 1–10: %15'e kadar yükleme bonusu, günlük çevirmeler, VIP çerçeveleri", "Düzeltildi: kendi bahsini yazarken artık üzerine yazılmıyor"],
      zh: ["全新开始页：今日目标、分类模式、所选模式说明", "VIP 1–10 级（按真实付款）：充值加成最高 +15%、每日免费转动、VIP 头像框", "修复：输入自定义赌注时不再被覆盖"],
      hi: ["नया प्ले टैब: आज के लक्ष्य, कैटेगरी में मोड और चुने मोड की जानकारी", "असली भुगतान से VIP 1–10: +15% तक टॉप-अप बोनस, रोज़ स्पिन, VIP फ़्रेम", "ठीक किया: अपना दांव लिखते समय अब नहीं बदलता"],
      ar: ["تبويب اللعب الجديد: أهداف اليوم، أوضاع حسب الفئة، وشرح الوضع المختار", "مستويات VIP 1–10 بالمدفوعات الحقيقية: مكافأة شحن حتى +15%، دورات يومية، إطارات VIP", "إصلاح: رهانك الخاص لم يعد يُستبدل أثناء الكتابة"],
    },
  },
  {
    id: '2026-10-10a',
    at: '2026-10-10T12:00:00+03:00',
    items: {
      en: ["Today's store: six skins a day bought outright, no roll, a new set every day", "Insider card: 30 days of daily shop $ and a wheel spin, +25% pass XP and its own frame", "Starter pack (once): an Epic outfit, 3 boxes, 5 spins and a frame for $1.99", "Buy battle-pass tiers; open every box you hold at once; spin all your free spins at once"],
      uk: ["Магазин дня: шість скінів щодня, купуєш одразу без рулетки, новий набір щодня", "Insider-картка: 30 днів щоденних $ у магазин і спіну колеса, +25% XP пасу і власна рамка", "Стартовий набір (один раз): епічний скін, 3 кейси, 5 спінів і рамка за $1.99", "Купівля рівнів батл-пасу; відкривай усі кейси одразу; крути всі безкоштовні спіни разом"],
      ru: ["Магазин дня: шесть скинов в день, покупка сразу без рулетки", "Insider-карта: 30 дней ежедневных $ в магазин и спина, +25% XP пасса и своя рамка", "Стартовый набор (один раз): эпический скин, 3 кейса, 5 спинов и рамка за $1.99", "Покупка уровней батл-пасса; открывай все кейсы сразу; крути все бесплатные спины разом"],
      es: ["Tienda del día: seis skins al día, compra directa", "Tarjeta Insider: 30 días de $ de tienda y giros diarios", "Pack de inicio por $1.99", "Compra niveles del pase; abre todas las cajas a la vez; gira todos tus giros"],
      fr: ["Boutique du jour : six skins par jour, achat direct", "Carte Insider : 30 jours de $ boutique et de tours quotidiens", "Pack de départ à 1,99 $", "Achète des paliers de pass ; ouvre toutes tes caisses d’un coup ; tous tes tours d’un coup"],
      pt: ["Loja do dia: seis skins por dia, compra direta", "Cartão Insider: 30 dias de $ da loja e giros diários", "Pacote inicial por $1.99", "Compre níveis do passe; abra todas as caixas de uma vez; gire todos os giros"],
      tr: ["Günün mağazası: günde altı skin, doğrudan satın al", "Insider kart: 30 gün günlük mağaza $ ve çevirme", "1,99 $ başlangıç paketi", "Pass seviyesi satın al; tüm kasaları tek seferde aç; tüm çevirmeleri birden çevir"],
      zh: ["今日商店：每天六款皮肤，直接购买", "内部人卡：30 天每日商店币和转盘次数", "新手礼包 $1.99", "购买通行证等级；一次打开所有箱子；一次用完所有转动"],
      hi: ["आज की दुकान: रोज़ छह स्किन, सीधी खरीद", "इनसाइडर कार्ड: 30 दिन रोज़ शॉप $ और स्पिन", "$1.99 का स्टार्टर पैक", "पास टियर खरीदो; सारे बॉक्स एक साथ खोलो; सारे स्पिन एक साथ"],
      ar: ["متجر اليوم: ستة سكنات يوميًا بشراء مباشر", "بطاقة Insider: 30 يومًا من رصيد المتجر والدورات اليومية", "حزمة بداية بـ 1.99$", "اشترِ مستويات التذكرة؛ افتح كل الصناديق دفعة واحدة؛ أدر كل الدورات معًا"],
    },
  },
  {
    id: '2026-10-09a',
    at: '2026-10-09T12:00:00+03:00',
    items: {
      en: ["Fortune wheel rebuilt: a real spinning wheel with lights, clicks and confetti, 18 kinds of prizes (style, gift boxes, pass XP, XP boosts, extra spins, real skins…)", "Free spins from tasks, the calendar and mail now spin the shop wheel; open boxes and spin right from the reward, the mail or the inventory", "Balance: free shop $ from tasks and the calendar is smaller, and boxes on the free pass track roll up to Epic"],
      uk: ["Нове колесо фортуни: справжнє колесо з вогнями, клацанням і конфеті, 18 видів призів (стиль, подарункові кейси, XP пасу, бусти XP, додаткові спіни, справжні скіни…)", "Безкоштовні спіни із завдань, календаря й пошти тепер крутять колесо в магазині; відкривай кейси й крути колесо прямо з нагороди, пошти чи інвентаря", "Баланс: менше безкоштовних $ магазину із завдань і календаря, кейси на безкоштовній доріжці пасу — до Епічного"],
      ru: ["Новое колесо фортуны: настоящее колесо с огнями, щелчками и конфетти, 18 видов призов", "Бесплатные спины из заданий, календаря и почты теперь крутят колесо в магазине; открывай кейсы и крути колесо прямо из награды, почты или инвентаря", "Баланс: меньше бесплатных $ магазина, кейсы на бесплатной дорожке пасса — до Эпического"],
      es: ["Nueva rueda de la fortuna: luces, clics, confeti y 18 tipos de premios", "Los giros gratis giran la rueda de la tienda; abre cajas y gira desde la recompensa, el correo o el inventario", "Balance: menos $ de tienda gratis; las cajas del pase gratis llegan hasta Épico"],
      fr: ["Nouvelle roue de la fortune : lumières, clics, confettis et 18 types de prix", "Les tours gratuits font tourner la roue de la boutique ; ouvre caisses et roue depuis la récompense, le courrier ou l’inventaire", "Équilibrage : moins de $ boutique gratuits ; les caisses du pass gratuit vont jusqu’à Épique"],
      pt: ["Nova roda da fortuna: luzes, cliques, confete e 18 tipos de prêmio", "Giros grátis giram a roda da loja; abra caixas e gire direto da recompensa, do correio ou do inventário", "Balanço: menos $ grátis da loja; caixas do passe grátis vão até Épico"],
      tr: ["Yeni şans çarkı: ışıklar, tıklamalar, konfeti ve 18 çeşit ödül", "Ücretsiz çevirmeler mağaza çarkını döndürür; kasaları ödülden, postadan veya envanterden aç", "Denge: daha az ücretsiz mağaza $; ücretsiz pass kasaları Epik'e kadar"],
      zh: ["全新幸运轮盘：灯光、咔哒声、彩带，18 种奖品", "免费次数现在用来转商店轮盘；可直接从奖励、邮件或库存开箱和转盘", "平衡：免费商店币减少；免费通行证的箱子最高史诗"],
      hi: ["नया फ़ॉर्च्यून व्हील: लाइट, क्लिक, कॉन्फ़ेटी और 18 तरह के इनाम", "मुफ़्त स्पिन अब दुकान का व्हील घुमाती हैं; इनाम, मेल या इन्वेंटरी से सीधे बॉक्स खोलो और व्हील घुमाओ", "बैलेंस: कम मुफ़्त शॉप $; फ़्री पास के बॉक्स एपिक तक"],
      ar: ["عجلة حظ جديدة: أضواء ونقرات وقصاصات و18 نوعًا من الجوائز", "الدورات المجانية تدير عجلة المتجر؛ افتح الصناديق وأدر العجلة من المكافأة أو البريد أو المخزون", "التوازن: رصيد متجر مجاني أقل؛ صناديق التذكرة المجانية حتى ملحمي"],
    },
  },
  {
    id: '2026-10-08a',
    at: '2026-10-08T12:00:00+03:00',
    items: {
      en: ["Hold Tab in a match (☰ on phones) for the full scoreboard: kills, deaths, K/D and ping of every player", "Voice chat in online matches: K (or 🎙) turns your microphone on and off; team modes talk to their team", "Free rewards (calendar, tasks, achievements, invites) now give boxes that roll up to Epic; Legendary and Mythic come from paid cases, ranked and the battle pass", "Ranked division prizes: reach Silver and up for style items, Master and Legend give Mythic and Exotic", "Battle pass: new style rewards on both tracks; premium has Mythic frames, names and kill effects", "Trial skins from the Fortune Wheel last 1 hour"],
      uk: ["Затисни Tab у матчі (☰ на телефоні), щоб побачити повну статистику: вбивства, смерті, K/D і пінг кожного гравця", "Голосовий чат в онлайн-матчах: K (або 🎙) вмикає й вимикає мікрофон; у командних режимах — зі своєю командою", "Безкоштовні нагороди (календар, завдання, досягнення, запрошення) тепер дають кейси до Епічної рідкості; Легендарні й Міфічні — з платних кейсів, рейтингу та батл-пасу", "Призи за дивізіони рейтингу: від Срібла — предмети стилю, Майстер і Легенда дають Міфічні та Екзотичні", "Батл-пас: нові стильові нагороди на обох доріжках; преміум має Міфічні рамки, ніки й ефекти вбивства", "Пробні скіни з Колеса Фортуни діють 1 годину"],
      ru: ["Зажми Tab в матче (☰ на телефоне), чтобы увидеть полную статистику: убийства, смерти, K/D и пинг каждого игрока", "Голосовой чат в онлайн-матчах: K (или 🎙) включает и выключает микрофон; в командных режимах — со своей командой", "Бесплатные награды теперь дают кейсы до Эпической редкости; Легендарные и Мифические — из платных кейсов, рейтинга и батл-пасса", "Призы за дивизионы рейтинга: от Серебра — предметы стиля, Мастер и Легенда дают Мифические и Экзотические", "Батл-пасс: новые стильные награды на обеих дорожках", "Пробные скины с Колеса Фортуны действуют 1 час"],
      es: ["Mantén Tab en la partida (☰ en móvil) para ver el marcador completo", "Chat de voz en partidas online: K (o 🎙) activa tu micrófono", "Las recompensas gratis dan cajas hasta Épico; Legendario y Mítico salen de cajas de pago, ranked y el pase", "Premios por división en ranked y estilo nuevo en el pase", "Las skins de prueba de la Rueda duran 1 hora"],
      fr: ["Maintiens Tab en match (☰ sur mobile) pour le tableau des scores complet", "Chat vocal en ligne : K (ou 🎙) active ton micro", "Les récompenses gratuites donnent des caisses jusqu’à Épique ; Légendaire et Mythique viennent des caisses payantes, du classé et du pass", "Prix de division en classé et nouveau style dans le pass", "Les skins d’essai de la Roue durent 1 heure"],
      pt: ["Segure Tab na partida (☰ no celular) para o placar completo", "Chat de voz online: K (ou 🎙) liga seu microfone", "Recompensas grátis dão caixas até Épico; Lendário e Mítico vêm de caixas pagas, ranqueada e passe", "Prêmios por divisão na ranqueada e estilo novo no passe", "Skins de teste da Roda duram 1 hora"],
      tr: ["Maçta Tab'a basılı tut (telefonda ☰): tam skor tablosu", "Çevrimiçi maçlarda sesli sohbet: K (veya 🎙) mikrofonu açar", "Ücretsiz ödüller Epik'e kadar kasa verir; Efsanevi ve Mitik ücretli kasalardan, dereceliden ve pass'ten gelir", "Derecelide lig ödülleri ve pass'te yeni stil", "Çarktaki deneme skinleri 1 saat sürer"],
      zh: ["比赛中按住 Tab（手机点 ☰）查看完整计分板", "在线比赛语音聊天：K（或 🎙）开关麦克风", "免费奖励的箱子最高史诗；传说和神话来自付费箱、排位和通行证", "排位段位奖励，通行证新增风格奖励", "幸运轮试用皮肤持续 1 小时"],
      hi: ["मैच में Tab दबाए रखो (फ़ोन पर ☰): पूरा स्कोरबोर्ड", "ऑनलाइन मैच में वॉइस चैट: K (या 🎙) से माइक", "मुफ़्त इनाम अब एपिक तक के बॉक्स देते हैं; लेजेंडरी और मिथिक पेड केस, रैंक्ड और पास से", "रैंक्ड डिवीज़न इनाम और पास में नया स्टाइल", "व्हील की ट्रायल स्किन 1 घंटा चलती है"],
      ar: ["اضغط مطولًا على Tab في المباراة (☰ على الهاتف) لعرض لوحة النتائج كاملة", "دردشة صوتية في المباريات: K (أو 🎙) يشغّل الميكروفون", "المكافآت المجانية تعطي صناديق حتى ملحمي؛ الأسطوري والخرافي من الصناديق المدفوعة والمصنّف والتذكرة", "جوائز الأقسام في المصنّف وأسلوب جديد في التذكرة", "سكنات التجربة من العجلة تدوم ساعة واحدة"],
    },
  },
  {
    id: '2026-10-07a',
    at: '2026-10-07T12:00:00+03:00',
    items: {
      en: ["Style: 44 animated items: profile frames, banners, kill effects and name colours", "Three Style cases in the shop; style also drops from the daily calendar, weekly tasks and achievement rewards", "Wear them in Inventory → Style: your frame and banner show on your card and in your profile, your name colour over your head, your kill effect where your enemies fall"],
      uk: ["Стиль: 44 анімовані предмети: рамки й банери профілю, ефекти вбивства й кольори ніків", "Три стильові кейси в магазині; стиль також випадає з щоденного календаря, тижневих завдань і нагород за досягнення", "Одягай в Інвентар → Стиль: рамка й банер видно на картці та в профілі, колір ніку над головою, ефект вбивства там, де падає ворог"],
      ru: ["Стиль: 44 анимированных предмета: рамки и баннеры профиля, эффекты убийства и цвета ников", "Три стильных кейса в магазине; стиль также выпадает из ежедневного календаря, недельных заданий и наград за достижения", "Надевай в Инвентарь → Стиль: рамку и баннер видно на карточке и в профиле, цвет ника над головой, эффект убийства там, где падает враг"],
      es: ["Estilo: 44 objetos animados: marcos y banners de perfil, efectos de baja y colores de nombre", "Tres cajas de estilo en la tienda; también salen del calendario diario, tareas semanales y logros", "Equípalos en Inventario → Estilo"],
      fr: ["Style : 44 objets animés : cadres et bannières de profil, effets d’élimination et couleurs de pseudo", "Trois caisses de style en boutique ; le style tombe aussi du calendrier, des tâches hebdo et des succès", "Équipe-les dans Inventaire → Style"],
      pt: ["Estilo: 44 itens animados: molduras e banners de perfil, efeitos de abate e cores de nome", "Três caixas de estilo na loja; também vêm do calendário diário, tarefas semanais e conquistas", "Equipe em Inventário → Estilo"],
      tr: ["Stil: 44 animasyonlu öğe: profil çerçeveleri, afişler, öldürme efektleri ve isim renkleri", "Mağazada üç stil kasası; stil ayrıca günlük takvimden, haftalık görevlerden ve başarımlardan düşer", "Envanter → Stil bölümünden tak"],
      zh: ["风格：44 件动态物品：头像框、横幅、击杀特效和名字颜色", "商店新增三种风格箱；每日签到、每周任务和成就奖励也会掉落", "在 库存 → 风格 中装备"],
      hi: ["स्टाइल: 44 एनिमेटेड चीज़ें: प्रोफ़ाइल फ़्रेम, बैनर, किल इफ़ेक्ट और नाम के रंग", "दुकान में तीन स्टाइल केस; डेली कैलेंडर, साप्ताहिक टास्क और उपलब्धियों से भी मिलते हैं", "इन्वेंटरी → स्टाइल में पहनो"],
      ar: ["الأسلوب: 44 عنصرًا متحركًا: إطارات ولافتات الملف وتأثيرات القتل وألوان الأسماء", "ثلاثة صناديق أسلوب في المتجر؛ ويأتي الأسلوب أيضًا من التقويم اليومي والمهام الأسبوعية والإنجازات", "ارتدِها من المخزون ← الأسلوب"],
    },
  },
  {
    id: '2026-10-06a',
    at: '2026-10-06T12:00:00+03:00',
    items: {
      en: ["Daily rewards: 30 days in a row, gifts grow every day, a big one every 7th day", "Tasks: three every day and three every week, rewards for each, a bonus for all three", "Achievements now pay a reward too: claim it on the Tasks page", "XP boosts and the first win of the day: +300 XP"],
      uk: ["Щоденні нагороди: 30 днів поспіль, подарунки ростуть щодня, щосьомого дня великий", "Завдання: три щодня й три щотижня, нагорода за кожне, бонус за всі три", "Досягнення тепер теж дають нагороду: забери її на сторінці «Завдання»", "Бустери XP і перша перемога дня: +300 XP"],
      ru: ["Ежедневные награды: 30 дней подряд, подарки растут каждый день, каждый 7-й день большой", "Задания: три каждый день и три каждую неделю, награда за каждое, бонус за все три", "Достижения теперь тоже дают награду: забери её на странице «Задания»", "Бустеры XP и первая победа дня: +300 XP"],
      es: ["Recompensas diarias: 30 días seguidos, regalos que crecen, uno grande cada 7 días", "Tareas: tres al día y tres a la semana, con recompensa y bonus por las tres", "Los logros ahora también dan recompensa: reclámala en Tareas", "Potenciadores de XP y primera victoria del día: +300 XP"],
      fr: ["Récompenses quotidiennes : 30 jours d’affilée, des cadeaux qui grandissent, un gros tous les 7 jours", "Tâches : trois par jour et trois par semaine, une récompense chacune, un bonus pour les trois", "Les succès donnent aussi une récompense : récupère-la dans Tâches", "Boosts d’XP et première victoire du jour : +300 XP"],
      pt: ["Recompensas diárias: 30 dias seguidos, presentes que crescem, um grande a cada 7 dias", "Tarefas: três por dia e três por semana, recompensa em cada, bônus pelas três", "Conquistas agora também dão recompensa: resgate em Tarefas", "Bônus de XP e primeira vitória do dia: +300 XP"],
      tr: ["Günlük ödüller: 30 gün üst üste, her gün büyüyen hediyeler, her 7. gün büyük", "Görevler: her gün üç, her hafta üç; her birine ödül, üçüne bonus", "Başarımlar artık ödül de veriyor: Görevler sayfasından al", "XP takviyeleri ve günün ilk galibiyeti: +300 XP"],
      zh: ["每日奖励：连续 30 天，礼物逐日升级，每第 7 天有大礼", "任务：每天三项、每周三项，每项都有奖励，全部完成另有奖励", "成就现在也有奖励：在任务页领取", "经验加成和每日首胜：+300 经验"],
      hi: ["डेली रिवॉर्ड: लगातार 30 दिन, हर दिन बढ़ते तोहफ़े, हर 7वें दिन बड़ा", "टास्क: रोज़ तीन और हर हफ़्ते तीन, हर एक पर इनाम, तीनों पर बोनस", "उपलब्धियाँ अब इनाम भी देती हैं: टास्क पेज पर लो", "XP बूस्ट और दिन की पहली जीत: +300 XP"],
      ar: ["المكافآت اليومية: 30 يومًا متتالية، هدايا تكبر كل يوم وهدية كبيرة كل يوم سابع", "المهام: ثلاث يوميًا وثلاث أسبوعيًا، مكافأة لكل مهمة ومكافأة إضافية للثلاث", "الإنجازات تمنح مكافأة الآن أيضًا: استلمها من صفحة المهام", "معززات XP وأول فوز في اليوم: +300 XP"],
    },
  },
  {
    id: '2026-10-05a',
    at: '2026-10-05T12:00:00+03:00',
    items: {
      en: ["12 new maps, each with its own layout and look: Blockchain, Brick Town, Red Dunes, Frostbite, Lava Forge, Downtown, Neon Arcade, Blackout, Dragon Keep, Toon Town, Gravity Track and the Night Docks", "Vote for the map in the ready room: most votes wins", "Lava, water, mud and mempools: you can't walk through them, but bullets fly over", "Weather on the maps: snow, rain, embers, sand, fireflies, confetti", "13 new music tracks: hardstyle, trap, industrial, chiptune, dubstep, trance and war drums in matches (picked to suit the map); chill lo-fi, jazz, bossa nova and ambient in the menu", "Swap redesigned, K/D leaderboard, the ready room shows your server and ping"],
      uk: ["12 нових карт, у кожної своє компонування й вигляд: Блокчейн, Цеглинкове місто, Червоні дюни, Мороз, Лавова кузня, Даунтаун, Неонова аркада, Блекаут, Драконяча фортеця, Мультяшне містечко, Гравіті-трек і Нічні доки", "Голосуй за карту в кімнаті очікування: перемагає та, що має найбільше голосів", "Лава, вода, багнюка й мемпули: крізь них не пройти, але кулі пролітають", "Погода на картах: сніг, дощ, жар, пісок, світлячки, конфеті", "13 нових музичних треків: хардстайл, треп, індастріал, чиптюн, дабстеп, транс і бойові барабани в матчах (під стиль карти); спокійний lo-fi, джаз, босанова та ембієнт у меню", "Оновлений свап, рейтинг К/С, у кімнаті очікування видно сервер і пінг"],
      ru: ["12 новых карт, у каждой своя планировка и стиль: Блокчейн, Город из кубиков, Красные дюны, Мороз, Лавовая кузня, Даунтаун, Неоновая аркада, Блэкаут, Драконья крепость, Мультгородок, Гравити-трек и Ночные доки", "Голосуй за карту в комнате ожидания: побеждает та, у которой больше голосов", "Лава, вода, грязь и мемпулы: через них не пройти, но пули пролетают", "Погода на картах: снег, дождь, искры, песок, светлячки, конфетти", "13 новых треков: хардстайл, трэп, индастриал, чиптюн, дабстеп, транс и боевые барабаны в матчах (под стиль карты); спокойный lo-fi, джаз, босса-нова и эмбиент в меню", "Обновлённый свап, рейтинг У/С, в комнате ожидания виден сервер и пинг"],
      es: ["12 mapas nuevos, cada uno con su diseño y estilo: Blockchain, Ciudad de bloques, Dunas rojas, Congelación, Forja de lava, Centro, Arcade neón, Apagón, Fortaleza del dragón, Villa cartoon, Pista Gravity y Muelles nocturnos", "Vota el mapa en la sala de espera: gana el más votado", "Lava, agua, barro y mempools: no se puede cruzar a pie, pero las balas pasan", "Clima en los mapas: nieve, lluvia, brasas, arena, luciérnagas, confeti", "13 temas nuevos: hardstyle, trap, industrial, chiptune, dubstep, trance y tambores de guerra en partidas; lo-fi, jazz, bossa nova y ambient en el menú", "Swap rediseñado, ranking K/D, la sala de espera muestra tu servidor y ping"],
      fr: ["12 nouvelles cartes, chacune avec son tracé et son style : Blockchain, Ville en briques, Dunes rouges, Gel mordant, Forge de lave, Centre-ville, Arcade néon, Black-out, Donjon du dragon, Toonville, Piste Gravity et Docks de nuit", "Vote pour la carte dans le salon d'attente : la plus votée gagne", "Lave, eau, boue et mempools : impossible de les traverser, mais les balles passent", "Météo sur les cartes : neige, pluie, braises, sable, lucioles, confettis", "13 nouvelles musiques : hardstyle, trap, industrial, chiptune, dubstep, trance et tambours de guerre en match ; lo-fi, jazz, bossa nova et ambient dans le menu", "Swap repensé, classement K/D, le salon affiche ton serveur et ton ping"],
      pt: ["12 mapas novos, cada um com layout e estilo próprios: Blockchain, Cidade de blocos, Dunas vermelhas, Congelamento, Forja de lava, Centro, Arcade neon, Apagão, Fortaleza do dragão, Cidade cartoon, Pista Gravity e Docas noturnas", "Vote no mapa na sala de espera: o mais votado vence", "Lava, água, lama e mempools: não dá para atravessar a pé, mas as balas passam", "Clima nos mapas: neve, chuva, brasas, areia, vaga-lumes, confete", "13 músicas novas: hardstyle, trap, industrial, chiptune, dubstep, trance e tambores de guerra nas partidas; lo-fi, jazz, bossa nova e ambient no menu", "Swap redesenhado, ranking K/D, a sala de espera mostra seu servidor e ping"],
      tr: ["Her biri kendi düzeni ve görünümüyle 12 yeni harita: Blokzincir, Tuğla Kasaba, Kızıl Kumullar, Ayaz, Lav Ocağı, Şehir Merkezi, Neon Atari, Karartma, Ejder Kalesi, Çizgi Kasaba, Gravity Pisti ve Gece Rıhtımı", "Bekleme odasında haritaya oy ver: en çok oy alan kazanır", "Lav, su, çamur ve mempool: içinden yürünmez ama mermiler geçer", "Haritalarda hava: kar, yağmur, kıvılcım, kum, ateş böceği, konfeti", "13 yeni müzik: maçlarda hardstyle, trap, industrial, chiptune, dubstep, trance ve savaş davulları; menüde lo-fi, caz, bossa nova ve ambient", "Yenilenen takas, K/D sıralaması, bekleme odasında sunucun ve pingin"],
      zh: ["12 张新地图，各有布局与风格：区块链、积木小镇、赤色沙丘、冰封雪原、熔岩熔炉、市中心、霓虹街机、漆黑之夜、龙之要塞、卡通小镇、重力赛道和夜色码头", "在准备室为地图投票：票数最多者胜", "熔岩、水、泥潭和内存池：人走不过去，但子弹能飞过", "地图天气：雪、雨、火星、风沙、萤火虫、彩纸", "13 首新曲：比赛中有硬核舞曲、陷阱、工业、芯片音乐、回响贝斯、迷幻舞曲和战鼓（按地图挑选）；菜单里有轻松的 lo-fi、爵士、波萨诺瓦和氛围音乐", "兑换重新设计、K/D 排行榜、准备室显示服务器与延迟"],
      hi: ["12 नए मैप, हर एक का अपना लेआउट और लुक: ब्लॉकचेन, ब्रिक टाउन, लाल टीले, फ्रॉस्टबाइट, लावा भट्टी, डाउनटाउन, नियॉन आर्केड, ब्लैकआउट, ड्रैगन का किला, टून टाउन, ग्रैविटी ट्रैक और रात के डॉक्स", "रेडी रूम में मैप के लिए वोट करो: सबसे ज़्यादा वोट वाला जीतता है", "लावा, पानी, कीचड़ और मेमपूल: इनसे चलकर नहीं जा सकते, पर गोलियाँ पार जाती हैं", "मैप पर मौसम: बर्फ़, बारिश, चिंगारियाँ, रेत, जुगनू, कॉन्फ़ेटी", "13 नए म्यूज़िक ट्रैक: मैच में हार्डस्टाइल, ट्रैप, इंडस्ट्रियल, चिपट्यून, डबस्टेप, ट्रांस और युद्ध ढोल; मेन्यू में लो-फ़ाई, जैज़, बोसा नोवा और एम्बिएंट", "नया स्वैप, K/D लीडरबोर्ड, रेडी रूम में सर्वर और पिंग"],
      ar: ["12 خريطة جديدة، لكل منها تصميمها وطابعها: بلوك تشين، مدينة المكعبات، الكثبان الحمراء، الصقيع، مسبك الحمم، وسط المدينة، صالة النيون، الظلام الدامس، حصن التنين، مدينة الكرتون، مضمار الجاذبية وأرصفة الليل", "صوّت للخريطة في غرفة الانتظار: الأكثر أصواتًا تفوز", "الحمم والماء والوحل والميمبول: لا يمكن عبورها مشيًا، لكن الرصاص يمر", "طقس على الخرائط: ثلج، مطر، جمر، رمال، يراعات، قصاصات ملونة", "13 مقطوعة جديدة: هاردستايل وتراب وإندستريال وتشيبتيون ودبستيب وترانس وطبول حرب في المباريات؛ ولو-فاي وجاز وبوسا نوفا وأمبينت في القائمة", "تبديل جديد، ترتيب K/D، وغرفة الانتظار تعرض الخادم والبنج"],
    },
  },
  {
    id: '2026-10-04a',
    at: '2026-10-04T12:00:00+03:00',
    items: {
      en: ["Invite friends: a new Invite page with your code and link. For 90 days you get 20% of the house's cut from every stake your friends play, as shop $; they get a welcome bag after their first match, and you a bonus bag when they finish 5", "Fair play: aim that is too perfect for a human (accuracy, headshots, inhuman flicks over hundreds of shots) puts an account under review and holds its withdrawals; one person, one seat at a staked table; limits on new accounts and invites from one network", "Stability: game state is saved safely to disk, slow connections drop stale frames instead of lagging"],
      uk: ["Запроси друзів: нова сторінка «Запросити» з твоїм кодом і посиланням. 90 днів ти отримуєш 20% від комісії гри з кожної ставки друзів доларами на покупки в магазині; друг отримує вітальну сумку після першого матчу, а ти бонусну сумку, коли він зіграє 5", "Чесна гра: занадто ідеальний для людини приціл (точність, хедшоти, нелюдські ривки мишею на сотнях пострілів) відправляє акаунт на перевірку і блокує вивід; одна людина займає одне місце за столом зі ставкою; ліміти на нові акаунти й запрошення з однієї мережі", "Стабільність: стан гри надійно зберігається на диск, на повільному з'єднанні старі кадри відкидаються замість лагів"],
      ru: ["Пригласи друзей: новая страница «Пригласить» с твоим кодом и ссылкой. 90 дней ты получаешь 20% от комиссии игры с каждой ставки друзей долларами на покупки в магазине; друг получает приветственную сумку после первого матча, а ты бонусную сумку, когда он сыграет 5", "Честная игра: слишком идеальный для человека прицел (точность, хедшоты, нечеловеческие рывки мышью на сотнях выстрелов) отправляет аккаунт на проверку и блокирует вывод; один человек занимает одно место за столом со ставкой; лимиты на новые аккаунты и приглашения из одной сети", "Стабильность: состояние игры надёжно сохраняется на диск, на медленном соединении старые кадры отбрасываются вместо лагов"],
      es: ["Invita amigos: nueva página Invitar con tu código y enlace. Durante 90 días recibes el 20% de la comisión de la casa de cada apuesta de tus amigos, como $ de tienda; ellos reciben una bolsa tras su primera partida y tú una extra cuando terminen 5", "Juego limpio: una puntería demasiado perfecta para un humano pone la cuenta en revisión y retiene sus retiros; una persona, un asiento por mesa con apuesta; límites a cuentas nuevas e invitaciones desde una misma red", "Estabilidad: el estado se guarda de forma segura y las conexiones lentas descartan fotogramas viejos en vez de ir con retraso"],
      fr: ["Invite tes amis : nouvelle page Inviter avec ton code et ton lien. Pendant 90 jours tu touches 20 % de la commission de la maison sur chaque mise de tes amis, en $ boutique ; ils reçoivent un sac après leur premier match, toi un sac bonus quand ils en ont joué 5", "Fair-play : une visée trop parfaite pour un humain met le compte en examen et bloque ses retraits ; une personne, une place par table avec mise ; limites sur les nouveaux comptes et invitations depuis un même réseau", "Stabilité : l'état du jeu est sauvegardé en sécurité, les connexions lentes sautent les vieilles images au lieu de laguer"],
      pt: ["Convide amigos: nova página Convidar com seu código e link. Por 90 dias você recebe 20% da taxa da casa de cada aposta dos seus amigos, como $ da loja; eles ganham uma bolsa após a primeira partida e você uma bônus quando terminarem 5", "Jogo limpo: mira perfeita demais para um humano coloca a conta em revisão e segura os saques; uma pessoa, um lugar por mesa com aposta; limites para contas novas e convites da mesma rede", "Estabilidade: o estado do jogo é salvo com segurança e conexões lentas descartam quadros velhos em vez de travar"],
      tr: ["Arkadaşlarını davet et: kodun ve bağlantınla yeni Davet sayfası. 90 gün boyunca arkadaşlarının her bahsinden kasa payının %20'si mağaza $'ı olarak senin; onlar ilk maçtan sonra hoş geldin çantası, sen de 5 maç bitirdiklerinde bonus çanta alırsın", "Adil oyun: bir insan için fazla kusursuz nişan hesabı incelemeye alır ve çekimleri durdurur; bir kişi, bahisli masada bir koltuk; aynı ağdan yeni hesap ve davetlere sınır", "Kararlılık: oyun durumu güvenle kaydedilir, yavaş bağlantılar gecikme yerine eski kareleri atlar"],
      zh: ["邀请好友：新增「邀请」页面，含你的邀请码和链接。90 天内好友每次下注，庄家抽成的 20% 以商店余额归你；好友首场比赛后获得欢迎袋，完成 5 场时你获得奖励袋", "公平竞技：对人类而言过于完美的瞄准会使账号进入审核并冻结提现；一人在下注桌只占一个座位；限制同一网络的新账号和邀请数量", "稳定性：游戏状态安全写入磁盘，慢速连接会丢弃旧帧而不是卡顿"],
      hi: ["दोस्तों को बुलाएँ: आपके कोड और लिंक के साथ नया आमंत्रण पेज। 90 दिन तक दोस्तों के हर दाँव पर हाउस के हिस्से का 20% दुकान $ में; उन्हें पहले मैच के बाद स्वागत बैग, और 5 मैच पूरे होने पर आपको बोनस बैग", "निष्पक्ष खेल: इंसान के लिए बहुत परफ़ेक्ट निशाना खाते को जाँच में डालता है और निकासी रोकता है; दाँव वाली टेबल पर एक व्यक्ति, एक सीट; एक नेटवर्क से नए खातों और आमंत्रणों पर सीमा", "स्थिरता: गेम की स्थिति सुरक्षित सेव होती है, धीमे कनेक्शन पर पुराने फ़्रेम छोड़े जाते हैं"],
      ar: ["ادعُ أصدقاءك: صفحة دعوة جديدة برمزك ورابطك. لمدة 90 يومًا تحصل على 20% من حصة المنزل من كل رهان لأصدقائك كرصيد متجر؛ ويحصلون على حقيبة ترحيب بعد أول مباراة، وأنت على حقيبة إضافية عندما يُنهون 5", "اللعب النظيف: التصويب المثالي أكثر من اللازم لإنسان يضع الحساب قيد المراجعة ويوقف السحب؛ شخص واحد ومقعد واحد في طاولة الرهان؛ حدود للحسابات الجديدة والدعوات من الشبكة نفسها", "الاستقرار: تُحفظ حالة اللعبة بأمان، والاتصالات البطيئة تتخطى الإطارات القديمة بدل التأخر"],
    },
  },
  {
    id: '2026-10-03a',
    at: '2026-10-03T12:00:00+03:00',
    items: {
      en: ["Teams and ranked: pick your weapon before the match; best of three rounds on a clock", "Shots: tracers fly exactly to where the damage lands; ranges by class, the pistol shortest, the snipers furthest", "Melee: the swing is drawn exactly where it hits; katanas, machetes, axes, scythes and energy swords reach further than a knife", "Zombies: 20 waves (bosses on 10 and 20), no clock, every wave harder; kills pay credits for turrets, laser mines and medkits", "The game server moves to Europe for a lower ping"],
      uk: ["Командні та рейтингові: вибір зброї перед матчем; бій до двох перемог у раундах за таймером", "Постріли: трасер летить рівно туди, де зараховується шкода; дальність за класом, пістолет найближче, снайперки найдалі", "Ближній бій: замах малюється там, де б'є; катани, мачете, сокири, коси й енергомечі дістають далі за ніж", "Зомбі: 20 хвиль (боси на 10-й і 20-й), без таймера, кожна хвиля складніша; за вбивства кредити на турелі, лазерні міни й аптечки", "Ігровий сервер переїжджає в Європу заради нижчого пінгу"],
      ru: ["Командные и рейтинговые: выбор оружия перед матчем; бой до двух побед в раундах по таймеру", "Выстрелы: трассер летит ровно туда, где засчитывается урон; дальность по классу, пистолет ближе всех, снайперки дальше всех", "Ближний бой: замах рисуется там, где бьёт; катаны, мачете, топоры, косы и энергомечи достают дальше ножа", "Зомби: 20 волн (боссы на 10-й и 20-й), без таймера, каждая волна сложнее; за убийства кредиты на турели, лазерные мины и аптечки", "Игровой сервер переезжает в Европу ради меньшего пинга"],
      es: ["Equipos y clasificatoria: elige arma antes de la partida; al mejor de tres rondas con reloj", "Disparos: el trazador llega justo donde cae el daño; alcance por clase", "Cuerpo a cuerpo: el tajo se dibuja donde golpea; katanas y machetes llegan más lejos", "Zombis: 20 oleadas, sin reloj, créditos por bajas para torretas, minas láser y botiquines", "El servidor se muda a Europa para menos ping"],
      fr: ["Équipes et classé : choix de l'arme avant le match ; deux manches gagnantes sur trois, chronométrées", "Tirs : le traceur va exactement là où tombent les dégâts ; portée selon la classe", "Corps à corps : le coup est dessiné là où il frappe ; katanas et machettes portent plus loin", "Zombies : 20 vagues, sans chrono, crédits par élimination pour tourelles, mines laser et trousses", "Le serveur passe en Europe pour un meilleur ping"],
      pt: ["Equipes e ranqueada: escolha a arma antes da partida; melhor de três rodadas com relógio", "Tiros: o traçante vai exatamente onde o dano acontece; alcance por classe", "Corpo a corpo: o golpe é desenhado onde acerta; katanas e facões alcançam mais", "Zumbis: 20 ondas, sem relógio, créditos por abate para torretas, minas laser e kits", "O servidor vai para a Europa para menos ping"],
      tr: ["Takım ve dereceli: maçtan önce silah seçimi; süreli üç rauntta iki galibiyet", "Atışlar: iz mermisi hasarın olduğu yere gider; menzil sınıfa göre", "Yakın dövüş: savuruş vurduğu yerde çizilir; katana ve palalar daha uzağa erişir", "Zombiler: 20 dalga, süre yok, öldürme başına taret, lazer mayın ve ilk yardım kredisi", "Sunucu daha düşük ping için Avrupa'ya taşınıyor"],
      zh: ["团队与排位：赛前选武器；限时三局两胜", "射击：弹道正好飞到造成伤害的位置；射程按类别", "近战：挥砍画在命中范围上；武士刀、砍刀攻击距离更远", "僵尸：20 波，不限时，击杀获得点数购买炮塔、激光地雷、医疗包", "游戏服务器迁至欧洲以降低延迟"],
      hi: ["टीम और रैंक्ड: मैच से पहले हथियार चुनें; घड़ी पर तीन में से दो राउंड", "गोलियाँ: ट्रेसर ठीक वहीं जाता है जहाँ नुकसान होता है; रेंज क्लास के हिसाब से", "हाथापाई: वार वहीं दिखता है जहाँ लगता है; कटाना और छुरे ज़्यादा दूर तक", "ज़ॉम्बी: 20 लहरें, कोई घड़ी नहीं, किल पर टरेट, लेज़र माइन, मेडकिट के क्रेडिट", "कम पिंग के लिए सर्वर यूरोप में"],
      ar: ["الفرق والتصنيف: اختيار السلاح قبل المباراة؛ أفضل جولتين من ثلاث بمؤقت", "الطلقات: يصل الأثر تمامًا إلى حيث يقع الضرر؛ المدى حسب الفئة", "الاشتباك: تُرسم الضربة حيث تصيب؛ الكاتانا والمناجل تصل أبعد", "الزومبي: 20 موجة بلا مؤقت، والقتل يمنح رصيدًا للأبراج والألغام وحقائب الإسعاف", "الخادم ينتقل إلى أوروبا لتقليل التأخير"],
    },
  },
  {
    id: '2026-10-02d',
    at: '2026-10-02T18:30:00+03:00',
    items: {
      en: ["New mode: Zombies ($0.10). Alone or with up to 3 friends, hold the graveyard against 10 waves of the dead coming from every side, each wave stronger, and a boss on the last. Pick your weapon in the ready room. The time is limited (8 minutes). The further you get, the more XP; clearing it earns titles", "New mode: Gold Rush ($0.10). A quarry map, bags of gold dropping everywhere, random weapons, quick respawns. Grab the most bags in 2:30: only the one winner takes the whole pot as shop credit", "15 new achievements for both modes, among them the titles Zombie Slayer, Top of the Horde, Army of One and Midas"],
      uk: ["Новий режим: Зомбі ($0.10). Сам або з друзями (до 4 гравців) утримуйте цвинтар проти 10 хвиль мерців з усіх боків. Кожна хвиля сильніша, в останній з'являється бос. Зброю обираєте в кімнаті очікування. Час обмежений (8 хвилин). Що далі пройдете, то більше досвіду, а за проходження дають титули", "Новий режим: Золота лихоманка ($0.10). Кар'єр, сумки із золотом падають усюди, зброя випадкова, швидке відродження. Зберіть найбільше сумок за 2:30: тільки один переможець забирає весь банк доларами на покупки в магазині", "15 нових досягнень для обох режимів, серед них титули «Винищувач зомбі», «Перший серед орди», «Армія з одного» та «Мідас»"],
      ru: ["Новый режим: Зомби ($0.10). Один или с друзьями (до 4 игроков) удерживайте кладбище против 10 волн мертвецов со всех сторон. Каждая волна сильнее, в последней появляется босс. Оружие выбираете в комнате ожидания. Время ограничено (8 минут). Чем дальше пройдёте, тем больше опыта, а за прохождение дают титулы", "Новый режим: Золотая лихорадка ($0.10). Карьер, мешки с золотом падают повсюду, оружие случайное, быстрое возрождение. Соберите больше всех мешков за 2:30: только один победитель забирает весь банк долларами на покупки в магазине", "15 новых достижений для обоих режимов, среди них титулы «Истребитель зомби», «Первый среди орды», «Армия из одного» и «Мидас»"],
      es: ["Modo nuevo: Zombis ($0.10). Solo o con hasta 3 amigos, defiende el cementerio de 10 oleadas de muertos que llegan por todos lados, cada una más fuerte, con un jefe en la última. Elige tu arma en la sala. El tiempo es limitado (8 minutos). Cuanto más lejos llegues, más XP; completarlo da títulos", "Modo nuevo: Fiebre del oro ($0.10). Una cantera, bolsas de oro cayendo por todas partes, armas al azar, reaparición rápida. Consigue más bolsas en 2:30: solo el ganador se lleva todo el bote como crédito de tienda", "15 logros nuevos para ambos modos, entre ellos los títulos Cazazombis, Cima de la horda, Ejército de uno y Midas"],
      fr: ["Nouveau mode : Zombies (0,10 $). Seul ou avec jusqu'à 3 amis, tiens le cimetière face à 10 vagues de morts venues de partout, chacune plus forte, avec un boss à la dernière. Choisis ton arme dans la salle. Le temps est limité (8 minutes). Plus tu vas loin, plus tu gagnes d'XP ; finir donne des titres", "Nouveau mode : Ruée vers l'or (0,10 $). Une carrière, des sacs d'or qui tombent partout, armes au hasard, réapparition rapide. Ramasse le plus de sacs en 2:30 : seul le vainqueur rafle tout le pot en crédit boutique", "15 nouveaux succès pour les deux modes, dont les titres Tueur de zombies, Tête de la horde, Armée à moi seul et Midas"],
      pt: ["Modo novo: Zumbis ($0.10). Sozinho ou com até 3 amigos, segure o cemitério contra 10 ondas de mortos vindo de todos os lados, cada uma mais forte, com um chefe na última. Escolha sua arma na sala. O tempo é limitado (8 minutos). Quanto mais longe, mais XP; completar dá títulos", "Modo novo: Corrida do ouro ($0.10). Uma pedreira, sacos de ouro caindo por toda parte, armas aleatórias, renascimento rápido. Pegue mais sacos em 2:30: só o vencedor leva o pote todo como crédito na loja", "15 conquistas novas para os dois modos, entre elas os títulos Matador de zumbis, Topo da horda, Exército de um e Midas"],
      tr: ["Yeni mod: Zombiler (0,10 $). Tek başına ya da en fazla 3 arkadaşla mezarlığı her yönden gelen 10 ölü dalgasına karşı tut; her dalga daha güçlü, sonuncusunda bir boss var. Silahını bekleme odasında seç. Süre sınırlı (8 dakika). Ne kadar ilerlersen o kadar XP; bitirmek unvan kazandırır", "Yeni mod: Altın Hücumu (0,10 $). Bir taş ocağı, her yere düşen altın torbaları, rastgele silahlar, hızlı yeniden doğma. 2:30'da en çok torbayı topla: tüm potu mağaza kredisi olarak yalnızca tek kazanan alır", "İki mod için 15 yeni başarım; aralarında Zombi Avcısı, Ordunun Zirvesi, Tek Kişilik Ordu ve Midas unvanları"],
      zh: ["新模式：僵尸（$0.10）。单人或与最多 3 位好友一起，在墓地抵御从四面八方涌来的 10 波亡灵，每波更强，最后一波有首领。在准备室选择武器。时间有限（8 分钟）。坚持得越久经验越多，通关可获得称号", "新模式：淘金热（$0.10）。采石场地图，金袋随处掉落，武器随机，快速重生。在 2:30 内捡到最多金袋：只有唯一的赢家拿走全部奖池，作为商店余额", "两个模式共 15 个新成就，包括称号「僵尸杀手」「尸群之首」「一人成军」和「点金王」"],
      hi: ["नया मोड: ज़ॉम्बी ($0.10)। अकेले या 3 दोस्तों तक के साथ, हर तरफ़ से आती मुर्दों की 10 लहरों से कब्रिस्तान बचाएँ, हर लहर ज़्यादा ताक़तवर, आख़िरी में बॉस। हथियार तैयारी कक्ष में चुनें। समय सीमित है (8 मिनट)। जितना आगे जाएँगे उतना XP; पूरा करने पर टाइटल", "नया मोड: गोल्ड रश ($0.10)। खदान का नक्शा, हर जगह गिरते सोने के थैले, रैंडम हथियार, तेज़ रीस्पॉन। 2:30 में सबसे ज़्यादा थैले उठाएँ: सिर्फ़ एक विजेता पूरा पॉट दुकान क्रेडिट के रूप में लेता है", "दोनों मोड के लिए 15 नई उपलब्धियाँ, जिनमें ज़ॉम्बी स्लेयर, झुंड का सरताज, अकेली सेना और मिडास टाइटल शामिल हैं"],
      ar: ["وضع جديد: الزومبي (0.10 $). وحدك أو مع حتى 3 أصدقاء، احمِ المقبرة من 10 موجات من الموتى قادمة من كل الجهات، كل موجة أقوى، وزعيم في الأخيرة. اختر سلاحك في غرفة الانتظار. الوقت محدود (8 دقائق). كلما تقدمت زادت الخبرة؛ وإتمامه يمنح ألقابًا", "وضع جديد: حمى الذهب (0.10 $). محجر وأكياس ذهب تتساقط في كل مكان وأسلحة عشوائية وعودة سريعة. اجمع أكثر الأكياس في 2:30: فائز واحد فقط يأخذ الوعاء كله رصيدًا للمتجر", "15 إنجازًا جديدًا للوضعين، منها ألقاب قاتل الزومبي وقمة الحشد وجيش من رجل واحد وميداس"],
    },
  },
  {
    id: '2026-10-02c',
    at: '2026-10-02T13:59:00+03:00',
    items: {
      en: ["Titles now have tiers, from plain to rare, epic, legendary (gold), mythic (rainbow aura) and mystery (secret, violet smoke): over your name in matches, in chat, friends, the ready room and on your player card", "32 new achievements: weapon mastery, deathmatch, duels, teams, hardcore, one-weapon wins, turrets, ranked leagues, cases, skins, the battle pass, season titles, and 4 secret ones"],
      uk: ["Титули тепер мають рівні: звичайний, рідкісний, епічний, легендарний (золото), міфічний (райдужна аура) і таємничий (секретні, фіолетовий дим) — над ніком у матчі, у чаті, друзях, кімнаті очікування та на картці гравця", "32 нові досягнення: майстерність зброї, бій на смерть, дуелі, команди, хардкор, перемоги з однією зброєю, турелі, рейтингові ліги, кейси, скіни, бойовий пропуск, сезонні титули і 4 таємні"],
      ru: ["У титулов теперь есть уровни: обычный, редкий, эпический, легендарный (золото), мифический (радужная аура) и таинственный (секретные, фиолетовый дым) — над ником в матче, в чате, друзьях, комнате ожидания и на карточке игрока", "32 новых достижения: мастерство оружия, бой насмерть, дуэли, команды, хардкор, победы с одним оружием, турели, рейтинговые лиги, кейсы, скины, боевой пропуск, сезонные титулы и 4 тайных"],
      es: ["Los títulos tienen niveles: común, raro, épico, legendario (oro), mítico (aura arcoíris) y misterio (secretos, humo violeta), sobre tu nombre, en el chat, amigos, la sala y tu tarjeta", "32 logros nuevos: maestría de armas, todos contra todos, duelos, equipos, hardcore, un arma, torretas, ligas clasificatorias, cajas, skins, pase, títulos de temporada y 4 secretos"],
      fr: ["Les titres ont des niveaux : commun, rare, épique, légendaire (or), mythique (aura arc-en-ciel) et mystère (secrets, fumée violette), au-dessus de ton nom, dans le chat, les amis, la salle et ta carte", "32 nouveaux succès : maîtrise des armes, deathmatch, duels, équipes, hardcore, une arme, tourelles, ligues classées, caisses, skins, passe, titres de saison et 4 secrets"],
      pt: ["Os títulos têm níveis: comum, raro, épico, lendário (ouro), mítico (aura arco-íris) e mistério (secretos, fumaça violeta), acima do seu nome, no chat, amigos, sala e no seu cartão", "32 conquistas novas: domínio de armas, mata-mata, duelos, equipes, hardcore, uma arma, torretas, ligas ranqueadas, caixas, skins, passe, títulos da temporada e 4 secretas"],
      tr: ["Unvanların artık seviyeleri var: sıradan, nadir, epik, efsanevi (altın), mitik (gökkuşağı aurası) ve gizem (gizli, mor duman); maçta adının üstünde, sohbette, arkadaşlarda, bekleme odasında ve oyuncu kartında", "32 yeni başarım: silah ustalığı, ölüm maçı, düellolar, takımlar, hardcore, tek silah, taretler, dereceli ligler, kasalar, görünümler, savaş bileti, sezon unvanları ve 4 gizli"],
      zh: ["称号现在有等级：普通、稀有、史诗、传说（金色）、神话（彩虹光环）和神秘（隐藏、紫色烟雾），显示在比赛中名字上方、聊天、好友、准备室和玩家卡片上", "32 个新成就：武器精通、死斗、决斗、团队、硬核、单武器、炮塔、排位联赛、箱子、皮肤、通行证、赛季称号，以及 4 个隐藏成就"],
      hi: ["टाइटल के अब स्तर हैं: सामान्य, दुर्लभ, एपिक, लीजेंडरी (सोना), मिथिक (इंद्रधनुषी आभा) और रहस्य (गुप्त, बैंगनी धुआँ) — मैच में नाम के ऊपर, चैट, दोस्तों, रेडी रूम और प्लेयर कार्ड पर", "32 नई उपलब्धियाँ: हथियार महारत, डेथमैच, द्वंद्व, टीमें, हार्डकोर, एक-हथियार, टर्रेट, रैंक्ड लीग, केस, स्किन, बैटल पास, सीज़न टाइटल और 4 गुप्त"],
      ar: ["للألقاب الآن مستويات: عادي، نادر، ملحمي، أسطوري (ذهبي)، خرافي (هالة قوس قزح) وغامض (سرية، دخان بنفسجي) — فوق اسمك في المباراة، في الدردشة، الأصدقاء، غرفة الاستعداد وبطاقة اللاعب", "32 إنجازاً جديداً: إتقان الأسلحة، القتال حتى الموت، المبارزات، الفرق، هاردكور، السلاح الواحد، الأبراج، دوريات المصنّفة، الصناديق، الأشكال، التذكرة، ألقاب الموسم و4 إنجازات سرية"],
    },
  },
  {
    id: '2026-10-02b',
    at: '2026-10-02T13:45:00+03:00',
    items: {
      en: ['Locker: tap your runner to see only what you own, filter and sort by rarity, preview and equip (outfits, weapon skins, turret skins)', 'Health no longer comes back by itself in a match: only Guns + Lasers medkits heal', 'Every enemy still standing shows on the minimap (teammates in green)', 'Enemy names and red health bars in every mode', 'Friends: browse everyone who has ever played (show more), invite players into your guild', 'Smoother menus: the live map behind windows pauses while they are open', 'Stakes: a $100 table, and type your own from $0.10 to $10,000', 'Share cards show your name', "What's new: these notes open after every update (also in Settings)"],
      uk: ['Шафка: натисни на персонажа — лише твої речі, фільтр і сортування за рідкістю, приміряти й екіпірувати (образи, скіни зброї, скіни турелей)', 'Здоров’я в матчі більше не відновлюється само: лікують лише аптечки в «Гармати + Лазери»', 'Усі живі вороги на міні-карті (союзники зеленим)', 'Ніки ворогів і червоні шкали здоров’я в усіх режимах', 'Друзі: усі гравці, які хоч раз грали («Показати ще»), запрошення в гільдію', 'Плавніші меню: жива карта за вікнами стає на паузу, поки вони відкриті', 'Ставки: стіл $100 і своя сума від $0.10 до $10 000', 'На картках «Поділитися» видно твій нік', '«Що нового»: ці нотатки відкриваються після кожного оновлення (також у Налаштуваннях)'],
      ru: ['Шкафчик: нажми на персонажа — только твои вещи, фильтр и сортировка по редкости, примерить и экипировать (образы, скины оружия, скины турелей)', 'Здоровье в матче больше не восстанавливается само: лечат только аптечки в «Пушки + Лазеры»', 'Все живые враги на мини-карте (союзники зелёным)', 'Ники врагов и красные полоски здоровья во всех режимах', 'Друзья: все игроки, кто хоть раз играл («Показать ещё»), приглашения в гильдию', 'Плавнее меню: живая карта за окнами на паузе, пока они открыты', 'Ставки: стол $100 и своя сумма от $0.10 до $10 000', 'На карточках «Поделиться» виден твой ник', '«Что нового»: эти заметки открываются после каждого обновления (также в Настройках)'],
      es: ['Taquilla: toca tu corredor para ver solo lo tuyo, filtra y ordena por rareza, prueba y equipa (atuendos, skins de arma y de torreta)', 'La salud ya no se recupera sola en partida: solo curan los botiquines de Armas + Láseres', 'Todos los enemigos vivos aparecen en el minimapa (aliados en verde)', 'Nombres de enemigos y barras de vida rojas en todos los modos', 'Amigos: todos los que han jugado alguna vez (mostrar más), invita jugadores a tu gremio', 'Menús más fluidos: el mapa en vivo detrás de las ventanas se pausa', 'Apuestas: mesa de $100 y tu propia cantidad de $0.10 a $10.000', 'Las tarjetas para compartir muestran tu nombre', 'Novedades: estas notas se abren tras cada actualización (también en Ajustes)'],
      fr: ['Casier : touche ton coureur pour ne voir que tes objets, filtre et trie par rareté, essaie et équipe (tenues, skins d’arme et de tourelle)', 'La santé ne revient plus seule en match : seuls les médikits de Armes + Lasers soignent', 'Tous les ennemis encore debout sur la mini-carte (alliés en vert)', 'Noms des ennemis et barres de vie rouges dans tous les modes', 'Amis : tous ceux qui ont déjà joué (voir plus), invite des joueurs dans ta guilde', 'Menus plus fluides : la carte en direct derrière les fenêtres se met en pause', 'Mises : une table à 100 $ et ton propre montant de 0,10 $ à 10 000 $', 'Les cartes à partager affichent ton pseudo', "Nouveautés : ces notes s'ouvrent après chaque mise à jour (aussi dans Réglages)"],
      pt: ['Armário: toque no seu corredor para ver só o que é seu, filtre e ordene por raridade, prove e equipe (roupas, skins de arma e de torreta)', 'A vida não volta mais sozinha na partida: só os kits médicos de Armas + Lasers curam', 'Todos os inimigos vivos aparecem no minimapa (aliados em verde)', 'Nomes de inimigos e barras de vida vermelhas em todos os modos', 'Amigos: todos que já jogaram (mostrar mais), convide jogadores para sua guilda', 'Menus mais suaves: o mapa ao vivo atrás das janelas pausa enquanto estão abertas', 'Apostas: mesa de $100 e seu próprio valor de $0,10 a $10.000', 'Os cartões de compartilhar mostram seu nome', 'Novidades: estas notas abrem após cada atualização (também em Ajustes)'],
      tr: ['Dolap: koşucuna dokun, yalnızca senin eşyaların; nadirliğe göre filtrele ve sırala, dene ve kuşan (kıyafetler, silah ve taret görünümleri)', 'Can artık maçta kendiliğinden dolmuyor: yalnızca Silahlar + Lazerler medkitleri iyileştirir', 'Ayakta kalan tüm düşmanlar mini haritada (takım arkadaşları yeşil)', 'Tüm modlarda düşman isimleri ve kırmızı can çubukları', 'Arkadaşlar: bir kez bile oynamış herkes (daha fazla), oyuncuları loncana davet et', 'Daha akıcı menüler: pencereler açıkken arkadaki canlı harita durur', 'Bahisler: $100 masası ve $0.10–$10.000 arası kendi tutarın', 'Paylaşım kartlarında adın görünür', 'Yenilikler: bu notlar her güncellemeden sonra açılır (Ayarlar’da da)'],
      zh: ['储物柜：点击角色只看你拥有的物品，按稀有度筛选和排序，试穿并装备（服装、武器皮肤、炮塔皮肤）', '比赛中生命不再自动恢复：只有「枪械+激光」的医疗包能治疗', '所有存活的敌人显示在小地图上（队友为绿色）', '所有模式中显示敌人名字和红色血条', '好友：浏览所有玩过的玩家（显示更多），邀请玩家加入你的公会', '菜单更流畅：窗口打开时后方的实时地图暂停', '赌注：新增 $100 桌，并可自填 $0.10 至 $10,000', '分享卡片显示你的昵称', '更新内容：每次更新后自动打开（也可在设置中查看）'],
      hi: ['लॉकर: अपने रनर पर टैप करो — सिर्फ़ तुम्हारी चीज़ें, दुर्लभता से फ़िल्टर और सॉर्ट, देखो और पहनो (आउटफ़िट, हथियार और टर्रेट स्किन)', 'मैच में हेल्थ अब अपने-आप वापस नहीं आती: सिर्फ़ गन्स + लेज़र्स के मेडकिट ठीक करते हैं', 'ज़िंदा सभी दुश्मन मिनी-मैप पर (साथी हरे)', 'हर मोड में दुश्मनों के नाम और लाल हेल्थ बार', 'दोस्त: जिसने भी कभी खेला सब (और दिखाओ), खिलाड़ियों को अपनी गिल्ड में बुलाओ', 'स्मूद मेन्यू: विंडो खुली रहने पर पीछे का लाइव मैप रुक जाता है', 'दांव: $100 टेबल, और $0.10 से $10,000 तक अपना दांव लिखो', 'शेयर कार्ड पर तुम्हारा नाम दिखता है', 'नया क्या है: ये नोट हर अपडेट के बाद खुलते हैं (सेटिंग्स में भी)'],
      ar: ['الخزانة: المس عدّاءك لترى ما تملكه فقط، صفِّ ورتّب حسب الندرة، جرّب وجهّز (أزياء، أشكال أسلحة وأبراج)', 'الصحة لم تعد تعود وحدها أثناء المباراة: فقط حقائب الإسعاف في الأسلحة + الليزر تعالج', 'كل الأعداء الأحياء على الخريطة المصغرة (الحلفاء بالأخضر)', 'أسماء الأعداء وأشرطة صحة حمراء في كل الأوضاع', 'الأصدقاء: كل من لعب ولو مرة (عرض المزيد)، وادعُ لاعبين إلى نقابتك', 'قوائم أسلس: الخريطة الحية خلف النوافذ تتوقف أثناء فتحها', 'الرهانات: طاولة 100$ ورهانك الخاص من 0.10$ إلى 10,000$', 'بطاقات المشاركة تعرض اسمك', 'الجديد: تُفتح هذه الملاحظات بعد كل تحديث (وفي الإعدادات أيضاً)'],
    },
  },
  {
    id: '2026-10-02a',
    at: '2026-10-02T01:22:00+03:00',
    items: {
      en: ['Ranked battles: a season rating from Bronze to Neon Legend, a bonus spin, neon season titles with bonus XP, and a leaderboard', 'Battle pass: monthly seasons with armour sets, seasonal weapon and turret skins', '18 new cases and a CS-style opening reel; a full-screen show for every new rank', '7 new guns with magazines and automatic reload; red and green team colours', '7 new music tracks'],
      uk: ['Рейтингові бої: сезонний рейтинг від Бронзи до Неонової легенди, бонусна рулетка, неонові сезонні титули з бонусом XP і таблиця лідерів', 'Бойовий пропуск: щомісячні сезони з бронею, сезонними скінами зброї та турелей', '18 нових кейсів і прокрутка відкриття як у CS; повноекранне вітання з кожним новим рангом', '7 нових стволів із магазинами й автоматичною перезарядкою; червоні й зелені кольори команд', '7 нових музичних треків'],
      ru: ['Рейтинговые бои: сезонный рейтинг от Бронзы до Неоновой легенды, бонусная рулетка, неоновые сезонные титулы с бонусом XP и таблица лидеров', 'Боевой пропуск: ежемесячные сезоны с бронёй, сезонными скинами оружия и турелей', '18 новых кейсов и прокрутка открытия как в CS; полноэкранное поздравление с каждым новым рангом', '7 новых стволов с магазинами и автоматической перезарядкой; красные и зелёные цвета команд', '7 новых музыкальных треков'],
      es: ['Clasificatorias: rango de temporada de Bronce a Leyenda Neón, giro extra, títulos neón con XP extra y tabla de líderes', 'Pase de batalla: temporadas mensuales con armaduras y skins de arma y torreta', '18 cajas nuevas y ruleta de apertura estilo CS; pantalla completa con cada nuevo rango', '7 armas nuevas con cargadores y recarga automática; colores de equipo rojo y verde', '7 temas musicales nuevos'],
      fr: ['Classé : classement de saison de Bronze à Légende Néon, tirage bonus, titres néon avec XP bonus et classement', 'Passe de combat : saisons mensuelles avec armures, skins d’arme et de tourelle', '18 nouvelles caisses et une roulette d’ouverture façon CS ; un écran plein pour chaque nouveau grade', '7 nouvelles armes avec chargeurs et rechargement automatique ; couleurs d’équipe rouge et vert', '7 nouveaux morceaux'],
      pt: ['Ranqueadas: classificação da temporada do Bronze à Lenda Neon, giro bônus, títulos neon com XP extra e ranking', 'Passe de batalha: temporadas mensais com armaduras, skins de arma e torreta', '18 caixas novas e roleta de abertura estilo CS; tela cheia a cada nova patente', '7 armas novas com carregadores e recarga automática; cores de equipe vermelho e verde', '7 músicas novas'],
      tr: ['Dereceli: Bronzdan Neon Efsane’ye sezon puanı, bonus çark, XP bonuslu neon unvanlar ve lider tablosu', 'Savaş bileti: zırh setli, sezonluk silah ve taret görünümlü aylık sezonlar', '18 yeni kasa ve CS tarzı açılış çarkı; her yeni rütbe için tam ekran gösteri', 'Şarjörlü ve otomatik doldurmalı 7 yeni silah; kırmızı ve yeşil takım renkleri', '7 yeni müzik parçası'],
      zh: ['排位赛：从青铜到霓虹传奇的赛季积分、额外转盘、带经验加成的霓虹赛季称号与排行榜', '战斗通行证：每月赛季，含护甲套装、赛季武器与炮塔皮肤', '18 个新箱子与 CS 风格开箱转盘；每次升衔全屏庆祝', '7 把带弹匣和自动换弹的新枪；红绿队伍配色', '7 首新音乐'],
      hi: ['रैंक्ड: ब्रॉन्ज़ से नियॉन लीजेंड तक सीज़न रेटिंग, बोनस स्पिन, बोनस XP वाले नियॉन टाइटल और लीडरबोर्ड', 'बैटल पास: कवच सेट, सीज़नल हथियार और टर्रेट स्किन वाले मासिक सीज़न', '18 नए केस और CS जैसा ओपनिंग रील; हर नई रैंक पर फ़ुल-स्क्रीन जश्न', 'मैगज़ीन और ऑटो रीलोड वाली 7 नई बंदूकें; लाल और हरे टीम रंग', '7 नए म्यूज़िक ट्रैक'],
      ar: ['المصنّفة: تصنيف موسمي من البرونز إلى أسطورة النيون، دورة إضافية، ألقاب نيون بخبرة إضافية، وجدول متصدرين', 'تذكرة المعركة: مواسم شهرية بدروع وأشكال أسلحة وأبراج موسمية', '18 صندوقاً جديداً وعجلة فتح على طريقة CS؛ احتفال بملء الشاشة لكل رتبة جديدة', '7 أسلحة جديدة بمخازن وإعادة تلقيم تلقائية؛ ألوان فرق حمراء وخضراء', '7 مقطوعات موسيقية جديدة'],
    },
  },
];

export function createNews() {
  function render() {
    const lang = getLang();
    const fmt = (iso) => new Date(iso).toLocaleString(lang, { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' });
    $('news-body').innerHTML = NEWS.map((n, i) => `<article class="news-item${i === 0 ? ' latest' : ''}"><time datetime="${n.at}">${esc(fmt(n.at))}</time><ul>${(n.items[lang] ?? n.items.en).map((x) => `<li>${esc(x)}</li>`).join('')}</ul></article>`).join('');
  }
  function open() {
    render();
    $('dlg-news').showModal();
    store.set(SEEN, NEWS[0].id);
  }
  // after an update: once, as the player comes in
  function maybeShow() {
    if (store.get(SEEN, null) !== NEWS[0].id) setTimeout(open, 500);
  }
  const markSeen = () => store.set(SEEN, NEWS[0].id);
  $('news-ok').addEventListener('click', () => $('dlg-news').close());
  return { open, maybeShow, markSeen };
}
