export default {
  'lobby.tagline': 'راهن. انهب. اخرج قبل العاصفة. <b>لا أحد يرى ما في حقيبتك.</b>',
  'lobby.namePh': 'اسم عدّائك',
  'lobby.locker': 'الخزانة · الأزياء · الحقائب',
  'lobby.refill': 'إعادة تعبئة عملات الاختبار',
  'lobby.online': 'أونلاين',
  'lobby.practice': 'تدريب ضد البوتات',
  'lobby.stakePer': 'الرهان لكل غارة',
  'lobby.stakeWith': 'راهن بـ <span class="fine">أي عملة · معروضة بالدولار · الأرباح تعود بالعملة نفسها</span>',
  'lobby.play': 'العب · رهان {s}',
  'lobby.signIn': 'سجّل الدخول للعب',
  'lobby.how': 'طريقة اللعب',
  'lobby.gore': '<b>وضع +18.</b> الأطراف تتطاير والدماء تبقى على الأرض.',
  'lobby.fine': 'التدريب يعمل في متصفحك. كل الأموال هنا أموال لعب.',
  'how.1': '<b>راهن واستعد.</b> الجميع يدخلون معًا بسكين و100 نقطة صحة. نصف رهانك في حقيبتك، والنصف الآخر منثور كغنائم.',
  'how.2': '<b>التقط الغنائم البرتقالية.</b> تذهب إلى حقيبتك. القتل يطوّر سلاحك: سكين ← مسدس ← بندقية خرطوش ← رشاش ← بندقية ← قناص ليزر.',
  'how.3': '<b>اخرج حيًا.</b> قف في مخرج أخضر 3 ثوانٍ قبل أن تغلقه العاصفة. الحقيبة كلها لك. إن مت، تسقط لغيرك.',
  'how.keys': '<kbd>WASD</kbd> حركة · <kbd>الفأرة</kbd> تصويب · <kbd>نقرة</kbd> هجوم · <kbd>Space</kbd> اندفاع · <kbd>Q</kbd> تمويه حجم الحقيبة · <kbd>M</kbd> الصوت · <kbd>N</kbd> الموسيقى',
  'how.fine': 'كل غارة وكل إنجاز يمنحان خبرة رتبة. كل ترقية تعيرك زيًا جديدًا لمدة 3 أيام.',
  'net.practice': 'أنت والبوتات فقط، دون اتصال.',
  'net.open': 'متصل. البشر والبوتات في الغارة نفسها.',
  'net.connecting': 'جارٍ الاتصال بالخادم…',
  'net.down': 'الخادم غير متاح. إعادة المحاولة… التدريب يعمل دون اتصال.',
  'net.lost': 'انقطع الاتصال. العودة إلى الطاولات.',
  'q.pick': 'اختر عملة للرهان.',
  'q.short': 'لا يكفي {c} لرهان {s}. اختر عملة أخرى أو رهانًا أصغر.',
  'q.shortDeposit': 'لا يكفي {c} لرهان {s}. اختر عملة أخرى أو رهانًا أصغر أو أودِع.',
  'q.stable': 'تراهن بـ {s} من {c}. اخرج حيًا واحتفظ بكل ما تحمله.',
  'q.coin': 'تراهن بـ {a} = {s} بسعر اليوم. الأرباح تعود بـ {c} بالسعر نفسه.',
  'tb.live': 'غارة جارية · {t}',
  'tb.ready': '{n} جاهزون · {s}ث',
  'tb.waiting': '{n} ينتظرون',
  'tb.golden': 'التالية: غارة ذهبية',
  'tb.jackpot': 'الجائزة الكبرى {v}',
  'pcfg.title': 'إعدادات التدريب',
  'pcfg.difficulty': 'البوتات',
  'pcfg.easy': 'سهل',
  'pcfg.normal': 'عادي',
  'pcfg.hard': 'صعب',
  'pcfg.runners': 'العدّاؤون في الغارة',
  'pcfg.time': 'مدة الغارة',
  'rk.max': 'أعلى رتبة',
  'rk.toNext': '{x} خبرة للرتبة {r}',
  'rk.of': 'الرتبة {r} من 90',
  'rk.rank': 'الرتبة',
  'rk.up': 'ترقية',
  'rk.xp': 'خبرة الرتبة',
  'xp.Raid': 'غارة',
  'xp.kills': '{n} قتلى',
  'xp.Damage': 'الضرر',
  'xp.Time alive': 'وقت البقاء',
  'xp.First blood': 'الدم الأول',
  'xp.Double kill': 'قتل مزدوج',
  'xp.Triple kill': 'قتل ثلاثي',
  'xp.Rampage': 'هيجان',
  'xp.Godlike': 'أسطوري',
  'xp.Full arsenal': 'ترسانة كاملة',
  'xp.Extracted': 'إجلاء',
  'xp.Profit': 'ربح',
  'xp.Practice ×0.5': 'تدريب ×0.5',
  'rw.title': 'مكافأة الترقية',
  'rw.trial': 'لك لمدة 72 ساعة',
  'rw.try': 'جرّبه',
  'rw.share': 'شارك الترقية',
  'prep.raid': 'الغارة {n} · رهان {s}',
  'prep.readyUp': 'جاهز؟',
  'prep.first': 'يبدأ العد التنازلي عندما يجهز أول عدّاء.',
  'prep.live': 'هناك غارة جارية. استعد الآن وادخل التالية مع الجميع.',
  'prep.over': 'انتهت الغارة. غرفة التحضير تفتح بعد لحظة.',
  'prep.many': 'الجميع هنا يبدأ بسكين. البوتات تنضم في الثواني الأخيرة.',
  'prep.bots': 'البوتات تملأ الأماكن الفارغة في الثواني الأخيرة.',
  'prep.open': 'شاغر',
  'prep.pot': 'الوعاء',
  'prep.cancel': 'إلغاء · استرداد {v}',
  'prep.ready': 'جاهز · رهان {v}',
  'prep.back': 'العودة إلى الطاولات',
  'hud.bagPrivate': 'حقيبتك · خاصة',
  'hud.golden': 'غارة ذهبية',
  'hud.goldenStart': 'غارة ذهبية · غنائم الجائزة الكبرى بالداخل',
  'hud.start': 'السكين بيدك · اجمع البرتقالي · جد مخرجًا',
  'hud.bagOpened': 'فُتحت حقيبة · +{v}',
  'hud.arsenal': 'اكتملت الترسانة · عودة إلى السكين ★',
  'hud.unlocked': 'فُتح {w}',
  'hud.pnl': '{d} مقابل رهان {s}',
  'hud.alive': '{n} بالداخل',
  'hud.next': 'التالي: {w}',
  'hud.final': 'الدائرة الأخيرة · المخرج الأخير',
  'hud.closing': 'العاصفة تنغلق · {t}',
  'hud.stormIn': 'العاصفة تتقدم بعد {t}',
  'hud.dash': 'اندفاع',
  'hud.bagLook': 'مظهر الحقيبة',
  'hud.extracting': 'إجلاء',
  'hud.holdStill': 'اثبت. أي إصابة تعيد العداد.',
  'hud.sound': 'الصوت',
  'hud.music': 'الموسيقى',
  'bluff.0': 'صغيرة',
  'bluff.1': 'متوسطة',
  'bluff.2': 'منتفخة',
  'touch.move': 'حركة',
  'touch.aim': 'تصويب · إطلاق',
  'touch.bag': 'الحقيبة',
  'w.Knife': 'سكين',
  'w.Pistol': 'مسدس',
  'w.Shotgun': 'بندقية خرطوش',
  'w.SMG': 'رشاش',
  'w.Rifle': 'بندقية',
  'w.Laser sniper': 'قناص ليزر',
  'streak.1': 'الدم الأول',
  'streak.2': 'قتل مزدوج',
  'streak.3': 'قتل ثلاثي',
  'streak.4': 'هيجان',
  'streak.5': 'أسطوري',
  'streak.you1': 'أرقت الدم الأول',
  'feed.storm': 'أخذتك العاصفة',
  'feed.droppedYou': '{name} أسقطك',
  'coach.storm': 'أنت في العاصفة · عُد إلى داخل الدائرة',
  'coach.touch': 'الإبهام الأيسر للحركة · الأيمن للتصويب والهجوم',
  'coach.keys': 'WASD للحركة · الفأرة للتصويب · النقر للهجوم',
  'coach.exit': 'حان وقت الخروج · قف في مخرج أخضر 3 ثوانٍ · أسهم الحافة تدلّك',
  'coach.loot': 'التقط الغنائم البرتقالية · تذهب إلى حقيبتك',
  'coach.kills': 'القتل يطوّر سلاحك · Space للاندفاع',
  'coach.killsTouch': 'القتل يطوّر سلاحك · اضغط اندفاع للمراوغة',
  'spect.watching': 'تشاهد {name} · ◀ ▶ للتبديل',
  'spect.down': 'سقطت',
  'spect.results': 'النتائج',
  'res.extracted': 'تم الإجلاء',
  'res.storm': 'ابتلعتك العاصفة',
  'res.dropped': 'سقطت',
  'res.sealed': 'محبوس بالداخل',
  'res.inside': '{k} قتلى · {t} بالداخل',
  'res.out': 'خرجت بـ {p} على رهان {s}: {d}.',
  'res.paid': 'دُفع {v} بسعر الدخول.',
  'res.killer': 'حقيبتك الآن مع {n}. كان فيها {v}، ولن يعرف ذلك سواكما.',
  'res.inStorm': 'حقيبتك، {v}، ملقاة في العاصفة لمن يجرؤ.',
  'res.sealedText': 'أُغلقت الغارة وأنت بالداخل. ذهبت {v} إلى غنائم الغارة التالية.',
  'res.again': 'العب مجددًا',
  'res.tables': 'الطاولات',
  'res.share': 'شارك البطاقة',
  'share.title': 'مشاركة',
  'share.x': 'انشر على 𝕏',
  'share.copy': 'انسخ الصورة',
  'share.save': 'احفظ PNG',
  'share.close': 'إغلاق',
  'lk.title': 'الخزانة',
  'lk.outfits': 'الأزياء',
  'lk.shop': 'المتجر',
  'lk.bags': 'حقائب الحظ',
  'lk.all': 'الكل',
  'lk.owned': 'أملكها',
  'lk.him': 'هو',
  'lk.her': 'هي',
  'lk.shopUsd': 'دولار المتجر',
  'lk.shopNote': 'اشحن دولار المتجر بـ USDC أو USDT (الحزم الكبيرة فيها مكافأة). دولار المتجر يُصرف هنا فقط ولا يمكن سحبه. ينقصك؟ يُخصم الفرق من USDC/USDT لديك.',
  'lk.bagsNote': 'احتمالات دقيقة تُسحب على الخادم. لا تكرار حتى تكمل ندرة كاملة، والمكرر يعيد 10% من سعره بدولار المتجر. ضمان: ملحمي+ خلال 15 فتحة وأسطوري+ خلال 60.',
  'lk.topupFrom': '+ {v} USDC/USDT متاحة للشحن',
  'lk.collected': 'جمعت {a} / {b}',
  'lk.equipped': 'مُرتدى',
  'lk.equip': 'ارتدِ',
  'lk.buy': 'اشترِ',
  'lk.trialLeft': 'تجربة · بقي {t}',
  'lk.trialHow': 'تجربة ترقية: لك لمدة {t} أخرى. اشترِه لتحتفظ به.',
  'lk.free': 'مجاني للجميع.',
  'lk.inCollection': 'في مجموعتك.',
  'lk.buyOrBag': 'اشترِه هنا أو جرّب حظك بحقيبة.',
  'lk.tryingOn': 'تجربة ارتداء.',
  'lk.bonus': '+{n}% مكافأة',
  'lk.pay': 'ادفع {v}',
  'lk.jackpot': 'الجائزة الكبرى',
  'lk.epicIn': 'ملحمي+ خلال',
  'lk.legIn': 'أسطوري+ خلال',
  'lk.openFree': 'افتح · مجانًا',
  'lk.buyOpen': 'اشترِ وافتح',
  'lk.pityDrop': 'إسقاط مضمون',
  'lk.dup': 'تملكه بالفعل · استرداد {v}',
  'lk.new': '<b>جديد</b> في مجموعتك',
  'lk.jackpotIs': 'الجائزة الكبرى {r}',
  'lk.showOff': 'تباهَ على X',
  'lk.postMiss': 'انشر الإخفاق على X',
  'lk.another': 'افتح واحدة أخرى',
  'lk.free1': 'مجانًا',
  'lk.back': 'العودة إلى الخزانة',
  'lk.yours': '{n} أصبح لك.',
  'r.common': 'عادي',
  'r.rare': 'نادر',
  'r.epic': 'ملحمي',
  'r.legendary': 'أسطوري',
  'r.mythic': 'خرافي',
  'r.exotic': 'استثنائي',
  'ach.title': 'الإنجازات',
  'ach.button': 'الإنجازات',
  'ach.intro': 'كل إنجاز يمنح خبرة رتبة مرة واحدة ويفتح اسمه كلقب يمكنك ارتداؤه.',
  'ach.wear': 'ارتدِ اللقب',
  'ach.worn': 'مُرتدى',
  'ach.wearing': 'اللقب:',
  'ach.takeOff': 'انزع',
  'ach.noTitle': 'بلا لقب',
  'ach.unlocked': 'إنجاز جديد',
  'ach.seeAll': 'كل الإنجازات',
  'achd.raids': 'العب {n} غارات',
  'achd.extracts': 'اخرج {n} مرات',
  'achd.kills': 'اقتل {n} مرات',
  'achd.bestKills': '{n} قتلى في غارة واحدة',
  'achd.bestMulti': 'قتل متعدد ×{n}',
  'achd.prestige': 'أكمل الترسانة {n} مرات',
  'achd.firstBloods': 'أرِق الدم الأول {n} مرات',
  'achd.secs': 'اقضِ {n} ساعة داخل الغارات',
  'achd.bestReturn': 'اخرج بـ {n} أضعاف رهانك',
  'achd.golden': 'اخرج من غارة ذهبية',
  'achd.lastExit': 'اخرج من المخرج الأخير',
  'achd.pacifist': 'اخرج دون أي قتل',
  'achd.rank': 'بلغ الرتبة {n}',
  'achd.outfits': 'امتلك {n} أزياء',
  'ach.rookie': 'مستجد',
  'ach.regular': 'معتاد',
  'ach.veteran': 'مخضرم',
  'ach.lifer': 'مدى الحياة',
  'ach.eternal': 'خالد',
  'ach.escape_artist': 'فنان الهروب',
  'ach.ghost': 'شبح',
  'ach.smuggler': 'مهرّب',
  'ach.phantom': 'طيف',
  'ach.first_kill': 'القتل الأول',
  'ach.hunter': 'صيّاد',
  'ach.butcher': 'جزّار',
  'ach.reaper': 'حاصد الأرواح',
  'ach.apex': 'القمة',
  'ach.rampage': 'هيجان',
  'ach.one_man_army': 'جيش من رجل واحد',
  'ach.double_tap': 'طلقتان',
  'ach.triple_threat': 'تهديد ثلاثي',
  'ach.godlike': 'أسطوري',
  'ach.full_arsenal': 'ترسانة كاملة',
  'ach.arsenal_master': 'سيد الترسانة',
  'ach.first_blood': 'الدم الأول',
  'ach.opener': 'المُبادِر',
  'ach.night_shift': 'الوردية الليلية',
  'ach.insomniac': 'الأرِق',
  'ach.double_up': 'ضعف الرهان',
  'ach.big_bag': 'الحقيبة الكبيرة',
  'ach.gold_rush': 'حمّى الذهب',
  'ach.last_one_out': 'آخر الخارجين',
  'ach.pacifist': 'مسالم',
  'ach.seasoned': 'متمرس',
  'ach.officer': 'ضابط',
  'ach.commander': 'قائد',
  'ach.legend': 'أسطورة',
  'ach.collector': 'جامع',
  'ach.curator': 'أمين المجموعة',
  'ach.hoarder': 'مكتنز',
};
