export default {
  // lobby
  'lobby.tagline': "Stake. Loot. Get out before the storm. <b>Nobody sees what's in your bag.</b>",
  'lobby.namePh': 'Your runner name',
  'lobby.locker': 'Locker · skins · bags',
  'lobby.refill': 'Refill test coins',
  'lobby.online': 'Online',
  'lobby.practice': 'Practice vs bots',
  'lobby.stakePer': 'Stake per raid',
  'lobby.stakeWith': 'Stake with <span class="fine">any coin · shown in $ · winnings come back in the same coin</span>',
  'lobby.play': 'Play · {s} stake',
  'lobby.signIn': 'Sign in to play',
  'lobby.how': 'How to play',
  'lobby.gore': '<b>18+ mode.</b> Limbs come off, blood stays on the floor.',
  'lobby.fine': 'Practice runs in your browser. All money here is play money.',
  'how.1': '<b>Stake and ready up.</b> Everyone drops in together with a knife and 100 health. Half your stake rides in your bag, half is scattered as loot.',
  'how.2': '<b>Grab the orange loot.</b> It goes into your bag. Kills upgrade your weapon: knife → pistol → shotgun → SMG → rifle → laser sniper.',
  'how.3': '<b>Get out alive.</b> Stand in a green exit for 3 seconds before the storm closes it. You keep your whole bag. Die and it drops for someone else.',
  'how.keys': '<kbd>WASD</kbd> move · <kbd>mouse</kbd> aim · <kbd>click</kbd> attack · <kbd>Space</kbd> dash · <kbd>Q</kbd> fake your bag size · <kbd>M</kbd> sound · <kbd>N</kbd> music',
  'how.fine': 'Every raid and every achievement pays rank XP. Every rank-up lends you a new skin for 3 days.',
  'net.practice': 'Just you and the bots, offline.',
  'net.open': 'Connected. Humans and bots share each raid.',
  'net.connecting': 'Connecting to the raid server…',
  'net.down': 'Server unreachable. Retrying… Practice mode works offline.',
  'net.lost': 'Lost the connection. Back at the tables.',
  'q.pick': 'Pick a coin to stake with.',
  'q.short': 'Not enough {c} for a {s} stake. Pick another coin or a smaller stake.',
  'q.shortDeposit': 'Not enough {c} for a {s} stake. Pick another coin, a smaller stake, or deposit.',
  'q.stable': 'You stake {s} in {c}. Get out alive to keep everything you carry.',
  'q.coin': "You stake {a} = {s} at today's price. Winnings come back in {c} at the same rate.",
  'tb.live': 'Raid live · {t}',
  'tb.ready': '{n} ready · {s}s',
  'tb.waiting': '{n} waiting',
  'tb.golden': 'Golden raid next',
  'tb.jackpot': 'Jackpot {v}',
  // practice settings
  'pcfg.title': 'Practice settings',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Easy',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Hard',
  'pcfg.runners': 'Runners in the raid',
  'pcfg.time': 'Raid length',
  // rank
  'rk.max': 'max rank',
  'rk.toNext': '{x} XP to rank {r}',
  'rk.of': 'Rank {r} of 90',
  'rk.rank': 'Rank',
  'rk.up': 'Rank up',
  'rk.xp': 'rank XP',
  'xp.Raid': 'Raid',
  'xp.kills': '{n} kills',
  'xp.Damage': 'Damage',
  'xp.Time alive': 'Time alive',
  'xp.First blood': 'First blood',
  'xp.Double kill': 'Double kill',
  'xp.Triple kill': 'Triple kill',
  'xp.Rampage': 'Rampage',
  'xp.Godlike': 'Godlike',
  'xp.Full arsenal': 'Full arsenal',
  'xp.Extracted': 'Extracted',
  'xp.Profit': 'Profit',
  'xp.Practice ×0.5': 'Practice ×0.5',
  'rw.title': 'Rank-up reward',
  'rw.trial': 'yours to wear for 72 hours',
  'rw.try': 'Try it on',
  'rw.share': 'Share rank-up',
  // ready room
  'prep.raid': 'Raid {n} · {s} stake',
  'prep.readyUp': 'Ready up',
  'prep.first': 'The countdown starts when the first runner is ready.',
  'prep.live': 'A raid is running. Ready up now and you drop into the next one together.',
  'prep.over': 'Raid over. The ready room opens in a moment.',
  'prep.many': 'Everyone here starts with a knife. Bots join in the last seconds.',
  'prep.bots': 'Bots fill the empty spots in the last seconds.',
  'prep.open': 'open',
  'prep.pot': 'Pot',
  'prep.cancel': 'Cancel · refund {v}',
  'prep.ready': 'Ready · stake {v}',
  'prep.back': 'Back to tables',
  // raid HUD
  'hud.bagPrivate': 'Your bag · private',
  'hud.golden': 'Golden raid',
  'hud.goldenStart': 'Golden raid · jackpot loot inside',
  'hud.start': 'Knife up · grab the orange · find an exit',
  'hud.bagOpened': 'Bag opened · +{v}',
  'hud.arsenal': 'Arsenal complete · back to the knife ★',
  'hud.unlocked': '{w} unlocked',
  'hud.pnl': '{d} vs {s} stake',
  'hud.alive': '{n} inside',
  'hud.next': 'Next: {w}',
  'hud.final': 'Final circle · last exit',
  'hud.closing': 'Storm closing · {t}',
  'hud.stormIn': 'Storm moves in {t}',
  'hud.dash': 'Dash',
  'hud.bagLook': 'Bag look',
  'hud.extracting': 'Extracting',
  'hud.holdStill': 'Hold still. A hit resets it.',
  'hud.sound': 'Sound',
  'hud.music': 'Music',
  'bluff.0': 'small',
  'bluff.1': 'medium',
  'bluff.2': 'fat',
  'touch.move': 'move',
  'touch.aim': 'aim · fire',
  'touch.bag': 'Bag',
  'w.Knife': 'Knife',
  'w.Pistol': 'Pistol',
  'w.Shotgun': 'Shotgun',
  'w.SMG': 'SMG',
  'w.Rifle': 'Rifle',
  'w.Laser sniper': 'Laser sniper',
  'streak.1': 'First blood',
  'streak.2': 'Double kill',
  'streak.3': 'Triple kill',
  'streak.4': 'Rampage',
  'streak.5': 'Godlike',
  'streak.you1': 'You drew first blood',
  'feed.storm': 'The storm took you',
  'feed.droppedYou': '{name} dropped you',
  'coach.storm': "You're in the storm · get back inside the circle",
  'coach.touch': 'Left thumb moves · right thumb aims and attacks',
  'coach.keys': 'WASD to move · mouse to aim · click to attack',
  'coach.exit': 'Time to get out · stand in a green EXIT for 3 seconds · edge arrows point the way',
  'coach.loot': 'Grab the orange loot · it goes into your bag',
  'coach.kills': 'Kills upgrade your weapon · Space to dash',
  'coach.killsTouch': 'Kills upgrade your weapon · tap Dash to dodge',
  'spect.watching': 'Watching {name} · ◀ ▶ to switch',
  'spect.down': 'You went down',
  'spect.results': 'Results',
  // result
  'res.extracted': 'Extracted',
  'res.storm': 'Eaten by the storm',
  'res.dropped': 'Dropped',
  'res.sealed': 'Sealed inside',
  'res.inside': '{k} kills · {t} inside',
  'res.out': 'Out with {p} on a {s} stake: {d}.',
  'res.paid': 'Paid out {v} at your entry rate.',
  'res.killer': '{n} has your bag now. It held {v}, and only the two of you will ever know.',
  'res.inStorm': 'Your bag, {v}, is lying in the storm for anyone brave enough.',
  'res.sealedText': "The raid closed with you still in it. Your {v} rolled into the next raid's loot.",
  'res.again': 'Play again',
  'res.tables': 'Tables',
  'res.share': 'Share card',
  'share.title': 'Share',
  'share.x': 'Post on 𝕏',
  'share.copy': 'Copy image',
  'share.save': 'Save PNG',
  'share.close': 'Close',
  // locker
  'lk.title': 'Locker',
  'lk.outfits': 'Outfits',
  'lk.shop': 'Shop',
  'lk.bags': 'Luck bags',
  'lk.all': 'All',
  'lk.owned': 'Owned',
  'lk.him': 'Him',
  'lk.her': 'Her',
  'lk.shopUsd': 'Shop $',
  'lk.shopNote': "Top up shop $ with USDC or USDT (bigger packs add a bonus). Shop $ only spends here and can't be withdrawn. Short on shop $? The difference comes from your USDC/USDT.",
  'lk.bagsNote': 'Exact odds, rolled on the server. No duplicates until you own a whole rarity, and a duplicate pays 10% of its price back in shop $. Pity guarantees Epic+ within 15 opens and Legendary+ within 60.',
  'lk.topupFrom': '+ {v} USDC/USDT to top up from',
  'lk.collected': '{a} / {b} collected',
  'lk.equipped': 'Equipped',
  'lk.equip': 'Equip',
  'lk.buy': 'Buy',
  'lk.trialLeft': 'Trial · {t} left',
  'lk.trialHow': 'A rank-up trial: yours for {t} more. Buy it to keep it.',
  'lk.free': 'Free for every runner.',
  'lk.inCollection': 'In your collection.',
  'lk.buyOrBag': 'Buy it here, or try your luck with a bag.',
  'lk.tryingOn': 'Trying it on.',
  'lk.bonus': '+{n}% bonus',
  'lk.pay': 'pay {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Epic+ in',
  'lk.legIn': 'Legendary+ in',
  'lk.openFree': 'Open · free',
  'lk.buyOpen': 'Buy & open',
  'lk.pityDrop': 'pity drop',
  'lk.dup': 'Already yours · {v} back',
  'lk.new': '<b>New</b> in your collection',
  'lk.jackpotIs': 'the jackpot is {r}',
  'lk.showOff': 'Show it off on X',
  'lk.postMiss': 'Post the miss on X',
  'lk.another': 'Open another',
  'lk.free1': 'free',
  'lk.back': 'Back to the locker',
  'lk.yours': '{n} is yours.',
  'r.common': 'Common',
  'r.rare': 'Rare',
  'r.epic': 'Epic',
  'r.legendary': 'Legendary',
  'r.mythic': 'Mythic',
  'r.exotic': 'Exotic',
  // achievements
  'ach.title': 'Achievements',
  'ach.button': 'Achievements',
  'ach.intro': 'Each one pays rank XP once and unlocks its name as a title you can wear.',
  'ach.wear': 'Wear title',
  'ach.worn': 'Worn',
  'ach.wearing': 'Title:',
  'ach.takeOff': 'take off',
  'ach.noTitle': 'No title',
  'ach.unlocked': 'Achievement unlocked',
  'ach.seeAll': 'All achievements',
  'achd.raids': 'Play {n} raids',
  'achd.extracts': 'Extract {n} times',
  'achd.kills': 'Get {n} kills',
  'achd.bestKills': '{n} kills in one raid',
  'achd.bestMulti': 'A {n}× multi-kill',
  'achd.prestige': 'Finish the arsenal {n} times',
  'achd.firstBloods': 'Draw first blood {n} times',
  'achd.secs': 'Spend {n} h inside raids',
  'achd.bestReturn': 'Extract with {n}× your stake',
  'achd.golden': 'Extract from a golden raid',
  'achd.lastExit': 'Get out through the last exit',
  'achd.pacifist': 'Extract without a single kill',
  'achd.rank': 'Reach rank {n}',
  'achd.outfits': 'Own {n} outfits',
  'ach.rookie': 'Rookie',
  'ach.regular': 'Regular',
  'ach.veteran': 'Veteran',
  'ach.lifer': 'Lifer',
  'ach.eternal': 'Eternal',
  'ach.escape_artist': 'Escape Artist',
  'ach.ghost': 'Ghost',
  'ach.smuggler': 'Smuggler',
  'ach.phantom': 'Phantom',
  'ach.first_kill': 'First Kill',
  'ach.hunter': 'Hunter',
  'ach.butcher': 'Butcher',
  'ach.reaper': 'Reaper',
  'ach.apex': 'Apex',
  'ach.rampage': 'Rampage',
  'ach.one_man_army': 'One-Man Army',
  'ach.double_tap': 'Double Tap',
  'ach.triple_threat': 'Triple Threat',
  'ach.godlike': 'Godlike',
  'ach.full_arsenal': 'Full Arsenal',
  'ach.arsenal_master': 'Arsenal Master',
  'ach.first_blood': 'First Blood',
  'ach.opener': 'The Opener',
  'ach.night_shift': 'Night Shift',
  'ach.insomniac': 'Insomniac',
  'ach.double_up': 'Double Up',
  'ach.big_bag': 'Big Bag',
  'ach.gold_rush': 'Gold Rush',
  'ach.last_one_out': 'Last One Out',
  'ach.pacifist': 'Pacifist',
  'ach.seasoned': 'Seasoned',
  'ach.officer': 'Officer',
  'ach.commander': 'Commander',
  'ach.legend': 'Legend',
  'ach.collector': 'Collector',
  'ach.curator': 'Curator',
  'ach.hoarder': 'Hoarder',
};
