export default {
  // lobby
  'lobby.tagline': "Stake. Loot. Get out before the storm. <b>Nobody sees what's in your bag.</b>",
  'lobby.namePh': 'Your runner name',
  'lobby.locker': 'Locker · skins · bags',
  'lobby.refill': 'Refill test coins',
  'lobby.online': 'Online',
  'lobby.practice': 'Practice vs bots',
  'lobby.stakePer': 'Stake per raid',
  'lobby.stakeWith': 'Stake with <span class="fine">any coin · shown in $ · winnings come back in the same coin</span>',
  'lobby.play': 'Play · {s} stake',
  'lobby.signIn': 'Sign in to play',
  'lobby.how': 'How to play',
  'lobby.gore': '<b>18+ mode.</b> Limbs come off, blood stays on the floor.',
  'lobby.fine': 'Practice runs in your browser. All money here is play money.',
  'how.1': '<b>Stake and ready up.</b> Everyone drops in together with a knife and 100 health. Half your stake rides in your bag, half is scattered as loot.',
  'how.2': '<b>Grab the orange loot.</b> It goes into your bag. Kills upgrade your weapon: knife → pistol → shotgun → SMG → rifle → laser sniper.',
  'how.3': '<b>Get out alive.</b> Stand in a green exit for 3 seconds before the storm closes it. You keep your whole bag. Die and it drops for someone else.',
  'how.keys': "<kbd>WASD</kbd> move · <kbd>mouse</kbd> aim · <kbd>click</kbd> attack · <kbd>Space</kbd> dash · <kbd>Q</kbd> fake your bag size · <kbd>M</kbd> sound · <kbd>N</kbd> music",
  'how.fine': 'Every raid and every achievement pays rank XP. Every rank-up lends you a new skin for 3 days.',
  'net.practice': 'Just you and the bots, offline.',
  'net.open': 'Connected. Humans and bots share each raid.',
  'net.connecting': 'Connecting to the raid server…',
  'net.down': 'Server unreachable. Retrying… Practice mode works offline.',
  'net.lost': 'Lost the connection. Back at the tables.',
  'q.pick': 'Pick a coin to stake with.',
  'q.short': 'Not enough {c} for a {s} stake. Pick another coin or a smaller stake.',
  'q.shortDeposit': 'Not enough {c} for a {s} stake. Pick another coin, a smaller stake, or deposit.',
  'q.stable': 'You stake {s} in {c}. Get out alive to keep everything you carry.',
  'q.coin': "You stake {a} = {s} at today's price. Winnings come back in {c} at the same rate.",
  'tb.live': 'Raid live · {t}',
  'tb.ready': '{n} ready · {s}s',
  'tb.waiting': '{n} waiting',
  'tb.golden': 'Golden raid next',
  'tb.jackpot': 'Jackpot {v}',
  // practice settings
  'pcfg.title': 'Practice settings',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Easy',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Hard',
  'pcfg.runners': 'Runners in the raid',
  'pcfg.time': 'Raid length',
  // rank
  'rk.max': 'max rank',
  'rk.toNext': '{x} XP to rank {r}',
  'rk.of': 'Rank {r} of 90',
  'rk.rank': 'Rank',
  'rk.up': 'Rank up',
  'rk.xp': 'rank XP',
  'xp.Raid': 'Raid',
  'xp.kills': '{n} kills',
  'xp.Damage': 'Damage',
  'xp.Time alive': 'Time alive',
  'xp.First blood': 'First blood',
  'xp.Double kill': 'Double kill',
  'xp.Triple kill': 'Triple kill',
  'xp.Rampage': 'Rampage',
  'xp.Godlike': 'Godlike',
  'xp.Full arsenal': 'Full arsenal',
  'xp.Extracted': 'Extracted',
  'xp.Profit': 'Profit',
  'xp.Practice ×0.5': 'Practice ×0.5',
  'rk.newRank': "New rank",
  'rw.continue': "Continue",
  'rw.title': 'Rank-up reward',
  'rw.trial': 'yours to wear for 72 hours',
  'rw.try': 'Try it on',
  'rw.share': 'Share rank-up',
  // ready room
  'prep.raid': 'Raid {n} · {s} stake',
  'prep.readyUp': 'Ready up',
  'prep.first': 'The countdown starts when the first runner is ready.',
  'prep.live': 'A raid is running. Ready up now and you drop into the next one together.',
  'prep.over': 'Raid over. The ready room opens in a moment.',
  'prep.many': 'Everyone here starts with a knife. Bots join in the last seconds.',
  'prep.bots': 'Bots fill the empty spots in the last seconds.',
  'prep.open': 'open',
  'prep.pot': 'Pot',
  'prep.cancel': 'Cancel · refund {v}',
  'prep.ready': 'Ready · stake {v}',
  'prep.back': 'Back to tables',
  // raid HUD
  'hud.bagPrivate': 'Your bag · private',
  'hud.golden': 'Golden raid',
  'hud.goldenStart': 'Golden raid · jackpot loot inside',
  'hud.start': 'Knife up · grab the orange · find an exit',
  'hud.bagOpened': 'Bag opened · +{v}',
  'hud.arsenal': 'Arsenal complete · back to the knife ★',
  'hud.unlocked': '{w} unlocked',
  'hud.pnl': '{d} vs {s} stake',
  'hud.alive': '{n} inside',
  'hud.next': 'Next: {w}',
  'hud.final': 'Final circle · last exit',
  'hud.closing': 'Storm closing · {t}',
  'hud.stormIn': 'Storm moves in {t}',
  'hud.dash': 'Dash',
  'hud.bagLook': 'Bag look',
  'hud.extracting': 'Extracting',
  'hud.holdStill': 'Hold still. A hit resets it.',
  'hud.sound': 'Sound',
  'hud.music': 'Music',
  'bluff.0': 'small',
  'bluff.1': 'medium',
  'bluff.2': 'fat',
  'touch.move': 'move',
  'touch.aim': 'aim · fire',
  'touch.bag': 'Bag',
  'w.Knife': 'Knife',
  'w.Pistol': 'Pistol',
  'w.Shotgun': 'Shotgun',
  'w.SMG': 'SMG',
  'w.Rifle': 'Rifle',
  'w.Laser sniper': 'Laser sniper',
  'w.Hand Cannon': "Hand Cannon",
  'w.Auto Shotgun': "Auto Shotgun",
  'w.PDW': "PDW",
  'w.Carbine': "Carbine",
  'w.Scout': "Scout",
  'w.Machine Gun': "Machine Gun",
  'w.Magnum Sniper': "Magnum Sniper",
  'hud.reloading': "Reloading",
  'streak.1': 'First blood',
  'streak.2': 'Double kill',
  'streak.3': 'Triple kill',
  'streak.4': 'Rampage',
  'streak.5': 'Godlike',
  'streak.you1': 'You drew first blood',
  'feed.storm': 'The storm took you',
  'feed.droppedYou': '{name} dropped you',
  'coach.storm': "You're in the storm · get back inside the circle",
  'coach.touch': "Left thumb moves · hold Fire: it aims at the nearest enemy for you",
  'coach.keys': 'WASD to move · mouse to aim · click to attack',
  'coach.exit': 'Time to get out · stand in a green EXIT for 3 seconds · edge arrows point the way',
  'coach.loot': 'Grab the orange loot · it goes into your bag',
  'coach.kills': 'Kills upgrade your weapon · Space to dash',
  'coach.killsTouch': 'Kills upgrade your weapon · tap Dash to dodge',
  'spect.watching': 'Watching {name} · ◀ ▶ to switch',
  'spect.down': 'You went down',
  'spect.results': 'Results',
  // result
  'res.extracted': 'Extracted',
  'res.storm': 'Eaten by the storm',
  'res.dropped': 'Dropped',
  'res.sealed': 'Sealed inside',
  'res.inside': '{k} kills · {t} inside',
  'res.out': 'Out with {p} on a {s} stake: {d}.',
  'res.paid': 'Paid out {v} at your entry rate.',
  'res.killer': '{n} has your bag now. It held {v}, and only the two of you will ever know.',
  'res.inStorm': 'Your bag, {v}, is lying in the storm for anyone brave enough.',
  'res.sealedText': "The raid closed with you still in it. Your {v} rolled into the next raid's loot.",
  'res.again': 'Play again',
  'res.tables': 'Tables',
  'res.share': 'Share card',
  'share.title': 'Share',
  'share.x': 'Post on 𝕏',
  'share.copy': 'Copy image',
  'share.save': 'Save PNG',
  'share.close': 'Close',
  // locker
  'lk.title': 'Locker',
  'lk.outfits': 'Outfits',
  'lk.shop': 'Shop',
  'lk.bags': 'Luck bags',
  'lk.sortDesc': "Rarest first ↓",
  'lk.sortAsc': "Commonest first ↑",
  'lk.allGuns': "All guns",
  'lk.takeOff': "Take off",
  'lk.empty': "Nothing here yet: bags and crates in the shop fill your collection.",
  'lk.emptyTurrets': "No turret skins yet: they come from the battle pass.",
  'lk.pickSkin': "Tap a skin to preview it, then equip it.",
  'lk.all': 'All',
  'lk.owned': 'Owned',
  'lk.him': 'Him',
  'lk.her': 'Her',
  'lk.shopUsd': 'Shop $',
  'lk.shopNote': "Top up shop $ with USDC or USDT (bigger packs add a bonus). Shop $ only spends here and can't be withdrawn. Short on shop $? The difference comes from your USDC/USDT.",
  'lk.bagsNote': 'Exact odds, rolled on the server. No duplicates until you own a whole rarity, and a duplicate pays 10% of its price back in shop $. Pity guarantees Epic+ within 15 opens and Legendary+ within 60.',
  'lk.topupFrom': '+ {v} USDC/USDT to top up from',
  'lk.collected': '{a} / {b} collected',
  'lk.equipped': 'Equipped',
  'lk.equip': 'Equip',
  'lk.buy': 'Buy',
  'lk.trialLeft': 'Trial · {t} left',
  'lk.trialHow': 'A rank-up trial: yours for {t} more. Buy it to keep it.',
  'lk.free': 'Free for every runner.',
  'lk.inCollection': 'In your collection.',
  'lk.buyOrBag': 'Buy it here, or try your luck with a bag.',
  'lk.tryingOn': 'Trying it on.',
  'lk.bonus': '+{n}% bonus',
  'lk.pay': 'pay {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Epic+ in',
  'lk.legIn': 'Legendary+ in',
  'lk.openFree': 'Open · free',
  'lk.buyOpen': 'Buy & open',
  'lk.pityDrop': 'pity drop',
  'lk.dup': 'Already yours · {v} back',
  'lk.new': '<b>New</b> in your collection',
  'lk.jackpotIs': 'the jackpot is {r}',
  'lk.showOff': 'Show it off on X',
  'lk.postMiss': 'Post the miss on X',
  'lk.another': 'Open another',
  'lk.free1': 'free',
  'lk.back': 'Back to the locker',
  'lk.yours': '{n} is yours.',
  'r.common': 'Common',
  'r.rare': 'Rare',
  'r.epic': 'Epic',
  'r.legendary': 'Legendary',
  'r.mythic': 'Mythic',
  'r.exotic': 'Exotic',
  // achievements
  'ach.title': 'Achievements',
  'ach.button': 'Achievements',
  'ach.intro': 'Each one pays rank XP once and unlocks its name as a title you can wear.',
  'ach.wear': 'Wear title',
  'ach.worn': 'Worn',
  'ach.wearing': 'Title:',
  'ach.takeOff': 'take off',
  'ach.noTitle': 'No title',
  'ach.unlocked': 'Achievement unlocked',
  'ach.seeAll': 'All achievements',
  'achd.raids': 'Play {n} raids',
  'achd.extracts': 'Extract {n} times',
  'achd.kills': 'Get {n} kills',
  'achd.bestKills': '{n} kills in one raid',
  'achd.bestMulti': 'A {n}× multi-kill',
  'achd.prestige': 'Finish the arsenal {n} times',
  'achd.firstBloods': 'Draw first blood {n} times',
  'achd.secs': 'Spend {n} h inside raids',
  'achd.bestReturn': 'Extract with {n}× your stake',
  'achd.golden': 'Extract from a golden raid',
  'achd.lastExit': 'Get out through the last exit',
  'achd.pacifist': 'Extract without a single kill',
  'achd.rank': 'Reach rank {n}',
  'achd.outfits': 'Own {n} outfits',
  'ach.gunslinger': "Gunslinger",
  'ach.close_quarters': "Close Quarters",
  'ach.spray_and_pray': "Spray and Pray",
  'ach.rifleman': "Rifleman",
  'ach.marksman': "Marksman",
  'ach.deadeye': "Deadeye",
  'ach.blade_dancer': "Blade Dancer",
  'ach.shadow_blade': "Shadow Blade",
  'ach.deathmatch_king': "Deathmatch King",
  'ach.duelist': "Duelist",
  'ach.squad_goals': "Squad Goals",
  'ach.one_shot_one_kill': "One Shot One Kill",
  'ach.specialist': "Specialist",
  'ach.engineer': "Engineer",
  'ach.ranked_debut': "Ranked Debut",
  'ach.ranked_grinder': "Ranked Grinder",
  'ach.ranked_victor': "Ranked Victor",
  'ach.gold_league': "Gold League",
  'ach.diamond_league': "Diamond League",
  'ach.neon_legend': "Neon Legend",
  'ach.unboxer': "Unboxer",
  'ach.case_hunter': "Case Hunter",
  'ach.case_lord': "Case Lord",
  'ach.armory': "Armory",
  'ach.arsenal_baron': "Arsenal Baron",
  'ach.pass_holder': "Pass Holder",
  'ach.pass_maxed': "Pass Maxed",
  'ach.neon_bearer': "Neon Bearer",
  'ach.by_a_thread': "By a Thread",
  'ach.untouchable': "Untouchable",
  'ach.ghost_walker': "Ghost Walker",
  'ach.one_tap': "One Tap",
  'achd.kHandgun': "Get {n} kills with pistols",
  'achd.kShotgun': "Get {n} kills with shotguns",
  'achd.kSmg': "Get {n} kills with SMGs",
  'achd.kRifle': "Get {n} kills with rifles and machine guns",
  'achd.kSniper': "Get {n} kills with snipers",
  'achd.kKnife': "Get {n} knife kills",
  'achd.dmWins': "Win {n} deathmatches",
  'achd.duelWins': "Win {n} duels",
  'achd.teamWins': "Win {n} team matches",
  'achd.hcWins': "Win {n} hardcore matches",
  'achd.weaponWins': "Win {n} one-weapon matches",
  'achd.turretKills': "Get {n} turret kills in Guns + Lasers",
  'achd.rankedGames': "Play {n} ranked matches",
  'achd.rankedWins': "Win {n} ranked matches",
  'achd.bestDiv': "Reach {n} in ranked",
  'achd.opened': "Open {n} cases and bags",
  'achd.wskins': "Own {n} weapon skins",
  'achd.passTier': "Reach battle pass tier {n}",
  'achd.stitles': "Win a season title",
  'achd.clutch': "Get out with 10 health or less",
  'achd.flawless': "Get out after 2+ minutes without taking a hit",
  'achd.ninjaWin': "Win a pot mode without a single kill",
  'achd.oneShots': "Take {n} runners from full health to zero in one hit",
  'ach.secret': "Secret",
  'ach.secretDesc': "Keep playing: this one reveals itself when you earn it.",
  'r.mystery': "Mystery",
  'ach.rookie': 'Rookie',
  'ach.regular': 'Regular',
  'ach.veteran': 'Veteran',
  'ach.lifer': 'Lifer',
  'ach.eternal': 'Eternal',
  'ach.escape_artist': 'Escape Artist',
  'ach.ghost': 'Ghost',
  'ach.smuggler': 'Smuggler',
  'ach.phantom': 'Phantom',
  'ach.first_kill': 'First Kill',
  'ach.hunter': 'Hunter',
  'ach.butcher': 'Butcher',
  'ach.reaper': 'Reaper',
  'ach.apex': 'Apex',
  'ach.rampage': 'Rampage',
  'ach.one_man_army': 'One-Man Army',
  'ach.double_tap': 'Double Tap',
  'ach.triple_threat': 'Triple Threat',
  'ach.godlike': 'Godlike',
  'ach.full_arsenal': 'Full Arsenal',
  'ach.arsenal_master': 'Arsenal Master',
  'ach.first_blood': 'First Blood',
  'ach.opener': 'The Opener',
  'ach.night_shift': 'Night Shift',
  'ach.insomniac': 'Insomniac',
  'ach.double_up': 'Double Up',
  'ach.big_bag': 'Big Bag',
  'ach.gold_rush': 'Gold Rush',
  'ach.last_one_out': 'Last One Out',
  'ach.pacifist': 'Pacifist',
  'ach.seasoned': 'Seasoned',
  'ach.officer': 'Officer',
  'ach.commander': 'Commander',
  'ach.legend': 'Legend',
  'ach.collector': 'Collector',
  'ach.curator': 'Curator',
  'ach.hoarder': 'Hoarder',
  'intro.tag': "Stake. Loot. Get out.",
  'intro.go': "Enter",
  'intro.fonts': "Sharpening knives…",
  'intro.world': "Painting the dark…",
  'intro.connect': "Finding a raid…",
  'intro.profile': "Packing your bag…",
  'intro.ready': "Ready",
  'tb.wallet': "Wallet",
  'tb.shop': "Shop $",
  'nav.play': "Play",
  'nav.shop': "Shop",
  'nav.inventory': "Inventory",
  'nav.swap': "Swap",
  'nav.chat': "Chat",
  'nav.achievements': "Achievements",
  'nav.pass': "Pass",
  'bp.season': "Season {n}",
  'bp.ends': "ends in {d}d {h}h",
  'bp.tier': "Tier {n}/{m}",
  'bp.xp': "{a}/{b} XP to the next tier",
  'bp.maxed': "All tiers done",
  'bp.how': "Every raid fills the pass with the same XP as your rank.",
  'bp.free': "Free",
  'bp.premium': "Premium",
  'bp.buy': "Premium pass · {v}",
  'bp.owned': "Premium active",
  'bp.perks': "All 50 tiers of rewards: the Warlord and Apex armour, 2 turret skins, 5 seasonal weapon skins, cases and $.",
  'bp.claim': "Claim",
  'bp.claimAll': "Claim all ({n})",
  'bp.claimed': "Claimed",
  'bp.limited': "This season only",
  'bp.turrets': "Turret skins",
  'bp.turretsNote': "Your turrets in Guns + Lasers.",
  'bp.equip': "Equip",
  'bp.equipped': "Equipped",
  'bp.none': "Plain",
  'bp.up': "Battle pass: tier {n}!",
  'bp.got': "Claimed: {x}",
  'bp.credit': "+{v} shop credit",
  'mode.ranked': "Ranked",
  'mode.ranked.d': "Battle royale for your season rating. Climb from Bronze to Neon Legend; top finishes win a bonus spin.",
  'nav.ranked': "Ranked",
  'rd.title': "Ranked · Season {n}",
  'rd.pos': "#{n} of {m}",
  'rd.unranked': "Play a ranked match to get on the table.",
  'rd.play': "Play ranked",
  'rd.games': "Matches",
  'rd.wins': "Wins",
  'rd.top3': "Top 3",
  'rd.kills': "Kills",
  'rd.winrate': "Win rate",
  'rd.player': "Runner",
  'rd.div': "Division",
  'rd.div.bronze': "Bronze",
  'rd.div.silver': "Silver",
  'rd.div.gold': "Gold",
  'rd.div.platinum': "Platinum",
  'rd.div.diamond': "Diamond",
  'rd.div.master': "Master",
  'rd.div.legend': "Neon Legend",
  'rd.titles': "Season titles",
  'rd.titlesNote': "Won from the ranked bonus spin. Worn in neon over your name, with bonus XP until the season ends.",
  'rd.wear': "Wear",
  'rd.off': "Take off",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "season over",
  'rd.board': "Season leaderboard",
  'rd.empty': "Nobody has played ranked this season yet. Be the first.",
  'rd.place': "Place #{p} of {n}",
  'rd.promoted': "promoted!",
  'rd.demoted': "demoted",
  'rd.practice': "Practice: your rating doesn't change.",
  'rd.spin': "Bonus spin",
  'rd.spinWhy': "for place #{p}",
  'rd.won': "You won:",
  'rd.wornNow': "Your new title is on, in neon.",
  'st.contender': "Contender",
  'st.elite': "Elite",
  'st.champion': "Champion",
  'xp.Season title': "Season title",
  'news.title': "What's new",
  'news.ok': "Got it",
  'news.note': "Every update, with its date and time.",
  'news.open': "Open",
  'stake.own': "Your stake",
  'stake.range': "Stake from $0.10 to $10,000",
  'nav.settings': "Settings",
  'modes.title': "Game mode",
  'kind.raid': "extraction",
  'kind.br': "winner takes the pot",
  'kind.team': "team pot",
  'mode.raid': "Raid",
  'mode.raid.d': "Loot, fight, get out through an exit. Keep what you carry.",
  'mode.br': "Battle Royale",
  'mode.br.d': "Up to 20 runners. Last one standing takes the whole pot.",
  'mode.duel': "Duel",
  'mode.duel.d': "One on one. Winner takes both stakes.",
  'mode.knives': "Knives only",
  'mode.knives.d': "Blades only, all raid. Last one standing wins.",
  'mode.pistols': "Pistols only",
  'mode.pistols.d': "Sidearms only. Last one standing wins.",
  'mode.shotguns': "Shotguns only",
  'mode.shotguns.d': "Close and loud. Last one standing wins.",
  'mode.rifles': "Rifles only",
  'mode.rifles.d': "Mid-range firefights. Last one standing wins.",
  'mode.snipers': "Snipers only",
  'mode.snipers.d': "Laser sights everywhere. Last one standing wins.",
  'mode.team2': "Team 2 v 2",
  'mode.team2.d': "Every stake grows one pot. The last team standing splits it.",
  'mode.team4': "Team 4 v 4",
  'mode.team4.d': "Every stake grows one pot. The last team standing splits it.",
  'mode.team8': "Team 8 v 8",
  'mode.team8.d': "Every stake grows one pot. The last team standing splits it.",
  'hud.pot': "Prize pot",
  'hud.left': "{n} left · {s} stake",
  'hud.teamsLeft': "{n} teams left · {s} stake",
  'hud.startPot': "Last one standing takes the pot",
  'hud.startTeam': "Stick with your team · wipe the other side",
  'hud.goldenPot': "Golden raid · jackpot added to the pot",
  'coach.pot': "No exits here · stay in the circle · last one standing wins",
  'coach.team': "Green names are your team · red names are the enemy",
  'warn.exit30': "30s · reach an open exit",
  'warn.exit10': "10s · extract or lose it all",
  'warn.pot30': "30s · the storm closes in",
  'warn.pot10': "10s · most runners alive wins",
  'storm.final': "Final collapse · last exit only",
  'storm.finalPot': "Final collapse · nowhere to hide",
  'storm.closing': "The storm is closing in",
  'storm.in5': "Storm moves in 5s",
  'feed.youDropped': "You dropped {name}",
  'feed.stormTook': "{name} was eaten by the storm",
  'feed.dropped': "{a} dropped {b}",
  'feed.down': "{name} went down",
  'feed.extracted': "{name} extracted",
  'feed.exitClosed': "Exit {name} is closed",
  'spect.settling': "Your result comes when the raid is settled.",
  'res.victory': "Victory",
  'res.teamWon': "Your team won",
  'res.defeated': "Defeated",
  'res.wonText': "You took {p} on a {s} stake.",
  'res.lostPot': "The pot went to the last one standing.",
  'res.teamLost': "The other team took the pot.",
  'xp.Victory': "Victory",
  'ach.champion': "Champion",
  'ach.warlord': "Warlord",
  'achd.wins': "Win {n} pot raids",
  'lk.weapons': "Weapon skins",
  'lk.onlyBags': "Skins come only from bags and crates in the shop.",
  'lk.toShop': "Open the shop",
  'lk.toOpen': "{n} to open",
  'lk.limited': "Limited · {n}",
  'lk.minted': "{a} of {b} minted",
  'lk.plain': "Standard",
  'lk.fromBags': "Drops from outfit bags in the shop.",
  'lk.fromCrates': "Drops from weapon crates in the shop.",
  'lk.trialHow2': "A rank-up trial: yours for {t} more.",
  'lk.weaponHow': "Pick a finish you own to equip it. Everyone in the raid sees it.",
  'fx.glow': "aura",
  'fx.pulse': "pulsing aura",
  'fx.ghost': "spectral",
  'fx.laser': "laser eyes",
  'fx.rainbow': "prismatic",
  'fx.fire': "burning",
  'fx.gold': "liquid gold",
  'fx.holo': "hologram",
  'fx.glitch': "glitch",
  'fx.lightning': "lightning",
  'fx.galaxy': "galaxy",
  'fx.sparks': "sparks",
  'fx.frost': "frost",
  'fx.money': "money rain",
  'fx.matrix': "code rain",
  'fx.shadow': "shadow smoke",
  'fx.cape': "cape",
  'box.c-samurai': "Cyber Samurai Case",
  'box.c-neon': "Neon Nights Case",
  'box.c-arctic': "Arctic Ops Case",
  'box.c-inferno': "Inferno Case",
  'box.c-crypto': "Crypto Kings Case",
  'box.c-toxic': "Toxic Wasteland Case",
  'box.c-toon': "Toon Town Case",
  'box.c-knife': "Knife Case",
  'box.c-pistol': "Pistol Case",
  'box.c-smg': "SMG Case",
  'box.c-rifle': "Rifle Case",
  'box.c-heavy': "Heavy Case",
  'box.c-sniper': "Sniper Case",
  'box.b-crypto': "Crypto Memes Bag",
  'box.b-heroes': "Multiverse Heroes Bag",
  'box.b-monsters': "Monsters & Myths Bag",
  'box.b-cyber': "Cyber Street Bag",
  'box.b-toon': "Toon Friends Bag",
  'shop.g.theme': "Collections",
  'shop.g.class': "Gun class cases",
  'shop.g.tier': "Tier cases",
  'shop.contents': "Inside · {n} items",
  'box.street': "Street Bag",
  'box.vault': "Vault Bag",
  'box.golden': "Golden Bag",
  'box.elite': "Elite Bag",
  'box.diamond': "Diamond Bag",
  'box.obsidian': "Obsidian Bag",
  'box.royal': "Royal Bag",
  'box.apex': "Apex Bag",
  'box.genesis': "Genesis Bag",
  'box.w-scrap': "Scrap Crate",
  'box.w-armory': "Armory Crate",
  'box.w-brass': "Brass Crate",
  'box.w-specops': "Spec Ops Crate",
  'box.w-diamond': "Diamond Crate",
  'box.w-obsidian': "Obsidian Crate",
  'box.w-royal': "Royal Crate",
  'box.w-apex': "Apex Crate",
  'box.w-genesis': "Genesis Crate",
  'shop.topup': "Top up shop $",
  'shop.bags': "Outfit bags",
  'shop.crates': "Weapon crates",
  'shop.bagsNote': "Outfits for your runner. Nine tiers: the dearer the bag, the better the odds.",
  'shop.cratesNote': "Skins for your guns and knife, sold separately from outfits. Nine tiers.",
  'shop.fair': "Odds are exact and rolled on the server. Pity: Epic+ within {e} opens, Legendary+ within {l}.",
  'shop.odds': "Odds and pity",
  'shop.qty': "How many",
  'shop.open': "Open ×{n}",
  'shop.limited': "Limited editions",
  'shop.soldOut': "Sold out",
  'shop.dup': "Duplicate · +{v}",
  'shop.new': "New",
  'shop.back': "{v} back",
  'shop.equipBest': "Equip {n}",
  'inv.wallet': "Wallet",
  'inv.deposit': "Deposit · cash out",
  'inv.walletNote': "Real tokens held by the house for you. Cash out any time to the address you signed in with.",
  'inv.playNote': "Play money in this browser. Refill any time.",
  'inv.shopNote': "Bought with USDC/USDT, spent only on bags and crates. It cannot be withdrawn.",
  'inv.unopened': "Unopened",
  'inv.collection': "Collection",
  'inv.opened': "Opened",
  'inv.career': "Career",
  'inv.raids': "Raids",
  'inv.kills': "Kills",
  'inv.extracts': "Extractions",
  'inv.wins': "Pot wins",
  'inv.best': "Best raid (kills)",
  'inv.time': "Time inside",
  'swap.game': "Game balance",
  'swap.gameNote': "Instant, at the live price, {f}% fee.",
  'swap.gameOff': "In-game swaps are off on this server. Use your wallet swap below.",
  'swap.from': "From",
  'swap.to': "To",
  'swap.have': "You have",
  'swap.flip': "Swap direction",
  'swap.go': "Swap",
  'swap.short': "Not enough",
  'swap.done': "Swapped {a} for {b}.",
  'swap.wallet': "Your wallet",
  'swap.signIn': "Sign in with a Starknet wallet to swap there through AVNU.",
  'swap.needChain': "AVNU swaps work with a real Starknet wallet in Online mode.",
  'swap.slippage': "Max slippage",
  'swap.quoting': "Getting the best route…",
  'swap.impact': "price impact {p}%",
  'swap.goAvnu': "Swap with AVNU",
  'swap.noQuote': "No route for that pair right now.",
  'swap.sent': "Swap sent: {tx}",
  'swap.walletNote': "Routed by AVNU across Starknet exchanges. You sign in your wallet; the game never holds these tokens.",
  'chat.ph': "Say something…",
  'chat.send': "Send",
  'chat.empty': "No messages yet. Say gm.",
  'chat.online': "Everyone in the lobby sees this. Be nice.",
  'chat.practice': "Practice is offline: only the bots are listening.",
  'set.graphics': "Graphics",
  'set.quality': "Quality",
  'set.qualityNote': "Auto lowers detail when frames get slow.",
  'set.auto': "Auto",
  'set.high': "High",
  'set.medium': "Medium",
  'set.low': "Low",
  'set.shake': "Screen shake",
  'set.motion': "Menu animations",
  'set.display': "Display",
  'set.skins': "Skins",
  'set.skinsNote': "Whose outfits and weapon skins to draw.",
  'set.skinsAll': "Everyone",
  'set.skinsMine': "Only mine",
  'set.skinsNone': "None",
  'set.names': "Names over runners",
  'set.titles': "Titles over names",
  'set.controls': "Controls",
  'set.stick': "Touch stick size",
  'set.lefty': "Left-handed touch",
  'set.leftyNote': "Swaps the move and aim sticks.",
  'set.audio': "Audio",
  'set.sound': "Effects volume",
  'set.music': "Music volume",
  'set.track': "Soundtrack",
  'set.trackAuto': "Mix",
  'set.trackNote': "A different raid track every match, or keep your favourite.",
  'pause.nextTrack': "Next track ⏭",
  'set.language': "Language",
  'shop.exoticIn': "Exotic+ in",
  'shop.guarantee': "Guaranteed Exotic within {n} opens",
  'set.voice': "Announcer",
  'mode.dm': "Deathmatch",
  'mode.dm.d': "Everyone for themselves, respawn after every death. Most kills at the whistle takes the pot.",
  'mode.gl': "Guns + Lasers",
  'mode.gl.d': "Deathmatch with a buy menu: kills pay credits for medkits, sentry turrets and laser tripmines.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Minimal health: one bullet and you're down. Last one standing takes the pot.",
  'kind.dm': "most kills takes the pot",
  'hud.startDm': "Most kills when the clock hits zero takes the pot",
  'hud.startGl': "Kills pay credits · 1 medkit · 2 turret · 3 laser mine",
  'hud.startHc': "One hit and you're down. Make yours count.",
  'hud.respawned': "Back in",
  'hud.respawnIn': "Back in {s}s",
  'hud.tookLead': "You have taken the lead",
  'hud.lostLead': "You have lost the lead",
  'hud.dmScore': "{k} kills · {d} deaths · #{p}",
  'hud.dmGoal': "First kill takes the lead",
  'hud.oneHit': "1 HIT",
  'feed.leader': "{name} takes the lead with {k}",
  'gl.medkit': "Medkit",
  'gl.turret': "Sentry turret",
  'gl.mine': "Laser mine",
  'gl.no.cash': "Not enough credits",
  'gl.no.full': "Already at full health",
  'gl.no.limit': "Limit reached",
  'gl.no.wall': "Too close to a wall",
  'res.dmLost': "Finished #{p}",
  'res.dmText': "{k} kills, {d} deaths. The winner had {top}.",
  'coach.dm': "You respawn · most kills when the clock runs out wins",
  'coach.gl': "Kills pay credits · spend them on a medkit ✚, a turret ◈ or a laser mine ⌁",
  'set.voiceNote': "Recorded announcer (English, Ukrainian, Spanish, French, Portuguese; English for other languages).",
  'net.waking': "Waking the server up (free hosting sleeps when nobody plays, up to a minute)… Practice works meanwhile.",
  'shop.bulk': "Every {n}th box free",
  'shop.bulkOn': "Includes {n} free",
  'net.online': "{n} online",
  'st.title': "Getting started",
  'st.signin': "Sign in",
  'st.signin.d': "With your Starknet wallet, Cartridge, or email.",
  'st.signin.go': "Sign in",
  'st.fund': "Add funds",
  'st.fund.d': "Send a few tokens from your wallet to your game balance. You can cash out any time.",
  'st.fundTest': "Testnet: free STRK at starknet-faucet.vercel.app.",
  'st.fund.go': "Deposit",
  'st.coin': "Pick your coin",
  'st.coin.d': "Choose which coin you stake with below. Winnings come back in the same coin.",
  'st.coin.go': "Show coins",
  'st.play': "Play your first match",
  'st.play.d': "Pick a mode and a stake, press Play, then Ready.",
  'st.play.go': "Play",
  'touch.fire': "Fire",
  'rot.title': "Turn your phone sideways",
  'rot.sub': "The raid plays best in landscape: move on the left, Fire on the right.",
  'rot.anyway': "Play upright anyway",
  'prep.waiting': "Waiting for players",
  'prep.waitingMe': "No timer: invite friends and press Start when you're ready. Empty seats get bots. {n} of {of} seats taken.",
  'prep.waitingJoin': "{n} of {of} seats taken. Stake & ready to join this raid.",
  'prep.firstWait': "Press Ready: the room waits for everyone, no timer.",
  'prep.start': "Start now",
  'nav.friends': "Friends",
  'nav.guilds': "Guilds",
  'so.now': "just now",
  'so.min': "{n} min ago",
  'so.hr': "{n} h ago",
  'so.day': "{n} d ago",
  'so.seen': "Last seen {t}",
  'so.st.lobby': "Online",
  'so.st.waiting': "Waiting in a room",
  'so.st.raid': "In a raid",
  'so.friend': "Friend",
  'so.sent': "Request sent",
  'so.accept': "Accept",
  'so.add': "Add friend",
  'so.invited': "Invited",
  'so.invite': "Invite",
  'so.message': "Message",
  'so.onlineOnly': "Friends, messages and guilds work when you play online.",
  'so.gInvite': "To guild",
  'so.gInvited': "Invited",
  'so.gInviteSent': "Guild invite sent",
  'so.gInvitesYou': "invites you to their guild",
  'so.gMembers': "{n} members",
  'so.gJoin': "Join the guild",
  'so.more': "Show more ({n})",
  'so.players': "Players",
  'so.friends': "Friends",
  'so.messages': "Messages",
  'so.search': "Search players by name",
  'so.count': "{n} players · {on} online",
  'so.none': "Nobody found.",
  'so.wants': "wants to be your friend",
  'so.requests': "Friend requests",
  'so.noFriends': "No friends yet. Find people under Players.",
  'so.pending': "Sent requests",
  'so.cancel': "Cancel",
  'so.decline': "Decline",
  'so.sayHi': "Say hi 👋",
  'so.noMsgs': "No messages yet.",
  'so.remove': "Remove friend",
  'so.onlineNow': "Online now",
  'so.nobody': "Nobody free online right now.",
  'so.invitesYou': "invites you to a raid",
  'so.waitingN': "{n} waiting",
  'so.join': "Join",
  'so.later': "Later",
  'so.reqToast': "{n} wants to be your friend",
  'so.nowFriends': "You and {n} are friends now",
  'so.invSent': "Invite sent",
  'so.invitePlayers': "Invite players",
  'so.inviteHint': "They get a card with a Join button that brings them into this room.",
  'gd.members': "{n} members",
  'gd.leave': "Leave guild",
  'gd.join': "Join",
  'gd.all': "All guilds",
  'gd.needRank': "Rank {n} or higher (you: {have})",
  'gd.needBuy': "At least one purchase with USDC/USDT",
  'gd.create': "Create a guild",
  'gd.name': "Guild name",
  'gd.tag': "Tag (2-5)",
  'gd.desc': "Short description (optional)",
  'gd.found': "Found the guild",
  'gd.count': "{n} members · {on} online",
  'gd.yours': "Your guild",
  'gd.list': "Guilds",
  'gd.none': "No guilds yet. Be the first.",
  'gd.err.signin': "Sign in first.",
  'gd.err.member': "Leave your guild first.",
  'gd.err.purchase': "Founding a guild needs one purchase with USDC/USDT first.",
  'gd.err.rank': "Founding a guild needs rank 20.",
  'gd.err.name': "Name: 3-24 letters, digits or spaces.",
  'gd.err.tag': "Tag: 2-5 letters or digits.",
  'gd.err.taken': "That name or tag is taken.",
  'pf.title': "Player",
  'pf.rank': "Rank {n}",
  'pf.guild': "Guild: {g}",
  'pf.raids': "Raids",
  'pf.wins': "Wins",
  'pf.kills': "Kills",
  'pf.extracts': "Extracted",
  'pf.best': "Best kills",
  'pf.time': "Played",
  'pf.ach': "Achievements",
  'pf.multi': "Best streak",
  'pf.since': "Playing since",
  'tb.readyWait': "{n} waiting",
  'mc.waiting': "{n} waiting",
  'pause.open': "Menu (Esc)",
  'pause.title': "Menu",
  'pause.resume': "Resume",
  'pause.settings': "Settings",
  'pause.leave': "Leave match",
  'pause.leaveLose': "Leave match (lose the stake)",
  'pause.leaveSure': "Press again to leave",
  'pause.keys': "Esc: back to the match",
  'pause.back': "← Back",
  'pause.on': "on",
  'pause.off': "off",
  'pause.practice': "Practice is paused.",
  'pause.practiceDead': "You're out. Leave whenever you like.",
  'pause.alive': "The match keeps going while this menu is open. Leave now and your runner stays behind: the stake stays in the match.",
  'pause.dead': "You're out. Leave anytime: anything you won still reaches your balance.",
  'gd.chat': "Chat",
  'gd.chatEmpty': "No messages yet. Say hi to your guild.",
  'gd.chatPh': "Message your guild…",
  'swap.min': "Smallest swap: {v}",
  'prep.waitingPeople': "No timer: invite friends, the raid can start once {min} players are ready. Every seat is a real player. {n} of {of} seats taken.",
  'prep.people': "Real players only: everyone here starts with a knife.",
  'shop.firstTopup': "First top-up doubles: get the same again in shop $, up to {v} extra.",
  'tour.who': "your handler",
  'tour.voice': "Voice on/off",
  'tour.skip': "Skip",
  'tour.next': "Next",
  'tour.done': "Let's go",
  'set.tour': "Tour",
  'set.tourNote': "Nyx walks you through the game again.",
  'set.tourBtn': "Replay the tour",
  'nyx.hello': "Hiii, runner! I'm Nyx, your guide tonight! Stick with me, and you'll walk out of your very first raid... rich!",
  'nyx.name': "Okay, first things first! Type a name. Everyone will see it, right above your head!",
  'nyx.nameOk': "Ooh, cute name! I like it!",
  'nyx.practice': "Now tap Practice! It's free, it's just bots. Perfect for your first run!",
  'nyx.practiceOk': "Yesss! Good call!",
  'nyx.modes': "These are the game modes! Today we play Raid, the classic one. Loot, fight, and get out! Tap Raid!",
  'nyx.modeOk': "Raid it is! Let's go!",
  'nyx.bag': "Here's the deal! Your stake goes in your bag. Take someone down, and their bag is yours! Go down... and yours is theirs. Eek!",
  'nyx.shop': "Outfits and weapon skins come from bags and crates, right here in the shop! And psst... there's a free one waiting for you!",
  'nyx.social': "Friends, messages, guilds! Bring your squad. Everything's more fun together!",
  'nyx.wallet': "Want real stakes? Sign in with a wallet, or just an email! Cash-outs only ever go back to your own address. Safe and sound!",
  'nyx.play': "Ready? Hit Play!",
  'nyx.ready': "This is the ready room! Press Ready, and we drop in! Woo!",
  'nyx.start': "We're in! Move with W, A, S, D. Aim with the mouse, and click to shoot! Space to dash!",
  'nyx.startTouch': "We're in! Your left thumb moves you. Hold Fire, on the right, and it aims for you!",
  'nyx.loot': "See that orange glow? That's money! Run right over it!",
  'nyx.pickup': "Yay! Your bag just got heavier!",
  'nyx.kill': "First blood! Nice shot! Grab what they dropped. Ooh, and a better gun!",
  'nyx.hurt': "Ouch, you're hurt! Health doesn't come back in a fight, so play it safe!",
  'nyx.storm': "The storm is coming! Stay inside the circle, quick!",
  'nyx.exit': "Ooh, that bag looks good on you! Find a green exit ring, and stand in it!",
  'nyx.extracting': "Hold still! Three seconds! Don't get hit!",
  'nyx.won': "You made it out! I knew you could do it! See you next raid, runner!",
  'nyx.dead': "Aww, it happens! Practice is free, so let's run it back!",
  'tour.yourMove': "Your move",
  'tour.skipStep': "Skip this step",
  'tour.again': "Tap Nyx to hear it again",
  'tour.replayHint': "Want the tour again? Settings → Tour.",
  'mode.zombies': "Zombies",
  'mode.zombies.d': "Co-op, alone or with up to 3 friends: 10 waves of the dead from every side, a boss on the last. Pick your weapon. Pays XP and titles.",
  'mode.gold': "Gold Rush",
  'mode.gold.d': "Bags of gold drop all over the quarry. Random guns, quick respawns. The one with the most bags takes the whole pot as shop credit.",
  'kind.zombie': "co-op · XP",
  'kind.gold': "one winner · shop credit",
  'tb.zFee': "entry · XP, titles",
  'tb.goldFee': "entry · winner takes all",
  'prep.zFee': "{v} entry",
  'prep.zSquad': "Squad",
  'prep.goldPot': "Prize (shop credit)",
  'zp.title': "Your weapon for the run",
  'zp.power': "Damage per second",
  'zp.melee': "no reload",
  'hud.waveK': "Wave",
  'hud.goldK': "Gold bags",
  'hud.startZ': "Hold the graveyard. They come from every side",
  'hud.startGold': "Grab the gold. Most bags wins it all",
  'hud.wave': "Wave {n} of {of}",
  'hud.bossWave': "FINAL WAVE · THE BOSS IS HERE",
  'hud.waveClear': "Wave {n} cleared",
  'hud.patched': "+35 HP",
  'hud.summon': "The boss calls the horde",
  'hud.bossDown': "THE BOSS IS DOWN · RUN CLEARED",
  'hud.bagsShort': "gold",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "next wave in {s}s",
  'hud.zLeft': "{n} left · {k} down",
  'hud.goldPlace': "place {p} · {d} deaths · prize {s}",
  'hud.bossHp': "BOSS {p}%",
  'hud.zBreak': "Reload and regroup: {s}s",
  'hud.zGoal': "Survive 10 waves · kill the boss",
  'hud.goldGoal': "Most gold bags at the whistle wins",
  'hud.zDown': "Down. You're back up when the next wave starts, if your squad holds",
  'feed.zYou': "The dead got you",
  'feed.zDown': "{name} was torn apart",
  'coach.z': "Stay on the plaza, back to back. Shoot the ones closest first; medkits drop from the dead",
  'coach.gold': "Run over gold bags to grab them. Die and half your bags spill, so grab, then stay alive",
  'warn.z60': "One minute left on the clock",
  'warn.z10': "10 seconds: kill the boss!",
  'warn.gold30': "30 seconds: grab what you can",
  'warn.gold10': "10 seconds left",
  'res.zCleared': "Run cleared",
  'res.zFell': "Overrun on wave {n}",
  'res.zWaves': "{n} / {of} waves",
  'res.zWonText': "Ten waves and their boss, with a squad of {s}. You dropped {k} of the dead.",
  'res.zText': "You dropped {k} of the dead (squad of {s}). The further you get, the more XP.",
  'res.zTime': "{t} on the clock",
  'res.goldWon': "Gold rush won",
  'res.goldLost': "Place {p} in the gold rush",
  'res.goldWonText': "{b} bags of gold, more than anyone. {c} is now in your shop balance.",
  'res.goldText': "You grabbed {b} bags; the winner had {top}. Only first place gets paid.",
  'xp.Waves survived': "Waves survived",
  'xp.Zombies': "Zombies",
  'xp.Boss slain': "Boss slain",
  'xp.Run cleared': "Run cleared",
  'xp.Gold bags': "Gold bags",
  'ach.graveyard_shift': "Graveyard Shift",
  'ach.hold_the_line': "Hold the Line",
  'ach.undertaker': "Undertaker",
  'ach.exterminator': "Exterminator",
  'ach.giant_slayer': "Giant Slayer",
  'ach.zombie_slayer': "Zombie Slayer",
  'ach.top_of_the_horde': "Top of the Horde",
  'ach.nightmare_walker': "Nightmare Walker",
  'ach.army_of_one': "Army of One",
  'ach.prospector': "Prospector",
  'ach.gold_fever': "Gold Fever",
  'ach.mother_lode': "Mother Lode",
  'ach.bag_hoarder': "Bag Hoarder",
  'ach.midas': "Midas",
  'achd.zRuns': "Play a zombie run",
  'achd.bestWave': "Clear wave {n} against the dead",
  'achd.zKills': "Kill {n} zombies",
  'achd.zBoss': "Land the killing blow on the boss",
  'achd.zClears': "Clear the zombie run {n} times",
  'achd.zMvp': "Clear a zombie run with the most kills in your squad",
  'achd.zSolo': "Clear the zombie run alone",
  'achd.goldRuns': "Play a gold rush",
  'achd.goldWins': "Win {n} gold rushes",
  'achd.bestGold': "Hold {n} gold bags at the end of one rush",
  'achd.goldBags': "Grab {n} gold bags in all",
};
