export default {
  'lobby.tagline': 'Apuesta. Saquea. Sal antes de la tormenta. <b>Nadie ve lo que hay en tu bolsa.</b>',
  'lobby.namePh': 'Nombre de tu corredor',
  'lobby.locker': 'Taquilla · skins · bolsas',
  'lobby.refill': 'Recargar monedas de prueba',
  'lobby.online': 'En línea',
  'lobby.practice': 'Práctica contra bots',
  'lobby.stakePer': 'Apuesta por incursión',
  'lobby.stakeWith': 'Apuesta con <span class="fine">cualquier moneda · mostrado en $ · las ganancias vuelven en la misma moneda</span>',
  'lobby.play': 'Jugar · apuesta {s}',
  'lobby.signIn': 'Inicia sesión para jugar',
  'lobby.how': 'Cómo se juega',
  'lobby.gore': '<b>Modo 18+.</b> Las extremidades salen volando y la sangre se queda en el suelo.',
  'lobby.fine': 'La práctica funciona en tu navegador. Todo el dinero aquí es de juego.',
  'how.1': '<b>Apuesta y prepárate.</b> Todos entran juntos con un cuchillo y 100 de salud. La mitad de tu apuesta va en tu bolsa y la otra mitad se reparte como botín.',
  'how.2': '<b>Coge el botín naranja.</b> Va a tu bolsa. Las bajas mejoran tu arma: cuchillo → pistola → escopeta → subfusil → rifle → francotirador láser.',
  'how.3': '<b>Sal con vida.</b> Quédate 3 segundos en una salida verde antes de que la tormenta la cierre. Te quedas toda la bolsa. Si mueres, cae para otro.',
  'how.keys': "<kbd>WASD</kbd> moverse · <kbd>ratón</kbd> apuntar · <kbd>clic</kbd> atacar · <kbd>Espacio</kbd> esquivar · <kbd>Q</kbd> fingir el tamaño de la bolsa · <kbd>M</kbd> sonido · <kbd>N</kbd> música",
  'how.fine': 'Cada incursión y cada logro dan XP de rango. Cada ascenso te presta un skin nuevo durante 3 días.',
  'net.practice': 'Solo tú y los bots, sin conexión.',
  'net.open': 'Conectado. En línea solo juegan personas reales.',
  'net.connecting': 'Conectando con el servidor…',
  'net.down': 'Servidor inaccesible. Reintentando… La práctica funciona sin conexión.',
  'net.lost': 'Conexión perdida. De vuelta a las mesas.',
  'q.pick': 'Elige una moneda para apostar.',
  'q.short': 'No tienes suficiente {c} para una apuesta de {s}. Elige otra moneda o una apuesta menor.',
  'q.shortDeposit': 'No tienes suficiente {c} para una apuesta de {s}. Elige otra moneda, una apuesta menor o deposita.',
  'q.stable': 'Apuestas {s} en {c}. Sal con vida y quédate con todo lo que llevas.',
  'q.coin': 'Apuestas {a} = {s} al precio de hoy. Las ganancias vuelven en {c} al mismo tipo.',
  'tb.live': 'Incursión en curso · {t}',
  'tb.ready': '{n} listos · {s}s',
  'tb.waiting': '{n} esperando',
  'tb.golden': 'Próxima: incursión dorada',
  'tb.jackpot': 'Bote {v}',
  'pcfg.title': 'Ajustes de práctica',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Fácil',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difícil',
  'pcfg.runners': 'Corredores en la incursión',
  'pcfg.time': 'Duración de la incursión',
  'rk.max': 'rango máximo',
  'rk.toNext': '{x} XP para el rango {r}',
  'rk.of': 'Rango {r} de 90',
  'rk.rank': 'Rango',
  'rk.up': 'Ascenso',
  'rk.xp': 'XP de rango',
  'xp.Raid': 'Incursión',
  'xp.kills': '{n} bajas',
  'xp.Damage': 'Daño',
  'xp.Time alive': 'Tiempo con vida',
  'xp.First blood': 'Primera sangre',
  'xp.Double kill': 'Doble baja',
  'xp.Triple kill': 'Triple baja',
  'xp.Rampage': 'Masacre',
  'xp.Godlike': 'Divino',
  'xp.Full arsenal': 'Arsenal completo',
  'xp.Extracted': 'Extracción',
  'xp.Profit': 'Beneficio',
  'xp.Practice ×0.5': 'Práctica ×0.5',
  'rk.newRank': "Nuevo rango",
  'rw.continue': "Continuar",
  'rw.title': 'Recompensa de ascenso',
  'rw.trial': 'tuyo durante 72 horas',
  'rw.try': 'Probártelo',
  'rw.share': 'Compartir ascenso',
  'prep.raid': 'Incursión {n} · apuesta {s}',
  'prep.readyUp': '¿Listo?',
  'prep.first': 'La cuenta atrás empieza cuando el primer corredor esté listo.',
  'prep.live': 'Hay una incursión en curso. Prepárate y entrarás en la siguiente con todos.',
  'prep.over': 'Incursión terminada. La sala se abre en un momento.',
  'prep.many': 'Aquí todos empiezan con cuchillo. Los bots entran en los últimos segundos.',
  'prep.bots': 'Los bots ocupan los huecos en los últimos segundos.',
  'prep.open': 'libre',
  'prep.pot': 'Bote',
  'prep.cancel': 'Cancelar · devolver {v}',
  'prep.ready': 'Listo · apuesta {v}',
  'prep.back': 'Volver a las mesas',
  'hud.bagPrivate': 'Tu bolsa · privada',
  'hud.lag': 'El servidor no responde · reconectando…',
  'hud.golden': 'Incursión dorada',
  'hud.goldenStart': 'Incursión dorada · botín del bote dentro',
  'hud.start': 'Cuchillo en mano · coge lo naranja · busca una salida',
  'hud.bagOpened': 'Bolsa abierta · +{v}',
  'hud.arsenal': "Arsenal completo · otra vez la pistola ★",
  'hud.unlocked': '{w} desbloqueado',
  'hud.pnl': '{d} frente a la apuesta de {s}',
  'hud.alive': '{n} dentro',
  'hud.next': 'Siguiente: {w}',
  'hud.final': 'Círculo final · última salida',
  'hud.closing': 'La tormenta se cierra · {t}',
  'hud.stormIn': 'La tormenta avanza en {t}',
  'hud.dash': 'Esquivar',
  'hud.bagLook': 'Aspecto de la bolsa',
  'hud.extracting': 'Extrayendo',
  'hud.holdStill': 'Quieto. Un impacto lo reinicia.',
  'hud.sound': 'Sonido',
  'hud.music': 'Música',
  'bluff.0': 'pequeña',
  'bluff.1': 'mediana',
  'bluff.2': 'gorda',
  'touch.move': 'mover',
  'touch.aim': 'apuntar · disparar',
  'touch.bag': 'Bolsa',
  'w.Knife': 'Cuchillo',
  'w.Pistol': 'Pistola',
  'w.Shotgun': 'Escopeta',
  'w.SMG': 'Subfusil',
  'w.Rifle': 'Rifle',
  'w.Laser sniper': 'Francotirador láser',
  'w.Hand Cannon': "Cañón de mano",
  'w.Auto Shotgun': "Escopeta automática",
  'w.PDW': "PDW",
  'w.Carbine': "Carabina",
  'w.Scout': "Explorador",
  'w.Machine Gun': "Ametralladora",
  'w.Magnum Sniper': "Francotirador Magnum",
  'hud.reloading': "Recargando",
  'streak.1': 'Primera sangre',
  'streak.2': 'Doble baja',
  'streak.3': 'Triple baja',
  'streak.4': 'Masacre',
  'streak.5': 'Divino',
  'streak.you1': 'Has hecho la primera sangre',
  'feed.storm': 'La tormenta te atrapó',
  'feed.droppedYou': '{name} te ha tumbado',
  'coach.storm': 'Estás en la tormenta · vuelve al círculo',
  'coach.touch': "Pulgar izquierdo para moverte · mantén Fuego: apunta solo al enemigo más cercano",
  'coach.keys': 'WASD para moverte · ratón para apuntar · clic para atacar',
  'coach.exit': 'Hora de salir · quédate 3 segundos en una SALIDA verde · las flechas del borde marcan el camino',
  'coach.loot': 'Coge el botín naranja · va a tu bolsa',
  'coach.kills': 'Las bajas mejoran tu arma · Espacio para esquivar',
  'coach.killsTouch': 'Las bajas mejoran tu arma · toca Esquivar',
  'spect.watching': 'Viendo a {name} · ◀ ▶ para cambiar',
  'spect.down': 'Has caído',
  'spect.results': 'Resultados',
  'res.extracted': 'Extraído',
  'res.storm': 'Te tragó la tormenta',
  'res.dropped': 'Abatido',
  'res.sealed': 'Encerrado dentro',
  'res.inside': '{k} bajas · {t} dentro',
  'res.out': 'Saliste con {p} con una apuesta de {s}: {d}.',
  'res.paid': 'Pagado {v} al tipo de entrada.',
  'res.killer': '{n} tiene tu bolsa ahora. Llevaba {v}, y solo vosotros dos lo sabréis.',
  'res.inStorm': 'Tu bolsa, {v}, está en la tormenta para quien se atreva.',
  'res.sealedText': 'La incursión se cerró contigo dentro. Tus {v} pasaron al botín de la siguiente.',
  'res.again': 'Jugar otra vez',
  'res.tables': 'Mesas',
  'res.share': 'Compartir',
  'share.title': 'Compartir',
  'share.x': 'Publicar en 𝕏',
  'share.copy': 'Copiar imagen',
  'share.save': 'Guardar PNG',
  'share.close': 'Cerrar',
  'lk.title': 'Taquilla',
  'lk.outfits': 'Atuendos',
  'lk.shop': 'Tienda',
  'lk.bags': 'Bolsas de suerte',
  'lk.sortDesc': "Más raros primero ↓",
  'lk.sortAsc': "Más comunes primero ↑",
  'lk.allGuns': "Todas las armas",
  'lk.takeOff': "Quitar",
  'lk.empty': "Aún no hay nada: las bolsas y cajas de la tienda llenan tu colección.",
  'lk.emptyTurrets': "Aún no tienes skins de torreta: vienen del pase de batalla.",
  'lk.pickSkin': "Toca un skin para verlo y luego equípalo.",
  'lk.all': 'Todos',
  'lk.owned': 'Míos',
  'lk.him': 'Él',
  'lk.her': 'Ella',
  'lk.shopUsd': '$ de tienda',
  'lk.shopNote': 'Recarga $ de tienda con USDC o USDT (los paquetes grandes dan bonus). Los $ de tienda solo se gastan aquí y no se pueden retirar. ¿Te faltan? La diferencia sale de tus USDC/USDT.',
  'lk.bagsNote': 'Probabilidades exactas, sorteadas en el servidor. Sin duplicados hasta completar una rareza, y un duplicado devuelve el 10% de su precio en $ de tienda. Garantía: Épico+ en 15 aperturas y Legendario+ en 60.',
  'lk.topupFrom': '+ {v} USDC/USDT para recargar',
  'lk.collected': '{a} / {b} conseguidos',
  'lk.equipped': 'Equipado',
  'lk.equip': 'Equipar',
  'lk.buy': 'Comprar',
  'lk.trialLeft': 'Prueba · quedan {t}',
  'lk.trialHow': 'Prueba por ascenso: tuyo {t} más. Cómpralo para quedártelo.',
  'lk.free': 'Gratis para todos.',
  'lk.inCollection': 'En tu colección.',
  'lk.buyOrBag': 'Cómpralo aquí o prueba suerte con una bolsa.',
  'lk.tryingOn': 'Probándotelo.',
  'lk.bonus': '+{n}% de bonus',
  'lk.pay': 'pagas {v}',
  'lk.jackpot': 'Premio gordo',
  'lk.epicIn': 'Épico+ en',
  'lk.legIn': 'Legendario+ en',
  'lk.openFree': 'Abrir · gratis',
  'lk.buyOpen': 'Comprar y abrir',
  'lk.pityDrop': 'garantía',
  'lk.dup': 'Ya es tuyo · {v} de vuelta',
  'lk.new': '<b>Nuevo</b> en tu colección',
  'lk.jackpotIs': 'el premio gordo es {r}',
  'lk.showOff': 'Presumir en X',
  'lk.postMiss': 'Publicar el fallo en X',
  'lk.another': 'Abrir otra',
  'lk.free1': 'gratis',
  'lk.back': 'Volver a la taquilla',
  'lk.yours': '{n} es tuyo.',
  'r.common': 'Común',
  'r.rare': 'Raro',
  'r.epic': 'Épico',
  'r.legendary': 'Legendario',
  'r.mythic': 'Mítico',
  'r.exotic': 'Exótico',
  'ach.title': 'Logros',
  'ach.button': 'Logros',
  'ach.intro': 'Cada uno da XP de rango una vez y desbloquea su nombre como título que puedes llevar.',
  'ach.wear': 'Llevar título',
  'ach.worn': 'Puesto',
  'ach.wearing': 'Título:',
  'ach.takeOff': 'quitar',
  'ach.noTitle': 'Sin título',
  'ach.unlocked': 'Logro desbloqueado',
  'ach.seeAll': 'Todos los logros',
  'achd.raids': 'Juega {n} incursiones',
  'achd.extracts': 'Extráete {n} veces',
  'achd.kills': 'Consigue {n} bajas',
  'achd.bestKills': '{n} bajas en una incursión',
  'achd.bestMulti': 'Una baja múltiple ×{n}',
  'achd.prestige': 'Completa el arsenal {n} veces',
  'achd.firstBloods': 'Haz la primera sangre {n} veces',
  'achd.secs': 'Pasa {n} h dentro de incursiones',
  'achd.bestReturn': 'Sal con {n}× tu apuesta',
  'achd.golden': 'Extráete de una incursión dorada',
  'achd.lastExit': 'Sal por la última salida',
  'achd.pacifist': 'Extráete sin una sola baja',
  'achd.rank': 'Alcanza el rango {n}',
  'achd.outfits': 'Consigue {n} atuendos',
  'ach.gunslinger': "Pistolero",
  'ach.close_quarters': "Cuerpo a cuerpo",
  'ach.spray_and_pray': "Ráfaga ciega",
  'ach.rifleman': "Fusilero",
  'ach.marksman': "Tirador",
  'ach.deadeye': "Ojo de halcón",
  'ach.blade_dancer': "Danzante de hoja",
  'ach.shadow_blade': "Hoja sombría",
  'ach.deathmatch_king': "Rey del todos contra todos",
  'ach.duelist': "Duelista",
  'ach.squad_goals': "Espíritu de equipo",
  'ach.one_shot_one_kill': "Un disparo, una baja",
  'ach.specialist': "Especialista",
  'ach.engineer': "Ingeniero",
  'ach.ranked_debut': "Debut clasificatorio",
  'ach.ranked_grinder': "Currante clasificatorio",
  'ach.ranked_victor': "Vencedor clasificatorio",
  'ach.gold_league': "Liga de Oro",
  'ach.diamond_league': "Liga de Diamante",
  'ach.neon_legend': "Leyenda Neón",
  'ach.unboxer': "Desempaquetador",
  'ach.case_hunter': "Cazacajas",
  'ach.case_lord': "Señor de las cajas",
  'ach.armory': "Arsenal",
  'ach.arsenal_baron': "Barón del arsenal",
  'ach.pass_holder': "Portador del pase",
  'ach.pass_maxed': "Pase completo",
  'ach.neon_bearer': "Portador de neón",
  'ach.by_a_thread': "Por un pelo",
  'ach.untouchable': "Intocable",
  'ach.ghost_walker': "Paso fantasma",
  'ach.one_tap': "Un toque",
  'achd.kHandgun': "Consigue {n} bajas con pistolas",
  'achd.kShotgun': "Consigue {n} bajas con escopetas",
  'achd.kSmg': "Consigue {n} bajas con subfusiles",
  'achd.kRifle': "Consigue {n} bajas con rifles y ametralladoras",
  'achd.kSniper': "Consigue {n} bajas con francotiradores",
  'achd.kKnife': "Consigue {n} bajas con cuchillo",
  'achd.dmWins': "Gana {n} todos contra todos",
  'achd.duelWins': "Gana {n} duelos",
  'achd.teamWins': "Gana {n} partidas por equipos",
  'achd.hcWins': "Gana {n} partidas hardcore",
  'achd.weaponWins': "Gana {n} partidas de un arma",
  'achd.turretKills': "Consigue {n} bajas con torretas en Armas + Láseres",
  'achd.rankedGames': "Juega {n} clasificatorias",
  'achd.rankedWins': "Gana {n} clasificatorias",
  'achd.bestDiv': "Llega a {n} en clasificatoria",
  'achd.opened': "Abre {n} cajas y bolsas",
  'achd.wskins': "Ten {n} skins de arma",
  'achd.passTier': "Llega al nivel {n} del pase",
  'achd.stitles': "Gana un título de temporada",
  'achd.clutch': "Sal con 10 de vida o menos",
  'achd.flawless': "Sal tras 2+ minutos sin recibir un golpe",
  'achd.ninjaWin': "Gana una partida de bote sin una sola baja",
  'achd.oneShots': "Lleva a {n} corredores de vida completa a cero de un golpe",
  'ach.secret': "Secreto",
  'ach.secretDesc': "Sigue jugando: se revela cuando lo consigas.",
  'r.mystery': "Misterio",
  'ach.rookie': 'Novato',
  'ach.regular': 'Habitual',
  'ach.veteran': 'Veterano',
  'ach.lifer': 'De por vida',
  'ach.eternal': 'Eterno',
  'ach.escape_artist': 'Escapista',
  'ach.ghost': 'Fantasma',
  'ach.smuggler': 'Contrabandista',
  'ach.phantom': 'Espectro',
  'ach.first_kill': 'Primera baja',
  'ach.hunter': 'Cazador',
  'ach.butcher': 'Carnicero',
  'ach.reaper': 'Segador',
  'ach.apex': 'Depredador',
  'ach.rampage': 'Masacre',
  'ach.one_man_army': 'Ejército de uno',
  'ach.double_tap': 'Doble toque',
  'ach.triple_threat': 'Triple amenaza',
  'ach.godlike': 'Divino',
  'ach.full_arsenal': 'Arsenal completo',
  'ach.arsenal_master': 'Maestro del arsenal',
  'ach.first_blood': 'Primera sangre',
  'ach.opener': 'El que abre',
  'ach.night_shift': 'Turno de noche',
  'ach.insomniac': 'Insomne',
  'ach.double_up': 'Doblete',
  'ach.big_bag': 'Bolsa grande',
  'ach.gold_rush': 'Fiebre del oro',
  'ach.last_one_out': 'El último en salir',
  'ach.pacifist': 'Pacifista',
  'ach.seasoned': 'Curtido',
  'ach.officer': 'Oficial',
  'ach.commander': 'Comandante',
  'ach.legend': 'Leyenda',
  'ach.collector': 'Coleccionista',
  'ach.curator': 'Conservador',
  'ach.hoarder': 'Acaparador',
  'intro.tag': "Apuesta. Saquea. Sal.",
  'intro.go': "Entrar",
  'intro.fonts': "Afilando cuchillos…",
  'intro.world': "Pintando la oscuridad…",
  'intro.connect': "Buscando incursión…",
  'intro.profile': "Preparando tu bolsa…",
  'intro.ready': "Listo",
  'tb.wallet': "Cartera",
  'tb.shop': "$ de tienda",
  'nav.play': "Jugar",
  'nav.shop': "Tienda",
  'nav.inventory': "Inventario",
  'nav.swap': "Intercambio",
  'nav.chat': "Chat",
  'nav.achievements': "Logros",
  'nav.pass': "Pase",
  'bp.season': "Temporada {n}",
  'bp.ends': "termina en {d}d {h}h",
  'bp.tier': "Nivel {n}/{m}",
  'bp.xp': "{a}/{b} XP para el siguiente nivel",
  'bp.maxed': "Todos los niveles completados",
  'bp.how': "Cada incursión llena el pase con la misma XP que tu rango.",
  'bp.free': "Gratis",
  'bp.premium': "Premium",
  'bp.buy': "Pase premium · {v}",
  'bp.owned': "Premium activo",
  'bp.perks': "Los 50 niveles de recompensas: armaduras Señor de la Guerra y Ápice, 2 skins de torreta, 5 skins de arma de temporada, cajas y $.",
  'bp.claim': "Reclamar",
  'bp.claimAll': "Reclamar todo ({n})",
  'bp.claimed': "Reclamado",
  'bp.limited': "Solo esta temporada",
  'bp.turrets': "Skins de torreta",
  'bp.turretsNote': "Tus torretas en Armas + Láseres.",
  'bp.equip': "Equipar",
  'bp.equipped': "Equipado",
  'bp.none': "Normal",
  'bp.up': "Pase de batalla: ¡nivel {n}!",
  'bp.got': "Reclamado: {x}",
  'bp.credit': "+{v} de tienda",
  'mode.ranked': "Clasificatoria",
  'mode.ranked.d': "Battle royale por tu rango de temporada. Sube de Bronce a Leyenda Neón; los mejores puestos ganan un giro extra.",
  'nav.ranked': "Clasificatoria",
  'rd.title': "Clasificatoria · Temporada {n}",
  'rd.pos': "#{n} de {m}",
  'rd.unranked': "Juega una partida clasificatoria para entrar en la tabla.",
  'rd.play': "Jugar clasificatoria",
  'rd.games': "Partidas",
  'rd.wins': "Victorias",
  'rd.top3': "Top 3",
  'rd.kills': "Bajas",
  'rd.winrate': "% de victorias",
  'rd.player': "Jugador",
  'rd.div': "División",
  'rd.div.bronze': "Bronce",
  'rd.div.silver': "Plata",
  'rd.div.gold': "Oro",
  'rd.div.platinum': "Platino",
  'rd.div.diamond': "Diamante",
  'rd.div.master': "Maestro",
  'rd.div.legend': "Leyenda Neón",
  'rd.titles': "Títulos de temporada",
  'rd.titlesNote': "Salen del giro extra de la clasificatoria. Brillan en neón sobre tu nombre y dan XP extra hasta el fin de temporada.",
  'rd.wear': "Llevar",
  'rd.off': "Quitar",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "temporada terminada",
  'rd.board': "Tabla de la temporada",
  'rd.empty': "Nadie ha jugado clasificatoria esta temporada. Sé el primero.",
  'rd.place': "Puesto #{p} de {n}",
  'rd.promoted': "¡ascenso!",
  'rd.demoted': "descenso",
  'rd.practice': "Práctica: tu rango no cambia.",
  'rd.spin': "Giro extra",
  'rd.spinWhy': "por el puesto #{p}",
  'rd.won': "Has ganado:",
  'rd.wornNow': "Tu nuevo título ya brilla sobre ti.",
  'st.contender': "Aspirante",
  'st.elite': "Élite",
  'st.champion': "Campeón",
  'xp.Season title': "Título de temporada",
  'news.title': "Novedades",
  'news.ok': "Entendido",
  'news.note': "Cada actualización, con fecha y hora.",
  'news.open': "Abrir",
  'stake.own': "Tu apuesta",
  'stake.range': "Apuesta de $0.10 a $10.000",
  'nav.settings': "Ajustes",
  'modes.title': "Modo de juego",
  'kind.raid': "extracción",
  'kind.br': "el ganador se lleva el bote",
  'kind.team': "bote de equipo",
  'mode.raid': "Incursión",
  'mode.raid.d': "Saquea, pelea y sal por una salida. Te quedas lo que llevas.",
  'mode.br': "Battle Royale",
  'mode.br.d': "Hasta 20 corredores. El último en pie se lleva todo el bote.",
  'mode.duel': "Duelo",
  'mode.duel.d': "Uno contra uno. El ganador se lleva ambas apuestas.",
  'mode.knives': "Solo cuchillos",
  'mode.knives.d': "Solo cuchillas toda la incursión. Gana el último en pie.",
  'mode.pistols': "Solo pistolas",
  'mode.pistols.d': "Solo pistolas. Gana el último en pie.",
  'mode.shotguns': "Solo escopetas",
  'mode.shotguns.d': "De cerca y a lo bestia. Gana el último en pie.",
  'mode.rifles': "Solo rifles",
  'mode.rifles.d': "Tiroteos a media distancia. Gana el último en pie.",
  'mode.snipers': "Solo francotiradores",
  'mode.snipers.d': "Miras láser por todas partes. Gana el último en pie.",
  'mode.team2': "Equipos 2 vs 2",
  'mode.team2.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'mode.team4': "Equipos 4 vs 4",
  'mode.team4.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'mode.team8': "Equipos 8 vs 8",
  'mode.team8.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'hud.pot': "Bote",
  'hud.left': "Quedan {n} · apuesta {s}",
  'hud.teamsLeft': "Quedan {n} equipos · apuesta {s}",
  'hud.startPot': "El último en pie se lleva el bote",
  'hud.startTeam': "Quédate con tu equipo · acaba con el otro",
  'hud.goldenPot': "Incursión dorada · premio añadido al bote",
  'coach.pot': "Aquí no hay salidas · quédate en el círculo · gana el último en pie",
  'coach.team': "Nombres verdes: tu equipo · rojos: el enemigo",
  'warn.exit30': "30s · llega a una salida abierta",
  'warn.exit10': "10s · extráete o piérdelo todo",
  'warn.pot30': "30s · la tormenta se cierra",
  'warn.pot10': "10s · gana quien tenga más vivos",
  'storm.final': "Colapso final · solo la última salida",
  'storm.finalPot': "Colapso final · no hay dónde esconderse",
  'storm.closing': "La tormenta se acerca",
  'storm.in5': "La tormenta avanza en 5s",
  'feed.youDropped': "Tumbaste a {name}",
  'feed.stormTook': "La tormenta se tragó a {name}",
  'feed.dropped': "{a} tumbó a {b}",
  'feed.down': "{name} cayó",
  'feed.extracted': "{name} se extrajo",
  'feed.exitClosed': "La salida {name} está cerrada",
  'spect.settling': "Tu resultado llega cuando se cierre la incursión.",
  'res.victory': "Victoria",
  'res.teamWon': "Tu equipo ganó",
  'res.defeated': "Derrota",
  'res.wonText': "Te llevaste {p} con una apuesta de {s}.",
  'res.lostPot': "El bote fue para el último en pie.",
  'res.teamLost': "El otro equipo se llevó el bote.",
  'xp.Victory': "Victoria",
  'ach.champion': "Campeón",
  'ach.warlord': "Señor de la guerra",
  'achd.wins': "Gana {n} incursiones con bote",
  'lk.weapons': "Skins de armas",
  'lk.onlyBags': "Los skins solo salen de bolsas y cajas de la tienda.",
  'lk.toShop': "Abrir la tienda",
  'lk.toOpen': "{n} por abrir",
  'lk.limited': "Limitado · {n}",
  'lk.minted': "{a} de {b} acuñados",
  'lk.plain': "Estándar",
  'lk.fromBags': "Sale de las bolsas de atuendos de la tienda.",
  'lk.fromCrates': "Sale de las cajas de armas de la tienda.",
  'lk.trialHow2': "Prueba por ascenso: tuyo {t} más.",
  'lk.weaponHow': "Elige un acabado tuyo para equiparlo. Todos en la incursión lo ven.",
  'fx.glow': "aura",
  'fx.pulse': "aura pulsante",
  'fx.ghost': "espectral",
  'fx.laser': "ojos láser",
  'fx.rainbow': "prismático",
  'fx.fire': "en llamas",
  'fx.gold': "oro líquido",
  'fx.holo': "holograma",
  'fx.glitch': "glitch",
  'fx.lightning': "rayos",
  'fx.galaxy': "galaxia",
  'fx.sparks': "chispas",
  'fx.frost': "escarcha",
  'fx.money': "lluvia de dinero",
  'fx.matrix': "lluvia de código",
  'fx.shadow': "humo de sombra",
  'fx.cape': "capa",
  'box.c-samurai': "Caja Ciber Samurái",
  'box.c-neon': "Caja Noches de Neón",
  'box.c-arctic': "Caja Ártica",
  'box.c-inferno': "Caja Infierno",
  'box.c-crypto': "Caja Reyes Cripto",
  'box.c-toxic': "Caja Páramo Tóxico",
  'box.c-toon': "Caja Villa Toon",
  'box.c-knife': "Caja de cuchillos",
  'box.c-pistol': "Caja de pistolas",
  'box.c-smg': "Caja de subfusiles",
  'box.c-rifle': "Caja de rifles",
  'box.c-heavy': "Caja pesada",
  'box.c-sniper': "Caja de francotirador",
  'box.b-crypto': "Bolsa Memes Cripto",
  'box.b-heroes': "Bolsa Héroes del Multiverso",
  'box.b-monsters': "Bolsa Monstruos y Mitos",
  'box.b-cyber': "Bolsa Ciber Calle",
  'box.b-toon': "Bolsa Amigos Toon",
  'shop.g.theme': "Colecciones",
  'shop.g.class': "Cajas por clase de arma",
  'shop.g.tier': "Cajas por nivel",
  'shop.contents': "Contenido · {n} objetos",
  'box.street': "Bolsa callejera",
  'box.vault': "Bolsa de la cámara",
  'box.golden': "Bolsa dorada",
  'box.elite': "Bolsa élite",
  'box.diamond': "Bolsa de diamante",
  'box.obsidian': "Bolsa de obsidiana",
  'box.royal': "Bolsa real",
  'box.apex': "Bolsa Apex",
  'box.genesis': "Bolsa Génesis",
  'box.w-scrap': "Caja de chatarra",
  'box.w-armory': "Caja del arsenal",
  'box.w-brass': "Caja de latón",
  'box.w-specops': "Caja de operaciones especiales",
  'box.w-diamond': "Caja de diamante",
  'box.w-obsidian': "Caja de obsidiana",
  'box.w-royal': "Caja real",
  'box.w-apex': "Caja Apex",
  'box.w-genesis': "Caja Génesis",
  'shop.topup': "Recargar $ de tienda",
  'shop.bags': "Bolsas de atuendos",
  'shop.crates': "Cajas de armas",
  'shop.bagsNote': "Atuendos para tu corredor. Nueve niveles: cuanto más cara la bolsa, mejores probabilidades.",
  'shop.cratesNote': "Skins para tus armas y cuchillo, se venden aparte de los atuendos. Nueve niveles.",
  'shop.fair': "Probabilidades exactas, sorteadas en el servidor. Garantía: Épico+ en {e} aperturas, Legendario+ en {l}.",
  'shop.odds': "Probabilidades y garantía",
  'shop.qty': "Cantidad",
  'shop.open': "Abrir ×{n}",
  'shop.limited': "Ediciones limitadas",
  'shop.soldOut': "Agotado",
  'shop.dup': "Duplicado · +{v}",
  'shop.new': "Nuevo",
  'shop.back': "{v} de vuelta",
  'shop.equipBest': "Equipar {n}",
  'inv.wallet': "Cartera",
  'inv.deposit': "Depositar · retirar",
  'inv.walletNote': "Tokens reales que la casa guarda para ti. Retira cuando quieras a la dirección con la que entraste.",
  'inv.playNote': "Dinero de juego en este navegador. Recarga cuando quieras.",
  'inv.shopNote': "Se compra con USDC/USDT y solo se gasta en bolsas y cajas. No se puede retirar.",
  'inv.unopened': "Sin abrir",
  'inv.collection': "Colección",
  'inv.opened': "Abiertas",
  'inv.career': "Carrera",
  'inv.raids': "Incursiones",
  'inv.kills': "Bajas",
  'inv.extracts': "Extracciones",
  'inv.wins': "Botes ganados",
  'inv.best': "Mejor incursión (bajas)",
  'inv.time': "Tiempo dentro",
  'swap.game': "Saldo del juego",
  'swap.gameNote': "Al instante, al precio actual, {f}% de comisión.",
  'swap.gameOff': "Los intercambios dentro del juego están desactivados en este servidor. Usa el de tu cartera abajo.",
  'swap.from': "Das",
  'swap.to': "Recibes",
  'swap.have': "Tienes",
  'swap.flip': "Invertir",
  'swap.go': "Intercambiar",
  'swap.short': "Saldo insuficiente",
  'swap.done': "Cambiaste {a} por {b}.",
  'swap.wallet': "Tu cartera",
  'swap.signIn': "Conecta una cartera Starknet para intercambiar allí con AVNU.",
  'swap.needChain': "Los intercambios con AVNU funcionan con una cartera Starknet real en modo en línea.",
  'swap.slippage': "Deslizamiento máx.",
  'swap.quoting': "Buscando la mejor ruta…",
  'swap.impact': "impacto en el precio {p}%",
  'swap.goAvnu': "Intercambiar con AVNU",
  'swap.noQuote': "Ahora no hay ruta para ese par.",
  'swap.sent': "Intercambio enviado: {tx}",
  'swap.walletNote': "AVNU busca la ruta entre los exchanges de Starknet. Firmas en tu cartera; el juego nunca guarda estos tokens.",
  'chat.ph': "Di algo…",
  'chat.send': "Enviar",
  'chat.empty': "Aún no hay mensajes. Di gm.",
  'chat.online': "Todo el lobby ve esto. Sé amable.",
  'chat.practice': "La práctica es sin conexión: solo escuchan los bots.",
  'set.graphics': "Gráficos",
  'set.quality': "Calidad",
  'set.qualityNote': "Auto baja el detalle cuando van lentos los fotogramas.",
  'set.auto': "Auto",
  'set.high': "Alta",
  'set.medium': "Media",
  'set.low': "Baja",
  'set.shake': "Vibración de pantalla",
  'set.motion': "Animaciones del menú",
  'set.display': "Visualización",
  'set.skins': "Skins",
  'set.skinsNote': "De quién dibujar atuendos y skins de armas.",
  'set.skinsAll': "Todos",
  'set.skinsMine': "Solo los míos",
  'set.skinsNone': "Ninguno",
  'set.names': "Nombres sobre los corredores",
  'set.titles': "Títulos sobre los nombres",
  'set.controls': "Controles",
  'set.stick': "Tamaño de los sticks táctiles",
  'set.lefty': "Zurdo (táctil)",
  'set.leftyNote': "Intercambia los sticks de mover y apuntar.",
  'set.audio': "Audio",
  'set.sound': "Volumen de efectos",
  'set.music': "Volumen de música",
  'set.track': "Banda sonora",
  'set.trackAuto': "Mezcla",
  'set.trackNote': "Una pista distinta en cada partida, o quédate con tu favorita.",
  'pause.nextTrack': "Siguiente pista ⏭",
  'set.language': "Idioma",
  'shop.exoticIn': "Exótico en",
  'shop.guarantee': "Exótico garantizado en {n} aperturas",
  'set.voice': "Locutor",
  'mode.dm': "Todos contra todos",
  'mode.dm.d': "Cada uno por su cuenta, reapareces tras cada muerte. Quien tenga más bajas al final se lleva el bote.",
  'mode.gl': "Armas + Láseres",
  'mode.gl.d': "Todos contra todos con tienda: las bajas dan créditos para botiquines, torretas y minas láser.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Vida mínima: una bala y caes. El último en pie se lleva el bote.",
  'kind.dm': "más bajas se lleva el bote",
  'hud.startDm': "Quien tenga más bajas cuando el reloj llegue a cero se lleva el bote",
  'hud.startGl': "Las bajas dan créditos · 1 botiquín · 2 torreta · 3 mina láser",
  'hud.startHc': "Un impacto y caes. Que cada disparo cuente.",
  'hud.respawned': "De vuelta",
  'hud.respawnIn': "Reapareces en {s}s",
  'hud.tookLead': "Has tomado la delantera",
  'hud.lostLead': "Has perdido la delantera",
  'hud.dmScore': "{k} bajas · {d} muertes · #{p}",
  'hud.dmGoal': "La primera baja toma la delantera",
  'hud.oneHit': "1 IMPACTO",
  'feed.leader': "{name} toma la delantera con {k}",
  'gl.medkit': "Botiquín",
  'gl.turret': "Torreta",
  'gl.mine': "Mina láser",
  'gl.no.cash': "Créditos insuficientes",
  'gl.no.full': "Ya tienes la vida al máximo",
  'gl.no.limit': "Límite alcanzado",
  'gl.no.wall': "Demasiado cerca de una pared",
  'res.dmLost': "Terminaste #{p}",
  'res.dmText': "{k} bajas, {d} muertes. El ganador tuvo {top}.",
  'coach.dm': "Reapareces · gana quien tenga más bajas al acabar el tiempo",
  'coach.gl': "Las bajas dan créditos · gástalos en un botiquín ✚, una torreta ◈ o una mina láser ⌁",
  'set.voiceNote': "Locutor grabado (inglés, ucraniano, español, francés, portugués; inglés para los demás idiomas).",
  'net.waking': "Despertando el servidor (el hosting gratuito se duerme cuando nadie juega, hasta un minuto)… Mientras tanto, la práctica funciona.",
  'shop.bulk': "Cada caja n.º {n} gratis",
  'shop.bulkOn': "Cajas gratis incluidas: {n}",
  'net.online': "{n} en línea",
  'st.title': "Primeros pasos",
  'st.signin': "Inicia sesión",
  'st.signin.d': "Con tu billetera Starknet, Cartridge o correo.",
  'st.signin.go': "Entrar",
  'st.fund': "Añade fondos",
  'st.fund.d': "Envía algunos tokens de tu billetera a tu saldo de juego. Puedes retirar cuando quieras.",
  'st.fundTest': "Testnet: STRK gratis en starknet-faucet.vercel.app.",
  'st.fund.go': "Depositar",
  'st.coin': "Elige tu moneda",
  'st.coin.d': "Elige abajo con qué moneda apuestas. Las ganancias vuelven en la misma moneda.",
  'st.coin.go': "Ver monedas",
  'st.play': "Juega tu primera partida",
  'st.play.d': "Elige modo y apuesta, pulsa Jugar y luego Listo.",
  'st.play.go': "Jugar",
  'touch.fire': "Fuego",
  'rot.title': "Gira el teléfono",
  'rot.sub': "El raid se juega mejor en horizontal: muévete a la izquierda, dispara a la derecha.",
  'rot.anyway': "Jugar en vertical",
  'prep.waiting': "Esperando jugadores",
  'prep.waitingMe': "Sin temporizador: invita a tus amigos y pulsa Empezar cuando estéis listos. Los bots ocupan los huecos. {n} de {of} plazas ocupadas.",
  'prep.waitingJoin': "{n} de {of} plazas ocupadas. Apuesta y pulsa Listo para unirte.",
  'prep.firstWait': "Pulsa Listo: la sala espera a todos, sin temporizador.",
  'prep.start': "Empezar ya",
  'nav.friends': "Amigos",
  'nav.guilds': "Gremios",
  'so.now': "ahora",
  'so.min': "hace {n} min",
  'so.hr': "hace {n} h",
  'so.day': "hace {n} d",
  'so.seen': "Visto {t}",
  'so.st.lobby': "En línea",
  'so.st.waiting': "Esperando en una sala",
  'so.st.raid': "En una incursión",
  'so.friend': "Amigo",
  'so.sent': "Solicitud enviada",
  'so.accept': "Aceptar",
  'so.add': "Añadir amigo",
  'so.invited': "Invitado",
  'so.invite': "Invitar",
  'so.message': "Mensaje",
  'so.onlineOnly': "Amigos, mensajes y gremios funcionan al jugar en línea.",
  'so.gInvite': "Al gremio",
  'so.gInvited': "Invitado",
  'so.gInviteSent': "Invitación al gremio enviada",
  'so.gInvitesYou': "te invita a su gremio",
  'so.gMembers': "{n} miembros",
  'so.gJoin': "Unirse al gremio",
  'so.more': "Mostrar más ({n})",
  'so.players': "Jugadores",
  'so.friends': "Amigos",
  'so.messages': "Mensajes",
  'so.search': "Buscar jugadores por nombre",
  'so.count': "{n} jugadores · {on} en línea",
  'so.none': "No se encontró a nadie.",
  'so.wants': "quiere ser tu amigo",
  'so.requests': "Solicitudes de amistad",
  'so.noFriends': "Aún no tienes amigos. Búscalos en Jugadores.",
  'so.pending': "Solicitudes enviadas",
  'so.cancel': "Cancelar",
  'so.decline': "Rechazar",
  'so.sayHi': "Saluda 👋",
  'so.noMsgs': "Aún no hay mensajes.",
  'so.remove': "Eliminar amigo",
  'so.onlineNow': "En línea ahora",
  'so.nobody': "No hay nadie libre en línea ahora.",
  'so.invitesYou': "te invita a una incursión",
  'so.waitingN': "{n} esperando",
  'so.join': "Unirse",
  'so.later': "Luego",
  'so.reqToast': "{n} quiere ser tu amigo",
  'so.nowFriends': "Ahora tú y {n} sois amigos",
  'so.invSent': "Invitación enviada",
  'so.invitePlayers': "Invitar jugadores",
  'so.inviteHint': "Recibirán una tarjeta con un botón Unirse que los trae a esta sala.",
  'gd.members': "{n} miembros",
  'gd.leave': "Salir del gremio",
  'gd.join': "Unirse",
  'gd.all': "Todos los gremios",
  'gd.needRank': "Rango {n} o más (tú: {have})",
  'gd.needBuy': "Al menos una compra con USDC/USDT",
  'gd.create': "Crear un gremio",
  'gd.name': "Nombre del gremio",
  'gd.tag': "Etiqueta (2-5)",
  'gd.desc': "Descripción corta (opcional)",
  'gd.found': "Fundar el gremio",
  'gd.count': "{n} miembros · {on} en línea",
  'gd.yours': "Tu gremio",
  'gd.list': "Gremios",
  'gd.none': "Aún no hay gremios. Sé el primero.",
  'gd.err.signin': "Inicia sesión primero.",
  'gd.err.member': "Sal de tu gremio primero.",
  'gd.err.purchase': "Fundar un gremio requiere una compra con USDC/USDT.",
  'gd.err.rank': "Fundar un gremio requiere rango 20.",
  'gd.err.name': "Nombre: 3-24 letras, dígitos o espacios.",
  'gd.err.tag': "Etiqueta: 2-5 letras o dígitos.",
  'gd.err.taken': "Ese nombre o etiqueta ya existe.",
  'pf.title': "Jugador",
  'pf.rank': "Rango {n}",
  'pf.guild': "Gremio: {g}",
  'pf.raids': "Incursiones",
  'pf.wins': "Victorias",
  'pf.kills': "Bajas",
  'pf.extracts': "Extracciones",
  'pf.best': "Récord de bajas",
  'pf.time': "Jugado",
  'pf.ach': "Logros",
  'pf.multi': "Mejor racha",
  'pf.since': "Juega desde",
  'tb.readyWait': "{n} esperando",
  'mc.waiting': "{n} esperando",
  'pause.open': "Menú (Esc)",
  'pause.title': "Menú",
  'pause.resume': "Continuar",
  'pause.settings': "Ajustes",
  'pause.leave': "Salir de la partida",
  'pause.leaveLose': "Salir (pierdes la apuesta)",
  'pause.leaveSure': "Pulsa otra vez para salir",
  'pause.keys': "Esc: volver a la partida",
  'pause.back': "← Atrás",
  'pause.on': "sí",
  'pause.off': "no",
  'pause.practice': "La práctica está en pausa.",
  'pause.practiceDead': "Estás fuera. Sal cuando quieras.",
  'pause.alive': "La partida sigue mientras el menú está abierto. Si sales ahora, tu corredor se queda y la apuesta se queda en la partida.",
  'pause.dead': "Estás fuera. Sal cuando quieras: lo que hayas ganado llegará igual a tu saldo.",
  'gd.chat': "Chat",
  'gd.chatEmpty': "Aún no hay mensajes. Saluda a tu gremio.",
  'gd.chatPh': "Escribe a tu gremio…",
  'swap.min': "Intercambio mínimo: {v}",
  'prep.waitingPeople': "Sin temporizador: invita a amigos, la incursión empieza cuando haya {min} jugadores listos. Solo jugadores reales. {n} de {of} plazas ocupadas.",
  'prep.people': "Solo jugadores reales: aquí todos empiezan con un cuchillo.",
  'shop.firstTopup': "La primera recarga se duplica: recibe lo mismo otra vez en $ de tienda, hasta {v} extra.",
  'tour.who': "tu contacto",
  'tour.voice': "Voz sí/no",
  'tour.skip': "Saltar",
  'tour.next': "Siguiente",
  'tour.done': "Vamos",
  'set.tour': "Tutorial",
  'set.tourNote': "Nyx te enseña el juego otra vez.",
  'set.tourBtn': "Repetir el tutorial",
  'nyx.hello': "¡Holaaa, corredor! Soy Nyx, ¡tu guía esta noche! Quédate conmigo y saldrás de tu primera incursión... ¡rico!",
  'nyx.name': "¡Primero lo primero! Escribe el nombre de tu corredor y toca Listo. ¡Todos lo verán sobre tu cabeza!",
  'nyx.nameOk': "¡Oh, qué nombre tan lindo! ¡Me gusta!",
  'nyx.practice': "¡Ahora toca Práctica! Es gratis, solo bots. ¡Perfecto para tu primera partida!",
  'nyx.practiceOk': "¡Síii! ¡Buena elección!",
  'nyx.modes': "¡Estos son los modos de juego! Hoy jugamos Incursión, el clásico. ¡Saquea, pelea y sal! ¡Toca Incursión!",
  'nyx.modeOk': "¡Incursión será! ¡Vamos!",
  'nyx.bag': "¡Así funciona! Tu apuesta va en tu bolsa. Derriba a alguien y su bolsa es tuya. Si caes... la tuya es suya. ¡Uy!",
  'nyx.shop': "Los atuendos y skins de armas salen de bolsas y cajas, ¡aquí en la tienda! Y psst... ¡hay una gratis esperándote!",
  'nyx.social': "¡Amigos, mensajes, gremios! Trae a tu equipo. ¡Todo es más divertido juntos!",
  'nyx.wallet': "¿Quieres apuestas reales? ¡Entra con una cartera o solo con un email! Los retiros solo van a tu propia dirección. ¡Sano y salvo!",
  'nyx.play': "¿Listo? ¡Pulsa Jugar!",
  'nyx.ready': "¡Esta es la sala de espera! Pulsa Listo, ¡y caemos! ¡Uuh!",
  'nyx.start': "¡Estamos dentro! Muévete con W, A, S, D. Apunta con el ratón y haz clic para disparar. ¡Espacio para el impulso!",
  'nyx.startTouch': "¡Estamos dentro! Tu pulgar izquierdo te mueve. Mantén Fuego a la derecha, ¡apunta por ti!",
  'nyx.loot': "¿Ves ese brillo naranja? ¡Es dinero! ¡Pasa corriendo por encima!",
  'nyx.pickup': "¡Bien! ¡Tu bolsa pesa más!",
  'nyx.kill': "¡Primera sangre! ¡Buen tiro! Agarra lo que soltó. ¡Oh, y un arma mejor!",
  'nyx.hurt': "¡Ay, estás herido! La salud no vuelve en combate, ¡ten cuidado!",
  'nyx.storm': "¡Se acerca la tormenta! ¡Quédate dentro del círculo, rápido!",
  'nyx.exit': "¡Oh, esa bolsa te queda bien! Busca un anillo verde de salida y quédate dentro.",
  'nyx.extracting': "¡Quieto! ¡Tres segundos! ¡Que no te den!",
  'nyx.won': "¡Saliste! ¡Sabía que podías! ¡Nos vemos en la próxima incursión, corredor!",
  'nyx.dead': "¡Ay, pasa! La práctica es gratis, ¡otra vez!",
  'tour.yourMove': "Tu turno",
  'tour.skipStep': "Saltar este paso",
  'tour.again': "Toca a Nyx para oírlo otra vez",
  'tour.replayHint': "¿Repetir el tutorial? Ajustes → Tutorial.",
  'mode.zombies': "Zombis",
  'mode.zombies.d': "Cooperativo, solo o con hasta 3 amigos: 20 oleadas de muertos, cada una más dura, jefes en la 10 y la 20. Sin reloj. Las bajas dan créditos para torretas, minas láser y botiquines.",
  'mode.gold': "Fiebre del oro",
  'mode.gold.d': "Caen bolsas de oro por toda la cantera. Armas al azar, reaparición rápida. Quien junte más bolsas se lleva todo el bote como crédito de tienda.",
  'kind.zombie': "cooperativo · XP",
  'kind.gold': "un ganador · crédito",
  'tb.zFee': "entrada · XP, títulos",
  'tb.goldFee': "entrada · el ganador se lo lleva todo",
  'prep.zFee': "entrada {v}",
  'prep.zSquad': "Escuadra",
  'prep.goldPot': "Premio (crédito de tienda)",
  'zp.title': "Tu arma para la partida",
  'zp.power': "Daño por segundo",
  'zp.melee': "sin recarga",
  'hud.waveK': "Oleada",
  'hud.goldK': "Bolsas de oro",
  'hud.startZ': "Defiende el cementerio. Vienen por todos lados",
  'hud.startGold': "Agarra el oro. Quien más bolsas tenga se lo lleva todo",
  'hud.wave': "Oleada {n} de {of}",
  'hud.bossWave': "ÚLTIMA OLEADA · LLEGA EL JEFE",
  'hud.waveClear': "Oleada {n} superada",
  'hud.patched': "+35 HP",
  'hud.summon': "El jefe llama a la horda",
  'hud.bossDown': "JEFE ABATIDO · PARTIDA COMPLETADA",
  'hud.bagsShort': "oro",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "siguiente oleada en {s} s",
  'hud.zLeft': "quedan {n} · {k} abatidos",
  'hud.goldPlace': "puesto {p} · {d} muertes · premio {s}",
  'hud.bossHp': "JEFE {p}%",
  'hud.zBreak': "Recarga y reagrúpate: {s} s",
  'hud.zGoal': "Sobrevive 20 oleadas · jefes en la 10 y la 20",
  'hud.goldGoal': "Gana quien tenga más bolsas al final",
  'hud.zDown': "Caíste. Vuelves en la siguiente oleada si tu escuadra aguanta",
  'feed.zYou': "Los muertos te atraparon",
  'feed.zDown': "{name} fue despedazado",
  'coach.z': "Quédate en la plaza, espalda con espalda. Las bajas dan créditos: compra torretas (2), minas láser (3) y botiquines (1)",
  'coach.gold': "Pasa sobre las bolsas para tomarlas. Si mueres, se cae la mitad, así que agarra y sobrevive",
  'warn.z60': "Queda un minuto",
  'warn.z10': "¡10 segundos: mata al jefe!",
  'warn.gold30': "30 segundos: agarra lo que puedas",
  'warn.gold10': "Quedan 10 segundos",
  'res.zCleared': "Partida completada",
  'res.zFell': "Arrasados en la oleada {n}",
  'res.zWaves': "{n} / {of} oleadas",
  'res.zWonText': "Diez oleadas y su jefe, con una escuadra de {s}. Abatiste {k} muertos.",
  'res.zText': "Abatiste {k} muertos (escuadra de {s}). Cuanto más lejos, más XP.",
  'res.zTime': "tiempo {t}",
  'res.goldWon': "Fiebre del oro ganada",
  'res.goldLost': "Puesto {p} en la fiebre del oro",
  'res.goldWonText': "{b} bolsas de oro, más que nadie. {c} ya está en tu saldo de tienda.",
  'res.goldText': "Juntaste {b} bolsas; el ganador tuvo {top}. Solo cobra el primero.",
  'xp.Waves survived': "Oleadas superadas",
  'xp.Zombies': "Zombis",
  'xp.Boss slain': "Jefe abatido",
  'xp.Run cleared': "Partida completada",
  'xp.Gold bags': "Bolsas de oro",
  'ach.graveyard_shift': "Turno de cementerio",
  'ach.hold_the_line': "Mantén la línea",
  'ach.undertaker': "Sepulturero",
  'ach.exterminator': "Exterminador",
  'ach.giant_slayer': "Matagigantes",
  'ach.zombie_slayer': "Cazazombis",
  'ach.top_of_the_horde': "Cima de la horda",
  'ach.nightmare_walker': "Caminante de pesadillas",
  'ach.army_of_one': "Ejército de uno",
  'ach.prospector': "Buscador",
  'ach.gold_fever': "Fiebre de oro",
  'ach.mother_lode': "Filón madre",
  'ach.bag_hoarder': "Acaparador de bolsas",
  'ach.midas': "Midas",
  'achd.zRuns': "Juega una partida de zombis",
  'achd.bestWave': "Supera la oleada {n} de muertos",
  'achd.zKills': "Mata {n} zombis",
  'achd.zBoss': "Da el golpe final al jefe",
  'achd.zClears': "Completa la partida de zombis {n} veces",
  'achd.zMvp': "Completa una partida con más bajas que nadie en tu escuadra",
  'achd.zSolo': "Completa la partida de zombis solo",
  'achd.goldRuns': "Juega una fiebre del oro",
  'achd.goldWins': "Gana {n} fiebres del oro",
  'achd.bestGold': "Termina una fiebre con {n} bolsas",
  'achd.goldBags': "Junta {n} bolsas de oro en total",
  'tour.nameDone': "Listo",
  'tour.finish': "¡A jugar!",
  'nyx.stake': "Esta es tu apuesta: lo que llevas en la bolsa. En práctica es dinero de juego, así que no pierdes nada. ¡Jugamos por un dólar!",
  'nyx.retry': "¡Ay, caíste! Pasa, ¡la práctica es gratis! Toca Jugar otra vez. Esta vez junta un poco de botín y corre a una salida verde.",
  'nyx.resultWon': "¡Saliste! ¡Ganaste! ¡Sabía que podías! El dinero de práctica es solo para divertirse. ¡Toca Mesas y te enseño la tienda!",
  'nyx.shopGo': "¡Ahora toca la Tienda!",
  'nyx.shopCase': "¡Bienvenido a la tienda! En práctica es solo una demo, no se cobra nada. ¡Toca Demo en esta bolsa y mira cómo se abre!",
  'nyx.shopEquip': "¡Mira lo que salió! En línea, con tus $ de tienda, sería tuyo. ¡Toca Cerrar!",
  'nyx.bye': "¡Eso es todo! Ya sabes jugar, ganar y comprar. ¡A por ellos, corredor! Puedes llamarme cuando quieras en Ajustes.",
  'hud.headshot': "¡TIRO EN LA CABEZA!",
  'inv.open': "Abrir",
  'bp.later': "Más tarde",
  'ach.sharpshooter': "Tirador certero",
  'ach.headhunter': "Cazacabezas",
  'achd.headshots': "Acierta {n} tiros en la cabeza",
  'hud.demoted': "Muerte: bajas a {w}",
  'hud.crit': "CRÍTICO",
  'hud.roundStart': "Ronda {n} de {of}",
  'hud.roundWon': "¡Ronda {n} para ti!",
  'hud.roundLost': "Ronda {n} perdida",
  'hud.roundDraw': "Ronda {n}: empate",
  'hud.roundTo': "La ronda {n} es para {name}",
  'hud.roundNext': "Siguiente ronda en {s} s",
  'hud.roundScore': "Ronda {n}/{of} · {a} : {b}",
  'hud.roundDown': "Caíste. Vuelves en la siguiente ronda",
  'mc.rounds': "{w} de {n} rondas",
  'hud.midBossWave': "OLEADA 10 · UN JEFE SALTA LA VALLA",
  'hud.midBossDown': "¡Jefe abatido! Quedan diez oleadas",
  'ach.last_stand': "Última resistencia",
  'gl.upTurret': "Torreta mejorada: nivel {lv}",
  'gl.upMine': "Mina láser mejorada: {lv} rayos",
  'gl.upHint': "Espacio: {what} → nivel {lv} · {c} CR",
  'gl.upHintTouch': "⬆ {what} → nivel {lv} · {c} CR",
  'gl.no.max': "Ya está al máximo",
  'gl.no.near': "Acércate a tu torreta o mina",
  'nav.invite': "Invitar",
  'ref.title': "Invita a tus amigos",
  'ref.lead': "Trae amigos con tu enlace. Durante {d} días recibes el {p}% de la comisión de la casa de cada apuesta suya, como $ de tienda.",
  'ref.yourCode': "Tu código",
  'ref.link': "Tu enlace de invitación",
  'ref.copy': "Copiar",
  'ref.share': "Compartir",
  'ref.copied': "Enlace copiado",
  'ref.shareText': "Ven a hacer raids conmigo en DARK BAGS. Mi código: {c}",
  'ref.invited': "Invitados",
  'ref.active': "Jugaron una partida",
  'ref.earned': "Has ganado",
  'ref.how': "Cómo funciona",
  'ref.step1': "Tu amigo abre tu enlace (o escribe tu código) antes de su primera partida",
  'ref.step2': "Tras su primera partida con apuesta recibe una bolsa de bienvenida",
  'ref.step3': "Cada apuesta suya te da el {p}% de la comisión de la casa durante {d} días, como $ de tienda",
  'ref.step4': "Cuando termine {m} partidas recibes una bolsa extra",
  'ref.fair': "Juego limpio: las cuentas de tu misma red o dispositivo no cuentan, hay un límite diario y las trampas anulan todas las recompensas.",
  'ref.by': "Llegaste con el código {c}",
  'ref.have': "¿Tienes un código de un amigo?",
  'ref.apply': "Aplicar",
  'ref.online': "Las invitaciones funcionan en el juego en línea. Actívalo en Ajustes.",
  'ref.signin': "Inicia sesión para obtener tu enlace.",
  'ref.claimedToast': "Código aplicado: tu bolsa de bienvenida llega tras tu primera partida",
  'ref.err.already': "Ya tienes quien te invitó",
  'ref.err.unknown': "Ese código no existe",
  'ref.err.self': "No puedes invitarte a ti mismo",
  'ref.err.late': "Los códigos solo valen antes de tu primera partida",
  'ref.err.linked': "Ese código es de tu propia red o dispositivo",
  'ref.err.busy': "Ese jugador alcanzó el límite de hoy. Prueba mañana",
  'err.guard_seat': "Otra cuenta de tu red o dispositivo ya está en esta mesa",
  'err.guard_new': "Demasiadas cuentas nuevas desde tu red hoy. Vuelve mañana",
  'err.guard_faucet': "Tu red ya recibió sus tokens de prueba hoy",
  'res.practiceNoXp': "La práctica es gratis: sin XP ni recompensas. Juega en línea para subir de rango.",
  'online.only': "Solo en línea. La práctica es gratis, así que no cuenta para el pase ni la clasificatoria. Cambia a En línea en la página Jugar.",
  'err.online_only': "Esto solo funciona en línea",
  'tour.skip': "Saltar tutorial",
  'tour.skipped': "Tutorial omitido. Puedes llamar a Nyx otra vez en Ajustes.",
  'shop.demo': "Demo",
  'shop.demoNote': "Una demo: no se cobró ni se dio nada. En línea abres bolsas con $ de tienda y te quedas lo que sale.",
  'acct.signin': "Entrar",
  'acct.copy': "Copiar dirección",
  'acct.explorer': "Explorador",
  'acct.inWallet': "En la billetera",
  'acct.inGame': "En el juego",
  'acct.deposit': "Depositar",
  'acct.withdraw': "Retirar",
  'acct.cartridge': "Abrir billetera Cartridge",
  'acct.signout': "Salir",
  'acct.copied': "Dirección copiada",
  'br.tab': "Puente",
  'br.in': "Hacia Starknet",
  'br.out': "Desde Starknet",
  'br.fromNet': "Desde la red",
  'br.toNet': "A la red",
  'br.youSend': "Envías",
  'br.youGet': "Recibes",
  'br.amount': "Cantidad",
  'br.refund': "Tu dirección en {c} (para reembolsos)",
  'br.refundPh': "Adónde vuelve si el intercambio falla",
  'br.recipient': "Dirección en {c} que lo recibe",
  'br.recipientPh': "La dirección receptora en esa red",
  'br.landsIn': "Llega a tu billetera Starknet {a}; luego Depositar lo pasa al juego.",
  'br.fromWallet': "Se envía desde tu billetera Starknet {a}.",
  'br.fee': "Incluye nuestra comisión del {p}%.",
  'br.getAddr': "Obtener dirección de depósito",
  'br.send': "Enviar desde mi billetera",
  'br.estimate': "Recibes unos {a} ({u}), en ~{s} s",
  'br.needAmount': "Escribe una cantidad.",
  'br.needRefund': "Escribe tu dirección en la red de origen, para reembolsos.",
  'br.needRecipient': "Escribe la dirección receptora.",
  'br.sent': "Enviado. El puente se encarga.",
  'br.sendExactly': "Envía exactamente {a} en {c} a esta dirección:",
  'br.memo': "Memo (obligatorio)",
  'br.copyMemo': "Copiar memo",
  'br.outSent': "{a} enviado al puente hacia {c}.",
  'br.youGetAbout': "Recibes unos {a} en {c}.",
  'br.deadline': "Reembolso si no termina antes de {t}.",
  'br.toGame': "Depositarlo en el juego",
  'br.new': "Nuevo puente",
  'br.others': "Otros puentes",
  'br.othersNote': "Abre el sitio del puente; ahí no cobramos. Envía a tu dirección Starknet del panel de billetera.",
  'br.lsSub': "Más de 40 redes y exchanges",
  'br.avnuSub': "Intercambia tokens en Starknet",
  'br.mainnetOnly': "Los puentes funcionan con monedas reales en la mainnet de Starknet. En testnet, usa los de abajo.",
  'br.s.wait': "Esperando tu depósito",
  'br.s.seen': "Depósito visto, confirmando",
  'br.s.partial': "Depósito insuficiente; envía el resto o espera el reembolso",
  'br.s.proc': "Cruzando…",
  'br.s.ok': "Listo: está en tu billetera",
  'br.s.refund': "Reembolsado",
  'br.s.fail': "Falló; no se cobró nada",
  'nav.mail': "Correo",
  'mail.claim': "Reclamar",
  'mail.claimed': "Recibido: {g}",
  'mail.creditNote': "$ de tienda: gástalos en la tienda. No se pueden retirar ni vender.",
  'mail.empty': "Aún no hay correo.",
  'mail.g.credit': "{v} en $ de tienda",
  'mail.g.spin': "{n} giro(s) de ruleta",
  'mail.g.trial': "{n} por 72 h",
  'mail.newToast': "¡Correo nuevo!",
  'mail.noSpins': "No quedan giros",
  'mail.pick': "Elige una carta para leerla.",
  'mail.signin': "Inicia sesión para recibir correo.",
  'mail.spinBtn': "Girar la ruleta ({n})",
  'mail.spinNow': "¡Girar!",
  'mail.taken': "Recibido",
  'mail.welcomeToast': "¡Bono de bienvenida! Ya llevas el título Fundador y te espera un giro de ruleta en Correo.",
  'mail.wheel': "Ruleta de la fortuna",
  'mail.wheelNote': "Un aspecto de corredor por 72 h, un aspecto de arma por 72 h o hasta $2 en $ de tienda.",
  'mail.trial72': "Tuyo por 72 horas. Póntelo desde el inventario.",
  'mail.welcome.t': "♛ ¡Bienvenido, Fundador!",
  'mail.welcome.b': "Eres de los primeros en apoyar DARK BAGS con una recarga real, y no lo olvidaremos. ¡Gracias!\n\nDesde hoy llevas el título premium Fundador en oro vivo: solo lo tendrán quienes creyeron en el juego desde el principio.\n\nTu regalo está abajo: un giro de la ruleta de la fortuna. Suerte ahí fuera, nos vemos en la oscuridad.\n\nEl equipo de DARK BAGS",
  'ach.founder': "Fundador",
  'achd.deposits': "Haz tu primera recarga",
  'r.premium': "Premium",
  'mail.jackpot.t': "🎰 ¡Bote de la ruleta!",
  'mail.jackpot.b': "El bote de la fortuna fue tuyo: las monedas van hacia ti (o ya están en tu saldo del juego). ¡Felicidades!",
  'fw.bank': "Bote de la fortuna",
  'fw.coin': "Pagar con",
  'fw.inBalance': "Abonado a tu saldo del juego: retíralo cuando quieras.",
  'fw.jackpot': "BOTE",
  'fw.kicker': "$0.05 por giro",
  'fw.lead': "Cada giro gana un aspecto de 72 h, a veces uno real para siempre. Y cada giro llena el bote: el giro que alcanza la marca se lo lleva todo en monedas reales.",
  'fw.next': "paga en {m}",
  'fw.noCoins': "Deposita cualquier moneda para girar.",
  'fw.odds': "Qué puede salir",
  'fw.real': "Aspecto real ({r})",
  'fw.realKeep': "Tuyo para siempre.",
  'fw.rules': "El 30% de cada giro va al bote. Cuando alcanza su marca ($0.50, luego $1, $1.50, $2… hasta $5), el giro que la alcanza gana todo el bote en USDC (o USDT, o STRK). Los aspectos de prueba duran 72 horas. Los artículos de tienda no se pueden retirar ni vender.",
  'fw.sentChain': "Enviado a tu billetera en Starknet.",
  'fw.share': "Compartir la victoria",
  'fw.spin': "Girar",
  'fw.title': "Ruleta de la fortuna",
  'fw.trial': "Aspecto de corredor 72 h",
  'fw.wtrial': "Aspecto de arma 72 h",
  'coin.import': "Importar moneda",
  'coin.search': "Buscar: símbolo, nombre o dirección",
  'coin.added': "añadida",
  'coin.add': "Añadir",
  'coin.none': "No se encontró nada",
  'coin.note': "Cualquier moneda de Starknet de la lista verificada de AVNU o de Ekubo. Una vez añadida, deposítala y apuesta como con cualquier otra; las ganancias vuelven en ella.",
  'coin.done': "{s} añadida: deposítala y elígela para apostar.",
  'coin.noPrice': "{s} añadida; su precio aparecerá en un minuto.",
};
