export default {
  'lobby.tagline': 'Apuesta. Saquea. Sal antes de la tormenta. <b>Nadie ve lo que hay en tu bolsa.</b>',
  'lobby.namePh': 'Nombre de tu corredor',
  'lobby.locker': 'Taquilla · skins · bolsas',
  'lobby.refill': 'Recargar monedas de prueba',
  'lobby.online': 'En línea',
  'lobby.practice': 'Práctica contra bots',
  'lobby.stakePer': 'Apuesta por incursión',
  'lobby.stakeWith': 'Apuesta con <span class="fine">cualquier moneda · mostrado en $ · las ganancias vuelven en la misma moneda</span>',
  'lobby.play': 'Jugar · apuesta {s}',
  'lobby.signIn': 'Inicia sesión para jugar',
  'lobby.how': 'Cómo se juega',
  'lobby.gore': '<b>Modo 18+.</b> Las extremidades salen volando y la sangre se queda en el suelo.',
  'lobby.fine': 'La práctica funciona en tu navegador. Todo el dinero aquí es de juego.',
  'how.1': '<b>Apuesta y prepárate.</b> Todos entran juntos con un cuchillo y 100 de salud. La mitad de tu apuesta va en tu bolsa y la otra mitad se reparte como botín.',
  'how.2': '<b>Coge el botín naranja.</b> Va a tu bolsa. Las bajas mejoran tu arma: cuchillo → pistola → escopeta → subfusil → rifle → francotirador láser.',
  'how.3': '<b>Sal con vida.</b> Quédate 3 segundos en una salida verde antes de que la tormenta la cierre. Te quedas toda la bolsa. Si mueres, cae para otro.',
  'how.keys': '<kbd>WASD</kbd> moverse · <kbd>ratón</kbd> apuntar · <kbd>clic</kbd> atacar · <kbd>Espacio</kbd> esquivar · <kbd>Q</kbd> fingir el tamaño de la bolsa · <kbd>M</kbd> sonido · <kbd>N</kbd> música',
  'how.fine': 'Cada incursión y cada logro dan XP de rango. Cada ascenso te presta un skin nuevo durante 3 días.',
  'net.practice': 'Solo tú y los bots, sin conexión.',
  'net.open': 'Conectado. Humanos y bots comparten cada incursión.',
  'net.connecting': 'Conectando con el servidor…',
  'net.down': 'Servidor inaccesible. Reintentando… La práctica funciona sin conexión.',
  'net.lost': 'Conexión perdida. De vuelta a las mesas.',
  'q.pick': 'Elige una moneda para apostar.',
  'q.short': 'No tienes suficiente {c} para una apuesta de {s}. Elige otra moneda o una apuesta menor.',
  'q.shortDeposit': 'No tienes suficiente {c} para una apuesta de {s}. Elige otra moneda, una apuesta menor o deposita.',
  'q.stable': 'Apuestas {s} en {c}. Sal con vida y quédate con todo lo que llevas.',
  'q.coin': 'Apuestas {a} = {s} al precio de hoy. Las ganancias vuelven en {c} al mismo tipo.',
  'tb.live': 'Incursión en curso · {t}',
  'tb.ready': '{n} listos · {s}s',
  'tb.waiting': '{n} esperando',
  'tb.golden': 'Próxima: incursión dorada',
  'tb.jackpot': 'Bote {v}',
  'pcfg.title': 'Ajustes de práctica',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Fácil',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difícil',
  'pcfg.runners': 'Corredores en la incursión',
  'pcfg.time': 'Duración de la incursión',
  'rk.max': 'rango máximo',
  'rk.toNext': '{x} XP para el rango {r}',
  'rk.of': 'Rango {r} de 90',
  'rk.rank': 'Rango',
  'rk.up': 'Ascenso',
  'rk.xp': 'XP de rango',
  'xp.Raid': 'Incursión',
  'xp.kills': '{n} bajas',
  'xp.Damage': 'Daño',
  'xp.Time alive': 'Tiempo con vida',
  'xp.First blood': 'Primera sangre',
  'xp.Double kill': 'Doble baja',
  'xp.Triple kill': 'Triple baja',
  'xp.Rampage': 'Masacre',
  'xp.Godlike': 'Divino',
  'xp.Full arsenal': 'Arsenal completo',
  'xp.Extracted': 'Extracción',
  'xp.Profit': 'Beneficio',
  'xp.Practice ×0.5': 'Práctica ×0.5',
  'rw.title': 'Recompensa de ascenso',
  'rw.trial': 'tuyo durante 72 horas',
  'rw.try': 'Probártelo',
  'rw.share': 'Compartir ascenso',
  'prep.raid': 'Incursión {n} · apuesta {s}',
  'prep.readyUp': '¿Listo?',
  'prep.first': 'La cuenta atrás empieza cuando el primer corredor esté listo.',
  'prep.live': 'Hay una incursión en curso. Prepárate y entrarás en la siguiente con todos.',
  'prep.over': 'Incursión terminada. La sala se abre en un momento.',
  'prep.many': 'Aquí todos empiezan con cuchillo. Los bots entran en los últimos segundos.',
  'prep.bots': 'Los bots ocupan los huecos en los últimos segundos.',
  'prep.open': 'libre',
  'prep.pot': 'Bote',
  'prep.cancel': 'Cancelar · devolver {v}',
  'prep.ready': 'Listo · apuesta {v}',
  'prep.back': 'Volver a las mesas',
  'hud.bagPrivate': 'Tu bolsa · privada',
  'hud.golden': 'Incursión dorada',
  'hud.goldenStart': 'Incursión dorada · botín del bote dentro',
  'hud.start': 'Cuchillo en mano · coge lo naranja · busca una salida',
  'hud.bagOpened': 'Bolsa abierta · +{v}',
  'hud.arsenal': 'Arsenal completo · otra vez el cuchillo ★',
  'hud.unlocked': '{w} desbloqueado',
  'hud.pnl': '{d} frente a la apuesta de {s}',
  'hud.alive': '{n} dentro',
  'hud.next': 'Siguiente: {w}',
  'hud.final': 'Círculo final · última salida',
  'hud.closing': 'La tormenta se cierra · {t}',
  'hud.stormIn': 'La tormenta avanza en {t}',
  'hud.dash': 'Esquivar',
  'hud.bagLook': 'Aspecto de la bolsa',
  'hud.extracting': 'Extrayendo',
  'hud.holdStill': 'Quieto. Un impacto lo reinicia.',
  'hud.sound': 'Sonido',
  'hud.music': 'Música',
  'bluff.0': 'pequeña',
  'bluff.1': 'mediana',
  'bluff.2': 'gorda',
  'touch.move': 'mover',
  'touch.aim': 'apuntar · disparar',
  'touch.bag': 'Bolsa',
  'w.Knife': 'Cuchillo',
  'w.Pistol': 'Pistola',
  'w.Shotgun': 'Escopeta',
  'w.SMG': 'Subfusil',
  'w.Rifle': 'Rifle',
  'w.Laser sniper': 'Francotirador láser',
  'streak.1': 'Primera sangre',
  'streak.2': 'Doble baja',
  'streak.3': 'Triple baja',
  'streak.4': 'Masacre',
  'streak.5': 'Divino',
  'streak.you1': 'Has hecho la primera sangre',
  'feed.storm': 'La tormenta te atrapó',
  'feed.droppedYou': '{name} te ha tumbado',
  'coach.storm': 'Estás en la tormenta · vuelve al círculo',
  'coach.touch': 'Pulgar izquierdo mueve · pulgar derecho apunta y ataca',
  'coach.keys': 'WASD para moverte · ratón para apuntar · clic para atacar',
  'coach.exit': 'Hora de salir · quédate 3 segundos en una SALIDA verde · las flechas del borde marcan el camino',
  'coach.loot': 'Coge el botín naranja · va a tu bolsa',
  'coach.kills': 'Las bajas mejoran tu arma · Espacio para esquivar',
  'coach.killsTouch': 'Las bajas mejoran tu arma · toca Esquivar',
  'spect.watching': 'Viendo a {name} · ◀ ▶ para cambiar',
  'spect.down': 'Has caído',
  'spect.results': 'Resultados',
  'res.extracted': 'Extraído',
  'res.storm': 'Te tragó la tormenta',
  'res.dropped': 'Abatido',
  'res.sealed': 'Encerrado dentro',
  'res.inside': '{k} bajas · {t} dentro',
  'res.out': 'Saliste con {p} con una apuesta de {s}: {d}.',
  'res.paid': 'Pagado {v} al tipo de entrada.',
  'res.killer': '{n} tiene tu bolsa ahora. Llevaba {v}, y solo vosotros dos lo sabréis.',
  'res.inStorm': 'Tu bolsa, {v}, está en la tormenta para quien se atreva.',
  'res.sealedText': 'La incursión se cerró contigo dentro. Tus {v} pasaron al botín de la siguiente.',
  'res.again': 'Jugar otra vez',
  'res.tables': 'Mesas',
  'res.share': 'Compartir',
  'share.title': 'Compartir',
  'share.x': 'Publicar en 𝕏',
  'share.copy': 'Copiar imagen',
  'share.save': 'Guardar PNG',
  'share.close': 'Cerrar',
  'lk.title': 'Taquilla',
  'lk.outfits': 'Atuendos',
  'lk.shop': 'Tienda',
  'lk.bags': 'Bolsas de suerte',
  'lk.all': 'Todos',
  'lk.owned': 'Míos',
  'lk.him': 'Él',
  'lk.her': 'Ella',
  'lk.shopUsd': '$ de tienda',
  'lk.shopNote': 'Recarga $ de tienda con USDC o USDT (los paquetes grandes dan bonus). Los $ de tienda solo se gastan aquí y no se pueden retirar. ¿Te faltan? La diferencia sale de tus USDC/USDT.',
  'lk.bagsNote': 'Probabilidades exactas, sorteadas en el servidor. Sin duplicados hasta completar una rareza, y un duplicado devuelve el 10% de su precio en $ de tienda. Garantía: Épico+ en 15 aperturas y Legendario+ en 60.',
  'lk.topupFrom': '+ {v} USDC/USDT para recargar',
  'lk.collected': '{a} / {b} conseguidos',
  'lk.equipped': 'Equipado',
  'lk.equip': 'Equipar',
  'lk.buy': 'Comprar',
  'lk.trialLeft': 'Prueba · quedan {t}',
  'lk.trialHow': 'Prueba por ascenso: tuyo {t} más. Cómpralo para quedártelo.',
  'lk.free': 'Gratis para todos.',
  'lk.inCollection': 'En tu colección.',
  'lk.buyOrBag': 'Cómpralo aquí o prueba suerte con una bolsa.',
  'lk.tryingOn': 'Probándotelo.',
  'lk.bonus': '+{n}% de bonus',
  'lk.pay': 'pagas {v}',
  'lk.jackpot': 'Premio gordo',
  'lk.epicIn': 'Épico+ en',
  'lk.legIn': 'Legendario+ en',
  'lk.openFree': 'Abrir · gratis',
  'lk.buyOpen': 'Comprar y abrir',
  'lk.pityDrop': 'garantía',
  'lk.dup': 'Ya es tuyo · {v} de vuelta',
  'lk.new': '<b>Nuevo</b> en tu colección',
  'lk.jackpotIs': 'el premio gordo es {r}',
  'lk.showOff': 'Presumir en X',
  'lk.postMiss': 'Publicar el fallo en X',
  'lk.another': 'Abrir otra',
  'lk.free1': 'gratis',
  'lk.back': 'Volver a la taquilla',
  'lk.yours': '{n} es tuyo.',
  'r.common': 'Común',
  'r.rare': 'Raro',
  'r.epic': 'Épico',
  'r.legendary': 'Legendario',
  'r.mythic': 'Mítico',
  'r.exotic': 'Exótico',
  'ach.title': 'Logros',
  'ach.button': 'Logros',
  'ach.intro': 'Cada uno da XP de rango una vez y desbloquea su nombre como título que puedes llevar.',
  'ach.wear': 'Llevar título',
  'ach.worn': 'Puesto',
  'ach.wearing': 'Título:',
  'ach.takeOff': 'quitar',
  'ach.noTitle': 'Sin título',
  'ach.unlocked': 'Logro desbloqueado',
  'ach.seeAll': 'Todos los logros',
  'achd.raids': 'Juega {n} incursiones',
  'achd.extracts': 'Extráete {n} veces',
  'achd.kills': 'Consigue {n} bajas',
  'achd.bestKills': '{n} bajas en una incursión',
  'achd.bestMulti': 'Una baja múltiple ×{n}',
  'achd.prestige': 'Completa el arsenal {n} veces',
  'achd.firstBloods': 'Haz la primera sangre {n} veces',
  'achd.secs': 'Pasa {n} h dentro de incursiones',
  'achd.bestReturn': 'Sal con {n}× tu apuesta',
  'achd.golden': 'Extráete de una incursión dorada',
  'achd.lastExit': 'Sal por la última salida',
  'achd.pacifist': 'Extráete sin una sola baja',
  'achd.rank': 'Alcanza el rango {n}',
  'achd.outfits': 'Consigue {n} atuendos',
  'ach.rookie': 'Novato',
  'ach.regular': 'Habitual',
  'ach.veteran': 'Veterano',
  'ach.lifer': 'De por vida',
  'ach.eternal': 'Eterno',
  'ach.escape_artist': 'Escapista',
  'ach.ghost': 'Fantasma',
  'ach.smuggler': 'Contrabandista',
  'ach.phantom': 'Espectro',
  'ach.first_kill': 'Primera baja',
  'ach.hunter': 'Cazador',
  'ach.butcher': 'Carnicero',
  'ach.reaper': 'Segador',
  'ach.apex': 'Depredador',
  'ach.rampage': 'Masacre',
  'ach.one_man_army': 'Ejército de uno',
  'ach.double_tap': 'Doble toque',
  'ach.triple_threat': 'Triple amenaza',
  'ach.godlike': 'Divino',
  'ach.full_arsenal': 'Arsenal completo',
  'ach.arsenal_master': 'Maestro del arsenal',
  'ach.first_blood': 'Primera sangre',
  'ach.opener': 'El que abre',
  'ach.night_shift': 'Turno de noche',
  'ach.insomniac': 'Insomne',
  'ach.double_up': 'Doblete',
  'ach.big_bag': 'Bolsa grande',
  'ach.gold_rush': 'Fiebre del oro',
  'ach.last_one_out': 'El último en salir',
  'ach.pacifist': 'Pacifista',
  'ach.seasoned': 'Curtido',
  'ach.officer': 'Oficial',
  'ach.commander': 'Comandante',
  'ach.legend': 'Leyenda',
  'ach.collector': 'Coleccionista',
  'ach.curator': 'Conservador',
  'ach.hoarder': 'Acaparador',
  'intro.tag': "Apuesta. Saquea. Sal.",
  'intro.go': "Entrar",
  'intro.fonts': "Afilando cuchillos…",
  'intro.world': "Pintando la oscuridad…",
  'intro.connect': "Buscando incursión…",
  'intro.profile': "Preparando tu bolsa…",
  'intro.ready': "Listo",
  'tb.wallet': "Cartera",
  'tb.shop': "$ de tienda",
  'nav.play': "Jugar",
  'nav.shop': "Tienda",
  'nav.inventory': "Inventario",
  'nav.swap': "Intercambio",
  'nav.chat': "Chat",
  'nav.achievements': "Logros",
  'nav.settings': "Ajustes",
  'modes.title': "Modo de juego",
  'kind.raid': "extracción",
  'kind.br': "el ganador se lleva el bote",
  'kind.team': "bote de equipo",
  'mode.raid': "Incursión",
  'mode.raid.d': "Saquea, pelea y sal por una salida. Te quedas lo que llevas.",
  'mode.br': "Battle Royale",
  'mode.br.d': "Hasta 20 corredores. El último en pie se lleva todo el bote.",
  'mode.duel': "Duelo",
  'mode.duel.d': "Uno contra uno. El ganador se lleva ambas apuestas.",
  'mode.knives': "Solo cuchillos",
  'mode.knives.d': "Solo cuchillas toda la incursión. Gana el último en pie.",
  'mode.pistols': "Solo pistolas",
  'mode.pistols.d': "Solo pistolas. Gana el último en pie.",
  'mode.shotguns': "Solo escopetas",
  'mode.shotguns.d': "De cerca y a lo bestia. Gana el último en pie.",
  'mode.rifles': "Solo rifles",
  'mode.rifles.d': "Tiroteos a media distancia. Gana el último en pie.",
  'mode.snipers': "Solo francotiradores",
  'mode.snipers.d': "Miras láser por todas partes. Gana el último en pie.",
  'mode.team2': "Equipos 2 vs 2",
  'mode.team2.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'mode.team4': "Equipos 4 vs 4",
  'mode.team4.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'mode.team8': "Equipos 8 vs 8",
  'mode.team8.d': "Cada apuesta suma a un bote. El último equipo en pie lo reparte.",
  'hud.pot': "Bote",
  'hud.left': "Quedan {n} · apuesta {s}",
  'hud.teamsLeft': "Quedan {n} equipos · apuesta {s}",
  'hud.startPot': "El último en pie se lleva el bote",
  'hud.startTeam': "Quédate con tu equipo · acaba con el otro",
  'hud.goldenPot': "Incursión dorada · premio añadido al bote",
  'coach.pot': "Aquí no hay salidas · quédate en el círculo · gana el último en pie",
  'coach.team': "Nombres verdes: tu equipo · rojos: el enemigo",
  'warn.exit30': "30s · llega a una salida abierta",
  'warn.exit10': "10s · extráete o piérdelo todo",
  'warn.pot30': "30s · la tormenta se cierra",
  'warn.pot10': "10s · gana quien tenga más vivos",
  'storm.final': "Colapso final · solo la última salida",
  'storm.finalPot': "Colapso final · no hay dónde esconderse",
  'storm.closing': "La tormenta se acerca",
  'storm.in5': "La tormenta avanza en 5s",
  'feed.youDropped': "Tumbaste a {name}",
  'feed.stormTook': "La tormenta se tragó a {name}",
  'feed.dropped': "{a} tumbó a {b}",
  'feed.down': "{name} cayó",
  'feed.extracted': "{name} se extrajo",
  'feed.exitClosed': "La salida {name} está cerrada",
  'spect.settling': "Tu resultado llega cuando se cierre la incursión.",
  'res.victory': "Victoria",
  'res.teamWon': "Tu equipo ganó",
  'res.defeated': "Derrota",
  'res.wonText': "Te llevaste {p} con una apuesta de {s}.",
  'res.lostPot': "El bote fue para el último en pie.",
  'res.teamLost': "El otro equipo se llevó el bote.",
  'xp.Victory': "Victoria",
  'ach.champion': "Campeón",
  'ach.warlord': "Señor de la guerra",
  'achd.wins': "Gana {n} incursiones con bote",
  'lk.weapons': "Skins de armas",
  'lk.onlyBags': "Los skins solo salen de bolsas y cajas de la tienda.",
  'lk.toShop': "Abrir la tienda",
  'lk.toOpen': "{n} por abrir",
  'lk.limited': "Limitado · {n}",
  'lk.minted': "{a} de {b} acuñados",
  'lk.plain': "Estándar",
  'lk.fromBags': "Sale de las bolsas de atuendos de la tienda.",
  'lk.fromCrates': "Sale de las cajas de armas de la tienda.",
  'lk.trialHow2': "Prueba por ascenso: tuyo {t} más.",
  'lk.weaponHow': "Elige un acabado tuyo para equiparlo. Todos en la incursión lo ven.",
  'fx.glow': "aura",
  'fx.pulse': "aura pulsante",
  'fx.ghost': "espectral",
  'fx.laser': "ojos láser",
  'fx.rainbow': "prismático",
  'fx.fire': "en llamas",
  'fx.gold': "oro líquido",
  'fx.holo': "holograma",
  'fx.glitch': "glitch",
  'fx.lightning': "rayos",
  'fx.galaxy': "galaxia",
  'fx.sparks': "chispas",
  'fx.frost': "escarcha",
  'fx.money': "lluvia de dinero",
  'fx.matrix': "lluvia de código",
  'fx.shadow': "humo de sombra",
  'fx.cape': "capa",
  'box.street': "Bolsa callejera",
  'box.vault': "Bolsa de la cámara",
  'box.golden': "Bolsa dorada",
  'box.elite': "Bolsa élite",
  'box.diamond': "Bolsa de diamante",
  'box.obsidian': "Bolsa de obsidiana",
  'box.royal': "Bolsa real",
  'box.apex': "Bolsa Apex",
  'box.genesis': "Bolsa Génesis",
  'box.w-scrap': "Caja de chatarra",
  'box.w-armory': "Caja del arsenal",
  'box.w-brass': "Caja de latón",
  'box.w-specops': "Caja de operaciones especiales",
  'box.w-diamond': "Caja de diamante",
  'box.w-obsidian': "Caja de obsidiana",
  'box.w-royal': "Caja real",
  'box.w-apex': "Caja Apex",
  'box.w-genesis': "Caja Génesis",
  'shop.topup': "Recargar $ de tienda",
  'shop.bags': "Bolsas de atuendos",
  'shop.crates': "Cajas de armas",
  'shop.bagsNote': "Atuendos para tu corredor. Nueve niveles: cuanto más cara la bolsa, mejores probabilidades.",
  'shop.cratesNote': "Skins para tus armas y cuchillo, se venden aparte de los atuendos. Nueve niveles.",
  'shop.fair': "Probabilidades exactas, sorteadas en el servidor. Garantía: Épico+ en {e} aperturas, Legendario+ en {l}.",
  'shop.odds': "Probabilidades y garantía",
  'shop.qty': "Cantidad",
  'shop.open': "Abrir ×{n}",
  'shop.limited': "Ediciones limitadas",
  'shop.soldOut': "Agotado",
  'shop.dup': "Duplicado · +{v}",
  'shop.new': "Nuevo",
  'shop.back': "{v} de vuelta",
  'shop.equipBest': "Equipar {n}",
  'inv.wallet': "Cartera",
  'inv.deposit': "Depositar · retirar",
  'inv.walletNote': "Tokens reales que la casa guarda para ti. Retira cuando quieras a la dirección con la que entraste.",
  'inv.playNote': "Dinero de juego en este navegador. Recarga cuando quieras.",
  'inv.shopNote': "Se compra con USDC/USDT y solo se gasta en bolsas y cajas. No se puede retirar.",
  'inv.unopened': "Sin abrir",
  'inv.collection': "Colección",
  'inv.opened': "Abiertas",
  'inv.career': "Carrera",
  'inv.raids': "Incursiones",
  'inv.kills': "Bajas",
  'inv.extracts': "Extracciones",
  'inv.wins': "Botes ganados",
  'inv.best': "Mejor incursión (bajas)",
  'inv.time': "Tiempo dentro",
  'swap.game': "Saldo del juego",
  'swap.gameNote': "Al instante, al precio actual, {f}% de comisión.",
  'swap.gameOff': "Los intercambios dentro del juego están desactivados en este servidor. Usa el de tu cartera abajo.",
  'swap.from': "Das",
  'swap.to': "Recibes",
  'swap.have': "Tienes",
  'swap.flip': "Invertir",
  'swap.go': "Intercambiar",
  'swap.short': "Saldo insuficiente",
  'swap.done': "Cambiaste {a} por {b}.",
  'swap.wallet': "Tu cartera",
  'swap.signIn': "Conecta una cartera Starknet para intercambiar allí con AVNU.",
  'swap.needChain': "Los intercambios con AVNU funcionan con una cartera Starknet real en modo en línea.",
  'swap.slippage': "Deslizamiento máx.",
  'swap.quoting': "Buscando la mejor ruta…",
  'swap.impact': "impacto en el precio {p}%",
  'swap.goAvnu': "Intercambiar con AVNU",
  'swap.noQuote': "Ahora no hay ruta para ese par.",
  'swap.sent': "Intercambio enviado: {tx}",
  'swap.walletNote': "AVNU busca la ruta entre los exchanges de Starknet. Firmas en tu cartera; el juego nunca guarda estos tokens.",
  'chat.ph': "Di algo…",
  'chat.send': "Enviar",
  'chat.empty': "Aún no hay mensajes. Di gm.",
  'chat.online': "Todo el lobby ve esto. Sé amable.",
  'chat.practice': "La práctica es sin conexión: solo escuchan los bots.",
  'set.graphics': "Gráficos",
  'set.quality': "Calidad",
  'set.qualityNote': "Auto baja el detalle cuando van lentos los fotogramas.",
  'set.auto': "Auto",
  'set.high': "Alta",
  'set.medium': "Media",
  'set.low': "Baja",
  'set.shake': "Vibración de pantalla",
  'set.motion': "Animaciones del menú",
  'set.display': "Visualización",
  'set.skins': "Skins",
  'set.skinsNote': "De quién dibujar atuendos y skins de armas.",
  'set.skinsAll': "Todos",
  'set.skinsMine': "Solo los míos",
  'set.skinsNone': "Ninguno",
  'set.names': "Nombres sobre los corredores",
  'set.titles': "Títulos sobre los nombres",
  'set.controls': "Controles",
  'set.stick': "Tamaño de los sticks táctiles",
  'set.lefty': "Zurdo (táctil)",
  'set.leftyNote': "Intercambia los sticks de mover y apuntar.",
  'set.audio': "Audio",
  'set.sound': "Volumen de efectos",
  'set.music': "Volumen de música",
  'set.language': "Idioma",
  'shop.exoticIn': "Exótico en",
  'shop.guarantee': "Exótico garantizado en {n} aperturas",
  'set.voice': "Locutor",
  'mode.dm': "Todos contra todos",
  'mode.dm.d': "Cada uno por su cuenta, reapareces tras cada muerte. Quien tenga más bajas al final se lleva el bote.",
  'mode.gl': "Armas + Láseres",
  'mode.gl.d': "Todos contra todos con tienda: las bajas dan créditos para botiquines, torretas y minas láser.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Vida mínima: una bala y caes. El último en pie se lleva el bote.",
  'kind.dm': "más bajas se lleva el bote",
  'hud.startDm': "Quien tenga más bajas cuando el reloj llegue a cero se lleva el bote",
  'hud.startGl': "Las bajas dan créditos · 1 botiquín · 2 torreta · 3 mina láser",
  'hud.startHc': "Un impacto y caes. Que cada disparo cuente.",
  'hud.respawned': "De vuelta",
  'hud.respawnIn': "Reapareces en {s}s",
  'hud.tookLead': "Has tomado la delantera",
  'hud.lostLead': "Has perdido la delantera",
  'hud.dmScore': "{k} bajas · {d} muertes · #{p}",
  'hud.dmGoal': "La primera baja toma la delantera",
  'hud.oneHit': "1 IMPACTO",
  'feed.leader': "{name} toma la delantera con {k}",
  'gl.medkit': "Botiquín",
  'gl.turret': "Torreta",
  'gl.mine': "Mina láser",
  'gl.no.cash': "Créditos insuficientes",
  'gl.no.full': "Ya tienes la vida al máximo",
  'gl.no.limit': "Límite alcanzado",
  'gl.no.wall': "Demasiado cerca de una pared",
  'res.dmLost': "Terminaste #{p}",
  'res.dmText': "{k} bajas, {d} muertes. El ganador tuvo {top}.",
  'coach.dm': "Reapareces · gana quien tenga más bajas al acabar el tiempo",
  'coach.gl': "Las bajas dan créditos · gástalos en un botiquín ✚, una torreta ◈ o una mina láser ⌁",
  'set.voiceNote': "Locutor grabado (inglés, ucraniano, español, francés, portugués; inglés para los demás idiomas).",
  'net.waking': "Despertando el servidor (el hosting gratuito se duerme cuando nadie juega, hasta un minuto)… Mientras tanto, la práctica funciona.",
  'shop.bulk': "Cada caja n.º {n} gratis",
  'shop.bulkOn': "Cajas gratis incluidas: {n}",
  'net.online': "{n} en línea",
};
