export default {
  'lobby.tagline': 'Misez. Pillez. Sortez avant la tempête. <b>Personne ne voit ce qu’il y a dans votre sac.</b>',
  'lobby.namePh': 'Nom de votre coureur',
  'lobby.locker': 'Casier · skins · sacs',
  'lobby.refill': 'Recharger les pièces de test',
  'lobby.online': 'En ligne',
  'lobby.practice': 'Entraînement contre bots',
  'lobby.stakePer': 'Mise par raid',
  'lobby.stakeWith': 'Misez avec <span class="fine">n’importe quelle crypto · affiché en $ · les gains reviennent dans la même crypto</span>',
  'lobby.play': 'Jouer · mise {s}',
  'lobby.signIn': 'Connectez-vous pour jouer',
  'lobby.how': 'Comment jouer',
  'lobby.gore': '<b>Mode 18+.</b> Les membres volent, le sang reste au sol.',
  'lobby.fine': 'L’entraînement tourne dans votre navigateur. Tout l’argent ici est fictif.',
  'how.1': '<b>Misez et soyez prêt.</b> Tout le monde entre ensemble avec un couteau et 100 PV. La moitié de votre mise est dans votre sac, l’autre est dispersée en butin.',
  'how.2': '<b>Ramassez le butin orange.</b> Il va dans votre sac. Les éliminations améliorent votre arme : couteau → pistolet → fusil à pompe → mitraillette → fusil → sniper laser.',
  'how.3': '<b>Sortez vivant.</b> Restez 3 secondes dans une sortie verte avant que la tempête ne la ferme. Le sac entier est à vous. Mourez et il tombe pour un autre.',
  'how.keys': '<kbd>ZQSD/WASD</kbd> bouger · <kbd>souris</kbd> viser · <kbd>clic</kbd> attaquer · <kbd>Espace</kbd> esquive · <kbd>Q</kbd> bluffer la taille du sac · <kbd>M</kbd> son · <kbd>N</kbd> musique',
  'how.fine': 'Chaque raid et chaque succès rapportent de l’XP de grade. Chaque promotion vous prête un nouveau skin pendant 3 jours.',
  'net.practice': 'Juste vous et les bots, hors ligne.',
  'net.open': 'Connecté. Humains et bots partagent chaque raid.',
  'net.connecting': 'Connexion au serveur…',
  'net.down': 'Serveur injoignable. Nouvelle tentative… L’entraînement marche hors ligne.',
  'net.lost': 'Connexion perdue. Retour aux tables.',
  'q.pick': 'Choisissez une crypto pour miser.',
  'q.short': 'Pas assez de {c} pour une mise de {s}. Choisissez une autre crypto ou une mise plus petite.',
  'q.shortDeposit': 'Pas assez de {c} pour une mise de {s}. Choisissez une autre crypto, une mise plus petite, ou déposez.',
  'q.stable': 'Vous misez {s} en {c}. Sortez vivant pour garder tout ce que vous portez.',
  'q.coin': 'Vous misez {a} = {s} au cours du jour. Les gains reviennent en {c} au même taux.',
  'tb.live': 'Raid en cours · {t}',
  'tb.ready': '{n} prêts · {s}s',
  'tb.waiting': '{n} en attente',
  'tb.golden': 'Prochain : raid doré',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Réglages d’entraînement',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Facile',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difficile',
  'pcfg.runners': 'Coureurs dans le raid',
  'pcfg.time': 'Durée du raid',
  'rk.max': 'grade max',
  'rk.toNext': '{x} XP jusqu’au grade {r}',
  'rk.of': 'Grade {r} sur 90',
  'rk.rank': 'Grade',
  'rk.up': 'Promotion',
  'rk.xp': 'XP de grade',
  'xp.Raid': 'Raid',
  'xp.kills': '{n} éliminations',
  'xp.Damage': 'Dégâts',
  'xp.Time alive': 'Temps en vie',
  'xp.First blood': 'Premier sang',
  'xp.Double kill': 'Double élimination',
  'xp.Triple kill': 'Triple élimination',
  'xp.Rampage': 'Carnage',
  'xp.Godlike': 'Divin',
  'xp.Full arsenal': 'Arsenal complet',
  'xp.Extracted': 'Extraction',
  'xp.Profit': 'Profit',
  'xp.Practice ×0.5': 'Entraînement ×0.5',
  'rw.title': 'Récompense de promotion',
  'rw.trial': 'à vous pendant 72 heures',
  'rw.try': 'L’essayer',
  'rw.share': 'Partager la promotion',
  'prep.raid': 'Raid {n} · mise {s}',
  'prep.readyUp': 'Prêt ?',
  'prep.first': 'Le compte à rebours démarre quand le premier coureur est prêt.',
  'prep.live': 'Un raid est en cours. Soyez prêt et vous entrerez dans le suivant avec tout le monde.',
  'prep.over': 'Raid terminé. La salle ouvre dans un instant.',
  'prep.many': 'Ici tout le monde commence au couteau. Les bots arrivent dans les dernières secondes.',
  'prep.bots': 'Les bots comblent les places libres dans les dernières secondes.',
  'prep.open': 'libre',
  'prep.pot': 'Pot',
  'prep.cancel': 'Annuler · rembourser {v}',
  'prep.ready': 'Prêt · mise {v}',
  'prep.back': 'Retour aux tables',
  'hud.bagPrivate': 'Votre sac · privé',
  'hud.golden': 'Raid doré',
  'hud.goldenStart': 'Raid doré · butin du jackpot à l’intérieur',
  'hud.start': 'Couteau en main · prenez l’orange · trouvez une sortie',
  'hud.bagOpened': 'Sac ouvert · +{v}',
  'hud.arsenal': 'Arsenal complet · retour au couteau ★',
  'hud.unlocked': '{w} débloqué',
  'hud.pnl': '{d} par rapport à la mise de {s}',
  'hud.alive': '{n} à l’intérieur',
  'hud.next': 'Suivant : {w}',
  'hud.final': 'Cercle final · dernière sortie',
  'hud.closing': 'La tempête se referme · {t}',
  'hud.stormIn': 'La tempête avance dans {t}',
  'hud.dash': 'Esquive',
  'hud.bagLook': 'Allure du sac',
  'hud.extracting': 'Extraction',
  'hud.holdStill': 'Ne bougez pas. Un coup remet à zéro.',
  'hud.sound': 'Son',
  'hud.music': 'Musique',
  'bluff.0': 'petit',
  'bluff.1': 'moyen',
  'bluff.2': 'gros',
  'touch.move': 'bouger',
  'touch.aim': 'viser · tirer',
  'touch.bag': 'Sac',
  'w.Knife': 'Couteau',
  'w.Pistol': 'Pistolet',
  'w.Shotgun': 'Fusil à pompe',
  'w.SMG': 'Mitraillette',
  'w.Rifle': 'Fusil',
  'w.Laser sniper': 'Sniper laser',
  'streak.1': 'Premier sang',
  'streak.2': 'Double élimination',
  'streak.3': 'Triple élimination',
  'streak.4': 'Carnage',
  'streak.5': 'Divin',
  'streak.you1': 'Vous avez fait couler le premier sang',
  'feed.storm': 'La tempête vous a eu',
  'feed.droppedYou': '{name} vous a abattu',
  'coach.storm': 'Vous êtes dans la tempête · revenez dans le cercle',
  'coach.touch': 'Pouce gauche pour bouger · pouce droit pour viser et attaquer',
  'coach.keys': 'WASD pour bouger · souris pour viser · clic pour attaquer',
  'coach.exit': 'Il faut sortir · restez 3 secondes dans une SORTIE verte · les flèches au bord montrent le chemin',
  'coach.loot': 'Ramassez le butin orange · il va dans votre sac',
  'coach.kills': 'Les éliminations améliorent votre arme · Espace pour esquiver',
  'coach.killsTouch': 'Les éliminations améliorent votre arme · touchez Esquive',
  'spect.watching': 'Vous regardez {name} · ◀ ▶ pour changer',
  'spect.down': 'Vous êtes tombé',
  'spect.results': 'Résultats',
  'res.extracted': 'Extrait',
  'res.storm': 'Englouti par la tempête',
  'res.dropped': 'Abattu',
  'res.sealed': 'Enfermé à l’intérieur',
  'res.inside': '{k} éliminations · {t} à l’intérieur',
  'res.out': 'Sorti avec {p} pour une mise de {s} : {d}.',
  'res.paid': 'Payé {v} au taux d’entrée.',
  'res.killer': '{n} a votre sac maintenant. Il contenait {v}, et vous serez les deux seuls à le savoir.',
  'res.inStorm': 'Votre sac, {v}, traîne dans la tempête pour qui osera.',
  'res.sealedText': 'Le raid s’est fermé avec vous dedans. Vos {v} passent dans le butin du raid suivant.',
  'res.again': 'Rejouer',
  'res.tables': 'Tables',
  'res.share': 'Partager',
  'share.title': 'Partager',
  'share.x': 'Publier sur 𝕏',
  'share.copy': 'Copier l’image',
  'share.save': 'Enregistrer le PNG',
  'share.close': 'Fermer',
  'lk.title': 'Casier',
  'lk.outfits': 'Tenues',
  'lk.shop': 'Boutique',
  'lk.bags': 'Sacs chance',
  'lk.all': 'Toutes',
  'lk.owned': 'Les miennes',
  'lk.him': 'Lui',
  'lk.her': 'Elle',
  'lk.shopUsd': '$ boutique',
  'lk.shopNote': 'Rechargez des $ boutique en USDC ou USDT (les gros packs ont un bonus). Les $ boutique ne servent qu’ici et ne se retirent pas. Il en manque ? La différence est prise sur vos USDC/USDT.',
  'lk.bagsNote': 'Chances exactes, tirées sur le serveur. Pas de doublon avant d’avoir toute une rareté, et un doublon rend 10 % de son prix en $ boutique. Garantie : Épique+ en 15 ouvertures, Légendaire+ en 60.',
  'lk.topupFrom': '+ {v} USDC/USDT disponibles pour recharger',
  'lk.collected': '{a} / {b} obtenues',
  'lk.equipped': 'Équipée',
  'lk.equip': 'Équiper',
  'lk.buy': 'Acheter',
  'lk.trialLeft': 'Essai · encore {t}',
  'lk.trialHow': 'Essai de promotion : à vous encore {t}. Achetez-la pour la garder.',
  'lk.free': 'Gratuite pour tous.',
  'lk.inCollection': 'Dans votre collection.',
  'lk.buyOrBag': 'Achetez-la ici ou tentez votre chance avec un sac.',
  'lk.tryingOn': 'Essayage.',
  'lk.bonus': '+{n} % de bonus',
  'lk.pay': 'payez {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Épique+ dans',
  'lk.legIn': 'Légendaire+ dans',
  'lk.openFree': 'Ouvrir · gratuit',
  'lk.buyOpen': 'Acheter et ouvrir',
  'lk.pityDrop': 'garantie',
  'lk.dup': 'Déjà à vous · {v} rendus',
  'lk.new': '<b>Nouveau</b> dans votre collection',
  'lk.jackpotIs': 'le jackpot est {r}',
  'lk.showOff': 'Frimer sur X',
  'lk.postMiss': 'Publier le raté sur X',
  'lk.another': 'En ouvrir un autre',
  'lk.free1': 'gratuit',
  'lk.back': 'Retour au casier',
  'lk.yours': '{n} est à vous.',
  'r.common': 'Commun',
  'r.rare': 'Rare',
  'r.epic': 'Épique',
  'r.legendary': 'Légendaire',
  'r.mythic': 'Mythique',
  'ach.title': 'Succès',
  'ach.button': 'Succès',
  'ach.intro': 'Chacun rapporte de l’XP de grade une fois et débloque son nom comme titre à porter.',
  'ach.wear': 'Porter le titre',
  'ach.worn': 'Porté',
  'ach.wearing': 'Titre :',
  'ach.takeOff': 'retirer',
  'ach.noTitle': 'Sans titre',
  'ach.unlocked': 'Succès débloqué',
  'ach.seeAll': 'Tous les succès',
  'achd.raids': 'Jouez {n} raids',
  'achd.extracts': 'Extrayez-vous {n} fois',
  'achd.kills': 'Faites {n} éliminations',
  'achd.bestKills': '{n} éliminations en un raid',
  'achd.bestMulti': 'Une multi-élimination ×{n}',
  'achd.prestige': 'Terminez l’arsenal {n} fois',
  'achd.firstBloods': 'Faites couler le premier sang {n} fois',
  'achd.secs': 'Passez {n} h en raid',
  'achd.bestReturn': 'Sortez avec {n}× votre mise',
  'achd.golden': 'Extrayez-vous d’un raid doré',
  'achd.lastExit': 'Sortez par la dernière sortie',
  'achd.pacifist': 'Extrayez-vous sans aucune élimination',
  'achd.rank': 'Atteignez le grade {n}',
  'achd.outfits': 'Possédez {n} tenues',
  'ach.rookie': 'Bleu',
  'ach.regular': 'Habitué',
  'ach.veteran': 'Vétéran',
  'ach.lifer': 'De carrière',
  'ach.eternal': 'Éternel',
  'ach.escape_artist': 'As de l’évasion',
  'ach.ghost': 'Fantôme',
  'ach.smuggler': 'Contrebandier',
  'ach.phantom': 'Spectre',
  'ach.first_kill': 'Première élimination',
  'ach.hunter': 'Chasseur',
  'ach.butcher': 'Boucher',
  'ach.reaper': 'Faucheur',
  'ach.apex': 'Prédateur',
  'ach.rampage': 'Carnage',
  'ach.one_man_army': 'Armée à lui seul',
  'ach.double_tap': 'Doublé',
  'ach.triple_threat': 'Triple menace',
  'ach.godlike': 'Divin',
  'ach.full_arsenal': 'Arsenal complet',
  'ach.arsenal_master': 'Maître de l’arsenal',
  'ach.first_blood': 'Premier sang',
  'ach.opener': 'L’ouvreur',
  'ach.night_shift': 'Équipe de nuit',
  'ach.insomniac': 'Insomniaque',
  'ach.double_up': 'Quitte ou double',
  'ach.big_bag': 'Gros sac',
  'ach.gold_rush': 'Ruée vers l’or',
  'ach.last_one_out': 'Le dernier à sortir',
  'ach.pacifist': 'Pacifiste',
  'ach.seasoned': 'Aguerri',
  'ach.officer': 'Officier',
  'ach.commander': 'Commandant',
  'ach.legend': 'Légende',
  'ach.collector': 'Collectionneur',
  'ach.curator': 'Conservateur',
  'ach.hoarder': 'Thésauriseur',
};
