export default {
  'lobby.tagline': 'Misez. Pillez. Sortez avant la tempête. <b>Personne ne voit ce qu’il y a dans votre sac.</b>',
  'lobby.namePh': 'Nom de votre coureur',
  'lobby.locker': 'Casier · skins · sacs',
  'lobby.refill': 'Recharger les pièces de test',
  'lobby.online': 'En ligne',
  'lobby.practice': 'Entraînement contre bots',
  'lobby.stakePer': 'Mise par raid',
  'lobby.stakeWith': 'Misez avec <span class="fine">n’importe quelle crypto · affiché en $ · les gains reviennent dans la même crypto</span>',
  'lobby.play': 'Jouer · mise {s}',
  'lobby.signIn': 'Connectez-vous pour jouer',
  'lobby.how': 'Comment jouer',
  'lobby.gore': '<b>Mode 18+.</b> Les membres volent, le sang reste au sol.',
  'lobby.fine': 'L’entraînement tourne dans votre navigateur. Tout l’argent ici est fictif.',
  'how.1': '<b>Misez et soyez prêt.</b> Tout le monde entre ensemble avec un couteau et 100 PV. La moitié de votre mise est dans votre sac, l’autre est dispersée en butin.',
  'how.2': '<b>Ramassez le butin orange.</b> Il va dans votre sac. Les éliminations améliorent votre arme : couteau → pistolet → fusil à pompe → mitraillette → fusil → sniper laser.',
  'how.3': "<b>Sors vivant.</b> Il n'y a qu'une sortie, au centre de la carte. Tiens-la 10 secondes : tout le monde est prévenu de ton départ et chaque impact relance le compte. Réussis et tu gardes tout ton sac. Meurs et il tombe pour un autre.",
  'how.keys': "<kbd>ZQSD/WASD</kbd> bouger · <kbd>souris</kbd> viser · <kbd>clic</kbd> attaquer · <kbd>Espace</kbd> esquive · <kbd>Q</kbd> bluffer la taille du sac · <kbd>M</kbd> son · <kbd>N</kbd> musique",
  'how.fine': 'Chaque raid et chaque succès rapportent de l’XP de grade. Chaque promotion vous prête un nouveau skin pendant 3 jours.',
  'net.practice': 'Juste vous et les bots, hors ligne.',
  'net.open': 'Connecté. En ligne, uniquement de vrais joueurs.',
  'reg.title': "Serveur",
  'reg.auto': "Le plus proche",
  'reg.fallback': "Ce serveur n'accepte pas de joueurs pour l'instant. Tu joues sur {r}.",
  'reg.eu': "Europe",
  'reg.us': "Amérique",
  'reg.asia': "Asie",
  'cx.noRef': "Le serveur n'a pas fourni de référence de dépôt. Réessaie.",
  'nav.starknet': "Starknet",
  'nav.s.starknet': "Confidentialité · chiffres en direct",
  'sk.kicker': "Construit sur Starknet",
  'sk.title': "Privé par défaut",
  'sk.lede': "Ton argent n'est visible que par toi. Dépôts et retraits passent par le pool protégé STRK20 de Starknet avec des preuves à divulgation nulle, les mises restent privées, les swaps ne touchent jamais la chaîne et le Bitcoin se joue comme n'importe quelle crypto.",
  'sk.dep.t': "Dépôt privé",
  'sk.dep.b': "De ton solde protégé vers le jeu par le pool STRK20. Une preuve à divulgation nulle le vérifie : personne sur la chaîne ne voit qui a payé ni combien.",
  'sk.dep.a': "Déposer en privé",
  'sk.stake.t': "Mises privées",
  'sk.stake.b': "Choisis n'importe quelle mise dans la fourchette de la table. Toi seul la connais : la table n'affiche que le pot total. Les gains se partagent équitablement, comme les side pots du poker.",
  'sk.stake.a': "Jouer",
  'sk.swap.t': "Swap privé",
  'sk.swap.b': "Échange tes cryptos dans ton solde de jeu au prix en direct. Rien ne touche la chaîne, aucun explorateur ne le montre.",
  'sk.swap.a': "Échanger",
  'sk.wd.t': "Retrait privé",
  'sk.wd.b': "Les gains retournent sur ton solde protégé via STRK20 : personne sur la chaîne ne voit que le paiement était le tien.",
  'sk.wd.a': "Retirer en privé",
  'sk.ready': "Prêt",
  'sk.needWallet': "Il faut Ready ou Xverse",
  'sk.signIn': "Connecte-toi avec un portefeuille Starknet",
  'sk.always': "Toujours actif",
  'sk.btc.t': "Bitcoin sur Starknet",
  'sk.btc.b': "Mise du BTC (WBTC et autres Bitcoin sur Starknet) comme n'importe quelle crypto : les gains reviennent en Bitcoin au prix en direct.",
  'sk.btc.a': "Jouer en BTC",
  'sk.btc.picked': "Ta crypto de mise est maintenant le Bitcoin.",
  'sk.live': "En direct sur Starknet",
  'sk.test': "réseau de test",
  'sk.s.players': "Joueurs",
  'sk.s.d7': "Actifs cette semaine",
  'sk.s.matches': "Matchs joués",
  'sk.s.staked': "Misé en match",
  'sk.s.privStakes': "Mises privées",
  'sk.s.privTx': "Transferts privés (STRK20)",
  'sk.s.deposits': "Déposé sur la chaîne",
  'sk.s.tvl': "Détenu dans le jeu",
  'sk.loading': "Chargement des chiffres…",
  'sk.note': "Des totaux seulement : aucun joueur ni montant de personne n'apparaît ici.",
  'cx.none': "Rien pour le moment.",
  'cx.loading': "Chargement des portefeuilles…",
  'cx.cartridgeGo': "Continue dans la fenêtre Cartridge…",
  'cx.waitWallet': "En attente du portefeuille…",
  'cx.signMsg': "Signe le message de connexion dans ton portefeuille (c'est gratuit).",
  'cx.noAnswer': "Le serveur n'a pas répondu.",
  'cx.noSig': "Le portefeuille n'a pas renvoyé de signature. Réessaie.",
  'cx.checkingSig': "Signé. Vérification de la signature sur Starknet…",
  'cx.notConfirmed': "Le serveur n'a pas confirmé la connexion à temps. Réessaie.",
  'cx.typeEmail': "Saisis d'abord ton email.",
  'cx.sendingCode': "Envoi d'un code…",
  'cx.codeSent': "Code envoyé à {e}.",
  'cx.checkingCode': "Vérification du code…",
  'cx.privyAgain': "Reconnecte-toi avec Privy.",
  'cx.signAgain': "Reconnecte-toi pour choisir ton portefeuille.",
  'cx.otherAcct': "{w} est sur le compte {a}, mais tu es connecté en tant que {b}. Change de compte dans le portefeuille ou connecte-toi avec {a}.",
  'cx.signInAs': "Se connecter avec {a}",
  'cx.inWalletChecking': "Dans ton portefeuille : vérification…",
  'cx.inWallet': "Dans ton portefeuille : {v}",
  'cx.keepStrk': " (garde ~1 STRK pour les frais réseau)",
  'cx.transfer': "Transfert public",
  'cx.transferDep': "tout portefeuille : un simple transfert de jetons, visible sur la chaîne",
  'cx.transferWd': "un simple transfert vers ton adresse, visible sur la chaîne",
  'cx.private': "🔒 Privé · Starknet STRK20",
  'cx.privateDep': "Ready ou Xverse : depuis ton solde protégé avec une preuve à divulgation nulle. Personne sur la chaîne ne voit qui a payé ni combien",
  'cx.privateWd': "vers ton solde protégé : personne sur la chaîne ne voit que le paiement était le tien. Ton adresse doit être inscrite dans le pool STRK20",
  'cx.typeAmount': "Saisis un montant.",
  'cx.walletOnly': "Ton portefeuille n'a que {v}.",
  'cx.faucet': " STRK de test gratuits sur starknet-faucet.vercel.app.",
  'cx.leaveStrk': "Garde environ 1 STRK dans ton portefeuille pour les frais (utilise Max).",
  'cx.confirmDep': "Confirme le dépôt dans ton portefeuille…",
  'cx.holdsOnly': "{w} ({a}) contient {v}. Envoie d'abord des {s} à cette adresse.",
  'cx.noPrivate': "Ce mode de connexion ne permet pas les transferts privés. Utilise un transfert public.",
  'cx.sentWait': "Envoyé ({tx}). En attente de Starknet…",
  'cx.youHave': "Tu as {v}.",
  'cx.depBad': "Dépôt (jeton non accepté, contacte le support)",
  'cx.depHeld': "Dépôt retenu (au-dessus de la limite bêta, remboursé)",
  'cx.dep': "Dépôt",
  'cx.cashout': "Retrait · {s}",
  'cx.signedAs': "Connecté en tant que {a}.",
  'cx.checkingChain': "La caisse vérifie la chaîne…",
  'cx.notCredited': "Reçu mais non crédité car {r}. C'est en sécurité et te sera renvoyé.",
  'cx.credited': "Crédité {v}.",
  'cx.creditedToast': "Dépôt crédité : {v}.",
  'cx.txFailed': "La transaction a échoué sur la chaîne. Rien n'a été prélevé.",
  'cx.sentPrivate': "Envoyé en privé. La note protégée arrive en une ou deux minutes ; ton solde se met à jour tout seul.",
  'cx.sentPublic': "En attente que Starknet l'accepte. Ton solde se met à jour tout seul.",
  'cx.paying': "Paiement…",
  'cx.paid': "Payé. Transaction {tx}.",
  'cx.paidToast': "Retrait envoyé.",
  'cx.payFailed': "Le paiement n'a pas pu être envoyé. Ton solde est revenu.",
  'cx.payHeld': "Le paiement est retenu pour vérification manuelle. Tes fonds sont en sécurité ; il est dans ton historique.",
  'cx.wrong': "Un problème est survenu.",
  'cx.cancelled': "Annulé dans le portefeuille.",
  'cx.cantSend': "Ton portefeuille n'a pas pu l'envoyer : souvent pas assez de ce jeton ou plus de STRK pour les frais. Essaie un montant plus petit (Max garde de quoi payer les frais).",
  'cx.notDeployed': "Ton compte n'est pas encore déployé sur ce réseau. Fais d'abord une transaction dans le portefeuille (par exemple, envoie-toi un peu de STRK), puis réessaie.",
  'cx.minWd': "Minimum ${m}. Payé à {a}.",
  'cx.wdOff': "Les retraits sont désactivés sur ce serveur pour le moment.",
  'cx.hintPrivate': "Ton portefeuille construit une preuve à divulgation nulle sur Starknet ; cela peut prendre une minute.",
  'cx.hintPublic': "Ton solde se met à jour une fois le transfert accepté sur Starknet.",
  'cx.connectT': "Connecte-toi pour jouer avec des jetons",
  'cx.swallet': "Portefeuille Starknet",
  'cx.looking': "Recherche de portefeuilles…",
  'cx.privNote': "Tout portefeuille Starknet fonctionne. Ready et Xverse peuvent aussi déposer et retirer en privé via le pool STRK20 : personne sur la chaîne ne voit qui tu es ni combien.",
  'cx.noWallet': "Sans portefeuille · Cartridge",
  'cx.cartSub': "passkey ou réseaux sociaux, sans frais",
  'cx.privyT': "Email ou réseaux · Privy",
  'cx.sendCode': "Envoyer le code",
  'cx.codePh': "Code de l'email",
  'cx.signIn': "Se connecter",
  'cx.cashier': "Caisse",
  'cx.tDeposit': "Déposer",
  'cx.tCash': "Retirer",
  'cx.tHistory': "Historique",
  'cx.amount': "Montant",
  'cx.testFaucet': "Testnet : des STRK gratuits pour ton adresse sur starknet-faucet.vercel.app, puis dépose-les ici.",
  'stake.private': "🔒 Ta mise est privée : la table ne montre que le pot total, jamais qui a misé combien.",
  'prep.mine': "🔒 Ta mise : {v} · toi seul la vois",
  'res.refund': "{v} de ta mise te sont revenus : aucun gagnant n'avait misé autant.",
  'medal.long': "Tir lointain",
  'medal.knife': "Mise à mort au couteau",
  'ex.centre': "SORTIE · TIENS {s} S",
  'feed.extracting': "{name} tient la sortie",
  'hud.holdExit': "Tiens la sortie {s} s · tout le monde le sait · un impact relance le compte",
  'cs.signedOut': "Vrais jetons sur Starknet {n}. Connecte-toi pour jouer.",
  'cs.manage': "Déposer · retirer",
  'cs.fine': "Vrais jetons sur Starknet {n}. La maison garde les dépôts jusqu'au retrait ; les retraits vont seulement à l'adresse de connexion.",
  'cs.beta': "Bêta : jusqu'à {v} par joueur.",
  'wel.name.t': "Choisis le nom de ton runner",
  'wel.name.b': "Salut, je suis Nyx, ta coordinatrice ! Avant de sauter, dis-moi comment t’appeler. Tout le monde voit ce nom au-dessus de ta tête, dans le tableau des scores et dans le chat.",
  'wel.name.ph': "Le nom de ton runner",
  'wel.name.rules': "De 3 à 16 lettres ou chiffres. Tu pourras le changer plus tard sur la page Jouer.",
  'wel.name.dice': "Un nom au hasard",
  'wel.next': "Suivant",
  'wel.back': "Retour",
  'wel.go': "C’est parti",
  'wel.region.t': "Choisis ta région",
  'wel.region.b': "Les matchs se jouent sur un serveur proche de toi. Plus le ping (ms) est bas, plus le jeu est fluide. Je les ai tous testés : le vert est le plus rapide.",
  'wel.region.best': "Le meilleur pour toi",
  'wel.region.off': "ne répond pas",
  'wel.region.players': "{n} en ligne",
  'wel.region.auto': "Auto",
  'wel.region.autoD': "toujours le plus rapide pour toi",
  'wel.region.note': "Tu peux changer de région à tout moment sur la page Jouer.",
  'tut.hello.t': "Bienvenue dans DARK BAGS !",
  'tut.hello': "Je suis Nyx. En quelques minutes, je vais te montrer **chaque partie du jeu**, pour que rien ne te perde, puis on jouera **ton premier match ensemble**.\nLe principe est simple : tu entres dans le match avec un **sac** d’argent (ta mise), tu ramasses du butin, tu affrontes d’autres runners et tu **sors vivant** pour garder ce que tu portes.\nUtilise **Suivant** (ou la touche →) pour avancer et **Retour** pour relire.",
  'tut.menu.t': "Le menu",
  'tut.menu': "Tout est ici, en quatre groupes :\n**Jouer** : les matchs, le Classé et le Passe de combat. **Boutique** : la boutique, ton inventaire et l’échange de cryptos. **Social** : chat, amis, guildes, courrier et invitations. **Toi** : tâches et réglages.\nLa ligne sous chaque nom te dit ce qui t’attend (tâches, caisses, minuteur de la boutique). Un chiffre rouge, c’est du nouveau. Ta carte en bas montre ton rang et ton niveau VIP.",
  'tut.profile.t': "Ton runner",
  'tut.profile': "C’est toi. Touche ton runner pour ouvrir le **Casier** : tenues, skins d’armes et style.\nSous ton nom : ton **rang** (1 à 90). Chaque match rapporte de l’XP : éliminations, survie, sortie, victoire. Les succès débloquent des **titres** à porter.\n**En ligne** : de vrais joueurs pour de vraies mises. **Entraînement** : des bots avec de l’argent fictif, gratuit et parfait pour apprendre.",
  'tut.goals.t': "Objectifs du jour",
  'tut.goals': "Ta liste du jour : le **cadeau du calendrier**, les **tâches du jour**, la **première victoire du jour** (+300 XP), ton **palier de pass** et tes **tours gratuits**.\nUne carte qui brille signifie qu’une récompense t’attend : touche-la et elle t’y emmène. Reviens chaque jour : le calendrier grandit pendant 30 jours d’affilée.",
  'tut.modes.t': "Modes de jeu",
  'tut.modes': "17 modes en 5 groupes : **Classiques**, **Armes**, **Équipes**, **Événements** (Classé, Zombies, Ruée vers l’or) ou **Tous**.\nChaque carte montre combien jouent, la durée d’un match, qui est dedans **maintenant** et qui **attend**. 🔥 marque le plus actif. Touche une carte pour la choisir.",
  'tut.modeInfo.t': "Le mode choisi",
  'tut.modeInfo': "Tout sur le mode choisi : **comment gagner**, une **astuce** de ma part et **ce qu’il rapporte**, plus les joueurs, la durée et qui y est maintenant.\nTu hésites ? Lis d’abord cet encadré. Pour un premier match, **Raid** est le meilleur.",
  'tut.stake.t': "Ta mise",
  'tut.stake': "Ce que tu apportes au match : **0,10 $, 1 $, 10 $, 100 $** ou **ton propre montant** (0,10 $ à 10 000 $).\nEn **Raid**, la moitié de ta mise est dans ton sac et l’autre moitié est éparpillée sur la carte en butin. Sors vivant et tu gardes tout ton sac. Dans les **modes à cagnotte**, les mises de tous forment un seul prix : le gagnant le prend.\nLa maison garde 5 %. Commence petit : 0,10 $ ou 1 $.\n🔒 Ta mise est **privée** : la table n'affiche que le pot total. Avec des mises différentes, le pot se partage équitablement : le gagnant prend à chaque joueur au plus ce qu'il a misé lui-même.",
  'tut.coins.t': "Mise avec n’importe quelle crypto",
  'tut.coins': "Paie avec la crypto que tu veux : USDC, USDT, STRK, ETH, BTC et plus. Les montants sont affichés en dollars, tu sais toujours ce que tu risques.\nTes gains reviennent **dans la même crypto, au prix d’entrée** : les variations pendant le match ne changent rien.",
  'tut.wallet.t': "Ton portefeuille et les $ boutique",
  'tut.wallet': "En haut : **Wallet**, ce sont tes vraies cryptos (dépôt et retrait à tout moment). **Shop $** est un crédit boutique pour les caisses et les offres : il ne se retire pas.\nPour jouer en ligne avec de vraies mises, connecte un portefeuille ou juste un e-mail. Les retraits vont uniquement vers **ta propre adresse**. L’entraînement ne demande rien.",
  'tut.shop.t': "La boutique : offres",
  'tut.shop': "En haut de la boutique :\n**Pack de départ** (une fois) : une tenue Épique, 3 caisses, 5 tours et un cadre pour 1,99 $. **Boutique du jour** : six skins par jour achetés directement, sans tirage. **Carte Insider** : 30 jours de $ boutique et de tours chaque jour, +25 % d’XP de pass. **VIP** : plus tu as payé, plus ton bonus de recharge et tes tours quotidiens sont grands.\nChaque achat demande une deuxième touche : rien ne s’achète par erreur.",
  'tut.cases.t': "Les caisses",
  'tut.cases': "Les **sacs** donnent des tenues, les **caisses** des skins d’armes, les **caisses de style** des cadres, bannières, effets d’élimination et couleurs de pseudo. Plus c’est cher, meilleures sont les chances.\nChaque caisse affiche ses **chances exactes**, tirées sur le serveur. **Garanties** : un Épique ou mieux en 15 ouvertures, un Légendaire en 60. Chaque 10e caisse est offerte. Un doublon rembourse des $ boutique. Achète et ouvre jusqu’à 100 d’un coup.",
  'tut.wheel.t': "La roue de la fortune",
  'tut.wheel': "0,05 $ le tour, ou gratuit avec les tours des tâches, du calendrier, du courrier et du VIP. **18 prix** : skins d’1 heure, vrais skins, style, caisses cadeaux, $ boutique, XP de pass, boosts d’XP et tours bonus.\nChaque tour payant remplit la **banque de la fortune** : le tour qui atteint le palier gagne toute la banque **en vraies cryptos**. **Tout tourner** utilise tous tes tours gratuits d’un coup.",
  'tut.inventory.t': "Inventaire",
  'tut.inventory': "Tout ce que tu possèdes : cryptos du portefeuille, $ boutique, **caisses non ouvertes** (touche **Tout ouvrir** pour les ouvrir d’un coup), **tours gratuits**, ton **style** (cadre, bannière, effet d’élimination, couleur de pseudo : équipe-les ici), ta collection et tes stats.",
  'tut.swap.t': "Échange",
  'tut.swap': "Échange une crypto contre une autre dans le jeu, avec de petits frais. Pratique pour miser ou retirer dans une autre crypto.",
  'tut.pass.t': "Passe de combat",
  'tut.pass': "Une nouvelle saison chaque mois avec **50 paliers**. Chaque match le remplit d’XP. La **piste gratuite** récompense tout le monde ; la **premium** (9,99 $) ajoute une récompense à chaque palier : armures, skins d’armes et de tourelles, style Mythique.\nPressé ? Achète des paliers. Récupère tes récompenses sur la page du pass.",
  'tut.ranked.t': "Classé",
  'tut.ranked': "Un battle royale avec mise qui fait aussi bouger ton **classement de saison**. Place et éliminations décident de ta montée : Bronze, Argent, Or, Platine, Diamant, Maître, **Légende Néon**.\nChaque nouvelle division paie des **prix** une fois par saison (style Légendaire, Mythique, voire Exotique), et après un match une loterie de caisses peut tomber.",
  'tut.tasks.t': "Tâches",
  'tut.tasks': "Le **calendrier de 30 jours** : un cadeau chaque jour où tu reviens (un jour manqué et il recommence), les plus gros aux jours 7, 14, 21 et 30. **3 tâches du jour** et **tâches hebdo** pour caisses, tours, $ boutique et boosts d’XP.\n**Succès** : 96 objectifs ; chacun donne de l’XP, une récompense et un **titre** à porter.",
  'tut.social.t': "Amis, guildes, chat",
  'tut.social': "Ajoute des **amis**, vois qui est en ligne, écris-leur et invite-les à ta table. Rejoins ou fonde une **guilde** avec son propre chat. Le **chat** parle à tout le monde.\nEn match : **Tab** affiche le tableau des scores, **K** active ou coupe ton micro du **chat vocal** (en équipes, tu parles à ton équipe).",
  'tut.mail.t': "Courrier et invitations",
  'tut.mail': "**Courrier** : des lettres du jeu avec des cadeaux (ouvre une caisse ou fais tourner la roue depuis la lettre).\n**Inviter** : partage ton lien. Tes amis reçoivent un sac de bienvenue, et tu gagnes des $ boutique chaque fois qu’ils jouent.",
  'tut.settings.t': "Réglages",
  'tut.settings': "Son, musique, graphismes et effets, contrôles, langue et chat vocal. Envie de refaire ce tour ? C’est ici : **Réglages → Tour**.",
  'tut.match.t': "Ton premier match !",
  'tut.match': "Voilà tout le jeu. Maintenant le plus fun : jouons **ton premier match ensemble**. C’est un entraînement gratuit contre des bots, rien à perdre. Je te dirai quoi faire à chaque étape.",
  'tut.practice.t': "Touche Entraînement",
  'tut.practice': "Touche **Entraînement** (en surbrillance). Des bots et de l’argent fictif : gratuit et parfait pour apprendre.",
  'tut.raidPick.t': "Touche Raid",
  'tut.raidPick': "Touche la carte **Raid** : butin, combat et sortie. Le classique.",
  'tut.bag.t': "Ton sac",
  'tut.bag': "On joue **1 $ d'argent d'entraînement**. Il est dans ton **sac**. Ramasse du butin pour l'alourdir. Abats un runner et son sac tombe pour toi. Tombe et le tien tombe pour lui.\nPour le garder, atteins la **sortie au centre de la carte** et tiens-la **10 secondes**. Tout le monde est prévenu de ton départ, et un impact relance le compte.",
  'tut.play.t': "Touche Jouer",
  'tut.play': "Touche **Jouer**. Tu iras dans la salle d’attente.",
  'tut.ready.t': "Appuie sur Prêt",
  'tut.ready': "Appuie sur **Prêt** et on saute !\nContrôles : **ZQSD/WASD** bouger, **souris** viser, **clic** tirer, **Espace** esquive, **Q** fausse la taille de ton sac, **Tab** scores. Sur mobile : le pouce gauche déplace, maintiens **Tir** à droite et ça vise pour toi.",
  'tut.resultWon.t': "Tu es sorti !",
  'tut.resultWon': "Tu as gagné ton premier raid ! Je savais que tu y arriverais. L’argent d’entraînement sert juste à apprendre. Touche **Tables** pour revenir au menu.",
  'tut.retry.t': "Réessaie",
  'tut.retry': "Tu es tombé : ça arrive, l'entraînement est gratuit ! Touche **Rejouer**. Cette fois, ramasse un peu de butin, puis va à la **sortie au centre** et tiens-la 10 secondes.",
  'tut.bye.t': "Prêt, runner !",
  'tut.bye': "Tu connais tout le jeu maintenant. Conseils : commence par de petites mises, fais tes **tâches du jour**, récupère le **calendrier** chaque jour et joue avec des **amis**.\nSi tu as besoin de moi : **Réglages → Tour**. Bonne chance !",
  'nav.g.play': "Jouer",
  'nav.g.store': "Boutique",
  'nav.g.social': "Social",
  'nav.g.you': "Toi",
  'nav.s.ranked': "Grimpe les divisions",
  'nav.s.pass': "Récompenses de saison",
  'nav.s.shop': "Caisses, offres, la roue",
  'nav.s.inventory': "Skins, caisses, style",
  'nav.s.swap': "Échange tes cryptos",
  'nav.s.chat': "Parle à tous",
  'nav.s.friends': "Jouez ensemble",
  'nav.s.guilds': "Clans et chat",
  'nav.s.mail': "Lettres et cadeaux",
  'nav.s.invite': "Gagne avec tes amis",
  'nav.s.achievements': "Calendrier, tâches, succès",
  'nav.s.settings': "Son, contrôles, langue",
  'nav.d.pass': "Palier {n} sur 50",
  'nav.d.store': "Nouvelle boutique dans {t}",
  'nav.d.inv': "{b} caisses · {s} tours",
  'nav.d.mail': "{n} non lus",
  'nav.d.tasks': "{n} à récupérer",
  'mcat.all': "Tous",
  'mcat.classic': "Classiques",
  'mcat.weapons': "Armes",
  'mcat.teams': "Équipes",
  'mcat.events': "Événements",
  'mc.hot': "Top",
  'mc.season': "Saison",
  'mi.waves': "Vagues",
  'mi.rounds': "{n} manches × {s}",
  'mi.win': "Comment gagner :",
  'mi.tip': "Astuce :",
  'mi.pays': "Rapporte :",
  'mi.rew': "De l’XP pour chaque élimination et fin ; compte pour les tâches et le pass.",
  'mi.players': "Joueurs",
  'mi.time': "Match",
  'mi.now': "Maintenant",
  'mi.win.raid': "Atteins la sortie au centre de la carte et tiens-la 10 secondes (tout le monde est prévenu, un impact relance le compte) : tu gardes tout ton sac.",
  'mi.win.br': "Sois le dernier debout : la cagnotte est à toi.",
  'mi.win.duel': "Bats l’autre en 90 secondes : tu prends les deux mises.",
  'mi.win.dm': "Le plus d’éliminations à la fin prend la cagnotte. Tu réapparais.",
  'mi.win.gl': "Le plus d’éliminations gagne. Elles paient des crédits pour soins, tourelles et mines laser.",
  'mi.win.hardcore': "Le dernier debout prend la cagnotte. Un tir suffit.",
  'mi.win.weapon': "Le dernier debout prend la cagnotte, une seule arme pour tous.",
  'mi.win.team': "Gagne 2 manches sur 3 en équipe : l’équipe partage la cagnotte.",
  'mi.win.ranked': "Finis haut et élimine : ton classement monte et chaque division paie des prix.",
  'mi.win.zombies': "Survis aux vagues avec 3 amis. Chaque vague donne de l’XP.",
  'mi.win.gold': "Ramasse le plus de sacs d’or : le gagnant reçoit des $ boutique.",
  'mi.tip.raid': "Pille d’abord, combats ensuite.",
  'mi.tip.br': "Reste dans la zone sûre et laisse les autres s’affronter.",
  'mi.tip.duel': "Esquive (Espace) et bouge sans arrêt.",
  'mi.tip.dm': "Continue : chaque élimination améliore ton arme.",
  'mi.tip.gl': "Dépense tôt : une tourelle dans un couloir gagne pour toi.",
  'mi.tip.hardcore': "Va de couvert en couvert : un tir te met à terre.",
  'mi.tip.weapon': "Apprends la portée de l’arme et combats là où elle excelle.",
  'mi.tip.team': "Reste avec ton équipe : deux armes sur un ennemi gagnent.",
  'mi.tip.ranked': "Survis d’abord : la place compte autant que les éliminations.",
  'mi.tip.zombies': "Dos à dos, et garde les soins pour les grosses vagues.",
  'mi.tip.gold': "Prends les sacs proches et évite le combat chargé.",
  'goal.title': "Aujourd’hui",
  'goal.cal': "Cadeau du jour {d} prêt",
  'goal.claim': "Touche pour récupérer",
  'goal.tasks': "Tâches {a}/{b}",
  'goal.tasksS': "tâches du jour",
  'goal.first': "Première victoire du jour",
  'goal.firstS': "+300 XP en attente",
  'goal.pass': "Palier de pass {n}",
  'goal.passP': "pass premium",
  'goal.passF': "piste gratuite : passe premium",
  'goal.card': "Insider : cadeau du jour",
  'goal.vip': "VIP {n} : tours quotidiens",
  'goal.spins': "{n} tours gratuits",
  'goal.spinsS': "tourne la roue",
  'vip.toNext': "Encore {v} pour VIP {n}",
  'vip.max': "VIP maximum",
  'vip.how': "Le VIP monte avec l’argent réel payé (recharges et paiements USDC/USDT), jamais avec les $ boutique gratuits.",
  'vip.claim': "Récupérer {n} tours",
  'vip.perks': "Tous les niveaux",
  'vip.paid': "Payé",
  'vip.bonus': "Bonus de recharge",
  'vip.daily': "Chaque jour",
  'vip.frame': "Cadre",
  'vip.note': "Les avantages VIP sont confort et statut : jamais plus de puissance en match.",
  'vip.got': "+{n} tours",
  'fw.all': "Tout tourner ×{n}",
  'fw.allGot': "{n} tours : tout ce que tu as gagné",
  'inv.openAll': "Tout ouvrir ({n})",
  'inv.openN': "Ouvrir ×{n}",
  'bp.buyTier': "+{n} palier · {v}",
  'bp.tiersGot': "+{n} paliers : palier {t}",
  'of.confirm': "Touche encore : {v}",
  'of.once': "Une seule fois",
  'of.starter': "Pack de départ",
  'of.st.outfit': "Une tenue Épique à garder",
  'of.st.boxes': "2 sacs Vault + une caisse Armory (chances complètes)",
  'of.st.spins': "{n} tours de roue",
  'of.buy': "Acheter · {v}",
  'of.k.outfit': "Tenue",
  'of.k.wskin': "Arme",
  'of.k.style': "Style",
  'of.owned': "Possédé",
  'of.card': "Carte Insider",
  'of.cardOn': "Insider · {n} jours restants",
  'of.cardDaily': "Chaque jour : {v} boutique + {n} tour",
  'of.claimed': "Récupéré aujourd’hui",
  'of.claim': "Récupérer",
  'of.extend': "+30 jours · {v}",
  'of.cardTitle': "Carte Insider · {d} jours",
  'of.c.now': "{v} boutique tout de suite",
  'of.c.pass': "+{n}% d’XP de pass",
  'of.c.frame': "Le cadre {n}, seulement avec la carte",
  'of.c.value': "Vaut {v} boutique et {s} tours sur le mois si tu récupères chaque jour.",
  'of.kicker': "Acheté direct, sans roulette",
  'of.store': "Boutique du jour",
  'of.newIn': "Nouveau lot dans",
  'of.storeNote': "Six skins par jour, les mêmes pour tous. Jamais d’éditions limitées ni d’Exotiques.",
  'of.got': "À toi : {x}",
  'of.cardGot': "Carte Insider active : {n} jours",
  'of.claimGot': "+{v} boutique et {n} tour",
  'of.starterGot': "Le pack de départ est à toi : ouvre tes sacs dans l’inventaire",
  'fw.k.credit': "{v} de boutique",
  'fw.k.pass': "+{v} XP de pass",
  'fw.k.boost': "×2 XP pendant {n} match",
  'fw.k.spin': "+1 tour gratuit",
  'fw.k.box': "Cadeau : {name}",
  'fw.k.style': "Objet de style {r}",
  'fw.free': "Tour gratuit ×{n}",
  'fw.freeNote': "Les tours gratuits des tâches, du calendrier et du courrier font tourner cette roue. Touche la roue pour tourner.",
  'fw.again': "Tourner encore",
  'fw.styleNote': "Un objet de style à garder : équipe-le dans Inventaire → Style.",
  'fw.passNote': "Compte pour ton niveau de pass.",
  'fw.boostNote': "Ton prochain match donne double XP.",
  'fw.spinNote': "Un tour de plus, offert par la maison.",
  'fw.boxNote': "Une caisse cadeau dans ton inventaire : jusqu’à Épique.",
  'dl.openBox': "Ouvrir {name}",
  'dl.spinNow': "Tourner la roue",
  'inv.spins': "Tours gratuits",
  'vc.toggle': "Micro on/off (K)",
  'vc.peers': "voix : {n}",
  'vc.micOn': "Micro activé : on t’entend. K pour couper.",
  'vc.noMic': "Pas de micro : autorise-le dans le navigateur pour parler.",
  'set.vchat': "Chat vocal",
  'set.vchatNote': "Entends les joueurs de ton match (en équipes : ton équipe). K active et coupe ton micro.",
  'sb.open': "Tableau (Tab)",
  'sb.title': "Tableau des scores",
  'sb.hint': "maintiens Tab",
  'sb.player': "Joueur",
  'sb.k': "É",
  'sb.d': "M",
  'sb.ping': "Ping",
  'sb.bot': "bot",
  'sb.zk': "Zombies",
  'sb.gb': "Or",
  'sb.yours': "Ton équipe",
  'sb.theirs': "Adversaires",
  'rd.divPrize': "Prix de division",
  'rd.divPrizes': "Prix de division",
  'rd.divPrizesNote': "Atteins une division pour gagner son prix, une fois par saison. Le style Légendaire et Mythique se gagne ici et dans le passe.",
  'rd.styleOf': "Style {r}",
  'inv.giftCap': "{n} cadeau : jusqu’à Épique",
  'shop.style': "Style",
  'shop.styleNote': "Cadres, bannières, effets d’élimination et couleurs de pseudo animés. Les doublons rendent du $ boutique.",
  'sty.title': "Style",
  'sty.frame': "Cadres",
  'sty.banner': "Bannières",
  'sty.killfx': "Effets d’élimination",
  'sty.namefx': "Pseudos",
  'sty.none': "Aucun",
  'sty.worn': "porté",
  'sty.empty': "Rien pour l’instant : {n} à trouver dans les caisses de style, le calendrier et les tâches.",
  'sty.get': "Obtenir du style",
  'box.s-street': "Caisse style urbain",
  'box.s-neon': "Caisse style néon",
  'box.s-icon': "Caisse style icône",
  'ach.listTitle': "Succès",
  'dl.g.credit': "{v} boutique",
  'dl.g.spin': "{n}× tour de roue",
  'dl.g.pass': "+{n} XP de passe",
  'dl.g.xp': "+{n} XP",
  'dl.g.boost': "×2 XP pendant {n} matchs",
  'dl.days': "{d}j {h}h",
  'dl.t.raids': "Joue {n} matchs",
  'dl.t.kills': "Fais {n} éliminations",
  'dl.t.secs': "Passe {n} min en match",
  'dl.t.firstBloods': "Premier sang {n}×",
  'dl.t.extracts': "Extrais-toi {n}×",
  'dl.t.pvpKills': "Élimine {n} joueurs",
  'dl.t.headshots': "Réussis {n} tirs à la tête",
  'dl.t.zKills': "Tue {n} zombies",
  'dl.t.goldBags': "Ramasse {n} sacs d’or",
  'dl.t.wins': "Gagne {n}×",
  'dl.t.kKnife': "Fais {n} éliminations au couteau",
  'dl.t.kSniper': "Fais {n} éliminations au sniper",
  'dl.t.rankedGames': "Joue {n} matchs classés",
  'dl.t.zClears': "Termine {n} parties zombies",
  'dl.calendar': "Récompenses quotidiennes · 30 jours",
  'dl.dayOf': "Jour {d} sur 30",
  'dl.lost': "Série interrompue : retour au jour 1.",
  'dl.calNote': "Reviens chaque jour d’affilée : les cadeaux grandissent, un gros tous les 7 jours.",
  'dl.best': "meilleure série {n}",
  'dl.next': "Prochain cadeau dans {t}",
  'dl.claim': "Récupérer",
  'dl.done': "Fait",
  'dl.today': "Tâches du jour",
  'dl.resets': "nouvelles dans {t}",
  'dl.sweep': "Les trois aujourd’hui :",
  'dl.sweepGot': "Les trois faites ! Bonus :",
  'dl.week': "Cette semaine",
  'dl.boostLeft': "encore {n} matchs",
  'dl.boostNone': "pas encore de boost : gagne-le avec les tâches et le calendrier",
  'dl.fwDone': "Première victoire du jour : obtenue",
  'dl.fwReady': "Première victoire du jour : +300 XP en attente",
  'dl.todayDone': "tâches faites aujourd’hui",
  'dl.offline': "Récompenses et tâches quotidiennes en ligne uniquement.",
  'dl.signIn': "Connecte-toi pour les récompenses et tâches quotidiennes.",
  'dl.dayGot': "Jour {d} : récupéré !",
  'dl.achGot': "Récompense de succès",
  'dl.taskGot': "Tâche faite !",
  'dl.reward': "Récompense",
  'dl.nice': "Génial !",
  'dl.streak': "{n} jours d’affilée",
  'dl.seeAll': "Voir les tâches",
  'dl.taskDone': "{n} tâche(s) faite(s) : récupère la récompense dans Tâches",
  'ach.habit': "Habitude",
  'ach.devoted': "Dévoué",
  'ach.loyal': "Fidèle",
  'ach.regular_face': "Habitué",
  'ach.dutiful': "Consciencieux",
  'ach.workhorse': "Bourreau de travail",
  'ach.taskmaster': "Maître des tâches",
  'achd.streak': "Reviens {n} jours d’affilée",
  'achd.calDays': "Récupère {n} récompenses quotidiennes",
  'achd.tasksDone': "Termine {n} tâches",
  'map.title': "Carte",
  'map.any': "N’importe laquelle",
  'map.hint': "La plus votée gagne, égalité tirée au sort",
  'map.hintNone': "Vote pour la carte : la plus votée gagne",
  'map.now': "Carte : {m}",
  'map.docks': "Docks de nuit",
  'map.chain': "Blockchain",
  'map.lego': "Ville en briques",
  'map.dunes': "Dunes rouges",
  'map.snow': "Gel mordant",
  'map.lava': "Forge de lave",
  'map.city': "Centre-ville",
  'map.neon': "Arcade néon",
  'map.blackout': "Black-out",
  'map.fantasy': "Donjon du dragon",
  'map.toon': "Toonville",
  'map.gravity': "Piste Gravity",
  'map.speedway': "Circuit de nuit",
  'map.skate': "Skatepark",
  'map.metro': "Métro",
  'map.factory': "Usine",
  'map.jungle': "Temple de la jungle",
  'map.junkyard': "Casse auto",
  'map.moon': "Base lunaire",
  'map.casino': "Casino",
  'swap.rate': "Taux",
  'swap.impactK': "Impact sur le prix",
  'swap.minGet': "Minimum reçu ({p} % de glissement)",
  'swap.highImpact': "Impact élevé : vous recevrez bien moins que le prix du marché. Essayez un montant plus petit.",
  'swap.pick': "Choisir une pièce",
  'swap.youPay': "Vous payez",
  'swap.youGet': "Vous recevez",
  'swap.balance': "Solde",
  'swap.inGame': "en jeu",
  'swap.listNote': "Pièces de la liste vérifiée d'AVNU et de celle d'Ekubo.",
  'swap.empty': "Rien sur votre solde de jeu pour l'instant.",
  'rd.tabAll': "Tous les joueurs",
  'rd.tabSeason': "Saison classée",
  'rd.kd': "K/D",
  'rd.deaths': "Morts",
  'rd.myPvp': "Vos stats PvP",
  'rd.noPvp': "Jouez un match PvP en ligne pour obtenir votre K/D.",
  'rd.emptyAll': 'Aucun match PvP en ligne pour l’instant. Joue et prends la tête.',
  'rd.kdNote': "K/D = éliminations ÷ morts en PvP en ligne (les zombies ne comptent pas). 3 matchs pour être classé au K/D.",
  'rd.sortBy': "Trier par",
  'rd.by.kd': "K/D",
  'rd.by.kills': "Éliminations",
  'rd.by.xp': "XP de rang",
  'reg.table': "Serveur : {r}",
  'reg.closer': "Plus proche de vous : {r} ({ms} ms). Choisissez-le dans le lobby pour jouer avec ceux qui y sont.",
  'net.connecting': 'Connexion au serveur…',
  'net.down': 'Serveur injoignable. Nouvelle tentative… L’entraînement marche hors ligne.',
  'net.lost': 'Connexion perdue. Retour aux tables.',
  'q.pick': 'Choisissez une crypto pour miser.',
  'q.short': 'Pas assez de {c} pour une mise de {s}. Choisissez une autre crypto ou une mise plus petite.',
  'q.shortDeposit': 'Pas assez de {c} pour une mise de {s}. Choisissez une autre crypto, une mise plus petite, ou déposez.',
  'q.stable': 'Vous misez {s} en {c}. Sortez vivant pour garder tout ce que vous portez.',
  'q.coin': 'Vous misez {a} = {s} au cours du jour. Les gains reviennent en {c} au même taux.',
  'tb.live': 'Raid en cours · {t}',
  'tb.ready': '{n} prêts · {s}s',
  'tb.waiting': '{n} en attente',
  'tb.golden': 'Prochain : raid doré',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Réglages d’entraînement',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Facile',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difficile',
  'pcfg.runners': 'Coureurs dans le raid',
  'pcfg.time': 'Durée du raid',
  'rk.max': 'grade max',
  'rk.toNext': '{x} XP jusqu’au grade {r}',
  'rk.of': 'Grade {r} sur 90',
  'rk.rank': 'Grade',
  'rk.up': 'Promotion',
  'rk.xp': 'XP de grade',
  'xp.Raid': 'Raid',
  'xp.kills': '{n} éliminations',
  'xp.Damage': 'Dégâts',
  'xp.Time alive': 'Temps en vie',
  'xp.First blood': 'Premier sang',
  'xp.Double kill': 'Double élimination',
  'xp.Triple kill': 'Triple élimination',
  'xp.Rampage': 'Carnage',
  'xp.Godlike': 'Divin',
  'xp.Full arsenal': 'Arsenal complet',
  'xp.Extracted': 'Extraction',
  'xp.Profit': 'Profit',
  'xp.Practice ×0.5': 'Entraînement ×0.5',
  'rk.newRank': "Nouveau grade",
  'rw.continue': "Continuer",
  'rw.title': 'Récompense de promotion',
  'rw.trial': 'à vous pendant 1 heure',
  'rw.try': 'L’essayer',
  'rw.share': 'Partager la promotion',
  'prep.raid': 'Raid {n} · mise {s}',
  'prep.readyUp': 'Prêt ?',
  'prep.first': 'Le compte à rebours démarre quand le premier coureur est prêt.',
  'prep.live': 'Un raid est en cours. Soyez prêt et vous entrerez dans le suivant avec tout le monde.',
  'prep.over': 'Raid terminé. La salle ouvre dans un instant.',
  'prep.many': 'Ici tout le monde commence au couteau. Les bots arrivent dans les dernières secondes.',
  'prep.bots': 'Les bots comblent les places libres dans les dernières secondes.',
  'prep.open': 'libre',
  'prep.pot': 'Pot',
  'prep.cancel': 'Annuler · rembourser {v}',
  'prep.ready': 'Prêt · mise {v}',
  'prep.back': 'Retour aux tables',
  'hud.bagPrivate': 'Votre sac · privé',
  'hud.lag': 'Le serveur ne répond pas · reconnexion…',
  'hud.golden': 'Raid doré',
  'hud.goldenStart': 'Raid doré · butin du jackpot à l’intérieur',
  'hud.start': "Couteau en main · ramasse l'orange · la sortie est au centre",
  'hud.bagOpened': 'Sac ouvert · +{v}',
  'hud.arsenal': "Arsenal complet · retour au pistolet ★",
  'hud.unlocked': '{w} débloqué',
  'hud.pnl': '{d} par rapport à la mise de {s}',
  'hud.alive': '{n} à l’intérieur',
  'hud.next': 'Suivant : {w}',
  'hud.final': 'Cercle final · dernière sortie',
  'hud.closing': 'La tempête se referme · {t}',
  'hud.stormIn': 'La tempête avance dans {t}',
  'hud.dash': 'Esquive',
  'hud.bagLook': 'Allure du sac',
  'hud.extracting': 'Extraction',
  'hud.someoneOut': "⚠ {name} sort · {s} s pour l'arrêter !",
  'hud.holdStill': 'Ne bougez pas. Un coup remet à zéro.',
  'hud.sound': 'Son',
  'hud.music': 'Musique',
  'bluff.0': 'petit',
  'bluff.1': 'moyen',
  'bluff.2': 'gros',
  'touch.move': 'bouger',
  'touch.aim': 'viser · tirer',
  'touch.bag': 'Sac',
  'w.Knife': 'Couteau',
  'w.Pistol': 'Pistolet',
  'w.Shotgun': 'Fusil à pompe',
  'w.SMG': 'Mitraillette',
  'w.Rifle': 'Fusil',
  'w.Laser sniper': 'Sniper laser',
  'w.Hand Cannon': "Canon de poing",
  'w.Auto Shotgun': "Fusil à pompe auto",
  'w.PDW': "PDW",
  'w.Carbine': "Carabine",
  'w.Scout': "Éclaireur",
  'w.Machine Gun': "Mitrailleuse",
  'w.Magnum Sniper': "Sniper Magnum",
  'hud.reloading': "Rechargement",
  'streak.1': 'Premier sang',
  'streak.2': 'Double élimination',
  'streak.3': 'Triple élimination',
  'streak.4': 'Carnage',
  'streak.5': 'Divin',
  'streak.you1': 'Vous avez fait couler le premier sang',
  'feed.storm': 'La tempête vous a eu',
  'feed.droppedYou': '{name} vous a abattu',
  'coach.storm': 'Vous êtes dans la tempête · revenez dans le cercle',
  'coach.touch': "Pouce gauche pour bouger · maintiens Tir : il vise tout seul l'ennemi le plus proche",
  'coach.keys': 'WASD pour bouger · souris pour viser · clic pour attaquer',
  'coach.exit': "Il faut sortir · la SORTIE est au centre · tiens-la 10 secondes · les flèches montrent le chemin",
  'coach.loot': 'Ramassez le butin orange · il va dans votre sac',
  'coach.kills': 'Les éliminations améliorent votre arme · Espace pour esquiver',
  'coach.killsTouch': 'Les éliminations améliorent votre arme · touchez Esquive',
  'spect.watching': 'Vous regardez {name} · ◀ ▶ pour changer',
  'spect.down': 'Vous êtes tombé',
  'spect.results': 'Résultats',
  'res.extracted': 'Extrait',
  'res.storm': 'Englouti par la tempête',
  'res.dropped': 'Abattu',
  'res.sealed': 'Enfermé à l’intérieur',
  'res.inside': '{k} éliminations · {t} à l’intérieur',
  'res.out': 'Sorti avec {p} pour une mise de {s} : {d}.',
  'res.paid': 'Payé {v} au taux d’entrée.',
  'res.killer': '{n} a votre sac maintenant. Il contenait {v}, et vous serez les deux seuls à le savoir.',
  'res.inStorm': 'Votre sac, {v}, traîne dans la tempête pour qui osera.',
  'res.sealedText': 'Le raid s’est fermé avec vous dedans. Vos {v} passent dans le butin du raid suivant.',
  'res.again': 'Rejouer',
  'res.tables': 'Tables',
  'res.share': 'Partager',
  'share.title': 'Partager',
  'share.x': 'Publier sur 𝕏',
  'share.copy': 'Copier l’image',
  'share.save': 'Enregistrer le PNG',
  'share.close': 'Fermer',
  'lk.title': 'Casier',
  'lk.outfits': 'Tenues',
  'lk.shop': 'Boutique',
  'lk.bags': 'Sacs chance',
  'lk.sortDesc': "Les plus rares d'abord ↓",
  'lk.sortAsc': "Les plus communs d'abord ↑",
  'lk.allGuns': "Toutes les armes",
  'lk.takeOff': "Retirer",
  'lk.empty': "Rien pour l'instant : les sacs et caisses de la boutique remplissent ta collection.",
  'lk.emptyTurrets': "Pas encore de skins de tourelle : ils viennent du passe de combat.",
  'lk.pickSkin': "Touche un skin pour l'essayer, puis équipe-le.",
  'lk.all': 'Toutes',
  'lk.owned': 'Les miennes',
  'lk.him': 'Lui',
  'lk.her': 'Elle',
  'lk.shopUsd': '$ boutique',
  'lk.shopNote': 'Rechargez des $ boutique en USDC ou USDT (les gros packs ont un bonus). Les $ boutique ne servent qu’ici et ne se retirent pas. Il en manque ? La différence est prise sur vos USDC/USDT.',
  'lk.bagsNote': 'Chances exactes, tirées sur le serveur. Pas de doublon avant d’avoir toute une rareté, et un doublon rend 10 % de son prix en $ boutique. Garantie : Épique+ en 15 ouvertures, Légendaire+ en 60.',
  'lk.topupFrom': '+ {v} USDC/USDT disponibles pour recharger',
  'lk.collected': '{a} / {b} obtenues',
  'lk.equipped': 'Équipée',
  'lk.equip': 'Équiper',
  'lk.buy': 'Acheter',
  'lk.trialLeft': 'Essai · encore {t}',
  'lk.trialHow': 'Essai de promotion : à vous encore {t}. Achetez-la pour la garder.',
  'lk.free': 'Gratuite pour tous.',
  'lk.inCollection': 'Dans votre collection.',
  'lk.buyOrBag': 'Achetez-la ici ou tentez votre chance avec un sac.',
  'lk.tryingOn': 'Essayage.',
  'lk.bonus': '+{n} % de bonus',
  'lk.pay': 'payez {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Épique+ dans',
  'lk.legIn': 'Légendaire+ dans',
  'lk.openFree': 'Ouvrir · gratuit',
  'lk.buyOpen': 'Acheter et ouvrir',
  'lk.pityDrop': 'garantie',
  'lk.dup': 'Déjà à vous · {v} rendus',
  'lk.new': '<b>Nouveau</b> dans votre collection',
  'lk.jackpotIs': 'le jackpot est {r}',
  'lk.showOff': 'Frimer sur X',
  'lk.postMiss': 'Publier le raté sur X',
  'lk.another': 'En ouvrir un autre',
  'lk.free1': 'gratuit',
  'lk.back': 'Retour au casier',
  'lk.yours': '{n} est à vous.',
  'r.common': 'Commun',
  'r.rare': 'Rare',
  'r.epic': 'Épique',
  'r.legendary': 'Légendaire',
  'r.mythic': 'Mythique',
  'r.exotic': 'Exotique',
  'ach.title': "Tâches et succès",
  'ach.button': 'Succès',
  'ach.intro': 'Chacun rapporte de l’XP de grade une fois et débloque son nom comme titre à porter.',
  'ach.wear': 'Porter le titre',
  'ach.worn': 'Porté',
  'ach.wearing': 'Titre :',
  'ach.takeOff': 'retirer',
  'ach.noTitle': 'Sans titre',
  'ach.unlocked': 'Succès débloqué',
  'ach.seeAll': 'Tous les succès',
  'achd.raids': 'Jouez {n} raids',
  'achd.extracts': 'Extrayez-vous {n} fois',
  'achd.kills': 'Faites {n} éliminations',
  'achd.bestKills': '{n} éliminations en un raid',
  'achd.bestMulti': 'Une multi-élimination ×{n}',
  'achd.prestige': 'Terminez l’arsenal {n} fois',
  'achd.firstBloods': 'Faites couler le premier sang {n} fois',
  'achd.secs': 'Passez {n} h en raid',
  'achd.bestReturn': 'Sortez avec {n}× votre mise',
  'achd.golden': 'Extrayez-vous d’un raid doré',
  'achd.lastExit': 'Sortez par la dernière sortie',
  'achd.pacifist': 'Extrayez-vous sans aucune élimination',
  'achd.rank': 'Atteignez le grade {n}',
  'achd.outfits': 'Possédez {n} tenues',
  'ach.gunslinger': "Flingueur",
  'ach.close_quarters': "Combat rapproché",
  'ach.spray_and_pray': "Arrose et prie",
  'ach.rifleman': "Fusilier",
  'ach.marksman': "Tireur d'élite",
  'ach.deadeye': "Œil de lynx",
  'ach.blade_dancer': "Danseur de lame",
  'ach.shadow_blade': "Lame de l'ombre",
  'ach.deathmatch_king': "Roi du deathmatch",
  'ach.duelist': "Duelliste",
  'ach.squad_goals': "Esprit d'équipe",
  'ach.one_shot_one_kill': "Un tir, un mort",
  'ach.specialist': "Spécialiste",
  'ach.engineer': "Ingénieur",
  'ach.ranked_debut': "Débuts en classé",
  'ach.ranked_grinder': "Acharné du classé",
  'ach.ranked_victor': "Vainqueur classé",
  'ach.gold_league': "Ligue Or",
  'ach.diamond_league': "Ligue Diamant",
  'ach.neon_legend': "Légende Néon",
  'ach.unboxer': "Déballeur",
  'ach.case_hunter': "Chasseur de caisses",
  'ach.case_lord': "Seigneur des caisses",
  'ach.armory': "Armurerie",
  'ach.arsenal_baron': "Baron de l'arsenal",
  'ach.pass_holder': "Détenteur du passe",
  'ach.pass_maxed': "Passe terminé",
  'ach.neon_bearer': "Porteur de néon",
  'ach.by_a_thread': "Sur le fil",
  'ach.untouchable': "Intouchable",
  'ach.ghost_walker': "Pas fantôme",
  'ach.one_tap': "Un seul coup",
  'achd.kHandgun': "Fais {n} éliminations au pistolet",
  'achd.kShotgun': "Fais {n} éliminations au fusil à pompe",
  'achd.kSmg': "Fais {n} éliminations au SMG",
  'achd.kRifle': "Fais {n} éliminations au fusil et à la mitrailleuse",
  'achd.kSniper': "Fais {n} éliminations au sniper",
  'achd.kKnife': "Fais {n} éliminations au couteau",
  'achd.dmWins': "Gagne {n} deathmatchs",
  'achd.duelWins': "Gagne {n} duels",
  'achd.teamWins': "Gagne {n} matchs en équipe",
  'achd.hcWins': "Gagne {n} matchs hardcore",
  'achd.weaponWins': "Gagne {n} matchs à une arme",
  'achd.turretKills': "Fais {n} éliminations avec des tourelles en Armes + Lasers",
  'achd.rankedGames': "Joue {n} matchs classés",
  'achd.rankedWins': "Gagne {n} matchs classés",
  'achd.bestDiv': "Atteins {n} en classé",
  'achd.opened': "Ouvre {n} caisses et sacs",
  'achd.wskins': "Possède {n} skins d'arme",
  'achd.passTier': "Atteins le palier {n} du passe",
  'achd.stitles': "Gagne un titre de saison",
  'achd.clutch': "Sors avec 10 PV ou moins",
  'achd.flawless': "Sors après 2+ minutes sans être touché",
  'achd.ninjaWin': "Gagne un mode à cagnotte sans une seule élimination",
  'achd.oneShots': "Fais passer {n} coureurs de la pleine santé à zéro d'un coup",
  'ach.secret': "Secret",
  'ach.secretDesc': "Continue de jouer : il se révèle quand tu l'obtiens.",
  'r.mystery': "Mystère",
  'ach.rookie': 'Bleu',
  'ach.regular': 'Habitué',
  'ach.veteran': 'Vétéran',
  'ach.lifer': 'De carrière',
  'ach.eternal': 'Éternel',
  'ach.escape_artist': 'As de l’évasion',
  'ach.ghost': 'Fantôme',
  'ach.smuggler': 'Contrebandier',
  'ach.phantom': 'Spectre',
  'ach.first_kill': 'Première élimination',
  'ach.hunter': 'Chasseur',
  'ach.butcher': 'Boucher',
  'ach.reaper': 'Faucheur',
  'ach.apex': 'Prédateur',
  'ach.rampage': 'Carnage',
  'ach.one_man_army': 'Armée à lui seul',
  'ach.double_tap': 'Doublé',
  'ach.triple_threat': 'Triple menace',
  'ach.godlike': 'Divin',
  'ach.full_arsenal': 'Arsenal complet',
  'ach.arsenal_master': 'Maître de l’arsenal',
  'ach.first_blood': 'Premier sang',
  'ach.opener': 'L’ouvreur',
  'ach.night_shift': 'Équipe de nuit',
  'ach.insomniac': 'Insomniaque',
  'ach.double_up': 'Quitte ou double',
  'ach.big_bag': 'Gros sac',
  'ach.gold_rush': 'Ruée vers l’or',
  'ach.last_one_out': 'Le dernier à sortir',
  'ach.pacifist': 'Pacifiste',
  'ach.seasoned': 'Aguerri',
  'ach.officer': 'Officier',
  'ach.commander': 'Commandant',
  'ach.legend': 'Légende',
  'ach.collector': 'Collectionneur',
  'ach.curator': 'Conservateur',
  'ach.hoarder': 'Thésauriseur',
  'intro.tag': "Misez. Pillez. Sortez.",
  'intro.go': "Entrer",
  'intro.fonts': "On aiguise les couteaux…",
  'intro.world': "On peint l'obscurité…",
  'intro.connect': "Recherche d'un raid…",
  'intro.profile': "On prépare votre sac…",
  'intro.ready': "Prêt",
  'tb.wallet': "Portefeuille",
  'tb.shop': "$ boutique",
  'nav.play': "Jouer",
  'nav.shop': "Boutique",
  'nav.inventory': "Inventaire",
  'nav.swap': "Échange",
  'nav.chat': "Chat",
  'nav.achievements': "Tâches",
  'nav.pass': "Passe",
  'bp.season': "Saison {n}",
  'bp.ends': "se termine dans {d} j {h} h",
  'bp.tier': "Palier {n}/{m}",
  'bp.xp': "{a}/{b} XP jusqu'au palier suivant",
  'bp.maxed': "Tous les paliers terminés",
  'bp.how': "Chaque raid remplit le passe avec la même XP que ton grade.",
  'bp.free': "Gratuit",
  'bp.premium': "Premium",
  'bp.buy': "Passe premium · {v}",
  'bp.owned': "Premium actif",
  'bp.perks': "Les 50 paliers de récompenses : armures Seigneur de guerre et Apex, 2 skins de tourelle, 5 skins d'arme de saison, caisses et $.",
  'bp.claim': "Récupérer",
  'bp.claimAll': "Tout récupérer ({n})",
  'bp.claimed': "Récupéré",
  'bp.limited': "Cette saison uniquement",
  'bp.turrets': "Skins de tourelle",
  'bp.turretsNote': "Tes tourelles en Armes + Lasers.",
  'bp.equip': "Équiper",
  'bp.equipped': "Équipé",
  'bp.none': "Standard",
  'bp.up': "Passe de combat : palier {n} !",
  'bp.got': "Récupéré : {x}",
  'bp.credit': "+{v} boutique",
  'mode.ranked': "Classé",
  'mode.ranked.d': "Battle royale pour ton classement de saison. De Bronze à Légende Néon ; les meilleures places gagnent un tirage bonus.",
  'nav.ranked': "Classé",
  'rd.title': "Classé · Saison {n}",
  'rd.pos': "#{n} sur {m}",
  'rd.unranked': "Joue un match classé pour entrer au tableau.",
  'rd.play': "Jouer en classé",
  'rd.games': "Matchs",
  'rd.wins': "Victoires",
  'rd.top3': "Top 3",
  'rd.kills': "Éliminations",
  'rd.winrate': "Taux de victoire",
  'rd.player': "Joueur",
  'rd.div': "Division",
  'rd.div.bronze': "Bronze",
  'rd.div.silver': "Argent",
  'rd.div.gold': "Or",
  'rd.div.platinum': "Platine",
  'rd.div.diamond': "Diamant",
  'rd.div.master': "Maître",
  'rd.div.legend': "Légende Néon",
  'rd.titles': "Titres de saison",
  'rd.titlesNote': "Gagnés au tirage bonus du classé. Brillent en néon au-dessus de ton nom, avec un bonus d'XP jusqu'à la fin de la saison.",
  'rd.wear': "Porter",
  'rd.off': "Retirer",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "saison terminée",
  'rd.board': "Classement de la saison",
  'rd.empty': "Personne n'a encore joué en classé cette saison. Sois le premier.",
  'rd.place': "Place #{p} sur {n}",
  'rd.promoted': "promu !",
  'rd.demoted': "rétrogradé",
  'rd.practice': "Entraînement : ton classement ne change pas.",
  'rd.spin': "Tirage bonus",
  'rd.spinWhy': "pour la place #{p}",
  'rd.won': "Tu gagnes :",
  'rd.wornNow': "Ton nouveau titre brille déjà au-dessus de toi.",
  'st.contender': "Prétendant",
  'st.elite': "Élite",
  'st.champion': "Champion",
  'xp.Season title': "Titre de saison",
  'news.title': "Nouveautés",
  'news.ok': "Compris",
  'news.note': "Chaque mise à jour, avec sa date et son heure.",
  'news.open': "Ouvrir",
  'stake.own': "Ta mise",
  'stake.range': "Mise de 0,10 $ à 10 000 $",
  'nav.settings': "Réglages",
  'nav.more': "Plus",
  'modes.title': "Mode de jeu",
  'kind.raid': "extraction",
  'kind.br': "le gagnant rafle le pot",
  'kind.team': "pot d'équipe",
  'mode.raid': "Raid",
  'mode.raid.d': "Pille, combats, puis tiens 10 s la sortie au centre. Tu gardes ce que tu portes.",
  'mode.br': "Battle royale",
  'mode.br.d': "Jusqu'à 20 coureurs. Le dernier debout rafle tout le pot.",
  'mode.duel': "Duel",
  'mode.duel.d': "Un contre un. Le gagnant rafle les deux mises.",
  'mode.knives': "Couteaux seulement",
  'mode.knives.d': "Lames uniquement, tout le raid. Le dernier debout gagne.",
  'mode.pistols': "Pistolets seulement",
  'mode.pistols.d': "Armes de poing uniquement. Le dernier debout gagne.",
  'mode.shotguns': "Fusils à pompe seulement",
  'mode.shotguns.d': "De près et bruyant. Le dernier debout gagne.",
  'mode.rifles': "Fusils seulement",
  'mode.rifles.d': "Fusillades à moyenne portée. Le dernier debout gagne.",
  'mode.snipers': "Snipers seulement",
  'mode.snipers.d': "Des viseurs laser partout. Le dernier debout gagne.",
  'mode.team2': "Équipes 2 c. 2",
  'mode.team2.d': "Chaque mise grossit un seul pot. La dernière équipe debout le partage.",
  'mode.team4': "Équipes 4 c. 4",
  'mode.team4.d': "Chaque mise grossit un seul pot. La dernière équipe debout le partage.",
  'mode.team8': "Équipes 8 c. 8",
  'mode.team8.d': "Chaque mise grossit un seul pot. La dernière équipe debout le partage.",
  'hud.pot': "Pot",
  'hud.left': "Encore {n} · mise {s}",
  'hud.teamsLeft': "Encore {n} équipes · mise {s}",
  'hud.startPot': "Le dernier debout rafle le pot",
  'hud.startTeam': "Restez avec votre équipe · éliminez l'autre camp",
  'hud.goldenPot': "Raid doré · jackpot ajouté au pot",
  'coach.pot': "Pas de sortie ici · restez dans le cercle · le dernier debout gagne",
  'coach.team': "Noms verts : votre équipe · rouges : l'ennemi",
  'warn.exit30': "Le temps presse · va à la sortie au centre",
  'warn.exit10': "Dernière chance · commence les 10 s maintenant ou perds tout",
  'warn.pot30': "30 s · la tempête se referme",
  'warn.pot10': "10 s · le camp avec le plus de vivants gagne",
  'storm.final': "Effondrement final · dernière sortie seulement",
  'storm.finalPot': "Effondrement final · nulle part où se cacher",
  'storm.closing': "La tempête approche",
  'storm.in5': "La tempête avance dans 5 s",
  'feed.youDropped': "Vous avez abattu {name}",
  'feed.stormTook': "{name} a été englouti par la tempête",
  'feed.dropped': "{a} a abattu {b}",
  'feed.down': "{name} est tombé",
  'feed.extracted': "{name} s'est extrait",
  'feed.exitClosed': "La sortie {name} est fermée",
  'spect.settling': "Votre résultat arrive quand le raid se termine.",
  'res.victory': "Victoire",
  'res.teamWon': "Votre équipe a gagné",
  'res.defeated': "Défaite",
  'res.wonText': "Vous avez raflé {p} pour une mise de {s}.",
  'res.lostPot': "Le pot est allé au dernier debout.",
  'res.teamLost': "L'autre équipe a raflé le pot.",
  'xp.Victory': "Victoire",
  'ach.champion': "Champion",
  'ach.warlord': "Seigneur de guerre",
  'achd.wins': "Gagnez {n} raids à pot",
  'lk.weapons': "Skins d'armes",
  'lk.onlyBags': "Les skins ne sortent que des sacs et caisses de la boutique.",
  'lk.toShop': "Ouvrir la boutique",
  'lk.toOpen': "{n} à ouvrir",
  'lk.limited': "Limité · {n}",
  'lk.minted': "{a} sur {b} frappés",
  'lk.plain': "Standard",
  'lk.fromBags': "Tombe des sacs de tenues de la boutique.",
  'lk.fromCrates': "Tombe des caisses d'armes de la boutique.",
  'lk.trialHow2': "Essai de promotion : à vous encore {t}.",
  'lk.weaponHow': "Choisissez une finition que vous possédez pour l'équiper. Tout le raid la voit.",
  'fx.glow': "aura",
  'fx.pulse': "aura pulsante",
  'fx.ghost': "spectral",
  'fx.laser': "yeux laser",
  'fx.rainbow': "prismatique",
  'fx.fire': "en flammes",
  'fx.gold': "or liquide",
  'fx.holo': "hologramme",
  'fx.glitch': "glitch",
  'fx.lightning': "éclairs",
  'fx.galaxy': "galaxie",
  'fx.sparks': "étincelles",
  'fx.frost': "givre",
  'fx.money': "pluie d'argent",
  'fx.matrix': "pluie de code",
  'fx.shadow': "fumée d'ombre",
  'fx.cape': "cape",
  'box.c-samurai': "Caisse Cyber Samouraï",
  'box.c-neon': "Caisse Nuits Néon",
  'box.c-arctic': "Caisse Arctique",
  'box.c-inferno': "Caisse Inferno",
  'box.c-crypto': "Caisse Rois Crypto",
  'box.c-toxic': "Caisse Terres Toxiques",
  'box.c-toon': "Caisse Toon Ville",
  'box.c-knife': "Caisse de couteaux",
  'box.c-pistol': "Caisse de pistolets",
  'box.c-smg': "Caisse de SMG",
  'box.c-rifle': "Caisse de fusils",
  'box.c-heavy': "Caisse lourde",
  'box.c-sniper': "Caisse de sniper",
  'box.b-crypto': "Sac Mèmes Crypto",
  'box.b-heroes': "Sac Héros du Multivers",
  'box.b-monsters': "Sac Monstres et Mythes",
  'box.b-cyber': "Sac Cyber Rue",
  'box.b-toon': "Sac Amis Toon",
  'shop.g.theme': "Collections",
  'shop.g.class': "Caisses par classe d'arme",
  'shop.g.tier': "Caisses par palier",
  'shop.contents': "Contenu · {n} objets",
  'box.street': "Sac de rue",
  'box.vault': "Sac du coffre",
  'box.golden': "Sac doré",
  'box.elite': "Sac d'élite",
  'box.diamond': "Sac diamant",
  'box.obsidian': "Sac d'obsidienne",
  'box.royal': "Sac royal",
  'box.apex': "Sac Apex",
  'box.genesis': "Sac Genesis",
  'box.w-scrap': "Caisse de ferraille",
  'box.w-armory': "Caisse d'armurerie",
  'box.w-brass': "Caisse de laiton",
  'box.w-specops': "Caisse des forces spéciales",
  'box.w-diamond': "Caisse diamant",
  'box.w-obsidian': "Caisse d'obsidienne",
  'box.w-royal': "Caisse royale",
  'box.w-apex': "Caisse Apex",
  'box.w-genesis': "Caisse Genesis",
  'shop.topup': "Recharger des $ boutique",
  'shop.bags': "Sacs de tenues",
  'shop.crates': "Caisses d'armes",
  'shop.bagsNote': "Des tenues pour votre coureur. Neuf niveaux : plus le sac est cher, meilleures sont les chances.",
  'shop.cratesNote': "Des skins pour vos armes et votre couteau, vendus séparément des tenues. Neuf niveaux.",
  'shop.fair': "Chances exactes, tirées sur le serveur. Garantie : Épique+ en {e} ouvertures, Légendaire+ en {l}.",
  'shop.odds': "Chances et garantie",
  'shop.qty': "Quantité",
  'shop.open': "Ouvrir ×{n}",
  'shop.limited': "Éditions limitées",
  'shop.soldOut': "Épuisé",
  'shop.dup': "Doublon · +{v}",
  'shop.new': "Nouveau",
  'shop.back': "{v} rendus",
  'shop.equipBest': "Équiper {n}",
  'inv.wallet': "Portefeuille",
  'inv.deposit': "Déposer · retirer",
  'inv.walletNote': "De vrais jetons que la maison garde pour vous. Retirez quand vous voulez vers l'adresse de connexion.",
  'inv.playNote': "De l'argent fictif dans ce navigateur. Rechargez quand vous voulez.",
  'inv.shopNote': "Acheté en USDC/USDT, dépensé uniquement en sacs et caisses. Impossible à retirer.",
  'inv.unopened': "Non ouverts",
  'inv.collection': "Collection",
  'inv.opened': "Ouverts",
  'inv.career': "Carrière",
  'inv.raids': "Raids",
  'inv.kills': "Éliminations",
  'inv.extracts': "Extractions",
  'inv.wins': "Pots gagnés",
  'inv.best': "Meilleur raid (éliminations)",
  'inv.time': "Temps en raid",
  'swap.game': "Solde en jeu",
  'swap.gameNote': "Instantané, au cours du moment, {f} % de frais.",
  'swap.gameOff': "Les échanges en jeu sont désactivés sur ce serveur. Utilisez l'échange dans votre portefeuille ci-dessous.",
  'swap.from': "Vous donnez",
  'swap.to': "Vous recevez",
  'swap.have': "Vous avez",
  'swap.flip': "Inverser",
  'swap.go': "Échanger",
  'swap.short': "Solde insuffisant",
  'swap.done': "{a} échangé contre {b}.",
  'swap.wallet': "Votre portefeuille",
  'swap.signIn': "Connectez un portefeuille Starknet pour y échanger via AVNU.",
  'swap.needChain': "Les échanges AVNU fonctionnent avec un vrai portefeuille Starknet en mode en ligne.",
  'swap.slippage': "Glissement max.",
  'swap.quoting': "Recherche du meilleur itinéraire…",
  'swap.impact': "impact prix {p} %",
  'swap.goAvnu': "Échanger avec AVNU",
  'swap.noQuote': "Pas d'itinéraire pour cette paire pour l'instant.",
  'swap.sent': "Échange envoyé : {tx}",
  'swap.walletNote': "AVNU route l'échange entre les plateformes Starknet. Vous signez dans votre portefeuille ; le jeu ne détient jamais ces jetons.",
  'chat.ph': "Dites quelque chose…",
  'chat.send': "Envoyer",
  'chat.empty': "Pas encore de message. Dites gm.",
  'chat.online': "Tout le lobby voit ceci. Restez courtois.",
  'chat.practice': "L'entraînement est hors ligne : seuls les bots écoutent.",
  'set.graphics': "Graphismes",
  'set.quality': "Qualité",
  'set.qualityNote': "Auto réduit les détails quand les images ralentissent.",
  'set.auto': "Auto",
  'set.high': "Haute",
  'set.medium': "Moyenne",
  'set.low': "Basse",
  'set.shake': "Tremblement d'écran",
  'set.motion': "Animations du menu",
  'set.display': "Affichage",
  'set.skins': "Skins",
  'set.skinsNote': "De qui dessiner les tenues et skins d'armes.",
  'set.skinsAll': "Tout le monde",
  'set.skinsMine': "Seulement les miens",
  'set.skinsNone': "Aucun",
  'set.names': "Noms au-dessus des coureurs",
  'set.titles': "Titres au-dessus des noms",
  'set.controls': "Commandes",
  'set.stick': "Taille des sticks tactiles",
  'set.lefty': "Gaucher (tactile)",
  'set.leftyNote': "Inverse les sticks de déplacement et de visée.",
  'set.audio': "Son",
  'set.sound': "Volume des effets",
  'set.music': "Volume de la musique",
  'set.track': "Bande-son",
  'set.trackAuto': "Mix",
  'set.trackNote': "Un morceau différent à chaque partie, ou garde ton préféré.",
  'pause.nextTrack': "Morceau suivant ⏭",
  'set.language': "Langue",
  'shop.exoticIn': "Exotique dans",
  'shop.guarantee': "Exotique garanti en {n} ouvertures",
  'set.voice': "Annonceur",
  'mode.dm': "Match à mort",
  'mode.dm.d': "Chacun pour soi, réapparition après chaque mort. Le plus de frags au coup de sifflet rafle la cagnotte.",
  'mode.gl': "Flingues + Lasers",
  'mode.gl.d': "Match à mort avec boutique : les frags rapportent des crédits pour des médikits, des tourelles et des mines laser.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Santé minimale : une balle et tu tombes. Le dernier debout rafle la cagnotte.",
  'kind.dm': "le plus de frags rafle la cagnotte",
  'hud.startDm': "Le plus de frags quand le chrono tombe à zéro rafle la cagnotte",
  'hud.startGl': "Les frags rapportent des crédits · 1 médikit · 2 tourelle · 3 mine laser",
  'hud.startHc': "Une touche et tu tombes. Fais compter chaque tir.",
  'hud.respawned': "De retour",
  'hud.respawnIn': "Retour dans {s}s",
  'hud.tookLead': "Vous avez pris la tête",
  'hud.lostLead': "Vous avez perdu la tête",
  'hud.dmScore': "{k} frags · {d} morts · #{p}",
  'hud.dmGoal': "Le premier frag prend la tête",
  'hud.oneHit': "1 TOUCHE",
  'feed.leader': "{name} prend la tête avec {k}",
  'gl.medkit': "Médikit",
  'gl.turret': "Tourelle",
  'gl.mine': "Mine laser",
  'gl.revive': "Ranimer l'escouade",
  'gl.no.none': "Personne n'est à terre",
  'gl.no.mode': "Seulement en mode zombies",
  'gl.revived': "{name} a ranimé {n} de l'escouade",
  'gl.you': "Toi",
  'gl.no.cash': "Pas assez de crédits",
  'gl.no.full': "Santé déjà au maximum",
  'gl.no.limit': "Limite atteinte",
  'gl.no.wall': "Trop près d'un mur",
  'res.dmLost': "Classé #{p}",
  'res.dmText': "{k} frags, {d} morts. Le gagnant en avait {top}.",
  'coach.dm': "Tu réapparais · le plus de frags à la fin gagne",
  'coach.gl': "Les frags rapportent des crédits · achète un médikit ✚, une tourelle ◈ ou une mine laser ⌁",
  'set.voiceNote': "Annonceur enregistré (anglais, ukrainien, espagnol, français, portugais ; anglais pour les autres langues).",
  'net.waking': "Réveil du serveur (l'hébergement gratuit s'endort quand personne ne joue, jusqu'à une minute)… L'entraînement marche en attendant.",
  'shop.bulk': "Une boîte sur {n} offerte",
  'shop.bulkOn': "Boîtes offertes incluses : {n}",
  'net.online': "{n} en ligne",
  'st.title': "Premiers pas",
  'st.signin': "Connecte-toi",
  'st.signin.d': "Avec ton portefeuille Starknet, Cartridge ou un e-mail.",
  'st.signin.go': "Se connecter",
  'st.fund': "Ajoute des fonds",
  'st.fund.d': "Envoie quelques jetons de ton portefeuille vers ton solde de jeu. Retrait possible à tout moment.",
  'st.fundTest': "Testnet : STRK gratuits sur starknet-faucet.vercel.app.",
  'st.fund.go': "Déposer",
  'st.coin': "Choisis ta monnaie",
  'st.coin.d': "Choisis ci-dessous la monnaie de ta mise. Les gains reviennent dans la même monnaie.",
  'st.coin.go': "Voir les monnaies",
  'st.play': "Joue ta première partie",
  'st.play.d': "Choisis un mode et une mise, appuie sur Jouer puis Prêt.",
  'st.play.go': "Jouer",
  'touch.fire': "Tir",
  'rot.title': "Tourne ton téléphone",
  'rot.sub': "Le raid se joue mieux à l'horizontale : déplacement à gauche, tir à droite.",
  'rot.anyway': "Jouer en vertical",
  'prep.waiting': "En attente de joueurs",
  'prep.waitingMe': "Pas de chrono : invite tes amis et appuie sur Lancer quand vous êtes prêts. Les places vides vont aux bots. {n} sur {of} places prises.",
  'prep.waitingJoin': "{n} sur {of} places prises. Mise et appuie sur Prêt pour rejoindre.",
  'prep.firstWait': "Appuie sur Prêt : la salle attend tout le monde, sans chrono.",
  'prep.start': "Lancer",
  'nav.friends': "Amis",
  'nav.guilds': "Guildes",
  'so.now': "à l'instant",
  'so.min': "il y a {n} min",
  'so.hr': "il y a {n} h",
  'so.day': "il y a {n} j",
  'so.seen': "Vu {t}",
  'so.st.lobby': "En ligne",
  'so.st.waiting': "Attend dans une salle",
  'so.st.raid': "En raid",
  'so.friend': "Ami",
  'so.sent': "Demande envoyée",
  'so.accept': "Accepter",
  'so.add': "Ajouter en ami",
  'so.invited': "Invité",
  'so.invite': "Inviter",
  'so.message': "Message",
  'so.onlineOnly': "Amis, messages et guildes fonctionnent en ligne.",
  'so.gInvite': "En guilde",
  'so.gInvited': "Invité",
  'so.gInviteSent': "Invitation de guilde envoyée",
  'so.gInvitesYou': "t'invite dans sa guilde",
  'so.gMembers': "{n} membres",
  'so.gJoin': "Rejoindre la guilde",
  'so.more': "Voir plus ({n})",
  'so.players': "Joueurs",
  'so.friends': "Amis",
  'so.messages': "Messages",
  'so.search': "Chercher un joueur par nom",
  'so.count': "{n} joueurs · {on} en ligne",
  'so.none': "Personne trouvé.",
  'so.wants': "veut être ton ami",
  'so.requests': "Demandes d'amis",
  'so.noFriends': "Pas encore d'amis. Trouve des gens dans Joueurs.",
  'so.pending': "Demandes envoyées",
  'so.cancel': "Annuler",
  'so.decline': "Refuser",
  'so.sayHi': "Dis bonjour 👋",
  'so.noMsgs': "Pas encore de messages.",
  'so.remove': "Retirer des amis",
  'so.onlineNow': "En ligne maintenant",
  'so.nobody': "Personne de libre en ligne pour l'instant.",
  'so.invitesYou': "t'invite à un raid",
  'so.waitingN': "{n} en attente",
  'so.join': "Rejoindre",
  'so.later': "Plus tard",
  'so.reqToast': "{n} veut être ton ami",
  'so.nowFriends': "{n} et toi êtes amis",
  'so.invSent': "Invitation envoyée",
  'so.invitePlayers': "Inviter des joueurs",
  'so.inviteHint': "Ils reçoivent une carte avec un bouton Rejoindre qui les amène dans cette salle.",
  'gd.members': "{n} membres",
  'gd.leave': "Quitter la guilde",
  'gd.join': "Rejoindre",
  'gd.all': "Toutes les guildes",
  'gd.needRank': "Rang {n} ou plus (toi : {have})",
  'gd.needBuy': "Au moins un achat en USDC/USDT",
  'gd.create': "Créer une guilde",
  'gd.name': "Nom de la guilde",
  'gd.tag': "Tag (2-5)",
  'gd.desc': "Courte description (facultatif)",
  'gd.found': "Fonder la guilde",
  'gd.count': "{n} membres · {on} en ligne",
  'gd.yours': "Ta guilde",
  'gd.list': "Guildes",
  'gd.none': "Pas encore de guildes. Sois le premier.",
  'gd.err.signin': "Connecte-toi d'abord.",
  'gd.err.member': "Quitte d'abord ta guilde.",
  'gd.err.purchase': "Fonder une guilde demande un achat en USDC/USDT.",
  'gd.err.rank': "Fonder une guilde demande le rang 20.",
  'gd.err.name': "Nom : 3-24 lettres, chiffres ou espaces.",
  'gd.err.tag': "Tag : 2-5 lettres ou chiffres.",
  'gd.err.taken': "Ce nom ou ce tag est déjà pris.",
  'pf.title': "Joueur",
  'pf.rank': "Rang {n}",
  'pf.guild': "Guilde : {g}",
  'pf.raids': "Raids",
  'pf.wins': "Victoires",
  'pf.kills': "Frags",
  'pf.extracts': "Extractions",
  'pf.best': "Record de frags",
  'pf.time': "Temps joué",
  'pf.ach': "Succès",
  'pf.multi': "Meilleure série",
  'pf.since': "Joue depuis",
  'tb.readyWait': "{n} en attente",
  'mc.waiting': "{n} en attente",
  'pause.open': "Menu (Échap)",
  'pause.title': "Menu",
  'pause.resume': "Reprendre",
  'pause.settings': "Réglages",
  'pause.leave': "Quitter la partie",
  'pause.leaveLose': "Quitter (mise perdue)",
  'pause.leaveSure': "Appuie encore pour quitter",
  'pause.keys': "Échap : retour à la partie",
  'pause.back': "← Retour",
  'pause.on': "oui",
  'pause.off': "non",
  'pause.practice': "L'entraînement est en pause.",
  'pause.practiceDead': "Tu es éliminé. Pars quand tu veux.",
  'pause.alive': "La partie continue pendant que le menu est ouvert. Si tu pars maintenant, ton coureur reste sur place et la mise reste dans la partie.",
  'pause.dead': "Tu es éliminé. Pars quand tu veux : tes gains éventuels arriveront quand même sur ton solde.",
  'gd.chat': "Chat",
  'gd.chatEmpty': "Pas encore de messages. Salue ta guilde.",
  'gd.chatPh': "Écris à ta guilde…",
  'swap.min': "Échange minimum : {v}",
  'prep.waitingPeople': "Pas de minuteur : invite tes amis, le raid peut commencer dès que {min} joueurs sont prêts. Que des vrais joueurs. {n} places sur {of} prises.",
  'prep.people': "Que des vrais joueurs : ici tout le monde commence au couteau.",
  'shop.firstTopup': "La première recharge est doublée : reçois autant en $ boutique, jusqu'à {v} en plus.",
  'tour.who': "ta contact",
  'tour.voice': "Voix oui/non",
  'tour.next': "Suivant",
  'tour.done': "C'est parti",
  'set.tour': "Visite",
  'set.tourNote': "Nyx te refait le tour du jeu.",
  'set.tourBtn': "Refaire la visite",
  'nyx.hello': "Coucouuu, coureur ! Moi c'est Nyx, ta guide ce soir ! Reste avec moi, et tu sortiras de ton tout premier raid... riche !",
  'nyx.name': "D'abord le plus important ! Tape un nom pour ton coureur, puis touche OK. Tout le monde le verra au-dessus de ta tête !",
  'nyx.nameOk': "Oh, trop mignon ce nom ! J'adore !",
  'nyx.practice': "Maintenant, touche Entraînement ! C'est gratuit, que des bots. Parfait pour ta première partie !",
  'nyx.practiceOk': "Ouiii ! Bon choix !",
  'nyx.modes': "Voici les modes de jeu ! Aujourd'hui on joue Raid, le classique. Pille, combats et sors ! Touche Raid !",
  'nyx.modeOk': "Va pour le Raid ! C'est parti !",
  'nyx.bag': "Le principe ! Ta mise va dans ton sac. Élimine quelqu'un, et son sac est à toi ! Tombe... et le tien est à lui. Aïe !",
  'nyx.shop': "Les tenues et skins d'armes sortent des sacs et caisses, ici dans la boutique ! Et psst... une gratuite t'attend !",
  'nyx.social': "Amis, messages, guildes ! Amène ton équipe. Tout est plus fun ensemble !",
  'nyx.wallet': "Envie de vraies mises ? Connecte-toi avec un portefeuille, ou juste un e-mail ! Les retraits ne vont qu'à ta propre adresse. En toute sécurité !",
  'nyx.play': "Prêt ? Appuie sur Jouer !",
  'nyx.ready': "Voici la salle d'attente ! Appuie sur Prêt, et on saute ! Youhou !",
  'nyx.start': "On y est ! Bouge avec W, A, S, D. Vise à la souris et clique pour tirer ! Espace pour le sprint !",
  'nyx.startTouch': "On y est ! Ton pouce gauche te déplace. Maintiens Tir à droite, il vise pour toi !",
  'nyx.loot': "Tu vois cette lueur orange ? C'est de l'argent ! Cours dessus !",
  'nyx.pickup': "Youpi ! Ton sac s'est alourdi !",
  'nyx.kill': "Premier sang ! Beau tir ! Ramasse ce qu'il a lâché. Oh, et une meilleure arme !",
  'nyx.hurt': "Aïe, tu es blessé ! La santé ne revient pas en combat, alors prudence !",
  'nyx.storm': "La tempête arrive ! Reste dans le cercle, vite !",
  'nyx.exit': "Oh, ce sac te va bien ! Trouve un anneau de sortie vert et tiens-toi dedans !",
  'nyx.extracting': "Ne bouge pas ! Trois secondes ! Ne te fais pas toucher !",
  'nyx.won': "Tu t'en es sorti ! Je savais que tu pouvais ! À la prochaine, coureur !",
  'nyx.dead': "Oh, ça arrive ! L'entraînement est gratuit, on recommence !",
  'tour.yourMove': "À toi",
  'tour.skipStep': "Passer cette étape",
  'tour.again': "Touche Nyx pour réécouter",
  'tour.replayHint': "Refaire la visite ? Réglages → Visite.",
  'mode.zombies': "Zombies",
  'mode.zombies.d': "Coop, seul ou avec jusqu'à 3 amis : 20 vagues de morts, chacune plus dure, des boss aux vagues 10 et 20. Sans chrono. Les éliminations rapportent des crédits pour tourelles, mines laser et trousses.",
  'mode.gold': "Ruée vers l'or",
  'mode.gold.d': "Des sacs d'or tombent partout dans la carrière. Armes au hasard, réapparition rapide. Celui qui en a le plus rafle tout le pot en crédit boutique.",
  'kind.zombie': "coop · XP",
  'kind.gold': "un seul gagnant · crédit",
  'tb.zFee': "entrée · XP, titres",
  'tb.goldFee': "entrée · le gagnant rafle tout",
  'prep.zFee': "entrée {v}",
  'prep.zSquad': "Escouade",
  'prep.goldPot': "Prix (crédit boutique)",
  'zp.title': "Ton arme pour le match",
  'zp.power': "Dégâts par seconde",
  'zp.melee': "sans recharge",
  'hud.waveK': "Vague",
  'hud.goldK': "Sacs d'or",
  'hud.startZ': "Tiens le cimetière. Ils viennent de partout",
  'hud.startGold': "Rafle l'or. Le plus de sacs gagne tout",
  'hud.wave': "Vague {n} sur {of}",
  'hud.bossWave': "DERNIÈRE VAGUE · LE BOSS EST LÀ",
  'hud.waveClear': "Vague {n} repoussée",
  'hud.patched': "+35 HP",
  'hud.summon': "Le boss appelle la horde",
  'hud.bossDown': "BOSS ABATTU · PARTIE TERMINÉE",
  'hud.bagsShort': "or",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "prochaine vague dans {s} s",
  'hud.zLeft': "{n} restants · {k} abattus",
  'hud.goldPlace': "place {p} · {d} morts · prix {s}",
  'hud.bossHp': "BOSS {p}%",
  'hud.zBreak': "Recharge et regroupe-toi : {s} s",
  'hud.zGoal': "Survis à 20 vagues · boss aux vagues 10 et 20",
  'hud.goldGoal': "Le plus de sacs à la fin gagne",
  'hud.zDown': "À terre. Tu reviens à la prochaine vague si ton escouade tient",
  'feed.zYou': "Les morts t'ont eu",
  'feed.zDown': "{name} a été déchiqueté",
  'coach.z': "Reste sur la place, dos à dos. Les éliminations paient : tourelles (2), mines laser (3), trousses (1)",
  'coach.gold': "Passe sur les sacs pour les prendre. Si tu meurs, la moitié tombe : ramasse, puis survis",
  'warn.z60': "Plus qu'une minute",
  'warn.z10': "10 secondes : tue le boss !",
  'warn.gold30': "30 secondes : ramasse ce que tu peux",
  'warn.gold10': "Plus que 10 secondes",
  'res.zCleared': "Partie terminée",
  'res.zFell': "Submergés à la vague {n}",
  'res.zWaves': "{n} / {of} vagues",
  'res.zWonText': "Dix vagues et leur boss, à {s}. Tu as abattu {k} morts.",
  'res.zText': "Tu as abattu {k} morts (escouade de {s}). Plus tu vas loin, plus d'XP.",
  'res.zTime': "temps {t}",
  'res.goldWon': "Ruée vers l'or gagnée",
  'res.goldLost': "Place {p} dans la ruée vers l'or",
  'res.goldWonText': "{b} sacs d'or, plus que tout le monde. {c} est sur ton solde boutique.",
  'res.goldText': "Tu as pris {b} sacs ; le gagnant en avait {top}. Seule la première place est payée.",
  'xp.Waves survived': "Vagues survécues",
  'xp.Zombies': "Zombies",
  'xp.Boss slain': "Boss abattu",
  'xp.Run cleared': "Partie terminée",
  'xp.Gold bags': "Sacs d'or",
  'ach.graveyard_shift': "Équipe de nuit",
  'ach.hold_the_line': "Tenir la ligne",
  'ach.undertaker': "Fossoyeur",
  'ach.exterminator': "Exterminateur",
  'ach.giant_slayer': "Tueur de géants",
  'ach.zombie_slayer': "Tueur de zombies",
  'ach.top_of_the_horde': "Tête de la horde",
  'ach.nightmare_walker': "Marcheur des cauchemars",
  'ach.army_of_one': "Armée à moi seul",
  'ach.prospector': "Prospecteur",
  'ach.gold_fever': "Fièvre de l'or",
  'ach.mother_lode': "Filon mère",
  'ach.bag_hoarder': "Amasseur de sacs",
  'ach.midas': "Midas",
  'achd.zRuns': "Joue une partie de zombies",
  'achd.bestWave': "Repousse la vague {n} de morts",
  'achd.zKills': "Tue {n} zombies",
  'achd.zBoss': "Porte le coup fatal au boss",
  'achd.zClears': "Termine la partie de zombies {n} fois",
  'achd.zMvp': "Termine une partie avec le plus de victimes de ton escouade",
  'achd.zSolo': "Termine la partie de zombies seul",
  'achd.goldRuns': "Joue une ruée vers l'or",
  'achd.goldWins': "Gagne {n} ruées vers l'or",
  'achd.bestGold': "Finis une ruée avec {n} sacs",
  'achd.goldBags': "Ramasse {n} sacs d'or au total",
  'tour.nameDone': "OK",
  'tour.finish': "On joue !",
  'nyx.stake': "Voici ta mise : ce que tu mets dans ton sac. En entraînement c'est de l'argent fictif, rien à perdre. On joue pour un dollar !",
  'nyx.retry': "Oh, tu es tombé ! Ça arrive, l'entraînement est gratuit ! Touche Rejouer. Cette fois, ramasse un peu de butin, puis cours vers une sortie verte !",
  'nyx.resultWon': "Tu t'en es sorti ! Tu as gagné ! Je savais que tu pouvais ! L'argent d'entraînement, c'est juste pour jouer. Appuie sur Tables, je te montre la boutique !",
  'nyx.shopGo': "Maintenant, touche la Boutique !",
  'nyx.shopCase': "Bienvenue à la boutique ! En entraînement, ce n'est qu'une démo, rien n'est débité. Appuie sur Démo sur ce sac et regarde-le s'ouvrir !",
  'nyx.shopEquip': "Oh, regarde ce qui est sorti ! En ligne, avec tes $ boutique, ce serait à toi. Appuie sur Fermer !",
  'nyx.bye': "C'est tout ! Tu sais jouer, gagner et acheter. Fonce, coureur ! Tu peux me rappeler quand tu veux dans les Réglages.",
  'hud.headshot': "EN PLEINE TÊTE",
  'inv.open': "Ouvrir",
  'bp.later': "Plus tard",
  'ach.sharpshooter': "Tireur d'élite",
  'ach.headhunter': "Chasseur de têtes",
  'achd.headshots': "Place {n} tirs en pleine tête",
  'hud.demoted': "Mort : retour à {w}",
  'hud.crit': "CRITIQUE",
  'hud.roundStart': "Manche {n} sur {of}",
  'hud.roundWon': "Manche {n} gagnée !",
  'hud.roundLost': "Manche {n} perdue",
  'hud.roundDraw': "Manche {n} : égalité",
  'hud.roundTo': "Manche {n} pour {name}",
  'hud.roundNext': "Prochaine manche dans {s} s",
  'hud.roundScore': "Manche {n}/{of} · {a} : {b}",
  'hud.roundDown': "À terre. Retour à la prochaine manche",
  'mc.rounds': "{w} manches sur {n}",
  'hud.midBossWave': "VAGUE 10 · UN BOSS FRANCHIT LA CLÔTURE",
  'hud.midBossDown': "Boss abattu ! Encore dix vagues",
  'ach.last_stand': "Dernier rempart",
  'gl.upTurret': "Tourelle améliorée : niveau {lv}",
  'gl.upMine': "Mine laser améliorée : {lv} rayons",
  'gl.upHint': "Espace: {what} → niveau {lv} · {c} CR",
  'gl.upHintTouch': "⬆ {what} → niveau {lv} · {c} CR",
  'gl.no.max': "Déjà au niveau max",
  'gl.no.near': "Approche-toi de ta tourelle ou mine",
  'nav.invite': "Inviter",
  'ref.title': "Invite tes amis",
  'ref.lead': "Fais venir tes amis avec ton lien. Pendant {d} jours tu touches {p} % de la commission de la maison sur chacune de leurs mises, en $ boutique.",
  'ref.yourCode': "Ton code",
  'ref.link': "Ton lien d'invitation",
  'ref.copy': "Copier",
  'ref.share': "Partager",
  'ref.copied': "Lien copié",
  'ref.shareText': "Viens faire des raids avec moi sur DARK BAGS. Mon code : {c}",
  'ref.invited': "Invités",
  'ref.active': "Ont joué un match",
  'ref.earned': "Tu as gagné",
  'ref.how': "Comment ça marche",
  'ref.step1': "Ton ami ouvre ton lien (ou tape ton code) avant son premier match",
  'ref.step2': "Après son premier match avec mise, il reçoit un sac de bienvenue",
  'ref.step3': "Chacune de ses mises te rapporte {p} % de la commission de la maison pendant {d} jours, en $ boutique",
  'ref.step4': "Quand il a joué {m} matchs, tu reçois un sac bonus",
  'ref.fair': "Fair-play : les comptes sur ton réseau ou ton appareil ne comptent pas, il y a une limite par jour et la triche annule toutes les récompenses.",
  'ref.by': "Tu es venu avec le code {c}",
  'ref.have': "Un ami t'a donné un code ?",
  'ref.apply': "Valider",
  'ref.online': "Les invitations marchent en jeu en ligne. Active-le dans les Réglages.",
  'ref.signin': "Connecte-toi pour obtenir ton lien.",
  'ref.claimedToast': "Code validé : ton sac de bienvenue arrive après ton premier match",
  'ref.err.already': "Tu as déjà un parrain",
  'ref.err.unknown': "Ce code n'existe pas",
  'ref.err.self': "Tu ne peux pas t'inviter toi-même",
  'ref.err.late': "Les codes ne marchent qu'avant ton premier match",
  'ref.err.linked': "Ce code vient de ton propre réseau ou appareil",
  'ref.err.busy': "Ce parrain a atteint sa limite du jour. Réessaie demain",
  'err.guard_seat': "Un autre compte de ton réseau ou appareil est déjà à cette table",
  'err.guard_new': "Trop de nouveaux comptes depuis ton réseau aujourd'hui. Reviens demain",
  'err.guard_faucet': "Ton réseau a déjà reçu ses jetons de test aujourd'hui",
  'res.practiceNoXp': "L'entraînement est gratuit : ni XP ni récompenses. Joue en ligne pour monter en rang.",
  'online.only': "En ligne uniquement. L'entraînement est gratuit, il ne compte ni pour la passe ni pour le classement. Passe en ligne sur la page Jouer.",
  'err.online_only': "Ça ne marche qu'en ligne",
  'tour.skip': "Passer le tutoriel",
  'tour.skipped': "Tutoriel passé. Tu peux rappeler Nyx dans les Réglages.",
  'shop.demo': "Démo",
  'shop.demoNote': "Une démo : rien n'a été débité ni donné. En ligne, tu ouvres les sacs avec des $ boutique et tu gardes ce qui tombe.",
  'acct.signin': "Connexion",
  'acct.copy': "Copier l'adresse",
  'acct.explorer': "Explorateur",
  'acct.inWallet': "Dans le portefeuille",
  'acct.inGame': "En jeu",
  'acct.deposit': "Déposer",
  'acct.withdraw': "Retirer",
  'acct.cartridge': "Ouvrir le portefeuille Cartridge",
  'acct.signout': "Déconnexion",
  'acct.copied': "Adresse copiée",
  'br.tab': "Acheter et bridges",
  'br.buy': "Acheter par carte",
  'br.buySub': "Carte, Apple Pay ou virement, directement dans ton portefeuille Starknet",
  'br.intro': "Fais venir des cryptos sur Starknet : achète-les par carte ou transfère-les depuis une autre chaîne sur le site du bridge. Elles arrivent dans ton portefeuille Starknet ; ensuite Déposer (en privé si ton portefeuille le permet) les met dans le jeu.",
  'br.yourAddr': "Ton adresse Starknet :",
  'br.in': "Vers Starknet",
  'br.out': "Depuis Starknet",
  'br.fromNet': "Depuis le réseau",
  'br.toNet': "Vers le réseau",
  'br.youSend': "Tu envoies",
  'br.youGet': "Tu reçois",
  'br.amount': "Montant",
  'br.refund': "Ton adresse {c} (pour les remboursements)",
  'br.refundPh': "Où revient l'argent si l'échange échoue",
  'br.recipient': "Adresse {c} qui reçoit",
  'br.recipientPh': "L'adresse de réception sur ce réseau",
  'br.landsIn': "Arrive sur ton portefeuille Starknet {a} ; ensuite Déposer l'envoie dans le jeu.",
  'br.fromWallet': "Envoyé depuis ton portefeuille Starknet {a}.",
  'br.fee': "Inclut nos frais de {p} %.",
  'br.getAddr': "Obtenir l'adresse de dépôt",
  'br.send': "Envoyer depuis mon portefeuille",
  'br.estimate': "Tu reçois environ {a} ({u}), en ~{s} s",
  'br.needAmount': "Indique un montant.",
  'br.needRefund': "Indique ton adresse sur le réseau d'envoi, pour les remboursements.",
  'br.needRecipient': "Indique l'adresse de réception.",
  'br.sent': "Envoyé. Le pont s'occupe du reste.",
  'br.sendExactly': "Envoie exactement {a} sur {c} à cette adresse :",
  'br.memo': "Mémo (obligatoire)",
  'br.copyMemo': "Copier le mémo",
  'br.outSent': "{a} envoyé au pont vers {c}.",
  'br.youGetAbout': "Tu reçois environ {a} sur {c}.",
  'br.deadline': "Remboursement si non terminé avant {t}.",
  'br.toGame': "Le déposer dans le jeu",
  'br.new': "Nouveau transfert",
  'br.others': "Autres ponts",
  'br.othersNote': "Ouvre le site du pont ; aucun frais de notre part. Envoie vers ton adresse Starknet du panneau portefeuille.",
  'br.lsSub': "Plus de 40 réseaux et plateformes",
  'br.avnuSub': "Échanger des jetons sur Starknet",
  'br.mainnetOnly': "Les ponts marchent avec de vraies cryptos sur le mainnet Starknet. En testnet, utilise ceux ci-dessous.",
  'br.s.wait': "En attente de ton dépôt",
  'br.s.seen': "Dépôt vu, confirmation",
  'br.s.partial': "Dépôt trop faible ; envoie le reste ou attends le remboursement",
  'br.s.proc': "Transfert…",
  'br.s.ok': "Fini : c'est dans ton portefeuille",
  'br.s.refund': "Remboursé",
  'br.s.fail': "Échec ; rien n'a été pris",
  'nav.mail': "Courrier",
  'mail.claim': "Récupérer",
  'mail.claimed': "Reçu : {g}",
  'mail.creditNote': "$ boutique : à dépenser en boutique. Impossible de les retirer ou de les vendre.",
  'mail.empty': "Pas encore de courrier.",
  'mail.g.credit': "{v} en $ boutique",
  'mail.g.spin': "{n} tour(s) de roue",
  'mail.g.trial': "{n} pendant 1 h",
  'mail.newToast': "Nouveau courrier !",
  'mail.noSpins': "Plus de tours",
  'mail.pick': "Choisis une lettre pour la lire.",
  'mail.signin': "Connecte-toi pour recevoir du courrier.",
  'mail.spinBtn': "Tourner la roue ({n})",
  'mail.spinNow': "Tourner !",
  'mail.taken': "Reçu",
  'mail.welcomeToast': "Bonus de bienvenue ! Tu portes le titre Fondateur, et un tour de roue t'attend dans le Courrier.",
  'mail.wheel': "Roue de la fortune",
  'mail.wheelNote': "Un skin de coureur 1 h, un skin d'arme 1 h ou jusqu'à 2 $ de $ boutique.",
  'mail.trial72': "À toi pendant 1 heure. Équipe-le depuis l'inventaire.",
  'mail.welcome.t': "♛ Bienvenue, Fondateur !",
  'mail.welcome.b': "Tu fais partie des premiers à soutenir DARK BAGS avec une vraie recharge, et nous ne l'oublierons pas. Merci !\n\nDès aujourd'hui tu portes le titre premium Fondateur en or vivant : seuls ceux qui ont cru au jeu dès le début l'auront.\n\nTon cadeau est ci-dessous : un tour de la roue de la fortune. Bonne chance, on se retrouve dans le noir.\n\nL'équipe DARK BAGS",
  'ach.founder': "Fondateur",
  'achd.deposits': "Fais ta première recharge",
  'r.premium': "Premium",
  'mail.jackpot.t': "🎰 Jackpot de la roue !",
  'mail.jackpot.b': "La cagnotte de la fortune était pour toi : les jetons arrivent (ou sont déjà sur ton solde de jeu). Bravo !",
  'fw.bank': "Cagnotte de la fortune",
  'fw.coin': "Payer en",
  'fw.inBalance': "Crédité sur ton solde de jeu : retirable à tout moment.",
  'fw.jackpot': "JACKPOT",
  'fw.kicker': "0,05 $ le tour",
  'fw.lead': "18 types de prix : skins 1 h, vrais skins à garder, style, caisses cadeaux, $ boutique, XP de pass, boosts d’XP, tours bonus. Chaque tour payant remplit la banque : celui qui atteint le palier rafle tout en vraies cryptos.",
  'fw.next': "paie à {m}",
  'fw.noCoins': "Dépose n'importe quelle crypto pour tourner.",
  'fw.odds': "Ce qui peut tomber",
  'fw.real': "Vrai skin ({r})",
  'fw.realKeep': "À toi pour toujours.",
  'fw.rules': "30 % de chaque tour vont dans la cagnotte. Quand elle atteint son palier (0,50 $, puis 1 $, 1,50 $, 2 $… jusqu'à 5 $), le tour qui l'atteint gagne toute la cagnotte en USDC (ou USDT, ou STRK). Les skins d'essai durent 1 heure. Les objets de boutique ne peuvent être ni retirés ni vendus.",
  'fw.sentChain': "Envoyé sur ton portefeuille Starknet.",
  'fw.share': "Partager le gain",
  'fw.spin': "Tourner",
  'fw.title': "Roue de la fortune",
  'fw.trial': "Skin de coureur 1 h",
  'fw.wtrial': "Skin d'arme 1 h",
  'coin.import': "Importer une crypto",
  'coin.search': "Recherche : symbole, nom ou adresse",
  'coin.added': "ajoutée",
  'coin.add': "Ajouter",
  'coin.none': "Rien trouvé",
  'coin.note': "N'importe quelle crypto Starknet de la liste vérifiée d'AVNU ou d'Ekubo. Une fois ajoutée, dépose-la et mise avec comme les autres ; les gains reviennent dedans.",
  'coin.done': "{s} ajoutée : dépose-la et choisis-la pour miser.",
  'coin.noPrice': "{s} ajoutée ; son prix apparaît dans une minute.",
};
