export default {
  'lobby.tagline': 'Aposte. Saqueie. Saia antes da tempestade. <b>Ninguém vê o que tem na sua bolsa.</b>',
  'lobby.namePh': 'Nome do seu corredor',
  'lobby.locker': 'Armário · skins · bolsas',
  'lobby.refill': 'Recarregar moedas de teste',
  'lobby.online': 'Online',
  'lobby.practice': 'Treino contra bots',
  'lobby.stakePer': 'Aposta por incursão',
  'lobby.stakeWith': 'Aposte com <span class="fine">qualquer moeda · mostrado em $ · os ganhos voltam na mesma moeda</span>',
  'lobby.play': 'Jogar · aposta {s}',
  'lobby.signIn': 'Entre para jogar',
  'lobby.how': 'Como jogar',
  'lobby.gore': '<b>Modo 18+.</b> Membros voam e o sangue fica no chão.',
  'lobby.fine': 'O treino roda no seu navegador. Todo o dinheiro aqui é de brincadeira.',
  'how.1': '<b>Aposte e fique pronto.</b> Todos entram juntos com uma faca e 100 de vida. Metade da aposta vai na sua bolsa, a outra metade vira saque espalhado.',
  'how.2': '<b>Pegue o saque laranja.</b> Ele vai para a sua bolsa. Abates melhoram sua arma: faca → pistola → escopeta → submetralhadora → fuzil → sniper a laser.',
  'how.3': '<b>Saia vivo.</b> Fique 3 segundos numa saída verde antes que a tempestade a feche. A bolsa inteira é sua. Morra e ela cai para outro.',
  'how.keys': '<kbd>WASD</kbd> mover · <kbd>mouse</kbd> mirar · <kbd>clique</kbd> atacar · <kbd>Espaço</kbd> esquiva · <kbd>Q</kbd> disfarçar o tamanho da bolsa · <kbd>M</kbd> som · <kbd>N</kbd> música',
  'how.fine': 'Cada incursão e cada conquista dão XP de patente. Cada promoção empresta uma skin nova por 3 dias.',
  'net.practice': 'Só você e os bots, offline.',
  'net.open': 'Conectado. Humanos e bots dividem cada incursão.',
  'net.connecting': 'Conectando ao servidor…',
  'net.down': 'Servidor indisponível. Tentando de novo… O treino funciona offline.',
  'net.lost': 'Conexão perdida. De volta às mesas.',
  'q.pick': 'Escolha uma moeda para apostar.',
  'q.short': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda ou uma aposta menor.',
  'q.shortDeposit': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda, uma aposta menor ou deposite.',
  'q.stable': 'Você aposta {s} em {c}. Saia vivo e fique com tudo o que carrega.',
  'q.coin': 'Você aposta {a} = {s} ao preço de hoje. Os ganhos voltam em {c} na mesma taxa.',
  'tb.live': 'Incursão rolando · {t}',
  'tb.ready': '{n} prontos · {s}s',
  'tb.waiting': '{n} esperando',
  'tb.golden': 'Próxima: incursão dourada',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Ajustes do treino',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Fácil',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difícil',
  'pcfg.runners': 'Corredores na incursão',
  'pcfg.time': 'Duração da incursão',
  'rk.max': 'patente máxima',
  'rk.toNext': '{x} XP até a patente {r}',
  'rk.of': 'Patente {r} de 90',
  'rk.rank': 'Patente',
  'rk.up': 'Promoção',
  'rk.xp': 'XP de patente',
  'xp.Raid': 'Incursão',
  'xp.kills': '{n} abates',
  'xp.Damage': 'Dano',
  'xp.Time alive': 'Tempo vivo',
  'xp.First blood': 'Primeiro sangue',
  'xp.Double kill': 'Abate duplo',
  'xp.Triple kill': 'Abate triplo',
  'xp.Rampage': 'Massacre',
  'xp.Godlike': 'Divino',
  'xp.Full arsenal': 'Arsenal completo',
  'xp.Extracted': 'Extração',
  'xp.Profit': 'Lucro',
  'xp.Practice ×0.5': 'Treino ×0.5',
  'rw.title': 'Recompensa de promoção',
  'rw.trial': 'seu por 72 horas',
  'rw.try': 'Experimentar',
  'rw.share': 'Compartilhar promoção',
  'prep.raid': 'Incursão {n} · aposta {s}',
  'prep.readyUp': 'Pronto?',
  'prep.first': 'A contagem começa quando o primeiro corredor ficar pronto.',
  'prep.live': 'Há uma incursão rolando. Fique pronto e entre na próxima com todos.',
  'prep.over': 'Incursão encerrada. A sala abre em instantes.',
  'prep.many': 'Aqui todo mundo começa com faca. Bots entram nos últimos segundos.',
  'prep.bots': 'Bots preenchem as vagas nos últimos segundos.',
  'prep.open': 'livre',
  'prep.pot': 'Pote',
  'prep.cancel': 'Cancelar · reembolsar {v}',
  'prep.ready': 'Pronto · aposta {v}',
  'prep.back': 'Voltar às mesas',
  'hud.bagPrivate': 'Sua bolsa · privada',
  'hud.golden': 'Incursão dourada',
  'hud.goldenStart': 'Incursão dourada · saque do jackpot lá dentro',
  'hud.start': 'Faca na mão · pegue o laranja · ache uma saída',
  'hud.bagOpened': 'Bolsa aberta · +{v}',
  'hud.arsenal': 'Arsenal completo · de volta à faca ★',
  'hud.unlocked': '{w} desbloqueada',
  'hud.pnl': '{d} contra a aposta de {s}',
  'hud.alive': '{n} lá dentro',
  'hud.next': 'Próxima: {w}',
  'hud.final': 'Círculo final · última saída',
  'hud.closing': 'Tempestade fechando · {t}',
  'hud.stormIn': 'A tempestade avança em {t}',
  'hud.dash': 'Esquiva',
  'hud.bagLook': 'Aparência da bolsa',
  'hud.extracting': 'Extraindo',
  'hud.holdStill': 'Fique parado. Um tiro zera o progresso.',
  'hud.sound': 'Som',
  'hud.music': 'Música',
  'bluff.0': 'pequena',
  'bluff.1': 'média',
  'bluff.2': 'gorda',
  'touch.move': 'mover',
  'touch.aim': 'mirar · atirar',
  'touch.bag': 'Bolsa',
  'w.Knife': 'Faca',
  'w.Pistol': 'Pistola',
  'w.Shotgun': 'Escopeta',
  'w.SMG': 'Submetralhadora',
  'w.Rifle': 'Fuzil',
  'w.Laser sniper': 'Sniper a laser',
  'streak.1': 'Primeiro sangue',
  'streak.2': 'Abate duplo',
  'streak.3': 'Abate triplo',
  'streak.4': 'Massacre',
  'streak.5': 'Divino',
  'streak.you1': 'Você tirou o primeiro sangue',
  'feed.storm': 'A tempestade te pegou',
  'feed.droppedYou': '{name} te derrubou',
  'coach.storm': 'Você está na tempestade · volte para o círculo',
  'coach.touch': 'Polegar esquerdo move · direito mira e ataca',
  'coach.keys': 'WASD para mover · mouse para mirar · clique para atacar',
  'coach.exit': 'Hora de sair · fique 3 segundos numa SAÍDA verde · as setas na borda mostram o caminho',
  'coach.loot': 'Pegue o saque laranja · ele vai para a sua bolsa',
  'coach.kills': 'Abates melhoram sua arma · Espaço para esquivar',
  'coach.killsTouch': 'Abates melhoram sua arma · toque em Esquiva',
  'spect.watching': 'Assistindo {name} · ◀ ▶ para trocar',
  'spect.down': 'Você caiu',
  'spect.results': 'Resultados',
  'res.extracted': 'Extraído',
  'res.storm': 'Engolido pela tempestade',
  'res.dropped': 'Derrubado',
  'res.sealed': 'Preso lá dentro',
  'res.inside': '{k} abates · {t} lá dentro',
  'res.out': 'Saiu com {p} numa aposta de {s}: {d}.',
  'res.paid': 'Pago {v} na taxa de entrada.',
  'res.killer': '{n} está com a sua bolsa agora. Tinha {v}, e só vocês dois vão saber.',
  'res.inStorm': 'Sua bolsa, {v}, está na tempestade para quem tiver coragem.',
  'res.sealedText': 'A incursão fechou com você lá dentro. Seus {v} foram para o saque da próxima.',
  'res.again': 'Jogar de novo',
  'res.tables': 'Mesas',
  'res.share': 'Compartilhar',
  'share.title': 'Compartilhar',
  'share.x': 'Postar no 𝕏',
  'share.copy': 'Copiar imagem',
  'share.save': 'Salvar PNG',
  'share.close': 'Fechar',
  'lk.title': 'Armário',
  'lk.outfits': 'Visuais',
  'lk.shop': 'Loja',
  'lk.bags': 'Bolsas da sorte',
  'lk.all': 'Todos',
  'lk.owned': 'Meus',
  'lk.him': 'Ele',
  'lk.her': 'Ela',
  'lk.shopUsd': '$ da loja',
  'lk.shopNote': 'Recarregue $ da loja com USDC ou USDT (pacotes maiores dão bônus). $ da loja só vale aqui e não pode ser sacado. Faltou? A diferença sai dos seus USDC/USDT.',
  'lk.bagsNote': 'Chances exatas, sorteadas no servidor. Sem repetidos até completar uma raridade, e um repetido devolve 10% do preço em $ da loja. Garantia: Épico+ em 15 aberturas e Lendário+ em 60.',
  'lk.topupFrom': '+ {v} USDC/USDT para recarregar',
  'lk.collected': '{a} / {b} coletados',
  'lk.equipped': 'Equipado',
  'lk.equip': 'Equipar',
  'lk.buy': 'Comprar',
  'lk.trialLeft': 'Teste · faltam {t}',
  'lk.trialHow': 'Teste de promoção: seu por mais {t}. Compre para ficar com ele.',
  'lk.free': 'Grátis para todos.',
  'lk.inCollection': 'Na sua coleção.',
  'lk.buyOrBag': 'Compre aqui ou tente a sorte com uma bolsa.',
  'lk.tryingOn': 'Experimentando.',
  'lk.bonus': '+{n}% de bônus',
  'lk.pay': 'paga {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Épico+ em',
  'lk.legIn': 'Lendário+ em',
  'lk.openFree': 'Abrir · grátis',
  'lk.buyOpen': 'Comprar e abrir',
  'lk.pityDrop': 'garantia',
  'lk.dup': 'Já é seu · {v} de volta',
  'lk.new': '<b>Novo</b> na sua coleção',
  'lk.jackpotIs': 'o jackpot é {r}',
  'lk.showOff': 'Exibir no X',
  'lk.postMiss': 'Postar o azar no X',
  'lk.another': 'Abrir outra',
  'lk.free1': 'grátis',
  'lk.back': 'Voltar ao armário',
  'lk.yours': '{n} é seu.',
  'r.common': 'Comum',
  'r.rare': 'Raro',
  'r.epic': 'Épico',
  'r.legendary': 'Lendário',
  'r.mythic': 'Mítico',
  'r.exotic': 'Exótico',
  'ach.title': 'Conquistas',
  'ach.button': 'Conquistas',
  'ach.intro': 'Cada uma dá XP de patente uma vez e libera seu nome como título para usar.',
  'ach.wear': 'Usar título',
  'ach.worn': 'Em uso',
  'ach.wearing': 'Título:',
  'ach.takeOff': 'tirar',
  'ach.noTitle': 'Sem título',
  'ach.unlocked': 'Conquista liberada',
  'ach.seeAll': 'Todas as conquistas',
  'achd.raids': 'Jogue {n} incursões',
  'achd.extracts': 'Extraia-se {n} vezes',
  'achd.kills': 'Faça {n} abates',
  'achd.bestKills': '{n} abates numa incursão',
  'achd.bestMulti': 'Um abate múltiplo ×{n}',
  'achd.prestige': 'Complete o arsenal {n} vezes',
  'achd.firstBloods': 'Tire o primeiro sangue {n} vezes',
  'achd.secs': 'Passe {n} h dentro de incursões',
  'achd.bestReturn': 'Saia com {n}× a sua aposta',
  'achd.golden': 'Extraia-se de uma incursão dourada',
  'achd.lastExit': 'Saia pela última saída',
  'achd.pacifist': 'Extraia-se sem nenhum abate',
  'achd.rank': 'Chegue à patente {n}',
  'achd.outfits': 'Tenha {n} visuais',
  'ach.rookie': 'Recruta',
  'ach.regular': 'Frequentador',
  'ach.veteran': 'Veterano',
  'ach.lifer': 'Carreira',
  'ach.eternal': 'Eterno',
  'ach.escape_artist': 'Mestre da fuga',
  'ach.ghost': 'Fantasma',
  'ach.smuggler': 'Contrabandista',
  'ach.phantom': 'Espectro',
  'ach.first_kill': 'Primeiro abate',
  'ach.hunter': 'Caçador',
  'ach.butcher': 'Açougueiro',
  'ach.reaper': 'Ceifador',
  'ach.apex': 'Predador',
  'ach.rampage': 'Massacre',
  'ach.one_man_army': 'Exército de um',
  'ach.double_tap': 'Toque duplo',
  'ach.triple_threat': 'Ameaça tripla',
  'ach.godlike': 'Divino',
  'ach.full_arsenal': 'Arsenal completo',
  'ach.arsenal_master': 'Mestre do arsenal',
  'ach.first_blood': 'Primeiro sangue',
  'ach.opener': 'O abridor',
  'ach.night_shift': 'Turno da noite',
  'ach.insomniac': 'Insone',
  'ach.double_up': 'Dobrou',
  'ach.big_bag': 'Bolsa cheia',
  'ach.gold_rush': 'Corrida do ouro',
  'ach.last_one_out': 'O último a sair',
  'ach.pacifist': 'Pacifista',
  'ach.seasoned': 'Calejado',
  'ach.officer': 'Oficial',
  'ach.commander': 'Comandante',
  'ach.legend': 'Lenda',
  'ach.collector': 'Colecionador',
  'ach.curator': 'Curador',
  'ach.hoarder': 'Acumulador',
};
