export default {
  'lobby.tagline': 'Aposte. Saqueie. Saia antes da tempestade. <b>Ninguém vê o que tem na sua bolsa.</b>',
  'lobby.namePh': 'Nome do seu corredor',
  'lobby.locker': 'Armário · skins · bolsas',
  'lobby.refill': 'Recarregar moedas de teste',
  'lobby.online': 'Online',
  'lobby.practice': 'Treino contra bots',
  'lobby.stakePer': 'Aposta por incursão',
  'lobby.stakeWith': 'Aposte com <span class="fine">qualquer moeda · mostrado em $ · os ganhos voltam na mesma moeda</span>',
  'lobby.play': 'Jogar · aposta {s}',
  'lobby.signIn': 'Entre para jogar',
  'lobby.how': 'Como jogar',
  'lobby.gore': '<b>Modo 18+.</b> Membros voam e o sangue fica no chão.',
  'lobby.fine': 'O treino roda no seu navegador. Todo o dinheiro aqui é de brincadeira.',
  'how.1': '<b>Aposte e fique pronto.</b> Todos entram juntos com uma faca e 100 de vida. Metade da aposta vai na sua bolsa, a outra metade vira saque espalhado.',
  'how.2': '<b>Pegue o saque laranja.</b> Ele vai para a sua bolsa. Abates melhoram sua arma: faca → pistola → escopeta → submetralhadora → fuzil → sniper a laser.',
  'how.3': "<b>Saia vivo.</b> Só há uma saída, no centro do mapa. Segure nela 10 segundos: todos ficam sabendo que você está saindo e qualquer acerto reinicia a contagem. Conseguiu, a bolsa toda é sua. Morreu, ela cai para outro.",
  'how.keys': "<kbd>WASD</kbd> mover · <kbd>mouse</kbd> mirar · <kbd>clique</kbd> atacar · <kbd>Espaço</kbd> esquiva · <kbd>Q</kbd> disfarçar o tamanho da bolsa · <kbd>M</kbd> som · <kbd>N</kbd> música",
  'how.fine': 'Cada incursão e cada conquista dão XP de patente. Cada promoção empresta uma skin nova por 3 dias.',
  'net.practice': 'Só você e os bots, offline.',
  'net.open': 'Conectado. Online, só jogadores reais.',
  'reg.title': "Servidor",
  'reg.auto': "Mais próximo",
  'reg.eu': "Europa",
  'reg.us': "Américas",
  'reg.asia': "Ásia",
  'nav.starknet': "Starknet",
  'nav.s.starknet': "Privacidade · números ao vivo",
  'sk.kicker': "Feito na Starknet",
  'sk.title': "Privado por padrão",
  'sk.lede': "Seu dinheiro só você vê. Depósitos e saques passam pelo pool protegido STRK20 da Starknet com provas de conhecimento zero, as apostas ficam privadas, os swaps nunca tocam a rede e o Bitcoin joga como qualquer moeda.",
  'sk.dep.t': "Depósito privado",
  'sk.dep.b': "Do seu saldo protegido para o jogo pelo pool STRK20. Uma prova de conhecimento zero verifica: ninguém na rede vê quem pagou nem quanto.",
  'sk.dep.a': "Depositar em privado",
  'sk.stake.t': "Apostas privadas",
  'sk.stake.b': "Escolha qualquer aposta dentro da faixa da mesa. Só você sabe: a mesa mostra apenas o pote total. Os prêmios são divididos de forma justa, como os side pots do pôquer.",
  'sk.stake.a': "Jogar",
  'sk.swap.t': "Swap privado",
  'sk.swap.b': "Troque moedas dentro do seu saldo de jogo pelo preço ao vivo. Nunca toca a rede, então nenhum explorador mostra.",
  'sk.swap.a': "Trocar",
  'sk.wd.t': "Saque privado",
  'sk.wd.b': "Os ganhos voltam para seu saldo protegido pela STRK20: ninguém na rede vê que o pagamento era seu.",
  'sk.wd.a': "Sacar em privado",
  'sk.ready': "Pronto",
  'sk.needWallet': "Precisa de Ready ou Xverse",
  'sk.signIn': "Entre com uma carteira Starknet",
  'sk.always': "Sempre ativo",
  'sk.btc.t': "Bitcoin na Starknet",
  'sk.btc.b': "Aposte BTC (WBTC e outro Bitcoin na Starknet) como qualquer moeda: os ganhos voltam em Bitcoin pelo preço ao vivo.",
  'sk.btc.a': "Jogar com BTC",
  'sk.btc.picked': "Sua moeda de aposta agora é Bitcoin.",
  'sk.live': "Ao vivo na Starknet",
  'sk.test': "rede de teste",
  'sk.s.players': "Jogadores",
  'sk.s.d7': "Ativos nesta semana",
  'sk.s.matches': "Partidas jogadas",
  'sk.s.staked': "Apostado em partidas",
  'sk.s.privStakes': "Apostas privadas",
  'sk.s.privTx': "Transferências privadas (STRK20)",
  'sk.s.deposits': "Depositado na rede",
  'sk.s.tvl': "Guardado no jogo",
  'sk.loading': "Carregando os números…",
  'sk.note': "Só totais: aqui não aparece nenhum jogador nem o valor de ninguém.",
  'cx.none': "Nada ainda.",
  'cx.loading': "Carregando carteiras…",
  'cx.cartridgeGo': "Continue na janela do Cartridge…",
  'cx.waitWallet': "Aguardando a carteira…",
  'cx.signMsg': "Assine a mensagem de login na carteira (não custa nada).",
  'cx.noAnswer': "O servidor não respondeu.",
  'cx.noSig': "A carteira não devolveu assinatura. Tente de novo.",
  'cx.checkingSig': "Assinado. Verificando a assinatura na Starknet…",
  'cx.notConfirmed': "O servidor não confirmou o login a tempo. Tente de novo.",
  'cx.typeEmail': "Digite seu email primeiro.",
  'cx.sendingCode': "Enviando um código…",
  'cx.codeSent': "Código enviado para {e}.",
  'cx.checkingCode': "Verificando o código…",
  'cx.privyAgain': "Entre com o Privy novamente.",
  'cx.signAgain': "Entre novamente para escolher sua carteira.",
  'cx.otherAcct': "{w} está na conta {a}, mas você entrou como {b}. Troque a conta na carteira ou entre como {a}.",
  'cx.signInAs': "Entrar como {a}",
  'cx.inWalletChecking': "Na sua carteira: verificando…",
  'cx.inWallet': "Na sua carteira: {v}",
  'cx.keepStrk': " (deixe ~1 STRK para as taxas da rede)",
  'cx.transfer': "Transferência pública",
  'cx.transferDep': "qualquer carteira: uma transferência simples de tokens, visível na rede",
  'cx.transferWd': "uma transferência simples para seu endereço, visível na rede",
  'cx.private': "🔒 Privado · Starknet STRK20",
  'cx.privateDep': "Ready ou Xverse: do seu saldo protegido com prova de conhecimento zero. Ninguém na rede vê quem pagou nem quanto",
  'cx.privateWd': "para seu saldo protegido: ninguém na rede vê que o pagamento era seu. Seu endereço precisa estar registrado no pool STRK20",
  'cx.typeAmount': "Digite um valor.",
  'cx.walletOnly': "Sua carteira só tem {v}.",
  'cx.faucet': " STRK de teste grátis em starknet-faucet.vercel.app.",
  'cx.leaveStrk': "Deixe cerca de 1 STRK na carteira para a taxa (use Max).",
  'cx.confirmDep': "Confirme o depósito na carteira…",
  'cx.holdsOnly': "{w} ({a}) tem {v}. Envie {s} para este endereço primeiro.",
  'cx.noPrivate': "Este login não faz transferências privadas. Use uma transferência pública.",
  'cx.sentWait': "Enviado ({tx}). Aguardando a Starknet…",
  'cx.youHave': "Você tem {v}.",
  'cx.depBad': "Depósito (token não aceito, fale com o suporte)",
  'cx.depHeld': "Depósito retido (acima do limite beta, sendo devolvido)",
  'cx.dep': "Depósito",
  'cx.cashout': "Saque · {s}",
  'cx.signedAs': "Você entrou como {a}.",
  'cx.checkingChain': "O caixa está verificando a rede…",
  'cx.notCredited': "Recebido mas não creditado porque {r}. Está seguro e será devolvido a você.",
  'cx.credited': "Creditado {v}.",
  'cx.creditedToast': "Depósito creditado: {v}.",
  'cx.txFailed': "A transação falhou na rede. Nada foi debitado.",
  'cx.sentPrivate': "Enviado em privado. A nota protegida chega em um ou dois minutos; seu saldo atualiza sozinho.",
  'cx.sentPublic': "Aguardando a Starknet aceitar. Seu saldo atualiza sozinho.",
  'cx.paying': "Pagando…",
  'cx.paid': "Pago. Transação {tx}.",
  'cx.paidToast': "Saque enviado.",
  'cx.payFailed': "O pagamento não pôde ser enviado. Seu saldo voltou.",
  'cx.payHeld': "O pagamento está retido para verificação manual. Seus fundos estão seguros; está no seu histórico.",
  'cx.wrong': "Algo deu errado.",
  'cx.cancelled': "Cancelado na carteira.",
  'cx.cantSend': "Sua carteira não conseguiu enviar: normalmente falta desse token ou STRK para a taxa. Tente um valor menor (Max deixa espaço para a taxa).",
  'cx.notDeployed': "Sua conta ainda não está implantada nesta rede. Faça qualquer transação na carteira (por exemplo, envie um pouco de STRK para você) e tente de novo.",
  'cx.minWd': "Mínimo ${m}. Pago para {a}.",
  'cx.wdOff': "Os saques estão desativados neste servidor agora.",
  'cx.hintPrivate': "Sua carteira gera uma prova de conhecimento zero na Starknet; pode levar um minuto.",
  'cx.hintPublic': "Seu saldo atualiza quando a Starknet aceita a transferência.",
  'cx.connectT': "Entre para jogar com tokens",
  'cx.swallet': "Carteira Starknet",
  'cx.looking': "Procurando carteiras…",
  'cx.privNote': "Qualquer carteira Starknet serve. Ready e Xverse também podem depositar e sacar em privado pelo pool STRK20: ninguém na rede vê quem você é nem quanto.",
  'cx.noWallet': "Sem carteira · Cartridge",
  'cx.cartSub': "passkey ou redes sociais, sem gas",
  'cx.privyT': "Email ou redes · Privy",
  'cx.sendCode': "Enviar código",
  'cx.codePh': "Código do email",
  'cx.signIn': "Entrar",
  'cx.cashier': "Caixa",
  'cx.tDeposit': "Depositar",
  'cx.tCash': "Sacar",
  'cx.tHistory': "Histórico",
  'cx.amount': "Valor",
  'cx.testFaucet': "Testnet: STRK grátis para seu endereço em starknet-faucet.vercel.app, depois deposite aqui.",
  'stake.private': "🔒 Sua aposta é privada: a mesa mostra só o pote total, nunca quem apostou quanto.",
  'prep.mine': "🔒 Sua aposta: {v} · só você vê",
  'res.refund': "{v} da sua aposta voltaram: nenhum vencedor apostou tanto.",
  'medal.long': "Tiro longo",
  'medal.knife': "Morte na faca",
  'ex.centre': "SAÍDA · SEGURE {s} S",
  'feed.extracting': "{name} está segurando a saída",
  'hud.holdExit': "Segure a saída {s} s · todos sabem · um acerto reinicia a contagem",
  'cs.signedOut': "Tokens reais na Starknet {n}. Entre para jogar.",
  'cs.manage': "Depositar · sacar",
  'cs.fine': "Tokens reais na Starknet {n}. A casa guarda os depósitos até você sacar; saques vão só para o endereço com que você entrou.",
  'cs.beta': "Beta: até {v} por jogador.",
  'wel.name.t': "Escolha o nome do seu runner",
  'wel.name.b': "Oi, eu sou a Nyx, sua coordenadora! Antes de saltar, me diga como te chamar. Todos na partida veem esse nome sobre sua cabeça, no placar e no chat.",
  'wel.name.ph': "O nome do seu runner",
  'wel.name.rules': "De 3 a 16 letras ou números. Dá para mudar depois na página Jogar.",
  'wel.name.dice': "Um nome aleatório",
  'wel.next': "Próximo",
  'wel.back': "Voltar",
  'wel.go': "Bora",
  'wel.region.t': "Escolha sua região",
  'wel.region.b': "As partidas rodam num servidor perto de você. Quanto menor o ping (ms), mais fluido o jogo. Já testei todos: o verde é o mais rápido.",
  'wel.region.best': "O melhor para você",
  'wel.region.off': "não responde",
  'wel.region.players': "{n} online",
  'wel.region.auto': "Auto",
  'wel.region.autoD': "sempre o mais rápido para você",
  'wel.region.note': "Você pode mudar a região a qualquer momento na página Jogar.",
  'tut.hello.t': "Bem-vindo ao DARK BAGS!",
  'tut.hello': "Eu sou a Nyx. Em poucos minutos vou te mostrar **cada parte do jogo**, para nada te confundir, e depois vamos jogar **sua primeira partida juntos**.\nA ideia é simples: você entra na partida com uma **bolsa** de dinheiro (sua aposta), pega saque, enfrenta outros runners e **sai vivo** para ficar com o que carrega.\nUse **Próximo** (ou a tecla →) para avançar e **Voltar** para reler.",
  'tut.menu.t': "O menu",
  'tut.menu': "Tudo fica aqui, em quatro grupos:\n**Jogar**: partidas, Ranqueada e o Passe de batalha. **Loja**: a loja, seu inventário e a troca de moedas. **Social**: chat, amigos, guildas, correio e convites. **Você**: tarefas e ajustes.\nA linha sob cada nome mostra o que te espera (tarefas, caixas, o timer da loja). Número vermelho é novidade. Seu cartão embaixo mostra seu rank e nível VIP.",
  'tut.profile.t': "Seu runner",
  'tut.profile': "Este é você. Toque no runner para abrir o **Armário**: roupas, skins de armas e estilo.\nSob seu nome: seu **rank** (1 a 90). Cada partida dá XP: abates, sobreviver, sair, vencer. Conquistas liberam **títulos** para usar.\n**Online** é contra pessoas reais com apostas reais. **Treino** é contra bots com dinheiro de jogo: grátis e perfeito para aprender.",
  'tut.goals.t': "Metas de hoje",
  'tut.goals': "Sua lista do dia: o **presente do calendário**, as **tarefas diárias**, a **primeira vitória do dia** (+300 XP), seu **nível do passe** e os **giros grátis**.\nUm cartão brilhando quer dizer prêmio esperando: toque e ele te leva lá. Volte todo dia: o calendário cresce por 30 dias seguidos.",
  'tut.modes.t': "Modos de jogo",
  'tut.modes': "17 modos em 5 grupos: **Clássicos**, **Armas**, **Equipes**, **Eventos** (Ranqueada, Zumbis, Corrida do ouro) ou **Todos**.\nCada cartão mostra quantos jogam, quanto dura a partida, quem está **agora** e quem **espera**. 🔥 marca o mais movimentado. Toque num cartão para escolher.",
  'tut.modeInfo.t': "O modo escolhido",
  'tut.modeInfo': "Tudo sobre o modo escolhido: **como vencer**, uma **dica** minha e **o que paga**, além de jogadores, duração e quem está nele agora.\nNa dúvida, leia este quadro primeiro. Para a primeira partida, **Raid** é o melhor.",
  'tut.stake.t': "Sua aposta",
  'tut.stake': "Quanto você leva para a partida: **$0.10, $1, $10, $100** ou **seu próprio valor** ($0.10 a $10.000).\nNum **Raid**, metade da aposta vai na sua bolsa e metade fica espalhada no mapa como saque. Saia vivo e fica com tudo da bolsa. Nos **modos de pote**, as apostas de todos formam um prêmio: o vencedor leva.\nA casa fica com 5%. Comece pequeno: $0.10 ou $1.\n🔒 Sua aposta é **privada**: a mesa mostra só o pote total. Com apostas diferentes o pote é dividido de forma justa: o vencedor leva de cada jogador no máximo o que ele mesmo apostou.",
  'tut.coins.t': "Aposte com qualquer moeda",
  'tut.coins': "Pague com qualquer moeda que tiver: USDC, USDT, STRK, ETH, BTC e mais. Os valores aparecem em dólares, então você sempre sabe o que arrisca.\nSeus ganhos voltam **na mesma moeda, ao preço de entrada**: variações durante a partida não mudam nada.",
  'tut.wallet.t': "Sua carteira e o $ da loja",
  'tut.wallet': "No topo: **Wallet** são suas moedas reais (deposite e saque quando quiser). **Shop $** é crédito da loja para caixas e ofertas: não pode ser sacado.\nPara jogar online com apostas reais, entre com uma carteira ou só um email. Saques vão apenas para **o seu próprio endereço**. O treino não precisa de nada.",
  'tut.shop.t': "A loja: ofertas",
  'tut.shop': "No topo da loja:\n**Pacote inicial** (uma vez): uma roupa Épica, 3 caixas, 5 giros e uma moldura por $1.99. **Loja do dia**: seis skins por dia, compra direta, sem sorteio. **Cartão Insider**: 30 dias de $ da loja e giros diários, +25% de XP do passe. **VIP**: quanto mais você pagou, maior o bônus de recarga e os giros diários.\nToda compra pede um segundo toque, então nada é comprado sem querer.",
  'tut.cases.t': "Caixas",
  'tut.cases': "**Bolsas** dão roupas, **caixas** dão skins de armas, **caixas de estilo** dão molduras, banners, efeitos de abate e cores de nome. Quanto mais cara, melhores as chances.\nCada caixa mostra as **chances exatas**, sorteadas no servidor. **Garantias**: um Épico ou melhor em 15 aberturas, um Lendário em 60. Cada 10ª caixa é grátis. Duplicata devolve $ da loja. Compre e abra até 100 de uma vez.",
  'tut.wheel.t': "A roda da fortuna",
  'tut.wheel': "$0.05 por giro, ou grátis com giros de tarefas, calendário, correio e VIP. **18 prêmios**: skins de 1 hora, skins reais, estilo, caixas presente, $ da loja, XP do passe, boosts de XP e giros extras.\nCada giro pago enche o **banco da fortuna**: o giro que atinge a marca leva o banco inteiro **em moedas reais**. **Girar tudo** usa todos os giros grátis de uma vez.",
  'tut.inventory.t': "Inventário",
  'tut.inventory': "Tudo o que você tem: moedas da carteira, $ da loja, **caixas fechadas** (toque **Abrir tudo** para abrir de uma vez), **giros grátis**, seu **estilo** (moldura, banner, efeito de abate, cor do nome: equipe aqui), sua coleção e estatísticas.",
  'tut.swap.t': "Troca",
  'tut.swap': "Troque uma moeda por outra dentro do jogo, com uma pequena taxa. Útil para apostar ou sacar em outra moeda.",
  'tut.pass.t': "Passe de batalha",
  'tut.pass': "Uma temporada nova todo mês com **50 níveis**. Cada partida enche de XP. A **trilha grátis** premia todos; a **premium** ($9.99) adiciona um prêmio em cada nível: armaduras, skins de armas e torretas, estilo Mítico.\nCom pressa? Compre níveis direto. Pegue os prêmios na página do passe.",
  'tut.ranked.t': "Ranqueada",
  'tut.ranked': "Battle royale com aposta que também move seu **rating da temporada**. Posição e abates decidem até onde você sobe: Bronze, Prata, Ouro, Platina, Diamante, Mestre, **Lenda Neon**.\nCada nova divisão paga **prêmios** uma vez por temporada (estilo Lendário, Mítico e até Exótico), e após a partida pode sair uma loteria de caixas.",
  'tut.tasks.t': "Tarefas",
  'tut.tasks': "O **calendário de 30 dias**: um presente a cada dia que você volta (perdeu um dia, recomeça), os maiores nos dias 7, 14, 21 e 30. **3 tarefas diárias** e **semanais** dão caixas, giros, $ da loja e boosts de XP.\n**Conquistas**: 96 metas; cada uma dá XP, um prêmio e um **título** para usar.",
  'tut.social.t': "Amigos, guildas, chat",
  'tut.social': "Adicione **amigos**, veja quem está online, mande mensagens e convide para sua mesa. Entre ou funde uma **guilda** com chat próprio. O **chat** fala com todos.\nNa partida: **Tab** mostra o placar, **K** liga e desliga o microfone do **chat de voz** (em equipes você fala com sua equipe).",
  'tut.mail.t': "Correio e convites",
  'tut.mail': "**Correio**: cartas do jogo com presentes (abra uma caixa ou gire a roda direto da carta).\n**Convidar**: compartilhe seu link. Amigos ganham uma bolsa de boas-vindas e você ganha $ da loja sempre que eles jogam.",
  'tut.settings.t': "Ajustes",
  'tut.settings': "Som, música, gráficos e efeitos, controles, idioma e chat de voz. Quer este tour de novo? Está aqui: **Ajustes → Tour**.",
  'tut.match.t': "Sua primeira partida!",
  'tut.match': "Esse é o jogo todo. Agora a parte divertida: vamos jogar **sua primeira partida juntos**. É treino grátis contra bots, nada a perder. Eu te digo o que fazer em cada passo.",
  'tut.practice.t': "Toque em Treino",
  'tut.practice': "Toque em **Treino** (destacado). Bots e dinheiro de jogo: grátis e perfeito para aprender.",
  'tut.raidPick.t': "Toque em Raid",
  'tut.raidPick': "Toque no cartão **Raid**: saque, luta e saída. O clássico.",
  'tut.bag.t': "Sua bolsa",
  'tut.bag': "Jogamos por **$1 de dinheiro de treino**. Ele vai na sua **bolsa**. Pegue loot para deixá-la mais pesada. Derrube um corredor e a bolsa dele cai para você. Caiu, a sua cai para ele.\nPara ficar com ela, chegue à **saída no centro do mapa** e segure nela por **10 segundos**. Todos são avisados de que você está saindo, e um acerto reinicia a contagem.",
  'tut.play.t': "Toque em Jogar",
  'tut.play': "Toque em **Jogar**. Você vai para a sala de espera.",
  'tut.ready.t': "Aperte Pronto",
  'tut.ready': "Aperte **Pronto** e a gente salta!\nControles: **WASD** mover, **mouse** mirar, **clique** atirar, **Espaço** avançar, **Q** finge o tamanho da bolsa, **Tab** placar. No celular: o polegar esquerdo move; segure **Fogo** à direita e ele mira sozinho.",
  'tut.resultWon.t': "Você saiu!",
  'tut.resultWon': "Você venceu seu primeiro raid! Eu sabia que você conseguiria. Dinheiro de treino é só para aprender. Toque em **Mesas** para voltar ao menu.",
  'tut.retry.t': "Tente de novo",
  'tut.retry': "Você caiu: acontece, o treino é grátis! Toque em **Jogar de novo**. Desta vez pegue um pouco de loot e vá para a **saída no centro** e segure 10 segundos.",
  'tut.bye.t': "Pronto, runner!",
  'tut.bye': "Agora você conhece o jogo todo. Dicas: comece com apostas pequenas, faça as **tarefas diárias**, pegue o **calendário** todo dia e jogue com **amigos**.\nSe precisar de mim, **Ajustes → Tour**. Boa sorte lá fora!",
  'nav.g.play': "Jogar",
  'nav.g.store': "Loja",
  'nav.g.social': "Social",
  'nav.g.you': "Você",
  'nav.s.ranked': "Suba de divisão",
  'nav.s.pass': "Prêmios da temporada",
  'nav.s.shop': "Caixas, ofertas, a roda",
  'nav.s.inventory': "Skins, caixas, estilo",
  'nav.s.swap': "Troque moedas",
  'nav.s.chat': "Fale com todos",
  'nav.s.friends': "Joguem juntos",
  'nav.s.guilds': "Clãs e chat",
  'nav.s.mail': "Cartas e presentes",
  'nav.s.invite': "Ganhe com amigos",
  'nav.s.achievements': "Calendário, tarefas, conquistas",
  'nav.s.settings': "Som, controles, idioma",
  'nav.d.pass': "Nível {n} de 50",
  'nav.d.store': "Nova loja em {t}",
  'nav.d.inv': "{b} caixas · {s} giros",
  'nav.d.mail': "{n} não lidas",
  'nav.d.tasks': "{n} para pegar",
  'mcat.all': "Todos",
  'mcat.classic': "Clássicos",
  'mcat.weapons': "Armas",
  'mcat.teams': "Equipes",
  'mcat.events': "Eventos",
  'mc.hot': "Em alta",
  'mc.season': "Temporada",
  'mi.waves': "Ondas",
  'mi.rounds': "{n} rodadas × {s}",
  'mi.win': "Como vencer:",
  'mi.tip': "Dica:",
  'mi.pays': "Dá:",
  'mi.rew': "XP por abate e final; conta para tarefas diárias e o passe.",
  'mi.players': "Jogadores",
  'mi.time': "Partida",
  'mi.now': "Agora",
  'mi.win.raid': "Chegue à saída no centro do mapa e segure 10 segundos (todos são avisados, um acerto reinicia a contagem): tudo na bolsa é seu.",
  'mi.win.br': "Seja o último de pé: o pote é seu.",
  'mi.win.duel': "Vença o rival em 90 segundos: leva as duas apostas.",
  'mi.win.dm': "Mais abates ao fim leva o pote. Você renasce.",
  'mi.win.gl': "Mais abates no fim vence. Abates dão créditos para kits, torretas e minas laser.",
  'mi.win.hardcore': "O último de pé leva o pote. Um tiro derruba.",
  'mi.win.weapon': "O último de pé leva o pote, com uma arma só para todos.",
  'mi.win.team': "Vença 2 de 3 rodadas em equipe: a equipe divide o pote.",
  'mi.win.ranked': "Termine alto e abata: seu rating sobe por divisões com prêmios.",
  'mi.win.zombies': "Sobreviva às ondas com até 3 amigos. Cada onda dá XP.",
  'mi.win.gold': "Pegue mais bolsas de ouro até o fim: o vencedor ganha $ da loja.",
  'mi.tip.raid': "Saqueie primeiro, lute depois.",
  'mi.tip.br': "Fique na zona segura e deixe os outros brigarem.",
  'mi.tip.duel': "Avance (Espaço) entre os tiros e não pare.",
  'mi.tip.dm': "Continue abatendo: cada abate melhora a arma.",
  'mi.tip.gl': "Gaste créditos cedo: uma torreta no corredor vence por você.",
  'mi.tip.hardcore': "Vá de cobertura em cobertura: um tiro derruba.",
  'mi.tip.weapon': "Aprenda o alcance da arma e lute onde ela é forte.",
  'mi.tip.team': "Fique com a equipe: duas armas contra um vencem.",
  'mi.tip.ranked': "Sobreviva primeiro: a posição vale tanto quanto os abates.",
  'mi.tip.zombies': "Costas com costas e guarde kits para as ondas grandes.",
  'mi.tip.gold': "Pegue as bolsas perto e não lute carregado.",
  'goal.title': "Hoje",
  'goal.cal': "Presente do dia {d} pronto",
  'goal.claim': "Toque para pegar",
  'goal.tasks': "Tarefas {a}/{b}",
  'goal.tasksS': "tarefas diárias",
  'goal.first': "Primeira vitória hoje",
  'goal.firstS': "+300 XP esperando",
  'goal.pass': "Nível do passe {n}",
  'goal.passP': "passe premium",
  'goal.passF': "trilha grátis: vire premium",
  'goal.card': "Insider: presente de hoje",
  'goal.vip': "VIP {n}: giros diários",
  'goal.spins': "{n} giros grátis",
  'goal.spinsS': "gire a roda",
  'vip.toNext': "Faltam {v} para VIP {n}",
  'vip.max': "VIP máximo",
  'vip.how': "O VIP cresce com dinheiro real pago (recargas e pagamentos USDC/USDT), nunca com $ grátis da loja.",
  'vip.claim': "Pegar {n} giros",
  'vip.perks': "Todos os níveis",
  'vip.paid': "Pago",
  'vip.bonus': "Bônus de recarga",
  'vip.daily': "Todo dia",
  'vip.frame': "Moldura",
  'vip.note': "Vantagens VIP são conforto e status: nunca mais poder na partida.",
  'vip.got': "+{n} giros",
  'fw.all': "Girar tudo ×{n}",
  'fw.allGot': "{n} giros: tudo o que ganhou",
  'inv.openAll': "Abrir tudo ({n})",
  'inv.openN': "Abrir ×{n}",
  'bp.buyTier': "+{n} nível · {v}",
  'bp.tiersGot': "+{n} níveis: agora nível {t}",
  'of.confirm': "Toque de novo: {v}",
  'of.once': "Só uma vez",
  'of.starter': "Pacote inicial",
  'of.st.outfit': "Uma roupa Épica para sempre",
  'of.st.boxes': "2 bolsas Vault + uma caixa Armory (chances completas)",
  'of.st.spins': "{n} giros da roda",
  'of.buy': "Comprar · {v}",
  'of.k.outfit': "Roupa",
  'of.k.wskin': "Arma",
  'of.k.style': "Estilo",
  'of.owned': "Seu",
  'of.card': "Cartão Insider",
  'of.cardOn': "Insider · faltam {n} dias",
  'of.cardDaily': "Todo dia: {v} da loja + {n} giro",
  'of.claimed': "Pego hoje",
  'of.claim': "Pegar o de hoje",
  'of.extend': "+30 dias · {v}",
  'of.cardTitle': "Cartão Insider · {d} dias",
  'of.c.now': "{v} da loja na hora",
  'of.c.pass': "+{n}% de XP do passe",
  'of.c.frame': "A moldura {n}, só com o cartão",
  'of.c.value': "Vale {v} da loja e {s} giros no mês se pegar todo dia.",
  'of.kicker': "Compra direta, sem roleta",
  'of.store': "Loja do dia",
  'of.newIn': "Novo conjunto em",
  'of.storeNote': "Seis skins por dia, iguais para todos. Nunca edições limitadas nem Exóticas.",
  'of.got': "Seu: {x}",
  'of.cardGot': "Cartão Insider ativo: {n} dias",
  'of.claimGot': "+{v} da loja e {n} giro",
  'of.starterGot': "O pacote inicial é seu: abra as bolsas no inventário",
  'fw.k.credit': "{v} da loja",
  'fw.k.pass': "+{v} XP do passe",
  'fw.k.boost': "×2 XP por {n} partida",
  'fw.k.spin': "+1 giro grátis",
  'fw.k.box': "Presente: {name}",
  'fw.k.style': "Item de estilo {r}",
  'fw.free': "Giro grátis ×{n}",
  'fw.freeNote': "Giros grátis de tarefas, do calendário e do correio giram esta roda. Toque na roda para girar.",
  'fw.again': "Girar de novo",
  'fw.styleNote': "Um item de estilo para sempre: equipe em Inventário → Estilo.",
  'fw.passNote': "Conta para o nível do passe.",
  'fw.boostNote': "Sua próxima partida dá XP em dobro.",
  'fw.spinNote': "Mais um giro, por conta da casa.",
  'fw.boxNote': "Uma caixa presente no inventário: vai até Épico.",
  'dl.openBox': "Abrir {name}",
  'dl.spinNow': "Girar a roda",
  'inv.spins': "Giros grátis",
  'vc.toggle': "Microfone liga/desliga (K)",
  'vc.peers': "voz: {n}",
  'vc.micOn': "Microfone ligado: te ouvem. K para silenciar.",
  'vc.noMic': "Sem microfone: permita no navegador para falar.",
  'set.vchat': "Chat de voz",
  'set.vchatNote': "Ouça os jogadores da sua partida (em equipes: seu time). K liga e desliga seu microfone.",
  'sb.open': "Placar (Tab)",
  'sb.title': "Placar",
  'sb.hint': "segure Tab",
  'sb.player': "Jogador",
  'sb.k': "A",
  'sb.d': "M",
  'sb.ping': "Ping",
  'sb.bot': "bot",
  'sb.zk': "Zumbis",
  'sb.gb': "Ouro",
  'sb.yours': "Seu time",
  'sb.theirs': "Adversários",
  'rd.divPrize': "Prêmio de divisão",
  'rd.divPrizes': "Prêmios de divisão",
  'rd.divPrizesNote': "Alcance uma divisão e ganhe o prêmio, uma vez por temporada. Estilo Lendário e Mítico se ganha aqui e no passe.",
  'rd.styleOf': "Estilo {r}",
  'inv.giftCap': "{n} presente: até Épico",
  'shop.style': "Estilo",
  'shop.styleNote': "Molduras, banners, efeitos de abate e cores de nome animados. Duplicatas devolvem $ da loja.",
  'sty.title': "Estilo",
  'sty.frame': "Molduras",
  'sty.banner': "Banners",
  'sty.killfx': "Efeitos de abate",
  'sty.namefx': "Nomes",
  'sty.none': "Nenhum",
  'sty.worn': "equipado",
  'sty.empty': "Nada ainda: {n} para achar em caixas de estilo, no calendário diário e nas tarefas.",
  'sty.get': "Obter estilo",
  'box.s-street': "Caixa de estilo urbano",
  'box.s-neon': "Caixa de estilo neon",
  'box.s-icon': "Caixa de estilo ícone",
  'ach.listTitle': "Conquistas",
  'dl.g.credit': "{v} na loja",
  'dl.g.spin': "{n}× giro da roleta",
  'dl.g.pass': "+{n} XP de passe",
  'dl.g.xp': "+{n} XP",
  'dl.g.boost': "×2 XP por {n} partidas",
  'dl.days': "{d}d {h}h",
  'dl.t.raids': "Jogue {n} partidas",
  'dl.t.kills': "Faça {n} abates",
  'dl.t.secs': "Passe {n} min em partidas",
  'dl.t.firstBloods': "Primeiro sangue {n}×",
  'dl.t.extracts': "Extraia {n}×",
  'dl.t.pvpKills': "Abata {n} jogadores",
  'dl.t.headshots': "Acerte {n} tiros na cabeça",
  'dl.t.zKills': "Mate {n} zumbis",
  'dl.t.goldBags': "Pegue {n} sacos de ouro",
  'dl.t.wins': "Vença {n}×",
  'dl.t.kKnife': "Faça {n} abates com faca",
  'dl.t.kSniper': "Faça {n} abates com sniper",
  'dl.t.rankedGames': "Jogue {n} partidas ranqueadas",
  'dl.t.zClears': "Conclua {n} corridas zumbi",
  'dl.calendar': "Recompensas diárias · 30 dias",
  'dl.dayOf': "Dia {d} de 30",
  'dl.lost': "A sequência quebrou: de volta ao dia 1.",
  'dl.calNote': "Volte todo dia seguido: os presentes crescem, a cada 7 dias um grande.",
  'dl.best': "melhor sequência {n}",
  'dl.next': "Próximo presente em {t}",
  'dl.claim': "Resgatar",
  'dl.done': "Feito",
  'dl.today': "Tarefas de hoje",
  'dl.resets': "novas em {t}",
  'dl.sweep': "As três hoje:",
  'dl.sweepGot': "As três feitas! Bônus:",
  'dl.week': "Esta semana",
  'dl.boostLeft': "faltam {n} partidas",
  'dl.boostNone': "sem bônus ainda: ganhe com tarefas e o calendário",
  'dl.fwDone': "Primeira vitória do dia: obtida",
  'dl.fwReady': "Primeira vitória do dia: +300 XP esperando",
  'dl.todayDone': "tarefas feitas hoje",
  'dl.offline': "Recompensas e tarefas diárias só online.",
  'dl.signIn': "Entre para receber recompensas e tarefas diárias.",
  'dl.dayGot': "Dia {d}: resgatado!",
  'dl.achGot': "Recompensa de conquista",
  'dl.taskGot': "Tarefa feita!",
  'dl.reward': "Recompensa",
  'dl.nice': "Boa!",
  'dl.streak': "{n} dias seguidos",
  'dl.seeAll': "Ver tarefas",
  'dl.taskDone': "{n} tarefa(s) feita(s): resgate a recompensa em Tarefas",
  'ach.habit': "Hábito",
  'ach.devoted': "Dedicado",
  'ach.loyal': "Leal",
  'ach.regular_face': "Frequentador",
  'ach.dutiful': "Cumpridor",
  'ach.workhorse': "Incansável",
  'ach.taskmaster': "Mestre das tarefas",
  'achd.streak': "Volte {n} dias seguidos",
  'achd.calDays': "Resgate {n} recompensas diárias",
  'achd.tasksDone': "Conclua {n} tarefas",
  'map.title': "Mapa",
  'map.any': "Qualquer",
  'map.hint': "O mais votado vence; empate por sorteio",
  'map.hintNone': "Vote no mapa: o mais votado vence",
  'map.now': "Mapa: {m}",
  'map.docks': "Docas noturnas",
  'map.chain': "Blockchain",
  'map.lego': "Cidade de blocos",
  'map.dunes': "Dunas vermelhas",
  'map.snow': "Congelamento",
  'map.lava': "Forja de lava",
  'map.city': "Centro",
  'map.neon': "Arcade neon",
  'map.blackout': "Apagão",
  'map.fantasy': "Fortaleza do dragão",
  'map.toon': "Cidade cartoon",
  'map.gravity': "Pista Gravity",
  'map.speedway': "Autódromo noturno",
  'map.skate': "Skatepark",
  'map.metro': "Metrô",
  'map.factory': "Fábrica",
  'map.jungle': "Templo da selva",
  'map.junkyard': "Ferro-velho",
  'map.moon': "Base lunar",
  'map.casino': "Cassino",
  'swap.rate': "Taxa",
  'swap.impactK': "Impacto no preço",
  'swap.minGet': "Mínimo que você recebe ({p}% de slippage)",
  'swap.highImpact': "Impacto alto: você receberá bem menos que o preço de mercado. Tente um valor menor.",
  'swap.pick': "Escolha uma moeda",
  'swap.youPay': "Você paga",
  'swap.youGet': "Você recebe",
  'swap.balance': "Saldo",
  'swap.inGame': "no jogo",
  'swap.listNote': "Moedas da lista verificada da AVNU e da lista da Ekubo.",
  'swap.empty': "Nada no seu saldo do jogo ainda.",
  'rd.tabAll': "Todos os jogadores",
  'rd.tabSeason': "Temporada ranqueada",
  'rd.kd': "K/D",
  'rd.deaths': "Mortes",
  'rd.myPvp': "Suas estatísticas PvP",
  'rd.noPvp': "Jogue uma partida PvP online para obter seu K/D.",
  'rd.emptyAll': 'Ainda não há partidas PvP online. Jogue uma e lidere a tabela.',
  'rd.kdNote': "K/D = abates ÷ mortes em partidas PvP online (zumbis não contam). 3 partidas para entrar no ranking de K/D.",
  'rd.sortBy': "Ordenar por",
  'rd.by.kd': "K/D",
  'rd.by.kills': "Abates",
  'rd.by.xp': "XP de patente",
  'reg.table': "Servidor: {r}",
  'reg.closer': "Mais perto de você: {r} ({ms} ms). Escolha-o no lobby e jogue com quem está lá.",
  'net.connecting': 'Conectando ao servidor…',
  'net.down': 'Servidor indisponível. Tentando de novo… O treino funciona offline.',
  'net.lost': 'Conexão perdida. De volta às mesas.',
  'q.pick': 'Escolha uma moeda para apostar.',
  'q.short': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda ou uma aposta menor.',
  'q.shortDeposit': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda, uma aposta menor ou deposite.',
  'q.stable': 'Você aposta {s} em {c}. Saia vivo e fique com tudo o que carrega.',
  'q.coin': 'Você aposta {a} = {s} ao preço de hoje. Os ganhos voltam em {c} na mesma taxa.',
  'tb.live': 'Incursão rolando · {t}',
  'tb.ready': '{n} prontos · {s}s',
  'tb.waiting': '{n} esperando',
  'tb.golden': 'Próxima: incursão dourada',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Ajustes do treino',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Fácil',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difícil',
  'pcfg.runners': 'Corredores na incursão',
  'pcfg.time': 'Duração da incursão',
  'rk.max': 'patente máxima',
  'rk.toNext': '{x} XP até a patente {r}',
  'rk.of': 'Patente {r} de 90',
  'rk.rank': 'Patente',
  'rk.up': 'Promoção',
  'rk.xp': 'XP de patente',
  'xp.Raid': 'Incursão',
  'xp.kills': '{n} abates',
  'xp.Damage': 'Dano',
  'xp.Time alive': 'Tempo vivo',
  'xp.First blood': 'Primeiro sangue',
  'xp.Double kill': 'Abate duplo',
  'xp.Triple kill': 'Abate triplo',
  'xp.Rampage': 'Massacre',
  'xp.Godlike': 'Divino',
  'xp.Full arsenal': 'Arsenal completo',
  'xp.Extracted': 'Extração',
  'xp.Profit': 'Lucro',
  'xp.Practice ×0.5': 'Treino ×0.5',
  'rk.newRank': "Nova patente",
  'rw.continue': "Continuar",
  'rw.title': 'Recompensa de promoção',
  'rw.trial': 'seu por 1 hora',
  'rw.try': 'Experimentar',
  'rw.share': 'Compartilhar promoção',
  'prep.raid': 'Incursão {n} · aposta {s}',
  'prep.readyUp': 'Pronto?',
  'prep.first': 'A contagem começa quando o primeiro corredor ficar pronto.',
  'prep.live': 'Há uma incursão rolando. Fique pronto e entre na próxima com todos.',
  'prep.over': 'Incursão encerrada. A sala abre em instantes.',
  'prep.many': 'Aqui todo mundo começa com faca. Bots entram nos últimos segundos.',
  'prep.bots': 'Bots preenchem as vagas nos últimos segundos.',
  'prep.open': 'livre',
  'prep.pot': 'Pote',
  'prep.cancel': 'Cancelar · reembolsar {v}',
  'prep.ready': 'Pronto · aposta {v}',
  'prep.back': 'Voltar às mesas',
  'hud.bagPrivate': 'Sua bolsa · privada',
  'hud.lag': 'O servidor não responde · reconectando…',
  'hud.golden': 'Incursão dourada',
  'hud.goldenStart': 'Incursão dourada · saque do jackpot lá dentro',
  'hud.start': "Faca na mão · pegue o laranja · a saída fica no centro",
  'hud.bagOpened': 'Bolsa aberta · +{v}',
  'hud.arsenal': "Arsenal completo · de volta à pistola ★",
  'hud.unlocked': '{w} desbloqueada',
  'hud.pnl': '{d} contra a aposta de {s}',
  'hud.alive': '{n} lá dentro',
  'hud.next': 'Próxima: {w}',
  'hud.final': 'Círculo final · última saída',
  'hud.closing': 'Tempestade fechando · {t}',
  'hud.stormIn': 'A tempestade avança em {t}',
  'hud.dash': 'Esquiva',
  'hud.bagLook': 'Aparência da bolsa',
  'hud.extracting': 'Extraindo',
  'hud.someoneOut': "⚠ {name} está saindo · {s} s para impedir!",
  'hud.holdStill': 'Fique parado. Um tiro zera o progresso.',
  'hud.sound': 'Som',
  'hud.music': 'Música',
  'bluff.0': 'pequena',
  'bluff.1': 'média',
  'bluff.2': 'gorda',
  'touch.move': 'mover',
  'touch.aim': 'mirar · atirar',
  'touch.bag': 'Bolsa',
  'w.Knife': 'Faca',
  'w.Pistol': 'Pistola',
  'w.Shotgun': 'Escopeta',
  'w.SMG': 'Submetralhadora',
  'w.Rifle': 'Fuzil',
  'w.Laser sniper': 'Sniper a laser',
  'w.Hand Cannon': "Canhão de mão",
  'w.Auto Shotgun': "Escopeta automática",
  'w.PDW': "PDW",
  'w.Carbine': "Carabina",
  'w.Scout': "Batedor",
  'w.Machine Gun': "Metralhadora",
  'w.Magnum Sniper': "Sniper Magnum",
  'hud.reloading': "Recarregando",
  'streak.1': 'Primeiro sangue',
  'streak.2': 'Abate duplo',
  'streak.3': 'Abate triplo',
  'streak.4': 'Massacre',
  'streak.5': 'Divino',
  'streak.you1': 'Você tirou o primeiro sangue',
  'feed.storm': 'A tempestade te pegou',
  'feed.droppedYou': '{name} te derrubou',
  'coach.storm': 'Você está na tempestade · volte para o círculo',
  'coach.touch': "Polegar esquerdo move · segure Atirar: mira sozinho no inimigo mais próximo",
  'coach.keys': 'WASD para mover · mouse para mirar · clique para atacar',
  'coach.exit': "Hora de sair · a SAÍDA está no centro · segure 10 segundos · as setas mostram o caminho",
  'coach.loot': 'Pegue o saque laranja · ele vai para a sua bolsa',
  'coach.kills': 'Abates melhoram sua arma · Espaço para esquivar',
  'coach.killsTouch': 'Abates melhoram sua arma · toque em Esquiva',
  'spect.watching': 'Assistindo {name} · ◀ ▶ para trocar',
  'spect.down': 'Você caiu',
  'spect.results': 'Resultados',
  'res.extracted': 'Extraído',
  'res.storm': 'Engolido pela tempestade',
  'res.dropped': 'Derrubado',
  'res.sealed': 'Preso lá dentro',
  'res.inside': '{k} abates · {t} lá dentro',
  'res.out': 'Saiu com {p} numa aposta de {s}: {d}.',
  'res.paid': 'Pago {v} na taxa de entrada.',
  'res.killer': '{n} está com a sua bolsa agora. Tinha {v}, e só vocês dois vão saber.',
  'res.inStorm': 'Sua bolsa, {v}, está na tempestade para quem tiver coragem.',
  'res.sealedText': 'A incursão fechou com você lá dentro. Seus {v} foram para o saque da próxima.',
  'res.again': 'Jogar de novo',
  'res.tables': 'Mesas',
  'res.share': 'Compartilhar',
  'share.title': 'Compartilhar',
  'share.x': 'Postar no 𝕏',
  'share.copy': 'Copiar imagem',
  'share.save': 'Salvar PNG',
  'share.close': 'Fechar',
  'lk.title': 'Armário',
  'lk.outfits': 'Visuais',
  'lk.shop': 'Loja',
  'lk.bags': 'Bolsas da sorte',
  'lk.sortDesc': "Mais raros primeiro ↓",
  'lk.sortAsc': "Mais comuns primeiro ↑",
  'lk.allGuns': "Todas as armas",
  'lk.takeOff': "Tirar",
  'lk.empty': "Nada aqui ainda: bolsas e caixas da loja enchem sua coleção.",
  'lk.emptyTurrets': "Ainda sem skins de torreta: elas vêm do passe de batalha.",
  'lk.pickSkin': "Toque numa skin para ver e depois equipe.",
  'lk.all': 'Todos',
  'lk.owned': 'Meus',
  'lk.him': 'Ele',
  'lk.her': 'Ela',
  'lk.shopUsd': '$ da loja',
  'lk.shopNote': 'Recarregue $ da loja com USDC ou USDT (pacotes maiores dão bônus). $ da loja só vale aqui e não pode ser sacado. Faltou? A diferença sai dos seus USDC/USDT.',
  'lk.bagsNote': 'Chances exatas, sorteadas no servidor. Sem repetidos até completar uma raridade, e um repetido devolve 10% do preço em $ da loja. Garantia: Épico+ em 15 aberturas e Lendário+ em 60.',
  'lk.topupFrom': '+ {v} USDC/USDT para recarregar',
  'lk.collected': '{a} / {b} coletados',
  'lk.equipped': 'Equipado',
  'lk.equip': 'Equipar',
  'lk.buy': 'Comprar',
  'lk.trialLeft': 'Teste · faltam {t}',
  'lk.trialHow': 'Teste de promoção: seu por mais {t}. Compre para ficar com ele.',
  'lk.free': 'Grátis para todos.',
  'lk.inCollection': 'Na sua coleção.',
  'lk.buyOrBag': 'Compre aqui ou tente a sorte com uma bolsa.',
  'lk.tryingOn': 'Experimentando.',
  'lk.bonus': '+{n}% de bônus',
  'lk.pay': 'paga {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Épico+ em',
  'lk.legIn': 'Lendário+ em',
  'lk.openFree': 'Abrir · grátis',
  'lk.buyOpen': 'Comprar e abrir',
  'lk.pityDrop': 'garantia',
  'lk.dup': 'Já é seu · {v} de volta',
  'lk.new': '<b>Novo</b> na sua coleção',
  'lk.jackpotIs': 'o jackpot é {r}',
  'lk.showOff': 'Exibir no X',
  'lk.postMiss': 'Postar o azar no X',
  'lk.another': 'Abrir outra',
  'lk.free1': 'grátis',
  'lk.back': 'Voltar ao armário',
  'lk.yours': '{n} é seu.',
  'r.common': 'Comum',
  'r.rare': 'Raro',
  'r.epic': 'Épico',
  'r.legendary': 'Lendário',
  'r.mythic': 'Mítico',
  'r.exotic': 'Exótico',
  'ach.title': "Tarefas e conquistas",
  'ach.button': 'Conquistas',
  'ach.intro': 'Cada uma dá XP de patente uma vez e libera seu nome como título para usar.',
  'ach.wear': 'Usar título',
  'ach.worn': 'Em uso',
  'ach.wearing': 'Título:',
  'ach.takeOff': 'tirar',
  'ach.noTitle': 'Sem título',
  'ach.unlocked': 'Conquista liberada',
  'ach.seeAll': 'Todas as conquistas',
  'achd.raids': 'Jogue {n} incursões',
  'achd.extracts': 'Extraia-se {n} vezes',
  'achd.kills': 'Faça {n} abates',
  'achd.bestKills': '{n} abates numa incursão',
  'achd.bestMulti': 'Um abate múltiplo ×{n}',
  'achd.prestige': 'Complete o arsenal {n} vezes',
  'achd.firstBloods': 'Tire o primeiro sangue {n} vezes',
  'achd.secs': 'Passe {n} h dentro de incursões',
  'achd.bestReturn': 'Saia com {n}× a sua aposta',
  'achd.golden': 'Extraia-se de uma incursão dourada',
  'achd.lastExit': 'Saia pela última saída',
  'achd.pacifist': 'Extraia-se sem nenhum abate',
  'achd.rank': 'Chegue à patente {n}',
  'achd.outfits': 'Tenha {n} visuais',
  'ach.gunslinger': "Pistoleiro",
  'ach.close_quarters': "Combate próximo",
  'ach.spray_and_pray': "Rajada cega",
  'ach.rifleman': "Fuzileiro",
  'ach.marksman': "Atirador",
  'ach.deadeye': "Olho de águia",
  'ach.blade_dancer': "Dançarino da lâmina",
  'ach.shadow_blade': "Lâmina sombria",
  'ach.deathmatch_king': "Rei do mata-mata",
  'ach.duelist': "Duelista",
  'ach.squad_goals': "Espírito de equipe",
  'ach.one_shot_one_kill': "Um tiro, uma baixa",
  'ach.specialist': "Especialista",
  'ach.engineer': "Engenheiro",
  'ach.ranked_debut': "Estreia ranqueada",
  'ach.ranked_grinder': "Esforçado ranqueado",
  'ach.ranked_victor': "Vencedor ranqueado",
  'ach.gold_league': "Liga Ouro",
  'ach.diamond_league': "Liga Diamante",
  'ach.neon_legend': "Lenda Neon",
  'ach.unboxer': "Desempacotador",
  'ach.case_hunter': "Caçador de caixas",
  'ach.case_lord': "Senhor das caixas",
  'ach.armory': "Arsenal",
  'ach.arsenal_baron': "Barão do arsenal",
  'ach.pass_holder': "Dono do passe",
  'ach.pass_maxed': "Passe completo",
  'ach.neon_bearer': "Portador do neon",
  'ach.by_a_thread': "Por um fio",
  'ach.untouchable': "Intocável",
  'ach.ghost_walker': "Passo fantasma",
  'ach.one_tap': "Um toque",
  'achd.kHandgun': "Faça {n} abates com pistolas",
  'achd.kShotgun': "Faça {n} abates com escopetas",
  'achd.kSmg': "Faça {n} abates com submetralhadoras",
  'achd.kRifle': "Faça {n} abates com rifles e metralhadoras",
  'achd.kSniper': "Faça {n} abates com snipers",
  'achd.kKnife': "Faça {n} abates com faca",
  'achd.dmWins': "Vença {n} mata-matas",
  'achd.duelWins': "Vença {n} duelos",
  'achd.teamWins': "Vença {n} partidas em equipe",
  'achd.hcWins': "Vença {n} partidas hardcore",
  'achd.weaponWins': "Vença {n} partidas de uma arma",
  'achd.turretKills': "Faça {n} abates com torretas em Armas + Lasers",
  'achd.rankedGames': "Jogue {n} ranqueadas",
  'achd.rankedWins': "Vença {n} ranqueadas",
  'achd.bestDiv': "Chegue a {n} na ranqueada",
  'achd.opened': "Abra {n} caixas e bolsas",
  'achd.wskins': "Tenha {n} skins de arma",
  'achd.passTier': "Chegue ao nível {n} do passe",
  'achd.stitles': "Ganhe um título da temporada",
  'achd.clutch': "Saia com 10 de vida ou menos",
  'achd.flawless': "Saia após 2+ minutos sem levar um tiro",
  'achd.ninjaWin': "Vença um modo de bolão sem nenhum abate",
  'achd.oneShots': "Leve {n} corredores da vida cheia a zero com um golpe",
  'ach.secret': "Secreto",
  'ach.secretDesc': "Continue jogando: ele se revela quando você conquistar.",
  'r.mystery': "Mistério",
  'ach.rookie': 'Recruta',
  'ach.regular': 'Frequentador',
  'ach.veteran': 'Veterano',
  'ach.lifer': 'Carreira',
  'ach.eternal': 'Eterno',
  'ach.escape_artist': 'Mestre da fuga',
  'ach.ghost': 'Fantasma',
  'ach.smuggler': 'Contrabandista',
  'ach.phantom': 'Espectro',
  'ach.first_kill': 'Primeiro abate',
  'ach.hunter': 'Caçador',
  'ach.butcher': 'Açougueiro',
  'ach.reaper': 'Ceifador',
  'ach.apex': 'Predador',
  'ach.rampage': 'Massacre',
  'ach.one_man_army': 'Exército de um',
  'ach.double_tap': 'Toque duplo',
  'ach.triple_threat': 'Ameaça tripla',
  'ach.godlike': 'Divino',
  'ach.full_arsenal': 'Arsenal completo',
  'ach.arsenal_master': 'Mestre do arsenal',
  'ach.first_blood': 'Primeiro sangue',
  'ach.opener': 'O abridor',
  'ach.night_shift': 'Turno da noite',
  'ach.insomniac': 'Insone',
  'ach.double_up': 'Dobrou',
  'ach.big_bag': 'Bolsa cheia',
  'ach.gold_rush': 'Corrida do ouro',
  'ach.last_one_out': 'O último a sair',
  'ach.pacifist': 'Pacifista',
  'ach.seasoned': 'Calejado',
  'ach.officer': 'Oficial',
  'ach.commander': 'Comandante',
  'ach.legend': 'Lenda',
  'ach.collector': 'Colecionador',
  'ach.curator': 'Curador',
  'ach.hoarder': 'Acumulador',
  'intro.tag': "Aposte. Saqueie. Saia.",
  'intro.go': "Entrar",
  'intro.fonts': "Afiando facas…",
  'intro.world': "Pintando a escuridão…",
  'intro.connect': "Procurando incursão…",
  'intro.profile': "Arrumando sua bolsa…",
  'intro.ready': "Pronto",
  'tb.wallet': "Carteira",
  'tb.shop': "$ da loja",
  'nav.play': "Jogar",
  'nav.shop': "Loja",
  'nav.inventory': "Inventário",
  'nav.swap': "Troca",
  'nav.chat': "Chat",
  'nav.achievements': "Tarefas",
  'nav.pass': "Passe",
  'bp.season': "Temporada {n}",
  'bp.ends': "termina em {d}d {h}h",
  'bp.tier': "Nível {n}/{m}",
  'bp.xp': "{a}/{b} XP para o próximo nível",
  'bp.maxed': "Todos os níveis concluídos",
  'bp.how': "Cada incursão enche o passe com o mesmo XP da sua patente.",
  'bp.free': "Grátis",
  'bp.premium': "Premium",
  'bp.buy': "Passe premium · {v}",
  'bp.owned': "Premium ativo",
  'bp.perks': "Os 50 níveis de recompensas: armaduras Senhor da Guerra e Ápice, 2 skins de torreta, 5 skins de arma da temporada, caixas e $.",
  'bp.claim': "Resgatar",
  'bp.claimAll': "Resgatar tudo ({n})",
  'bp.claimed': "Resgatado",
  'bp.limited': "Só nesta temporada",
  'bp.turrets': "Skins de torreta",
  'bp.turretsNote': "Suas torretas em Armas + Lasers.",
  'bp.equip': "Equipar",
  'bp.equipped': "Equipado",
  'bp.none': "Padrão",
  'bp.up': "Passe de batalha: nível {n}!",
  'bp.got': "Resgatado: {x}",
  'bp.credit': "+{v} da loja",
  'mode.ranked': "Ranqueada",
  'mode.ranked.d': "Battle royale pela sua classificação da temporada. Do Bronze à Lenda Neon; as melhores posições ganham um giro bônus.",
  'nav.ranked': "Ranqueada",
  'rd.title': "Ranqueada · Temporada {n}",
  'rd.pos': "#{n} de {m}",
  'rd.unranked': "Jogue uma partida ranqueada para entrar na tabela.",
  'rd.play': "Jogar ranqueada",
  'rd.games': "Partidas",
  'rd.wins': "Vitórias",
  'rd.top3': "Top 3",
  'rd.kills': "Abates",
  'rd.winrate': "Taxa de vitória",
  'rd.player': "Jogador",
  'rd.div': "Divisão",
  'rd.div.bronze': "Bronze",
  'rd.div.silver': "Prata",
  'rd.div.gold': "Ouro",
  'rd.div.platinum': "Platina",
  'rd.div.diamond': "Diamante",
  'rd.div.master': "Mestre",
  'rd.div.legend': "Lenda Neon",
  'rd.titles': "Títulos da temporada",
  'rd.titlesNote': "Saem do giro bônus da ranqueada. Brilham em neon acima do seu nome e dão XP extra até o fim da temporada.",
  'rd.wear': "Usar",
  'rd.off': "Tirar",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "temporada encerrada",
  'rd.board': "Tabela da temporada",
  'rd.empty': "Ninguém jogou ranqueada nesta temporada ainda. Seja o primeiro.",
  'rd.place': "Posição #{p} de {n}",
  'rd.promoted': "promovido!",
  'rd.demoted': "rebaixado",
  'rd.practice': "Treino: sua classificação não muda.",
  'rd.spin': "Giro bônus",
  'rd.spinWhy': "pela posição #{p}",
  'rd.won': "Você ganhou:",
  'rd.wornNow': "Seu novo título já brilha acima de você.",
  'st.contender': "Desafiante",
  'st.elite': "Elite",
  'st.champion': "Campeão",
  'xp.Season title': "Título da temporada",
  'news.title': "Novidades",
  'news.ok': "Entendi",
  'news.note': "Cada atualização, com data e hora.",
  'news.open': "Abrir",
  'stake.own': "Sua aposta",
  'stake.range': "Aposta de $0,10 a $10.000",
  'nav.settings': "Ajustes",
  'nav.more': "Mais",
  'modes.title': "Modo de jogo",
  'kind.raid': "extração",
  'kind.br': "o vencedor leva o pote",
  'kind.team': "pote do time",
  'mode.raid': "Incursão",
  'mode.raid.d': "Saqueie, lute e segure 10 s na saída do centro. Fique com o que carrega.",
  'mode.br': "Battle Royale",
  'mode.br.d': "Até 20 corredores. O último de pé leva o pote inteiro.",
  'mode.duel': "Duelo",
  'mode.duel.d': "Um contra um. O vencedor leva as duas apostas.",
  'mode.knives': "Só facas",
  'mode.knives.d': "Só lâminas a incursão toda. Vence o último de pé.",
  'mode.pistols': "Só pistolas",
  'mode.pistols.d': "Só pistolas. Vence o último de pé.",
  'mode.shotguns': "Só escopetas",
  'mode.shotguns.d': "De perto e barulhento. Vence o último de pé.",
  'mode.rifles': "Só fuzis",
  'mode.rifles.d': "Tiroteios a média distância. Vence o último de pé.",
  'mode.snipers': "Só snipers",
  'mode.snipers.d': "Miras laser por toda parte. Vence o último de pé.",
  'mode.team2': "Times 2 x 2",
  'mode.team2.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'mode.team4': "Times 4 x 4",
  'mode.team4.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'mode.team8': "Times 8 x 8",
  'mode.team8.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'hud.pot': "Pote",
  'hud.left': "Restam {n} · aposta {s}",
  'hud.teamsLeft': "Restam {n} times · aposta {s}",
  'hud.startPot': "O último de pé leva o pote",
  'hud.startTeam': "Fique com seu time · elimine o outro",
  'hud.goldenPot': "Incursão dourada · jackpot somado ao pote",
  'coach.pot': "Sem saídas aqui · fique no círculo · vence o último de pé",
  'coach.team': "Nomes verdes são seu time · vermelhos são o inimigo",
  'warn.exit30': "O tempo está acabando · vá para a saída no centro",
  'warn.exit10': "Última chance · comece a segurar 10 s agora ou perde tudo",
  'warn.pot30': "30s · a tempestade se fecha",
  'warn.pot10': "10s · vence quem tiver mais vivos",
  'storm.final': "Colapso final · só a última saída",
  'storm.finalPot': "Colapso final · nenhum lugar para se esconder",
  'storm.closing': "A tempestade está chegando",
  'storm.in5': "A tempestade avança em 5s",
  'feed.youDropped': "Você derrubou {name}",
  'feed.stormTook': "{name} foi engolido pela tempestade",
  'feed.dropped': "{a} derrubou {b}",
  'feed.down': "{name} caiu",
  'feed.extracted': "{name} se extraiu",
  'feed.exitClosed': "A saída {name} fechou",
  'spect.settling': "Seu resultado chega quando a incursão fechar.",
  'res.victory': "Vitória",
  'res.teamWon': "Seu time venceu",
  'res.defeated': "Derrota",
  'res.wonText': "Você levou {p} com uma aposta de {s}.",
  'res.lostPot': "O pote ficou com o último de pé.",
  'res.teamLost': "O outro time levou o pote.",
  'xp.Victory': "Vitória",
  'ach.champion': "Campeão",
  'ach.warlord': "Senhor da guerra",
  'achd.wins': "Vença {n} incursões com pote",
  'lk.weapons': "Skins de armas",
  'lk.onlyBags': "Skins só saem das bolsas e caixas da loja.",
  'lk.toShop': "Abrir a loja",
  'lk.toOpen': "{n} para abrir",
  'lk.limited': "Limitado · {n}",
  'lk.minted': "{a} de {b} cunhados",
  'lk.plain': "Padrão",
  'lk.fromBags': "Sai das bolsas de visuais da loja.",
  'lk.fromCrates': "Sai das caixas de armas da loja.",
  'lk.trialHow2': "Teste de promoção: seu por mais {t}.",
  'lk.weaponHow': "Escolha um acabamento seu para equipar. Todos na incursão veem.",
  'fx.glow': "aura",
  'fx.pulse': "aura pulsante",
  'fx.ghost': "espectral",
  'fx.laser': "olhos laser",
  'fx.rainbow': "prismático",
  'fx.fire': "em chamas",
  'fx.gold': "ouro líquido",
  'fx.holo': "holograma",
  'fx.glitch': "glitch",
  'fx.lightning': "raios",
  'fx.galaxy': "galáxia",
  'fx.sparks': "faíscas",
  'fx.frost': "geada",
  'fx.money': "chuva de dinheiro",
  'fx.matrix': "chuva de código",
  'fx.shadow': "fumaça sombria",
  'fx.cape': "capa",
  'box.c-samurai': "Caixa Ciber Samurai",
  'box.c-neon': "Caixa Noites Neon",
  'box.c-arctic': "Caixa Ártica",
  'box.c-inferno': "Caixa Inferno",
  'box.c-crypto': "Caixa Reis Cripto",
  'box.c-toxic': "Caixa Terra Tóxica",
  'box.c-toon': "Caixa Cidade Toon",
  'box.c-knife': "Caixa de facas",
  'box.c-pistol': "Caixa de pistolas",
  'box.c-smg': "Caixa de submetralhadoras",
  'box.c-rifle': "Caixa de rifles",
  'box.c-heavy': "Caixa pesada",
  'box.c-sniper': "Caixa de sniper",
  'box.b-crypto': "Bolsa Memes Cripto",
  'box.b-heroes': "Bolsa Heróis do Multiverso",
  'box.b-monsters': "Bolsa Monstros e Mitos",
  'box.b-cyber': "Bolsa Ciber Rua",
  'box.b-toon': "Bolsa Amigos Toon",
  'shop.g.theme': "Coleções",
  'shop.g.class': "Caixas por classe de arma",
  'shop.g.tier': "Caixas por nível",
  'shop.contents': "Conteúdo · {n} itens",
  'box.street': "Bolsa de rua",
  'box.vault': "Bolsa do cofre",
  'box.golden': "Bolsa dourada",
  'box.elite': "Bolsa elite",
  'box.diamond': "Bolsa de diamante",
  'box.obsidian': "Bolsa de obsidiana",
  'box.royal': "Bolsa real",
  'box.apex': "Bolsa Apex",
  'box.genesis': "Bolsa Gênesis",
  'box.w-scrap': "Caixa de sucata",
  'box.w-armory': "Caixa do arsenal",
  'box.w-brass': "Caixa de latão",
  'box.w-specops': "Caixa de operações especiais",
  'box.w-diamond': "Caixa de diamante",
  'box.w-obsidian': "Caixa de obsidiana",
  'box.w-royal': "Caixa real",
  'box.w-apex': "Caixa Apex",
  'box.w-genesis': "Caixa Gênesis",
  'shop.topup': "Recarregar $ da loja",
  'shop.bags': "Bolsas de visuais",
  'shop.crates': "Caixas de armas",
  'shop.bagsNote': "Visuais para o seu corredor. Nove níveis: quanto mais cara a bolsa, melhores as chances.",
  'shop.cratesNote': "Skins para suas armas e faca, vendidas separadamente dos visuais. Nove níveis.",
  'shop.fair': "Chances exatas, sorteadas no servidor. Garantia: Épico+ em {e} aberturas, Lendário+ em {l}.",
  'shop.odds': "Chances e garantia",
  'shop.qty': "Quantidade",
  'shop.open': "Abrir ×{n}",
  'shop.limited': "Edições limitadas",
  'shop.soldOut': "Esgotado",
  'shop.dup': "Repetido · +{v}",
  'shop.new': "Novo",
  'shop.back': "{v} de volta",
  'shop.equipBest': "Equipar {n}",
  'inv.wallet': "Carteira",
  'inv.deposit': "Depositar · sacar",
  'inv.walletNote': "Tokens reais que a casa guarda para você. Saque quando quiser para o endereço com que entrou.",
  'inv.playNote': "Dinheiro de jogo neste navegador. Recarregue quando quiser.",
  'inv.shopNote': "Comprado com USDC/USDT, gasto só em bolsas e caixas. Não pode ser sacado.",
  'inv.unopened': "Fechadas",
  'inv.collection': "Coleção",
  'inv.opened': "Abertas",
  'inv.career': "Carreira",
  'inv.raids': "Incursões",
  'inv.kills': "Abates",
  'inv.extracts': "Extrações",
  'inv.wins': "Potes ganhos",
  'inv.best': "Melhor incursão (abates)",
  'inv.time': "Tempo lá dentro",
  'swap.game': "Saldo do jogo",
  'swap.gameNote': "Na hora, ao preço atual, taxa de {f}%.",
  'swap.gameOff': "Trocas dentro do jogo estão desligadas neste servidor. Use a troca na carteira abaixo.",
  'swap.from': "Você dá",
  'swap.to': "Você recebe",
  'swap.have': "Você tem",
  'swap.flip': "Inverter",
  'swap.go': "Trocar",
  'swap.short': "Saldo insuficiente",
  'swap.done': "Trocou {a} por {b}.",
  'swap.wallet': "Sua carteira",
  'swap.signIn': "Entre com uma carteira Starknet para trocar lá via AVNU.",
  'swap.needChain': "Trocas via AVNU funcionam com uma carteira Starknet real no modo online.",
  'swap.slippage': "Slippage máx.",
  'swap.quoting': "Buscando a melhor rota…",
  'swap.impact': "impacto no preço {p}%",
  'swap.goAvnu': "Trocar com AVNU",
  'swap.noQuote': "Sem rota para esse par agora.",
  'swap.sent': "Troca enviada: {tx}",
  'swap.walletNote': "A AVNU roteia entre as exchanges da Starknet. Você assina na sua carteira; o jogo nunca guarda esses tokens.",
  'chat.ph': "Diga algo…",
  'chat.send': "Enviar",
  'chat.empty': "Nenhuma mensagem ainda. Diga gm.",
  'chat.online': "Todo o lobby vê isto. Seja gentil.",
  'chat.practice': "O treino é offline: só os bots estão ouvindo.",
  'set.graphics': "Gráficos",
  'set.quality': "Qualidade",
  'set.qualityNote': "Auto reduz os detalhes quando os quadros ficam lentos.",
  'set.auto': "Auto",
  'set.high': "Alta",
  'set.medium': "Média",
  'set.low': "Baixa",
  'set.shake': "Tremor de tela",
  'set.motion': "Animações do menu",
  'set.display': "Exibição",
  'set.skins': "Skins",
  'set.skinsNote': "De quem desenhar visuais e skins de armas.",
  'set.skinsAll': "Todos",
  'set.skinsMine': "Só os meus",
  'set.skinsNone': "Nenhum",
  'set.names': "Nomes sobre os corredores",
  'set.titles': "Títulos sobre os nomes",
  'set.controls': "Controles",
  'set.stick': "Tamanho dos sticks de toque",
  'set.lefty': "Canhoto (toque)",
  'set.leftyNote': "Troca os sticks de mover e mirar.",
  'set.audio': "Áudio",
  'set.sound': "Volume dos efeitos",
  'set.music': "Volume da música",
  'set.track': "Trilha sonora",
  'set.trackAuto': "Mix",
  'set.trackNote': "Uma faixa diferente a cada partida, ou fique com a favorita.",
  'pause.nextTrack': "Próxima faixa ⏭",
  'set.language': "Idioma",
  'shop.exoticIn': "Exótico em",
  'shop.guarantee': "Exótico garantido em {n} aberturas",
  'set.voice': "Locutor",
  'mode.dm': "Mata-mata",
  'mode.dm.d': "Cada um por si, renasce após cada morte. Quem tiver mais abates no fim leva o pote.",
  'mode.gl': "Armas + Lasers",
  'mode.gl.d': "Mata-mata com loja: abates dão créditos para kits médicos, torretas e minas laser.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Vida mínima: uma bala e você cai. O último de pé leva o pote.",
  'kind.dm': "mais abates leva o pote",
  'hud.startDm': "Quem tiver mais abates quando o relógio zerar leva o pote",
  'hud.startGl': "Abates dão créditos · 1 kit médico · 2 torreta · 3 mina laser",
  'hud.startHc': "Um tiro e você cai. Faça cada tiro valer.",
  'hud.respawned': "De volta",
  'hud.respawnIn': "Renasce em {s}s",
  'hud.tookLead': "Você assumiu a liderança",
  'hud.lostLead': "Você perdeu a liderança",
  'hud.dmScore': "{k} abates · {d} mortes · #{p}",
  'hud.dmGoal': "O primeiro abate assume a liderança",
  'hud.oneHit': "1 TIRO",
  'feed.leader': "{name} assume a liderança com {k}",
  'gl.medkit': "Kit médico",
  'gl.turret': "Torreta",
  'gl.mine': "Mina laser",
  'gl.revive': "Reviver esquadrão",
  'gl.no.none': "Ninguém está caído",
  'gl.no.mode': "Só no modo zumbi",
  'gl.revived': "{name} reviveu {n} do esquadrão",
  'gl.you': "Você",
  'gl.no.cash': "Créditos insuficientes",
  'gl.no.full': "Vida já está cheia",
  'gl.no.limit': "Limite atingido",
  'gl.no.wall': "Perto demais de uma parede",
  'res.dmLost': "Terminou em #{p}",
  'res.dmText': "{k} abates, {d} mortes. O vencedor fez {top}.",
  'coach.dm': "Você renasce · vence quem tiver mais abates no fim",
  'coach.gl': "Abates dão créditos · gaste num kit médico ✚, numa torreta ◈ ou numa mina laser ⌁",
  'set.voiceNote': "Locutor gravado (inglês, ucraniano, espanhol, francês, português; inglês para os outros idiomas).",
  'net.waking': "Acordando o servidor (a hospedagem grátis dorme quando ninguém joga, até um minuto)… O treino funciona enquanto isso.",
  'shop.bulk': "A cada {n} caixas, uma grátis",
  'shop.bulkOn': "Caixas grátis incluídas: {n}",
  'net.online': "{n} online",
  'st.title': "Primeiros passos",
  'st.signin': "Entre",
  'st.signin.d': "Com sua carteira Starknet, Cartridge ou e-mail.",
  'st.signin.go': "Entrar",
  'st.fund': "Adicione fundos",
  'st.fund.d': "Envie alguns tokens da sua carteira para o saldo do jogo. Saque quando quiser.",
  'st.fundTest': "Testnet: STRK grátis em starknet-faucet.vercel.app.",
  'st.fund.go': "Depositar",
  'st.coin': "Escolha sua moeda",
  'st.coin.d': "Escolha abaixo com qual moeda apostar. Os ganhos voltam na mesma moeda.",
  'st.coin.go': "Ver moedas",
  'st.play': "Jogue sua primeira partida",
  'st.play.d': "Escolha modo e aposta, toque em Jogar e depois Pronto.",
  'st.play.go': "Jogar",
  'touch.fire': "Atirar",
  'rot.title': "Vire o celular",
  'rot.sub': "O raid funciona melhor na horizontal: mova-se à esquerda, atire à direita.",
  'rot.anyway': "Jogar na vertical",
  'prep.waiting': "Esperando jogadores",
  'prep.waitingMe': "Sem cronômetro: chame amigos e toque em Começar quando estiverem prontos. Bots ocupam as vagas. {n} de {of} vagas ocupadas.",
  'prep.waitingJoin': "{n} de {of} vagas ocupadas. Aposte e toque em Pronto para entrar.",
  'prep.firstWait': "Toque em Pronto: a sala espera todos, sem cronômetro.",
  'prep.start': "Começar agora",
  'nav.friends': "Amigos",
  'nav.guilds': "Guildas",
  'so.now': "agora",
  'so.min': "há {n} min",
  'so.hr': "há {n} h",
  'so.day': "há {n} d",
  'so.seen': "Visto {t}",
  'so.st.lobby': "Online",
  'so.st.waiting': "Esperando numa sala",
  'so.st.raid': "Num raid",
  'so.friend': "Amigo",
  'so.sent': "Pedido enviado",
  'so.accept': "Aceitar",
  'so.add': "Adicionar amigo",
  'so.invited': "Convidado",
  'so.invite': "Convidar",
  'so.message': "Mensagem",
  'so.onlineOnly': "Amigos, mensagens e guildas funcionam no modo online.",
  'so.gInvite': "Para a guilda",
  'so.gInvited': "Convidado",
  'so.gInviteSent': "Convite para a guilda enviado",
  'so.gInvitesYou': "convida você para a guilda",
  'so.gMembers': "{n} membros",
  'so.gJoin': "Entrar na guilda",
  'so.more': "Mostrar mais ({n})",
  'so.players': "Jogadores",
  'so.friends': "Amigos",
  'so.messages': "Mensagens",
  'so.search': "Buscar jogadores pelo nome",
  'so.count': "{n} jogadores · {on} online",
  'so.none': "Ninguém encontrado.",
  'so.wants': "quer ser seu amigo",
  'so.requests': "Pedidos de amizade",
  'so.noFriends': "Ainda sem amigos. Encontre pessoas em Jogadores.",
  'so.pending': "Pedidos enviados",
  'so.cancel': "Cancelar",
  'so.decline': "Recusar",
  'so.sayHi': "Diga oi 👋",
  'so.noMsgs': "Ainda sem mensagens.",
  'so.remove': "Remover amigo",
  'so.onlineNow': "Online agora",
  'so.nobody': "Ninguém livre online agora.",
  'so.invitesYou': "convida você para um raid",
  'so.waitingN': "{n} esperando",
  'so.join': "Entrar",
  'so.later': "Depois",
  'so.reqToast': "{n} quer ser seu amigo",
  'so.nowFriends': "Você e {n} agora são amigos",
  'so.invSent': "Convite enviado",
  'so.invitePlayers': "Convidar jogadores",
  'so.inviteHint': "Eles recebem um cartão com o botão Entrar que os traz para esta sala.",
  'gd.members': "{n} membros",
  'gd.leave': "Sair da guilda",
  'gd.join': "Entrar",
  'gd.all': "Todas as guildas",
  'gd.needRank': "Rank {n} ou mais (você: {have})",
  'gd.needBuy': "Pelo menos uma compra com USDC/USDT",
  'gd.create': "Criar uma guilda",
  'gd.name': "Nome da guilda",
  'gd.tag': "Tag (2-5)",
  'gd.desc': "Descrição curta (opcional)",
  'gd.found': "Fundar a guilda",
  'gd.count': "{n} membros · {on} online",
  'gd.yours': "Sua guilda",
  'gd.list': "Guildas",
  'gd.none': "Ainda sem guildas. Seja o primeiro.",
  'gd.err.signin': "Entre primeiro.",
  'gd.err.member': "Saia da sua guilda primeiro.",
  'gd.err.purchase': "Fundar uma guilda exige uma compra com USDC/USDT.",
  'gd.err.rank': "Fundar uma guilda exige rank 20.",
  'gd.err.name': "Nome: 3-24 letras, dígitos ou espaços.",
  'gd.err.tag': "Tag: 2-5 letras ou dígitos.",
  'gd.err.taken': "Esse nome ou tag já existe.",
  'pf.title': "Jogador",
  'pf.rank': "Rank {n}",
  'pf.guild': "Guilda: {g}",
  'pf.raids': "Raids",
  'pf.wins': "Vitórias",
  'pf.kills': "Abates",
  'pf.extracts': "Extrações",
  'pf.best': "Recorde de abates",
  'pf.time': "Tempo jogado",
  'pf.ach': "Conquistas",
  'pf.multi': "Melhor sequência",
  'pf.since': "Joga desde",
  'tb.readyWait': "{n} esperando",
  'mc.waiting': "{n} esperando",
  'pause.open': "Menu (Esc)",
  'pause.title': "Menu",
  'pause.resume': "Continuar",
  'pause.settings': "Configurações",
  'pause.leave': "Sair da partida",
  'pause.leaveLose': "Sair (perde a aposta)",
  'pause.leaveSure': "Toque de novo para sair",
  'pause.keys': "Esc: voltar à partida",
  'pause.back': "← Voltar",
  'pause.on': "lig.",
  'pause.off': "desl.",
  'pause.practice': "O treino está pausado.",
  'pause.practiceDead': "Você foi eliminado. Saia quando quiser.",
  'pause.alive': "A partida continua com o menu aberto. Se sair agora, seu corredor fica no mapa e a aposta fica na partida.",
  'pause.dead': "Você foi eliminado. Saia quando quiser: o que ganhou ainda chega ao seu saldo.",
  'gd.chat': "Chat",
  'gd.chatEmpty': "Nenhuma mensagem ainda. Diga oi para a guilda.",
  'gd.chatPh': "Escreva para a guilda…",
  'swap.min': "Troca mínima: {v}",
  'prep.waitingPeople': "Sem cronômetro: chame amigos, a incursão começa quando {min} jogadores estiverem prontos. Só jogadores reais. {n} de {of} vagas ocupadas.",
  'prep.people': "Só jogadores reais: aqui todos começam com uma faca.",
  'shop.firstTopup': "A primeira recarga dobra: ganhe o mesmo valor em $ da loja, até {v} extra.",
  'tour.who': "sua contato",
  'tour.voice': "Voz lig./desl.",
  'tour.next': "Próximo",
  'tour.done': "Vamos lá",
  'set.tour': "Tutorial",
  'set.tourNote': "A Nyx mostra o jogo de novo.",
  'set.tourBtn': "Refazer o tutorial",
  'nyx.hello': "Oiii, corredor! Eu sou a Nyx, sua guia esta noite! Fica comigo, e você sai da sua primeira incursão... rico!",
  'nyx.name': "Primeiro o mais importante! Digite um nome para seu corredor e toque em Pronto. Todos vão vê-lo acima da sua cabeça!",
  'nyx.nameOk': "Ah, que nome fofo! Gostei!",
  'nyx.practice': "Agora toque em Treino! É grátis, só bots. Perfeito para a primeira partida!",
  'nyx.practiceOk': "Ééé! Boa escolha!",
  'nyx.modes': "Esses são os modos de jogo! Hoje jogamos Incursão, o clássico. Saqueie, lute e saia! Toque em Incursão!",
  'nyx.modeOk': "Incursão, então! Bora!",
  'nyx.bag': "É assim! Sua aposta vai na sua bolsa. Derrube alguém, e a bolsa dele é sua! Caiu... e a sua é dele. Eita!",
  'nyx.shop': "Roupas e skins de armas saem de bolsas e caixas, aqui na loja! E psiu... tem uma grátis esperando por você!",
  'nyx.social': "Amigos, mensagens, guildas! Traga sua galera. Tudo é mais divertido junto!",
  'nyx.wallet': "Quer apostas reais? Entre com uma carteira, ou só com um e-mail! Saques só vão para o seu próprio endereço. Tudo seguro!",
  'nyx.play': "Pronto? Aperte Jogar!",
  'nyx.ready': "Essa é a sala de espera! Aperte Pronto, e a gente cai! Uhul!",
  'nyx.start': "Entramos! Mova com W, A, S, D. Mire com o mouse e clique para atirar! Espaço para o dash!",
  'nyx.startTouch': "Entramos! Seu polegar esquerdo te move. Segure Fogo, à direita, ele mira por você!",
  'nyx.loot': "Vê aquele brilho laranja? É dinheiro! Passa correndo por cima!",
  'nyx.pickup': "Eba! Sua bolsa ficou mais pesada!",
  'nyx.kill': "Primeiro abate! Belo tiro! Pegue o que caiu. Ah, e uma arma melhor!",
  'nyx.hurt': "Ai, você está ferido! A vida não volta no combate, então cuidado!",
  'nyx.storm': "A tempestade está chegando! Fique dentro do círculo, rápido!",
  'nyx.exit': "Ah, essa bolsa ficou ótima em você! Ache um anel verde de saída e fique nele!",
  'nyx.extracting': "Fica parado! Três segundos! Não leve tiro!",
  'nyx.won': "Você saiu! Eu sabia que você conseguia! Até a próxima incursão, corredor!",
  'nyx.dead': "Aah, acontece! O treino é grátis, bora de novo!",
  'tour.yourMove': "Sua vez",
  'tour.skipStep': "Pular este passo",
  'tour.again': "Toque na Nyx para ouvir de novo",
  'tour.replayHint': "Quer o tutorial de novo? Configurações → Tutorial.",
  'mode.zombies': "Zumbis",
  'mode.zombies.d': "Cooperativo, sozinho ou com até 3 amigos: 20 ondas de mortos, cada uma mais difícil, chefes na 10 e na 20. Sem relógio. Abates dão créditos para torretas, minas laser e kits médicos.",
  'mode.gold': "Corrida do ouro",
  'mode.gold.d': "Sacos de ouro caem por toda a pedreira. Armas aleatórias, renascimento rápido. Quem pegar mais sacos leva o pote todo como crédito na loja.",
  'kind.zombie': "cooperativo · XP",
  'kind.gold': "um vencedor · crédito",
  'tb.zFee': "entrada · XP, títulos",
  'tb.goldFee': "entrada · o vencedor leva tudo",
  'prep.zFee': "entrada {v}",
  'prep.zSquad': "Esquadrão",
  'prep.goldPot': "Prêmio (crédito na loja)",
  'zp.title': "Sua arma para a partida",
  'zp.power': "Dano por segundo",
  'zp.melee': "sem recarga",
  'hud.waveK': "Onda",
  'hud.goldK': "Sacos de ouro",
  'hud.startZ': "Segure o cemitério. Eles vêm de todos os lados",
  'hud.startGold': "Pegue o ouro. Quem tiver mais sacos leva tudo",
  'hud.wave': "Onda {n} de {of}",
  'hud.bossWave': "ÚLTIMA ONDA · O CHEFE CHEGOU",
  'hud.waveClear': "Onda {n} superada",
  'hud.patched': "+35 HP",
  'hud.summon': "O chefe chama a horda",
  'hud.bossDown': "CHEFE ABATIDO · PARTIDA CONCLUÍDA",
  'hud.bagsShort': "ouro",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "próxima onda em {s} s",
  'hud.zLeft': "faltam {n} · {k} abatidos",
  'hud.goldPlace': "lugar {p} · {d} mortes · prêmio {s}",
  'hud.bossHp': "CHEFE {p}%",
  'hud.zBreak': "Recarregue e reagrupe: {s} s",
  'hud.zGoal': "Sobreviva a 20 ondas · chefes na 10 e na 20",
  'hud.goldGoal': "Vence quem tiver mais sacos no fim",
  'hud.zDown': "Caiu. Você volta na próxima onda se o esquadrão aguentar",
  'feed.zYou': "Os mortos te pegaram",
  'feed.zDown': "{name} foi despedaçado",
  'coach.z': "Fique na praça, costas com costas. Abates dão créditos: compre torretas (2), minas laser (3) e kits (1)",
  'coach.gold': "Passe por cima dos sacos para pegá-los. Se morrer, metade cai, então pegue e sobreviva",
  'warn.z60': "Falta um minuto",
  'warn.z10': "10 segundos: mate o chefe!",
  'warn.gold30': "30 segundos: pegue o que puder",
  'warn.gold10': "Faltam 10 segundos",
  'res.zCleared': "Partida concluída",
  'res.zFell': "Derrotados na onda {n}",
  'res.zWaves': "{n} / {of} ondas",
  'res.zWonText': "Dez ondas e o chefe, com um esquadrão de {s}. Você abateu {k} mortos.",
  'res.zText': "Você abateu {k} mortos (esquadrão de {s}). Quanto mais longe, mais XP.",
  'res.zTime': "tempo {t}",
  'res.goldWon': "Corrida do ouro vencida",
  'res.goldLost': "Lugar {p} na corrida do ouro",
  'res.goldWonText': "{b} sacos de ouro, mais que todos. {c} já está no seu saldo da loja.",
  'res.goldText': "Você pegou {b} sacos; o vencedor teve {top}. Só o primeiro recebe.",
  'xp.Waves survived': "Ondas superadas",
  'xp.Zombies': "Zumbis",
  'xp.Boss slain': "Chefe abatido",
  'xp.Run cleared': "Partida concluída",
  'xp.Gold bags': "Sacos de ouro",
  'ach.graveyard_shift': "Turno do cemitério",
  'ach.hold_the_line': "Segure a linha",
  'ach.undertaker': "Coveiro",
  'ach.exterminator': "Exterminador",
  'ach.giant_slayer': "Mata-gigantes",
  'ach.zombie_slayer': "Matador de zumbis",
  'ach.top_of_the_horde': "Topo da horda",
  'ach.nightmare_walker': "Andarilho dos pesadelos",
  'ach.army_of_one': "Exército de um",
  'ach.prospector': "Garimpeiro",
  'ach.gold_fever': "Febre do ouro",
  'ach.mother_lode': "Veio de ouro",
  'ach.bag_hoarder': "Acumulador de sacos",
  'ach.midas': "Midas",
  'achd.zRuns': "Jogue uma partida de zumbis",
  'achd.bestWave': "Supere a onda {n} de mortos",
  'achd.zKills': "Mate {n} zumbis",
  'achd.zBoss': "Dê o golpe final no chefe",
  'achd.zClears': "Conclua a partida de zumbis {n} vezes",
  'achd.zMvp': "Conclua uma partida com mais abates do esquadrão",
  'achd.zSolo': "Conclua a partida de zumbis sozinho",
  'achd.goldRuns': "Jogue uma corrida do ouro",
  'achd.goldWins': "Vença {n} corridas do ouro",
  'achd.bestGold': "Termine uma corrida com {n} sacos",
  'achd.goldBags': "Pegue {n} sacos de ouro no total",
  'tour.nameDone': "Pronto",
  'tour.finish': "Bora jogar!",
  'nyx.stake': "Esta é sua aposta: o que vai na sua bolsa. No treino é dinheiro de mentira, nada a perder. Vamos jogar por um dólar!",
  'nyx.retry': "Ah, você caiu! Acontece, o treino é grátis! Toque em Jogar de novo. Desta vez pegue um pouco de saque e corra para uma saída verde!",
  'nyx.resultWon': "Você saiu! Você venceu! Eu sabia que conseguia! O dinheiro do treino é só por diversão. Toque em Mesas e eu te mostro a loja!",
  'nyx.shopGo': "Agora toque na Loja!",
  'nyx.shopCase': "Bem-vindo à loja! No treino é só uma demonstração, nada é cobrado. Toque em Demo nesta bolsa e veja ela abrir!",
  'nyx.shopEquip': "Olha o que saiu! Online, com seus $ da loja, seria seu. Toque em Fechar!",
  'nyx.bye': "É isso! Você já sabe jogar, vencer e comprar. Vai lá, corredor! Pode me chamar quando quiser nas Configurações.",
  'hud.headshot': "TIRO NA CABEÇA",
  'inv.open': "Abrir",
  'bp.later': "Depois",
  'ach.sharpshooter': "Atirador certeiro",
  'ach.headhunter': "Caçador de cabeças",
  'achd.headshots': "Acerte {n} tiros na cabeça",
  'hud.demoted': "Morte: volta para {w}",
  'hud.crit': "CRÍTICO",
  'hud.roundStart': "Rodada {n} de {of}",
  'hud.roundWon': "Rodada {n} é sua!",
  'hud.roundLost': "Rodada {n} perdida",
  'hud.roundDraw': "Rodada {n}: empate",
  'hud.roundTo': "Rodada {n} vai para {name}",
  'hud.roundNext': "Próxima rodada em {s} s",
  'hud.roundScore': "Rodada {n}/{of} · {a} : {b}",
  'hud.roundDown': "Caiu. Volta na próxima rodada",
  'mc.rounds': "{w} de {n} rodadas",
  'hud.midBossWave': "ONDA 10 · UM CHEFE PULA A CERCA",
  'hud.midBossDown': "Chefe abatido! Faltam dez ondas",
  'ach.last_stand': "Última resistência",
  'gl.upTurret': "Torreta melhorada: nível {lv}",
  'gl.upMine': "Mina laser melhorada: {lv} feixes",
  'gl.upHint': "Espaço: {what} → nível {lv} · {c} CR",
  'gl.upHintTouch': "⬆ {what} → nível {lv} · {c} CR",
  'gl.no.max': "Já está no nível máximo",
  'gl.no.near': "Fique perto da sua torreta ou mina",
  'nav.invite': "Convidar",
  'ref.title': "Convide amigos",
  'ref.lead': "Traga amigos com seu link. Por {d} dias você recebe {p}% da taxa da casa em cada aposta deles, como $ da loja.",
  'ref.yourCode': "Seu código",
  'ref.link': "Seu link de convite",
  'ref.copy': "Copiar",
  'ref.share': "Compartilhar",
  'ref.copied': "Link copiado",
  'ref.shareText': "Vem fazer raid comigo no DARK BAGS. Meu código: {c}",
  'ref.invited': "Convidados",
  'ref.active': "Jogaram uma partida",
  'ref.earned': "Você ganhou",
  'ref.how': "Como funciona",
  'ref.step1': "Seu amigo abre seu link (ou digita seu código) antes da primeira partida",
  'ref.step2': "Depois da primeira partida com aposta ele recebe uma bolsa de boas-vindas",
  'ref.step3': "Cada aposta dele te rende {p}% da taxa da casa por {d} dias, como $ da loja",
  'ref.step4': "Quando ele terminar {m} partidas você ganha uma bolsa bônus",
  'ref.fair': "Jogo limpo: contas na mesma rede ou dispositivo que o seu não contam, há um limite diário e trapaça anula todas as recompensas.",
  'ref.by': "Você entrou com o código {c}",
  'ref.have': "Tem um código de um amigo?",
  'ref.apply': "Aplicar",
  'ref.online': "Convites funcionam no jogo online. Ative em Configurações.",
  'ref.signin': "Entre para pegar seu link de convite.",
  'ref.claimedToast': "Código aplicado: sua bolsa de boas-vindas chega após a primeira partida",
  'ref.err.already': "Você já tem quem te convidou",
  'ref.err.unknown': "Esse código não existe",
  'ref.err.self': "Você não pode se convidar",
  'ref.err.late': "Códigos só valem antes da primeira partida",
  'ref.err.linked': "Esse código é da sua própria rede ou dispositivo",
  'ref.err.busy': "Esse jogador atingiu o limite de hoje. Tente amanhã",
  'err.guard_seat': "Outra conta da sua rede ou dispositivo já está nesta mesa",
  'err.guard_new': "Contas novas demais da sua rede hoje. Volte amanhã",
  'err.guard_faucet': "Sua rede já recebeu os tokens de teste de hoje",
  'res.practiceNoXp': "O treino é grátis: sem XP nem recompensas. Jogue online para subir de rank.",
  'online.only': "Só online. O treino é grátis, então não conta para o passe nem para o ranking. Mude para Online na página Jogar.",
  'err.online_only': "Isso só funciona online",
  'tour.skip': "Pular tutorial",
  'tour.skipped': "Tutorial pulado. Você pode chamar a Nyx de novo em Configurações.",
  'shop.demo': "Demo",
  'shop.demoNote': "Uma demonstração: nada foi cobrado nem dado. Online você abre bolsas com $ da loja e fica com o que sair.",
  'acct.signin': "Entrar",
  'acct.copy': "Copiar endereço",
  'acct.explorer': "Explorador",
  'acct.inWallet': "Na carteira",
  'acct.inGame': "No jogo",
  'acct.deposit': "Depositar",
  'acct.withdraw': "Sacar",
  'acct.cartridge': "Abrir carteira Cartridge",
  'acct.signout': "Sair",
  'acct.copied': "Endereço copiado",
  'br.tab': "Comprar e pontes",
  'br.buy': "Comprar com cartão",
  'br.buySub': "Cartão, Apple Pay ou transferência, direto na sua carteira Starknet",
  'br.intro': "Traga moedas para a Starknet: compre com cartão ou faça a ponte de outra rede no site da própria ponte. Elas chegam na sua carteira Starknet; depois Depositar (em privado, se a carteira permitir) as leva para o jogo.",
  'br.yourAddr': "Seu endereço Starknet:",
  'br.in': "Para Starknet",
  'br.out': "De Starknet",
  'br.fromNet': "Da rede",
  'br.toNet': "Para a rede",
  'br.youSend': "Você envia",
  'br.youGet': "Você recebe",
  'br.amount': "Valor",
  'br.refund': "Seu endereço em {c} (para reembolso)",
  'br.refundPh': "Para onde volta se a troca falhar",
  'br.recipient': "Endereço em {c} que recebe",
  'br.recipientPh': "O endereço de recebimento nessa rede",
  'br.landsIn': "Chega na sua carteira Starknet {a}; depois Depositar leva ao jogo.",
  'br.fromWallet': "Enviado da sua carteira Starknet {a}.",
  'br.fee': "Inclui nossa taxa de {p}%.",
  'br.getAddr': "Obter endereço de depósito",
  'br.send': "Enviar da minha carteira",
  'br.estimate': "Você recebe cerca de {a} ({u}), em ~{s} s",
  'br.needAmount': "Digite um valor.",
  'br.needRefund': "Digite seu endereço na rede de origem, para reembolso.",
  'br.needRecipient': "Digite o endereço de recebimento.",
  'br.sent': "Enviado. A ponte cuida do resto.",
  'br.sendExactly': "Envie exatamente {a} em {c} para este endereço:",
  'br.memo': "Memo (obrigatório)",
  'br.copyMemo': "Copiar memo",
  'br.outSent': "{a} enviado à ponte para {c}.",
  'br.youGetAbout': "Você recebe cerca de {a} em {c}.",
  'br.deadline': "Reembolso se não concluir até {t}.",
  'br.toGame': "Depositar no jogo",
  'br.new': "Nova ponte",
  'br.others': "Outras pontes",
  'br.othersNote': "Abre o site da ponte; sem taxa nossa lá. Envie para seu endereço Starknet do painel da carteira.",
  'br.lsSub': "Mais de 40 redes e corretoras",
  'br.avnuSub': "Trocar tokens na Starknet",
  'br.mainnetOnly': "As pontes funcionam com moedas reais na mainnet da Starknet. Na testnet, use as abaixo.",
  'br.s.wait': "Aguardando seu depósito",
  'br.s.seen': "Depósito visto, confirmando",
  'br.s.partial': "Depósito pequeno demais; envie o resto ou aguarde o reembolso",
  'br.s.proc': "Transferindo…",
  'br.s.ok': "Pronto: está na sua carteira",
  'br.s.refund': "Reembolsado",
  'br.s.fail': "Falhou; nada foi cobrado",
  'nav.mail': "Correio",
  'mail.claim': "Resgatar",
  'mail.claimed': "Recebido: {g}",
  'mail.creditNote': "$ da loja: gaste na loja. Não podem ser sacados nem vendidos.",
  'mail.empty': "Nenhuma mensagem ainda.",
  'mail.g.credit': "{v} em $ da loja",
  'mail.g.spin': "{n} giro(s) da roleta",
  'mail.g.trial': "{n} por 1 h",
  'mail.newToast': "Correio novo!",
  'mail.noSpins': "Sem giros",
  'mail.pick': "Escolha uma carta para ler.",
  'mail.signin': "Entre para receber correio.",
  'mail.spinBtn': "Girar a roleta ({n})",
  'mail.spinNow': "Girar!",
  'mail.taken': "Recebido",
  'mail.welcomeToast': "Bônus de boas-vindas! Você já usa o título Fundador e há um giro da roleta no Correio.",
  'mail.wheel': "Roleta da sorte",
  'mail.wheelNote': "Uma skin de corredor por 1 h, uma skin de arma por 1 h ou até $2 em $ da loja.",
  'mail.trial72': "Seu por 1 hora. Equipe no inventário.",
  'mail.welcome.t': "♛ Bem-vindo, Fundador!",
  'mail.welcome.b': "Você é um dos primeiros a apoiar o DARK BAGS com uma recarga real, e não vamos esquecer. Obrigado!\n\nA partir de hoje você usa o título premium Fundador em ouro vivo: só quem acreditou no jogo desde o início terá.\n\nSeu presente está abaixo: um giro da roleta da sorte. Boa sorte, nos vemos no escuro.\n\nEquipe DARK BAGS",
  'ach.founder': "Fundador",
  'achd.deposits': "Faça sua primeira recarga",
  'r.premium': "Premium",
  'mail.jackpot.t': "🎰 Jackpot da roleta!",
  'mail.jackpot.b': "O pote da sorte foi seu: as moedas estão a caminho (ou já no seu saldo do jogo). Parabéns!",
  'fw.bank': "Pote da sorte",
  'fw.coin': "Pagar com",
  'fw.inBalance': "Creditado no saldo do jogo: saque quando quiser.",
  'fw.jackpot': "JACKPOT",
  'fw.kicker': "$0.05 por giro",
  'fw.lead': "18 tipos de prêmio: skins de 1 h, skins para sempre, estilo, caixas presente, $ da loja, XP do passe, boosts de XP, giros extras. Cada giro pago enche o banco: quem atinge a marca leva tudo em moedas reais.",
  'fw.next': "paga em {m}",
  'fw.noCoins': "Deposite qualquer moeda para girar.",
  'fw.odds': "O que pode sair",
  'fw.real': "Skin real ({r})",
  'fw.realKeep': "Sua para sempre.",
  'fw.rules': "30% de cada giro vai para o pote. Quando ele atinge a marca ($0.50, depois $1, $1.50, $2… até $5), o giro que a atinge leva o pote todo em USDC (ou USDT, ou STRK). Skins de teste duram 1 hora. Itens da loja não podem ser sacados nem vendidos.",
  'fw.sentChain': "Enviado para sua carteira na Starknet.",
  'fw.share': "Compartilhar o prêmio",
  'fw.spin': "Girar",
  'fw.title': "Roleta da sorte",
  'fw.trial': "Skin de corredor 1 h",
  'fw.wtrial': "Skin de arma 1 h",
  'coin.import': "Importar moeda",
  'coin.search': "Buscar: símbolo, nome ou endereço",
  'coin.added': "adicionada",
  'coin.add': "Adicionar",
  'coin.none': "Nada encontrado",
  'coin.note': "Qualquer moeda Starknet da lista verificada da AVNU ou da Ekubo. Depois de adicionada, deposite e aposte como qualquer outra; os ganhos voltam nela.",
  'coin.done': "{s} adicionada: deposite e escolha para apostar.",
  'coin.noPrice': "{s} adicionada; o preço aparece em um minuto.",
};
