export default {
  'lobby.tagline': 'Aposte. Saqueie. Saia antes da tempestade. <b>Ninguém vê o que tem na sua bolsa.</b>',
  'lobby.namePh': 'Nome do seu corredor',
  'lobby.locker': 'Armário · skins · bolsas',
  'lobby.refill': 'Recarregar moedas de teste',
  'lobby.online': 'Online',
  'lobby.practice': 'Treino contra bots',
  'lobby.stakePer': 'Aposta por incursão',
  'lobby.stakeWith': 'Aposte com <span class="fine">qualquer moeda · mostrado em $ · os ganhos voltam na mesma moeda</span>',
  'lobby.play': 'Jogar · aposta {s}',
  'lobby.signIn': 'Entre para jogar',
  'lobby.how': 'Como jogar',
  'lobby.gore': '<b>Modo 18+.</b> Membros voam e o sangue fica no chão.',
  'lobby.fine': 'O treino roda no seu navegador. Todo o dinheiro aqui é de brincadeira.',
  'how.1': '<b>Aposte e fique pronto.</b> Todos entram juntos com uma faca e 100 de vida. Metade da aposta vai na sua bolsa, a outra metade vira saque espalhado.',
  'how.2': '<b>Pegue o saque laranja.</b> Ele vai para a sua bolsa. Abates melhoram sua arma: faca → pistola → escopeta → submetralhadora → fuzil → sniper a laser.',
  'how.3': '<b>Saia vivo.</b> Fique 3 segundos numa saída verde antes que a tempestade a feche. A bolsa inteira é sua. Morra e ela cai para outro.',
  'how.keys': "<kbd>WASD</kbd> mover · <kbd>mouse</kbd> mirar · <kbd>clique</kbd> atacar · <kbd>Espaço</kbd> esquiva · <kbd>Q</kbd> disfarçar o tamanho da bolsa · <kbd>M</kbd> som · <kbd>N</kbd> música",
  'how.fine': 'Cada incursão e cada conquista dão XP de patente. Cada promoção empresta uma skin nova por 3 dias.',
  'net.practice': 'Só você e os bots, offline.',
  'net.open': 'Conectado. Humanos e bots dividem cada incursão.',
  'net.connecting': 'Conectando ao servidor…',
  'net.down': 'Servidor indisponível. Tentando de novo… O treino funciona offline.',
  'net.lost': 'Conexão perdida. De volta às mesas.',
  'q.pick': 'Escolha uma moeda para apostar.',
  'q.short': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda ou uma aposta menor.',
  'q.shortDeposit': '{c} insuficiente para uma aposta de {s}. Escolha outra moeda, uma aposta menor ou deposite.',
  'q.stable': 'Você aposta {s} em {c}. Saia vivo e fique com tudo o que carrega.',
  'q.coin': 'Você aposta {a} = {s} ao preço de hoje. Os ganhos voltam em {c} na mesma taxa.',
  'tb.live': 'Incursão rolando · {t}',
  'tb.ready': '{n} prontos · {s}s',
  'tb.waiting': '{n} esperando',
  'tb.golden': 'Próxima: incursão dourada',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Ajustes do treino',
  'pcfg.difficulty': 'Bots',
  'pcfg.easy': 'Fácil',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Difícil',
  'pcfg.runners': 'Corredores na incursão',
  'pcfg.time': 'Duração da incursão',
  'rk.max': 'patente máxima',
  'rk.toNext': '{x} XP até a patente {r}',
  'rk.of': 'Patente {r} de 90',
  'rk.rank': 'Patente',
  'rk.up': 'Promoção',
  'rk.xp': 'XP de patente',
  'xp.Raid': 'Incursão',
  'xp.kills': '{n} abates',
  'xp.Damage': 'Dano',
  'xp.Time alive': 'Tempo vivo',
  'xp.First blood': 'Primeiro sangue',
  'xp.Double kill': 'Abate duplo',
  'xp.Triple kill': 'Abate triplo',
  'xp.Rampage': 'Massacre',
  'xp.Godlike': 'Divino',
  'xp.Full arsenal': 'Arsenal completo',
  'xp.Extracted': 'Extração',
  'xp.Profit': 'Lucro',
  'xp.Practice ×0.5': 'Treino ×0.5',
  'rk.newRank': "Nova patente",
  'rw.continue': "Continuar",
  'rw.title': 'Recompensa de promoção',
  'rw.trial': 'seu por 72 horas',
  'rw.try': 'Experimentar',
  'rw.share': 'Compartilhar promoção',
  'prep.raid': 'Incursão {n} · aposta {s}',
  'prep.readyUp': 'Pronto?',
  'prep.first': 'A contagem começa quando o primeiro corredor ficar pronto.',
  'prep.live': 'Há uma incursão rolando. Fique pronto e entre na próxima com todos.',
  'prep.over': 'Incursão encerrada. A sala abre em instantes.',
  'prep.many': 'Aqui todo mundo começa com faca. Bots entram nos últimos segundos.',
  'prep.bots': 'Bots preenchem as vagas nos últimos segundos.',
  'prep.open': 'livre',
  'prep.pot': 'Pote',
  'prep.cancel': 'Cancelar · reembolsar {v}',
  'prep.ready': 'Pronto · aposta {v}',
  'prep.back': 'Voltar às mesas',
  'hud.bagPrivate': 'Sua bolsa · privada',
  'hud.golden': 'Incursão dourada',
  'hud.goldenStart': 'Incursão dourada · saque do jackpot lá dentro',
  'hud.start': 'Faca na mão · pegue o laranja · ache uma saída',
  'hud.bagOpened': 'Bolsa aberta · +{v}',
  'hud.arsenal': "Arsenal completo · de volta à pistola ★",
  'hud.unlocked': '{w} desbloqueada',
  'hud.pnl': '{d} contra a aposta de {s}',
  'hud.alive': '{n} lá dentro',
  'hud.next': 'Próxima: {w}',
  'hud.final': 'Círculo final · última saída',
  'hud.closing': 'Tempestade fechando · {t}',
  'hud.stormIn': 'A tempestade avança em {t}',
  'hud.dash': 'Esquiva',
  'hud.bagLook': 'Aparência da bolsa',
  'hud.extracting': 'Extraindo',
  'hud.holdStill': 'Fique parado. Um tiro zera o progresso.',
  'hud.sound': 'Som',
  'hud.music': 'Música',
  'bluff.0': 'pequena',
  'bluff.1': 'média',
  'bluff.2': 'gorda',
  'touch.move': 'mover',
  'touch.aim': 'mirar · atirar',
  'touch.bag': 'Bolsa',
  'w.Knife': 'Faca',
  'w.Pistol': 'Pistola',
  'w.Shotgun': 'Escopeta',
  'w.SMG': 'Submetralhadora',
  'w.Rifle': 'Fuzil',
  'w.Laser sniper': 'Sniper a laser',
  'w.Hand Cannon': "Canhão de mão",
  'w.Auto Shotgun': "Escopeta automática",
  'w.PDW': "PDW",
  'w.Carbine': "Carabina",
  'w.Scout': "Batedor",
  'w.Machine Gun': "Metralhadora",
  'w.Magnum Sniper': "Sniper Magnum",
  'hud.reloading': "Recarregando",
  'streak.1': 'Primeiro sangue',
  'streak.2': 'Abate duplo',
  'streak.3': 'Abate triplo',
  'streak.4': 'Massacre',
  'streak.5': 'Divino',
  'streak.you1': 'Você tirou o primeiro sangue',
  'feed.storm': 'A tempestade te pegou',
  'feed.droppedYou': '{name} te derrubou',
  'coach.storm': 'Você está na tempestade · volte para o círculo',
  'coach.touch': "Polegar esquerdo move · segure Atirar: mira sozinho no inimigo mais próximo",
  'coach.keys': 'WASD para mover · mouse para mirar · clique para atacar',
  'coach.exit': 'Hora de sair · fique 3 segundos numa SAÍDA verde · as setas na borda mostram o caminho',
  'coach.loot': 'Pegue o saque laranja · ele vai para a sua bolsa',
  'coach.kills': 'Abates melhoram sua arma · Espaço para esquivar',
  'coach.killsTouch': 'Abates melhoram sua arma · toque em Esquiva',
  'spect.watching': 'Assistindo {name} · ◀ ▶ para trocar',
  'spect.down': 'Você caiu',
  'spect.results': 'Resultados',
  'res.extracted': 'Extraído',
  'res.storm': 'Engolido pela tempestade',
  'res.dropped': 'Derrubado',
  'res.sealed': 'Preso lá dentro',
  'res.inside': '{k} abates · {t} lá dentro',
  'res.out': 'Saiu com {p} numa aposta de {s}: {d}.',
  'res.paid': 'Pago {v} na taxa de entrada.',
  'res.killer': '{n} está com a sua bolsa agora. Tinha {v}, e só vocês dois vão saber.',
  'res.inStorm': 'Sua bolsa, {v}, está na tempestade para quem tiver coragem.',
  'res.sealedText': 'A incursão fechou com você lá dentro. Seus {v} foram para o saque da próxima.',
  'res.again': 'Jogar de novo',
  'res.tables': 'Mesas',
  'res.share': 'Compartilhar',
  'share.title': 'Compartilhar',
  'share.x': 'Postar no 𝕏',
  'share.copy': 'Copiar imagem',
  'share.save': 'Salvar PNG',
  'share.close': 'Fechar',
  'lk.title': 'Armário',
  'lk.outfits': 'Visuais',
  'lk.shop': 'Loja',
  'lk.bags': 'Bolsas da sorte',
  'lk.sortDesc': "Mais raros primeiro ↓",
  'lk.sortAsc': "Mais comuns primeiro ↑",
  'lk.allGuns': "Todas as armas",
  'lk.takeOff': "Tirar",
  'lk.empty': "Nada aqui ainda: bolsas e caixas da loja enchem sua coleção.",
  'lk.emptyTurrets': "Ainda sem skins de torreta: elas vêm do passe de batalha.",
  'lk.pickSkin': "Toque numa skin para ver e depois equipe.",
  'lk.all': 'Todos',
  'lk.owned': 'Meus',
  'lk.him': 'Ele',
  'lk.her': 'Ela',
  'lk.shopUsd': '$ da loja',
  'lk.shopNote': 'Recarregue $ da loja com USDC ou USDT (pacotes maiores dão bônus). $ da loja só vale aqui e não pode ser sacado. Faltou? A diferença sai dos seus USDC/USDT.',
  'lk.bagsNote': 'Chances exatas, sorteadas no servidor. Sem repetidos até completar uma raridade, e um repetido devolve 10% do preço em $ da loja. Garantia: Épico+ em 15 aberturas e Lendário+ em 60.',
  'lk.topupFrom': '+ {v} USDC/USDT para recarregar',
  'lk.collected': '{a} / {b} coletados',
  'lk.equipped': 'Equipado',
  'lk.equip': 'Equipar',
  'lk.buy': 'Comprar',
  'lk.trialLeft': 'Teste · faltam {t}',
  'lk.trialHow': 'Teste de promoção: seu por mais {t}. Compre para ficar com ele.',
  'lk.free': 'Grátis para todos.',
  'lk.inCollection': 'Na sua coleção.',
  'lk.buyOrBag': 'Compre aqui ou tente a sorte com uma bolsa.',
  'lk.tryingOn': 'Experimentando.',
  'lk.bonus': '+{n}% de bônus',
  'lk.pay': 'paga {v}',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Épico+ em',
  'lk.legIn': 'Lendário+ em',
  'lk.openFree': 'Abrir · grátis',
  'lk.buyOpen': 'Comprar e abrir',
  'lk.pityDrop': 'garantia',
  'lk.dup': 'Já é seu · {v} de volta',
  'lk.new': '<b>Novo</b> na sua coleção',
  'lk.jackpotIs': 'o jackpot é {r}',
  'lk.showOff': 'Exibir no X',
  'lk.postMiss': 'Postar o azar no X',
  'lk.another': 'Abrir outra',
  'lk.free1': 'grátis',
  'lk.back': 'Voltar ao armário',
  'lk.yours': '{n} é seu.',
  'r.common': 'Comum',
  'r.rare': 'Raro',
  'r.epic': 'Épico',
  'r.legendary': 'Lendário',
  'r.mythic': 'Mítico',
  'r.exotic': 'Exótico',
  'ach.title': 'Conquistas',
  'ach.button': 'Conquistas',
  'ach.intro': 'Cada uma dá XP de patente uma vez e libera seu nome como título para usar.',
  'ach.wear': 'Usar título',
  'ach.worn': 'Em uso',
  'ach.wearing': 'Título:',
  'ach.takeOff': 'tirar',
  'ach.noTitle': 'Sem título',
  'ach.unlocked': 'Conquista liberada',
  'ach.seeAll': 'Todas as conquistas',
  'achd.raids': 'Jogue {n} incursões',
  'achd.extracts': 'Extraia-se {n} vezes',
  'achd.kills': 'Faça {n} abates',
  'achd.bestKills': '{n} abates numa incursão',
  'achd.bestMulti': 'Um abate múltiplo ×{n}',
  'achd.prestige': 'Complete o arsenal {n} vezes',
  'achd.firstBloods': 'Tire o primeiro sangue {n} vezes',
  'achd.secs': 'Passe {n} h dentro de incursões',
  'achd.bestReturn': 'Saia com {n}× a sua aposta',
  'achd.golden': 'Extraia-se de uma incursão dourada',
  'achd.lastExit': 'Saia pela última saída',
  'achd.pacifist': 'Extraia-se sem nenhum abate',
  'achd.rank': 'Chegue à patente {n}',
  'achd.outfits': 'Tenha {n} visuais',
  'ach.gunslinger': "Pistoleiro",
  'ach.close_quarters': "Combate próximo",
  'ach.spray_and_pray': "Rajada cega",
  'ach.rifleman': "Fuzileiro",
  'ach.marksman': "Atirador",
  'ach.deadeye': "Olho de águia",
  'ach.blade_dancer': "Dançarino da lâmina",
  'ach.shadow_blade': "Lâmina sombria",
  'ach.deathmatch_king': "Rei do mata-mata",
  'ach.duelist': "Duelista",
  'ach.squad_goals': "Espírito de equipe",
  'ach.one_shot_one_kill': "Um tiro, uma baixa",
  'ach.specialist': "Especialista",
  'ach.engineer': "Engenheiro",
  'ach.ranked_debut': "Estreia ranqueada",
  'ach.ranked_grinder': "Esforçado ranqueado",
  'ach.ranked_victor': "Vencedor ranqueado",
  'ach.gold_league': "Liga Ouro",
  'ach.diamond_league': "Liga Diamante",
  'ach.neon_legend': "Lenda Neon",
  'ach.unboxer': "Desempacotador",
  'ach.case_hunter': "Caçador de caixas",
  'ach.case_lord': "Senhor das caixas",
  'ach.armory': "Arsenal",
  'ach.arsenal_baron': "Barão do arsenal",
  'ach.pass_holder': "Dono do passe",
  'ach.pass_maxed': "Passe completo",
  'ach.neon_bearer': "Portador do neon",
  'ach.by_a_thread': "Por um fio",
  'ach.untouchable': "Intocável",
  'ach.ghost_walker': "Passo fantasma",
  'ach.one_tap': "Um toque",
  'achd.kHandgun': "Faça {n} abates com pistolas",
  'achd.kShotgun': "Faça {n} abates com escopetas",
  'achd.kSmg': "Faça {n} abates com submetralhadoras",
  'achd.kRifle': "Faça {n} abates com rifles e metralhadoras",
  'achd.kSniper': "Faça {n} abates com snipers",
  'achd.kKnife': "Faça {n} abates com faca",
  'achd.dmWins': "Vença {n} mata-matas",
  'achd.duelWins': "Vença {n} duelos",
  'achd.teamWins': "Vença {n} partidas em equipe",
  'achd.hcWins': "Vença {n} partidas hardcore",
  'achd.weaponWins': "Vença {n} partidas de uma arma",
  'achd.turretKills': "Faça {n} abates com torretas em Armas + Lasers",
  'achd.rankedGames': "Jogue {n} ranqueadas",
  'achd.rankedWins': "Vença {n} ranqueadas",
  'achd.bestDiv': "Chegue a {n} na ranqueada",
  'achd.opened': "Abra {n} caixas e bolsas",
  'achd.wskins': "Tenha {n} skins de arma",
  'achd.passTier': "Chegue ao nível {n} do passe",
  'achd.stitles': "Ganhe um título da temporada",
  'achd.clutch': "Saia com 10 de vida ou menos",
  'achd.flawless': "Saia após 2+ minutos sem levar um tiro",
  'achd.ninjaWin': "Vença um modo de bolão sem nenhum abate",
  'achd.oneShots': "Leve {n} corredores da vida cheia a zero com um golpe",
  'ach.secret': "Secreto",
  'ach.secretDesc': "Continue jogando: ele se revela quando você conquistar.",
  'r.mystery': "Mistério",
  'ach.rookie': 'Recruta',
  'ach.regular': 'Frequentador',
  'ach.veteran': 'Veterano',
  'ach.lifer': 'Carreira',
  'ach.eternal': 'Eterno',
  'ach.escape_artist': 'Mestre da fuga',
  'ach.ghost': 'Fantasma',
  'ach.smuggler': 'Contrabandista',
  'ach.phantom': 'Espectro',
  'ach.first_kill': 'Primeiro abate',
  'ach.hunter': 'Caçador',
  'ach.butcher': 'Açougueiro',
  'ach.reaper': 'Ceifador',
  'ach.apex': 'Predador',
  'ach.rampage': 'Massacre',
  'ach.one_man_army': 'Exército de um',
  'ach.double_tap': 'Toque duplo',
  'ach.triple_threat': 'Ameaça tripla',
  'ach.godlike': 'Divino',
  'ach.full_arsenal': 'Arsenal completo',
  'ach.arsenal_master': 'Mestre do arsenal',
  'ach.first_blood': 'Primeiro sangue',
  'ach.opener': 'O abridor',
  'ach.night_shift': 'Turno da noite',
  'ach.insomniac': 'Insone',
  'ach.double_up': 'Dobrou',
  'ach.big_bag': 'Bolsa cheia',
  'ach.gold_rush': 'Corrida do ouro',
  'ach.last_one_out': 'O último a sair',
  'ach.pacifist': 'Pacifista',
  'ach.seasoned': 'Calejado',
  'ach.officer': 'Oficial',
  'ach.commander': 'Comandante',
  'ach.legend': 'Lenda',
  'ach.collector': 'Colecionador',
  'ach.curator': 'Curador',
  'ach.hoarder': 'Acumulador',
  'intro.tag': "Aposte. Saqueie. Saia.",
  'intro.go': "Entrar",
  'intro.fonts': "Afiando facas…",
  'intro.world': "Pintando a escuridão…",
  'intro.connect': "Procurando incursão…",
  'intro.profile': "Arrumando sua bolsa…",
  'intro.ready': "Pronto",
  'tb.wallet': "Carteira",
  'tb.shop': "$ da loja",
  'nav.play': "Jogar",
  'nav.shop': "Loja",
  'nav.inventory': "Inventário",
  'nav.swap': "Troca",
  'nav.chat': "Chat",
  'nav.achievements': "Conquistas",
  'nav.pass': "Passe",
  'bp.season': "Temporada {n}",
  'bp.ends': "termina em {d}d {h}h",
  'bp.tier': "Nível {n}/{m}",
  'bp.xp': "{a}/{b} XP para o próximo nível",
  'bp.maxed': "Todos os níveis concluídos",
  'bp.how': "Cada incursão enche o passe com o mesmo XP da sua patente.",
  'bp.free': "Grátis",
  'bp.premium': "Premium",
  'bp.buy': "Passe premium · {v}",
  'bp.owned': "Premium ativo",
  'bp.perks': "Os 50 níveis de recompensas: armaduras Senhor da Guerra e Ápice, 2 skins de torreta, 5 skins de arma da temporada, caixas e $.",
  'bp.claim': "Resgatar",
  'bp.claimAll': "Resgatar tudo ({n})",
  'bp.claimed': "Resgatado",
  'bp.limited': "Só nesta temporada",
  'bp.turrets': "Skins de torreta",
  'bp.turretsNote': "Suas torretas em Armas + Lasers.",
  'bp.equip': "Equipar",
  'bp.equipped': "Equipado",
  'bp.none': "Padrão",
  'bp.up': "Passe de batalha: nível {n}!",
  'bp.got': "Resgatado: {x}",
  'bp.credit': "+{v} da loja",
  'mode.ranked': "Ranqueada",
  'mode.ranked.d': "Battle royale pela sua classificação da temporada. Do Bronze à Lenda Neon; as melhores posições ganham um giro bônus.",
  'nav.ranked': "Ranqueada",
  'rd.title': "Ranqueada · Temporada {n}",
  'rd.pos': "#{n} de {m}",
  'rd.unranked': "Jogue uma partida ranqueada para entrar na tabela.",
  'rd.play': "Jogar ranqueada",
  'rd.games': "Partidas",
  'rd.wins': "Vitórias",
  'rd.top3': "Top 3",
  'rd.kills': "Abates",
  'rd.winrate': "Taxa de vitória",
  'rd.player': "Jogador",
  'rd.div': "Divisão",
  'rd.div.bronze': "Bronze",
  'rd.div.silver': "Prata",
  'rd.div.gold': "Ouro",
  'rd.div.platinum': "Platina",
  'rd.div.diamond': "Diamante",
  'rd.div.master': "Mestre",
  'rd.div.legend': "Lenda Neon",
  'rd.titles': "Títulos da temporada",
  'rd.titlesNote': "Saem do giro bônus da ranqueada. Brilham em neon acima do seu nome e dão XP extra até o fim da temporada.",
  'rd.wear': "Usar",
  'rd.off': "Tirar",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "temporada encerrada",
  'rd.board': "Tabela da temporada",
  'rd.empty': "Ninguém jogou ranqueada nesta temporada ainda. Seja o primeiro.",
  'rd.place': "Posição #{p} de {n}",
  'rd.promoted': "promovido!",
  'rd.demoted': "rebaixado",
  'rd.practice': "Treino: sua classificação não muda.",
  'rd.spin': "Giro bônus",
  'rd.spinWhy': "pela posição #{p}",
  'rd.won': "Você ganhou:",
  'rd.wornNow': "Seu novo título já brilha acima de você.",
  'st.contender': "Desafiante",
  'st.elite': "Elite",
  'st.champion': "Campeão",
  'xp.Season title': "Título da temporada",
  'news.title': "Novidades",
  'news.ok': "Entendi",
  'news.note': "Cada atualização, com data e hora.",
  'news.open': "Abrir",
  'stake.own': "Sua aposta",
  'stake.range': "Aposta de $0,10 a $10.000",
  'nav.settings': "Ajustes",
  'modes.title': "Modo de jogo",
  'kind.raid': "extração",
  'kind.br': "o vencedor leva o pote",
  'kind.team': "pote do time",
  'mode.raid': "Incursão",
  'mode.raid.d': "Saqueie, lute e saia por uma saída. Fique com o que carrega.",
  'mode.br': "Battle Royale",
  'mode.br.d': "Até 20 corredores. O último de pé leva o pote inteiro.",
  'mode.duel': "Duelo",
  'mode.duel.d': "Um contra um. O vencedor leva as duas apostas.",
  'mode.knives': "Só facas",
  'mode.knives.d': "Só lâminas a incursão toda. Vence o último de pé.",
  'mode.pistols': "Só pistolas",
  'mode.pistols.d': "Só pistolas. Vence o último de pé.",
  'mode.shotguns': "Só escopetas",
  'mode.shotguns.d': "De perto e barulhento. Vence o último de pé.",
  'mode.rifles': "Só fuzis",
  'mode.rifles.d': "Tiroteios a média distância. Vence o último de pé.",
  'mode.snipers': "Só snipers",
  'mode.snipers.d': "Miras laser por toda parte. Vence o último de pé.",
  'mode.team2': "Times 2 x 2",
  'mode.team2.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'mode.team4': "Times 4 x 4",
  'mode.team4.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'mode.team8': "Times 8 x 8",
  'mode.team8.d': "Cada aposta aumenta um pote. O último time de pé divide.",
  'hud.pot': "Pote",
  'hud.left': "Restam {n} · aposta {s}",
  'hud.teamsLeft': "Restam {n} times · aposta {s}",
  'hud.startPot': "O último de pé leva o pote",
  'hud.startTeam': "Fique com seu time · elimine o outro",
  'hud.goldenPot': "Incursão dourada · jackpot somado ao pote",
  'coach.pot': "Sem saídas aqui · fique no círculo · vence o último de pé",
  'coach.team': "Nomes verdes são seu time · vermelhos são o inimigo",
  'warn.exit30': "30s · chegue a uma saída aberta",
  'warn.exit10': "10s · extraia ou perca tudo",
  'warn.pot30': "30s · a tempestade se fecha",
  'warn.pot10': "10s · vence quem tiver mais vivos",
  'storm.final': "Colapso final · só a última saída",
  'storm.finalPot': "Colapso final · nenhum lugar para se esconder",
  'storm.closing': "A tempestade está chegando",
  'storm.in5': "A tempestade avança em 5s",
  'feed.youDropped': "Você derrubou {name}",
  'feed.stormTook': "{name} foi engolido pela tempestade",
  'feed.dropped': "{a} derrubou {b}",
  'feed.down': "{name} caiu",
  'feed.extracted': "{name} se extraiu",
  'feed.exitClosed': "A saída {name} fechou",
  'spect.settling': "Seu resultado chega quando a incursão fechar.",
  'res.victory': "Vitória",
  'res.teamWon': "Seu time venceu",
  'res.defeated': "Derrota",
  'res.wonText': "Você levou {p} com uma aposta de {s}.",
  'res.lostPot': "O pote ficou com o último de pé.",
  'res.teamLost': "O outro time levou o pote.",
  'xp.Victory': "Vitória",
  'ach.champion': "Campeão",
  'ach.warlord': "Senhor da guerra",
  'achd.wins': "Vença {n} incursões com pote",
  'lk.weapons': "Skins de armas",
  'lk.onlyBags': "Skins só saem das bolsas e caixas da loja.",
  'lk.toShop': "Abrir a loja",
  'lk.toOpen': "{n} para abrir",
  'lk.limited': "Limitado · {n}",
  'lk.minted': "{a} de {b} cunhados",
  'lk.plain': "Padrão",
  'lk.fromBags': "Sai das bolsas de visuais da loja.",
  'lk.fromCrates': "Sai das caixas de armas da loja.",
  'lk.trialHow2': "Teste de promoção: seu por mais {t}.",
  'lk.weaponHow': "Escolha um acabamento seu para equipar. Todos na incursão veem.",
  'fx.glow': "aura",
  'fx.pulse': "aura pulsante",
  'fx.ghost': "espectral",
  'fx.laser': "olhos laser",
  'fx.rainbow': "prismático",
  'fx.fire': "em chamas",
  'fx.gold': "ouro líquido",
  'fx.holo': "holograma",
  'fx.glitch': "glitch",
  'fx.lightning': "raios",
  'fx.galaxy': "galáxia",
  'fx.sparks': "faíscas",
  'fx.frost': "geada",
  'fx.money': "chuva de dinheiro",
  'fx.matrix': "chuva de código",
  'fx.shadow': "fumaça sombria",
  'fx.cape': "capa",
  'box.c-samurai': "Caixa Ciber Samurai",
  'box.c-neon': "Caixa Noites Neon",
  'box.c-arctic': "Caixa Ártica",
  'box.c-inferno': "Caixa Inferno",
  'box.c-crypto': "Caixa Reis Cripto",
  'box.c-toxic': "Caixa Terra Tóxica",
  'box.c-toon': "Caixa Cidade Toon",
  'box.c-knife': "Caixa de facas",
  'box.c-pistol': "Caixa de pistolas",
  'box.c-smg': "Caixa de submetralhadoras",
  'box.c-rifle': "Caixa de rifles",
  'box.c-heavy': "Caixa pesada",
  'box.c-sniper': "Caixa de sniper",
  'box.b-crypto': "Bolsa Memes Cripto",
  'box.b-heroes': "Bolsa Heróis do Multiverso",
  'box.b-monsters': "Bolsa Monstros e Mitos",
  'box.b-cyber': "Bolsa Ciber Rua",
  'box.b-toon': "Bolsa Amigos Toon",
  'shop.g.theme': "Coleções",
  'shop.g.class': "Caixas por classe de arma",
  'shop.g.tier': "Caixas por nível",
  'shop.contents': "Conteúdo · {n} itens",
  'box.street': "Bolsa de rua",
  'box.vault': "Bolsa do cofre",
  'box.golden': "Bolsa dourada",
  'box.elite': "Bolsa elite",
  'box.diamond': "Bolsa de diamante",
  'box.obsidian': "Bolsa de obsidiana",
  'box.royal': "Bolsa real",
  'box.apex': "Bolsa Apex",
  'box.genesis': "Bolsa Gênesis",
  'box.w-scrap': "Caixa de sucata",
  'box.w-armory': "Caixa do arsenal",
  'box.w-brass': "Caixa de latão",
  'box.w-specops': "Caixa de operações especiais",
  'box.w-diamond': "Caixa de diamante",
  'box.w-obsidian': "Caixa de obsidiana",
  'box.w-royal': "Caixa real",
  'box.w-apex': "Caixa Apex",
  'box.w-genesis': "Caixa Gênesis",
  'shop.topup': "Recarregar $ da loja",
  'shop.bags': "Bolsas de visuais",
  'shop.crates': "Caixas de armas",
  'shop.bagsNote': "Visuais para o seu corredor. Nove níveis: quanto mais cara a bolsa, melhores as chances.",
  'shop.cratesNote': "Skins para suas armas e faca, vendidas separadamente dos visuais. Nove níveis.",
  'shop.fair': "Chances exatas, sorteadas no servidor. Garantia: Épico+ em {e} aberturas, Lendário+ em {l}.",
  'shop.odds': "Chances e garantia",
  'shop.qty': "Quantidade",
  'shop.open': "Abrir ×{n}",
  'shop.limited': "Edições limitadas",
  'shop.soldOut': "Esgotado",
  'shop.dup': "Repetido · +{v}",
  'shop.new': "Novo",
  'shop.back': "{v} de volta",
  'shop.equipBest': "Equipar {n}",
  'inv.wallet': "Carteira",
  'inv.deposit': "Depositar · sacar",
  'inv.walletNote': "Tokens reais que a casa guarda para você. Saque quando quiser para o endereço com que entrou.",
  'inv.playNote': "Dinheiro de jogo neste navegador. Recarregue quando quiser.",
  'inv.shopNote': "Comprado com USDC/USDT, gasto só em bolsas e caixas. Não pode ser sacado.",
  'inv.unopened': "Fechadas",
  'inv.collection': "Coleção",
  'inv.opened': "Abertas",
  'inv.career': "Carreira",
  'inv.raids': "Incursões",
  'inv.kills': "Abates",
  'inv.extracts': "Extrações",
  'inv.wins': "Potes ganhos",
  'inv.best': "Melhor incursão (abates)",
  'inv.time': "Tempo lá dentro",
  'swap.game': "Saldo do jogo",
  'swap.gameNote': "Na hora, ao preço atual, taxa de {f}%.",
  'swap.gameOff': "Trocas dentro do jogo estão desligadas neste servidor. Use a troca na carteira abaixo.",
  'swap.from': "Você dá",
  'swap.to': "Você recebe",
  'swap.have': "Você tem",
  'swap.flip': "Inverter",
  'swap.go': "Trocar",
  'swap.short': "Saldo insuficiente",
  'swap.done': "Trocou {a} por {b}.",
  'swap.wallet': "Sua carteira",
  'swap.signIn': "Entre com uma carteira Starknet para trocar lá via AVNU.",
  'swap.needChain': "Trocas via AVNU funcionam com uma carteira Starknet real no modo online.",
  'swap.slippage': "Slippage máx.",
  'swap.quoting': "Buscando a melhor rota…",
  'swap.impact': "impacto no preço {p}%",
  'swap.goAvnu': "Trocar com AVNU",
  'swap.noQuote': "Sem rota para esse par agora.",
  'swap.sent': "Troca enviada: {tx}",
  'swap.walletNote': "A AVNU roteia entre as exchanges da Starknet. Você assina na sua carteira; o jogo nunca guarda esses tokens.",
  'chat.ph': "Diga algo…",
  'chat.send': "Enviar",
  'chat.empty': "Nenhuma mensagem ainda. Diga gm.",
  'chat.online': "Todo o lobby vê isto. Seja gentil.",
  'chat.practice': "O treino é offline: só os bots estão ouvindo.",
  'set.graphics': "Gráficos",
  'set.quality': "Qualidade",
  'set.qualityNote': "Auto reduz os detalhes quando os quadros ficam lentos.",
  'set.auto': "Auto",
  'set.high': "Alta",
  'set.medium': "Média",
  'set.low': "Baixa",
  'set.shake': "Tremor de tela",
  'set.motion': "Animações do menu",
  'set.display': "Exibição",
  'set.skins': "Skins",
  'set.skinsNote': "De quem desenhar visuais e skins de armas.",
  'set.skinsAll': "Todos",
  'set.skinsMine': "Só os meus",
  'set.skinsNone': "Nenhum",
  'set.names': "Nomes sobre os corredores",
  'set.titles': "Títulos sobre os nomes",
  'set.controls': "Controles",
  'set.stick': "Tamanho dos sticks de toque",
  'set.lefty': "Canhoto (toque)",
  'set.leftyNote': "Troca os sticks de mover e mirar.",
  'set.audio': "Áudio",
  'set.sound': "Volume dos efeitos",
  'set.music': "Volume da música",
  'set.track': "Trilha sonora",
  'set.trackAuto': "Mix",
  'set.trackNote': "Uma faixa diferente a cada partida, ou fique com a favorita.",
  'pause.nextTrack': "Próxima faixa ⏭",
  'set.language': "Idioma",
  'shop.exoticIn': "Exótico em",
  'shop.guarantee': "Exótico garantido em {n} aberturas",
  'set.voice': "Locutor",
  'mode.dm': "Mata-mata",
  'mode.dm.d': "Cada um por si, renasce após cada morte. Quem tiver mais abates no fim leva o pote.",
  'mode.gl': "Armas + Lasers",
  'mode.gl.d': "Mata-mata com loja: abates dão créditos para kits médicos, torretas e minas laser.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "Vida mínima: uma bala e você cai. O último de pé leva o pote.",
  'kind.dm': "mais abates leva o pote",
  'hud.startDm': "Quem tiver mais abates quando o relógio zerar leva o pote",
  'hud.startGl': "Abates dão créditos · 1 kit médico · 2 torreta · 3 mina laser",
  'hud.startHc': "Um tiro e você cai. Faça cada tiro valer.",
  'hud.respawned': "De volta",
  'hud.respawnIn': "Renasce em {s}s",
  'hud.tookLead': "Você assumiu a liderança",
  'hud.lostLead': "Você perdeu a liderança",
  'hud.dmScore': "{k} abates · {d} mortes · #{p}",
  'hud.dmGoal': "O primeiro abate assume a liderança",
  'hud.oneHit': "1 TIRO",
  'feed.leader': "{name} assume a liderança com {k}",
  'gl.medkit': "Kit médico",
  'gl.turret': "Torreta",
  'gl.mine': "Mina laser",
  'gl.no.cash': "Créditos insuficientes",
  'gl.no.full': "Vida já está cheia",
  'gl.no.limit': "Limite atingido",
  'gl.no.wall': "Perto demais de uma parede",
  'res.dmLost': "Terminou em #{p}",
  'res.dmText': "{k} abates, {d} mortes. O vencedor fez {top}.",
  'coach.dm': "Você renasce · vence quem tiver mais abates no fim",
  'coach.gl': "Abates dão créditos · gaste num kit médico ✚, numa torreta ◈ ou numa mina laser ⌁",
  'set.voiceNote': "Locutor gravado (inglês, ucraniano, espanhol, francês, português; inglês para os outros idiomas).",
  'net.waking': "Acordando o servidor (a hospedagem grátis dorme quando ninguém joga, até um minuto)… O treino funciona enquanto isso.",
  'shop.bulk': "A cada {n} caixas, uma grátis",
  'shop.bulkOn': "Caixas grátis incluídas: {n}",
  'net.online': "{n} online",
  'st.title': "Primeiros passos",
  'st.signin': "Entre",
  'st.signin.d': "Com sua carteira Starknet, Cartridge ou e-mail.",
  'st.signin.go': "Entrar",
  'st.fund': "Adicione fundos",
  'st.fund.d': "Envie alguns tokens da sua carteira para o saldo do jogo. Saque quando quiser.",
  'st.fundTest': "Testnet: STRK grátis em starknet-faucet.vercel.app.",
  'st.fund.go': "Depositar",
  'st.coin': "Escolha sua moeda",
  'st.coin.d': "Escolha abaixo com qual moeda apostar. Os ganhos voltam na mesma moeda.",
  'st.coin.go': "Ver moedas",
  'st.play': "Jogue sua primeira partida",
  'st.play.d': "Escolha modo e aposta, toque em Jogar e depois Pronto.",
  'st.play.go': "Jogar",
  'touch.fire': "Atirar",
  'rot.title': "Vire o celular",
  'rot.sub': "O raid funciona melhor na horizontal: mova-se à esquerda, atire à direita.",
  'rot.anyway': "Jogar na vertical",
  'prep.waiting': "Esperando jogadores",
  'prep.waitingMe': "Sem cronômetro: chame amigos e toque em Começar quando estiverem prontos. Bots ocupam as vagas. {n} de {of} vagas ocupadas.",
  'prep.waitingJoin': "{n} de {of} vagas ocupadas. Aposte e toque em Pronto para entrar.",
  'prep.firstWait': "Toque em Pronto: a sala espera todos, sem cronômetro.",
  'prep.start': "Começar agora",
  'nav.friends': "Amigos",
  'nav.guilds': "Guildas",
  'so.now': "agora",
  'so.min': "há {n} min",
  'so.hr': "há {n} h",
  'so.day': "há {n} d",
  'so.seen': "Visto {t}",
  'so.st.lobby': "Online",
  'so.st.waiting': "Esperando numa sala",
  'so.st.raid': "Num raid",
  'so.friend': "Amigo",
  'so.sent': "Pedido enviado",
  'so.accept': "Aceitar",
  'so.add': "Adicionar amigo",
  'so.invited': "Convidado",
  'so.invite': "Convidar",
  'so.message': "Mensagem",
  'so.onlineOnly': "Amigos, mensagens e guildas funcionam no modo online.",
  'so.gInvite': "Para a guilda",
  'so.gInvited': "Convidado",
  'so.gInviteSent': "Convite para a guilda enviado",
  'so.gInvitesYou': "convida você para a guilda",
  'so.gMembers': "{n} membros",
  'so.gJoin': "Entrar na guilda",
  'so.more': "Mostrar mais ({n})",
  'so.players': "Jogadores",
  'so.friends': "Amigos",
  'so.messages': "Mensagens",
  'so.search': "Buscar jogadores pelo nome",
  'so.count': "{n} jogadores · {on} online",
  'so.none': "Ninguém encontrado.",
  'so.wants': "quer ser seu amigo",
  'so.requests': "Pedidos de amizade",
  'so.noFriends': "Ainda sem amigos. Encontre pessoas em Jogadores.",
  'so.pending': "Pedidos enviados",
  'so.cancel': "Cancelar",
  'so.decline': "Recusar",
  'so.sayHi': "Diga oi 👋",
  'so.noMsgs': "Ainda sem mensagens.",
  'so.remove': "Remover amigo",
  'so.onlineNow': "Online agora",
  'so.nobody': "Ninguém livre online agora.",
  'so.invitesYou': "convida você para um raid",
  'so.waitingN': "{n} esperando",
  'so.join': "Entrar",
  'so.later': "Depois",
  'so.reqToast': "{n} quer ser seu amigo",
  'so.nowFriends': "Você e {n} agora são amigos",
  'so.invSent': "Convite enviado",
  'so.invitePlayers': "Convidar jogadores",
  'so.inviteHint': "Eles recebem um cartão com o botão Entrar que os traz para esta sala.",
  'gd.members': "{n} membros",
  'gd.leave': "Sair da guilda",
  'gd.join': "Entrar",
  'gd.all': "Todas as guildas",
  'gd.needRank': "Rank {n} ou mais (você: {have})",
  'gd.needBuy': "Pelo menos uma compra com USDC/USDT",
  'gd.create': "Criar uma guilda",
  'gd.name': "Nome da guilda",
  'gd.tag': "Tag (2-5)",
  'gd.desc': "Descrição curta (opcional)",
  'gd.found': "Fundar a guilda",
  'gd.count': "{n} membros · {on} online",
  'gd.yours': "Sua guilda",
  'gd.list': "Guildas",
  'gd.none': "Ainda sem guildas. Seja o primeiro.",
  'gd.err.signin': "Entre primeiro.",
  'gd.err.member': "Saia da sua guilda primeiro.",
  'gd.err.purchase': "Fundar uma guilda exige uma compra com USDC/USDT.",
  'gd.err.rank': "Fundar uma guilda exige rank 20.",
  'gd.err.name': "Nome: 3-24 letras, dígitos ou espaços.",
  'gd.err.tag': "Tag: 2-5 letras ou dígitos.",
  'gd.err.taken': "Esse nome ou tag já existe.",
  'pf.title': "Jogador",
  'pf.rank': "Rank {n}",
  'pf.guild': "Guilda: {g}",
  'pf.raids': "Raids",
  'pf.wins': "Vitórias",
  'pf.kills': "Abates",
  'pf.extracts': "Extrações",
  'pf.best': "Recorde de abates",
  'pf.time': "Tempo jogado",
  'pf.ach': "Conquistas",
  'pf.multi': "Melhor sequência",
  'pf.since': "Joga desde",
  'tb.readyWait': "{n} esperando",
  'mc.waiting': "{n} esperando",
  'pause.open': "Menu (Esc)",
  'pause.title': "Menu",
  'pause.resume': "Continuar",
  'pause.settings': "Configurações",
  'pause.leave': "Sair da partida",
  'pause.leaveLose': "Sair (perde a aposta)",
  'pause.leaveSure': "Toque de novo para sair",
  'pause.keys': "Esc: voltar à partida",
  'pause.back': "← Voltar",
  'pause.on': "lig.",
  'pause.off': "desl.",
  'pause.practice': "O treino está pausado.",
  'pause.practiceDead': "Você foi eliminado. Saia quando quiser.",
  'pause.alive': "A partida continua com o menu aberto. Se sair agora, seu corredor fica no mapa e a aposta fica na partida.",
  'pause.dead': "Você foi eliminado. Saia quando quiser: o que ganhou ainda chega ao seu saldo.",
  'gd.chat': "Chat",
  'gd.chatEmpty': "Nenhuma mensagem ainda. Diga oi para a guilda.",
  'gd.chatPh': "Escreva para a guilda…",
  'swap.min': "Troca mínima: {v}",
  'prep.waitingPeople': "Sem cronômetro: chame amigos, a incursão começa quando {min} jogadores estiverem prontos. Só jogadores reais. {n} de {of} vagas ocupadas.",
  'prep.people': "Só jogadores reais: aqui todos começam com uma faca.",
  'shop.firstTopup': "A primeira recarga dobra: ganhe o mesmo valor em $ da loja, até {v} extra.",
  'tour.who': "sua contato",
  'tour.voice': "Voz lig./desl.",
  'tour.skip': "Pular",
  'tour.next': "Próximo",
  'tour.done': "Vamos lá",
  'set.tour': "Tutorial",
  'set.tourNote': "A Nyx mostra o jogo de novo.",
  'set.tourBtn': "Refazer o tutorial",
  'nyx.hello': "Oiii, corredor! Eu sou a Nyx, sua guia esta noite! Fica comigo, e você sai da sua primeira incursão... rico!",
  'nyx.name': "Primeiro o mais importante! Digite um nome para seu corredor e toque em Pronto. Todos vão vê-lo acima da sua cabeça!",
  'nyx.nameOk': "Ah, que nome fofo! Gostei!",
  'nyx.practice': "Agora toque em Treino! É grátis, só bots. Perfeito para a primeira partida!",
  'nyx.practiceOk': "Ééé! Boa escolha!",
  'nyx.modes': "Esses são os modos de jogo! Hoje jogamos Incursão, o clássico. Saqueie, lute e saia! Toque em Incursão!",
  'nyx.modeOk': "Incursão, então! Bora!",
  'nyx.bag': "É assim! Sua aposta vai na sua bolsa. Derrube alguém, e a bolsa dele é sua! Caiu... e a sua é dele. Eita!",
  'nyx.shop': "Roupas e skins de armas saem de bolsas e caixas, aqui na loja! E psiu... tem uma grátis esperando por você!",
  'nyx.social': "Amigos, mensagens, guildas! Traga sua galera. Tudo é mais divertido junto!",
  'nyx.wallet': "Quer apostas reais? Entre com uma carteira, ou só com um e-mail! Saques só vão para o seu próprio endereço. Tudo seguro!",
  'nyx.play': "Pronto? Aperte Jogar!",
  'nyx.ready': "Essa é a sala de espera! Aperte Pronto, e a gente cai! Uhul!",
  'nyx.start': "Entramos! Mova com W, A, S, D. Mire com o mouse e clique para atirar! Espaço para o dash!",
  'nyx.startTouch': "Entramos! Seu polegar esquerdo te move. Segure Fogo, à direita, ele mira por você!",
  'nyx.loot': "Vê aquele brilho laranja? É dinheiro! Passa correndo por cima!",
  'nyx.pickup': "Eba! Sua bolsa ficou mais pesada!",
  'nyx.kill': "Primeiro abate! Belo tiro! Pegue o que caiu. Ah, e uma arma melhor!",
  'nyx.hurt': "Ai, você está ferido! A vida não volta no combate, então cuidado!",
  'nyx.storm': "A tempestade está chegando! Fique dentro do círculo, rápido!",
  'nyx.exit': "Ah, essa bolsa ficou ótima em você! Ache um anel verde de saída e fique nele!",
  'nyx.extracting': "Fica parado! Três segundos! Não leve tiro!",
  'nyx.won': "Você saiu! Eu sabia que você conseguia! Até a próxima incursão, corredor!",
  'nyx.dead': "Aah, acontece! O treino é grátis, bora de novo!",
  'tour.yourMove': "Sua vez",
  'tour.skipStep': "Pular este passo",
  'tour.again': "Toque na Nyx para ouvir de novo",
  'tour.replayHint': "Quer o tutorial de novo? Configurações → Tutorial.",
  'mode.zombies': "Zumbis",
  'mode.zombies.d': "Cooperativo, sozinho ou com até 3 amigos: 20 ondas de mortos, cada uma mais difícil, chefes na 10 e na 20. Sem relógio. Abates dão créditos para torretas, minas laser e kits médicos.",
  'mode.gold': "Corrida do ouro",
  'mode.gold.d': "Sacos de ouro caem por toda a pedreira. Armas aleatórias, renascimento rápido. Quem pegar mais sacos leva o pote todo como crédito na loja.",
  'kind.zombie': "cooperativo · XP",
  'kind.gold': "um vencedor · crédito",
  'tb.zFee': "entrada · XP, títulos",
  'tb.goldFee': "entrada · o vencedor leva tudo",
  'prep.zFee': "entrada {v}",
  'prep.zSquad': "Esquadrão",
  'prep.goldPot': "Prêmio (crédito na loja)",
  'zp.title': "Sua arma para a partida",
  'zp.power': "Dano por segundo",
  'zp.melee': "sem recarga",
  'hud.waveK': "Onda",
  'hud.goldK': "Sacos de ouro",
  'hud.startZ': "Segure o cemitério. Eles vêm de todos os lados",
  'hud.startGold': "Pegue o ouro. Quem tiver mais sacos leva tudo",
  'hud.wave': "Onda {n} de {of}",
  'hud.bossWave': "ÚLTIMA ONDA · O CHEFE CHEGOU",
  'hud.waveClear': "Onda {n} superada",
  'hud.patched': "+35 HP",
  'hud.summon': "O chefe chama a horda",
  'hud.bossDown': "CHEFE ABATIDO · PARTIDA CONCLUÍDA",
  'hud.bagsShort': "ouro",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "próxima onda em {s} s",
  'hud.zLeft': "faltam {n} · {k} abatidos",
  'hud.goldPlace': "lugar {p} · {d} mortes · prêmio {s}",
  'hud.bossHp': "CHEFE {p}%",
  'hud.zBreak': "Recarregue e reagrupe: {s} s",
  'hud.zGoal': "Sobreviva a 20 ondas · chefes na 10 e na 20",
  'hud.goldGoal': "Vence quem tiver mais sacos no fim",
  'hud.zDown': "Caiu. Você volta na próxima onda se o esquadrão aguentar",
  'feed.zYou': "Os mortos te pegaram",
  'feed.zDown': "{name} foi despedaçado",
  'coach.z': "Fique na praça, costas com costas. Abates dão créditos: compre torretas (2), minas laser (3) e kits (1)",
  'coach.gold': "Passe por cima dos sacos para pegá-los. Se morrer, metade cai, então pegue e sobreviva",
  'warn.z60': "Falta um minuto",
  'warn.z10': "10 segundos: mate o chefe!",
  'warn.gold30': "30 segundos: pegue o que puder",
  'warn.gold10': "Faltam 10 segundos",
  'res.zCleared': "Partida concluída",
  'res.zFell': "Derrotados na onda {n}",
  'res.zWaves': "{n} / {of} ondas",
  'res.zWonText': "Dez ondas e o chefe, com um esquadrão de {s}. Você abateu {k} mortos.",
  'res.zText': "Você abateu {k} mortos (esquadrão de {s}). Quanto mais longe, mais XP.",
  'res.zTime': "tempo {t}",
  'res.goldWon': "Corrida do ouro vencida",
  'res.goldLost': "Lugar {p} na corrida do ouro",
  'res.goldWonText': "{b} sacos de ouro, mais que todos. {c} já está no seu saldo da loja.",
  'res.goldText': "Você pegou {b} sacos; o vencedor teve {top}. Só o primeiro recebe.",
  'xp.Waves survived': "Ondas superadas",
  'xp.Zombies': "Zumbis",
  'xp.Boss slain': "Chefe abatido",
  'xp.Run cleared': "Partida concluída",
  'xp.Gold bags': "Sacos de ouro",
  'ach.graveyard_shift': "Turno do cemitério",
  'ach.hold_the_line': "Segure a linha",
  'ach.undertaker': "Coveiro",
  'ach.exterminator': "Exterminador",
  'ach.giant_slayer': "Mata-gigantes",
  'ach.zombie_slayer': "Matador de zumbis",
  'ach.top_of_the_horde': "Topo da horda",
  'ach.nightmare_walker': "Andarilho dos pesadelos",
  'ach.army_of_one': "Exército de um",
  'ach.prospector': "Garimpeiro",
  'ach.gold_fever': "Febre do ouro",
  'ach.mother_lode': "Veio de ouro",
  'ach.bag_hoarder': "Acumulador de sacos",
  'ach.midas': "Midas",
  'achd.zRuns': "Jogue uma partida de zumbis",
  'achd.bestWave': "Supere a onda {n} de mortos",
  'achd.zKills': "Mate {n} zumbis",
  'achd.zBoss': "Dê o golpe final no chefe",
  'achd.zClears': "Conclua a partida de zumbis {n} vezes",
  'achd.zMvp': "Conclua uma partida com mais abates do esquadrão",
  'achd.zSolo': "Conclua a partida de zumbis sozinho",
  'achd.goldRuns': "Jogue uma corrida do ouro",
  'achd.goldWins': "Vença {n} corridas do ouro",
  'achd.bestGold': "Termine uma corrida com {n} sacos",
  'achd.goldBags': "Pegue {n} sacos de ouro no total",
  'tour.nameDone': "Pronto",
  'tour.finish': "Bora jogar!",
  'nyx.stake': "Esta é sua aposta: o que vai na sua bolsa. No treino é dinheiro de mentira, nada a perder. Vamos jogar por um dólar!",
  'nyx.retry': "Ah, você caiu! Acontece, o treino é grátis! Toque em Jogar de novo. Desta vez pegue um pouco de saque e corra para uma saída verde!",
  'nyx.resultWon': "Você saiu! Você venceu! Eu sabia! O dinheiro já está na sua carteira. Toque em Mesas e vamos gastar um pouco!",
  'nyx.shopGo': "Agora toque na Loja!",
  'nyx.shopCase': "Bem-vindo à loja! Vamos gastar seus ganhos. Toque em Abrir nesta bolsa. É pago direto da sua carteira!",
  'nyx.shopEquip': "Uau, olha o que você ganhou! Toque no botão e é seu!",
  'nyx.bye': "É isso! Você já sabe jogar, vencer e comprar. Vai lá, corredor! Pode me chamar quando quiser nas Configurações.",
  'hud.headshot': "TIRO NA CABEÇA",
  'inv.open': "Abrir",
  'bp.later': "Depois",
  'ach.sharpshooter': "Atirador certeiro",
  'ach.headhunter': "Caçador de cabeças",
  'achd.headshots': "Acerte {n} tiros na cabeça",
  'hud.demoted': "Morte: volta para {w}",
  'hud.crit': "CRÍTICO",
  'hud.roundStart': "Rodada {n} de {of}",
  'hud.roundWon': "Rodada {n} é sua!",
  'hud.roundLost': "Rodada {n} perdida",
  'hud.roundDraw': "Rodada {n}: empate",
  'hud.roundTo': "Rodada {n} vai para {name}",
  'hud.roundNext': "Próxima rodada em {s} s",
  'hud.roundScore': "Rodada {n}/{of} · {a} : {b}",
  'hud.roundDown': "Caiu. Volta na próxima rodada",
  'mc.rounds': "{w} de {n} rodadas",
  'hud.midBossWave': "ONDA 10 · UM CHEFE PULA A CERCA",
  'hud.midBossDown': "Chefe abatido! Faltam dez ondas",
  'ach.last_stand': "Última resistência",
  'gl.upTurret': "Torreta melhorada: nível {lv}",
  'gl.upMine': "Mina laser melhorada: {lv} feixes",
  'gl.upHint': "Espaço: {what} → nível {lv} · {c} CR",
  'gl.upHintTouch': "⬆ {what} → nível {lv} · {c} CR",
  'gl.no.max': "Já está no nível máximo",
  'gl.no.near': "Fique perto da sua torreta ou mina",
};
