// Kiswahili (Swahili): the whole game, every string. Same keys as en.js.
export default {
  "lobby.tagline": "Weka dau. Kusanya ngawira. Toka kabla ya dhoruba. <b>Hakuna anayeona kilicho kwenye begi lako.</b>",
  "lobby.namePh": "Jina la mkimbiaji wako",
  "lobby.locker": "Kabati · skini · mabegi",
  "lobby.refill": "Jaza sarafu za majaribio",
  "lobby.online": "Mtandaoni",
  "lobby.practice": "Mazoezi dhidi ya roboti",
  "lobby.stakePer": "Dau kwa uvamizi",
  "lobby.stakeWith": "Weka dau kwa <span class=\"fine\">sarafu yoyote · inaonyeshwa kwa $ · ushindi unarudi kwa sarafu ileile</span>",
  "lobby.play": "Cheza · dau {s}",
  "lobby.signIn": "Ingia ili ucheze",
  "lobby.how": "Jinsi ya kucheza",
  "lobby.gore": "<b>Hali ya 18+.</b> Viungo vinakatika, damu inabaki sakafuni.",
  "lobby.fine": "Mazoezi yanaendeshwa kwenye kivinjari chako. Pesa zote hapa ni za mchezo.",
  "how.1": "<b>Weka dau na ujiandae.</b> Kila mtu anashuka pamoja akiwa na kisu na afya 100. Nusu ya dau lako iko kwenye begi lako, nusu imetawanyika kama ngawira.",
  "how.2": "<b>Chukua ngawira ya rangi ya chungwa.</b> Inaingia kwenye begi lako. Kuua kunaboresha silaha yako: kisu → bastola → shotgun → SMG → bunduki → sniper ya leza.",
  "how.3": "<b>Toka ukiwa hai.</b> Kuna njia moja tu ya kutoka, katikati ya ramani. Kaa ndani yake sekunde 10: kila mtu anaambiwa unaondoka, na kila pigo linaanzisha hesabu upya. Ukifanikiwa mfuko wote ni wako. Ukifa unadondokea mwingine.",
  "how.keys": "<kbd>WASD</kbd> tembea · <kbd>kipanya</kbd> lenga · <kbd>bofya</kbd> shambulia · <kbd>Space</kbd> ruka mbele · <kbd>Q</kbd> danganya ukubwa wa begi · <kbd>M</kbd> sauti · <kbd>N</kbd> muziki",
  "how.fine": "Kila uvamizi na kila mafanikio hulipa XP ya cheo. Kila kupanda cheo kunakuazima skini mpya kwa siku 3.",
  "net.practice": "Wewe na roboti tu, bila mtandao.",
  "net.open": "Umeunganishwa. Uvamizi wa mtandaoni ni wachezaji halisi tu.",
  "reg.title": "Seva",
  "reg.auto": "Iliyo karibu zaidi",
  "reg.fallback": "Seva hiyo haipokei wachezaji sasa hivi. Unacheza kwenye {r}.",
  "reg.eu": "Ulaya",
  "reg.us": "Amerika",
  "reg.asia": "Asia",
  "nav.starknet": "Starknet",
  "nav.s.starknet": "Faragha · takwimu hai",
  "sk.kicker": "Imejengwa kwenye Starknet",
  "sk.title": "Siri kwa chaguo-msingi",
  "sk.lede": "Pesa yako unaiona wewe tu. Amana na utoaji hupita kwenye pool iliyolindwa ya STRK20 ya Starknet kwa uthibitisho wa maarifa sifuri, dau hubaki siri, ubadilishaji haugusi mnyororo, na Bitcoin inachezwa kama sarafu yoyote.",
  "sk.dep.t": "Amana ya siri",
  "sk.dep.b": "Kutoka salio lako lililolindwa kwenda mchezoni kupitia pool ya STRK20. Uthibitisho wa maarifa sifuri unahakiki: hakuna kwenye mnyororo anayeona nani alilipa wala kiasi gani.",
  "sk.dep.a": "Weka kwa siri",
  "sk.stake.t": "Dau za siri",
  "sk.stake.b": "Chagua dau lolote ndani ya kiwango cha meza. Unalijua wewe tu: meza inaonyesha jumla ya pool tu. Zawadi zinagawanywa kwa haki, kama side pot za poka.",
  "sk.stake.a": "Cheza",
  "sk.swap.t": "Ubadilishaji wa siri",
  "sk.swap.b": "Badilisha sarafu ndani ya salio la mchezo kwa bei hai. Haugusi mnyororo kamwe, kwa hiyo hakuna explorer inayouonyesha.",
  "sk.swap.a": "Badilisha",
  "sk.wd.t": "Utoaji wa siri",
  "sk.wd.b": "Ushindi unarudi kwenye salio lako lililolindwa kupitia STRK20: hakuna kwenye mnyororo anayeona malipo ni yako.",
  "sk.wd.a": "Toa kwa siri",
  "sk.ready": "Tayari",
  "sk.needWallet": "Inahitaji Ready au Xverse",
  "sk.signIn": "Ingia kwa pochi ya Starknet",
  "sk.always": "Imewashwa kila wakati",
  "sk.btc.t": "Bitcoin kwenye Starknet",
  "sk.btc.b": "Weka dau la BTC (WBTC na Bitcoin nyingine kwenye Starknet) kama sarafu yoyote: ushindi unarudi kwa Bitcoin kwa bei hai.",
  "sk.btc.a": "Cheza na BTC",
  "sk.btc.picked": "Sarafu yako ya dau sasa ni Bitcoin.",
  "sk.live": "Hai kwenye Starknet",
  "sk.test": "mtandao wa majaribio",
  "sk.s.players": "Wachezaji",
  "sk.s.d7": "Hai wiki hii",
  "sk.s.matches": "Mechi zilizochezwa",
  "sk.s.staked": "Dau kwenye mechi",
  "sk.s.privStakes": "Dau za siri",
  "sk.s.privTx": "Uhamisho wa siri (STRK20)",
  "sk.s.deposits": "Amana kwenye mnyororo",
  "sk.s.tvl": "Kilichoshikiliwa mchezoni",
  "sk.loading": "Inapakia takwimu…",
  "sk.note": "Jumla tu: hapa hakuna mchezaji wala kiasi cha mtu yeyote.",
  "cx.none": "Bado hakuna kitu.",
  "cx.loading": "Inapakia pochi…",
  "cx.cartridgeGo": "Endelea kwenye dirisha la Cartridge…",
  "cx.waitWallet": "Inasubiri pochi…",
  "cx.signMsg": "Saini ujumbe wa kuingia kwenye pochi yako (ni bure).",
  "cx.noAnswer": "Seva haikujibu.",
  "cx.noSig": "Pochi haikurudisha sahihi. Jaribu tena.",
  "cx.checkingSig": "Imesainiwa. Inakagua sahihi kwenye Starknet…",
  "cx.notConfirmed": "Seva haikuthibitisha kuingia kwa wakati. Jaribu tena.",
  "cx.typeEmail": "Andika barua pepe yako kwanza.",
  "cx.sendingCode": "Inatuma msimbo…",
  "cx.codeSent": "Msimbo umetumwa kwa {e}.",
  "cx.checkingCode": "Inakagua msimbo…",
  "cx.privyAgain": "Ingia tena kwa Privy.",
  "cx.signAgain": "Ingia tena kuchagua pochi yako.",
  "cx.otherAcct": "{w} iko kwenye akaunti {a}, lakini umeingia kama {b}. Badilisha akaunti kwenye pochi, au ingia kwa {a}.",
  "cx.signInAs": "Ingia kama {a}",
  "cx.inWalletChecking": "Kwenye pochi yako: inakagua…",
  "cx.inWallet": "Kwenye pochi yako: {v}",
  "cx.keepStrk": " (acha ~1 STRK kwa ada za mtandao)",
  "cx.transfer": "Uhamisho wa wazi",
  "cx.transferDep": "pochi yoyote: uhamisho wa kawaida wa tokeni, unaonekana kwenye mnyororo",
  "cx.transferWd": "uhamisho wa kawaida kwa anwani yako, unaonekana kwenye mnyororo",
  "cx.private": "🔒 Siri · Starknet STRK20",
  "cx.privateDep": "Ready au Xverse: kutoka salio lako lililolindwa kwa uthibitisho wa maarifa sifuri. Hakuna kwenye mnyororo anayeona nani alilipa wala kiasi gani",
  "cx.privateWd": "kwenye salio lako lililolindwa: hakuna kwenye mnyororo anayeona malipo ni yako. Anwani yako lazima isajiliwe kwenye pool ya STRK20",
  "cx.typeAmount": "Andika kiasi.",
  "cx.walletOnly": "Pochi yako ina {v} tu.",
  "cx.faucet": " STRK za majaribio bure: starknet-faucet.vercel.app.",
  "cx.leaveStrk": "Acha takriban 1 STRK kwenye pochi kwa ada ya mtandao (tumia Max).",
  "cx.confirmDep": "Thibitisha amana kwenye pochi yako…",
  "cx.holdsOnly": "{w} ({a}) ina {v}. Tuma {s} kwa anwani hii kwanza.",
  "cx.noPrivate": "Njia hii ya kuingia haiwezi kufanya uhamisho wa siri. Tumia uhamisho wa wazi.",
  "cx.check": "Kagua",
  "cx.badTx": "Hiyo si hash ya muamala (0x…).",
  "cx.copied": "Anwani imenakiliwa",
  "cx.copy": "Nakili",
  "cx.manualHow": "Kutoka anwani uliyoingia nayo, tuma sarafu kwa anwani ya nyumba hapa chini. Kisha bandika hash ya muamala hapa.",
  "cx.manual": "Pochi haipakii? Tuma kwa mkono",
  "cx.noRef": "Seva haikutoa nambari ya kumbukumbu ya amana. Jaribu tena.",
  "cx.sentWait": "Imetumwa ({tx}). Inasubiri Starknet…",
  "cx.youHave": "Una {v}.",
  "cx.depBad": "Amana (tokeni haikubaliwi, wasiliana na msaada)",
  "cx.depHeld": "Amana imeshikiliwa (zaidi ya kikomo cha beta, inarudishwa)",
  "cx.dep": "Amana",
  "cx.cashout": "Utoaji · {s}",
  "cx.signedAs": "Umeingia kama {a}.",
  "cx.checkingChain": "Keshia inakagua mnyororo…",
  "cx.notCredited": "Imepokelewa lakini haijawekwa kwa sababu {r}. Iko salama na itarudishwa kwako.",
  "cx.credited": "Imewekwa {v}.",
  "cx.creditedToast": "Amana imewekwa: {v}.",
  "cx.txFailed": "Muamala huo umeshindwa kwenye mnyororo. Hakuna kilichochukuliwa.",
  "cx.sentPrivate": "Imetumwa kwa siri. Noti iliyolindwa inafika ndani ya dakika moja au mbili; salio lako linasasishwa lenyewe.",
  "cx.sentPublic": "Inasubiri Starknet ikubali. Salio lako linasasishwa lenyewe.",
  "cx.paying": "Inalipa…",
  "cx.paid": "Imelipwa. Muamala {tx}.",
  "cx.paidToast": "Utoaji umetumwa.",
  "cx.payFailed": "Malipo hayakuweza kutumwa. Salio lako limerudi.",
  "cx.payHeld": "Malipo yameshikiliwa kwa ukaguzi wa mkono. Pesa zako ziko salama; yako kwenye historia.",
  "cx.wrong": "Kuna hitilafu.",
  "cx.cancelled": "Imeghairiwa kwenye pochi.",
  "cx.cantSend": "Pochi yako haikuweza kutuma: kwa kawaida tokeni haitoshi, au hakuna STRK ya ada. Jaribu kiasi kidogo (Max inaacha nafasi ya ada).",
  "cx.notDeployed": "Akaunti ya pochi yako bado haijawekwa kwenye mtandao huu. Fanya muamala wowote kwanza (kwa mfano, jitumie STRK kidogo), kisha jaribu tena.",
  "cx.minWd": "Kiwango cha chini ${m}. Inalipwa kwa {a}.",
  "cx.wdOff": "Utoaji umezimwa kwenye seva hii kwa sasa.",
  "cx.hintPrivate": "Pochi yako inatengeneza uthibitisho wa maarifa sifuri kwenye Starknet; inaweza kuchukua dakika moja.",
  "cx.hintPublic": "Salio lako linasasishwa uhamisho ukikubaliwa kwenye Starknet.",
  "cx.connectT": "Ingia ili ucheze kwa tokeni",
  "cx.swallet": "Pochi ya Starknet",
  "cx.looking": "Inatafuta pochi…",
  "cx.privNote": "Pochi yoyote ya Starknet inafanya kazi. Ready na Xverse pia zinaweza kuweka na kutoa kwa siri kupitia pool ya STRK20: hakuna kwenye mnyororo anayeona wewe ni nani wala kiasi gani.",
  "cx.noWallet": "Bila pochi · Cartridge",
  "cx.cartSub": "passkey au mitandao ya kijamii, bila gesi",
  "cx.privyT": "Barua pepe au mitandao · Privy",
  "cx.sendCode": "Tuma msimbo",
  "cx.codePh": "Msimbo kutoka kwenye barua pepe",
  "cx.signIn": "Ingia",
  "cx.cashier": "Keshia",
  "cx.tDeposit": "Weka",
  "cx.tCash": "Toa",
  "cx.tHistory": "Historia",
  "cx.amount": "Kiasi",
  "cx.testFaucet": "Testnet: pata STRK bure kwa anwani yako kwenye starknet-faucet.vercel.app, kisha weka hapa.",
  "stake.private": "🔒 Dau lako ni la siri: meza inaonyesha jumla ya pool tu, kamwe si nani aliweka kiasi gani.",
  "prep.mine": "🔒 Dau lako: {v} · unaliona wewe tu",
  "res.refund": "{v} ya dau lako imerudi: hakuna mshindi aliyeweka kiasi hicho.",
  "medal.long": "Risasi ya mbali",
  "medal.knife": "Kuua kwa kisu",
  "ex.centre": "TOKA · KAA SEK {s}",
  "feed.extracting": "{name} anashika njia ya kutoka",
  "hud.holdExit": "Shika njia ya kutoka sekunde {s} · kila mtu anajua · pigo linaanzisha hesabu upya",
  "cs.signedOut": "Tokeni halisi kwenye Starknet {n}. Ingia ili ucheze.",
  "cs.manage": "Weka · toa",
  "cs.fine": "Tokeni halisi kwenye Starknet {n}. Mchezo unashikilia amana hadi utoe; utoaji unaenda tu kwenye anwani uliyoingia nayo.",
  "cs.beta": "Beta: hadi {v} kwa kila mchezaji.",
  "wel.name.t": "Chagua jina la mkimbiaji wako",
  "wel.name.b": "Habari, mimi ni Nyx, msimamizi wako! Kabla hatujashuka, niambie nikuite nani. Kila mtu kwenye mechi anaona jina hili juu ya kichwa chako, kwenye ubao wa alama na kwenye gumzo.",
  "wel.name.ph": "Jina la mkimbiaji wako",
  "wel.name.rules": "Herufi au tarakimu 3 hadi 16. Unaweza kulibadilisha baadaye kwenye ukurasa wa Cheza.",
  "wel.name.dice": "Jina la nasibu",
  "wel.next": "Endelea",
  "wel.back": "Rudi",
  "wel.go": "Twende",
  "wel.region.t": "Chagua eneo lako",
  "wel.region.b": "Mechi zinachezwa kwenye seva iliyo karibu nawe. Kadiri ping (ms) inavyokuwa chini, ndivyo mchezo unavyokuwa laini. Nimezijaribu zote kwa ajili yako: ya kijani ndiyo ya haraka zaidi.",
  "wel.region.best": "Bora kwako",
  "wel.region.off": "haijibu",
  "wel.region.players": "{n} mtandaoni",
  "wel.region.auto": "Otomatiki",
  "wel.region.autoD": "daima iliyo ya haraka zaidi kwako",
  "wel.region.note": "Unaweza kubadilisha eneo wakati wowote kwenye ukurasa wa Cheza.",
  "tut.hello.t": "Karibu DARK BAGS!",
  "tut.hello": "Mimi ni Nyx. Katika dakika chache nitakuonyesha **kila sehemu ya mchezo**, ili usichanganyikiwe na chochote, kisha tutacheza **mechi yako ya kwanza pamoja**.\nWazo ni rahisi: unaingia kwenye mechi na **begi** la pesa (dau lako), unakusanya ngawira, unapigana na wakimbiaji wengine na **unatoka ukiwa hai** ili ubaki na unachobeba.\nTumia **Endelea** (au kitufe →) kusonga mbele na **Rudi** kusoma tena.",
  "tut.menu.t": "Menyu",
  "tut.menu": "Kila kitu kiko hapa, katika makundi manne:\n**Cheza**: mechi, Ranked na Pasi ya Vita. **Duka**: duka, hifadhi yako na kubadilisha sarafu. **Kijamii**: gumzo, marafiki, vikundi, barua na mialiko. **Wewe**: kazi na mipangilio.\nMstari chini ya kila jina unakuambia kinachokusubiri (kazi za kudai, masanduku ya kufungua, saa ya duka). Nambari nyekundu inamaanisha kitu kipya. Kadi yako chini inaonyesha cheo chako na kiwango cha VIP.",
  "tut.profile.t": "Mkimbiaji wako",
  "tut.profile": "Huyu ni wewe. Gusa mkimbiaji wako kufungua **Kabati**: mavazi, skini za silaha na mtindo.\nChini ya jina lako: **cheo** chako (1 hadi 90). Kila mechi hulipa XP ya cheo: kuua, kubaki hai, kutoka, kushinda. Mafanikio hufungua **vyeo** unavyoweza kuvaa.\n**Mtandaoni** ni dhidi ya watu halisi kwa dau halisi. **Mazoezi** ni dhidi ya roboti kwa pesa za mchezo: bure, na bora kwa kujifunza.",
  "tut.goals.t": "Malengo ya leo",
  "tut.goals": "Orodha yako ya kila siku: **zawadi ya kalenda**, **kazi za kila siku**, **ushindi wa kwanza wa siku** (+300 XP), **daraja la pasi** yako na **mizunguko ya bure**.\nKadi inayong'aa inamaanisha zawadi inakusubiri: igusa na itakupeleka huko. Rudi kila siku: kalenda inakua kwa siku 30 mfululizo.",
  "tut.modes.t": "Aina za mchezo",
  "tut.modes": "Aina 17 katika makundi 5: **Klasiki**, **Silaha**, **Timu**, **Matukio** (Ranked, Zombi, Kimbilio la Dhahabu) au **Zote**.\nKila kadi inaonyesha wanaocheza, muda wa mechi, walio ndani **sasa hivi** na **wanaosubiri**. 🔥 inaonyesha iliyo na watu wengi zaidi. Gusa kadi kuichagua.",
  "tut.modeInfo.t": "Aina uliyochagua",
  "tut.modeInfo": "Kila kitu kuhusu aina uliyochagua: **jinsi ya kushinda**, **ushauri** kutoka kwangu na **inacholipa**, pamoja na wachezaji, muda wa mechi na walio ndani sasa.\nHujui ucheze nini? Soma kisanduku hiki kwanza. Kwa mechi ya kwanza, **Raid** ndiyo bora.",
  "tut.stake.t": "Dau lako",
  "tut.stake": "Unachoingiza kwenye mechi: **$0.10, $1, $10, $100** au **kiasi chako mwenyewe** ($0.10 hadi $10,000).\nKwenye **Raid**, nusu ya dau lako iko kwenye begi lako na nusu imetawanyika kwenye ramani kama ngawira. Toka ukiwa hai na ubaki na kila kitu kwenye begi lako. Kwenye **aina za chungu**, dau za wote zinakuwa zawadi moja: mshindi anaichukua.\nNyumba inachukua ada ya 5%. Anza kidogo: $0.10 au $1.\n🔒 Dau lako ni la **siri**: meza inaonyesha jumla ya pool tu. Dau zikitofautiana pool inagawanywa kwa haki: mshindi anachukua kwa kila mchezaji kiasi kisichozidi alichoweka yeye mwenyewe.",
  "tut.coins.t": "Weka dau kwa sarafu yoyote",
  "tut.coins": "Lipa kwa sarafu yoyote uliyo nayo: USDC, USDT, STRK, ETH, BTC na zaidi. Kiasi kinaonyeshwa kwa dola, kwa hivyo unajua daima unahatarisha nini.\nUshindi wako unarudi **kwa sarafu ileile, kwa bei uliyoingia nayo**: mabadiliko ya bei wakati wa mechi hayabadilishi chochote.",
  "tut.wallet.t": "Pochi yako na $ ya duka",
  "tut.wallet": "Juu: **Wallet** ni sarafu zako halisi (weka na toa wakati wowote). **Shop $** ni salio la duka kwa masanduku na ofa: haliwezi kutolewa.\nKucheza mtandaoni kwa dau halisi, ingia kwa pochi au barua pepe tu. Utoaji wa pesa unaenda **kwenye anwani yako mwenyewe** tu. Mazoezi hayahitaji chochote.",
  "tut.shop.t": "Duka: ofa",
  "tut.shop": "Juu ya duka:\n**Kifurushi cha mwanzo** (mara moja): vazi la Epic, masanduku 3, mizunguko 5 na fremu kwa $1.99. **Duka la leo**: skini sita kila siku unazonunua moja kwa moja, bila bahati nasibu. **Kadi ya Insider**: siku 30 za $ ya duka na mizunguko kila siku, +25% XP ya pasi. **VIP**: kadiri ulivyolipa zaidi, ndivyo bonasi ya kuongeza salio na mizunguko ya kila siku inavyokuwa kubwa.\nKila ununuzi unaomba mguso wa pili, kwa hivyo hakuna kinachonunuliwa kwa bahati mbaya.",
  "tut.cases.t": "Masanduku",
  "tut.cases": "**Mabegi** yanatoa mavazi ya mkimbiaji, **makasha** yanatoa skini za silaha, **masanduku ya mtindo** yanatoa fremu, mabango, athari za kuua na rangi za majina. Masanduku ghali zaidi yana nafasi bora.\nKila sanduku linaonyesha **nafasi kamili**, zinazochezwa kwenye seva. **Dhamana**: Epic au bora ndani ya mafunguo 15, Legendary ndani ya 60. Kila sanduku la 10 ni bure. Nakala inarudisha $ ya duka. Nunua na ufungue hadi 100 kwa mara moja.",
  "tut.wheel.t": "Gurudumu la bahati",
  "tut.wheel": "$0.05 kwa mzunguko, au bure kwa mizunguko kutoka kazi, kalenda, barua na VIP. **Zawadi 18**: skini za saa 1, skini halisi, mtindo, masanduku ya zawadi, $ ya duka, XP ya pasi, nyongeza za XP na mizunguko ya ziada.\nKila mzunguko unaolipiwa unajaza **benki ya bahati**: mzunguko unaofikia alama unashinda benki nzima **kwa sarafu halisi**. Tumia **Zungusha zote** kutumia mizunguko yote ya bure kwa mara moja.",
  "tut.inventory.t": "Hifadhi",
  "tut.inventory": "Kila kitu unachomiliki: sarafu kwenye pochi yako, $ ya duka, **masanduku yasiyofunguliwa** (gusa **Fungua yote** kuyafungua kwa mara moja), **mizunguko ya bure**, **mtindo** wako (fremu, bango, athari ya kuua, rangi ya jina: vaa hapa), mkusanyiko wako na takwimu zako.",
  "tut.swap.t": "Badilisha",
  "tut.swap": "Badilisha sarafu moja kwa nyingine ndani ya mchezo, kwa ada ndogo. Inafaa unapotaka kuweka dau au kutoa kwa sarafu nyingine.",
  "tut.pass.t": "Pasi ya Vita",
  "tut.pass": "Msimu mpya kila mwezi wenye **madaraja 50**. Kila mechi inaijaza kwa XP. **Njia ya bure** inatoa zawadi kwa kila mtu; **njia ya premium** ($9.99) inaongeza zawadi kwenye kila daraja: seti za siraha, skini za silaha na mizinga, mtindo wa Mythic.\nUna haraka? Nunua madaraja moja kwa moja. Dai zawadi zako kwenye ukurasa wa pasi.",
  "tut.ranked.t": "Ranked",
  "tut.ranked": "Battle royale yenye dau ambayo pia inasogeza **ukadiriaji wa msimu** wako. Nafasi na kuua vinaamua utapanda kiasi gani: Shaba, Fedha, Dhahabu, Platinamu, Almasi, Bingwa, **Hadithi ya Neon**.\nKila daraja jipya linalipa **zawadi** mara moja kwa msimu (mtindo wa Legendary, Mythic, hata Exotic), na baada ya mechi bahati nasibu ya sanduku inaweza kutokea.",
  "tut.tasks.t": "Kazi",
  "tut.tasks": "**Kalenda ya siku 30**: zawadi kila siku unaporudi (ukikosa siku inaanza upya), kubwa zaidi siku ya 7, 14, 21 na 30. **Kazi 3 za kila siku** na **kazi za kila wiki** kwa masanduku, mizunguko, $ ya duka na nyongeza za XP.\n**Mafanikio**: malengo 96; kila moja linalipa XP, zawadi na **cheo** unachoweza kuvaa.",
  "tut.social.t": "Marafiki, vikundi, gumzo",
  "tut.social": "Ongeza **marafiki**, ona walio mtandaoni, watumie ujumbe na uwaalike kwenye meza yako. Jiunge au anzisha **kikundi** chenye gumzo lake. **Gumzo** linazungumza na kila mtu.\nKwenye mechi: **Tab** inaonyesha ubao wa alama, **K** inawasha na kuzima maikrofoni ya **gumzo la sauti** (timu zinazungumza na timu yao).",
  "tut.mail.t": "Barua na mialiko",
  "tut.mail": "**Barua**: barua kutoka mchezo zenye zawadi za kudai (fungua sanduku au zungusha gurudumu moja kwa moja kutoka barua).\n**Alika**: shiriki kiungo chako. Marafiki wanaojiunga wanapata begi la karibu, na unapata $ ya duka kila wanapocheza.",
  "tut.settings.t": "Mipangilio",
  "tut.settings": "Sauti, muziki, michoro na athari, vidhibiti, lugha na gumzo la sauti. Unataka ziara hii tena? Iko hapa: **Mipangilio → Ziara**.",
  "tut.match.t": "Mechi yako ya kwanza!",
  "tut.match": "Huo ndio mchezo wote. Sasa sehemu ya kufurahisha: tucheze **mechi yako ya kwanza pamoja**. Ni mazoezi ya bure dhidi ya roboti, hakuna cha kupoteza. Nitakuambia la kufanya kila hatua.",
  "tut.practice.t": "Gusa Mazoezi",
  "tut.practice": "Gusa **Mazoezi** (iliyoangaziwa). Roboti na pesa za mchezo: bure, na bora kwa kujifunza.",
  "tut.raidPick.t": "Gusa Raid",
  "tut.raidPick": "Gusa kadi ya **Raid**: kusanya, pigana na utoke. Ya klasiki.",
  "tut.bag.t": "Begi lako",
  "tut.bag": "Tunacheza kwa **$1 ya pesa za mazoezi**. Ziko kwenye **mfuko** wako. Okota nyara ili uzito uongezeke. Mwangushe mkimbiaji na mfuko wake unakudondokea. Ukianguka, wako unamwendea yeye.\nIli uubaki nao, fika **njia ya kutoka katikati ya ramani** na ukae ndani yake **sekunde 10**. Kila mtu anaarifiwa kuwa unaondoka, na pigo linaanzisha hesabu upya.",
  "tut.play.t": "Gusa Cheza",
  "tut.play": "Gusa **Cheza**. Utaenda kwenye chumba cha maandalizi.",
  "tut.ready.t": "Bonyeza Tayari",
  "tut.ready": "Bonyeza **Tayari** na tunashuka!\nVidhibiti: **WASD** tembea, **kipanya** lenga, **bofya** piga risasi, **Space** ruka mbele, **Q** danganya ukubwa wa begi, **Tab** ubao wa alama. Kwenye simu: kidole gumba cha kushoto kinakusogeza, shikilia **Fire** upande wa kulia na inalenga yenyewe.",
  "tut.resultWon.t": "Umetoka!",
  "tut.resultWon": "Umeshinda uvamizi wako wa kwanza! Nilijua utaweza. Pesa za mazoezi ni za kujifunza tu. Gusa **Meza** kurudi kwenye menyu.",
  "tut.retry.t": "Jaribu tena",
  "tut.retry": "Umeangushwa: hutokea, mazoezi ni bure! Gusa **Cheza tena**. Safari hii okota nyara kidogo, kisha nenda **njia ya kutoka katikati** na ukae sekunde 10.",
  "tut.bye.t": "Uko tayari, mkimbiaji!",
  "tut.bye": "Sasa unaujua mchezo wote. Ushauri: anza na dau ndogo, fanya **kazi za kila siku**, dai **kalenda** kila siku na cheza na **marafiki**.\nUkinihitaji: **Mipangilio → Ziara**. Bahati njema huko nje!",
  "nav.g.play": "Cheza",
  "nav.g.store": "Duka",
  "nav.g.social": "Kijamii",
  "nav.g.you": "Wewe",
  "nav.s.ranked": "Panda madaraja",
  "nav.s.pass": "Zawadi za msimu",
  "nav.s.shop": "Masanduku, ofa, gurudumu",
  "nav.s.inventory": "Skini, masanduku, mtindo",
  "nav.s.swap": "Badilisha sarafu zako",
  "nav.s.chat": "Zungumza na kila mtu",
  "nav.s.friends": "Chezeni pamoja",
  "nav.s.guilds": "Koo na gumzo la kikundi",
  "nav.s.mail": "Barua na zawadi",
  "nav.s.invite": "Pata kutoka kwa marafiki",
  "nav.s.achievements": "Kalenda, kazi, mafanikio",
  "nav.s.settings": "Sauti, vidhibiti, lugha",
  "nav.d.pass": "Daraja {n} kati ya 50",
  "nav.d.store": "Duka jipya baada ya {t}",
  "nav.d.inv": "Masanduku {b} · mizunguko {s}",
  "nav.d.mail": "{n} hazijasomwa",
  "nav.d.tasks": "{n} tayari kudaiwa",
  "mcat.all": "Zote",
  "mcat.classic": "Klasiki",
  "mcat.weapons": "Silaha",
  "mcat.teams": "Timu",
  "mcat.events": "Matukio",
  "mc.hot": "Moto",
  "mc.season": "Msimu",
  "mi.waves": "Mawimbi",
  "mi.rounds": "Raundi {n} × {s}",
  "mi.win": "Jinsi ya kushinda:",
  "mi.tip": "Ushauri:",
  "mi.pays": "Inalipa:",
  "mi.rew": "XP ya cheo kwa kila kuua na kumaliza; inahesabiwa kwa kazi za kila siku na pasi ya vita.",
  "mi.players": "Wachezaji",
  "mi.time": "Mechi",
  "mi.now": "Sasa",
  "mi.win.raid": "Fika njia ya kutoka katikati ya ramani na ukae sekunde 10 (kila mtu anaonywa, pigo linaanzisha hesabu upya): kila kitu kwenye mfuko ni chako.",
  "mi.win.br": "Kuwa mkimbiaji wa mwisho aliyesimama: chungu chote ni chako.",
  "mi.win.duel": "Mshinde mkimbiaji mwingine ndani ya sekunde 90: unachukua dau zote mbili.",
  "mi.win.dm": "Aliyeua wengi zaidi muda unapoisha anachukua chungu. Unarudi uhai baada ya kila kifo.",
  "mi.win.gl": "Aliyeua wengi zaidi muda ukiisha anashinda. Kuua kunalipa mikopo ya vifaa vya huduma ya kwanza, mizinga ya ulinzi na mabomu ya leza.",
  "mi.win.hardcore": "Wa mwisho aliyesimama anachukua chungu. Pigo moja linatosha kukuangusha.",
  "mi.win.weapon": "Wa mwisho aliyesimama anachukua chungu, na silaha hiyo tu kwa kila mtu.",
  "mi.win.team": "Shinda raundi 2 kati ya 3 kama timu: timu inagawana chungu, hata walioanguka.",
  "mi.win.ranked": "Maliza juu na uue: ukadiriaji wako unapanda madaraja, na kila daraja jipya linalipa zawadi.",
  "mi.win.zombies": "Okoka mawimbi na hadi marafiki 3. Kila wimbi lililomalizwa linalipa XP.",
  "mi.win.gold": "Chukua mabegi mengi ya dhahabu kabla muda haujaisha: mshindi anapata $ ya duka.",
  "mi.tip.raid": "Kusanya kwanza, pigana baadaye: begi lililojaa linalotoka ni bora kuliko pambano kubwa unalopoteza.",
  "mi.tip.br": "Baki ndani ya eneo salama na waache wengine wapigane kwanza.",
  "mi.tip.duel": "Ruka mbele (Space) kupitia risasi zao na usisimame.",
  "mi.tip.dm": "Endelea kuua: kila kuua kunaboresha silaha yako.",
  "mi.tip.gl": "Tumia mikopo mapema: mzinga kwenye korido unakushindia mapambano.",
  "mi.tip.hardcore": "Sogea kutoka kizuizi hadi kizuizi: yeyote anaweza kukuangusha kwa risasi moja.",
  "mi.tip.weapon": "Jifunze umbali wa silaha na upigane pale tu inapokuwa na nguvu zaidi.",
  "mi.tip.team": "Baki na timu yako: bunduki mbili kwa adui mmoja zinashinda.",
  "mi.tip.ranked": "Okoka kwanza, ua baadaye: nafasi ina thamani sawa na kuua.",
  "mi.tip.zombies": "Simameni mgongo kwa mgongo na mhifadhi vifaa vya huduma kwa mawimbi makubwa.",
  "mi.tip.gold": "Chukua mabegi yaliyo karibu kwanza na usiingie vitani ukiwa umebeba mengi.",
  "goal.title": "Leo",
  "goal.cal": "Zawadi ya siku {d} iko tayari",
  "goal.claim": "Gusa kudai",
  "goal.tasks": "Kazi {a}/{b}",
  "goal.tasksS": "kazi za kila siku",
  "goal.first": "Ushindi wa kwanza leo",
  "goal.firstS": "+300 XP inasubiri",
  "goal.pass": "Daraja la pasi {n}",
  "goal.passP": "pasi ya premium",
  "goal.passF": "njia ya bure: nenda premium",
  "goal.card": "Insider: zawadi ya leo",
  "goal.vip": "VIP {n}: mizunguko ya kila siku",
  "goal.spins": "Mizunguko {n} ya bure",
  "goal.spinsS": "zungusha gurudumu",
  "vip.toNext": "{v} zaidi hadi VIP {n}",
  "vip.max": "Kiwango cha juu cha VIP",
  "vip.how": "VIP inakua kwa pesa halisi ulizolipa (kuongeza salio na malipo ya USDC/USDT), kamwe si kwa $ ya bure ya duka.",
  "vip.claim": "Dai mizunguko ×{n}",
  "vip.perks": "Viwango vyote na manufaa",
  "vip.paid": "Imelipwa",
  "vip.bonus": "Bonasi ya kuongeza salio",
  "vip.daily": "Kila siku",
  "vip.frame": "Fremu",
  "vip.note": "Manufaa ya VIP ni starehe na hadhi tu: kamwe si nguvu zaidi kwenye mechi.",
  "vip.got": "+{n} mizunguko ya gurudumu",
  "fw.all": "Zungusha zote ×{n}",
  "fw.allGot": "Mizunguko {n}: kila ulichoshinda",
  "inv.openAll": "Fungua yote ({n})",
  "inv.openN": "Fungua ×{n}",
  "bp.buyTier": "+{n} madaraja · {v}",
  "bp.tiersGot": "+{n} madaraja: sasa daraja {t}",
  "of.confirm": "Gusa tena: {v}",
  "of.once": "Mara moja tu",
  "of.starter": "Kifurushi cha mwanzo",
  "of.st.outfit": "Vazi la Epic la kudumu",
  "of.st.boxes": "Mabegi 2 ya Vault + kasha la Armory (nafasi kamili)",
  "of.st.spins": "Mizunguko {n} ya gurudumu",
  "of.buy": "Nunua · {v}",
  "of.k.outfit": "Vazi",
  "of.k.wskin": "Silaha",
  "of.k.style": "Mtindo",
  "of.owned": "Unacho",
  "of.card": "Kadi ya Insider",
  "of.cardOn": "Insider · siku {n} zimebaki",
  "of.cardDaily": "Kila siku: {v} ya duka + mzunguko {n}",
  "of.claimed": "Imedaiwa leo",
  "of.claim": "Dai ya leo",
  "of.extend": "+siku 30 · {v}",
  "of.cardTitle": "Kadi ya Insider · siku {d}",
  "of.c.now": "{v} ya duka papo hapo",
  "of.c.pass": "+{n}% XP ya pasi ya vita",
  "of.c.frame": "Fremu ya {n}, kwa kadi tu",
  "of.c.value": "Thamani ya {v} ya duka na mizunguko {s} kwa mwezi, ukidai kila siku.",
  "of.kicker": "Nunua moja kwa moja, bila bahati nasibu",
  "of.store": "Duka la leo",
  "of.newIn": "Seti mpya baada ya",
  "of.storeNote": "Skini sita kwa siku, sawa kwa kila mtu. Kamwe si toleo maalum au Exotic: hizo zinabaki kwenye masanduku.",
  "of.got": "Chako: {x}",
  "of.cardGot": "Kadi ya Insider imewashwa: siku {n}",
  "of.claimGot": "+{v} ya duka na mzunguko {n}",
  "of.starterGot": "Kifurushi cha mwanzo ni chako: fungua mabegi yako kwenye hifadhi",
  "fw.k.credit": "{v} ya duka",
  "fw.k.pass": "+{v} XP ya pasi",
  "fw.k.boost": "XP ×2 kwa mechi {n}",
  "fw.k.spin": "+1 mzunguko wa bure",
  "fw.k.box": "Zawadi: {name}",
  "fw.k.style": "Kitu cha mtindo {r}",
  "fw.free": "Mzunguko wa bure ×{n}",
  "fw.freeNote": "Mizunguko ya bure kutoka kazi, kalenda ya kila siku na barua inazungusha gurudumu hili. Gusa gurudumu kuzungusha.",
  "fw.again": "Zungusha tena",
  "fw.styleNote": "Kitu cha mtindo cha kudumu: kivae kwenye Hifadhi → Mtindo.",
  "fw.passNote": "Inahesabiwa kwa daraja la pasi yako ya vita.",
  "fw.boostNote": "Mechi yako ijayo inatoa XP mara mbili.",
  "fw.spinNote": "Mzunguko mmoja zaidi, bure kutoka kwetu.",
  "fw.boxNote": "Sanduku la zawadi kwenye hifadhi yako: linafika hadi Epic.",
  "dl.openBox": "Fungua {name}",
  "dl.spinNow": "Zungusha gurudumu",
  "inv.spins": "Mizunguko ya bure ya gurudumu",
  "vc.toggle": "Maikrofoni washa/zima (K)",
  "vc.peers": "sauti: {n}",
  "vc.micOn": "Maikrofoni imewashwa: wanakusikia. K kunyamazisha.",
  "vc.noMic": "Hakuna maikrofoni: iruhusu kwenye kivinjari ili uzungumze.",
  "set.vchat": "Gumzo la sauti",
  "set.vchatNote": "Sikia wachezaji kwenye mechi yako (aina za timu: timu yako). K inawasha na kuzima maikrofoni yako.",
  "sb.open": "Ubao wa alama (Tab)",
  "sb.title": "Ubao wa alama",
  "sb.hint": "shikilia Tab",
  "sb.player": "Mchezaji",
  "sb.k": "K",
  "sb.d": "D",
  "sb.ping": "Ping",
  "sb.bot": "roboti",
  "sb.zk": "Zombi",
  "sb.gb": "Dhahabu",
  "sb.yours": "Timu yako",
  "sb.theirs": "Timu ya adui",
  "rd.divPrize": "Zawadi ya daraja",
  "rd.divPrizes": "Zawadi za madaraja",
  "rd.divPrizesNote": "Fikia daraja ushinde zawadi yake, mara moja kwa msimu. Mtindo wa Legendary na Mythic unapatikana hapa na kwenye pasi ya vita.",
  "rd.styleOf": "Mtindo {r}",
  "inv.giftCap": "Zawadi {n}: hadi Epic",
  "shop.style": "Mtindo",
  "shop.styleNote": "Fremu, mabango, athari za kuua na rangi za majina zenye uhuishaji. Nakala zinarudisha $ ya duka.",
  "sty.title": "Mtindo",
  "sty.frame": "Fremu",
  "sty.banner": "Mabango",
  "sty.killfx": "Athari za kuua",
  "sty.namefx": "Majina",
  "sty.none": "Hakuna",
  "sty.worn": "imevaliwa",
  "sty.empty": "Hakuna kitu hapa bado: {n} za kupata kwenye masanduku ya Mtindo, kalenda ya kila siku na kazi.",
  "sty.get": "Pata mtindo",
  "box.s-street": "Sanduku la Mtindo wa Mtaani",
  "box.s-neon": "Sanduku la Mtindo wa Neon",
  "box.s-icon": "Sanduku la Mtindo wa Nyota",
  "ach.listTitle": "Mafanikio",
  "dl.g.credit": "{v} ya duka",
  "dl.g.spin": "Mzunguko {n}× wa gurudumu",
  "dl.g.pass": "+{n} XP ya pasi",
  "dl.g.xp": "+{n} XP",
  "dl.g.boost": "XP ×2 kwa mechi {n}",
  "dl.days": "siku {d} saa {h}",
  "dl.t.raids": "Cheza mechi {n}",
  "dl.t.kills": "Ua mara {n}",
  "dl.t.secs": "Tumia dakika {n} kwenye mechi",
  "dl.t.firstBloods": "Kuwa wa kwanza kuua mara {n}",
  "dl.t.extracts": "Toka mara {n}",
  "dl.t.pvpKills": "Ua wachezaji {n}",
  "dl.t.headshots": "Piga risasi {n} za kichwa",
  "dl.t.zKills": "Ua zombi {n}",
  "dl.t.goldBags": "Chukua mabegi {n} ya dhahabu",
  "dl.t.wins": "Shinda mara {n}",
  "dl.t.kKnife": "Ua {n} kwa kisu",
  "dl.t.kSniper": "Ua {n} kwa sniper",
  "dl.t.rankedGames": "Cheza mechi {n} za ranked",
  "dl.t.zClears": "Maliza mizunguko {n} ya zombi",
  "dl.calendar": "Zawadi za kila siku · siku 30",
  "dl.dayOf": "Siku {d} kati ya 30",
  "dl.lost": "Mfululizo ulivunjika: kurudi siku ya 1.",
  "dl.calNote": "Rudi kila siku mfululizo: zawadi zinakua, kila siku ya 7 ni kubwa.",
  "dl.best": "mfululizo bora {n}",
  "dl.next": "Zawadi ijayo baada ya {t}",
  "dl.claim": "Dai",
  "dl.done": "Imekamilika",
  "dl.today": "Kazi za leo",
  "dl.resets": "mpya baada ya {t}",
  "dl.sweep": "Zote tatu leo:",
  "dl.sweepGot": "Zote tatu zimekamilika leo! Bonasi:",
  "dl.week": "Wiki hii",
  "dl.boostLeft": "Mechi {n} zimebaki",
  "dl.boostNone": "bado hakuna nyongeza: ipate kwa kazi na kalenda",
  "dl.fwDone": "Ushindi wa kwanza wa siku: umechukuliwa",
  "dl.fwReady": "Ushindi wa kwanza wa siku: +300 XP inasubiri",
  "dl.todayDone": "kazi zilizokamilika leo",
  "dl.offline": "Zawadi za kila siku na kazi ni za mtandaoni tu.",
  "dl.signIn": "Ingia ili upate zawadi za kila siku na kazi.",
  "dl.dayGot": "Siku {d}: imedaiwa!",
  "dl.achGot": "Zawadi ya mafanikio",
  "dl.taskGot": "Kazi imekamilika!",
  "dl.reward": "Zawadi",
  "dl.nice": "Safi!",
  "dl.streak": "Siku {n} mfululizo",
  "dl.seeAll": "Ona kazi zote",
  "dl.taskDone": "Kazi {n} zimekamilika: dai zawadi kwenye ukurasa wa Kazi",
  "ach.habit": "Mazoea",
  "ach.devoted": "Mwaminifu",
  "ach.loyal": "Mtiifu",
  "ach.regular_face": "Uso wa Kawaida",
  "ach.dutiful": "Mwajibikaji",
  "ach.workhorse": "Mchapakazi",
  "ach.taskmaster": "Bingwa wa Kazi",
  "achd.streak": "Rudi siku {n} mfululizo",
  "achd.calDays": "Dai zawadi {n} za kila siku",
  "achd.tasksDone": "Kamilisha kazi {n}",
  "map.title": "Ramani",
  "map.any": "Ramani yoyote",
  "map.hint": "Kura nyingi zinashinda, sare kwa bahati nasibu",
  "map.hintNone": "Pigia kura ramani: kura nyingi zinashinda",
  "map.now": "Ramani: {m}",
  "map.docks": "Bandari za Usiku",
  "map.chain": "Blockchain",
  "map.lego": "Mji wa Matofali",
  "map.dunes": "Matuta Mekundu",
  "map.snow": "Baridi Kali",
  "map.lava": "Tanuru la Lava",
  "map.city": "Katikati ya Jiji",
  "map.neon": "Ukumbi wa Neon",
  "map.blackout": "Giza Totoro",
  "map.fantasy": "Ngome ya Joka",
  "map.toon": "Mji wa Katuni",
  "map.gravity": "Njia ya Mvuto",
  "map.speedway": "Uwanja wa Mbio Usiku",
  "map.skate": "Bustani ya Skate",
  "map.metro": "Treni ya Chini",
  "map.factory": "Kiwanda",
  "map.jungle": "Hekalu la Msituni",
  "map.junkyard": "Yadi ya Vyuma Chakavu",
  "map.moon": "Kituo cha Mwezi",
  "map.casino": "Kasino",
  "swap.rate": "Kiwango",
  "swap.impactK": "Athari ya bei",
  "swap.minGet": "Kiwango cha chini unachopata ({p}% slippage)",
  "swap.highImpact": "Athari kubwa ya bei: unapata kidogo sana kuliko bei ya soko. Jaribu kiasi kidogo.",
  "swap.pick": "Chagua sarafu",
  "swap.youPay": "Unalipa",
  "swap.youGet": "Unapata",
  "swap.balance": "Salio",
  "swap.inGame": "ndani ya mchezo",
  "swap.listNote": "Sarafu kutoka orodha iliyothibitishwa ya AVNU na orodha ya Ekubo.",
  "swap.empty": "Bado hakuna kitu kwenye salio lako la mchezo.",
  "rd.tabAll": "Wachezaji wote",
  "rd.tabSeason": "Msimu wa ranked",
  "rd.kd": "K/D",
  "rd.deaths": "Vifo",
  "rd.myPvp": "Takwimu zako za PvP",
  "rd.noPvp": "Cheza mechi ya PvP mtandaoni upate K/D yako.",
  "rd.emptyAll": "Bado hakuna mechi za PvP mtandaoni. Cheza moja uongoze ubao.",
  "rd.kdNote": "K/D = kuua ÷ vifo kwenye mechi za PvP mtandaoni (zombi hazihesabiwi). Mechi 3 ili kuorodheshwa kwa K/D.",
  "rd.sortBy": "Panga kwa",
  "rd.by.kd": "K/D",
  "rd.by.kills": "Kuua",
  "rd.by.xp": "XP ya cheo",
  "reg.table": "Seva: {r}",
  "reg.closer": "Iliyo karibu nawe: {r} ({ms} ms). Ichague kwenye ukumbi, na ucheze na wengine huko.",
  "net.connecting": "Inaunganisha na seva ya uvamizi…",
  "net.down": "Seva haipatikani. Inajaribu tena… Hali ya mazoezi inafanya kazi bila mtandao.",
  "net.lost": "Muunganisho umepotea. Umerudi mezani.",
  "q.pick": "Chagua sarafu ya kuweka dau.",
  "q.short": "Hakuna {c} ya kutosha kwa dau la {s}. Chagua sarafu nyingine au dau dogo.",
  "q.shortDeposit": "Hakuna {c} ya kutosha kwa dau la {s}. Chagua sarafu nyingine, dau dogo, au weka pesa.",
  "q.stable": "Unaweka dau la {s} kwa {c}. Toka ukiwa hai ubaki na kila unachobeba.",
  "q.coin": "Unaweka dau {a} = {s} kwa bei ya leo. Ushindi unarudi kwa {c} kwa kiwango kilekile.",
  "tb.live": "Uvamizi unaendelea · {t}",
  "tb.ready": "{n} tayari · {s}s",
  "tb.waiting": "{n} wanasubiri",
  "tb.golden": "Uvamizi wa dhahabu ujao",
  "tb.jackpot": "Jackpot {v}",
  "pcfg.title": "Mipangilio ya mazoezi",
  "pcfg.difficulty": "Roboti",
  "pcfg.easy": "Rahisi",
  "pcfg.normal": "Kawaida",
  "pcfg.hard": "Ngumu",
  "pcfg.runners": "Wakimbiaji kwenye uvamizi",
  "pcfg.time": "Urefu wa uvamizi",
  "rk.max": "cheo cha juu",
  "rk.toNext": "{x} XP hadi cheo {r}",
  "rk.of": "Cheo {r} kati ya 90",
  "rk.rank": "Cheo",
  "rk.up": "Kupanda cheo",
  "rk.xp": "XP ya cheo",
  "xp.Raid": "Uvamizi",
  "xp.kills": "Kuua {n}",
  "xp.Damage": "Madhara",
  "xp.Time alive": "Muda hai",
  "xp.First blood": "Kuua kwa kwanza",
  "xp.Double kill": "Kuua mara mbili",
  "xp.Triple kill": "Kuua mara tatu",
  "xp.Rampage": "Ghasia",
  "xp.Godlike": "Kama mungu",
  "xp.Full arsenal": "Silaha kamili",
  "xp.Extracted": "Umetoka",
  "xp.Profit": "Faida",
  "xp.Practice \u00d70.5": "Mazoezi ×0.5",
  "rk.newRank": "Cheo kipya",
  "rw.continue": "Endelea",
  "rw.title": "Zawadi ya kupanda cheo",
  "rw.trial": "chako kuvaa kwa saa 1",
  "rw.try": "Jaribu kuvaa",
  "rw.share": "Shiriki kupanda cheo",
  "prep.raid": "Uvamizi {n} · dau {s}",
  "prep.readyUp": "Jiandae",
  "prep.first": "Hesabu inaanza mkimbiaji wa kwanza anapokuwa tayari.",
  "prep.live": "Uvamizi unaendelea. Jiandae sasa na mtashuka pamoja kwenye unaofuata.",
  "prep.over": "Uvamizi umeisha. Chumba cha maandalizi kinafunguliwa punde.",
  "prep.many": "Kila mtu hapa anaanza na kisu. Roboti zinajiunga sekunde za mwisho.",
  "prep.bots": "Roboti zinajaza nafasi tupu sekunde za mwisho.",
  "prep.open": "wazi",
  "prep.pot": "Chungu",
  "prep.cancel": "Ghairi · rudisha {v}",
  "prep.ready": "Tayari · dau {v}",
  "prep.back": "Rudi mezani",
  "hud.bagPrivate": "Begi lako · siri",
  "hud.lag": "Seva haijibu · inaunganisha upya…",
  "hud.golden": "Uvamizi wa dhahabu",
  "hud.goldenStart": "Uvamizi wa dhahabu · ngawira ya jackpot ndani",
  "hud.start": "Kisu mkononi · okota machungwa · njia ya kutoka iko katikati",
  "hud.bagOpened": "Begi limefunguliwa · +{v}",
  "hud.arsenal": "Silaha zimekamilika · kurudi kwa bastola ★",
  "hud.unlocked": "{w} imefunguliwa",
  "hud.pnl": "{d} dhidi ya dau {s}",
  "hud.alive": "{n} ndani",
  "hud.next": "Inayofuata: {w}",
  "hud.final": "Duara la mwisho · njia ya mwisho ya kutokea",
  "hud.closing": "Dhoruba inafunga · {t}",
  "hud.stormIn": "Dhoruba inasonga baada ya {t}",
  "hud.dash": "Ruka mbele",
  "hud.bagLook": "Mwonekano wa begi",
  "hud.extracting": "Unatoka",
  "hud.someoneOut": "⚠ {name} anatoka · sekunde {s} kumzuia!",
  "hud.holdStill": "Tulia. Pigo linairudisha mwanzo.",
  "hud.sound": "Sauti",
  "hud.music": "Muziki",
  "bluff.0": "dogo",
  "bluff.1": "wastani",
  "bluff.2": "nono",
  "touch.move": "sogea",
  "touch.aim": "lenga · piga",
  "touch.bag": "Begi",
  "w.Knife": "Kisu",
  "w.Pistol": "Bastola",
  "w.Shotgun": "Shotgun",
  "w.SMG": "SMG",
  "w.Rifle": "Bunduki",
  "w.Laser sniper": "Sniper ya leza",
  "w.Hand Cannon": "Kanuni ya Mkono",
  "w.Auto Shotgun": "Shotgun ya Otomatiki",
  "w.PDW": "PDW",
  "w.Carbine": "Karabini",
  "w.Scout": "Skauti",
  "w.Machine Gun": "Bunduki ya Rashasha",
  "w.Magnum Sniper": "Sniper ya Magnum",
  "hud.reloading": "Inajaza risasi",
  "streak.1": "Kuua kwa kwanza",
  "streak.2": "Kuua mara mbili",
  "streak.3": "Kuua mara tatu",
  "streak.4": "Ghasia",
  "streak.5": "Kama mungu",
  "streak.you1": "Umeua wa kwanza",
  "feed.storm": "Dhoruba ilikuchukua",
  "feed.droppedYou": "{name} amekuangusha",
  "coach.storm": "Uko kwenye dhoruba · rudi ndani ya duara",
  "coach.touch": "Kidole gumba cha kushoto kinakusogeza · shikilia Fire: inamlenga adui wa karibu kwa ajili yako",
  "coach.keys": "WASD kutembea · kipanya kulenga · bofya kushambulia",
  "coach.exit": "Wakati wa kutoka · NJIA YA KUTOKA iko katikati · kaa sekunde 10 · mishale inaonyesha njia",
  "coach.loot": "Chukua ngawira ya chungwa · inaingia kwenye begi lako",
  "coach.kills": "Kuua kunaboresha silaha yako · Space kuruka mbele",
  "coach.killsTouch": "Kuua kunaboresha silaha yako · gusa Dash kukwepa",
  "spect.watching": "Unamtazama {name} · ◀ ▶ kubadilisha",
  "spect.down": "Umeanguka",
  "spect.results": "Matokeo",
  "res.extracted": "Umetoka",
  "res.storm": "Umemezwa na dhoruba",
  "res.dropped": "Umeangushwa",
  "res.sealed": "Umefungiwa ndani",
  "res.inside": "Kuua {k} · {t} ndani",
  "res.out": "Umetoka na {p} kwa dau la {s}: {d}.",
  "res.paid": "Imelipwa {v} kwa kiwango cha kuingia kwako.",
  "res.killer": "{n} ana begi lako sasa. Lilikuwa na {v}, na ni nyinyi wawili tu mtakaojua.",
  "res.inStorm": "Begi lako, {v}, liko kwenye dhoruba kwa yeyote mwenye ujasiri.",
  "res.sealedText": "Uvamizi ulifungwa ukiwa bado ndani. {v} yako imeingia kwenye ngawira ya uvamizi unaofuata.",
  "res.again": "Cheza tena",
  "res.tables": "Meza",
  "res.share": "Shiriki kadi",
  "share.title": "Shiriki",
  "share.x": "Chapisha kwenye 𝕏",
  "share.copy": "Nakili picha",
  "share.save": "Hifadhi PNG",
  "share.close": "Funga",
  "lk.title": "Kabati",
  "lk.outfits": "Mavazi",
  "lk.shop": "Duka",
  "lk.bags": "Mabegi ya bahati",
  "lk.sortDesc": "Adimu kwanza ↓",
  "lk.sortAsc": "Ya kawaida kwanza ↑",
  "lk.allGuns": "Bunduki zote",
  "lk.takeOff": "Vua",
  "lk.empty": "Hakuna kitu hapa bado: mabegi na makasha dukani yanajaza mkusanyiko wako.",
  "lk.emptyTurrets": "Bado hakuna skini za mizinga: zinatoka kwenye pasi ya vita.",
  "lk.pickSkin": "Gusa skini kuiona, kisha uivae.",
  "lk.all": "Zote",
  "lk.owned": "Unazo",
  "lk.him": "Yeye (m)",
  "lk.her": "Yeye (k)",
  "lk.shopUsd": "$ ya duka",
  "lk.shopNote": "Ongeza $ ya duka kwa USDC au USDT (vifurushi vikubwa vinaongeza bonasi). $ ya duka inatumika hapa tu na haiwezi kutolewa. Huna $ ya duka ya kutosha? Tofauti inatoka kwenye USDC/USDT yako.",
  "lk.bagsNote": "Nafasi kamili, zinazochezwa kwenye seva. Hakuna nakala hadi umiliki daraja zima, na nakala inarudisha 10% ya bei yake kama $ ya duka. Dhamana: Epic+ ndani ya mafunguo 15 na Legendary+ ndani ya 60.",
  "lk.topupFrom": "+ {v} USDC/USDT ya kuongezea",
  "lk.collected": "{a} / {b} zimekusanywa",
  "lk.equipped": "Imevaliwa",
  "lk.equip": "Vaa",
  "lk.buy": "Nunua",
  "lk.trialLeft": "Jaribio · {t} imebaki",
  "lk.trialHow": "Jaribio la kupanda cheo: ni lako kwa {t} zaidi. Linunue ulibakishe.",
  "lk.free": "Bure kwa kila mkimbiaji.",
  "lk.inCollection": "Kwenye mkusanyiko wako.",
  "lk.buyOrBag": "Linunue hapa, au jaribu bahati yako na begi.",
  "lk.tryingOn": "Unajaribu kuvaa.",
  "lk.bonus": "+{n}% bonasi",
  "lk.pay": "lipa {v}",
  "lk.jackpot": "Jackpot",
  "lk.epicIn": "Epic+ ndani ya",
  "lk.legIn": "Legendary+ ndani ya",
  "lk.openFree": "Fungua · bure",
  "lk.buyOpen": "Nunua na ufungue",
  "lk.pityDrop": "zawadi ya dhamana",
  "lk.dup": "Tayari ni chako · {v} imerudishwa",
  "lk.new": "<b>Mpya</b> kwenye mkusanyiko wako",
  "lk.jackpotIs": "jackpot ni {r}",
  "lk.showOff": "Jionyeshe kwenye X",
  "lk.postMiss": "Chapisha kukosa kwenye X",
  "lk.another": "Fungua jingine",
  "lk.free1": "bure",
  "lk.back": "Rudi kabatini",
  "lk.yours": "{n} ni chako.",
  "r.common": "Kawaida",
  "r.rare": "Adimu",
  "r.epic": "Epic",
  "r.legendary": "Legendary",
  "r.mythic": "Mythic",
  "r.exotic": "Exotic",
  "ach.title": "Kazi na mafanikio",
  "ach.button": "Mafanikio",
  "ach.intro": "Kila moja linalipa XP ya cheo mara moja na kufungua jina lake kama cheo unachoweza kuvaa.",
  "ach.wear": "Vaa cheo",
  "ach.worn": "Kimevaliwa",
  "ach.wearing": "Cheo:",
  "ach.takeOff": "vua",
  "ach.noTitle": "Hakuna cheo",
  "ach.unlocked": "Mafanikio yamefunguliwa",
  "ach.seeAll": "Mafanikio yote",
  "achd.raids": "Cheza uvamizi {n}",
  "achd.extracts": "Toka mara {n}",
  "achd.kills": "Ua mara {n}",
  "achd.bestKills": "Kuua {n} katika uvamizi mmoja",
  "achd.bestMulti": "Kuua mfululizo {n}×",
  "achd.prestige": "Maliza silaha zote mara {n}",
  "achd.firstBloods": "Kuwa wa kwanza kuua mara {n}",
  "achd.secs": "Tumia saa {n} ndani ya uvamizi",
  "achd.bestReturn": "Toka na mara {n} ya dau lako",
  "achd.golden": "Toka kwenye uvamizi wa dhahabu",
  "achd.lastExit": "Toka kupitia njia ya mwisho",
  "achd.pacifist": "Toka bila kuua hata mmoja",
  "achd.rank": "Fikia cheo {n}",
  "achd.outfits": "Miliki mavazi {n}",
  "ach.gunslinger": "Mpiga Bastola",
  "ach.close_quarters": "Karibu Sana",
  "ach.spray_and_pray": "Nyunyiza na Uombe",
  "ach.rifleman": "Mpiga Bunduki",
  "ach.marksman": "Mlengaji",
  "ach.deadeye": "Jicho la Kifo",
  "ach.blade_dancer": "Mcheza Kisu",
  "ach.shadow_blade": "Kisu cha Kivuli",
  "ach.deathmatch_king": "Mfalme wa Deathmatch",
  "ach.duelist": "Mpiganaji Pambano",
  "ach.squad_goals": "Malengo ya Kikosi",
  "ach.one_shot_one_kill": "Risasi Moja Kifo Kimoja",
  "ach.specialist": "Mtaalamu",
  "ach.engineer": "Mhandisi",
  "ach.ranked_debut": "Mwanzo wa Ranked",
  "ach.ranked_grinder": "Mvumilivu wa Ranked",
  "ach.ranked_victor": "Mshindi wa Ranked",
  "ach.gold_league": "Ligi ya Dhahabu",
  "ach.diamond_league": "Ligi ya Almasi",
  "ach.neon_legend": "Hadithi ya Neon",
  "ach.unboxer": "Mfunguaji",
  "ach.case_hunter": "Mwindaji wa Masanduku",
  "ach.case_lord": "Bwana wa Masanduku",
  "ach.armory": "Ghala la Silaha",
  "ach.arsenal_baron": "Bwana wa Silaha",
  "ach.pass_holder": "Mwenye Pasi",
  "ach.pass_maxed": "Pasi Imekamilika",
  "ach.neon_bearer": "Mbeba Neon",
  "ach.by_a_thread": "Kwa Uzi Mmoja",
  "ach.untouchable": "Asiyeguswa",
  "ach.ghost_walker": "Mtembea Kivuli",
  "ach.one_tap": "Mguso Mmoja",
  "achd.kHandgun": "Ua {n} kwa bastola",
  "achd.kShotgun": "Ua {n} kwa shotgun",
  "achd.kSmg": "Ua {n} kwa SMG",
  "achd.kRifle": "Ua {n} kwa bunduki na rashasha",
  "achd.kSniper": "Ua {n} kwa sniper",
  "achd.kKnife": "Ua {n} kwa kisu",
  "achd.dmWins": "Shinda deathmatch {n}",
  "achd.duelWins": "Shinda mapambano {n} ya wawili",
  "achd.teamWins": "Shinda mechi {n} za timu",
  "achd.hcWins": "Shinda mechi {n} za hardcore",
  "achd.weaponWins": "Shinda mechi {n} za silaha moja",
  "achd.turretKills": "Ua {n} kwa mizinga kwenye Guns + Lasers",
  "achd.rankedGames": "Cheza mechi {n} za ranked",
  "achd.rankedWins": "Shinda mechi {n} za ranked",
  "achd.bestDiv": "Fikia {n} kwenye ranked",
  "achd.opened": "Fungua masanduku na mabegi {n}",
  "achd.wskins": "Miliki skini {n} za silaha",
  "achd.passTier": "Fikia daraja {n} la pasi ya vita",
  "achd.stitles": "Shinda cheo cha msimu",
  "achd.clutch": "Toka ukiwa na afya 10 au chini",
  "achd.flawless": "Toka baada ya dakika 2+ bila kupigwa",
  "achd.ninjaWin": "Shinda aina ya chungu bila kuua hata mmoja",
  "achd.oneShots": "Waangushe wakimbiaji {n} kutoka afya kamili hadi sifuri kwa pigo moja",
  "ach.secret": "Siri",
  "ach.secretDesc": "Endelea kucheza: hili linajifichua unapolipata.",
  "r.mystery": "Fumbo",
  "ach.rookie": "Mgeni",
  "ach.regular": "Wa Kawaida",
  "ach.veteran": "Mkongwe",
  "ach.lifer": "Wa Maisha",
  "ach.eternal": "Wa Milele",
  "ach.escape_artist": "Fundi wa Kutoroka",
  "ach.ghost": "Mzimu",
  "ach.smuggler": "Mfanya Magendo",
  "ach.phantom": "Kivuli",
  "ach.first_kill": "Kuua kwa Kwanza",
  "ach.hunter": "Mwindaji",
  "ach.butcher": "Mchinjaji",
  "ach.reaper": "Mvunaji",
  "ach.apex": "Kilele",
  "ach.rampage": "Ghasia",
  "ach.one_man_army": "Jeshi la Mtu Mmoja",
  "ach.double_tap": "Mara Mbili",
  "ach.triple_threat": "Tishio Mara Tatu",
  "ach.godlike": "Kama Mungu",
  "ach.full_arsenal": "Silaha Kamili",
  "ach.arsenal_master": "Bingwa wa Silaha",
  "ach.first_blood": "Damu ya Kwanza",
  "ach.opener": "Mfunguaji",
  "ach.night_shift": "Zamu ya Usiku",
  "ach.insomniac": "Asiyelala",
  "ach.double_up": "Mara Mbili Zaidi",
  "ach.big_bag": "Begi Kubwa",
  "ach.gold_rush": "Kimbilio la Dhahabu",
  "ach.last_one_out": "Wa Mwisho Kutoka",
  "ach.pacifist": "Mpenda Amani",
  "ach.seasoned": "Mzoefu",
  "ach.officer": "Afisa",
  "ach.commander": "Kamanda",
  "ach.legend": "Hadithi",
  "ach.collector": "Mkusanyaji",
  "ach.curator": "Mtunzaji",
  "ach.hoarder": "Mlimbikizaji",
  "intro.tag": "Weka dau. Kusanya. Toka.",
  "intro.go": "Ingia",
  "intro.fonts": "Tunanoa visu…",
  "intro.world": "Tunapaka giza…",
  "intro.connect": "Tunatafuta uvamizi…",
  "intro.profile": "Tunafunga begi lako…",
  "intro.ready": "Tayari",
  "tb.wallet": "Pochi",
  "tb.shop": "$ ya duka",
  "nav.play": "Cheza",
  "nav.shop": "Duka",
  "nav.inventory": "Hifadhi",
  "nav.swap": "Badilisha",
  "nav.chat": "Gumzo",
  "nav.achievements": "Kazi",
  "nav.pass": "Pasi",
  "bp.season": "Msimu {n}",
  "bp.ends": "inaisha baada ya siku {d} saa {h}",
  "bp.tier": "Daraja {n}/{m}",
  "bp.xp": "{a}/{b} XP hadi daraja linalofuata",
  "bp.maxed": "Madaraja yote yamekamilika",
  "bp.how": "Kila uvamizi unajaza pasi kwa XP ileile ya cheo chako.",
  "bp.free": "Bure",
  "bp.premium": "Premium",
  "bp.buy": "Pasi ya premium · {v}",
  "bp.owned": "Premium imewashwa",
  "bp.perks": "Madaraja yote 50 ya zawadi: siraha za Warlord na Apex, skini 2 za mizinga, skini 5 za silaha za msimu, masanduku na $.",
  "bp.claim": "Dai",
  "bp.claimAll": "Dai zote ({n})",
  "bp.claimed": "Imedaiwa",
  "bp.limited": "Msimu huu tu",
  "bp.turrets": "Skini za mizinga",
  "bp.turretsNote": "Mizinga yako kwenye Guns + Lasers.",
  "bp.equip": "Vaa",
  "bp.equipped": "Imevaliwa",
  "bp.none": "Kawaida",
  "bp.up": "Pasi ya vita: daraja {n}!",
  "bp.got": "Imedaiwa: {x}",
  "bp.credit": "+{v} salio la duka",
  "mode.ranked": "Ranked",
  "mode.ranked.d": "Battle royale kwa ukadiriaji wa msimu wako. Panda kutoka Shaba hadi Hadithi ya Neon; walio juu wanashinda mzunguko wa bonasi.",
  "nav.ranked": "Ranked",
  "rd.title": "Ranked · Msimu {n}",
  "rd.pos": "#{n} kati ya {m}",
  "rd.unranked": "Cheza mechi ya ranked uingie kwenye jedwali.",
  "rd.play": "Cheza ranked",
  "rd.games": "Mechi",
  "rd.wins": "Ushindi",
  "rd.top3": "3 Bora",
  "rd.kills": "Kuua",
  "rd.winrate": "Kiwango cha ushindi",
  "rd.player": "Mkimbiaji",
  "rd.div": "Daraja",
  "rd.div.bronze": "Shaba",
  "rd.div.silver": "Fedha",
  "rd.div.gold": "Dhahabu",
  "rd.div.platinum": "Platinamu",
  "rd.div.diamond": "Almasi",
  "rd.div.master": "Bingwa",
  "rd.div.legend": "Hadithi ya Neon",
  "rd.titles": "Vyeo vya msimu",
  "rd.titlesNote": "Hupatikana kwenye mzunguko wa bonasi wa ranked. Huvaliwa kwa neon juu ya jina lako, na XP ya bonasi hadi msimu uishe.",
  "rd.wear": "Vaa",
  "rd.off": "Vua",
  "rd.bonus": "+{p}% XP",
  "rd.expired": "msimu umeisha",
  "rd.board": "Ubao wa wanaoongoza wa msimu",
  "rd.empty": "Hakuna aliyecheza ranked msimu huu bado. Kuwa wa kwanza.",
  "rd.place": "Nafasi #{p} kati ya {n}",
  "rd.promoted": "umepanda!",
  "rd.demoted": "umeshuka",
  "rd.practice": "Mazoezi: ukadiriaji wako haubadiliki.",
  "rd.spin": "Mzunguko wa bonasi",
  "rd.spinWhy": "kwa nafasi #{p}",
  "rd.won": "Umeshinda:",
  "rd.wornNow": "Cheo chako kipya kimewashwa, kwa neon.",
  "st.contender": "Mshindani",
  "st.elite": "Wasomi",
  "st.champion": "Bingwa",
  "xp.Season title": "Cheo cha msimu",
  "news.title": "Nini kipya",
  "news.ok": "Nimeelewa",
  "news.note": "Kila sasisho, na tarehe na saa yake.",
  "news.open": "Fungua",
  "stake.own": "Dau lako",
  "stake.range": "Dau kutoka $0.10 hadi $10,000",
  "nav.settings": "Mipangilio",
  "nav.more": "Zaidi",
  "modes.title": "Aina ya mchezo",
  "kind.raid": "kutoroka",
  "kind.br": "mshindi anachukua chungu",
  "kind.team": "chungu cha timu",
  "mode.raid": "Raid",
  "mode.raid.d": "Pora, pigana, kisha kaa sekunde 10 kwenye njia ya kutoka katikati. Unabaki na unachobeba.",
  "mode.br": "Battle Royale",
  "mode.br.d": "Hadi wakimbiaji 20. Wa mwisho aliyesimama anachukua chungu chote.",
  "mode.duel": "Pambano la Wawili",
  "mode.duel.d": "Mmoja dhidi ya mmoja. Mshindi anachukua dau zote mbili.",
  "mode.knives": "Visu tu",
  "mode.knives.d": "Visu tu, uvamizi wote. Wa mwisho aliyesimama anashinda.",
  "mode.pistols": "Bastola tu",
  "mode.pistols.d": "Bastola tu. Wa mwisho aliyesimama anashinda.",
  "mode.shotguns": "Shotgun tu",
  "mode.shotguns.d": "Karibu na kwa kelele. Wa mwisho aliyesimama anashinda.",
  "mode.rifles": "Bunduki tu",
  "mode.rifles.d": "Mapigano ya umbali wa kati. Wa mwisho aliyesimama anashinda.",
  "mode.snipers": "Sniper tu",
  "mode.snipers.d": "Lenzi za leza kila mahali. Wa mwisho aliyesimama anashinda.",
  "mode.team2": "Timu 2 v 2",
  "mode.team2.d": "Kila dau linakuza chungu kimoja. Timu ya mwisho iliyosimama inakigawana.",
  "mode.team4": "Timu 4 v 4",
  "mode.team4.d": "Kila dau linakuza chungu kimoja. Timu ya mwisho iliyosimama inakigawana.",
  "mode.team8": "Timu 8 v 8",
  "mode.team8.d": "Kila dau linakuza chungu kimoja. Timu ya mwisho iliyosimama inakigawana.",
  "hud.pot": "Chungu cha zawadi",
  "hud.left": "{n} wamebaki · dau {s}",
  "hud.teamsLeft": "Timu {n} zimebaki · dau {s}",
  "hud.startPot": "Wa mwisho aliyesimama anachukua chungu",
  "hud.startTeam": "Baki na timu yako · futa upande mwingine",
  "hud.goldenPot": "Uvamizi wa dhahabu · jackpot imeongezwa kwenye chungu",
  "coach.pot": "Hakuna njia za kutokea hapa · baki ndani ya duara · wa mwisho aliyesimama anashinda",
  "coach.team": "Majina ya kijani ni timu yako · majina mekundu ni adui",
  "warn.exit30": "Muda unaisha · nenda njia ya kutoka katikati",
  "warn.exit10": "Nafasi ya mwisho · anza kukaa sekunde 10 sasa au upoteze yote",
  "warn.pot30": "30s · dhoruba inakaribia",
  "warn.pot10": "10s · wakimbiaji wengi walio hai wanashinda",
  "storm.final": "Kuporomoka kwa mwisho · njia ya mwisho tu",
  "storm.finalPot": "Kuporomoka kwa mwisho · hakuna pa kujificha",
  "storm.closing": "Dhoruba inakaribia",
  "storm.in5": "Dhoruba inasonga baada ya 5s",
  "feed.youDropped": "Umemwangusha {name}",
  "feed.stormTook": "{name} amemezwa na dhoruba",
  "feed.dropped": "{a} amemwangusha {b}",
  "feed.down": "{name} ameanguka",
  "feed.extracted": "{name} ametoka",
  "feed.exitClosed": "Njia {name} imefungwa",
  "spect.settling": "Matokeo yako yanakuja uvamizi ukimalizika.",
  "res.victory": "Ushindi",
  "res.teamWon": "Timu yako imeshinda",
  "res.defeated": "Umeshindwa",
  "res.wonText": "Umechukua {p} kwa dau la {s}.",
  "res.lostPot": "Chungu kimeenda kwa wa mwisho aliyesimama.",
  "res.teamLost": "Timu nyingine imechukua chungu.",
  "xp.Victory": "Ushindi",
  "ach.champion": "Bingwa",
  "ach.warlord": "Mbabe wa Vita",
  "achd.wins": "Shinda uvamizi {n} wa chungu",
  "lk.weapons": "Skini za silaha",
  "lk.onlyBags": "Skini zinatoka tu kwenye mabegi na makasha dukani.",
  "lk.toShop": "Fungua duka",
  "lk.toOpen": "{n} za kufungua",
  "lk.limited": "Toleo maalum · {n}",
  "lk.minted": "{a} kati ya {b} zimetengenezwa",
  "lk.plain": "Kawaida",
  "lk.fromBags": "Hutoka kwenye mabegi ya mavazi dukani.",
  "lk.fromCrates": "Hutoka kwenye makasha ya silaha dukani.",
  "lk.trialHow2": "Jaribio la kupanda cheo: ni lako kwa {t} zaidi.",
  "lk.weaponHow": "Chagua umaliziaji unaomiliki ili uuvae. Kila mtu kwenye uvamizi anauona.",
  "fx.glow": "mng'ao",
  "fx.pulse": "mng'ao unaodunda",
  "fx.ghost": "wa kimizimu",
  "fx.laser": "macho ya leza",
  "fx.rainbow": "ya rangi zote",
  "fx.fire": "inayowaka",
  "fx.gold": "dhahabu ya majimaji",
  "fx.holo": "hologramu",
  "fx.glitch": "hitilafu",
  "fx.lightning": "radi",
  "fx.galaxy": "galaksi",
  "fx.sparks": "cheche",
  "fx.frost": "barafu",
  "fx.money": "mvua ya pesa",
  "fx.matrix": "mvua ya msimbo",
  "fx.shadow": "moshi wa kivuli",
  "fx.cape": "joho",
  "box.c-samurai": "Sanduku la Samurai wa Kidijitali",
  "box.c-neon": "Sanduku la Usiku wa Neon",
  "box.c-arctic": "Sanduku la Operesheni za Aktiki",
  "box.c-inferno": "Sanduku la Moto Mkali",
  "box.c-crypto": "Sanduku la Wafalme wa Crypto",
  "box.c-toxic": "Sanduku la Jangwa la Sumu",
  "box.c-toon": "Sanduku la Mji wa Katuni",
  "box.c-knife": "Sanduku la Visu",
  "box.c-pistol": "Sanduku la Bastola",
  "box.c-smg": "Sanduku la SMG",
  "box.c-rifle": "Sanduku la Bunduki",
  "box.c-heavy": "Sanduku Zito",
  "box.c-sniper": "Sanduku la Sniper",
  "box.b-crypto": "Begi la Memes za Crypto",
  "box.b-heroes": "Begi la Mashujaa wa Ulimwengu",
  "box.b-monsters": "Begi la Majitu na Hadithi",
  "box.b-cyber": "Begi la Mtaa wa Kidijitali",
  "box.b-toon": "Begi la Marafiki wa Katuni",
  "shop.g.theme": "Mikusanyiko",
  "shop.g.class": "Masanduku ya aina za bunduki",
  "shop.g.tier": "Masanduku ya madaraja",
  "shop.contents": "Ndani · vitu {n}",
  "box.street": "Begi la Mtaani",
  "box.vault": "Begi la Hazina",
  "box.golden": "Begi la Dhahabu",
  "box.elite": "Begi la Wasomi",
  "box.diamond": "Begi la Almasi",
  "box.obsidian": "Begi la Obsidian",
  "box.royal": "Begi la Kifalme",
  "box.apex": "Begi la Kilele",
  "box.genesis": "Begi la Mwanzo",
  "box.w-scrap": "Kasha la Chuma Chakavu",
  "box.w-armory": "Kasha la Ghala",
  "box.w-brass": "Kasha la Shaba",
  "box.w-specops": "Kasha la Operesheni Maalum",
  "box.w-diamond": "Kasha la Almasi",
  "box.w-obsidian": "Kasha la Obsidian",
  "box.w-royal": "Kasha la Kifalme",
  "box.w-apex": "Kasha la Kilele",
  "box.w-genesis": "Kasha la Mwanzo",
  "shop.topup": "Ongeza $ ya duka",
  "shop.bags": "Mabegi ya mavazi",
  "shop.crates": "Makasha ya silaha",
  "shop.bagsNote": "Mavazi ya mkimbiaji wako. Madaraja tisa: kadiri begi lilivyo ghali, ndivyo nafasi zinavyokuwa bora.",
  "shop.cratesNote": "Skini za bunduki na kisu chako, zinauzwa tofauti na mavazi. Madaraja tisa.",
  "shop.fair": "Nafasi ni kamili na zinachezwa kwenye seva. Dhamana: Epic+ ndani ya mafunguo {e}, Legendary+ ndani ya {l}.",
  "shop.odds": "Nafasi na dhamana",
  "shop.qty": "Ngapi",
  "shop.open": "Fungua ×{n}",
  "shop.limited": "Matoleo maalum",
  "shop.soldOut": "Zimeisha",
  "shop.dup": "Nakala · +{v}",
  "shop.new": "Mpya",
  "shop.back": "{v} imerudishwa",
  "shop.equipBest": "Vaa {n}",
  "inv.wallet": "Pochi",
  "inv.deposit": "Weka · toa",
  "inv.walletNote": "Tokeni halisi zinazoshikiliwa na nyumba kwa ajili yako. Toa wakati wowote kwenda anwani uliyoingia nayo.",
  "inv.playNote": "Pesa za mchezo kwenye kivinjari hiki. Jaza wakati wowote.",
  "inv.shopNote": "Inanunuliwa kwa USDC/USDT, inatumika tu kwa mabegi na makasha. Haiwezi kutolewa.",
  "inv.unopened": "Hayajafunguliwa",
  "inv.collection": "Mkusanyiko",
  "inv.opened": "Yaliyofunguliwa",
  "inv.career": "Taaluma",
  "inv.raids": "Uvamizi",
  "inv.kills": "Kuua",
  "inv.extracts": "Kutoka",
  "inv.wins": "Ushindi wa chungu",
  "inv.best": "Uvamizi bora (kuua)",
  "inv.time": "Muda ndani",
  "swap.game": "Salio la mchezo",
  "swap.gameNote": "Papo hapo, kwa bei ya sasa, ada ya {f}%.",
  "swap.gameOff": "Kubadilisha ndani ya mchezo kumezimwa kwenye seva hii. Tumia kubadilisha kwa pochi hapa chini.",
  "swap.from": "Kutoka",
  "swap.to": "Kwenda",
  "swap.have": "Unazo",
  "swap.flip": "Geuza mwelekeo",
  "swap.go": "Badilisha",
  "swap.short": "Haitoshi",
  "swap.done": "Umebadilisha {a} kwa {b}.",
  "swap.wallet": "Pochi yako",
  "swap.signIn": "Ingia kwa pochi ya Starknet ili ubadilishe huko kupitia AVNU.",
  "swap.needChain": "Kubadilisha kwa AVNU kunafanya kazi na pochi halisi ya Starknet kwenye hali ya Mtandaoni.",
  "swap.slippage": "Slippage ya juu",
  "swap.quoting": "Inatafuta njia bora…",
  "swap.impact": "athari ya bei {p}%",
  "swap.goAvnu": "Badilisha kwa AVNU",
  "swap.noQuote": "Hakuna njia kwa jozi hiyo sasa hivi.",
  "swap.sent": "Ubadilishaji umetumwa: {tx}",
  "swap.walletNote": "Inapitishwa na AVNU kupitia masoko ya Starknet. Unasaini kwenye pochi yako; mchezo haushikilii tokeni hizi kamwe.",
  "chat.ph": "Sema kitu…",
  "chat.send": "Tuma",
  "chat.empty": "Bado hakuna ujumbe. Sema gm.",
  "chat.online": "Kila mtu kwenye ukumbi anaona hili. Kuwa mstaarabu.",
  "chat.practice": "Mazoezi hayako mtandaoni: roboti tu ndizo zinasikiliza.",
  "set.graphics": "Michoro",
  "set.quality": "Ubora",
  "set.qualityNote": "Otomatiki hupunguza undani fremu zinapokuwa polepole.",
  "set.auto": "Otomatiki",
  "set.high": "Juu",
  "set.medium": "Wastani",
  "set.low": "Chini",
  "set.shake": "Kutikisika kwa skrini",
  "set.motion": "Uhuishaji wa menyu",
  "set.display": "Onyesho",
  "set.skins": "Skini",
  "set.skinsNote": "Mavazi na skini za silaha za nani zichorwe.",
  "set.skinsAll": "Kila mtu",
  "set.skinsMine": "Zangu tu",
  "set.skinsNone": "Hakuna",
  "set.names": "Majina juu ya wakimbiaji",
  "set.titles": "Vyeo juu ya majina",
  "set.controls": "Vidhibiti",
  "set.stick": "Ukubwa wa kijiti cha kugusa",
  "set.lefty": "Kugusa kwa mkono wa kushoto",
  "set.leftyNote": "Inabadilisha vijiti vya kusogea na kulenga.",
  "set.audio": "Sauti",
  "set.sound": "Sauti ya athari",
  "set.music": "Sauti ya muziki",
  "set.track": "Muziki wa mchezo",
  "set.trackAuto": "Mchanganyiko",
  "set.trackNote": "Wimbo tofauti wa uvamizi kila mechi, au baki na unaoupenda.",
  "pause.nextTrack": "Wimbo unaofuata ⏭",
  "set.language": "Lugha",
  "shop.exoticIn": "Exotic+ ndani ya",
  "shop.guarantee": "Exotic ya uhakika ndani ya mafunguo {n}",
  "set.voice": "Mtangazaji",
  "mode.dm": "Deathmatch",
  "mode.dm.d": "Kila mtu kwa nafsi yake, unarudi baada ya kila kifo. Aliyeua wengi zaidi filimbi ikipulizwa anachukua chungu.",
  "mode.gl": "Guns + Lasers",
  "mode.gl.d": "Deathmatch yenye menyu ya kununua: kuua kunalipa mikopo ya vifaa vya huduma, mizinga ya ulinzi na mabomu ya leza.",
  "mode.hardcore": "Hardcore",
  "mode.hardcore.d": "Afya ndogo sana: risasi moja na umeanguka. Wa mwisho aliyesimama anachukua chungu.",
  "kind.dm": "aliyeua wengi anachukua chungu",
  "hud.startDm": "Aliyeua wengi zaidi saa ikifika sifuri anachukua chungu",
  "hud.startGl": "Kuua kunalipa mikopo · 1 huduma · 2 mzinga · 3 bomu la leza",
  "hud.startHc": "Pigo moja na umeanguka. Fanya lako lihesabike.",
  "hud.respawned": "Umerudi",
  "hud.respawnIn": "Unarudi baada ya {s}s",
  "hud.tookLead": "Umechukua uongozi",
  "hud.lostLead": "Umepoteza uongozi",
  "hud.dmScore": "Kuua {k} · vifo {d} · #{p}",
  "hud.dmGoal": "Kuua kwa kwanza kunachukua uongozi",
  "hud.oneHit": "PIGO 1",
  "feed.leader": "{name} anaongoza na {k}",
  "gl.medkit": "Kifaa cha huduma",
  "gl.turret": "Mzinga wa ulinzi",
  "gl.mine": "Bomu la leza",
  "gl.revive": "Fufua kikosi",
  "gl.no.none": "Hakuna aliyeanguka",
  "gl.no.mode": "Kwenye hali ya zombi tu",
  "gl.revived": "{name} amefufua {n} wa kikosi",
  "gl.you": "Wewe",
  "gl.no.cash": "Mikopo haitoshi",
  "gl.no.full": "Tayari una afya kamili",
  "gl.no.limit": "Kikomo kimefikiwa",
  "gl.no.wall": "Karibu sana na ukuta",
  "res.dmLost": "Umemaliza #{p}",
  "res.dmText": "Kuua {k}, vifo {d}. Mshindi alikuwa na {top}.",
  "coach.dm": "Unarudi uhai · aliyeua wengi saa ikiisha anashinda",
  "coach.gl": "Kuua kunalipa mikopo · itumie kwa kifaa cha huduma ✚, mzinga ◈ au bomu la leza ⌁",
  "set.voiceNote": "Mtangazaji aliyerekodiwa (Kiingereza, Kiukreni, Kihispania, Kifaransa, Kireno; Kiingereza kwa lugha nyingine).",
  "net.waking": "Tunaamsha seva (seva ya bure hulala wakati hakuna anayecheza, hadi dakika moja)… Mazoezi yanafanya kazi wakati huo.",
  "shop.bulk": "Kila sanduku la {n} ni bure",
  "shop.bulkOn": "Inajumuisha {n} za bure",
  "net.online": "{n} mtandaoni",
  "st.title": "Kuanza",
  "st.signin": "Ingia",
  "st.signin.d": "Kwa pochi yako ya Starknet, Cartridge, au barua pepe.",
  "st.signin.go": "Ingia",
  "st.fund": "Ongeza pesa",
  "st.fund.d": "Tuma tokeni chache kutoka pochi yako kwenda salio lako la mchezo. Unaweza kutoa wakati wowote.",
  "st.fundTest": "Testnet: STRK ya bure kwenye starknet-faucet.vercel.app.",
  "st.fund.go": "Weka",
  "st.coin": "Chagua sarafu yako",
  "st.coin.d": "Chagua sarafu utakayowekea dau hapa chini. Ushindi unarudi kwa sarafu ileile.",
  "st.coin.go": "Onyesha sarafu",
  "st.play": "Cheza mechi yako ya kwanza",
  "st.play.d": "Chagua aina na dau, bonyeza Cheza, kisha Tayari.",
  "st.play.go": "Cheza",
  "touch.fire": "Fire",
  "rot.title": "Geuza simu yako kwa ubavu",
  "rot.sub": "Uvamizi unachezwa vizuri zaidi kwa mlalo: kusogea kushoto, Fire kulia.",
  "rot.anyway": "Cheza wima hata hivyo",
  "prep.waiting": "Inasubiri wachezaji",
  "prep.waitingMe": "Hakuna saa: alika marafiki na ubonyeze Anza ukiwa tayari. Viti vitupu vinapata roboti. Viti {n} kati ya {of} vimechukuliwa.",
  "prep.waitingJoin": "Viti {n} kati ya {of} vimechukuliwa. Weka dau na ujiandae kujiunga na uvamizi huu.",
  "prep.firstWait": "Bonyeza Tayari: chumba kinamsubiri kila mtu, hakuna saa.",
  "prep.start": "Anza sasa",
  "nav.friends": "Marafiki",
  "nav.guilds": "Vikundi",
  "so.now": "sasa hivi",
  "so.min": "dakika {n} zilizopita",
  "so.hr": "saa {n} zilizopita",
  "so.day": "siku {n} zilizopita",
  "so.seen": "Alionekana mwisho {t}",
  "so.st.lobby": "Mtandaoni",
  "so.st.waiting": "Anasubiri chumbani",
  "so.st.raid": "Yuko kwenye uvamizi",
  "so.friend": "Rafiki",
  "so.sent": "Ombi limetumwa",
  "so.accept": "Kubali",
  "so.add": "Ongeza rafiki",
  "so.invited": "Amealikwa",
  "so.invite": "Alika",
  "so.message": "Ujumbe",
  "so.onlineOnly": "Marafiki, ujumbe na vikundi vinafanya kazi unapocheza mtandaoni.",
  "so.gInvite": "Kwenye kikundi",
  "so.gInvited": "Amealikwa",
  "so.gInviteSent": "Mwaliko wa kikundi umetumwa",
  "so.gInvitesYou": "anakualika kwenye kikundi chao",
  "so.gMembers": "wanachama {n}",
  "so.gJoin": "Jiunge na kikundi",
  "so.more": "Onyesha zaidi ({n})",
  "so.players": "Wachezaji",
  "so.friends": "Marafiki",
  "so.messages": "Ujumbe",
  "so.search": "Tafuta wachezaji kwa jina",
  "so.count": "wachezaji {n} · {on} mtandaoni",
  "so.none": "Hakuna aliyepatikana.",
  "so.wants": "anataka kuwa rafiki yako",
  "so.requests": "Maombi ya urafiki",
  "so.noFriends": "Bado huna marafiki. Tafuta watu kwenye Wachezaji.",
  "so.pending": "Maombi yaliyotumwa",
  "so.cancel": "Ghairi",
  "so.decline": "Kataa",
  "so.sayHi": "Sema habari 👋",
  "so.noMsgs": "Bado hakuna ujumbe.",
  "so.remove": "Ondoa rafiki",
  "so.onlineNow": "Mtandaoni sasa",
  "so.nobody": "Hakuna aliye huru mtandaoni sasa hivi.",
  "so.invitesYou": "anakualika kwenye uvamizi",
  "so.waitingN": "{n} wanasubiri",
  "so.join": "Jiunge",
  "so.later": "Baadaye",
  "so.reqToast": "{n} anataka kuwa rafiki yako",
  "so.nowFriends": "Wewe na {n} sasa ni marafiki",
  "so.invSent": "Mwaliko umetumwa",
  "so.invitePlayers": "Alika wachezaji",
  "so.inviteHint": "Wanapata kadi yenye kitufe cha Jiunge kinachowaleta kwenye chumba hiki.",
  "gd.members": "wanachama {n}",
  "gd.leave": "Ondoka kwenye kikundi",
  "gd.join": "Jiunge",
  "gd.all": "Vikundi vyote",
  "gd.needRank": "Cheo {n} au zaidi (wewe: {have})",
  "gd.needBuy": "Angalau ununuzi mmoja kwa USDC/USDT",
  "gd.create": "Unda kikundi",
  "gd.name": "Jina la kikundi",
  "gd.tag": "Lebo (2-5)",
  "gd.desc": "Maelezo mafupi (hiari)",
  "gd.found": "Anzisha kikundi",
  "gd.count": "wanachama {n} · {on} mtandaoni",
  "gd.yours": "Kikundi chako",
  "gd.list": "Vikundi",
  "gd.none": "Bado hakuna vikundi. Kuwa wa kwanza.",
  "gd.err.signin": "Ingia kwanza.",
  "gd.err.member": "Ondoka kwenye kikundi chako kwanza.",
  "gd.err.purchase": "Kuanzisha kikundi kunahitaji ununuzi mmoja kwa USDC/USDT kwanza.",
  "gd.err.rank": "Kuanzisha kikundi kunahitaji cheo 20.",
  "gd.err.name": "Jina: herufi, tarakimu au nafasi 3-24.",
  "gd.err.tag": "Lebo: herufi au tarakimu 2-5.",
  "gd.err.taken": "Jina hilo au lebo hiyo imechukuliwa.",
  "pf.title": "Mchezaji",
  "pf.rank": "Cheo {n}",
  "pf.guild": "Kikundi: {g}",
  "pf.raids": "Uvamizi",
  "pf.wins": "Ushindi",
  "pf.kills": "Kuua",
  "pf.extracts": "Ametoka",
  "pf.best": "Kuua bora",
  "pf.time": "Amecheza",
  "pf.ach": "Mafanikio",
  "pf.multi": "Mfululizo bora",
  "pf.since": "Anacheza tangu",
  "tb.readyWait": "{n} wanasubiri",
  "mc.waiting": "{n} wanasubiri",
  "pause.open": "Menyu (Esc)",
  "pause.title": "Menyu",
  "pause.resume": "Endelea",
  "pause.settings": "Mipangilio",
  "pause.leave": "Ondoka kwenye mechi",
  "pause.leaveLose": "Ondoka kwenye mechi (poteza dau)",
  "pause.leaveSure": "Bonyeza tena kuondoka",
  "pause.keys": "Esc: rudi kwenye mechi",
  "pause.back": "← Rudi",
  "pause.on": "imewashwa",
  "pause.off": "imezimwa",
  "pause.practice": "Mazoezi yamesimamishwa.",
  "pause.practiceDead": "Umetoka nje. Ondoka wakati wowote.",
  "pause.alive": "Mechi inaendelea wakati menyu hii iko wazi. Ukiondoka sasa mkimbiaji wako anabaki nyuma: dau linabaki kwenye mechi.",
  "pause.dead": "Umetoka nje. Ondoka wakati wowote: chochote ulichoshinda bado kinafika kwenye salio lako.",
  "gd.chat": "Gumzo",
  "gd.chatEmpty": "Bado hakuna ujumbe. Wasalimie kikundi chako.",
  "gd.chatPh": "Andikia kikundi chako…",
  "swap.min": "Ubadilishaji mdogo zaidi: {v}",
  "prep.waitingPeople": "Hakuna saa: alika marafiki, uvamizi unaweza kuanza wachezaji {min} wakiwa tayari. Kila kiti ni mchezaji halisi. Viti {n} kati ya {of} vimechukuliwa.",
  "prep.people": "Wachezaji halisi tu: kila mtu hapa anaanza na kisu.",
  "shop.firstTopup": "Kuongeza salio kwa mara ya kwanza kunaongezeka mara mbili: pata kiasi kilekile kama $ ya duka, hadi {v} zaidi.",
  "tour.who": "msimamizi wako",
  "tour.voice": "Sauti washa/zima",
  "tour.skip": "Ruka mafunzo",
  "tour.next": "Endelea",
  "tour.done": "Twende",
  "set.tour": "Ziara",
  "set.tourNote": "Nyx anakuonyesha mchezo tena.",
  "set.tourBtn": "Rudia ziara",
  "nyx.hello": "Habariii, mkimbiaji! Mimi ni Nyx, kiongozi wako usiku huu! Kaa nami, na utatoka kwenye uvamizi wako wa kwanza... tajiri!",
  "nyx.name": "Sawa, kwanza kabisa! Andika jina la mkimbiaji wako, kisha gusa Imekamilika. Kila mtu ataliona, juu ya kichwa chako!",
  "nyx.nameOk": "Aah, jina zuri! Nalipenda!",
  "nyx.practice": "Sasa gusa Mazoezi! Ni bure, ni roboti tu. Bora kwa mara yako ya kwanza!",
  "nyx.practiceOk": "Ndiyooo! Uamuzi mzuri!",
  "nyx.modes": "Hizi ni aina za mchezo! Leo tunacheza Raid, ya klasiki. Kusanya, pigana, na utoke! Gusa Raid!",
  "nyx.modeOk": "Raid basi! Twende!",
  "nyx.bag": "Hivi ndivyo ilivyo! Dau lako linaingia kwenye begi lako. Mwangushe mtu, na begi lake ni lako! Ukianguka... lako ni lake. Lo!",
  "nyx.shop": "Mavazi na skini za silaha zinatoka kwenye mabegi na makasha, hapa hapa dukani! Na psst... kuna moja la bure linakusubiri!",
  "nyx.social": "Marafiki, ujumbe, vikundi! Leta kikosi chako. Kila kitu kinafurahisha zaidi pamoja!",
  "nyx.wallet": "Unataka dau halisi? Ingia kwa pochi, au barua pepe tu! Utoaji wa pesa unarudi kwenye anwani yako mwenyewe tu. Salama kabisa!",
  "nyx.play": "Tayari? Bonyeza Cheza!",
  "nyx.ready": "Hiki ni chumba cha maandalizi! Bonyeza Tayari, na tunashuka! Wuu!",
  "nyx.start": "Tumeingia! Tembea kwa W, A, S, D. Lenga kwa kipanya, na ubofye kupiga risasi! Space kuruka mbele!",
  "nyx.startTouch": "Tumeingia! Kidole gumba cha kushoto kinakusogeza. Shikilia Fire, upande wa kulia, na inalenga yenyewe!",
  "nyx.loot": "Unaona mng'ao huo wa chungwa? Ni pesa! Kimbia juu yake!",
  "nyx.pickup": "Yeee! Begi lako limekuwa zito zaidi!",
  "nyx.kill": "Damu ya kwanza! Risasi nzuri! Chukua walichodondosha. Aah, na bunduki bora!",
  "nyx.hurt": "Aah, umeumia! Afya hairudi wakati wa mapigano, kwa hivyo cheza kwa uangalifu!",
  "nyx.storm": "Dhoruba inakuja! Baki ndani ya duara, haraka!",
  "nyx.exit": "Aah, begi hilo linakupendeza! Tafuta duara la kijani la kutokea, na usimame ndani yake!",
  "nyx.extracting": "Tulia! Sekunde tatu! Usipigwe!",
  "nyx.won": "Umetoka! Nilijua utaweza! Tuonane uvamizi ujao, mkimbiaji!",
  "nyx.dead": "Aah, hutokea! Mazoezi ni bure, kwa hivyo turudie!",
  "tour.yourMove": "Zamu yako",
  "tour.skipStep": "Ruka hatua hii",
  "tour.again": "Gusa Nyx kuisikia tena",
  "tour.replayHint": "Unataka ziara tena? Mipangilio → Ziara.",
  "mode.zombies": "Zombi",
  "mode.zombies.d": "Ushirikiano, peke yako au na hadi marafiki 3: mawimbi 20 ya wafu kutoka kila upande, kila moja gumu zaidi, mabosi kwenye 10 na 20. Hakuna saa. Kuua kunalipa mikopo ya mizinga, mabomu ya leza na vifaa vya huduma.",
  "mode.gold": "Kimbilio la Dhahabu",
  "mode.gold.d": "Mabegi ya dhahabu yanadondoka kote machimboni. Bunduki za nasibu, kurudi haraka. Mwenye mabegi mengi anachukua chungu chote kama salio la duka.",
  "kind.zombie": "ushirikiano · XP",
  "kind.gold": "mshindi mmoja · salio la duka",
  "tb.zFee": "kiingilio · XP, vyeo",
  "tb.goldFee": "kiingilio · mshindi anachukua yote",
  "prep.zFee": "kiingilio {v}",
  "prep.zSquad": "Kikosi",
  "prep.goldPot": "Zawadi (salio la duka)",
  "zp.title": "Silaha yako kwa mechi",
  "zp.power": "Madhara kwa sekunde",
  "zp.melee": "hakuna kujaza risasi",
  "hud.waveK": "Wimbi",
  "hud.goldK": "Mabegi ya dhahabu",
  "hud.startZ": "Linda makaburi. Wanakuja kutoka kila upande",
  "hud.startGold": "Chukua dhahabu. Mabegi mengi yanashinda yote",
  "hud.wave": "Wimbi {n} kati ya {of}",
  "hud.bossWave": "WIMBI LA MWISHO · BOSI AMEFIKA",
  "hud.waveClear": "Wimbi {n} limemalizwa",
  "hud.patched": "+35 HP",
  "hud.summon": "Bosi anaita kundi",
  "hud.bossDown": "BOSI AMEANGUKA · MZUNGUKO UMEMALIZWA",
  "hud.bagsShort": "dhahabu",
  "hud.waveN": "{n} / {of}",
  "hud.nextWave": "wimbi lijalo baada ya {s}s",
  "hud.zLeft": "{n} wamebaki · {k} wameanguka",
  "hud.goldPlace": "nafasi {p} · vifo {d} · zawadi {s}",
  "hud.bossHp": "BOSI {p}%",
  "hud.zBreak": "Jaza risasi na mjipange: {s}s",
  "hud.zGoal": "Okoka mawimbi 20 · mabosi kwenye 10 na 20",
  "hud.goldGoal": "Mabegi mengi ya dhahabu filimbi ikipulizwa yanashinda",
  "hud.zDown": "Umeanguka. Utarudi wimbi linalofuata likianza, kikosi chako kikistahimili",
  "feed.zYou": "Wafu wamekupata",
  "feed.zDown": "{name} amechanwa vipande",
  "coach.z": "Baki uwanjani, mgongo kwa mgongo. Kuua kunalipa mikopo: nunua mizinga (2), mabomu ya leza (3) na vifaa vya huduma (1)",
  "coach.gold": "Kimbia juu ya mabegi ya dhahabu kuyachukua. Ukifa nusu ya mabegi yako yanamwagika, kwa hivyo chukua, kisha baki hai",
  "warn.z60": "Dakika moja imebaki kwenye saa",
  "warn.z10": "Sekunde 10: muue bosi!",
  "warn.gold30": "Sekunde 30: chukua unachoweza",
  "warn.gold10": "Sekunde 10 zimebaki",
  "res.zCleared": "Mzunguko umemalizwa",
  "res.zFell": "Mmezidiwa kwenye wimbi {n}",
  "res.zWaves": "mawimbi {n} / {of}",
  "res.zWonText": "Mawimbi kumi na bosi wao, na kikosi cha {s}. Umeangusha {k} wa wafu.",
  "res.zText": "Umeangusha {k} wa wafu (kikosi cha {s}). Kadiri unavyoenda mbali, ndivyo XP inavyoongezeka.",
  "res.zTime": "{t} kwenye saa",
  "res.goldWon": "Kimbilio la dhahabu limeshindwa",
  "res.goldLost": "Nafasi {p} kwenye kimbilio la dhahabu",
  "res.goldWonText": "Mabegi {b} ya dhahabu, zaidi ya yeyote. {c} sasa iko kwenye salio lako la duka.",
  "res.goldText": "Umechukua mabegi {b}; mshindi alikuwa na {top}. Nafasi ya kwanza tu inalipwa.",
  "xp.Waves survived": "Mawimbi uliyookoka",
  "xp.Zombies": "Zombi",
  "xp.Boss slain": "Bosi ameuawa",
  "xp.Run cleared": "Mzunguko umemalizwa",
  "xp.Gold bags": "Mabegi ya dhahabu",
  "ach.graveyard_shift": "Zamu ya Makaburini",
  "ach.hold_the_line": "Shikilia Mstari",
  "ach.undertaker": "Mzishi",
  "ach.exterminator": "Mwangamizaji",
  "ach.giant_slayer": "Muua Majitu",
  "ach.zombie_slayer": "Muua Zombi",
  "ach.top_of_the_horde": "Juu ya Kundi",
  "ach.nightmare_walker": "Mtembea Ndotoni",
  "ach.army_of_one": "Jeshi la Mmoja",
  "ach.prospector": "Mtafuta Madini",
  "ach.gold_fever": "Homa ya Dhahabu",
  "ach.mother_lode": "Mshipa Mkuu",
  "ach.bag_hoarder": "Mlimbikizaji wa Mabegi",
  "ach.midas": "Midas",
  "achd.zRuns": "Cheza mzunguko wa zombi",
  "achd.bestWave": "Maliza wimbi {n} dhidi ya wafu",
  "achd.zKills": "Ua zombi {n}",
  "achd.zBoss": "Piga pigo la mwisho kwa bosi",
  "achd.zClears": "Maliza mzunguko wa zombi mara {n}",
  "achd.zMvp": "Maliza mzunguko wa zombi ukiwa na kuua wengi zaidi kwenye kikosi chako",
  "achd.zSolo": "Maliza mzunguko wa zombi peke yako",
  "achd.goldRuns": "Cheza kimbilio la dhahabu",
  "achd.goldWins": "Shinda kimbilio la dhahabu mara {n}",
  "achd.bestGold": "Shikilia mabegi {n} ya dhahabu mwishoni mwa kimbilio moja",
  "achd.goldBags": "Chukua mabegi {n} ya dhahabu kwa jumla",
  "tour.nameDone": "Imekamilika",
  "tour.finish": "Tucheze!",
  "nyx.stake": "Hili ni dau lako: unachoweka kwenye begi lako. Kwenye mazoezi ni pesa za mchezo, kwa hivyo hakuna cha kupoteza. Tutacheza kwa dola moja!",
  "nyx.retry": "Aah, umeanguka! Hutokea, mazoezi ni bure! Gusa Cheza tena. Wakati huu chukua ngawira kidogo, kisha kimbia kwenye njia ya kijani ya kutokea!",
  "nyx.resultWon": "Umetoka! Umeshinda! Nilijua utaweza! Pesa za mazoezi ni za kufurahisha tu. Gusa Meza, nikuonyeshe duka!",
  "nyx.shopGo": "Sasa gusa Duka!",
  "nyx.shopCase": "Karibu dukani! Kwenye mazoezi ni onyesho tu, hakuna kinachotozwa. Gusa Onyesho kwenye begi hili na uangalie likifunguka!",
  "nyx.shopEquip": "Aah, angalia kilichotoka! Mtandaoni, kwa dola zako za duka, kingekuwa chako. Gusa Funga!",
  "nyx.bye": "Ni hayo yote! Unaweza kucheza, kushinda, na kununua. Nenda ukawashinde, mkimbiaji! Unaweza kuniita tena wakati wowote, kwenye Mipangilio.",
  "hud.headshot": "RISASI YA KICHWA",
  "inv.open": "Fungua",
  "bp.later": "Baadaye",
  "ach.sharpshooter": "Mlengaji Hodari",
  "ach.headhunter": "Mwindaji wa Vichwa",
  "achd.headshots": "Piga risasi {n} za kichwa",
  "hud.demoted": "Umekufa: umeshuka hadi {w}",
  "hud.crit": "CRIT",
  "hud.roundStart": "Raundi {n} kati ya {of}",
  "hud.roundWon": "Raundi {n} ni yako!",
  "hud.roundLost": "Raundi {n} imepotea",
  "hud.roundDraw": "Raundi {n}: sare",
  "hud.roundTo": "Raundi {n} imeenda kwa {name}",
  "hud.roundNext": "Raundi ijayo baada ya {s}s",
  "hud.roundScore": "Raundi {n}/{of} · {a} : {b}",
  "hud.roundDown": "Umeanguka. Utarudi raundi ijayo",
  "mc.rounds": "{w} kati ya raundi {n}",
  "hud.midBossWave": "WIMBI 10 · BOSI ANAVUKA UZIO",
  "hud.midBossDown": "Bosi ameanguka! Mawimbi kumi zaidi",
  "ach.last_stand": "Msimamo wa Mwisho",
  "gl.upTurret": "Mzinga umeboreshwa: kiwango {lv}",
  "gl.upMine": "Bomu la leza limeboreshwa: miale {lv}",
  "gl.upHint": "Space: {what} → kiwango {lv} · {c} CR",
  "gl.upHintTouch": "⬆ {what} → kiwango {lv} · {c} CR",
  "gl.no.max": "Tayari kiko kiwango cha juu",
  "gl.no.near": "Simama karibu na mzinga au bomu lako",
  "nav.invite": "Alika",
  "ref.title": "Alika marafiki",
  "ref.lead": "Walete marafiki kwa kiungo chako. Kwa siku {d} unapata {p}% ya sehemu ya nyumba kutoka kila dau wanalocheza, kama $ ya duka.",
  "ref.yourCode": "Msimbo wako",
  "ref.link": "Kiungo chako cha mwaliko",
  "ref.copy": "Nakili",
  "ref.share": "Shiriki",
  "ref.copied": "Kiungo kimenakiliwa",
  "ref.shareText": "Njoo tuvamie pamoja kwenye DARK BAGS. Msimbo wangu: {c}",
  "ref.invited": "Walioalikwa",
  "ref.active": "Wamecheza mechi",
  "ref.earned": "Umepata",
  "ref.how": "Jinsi inavyofanya kazi",
  "ref.step1": "Rafiki anafungua kiungo chako (au anaandika msimbo wako) kabla ya mechi yake ya kwanza",
  "ref.step2": "Baada ya mechi yake ya kwanza yenye dau anapata begi la karibu",
  "ref.step3": "Kila dau analocheza linakulipa {p}% ya sehemu ya nyumba, kwa siku {d}, kama $ ya duka",
  "ref.step4": "Akimaliza mechi {m} unapata begi la bonasi",
  "ref.fair": "Uchezaji wa haki: akaunti kwenye mtandao au kifaa kimoja na chako hazihesabiwi, kuna kikomo cha kila siku, na udanganyifu unafuta zawadi zote.",
  "ref.by": "Uliingia kwa msimbo {c}",
  "ref.have": "Una msimbo kutoka kwa rafiki?",
  "ref.apply": "Tumia",
  "ref.online": "Mialiko inafanya kazi kwenye mchezo wa mtandaoni. Badilisha kwenda mtandaoni kwenye Mipangilio.",
  "ref.signin": "Ingia upate kiungo chako cha mwaliko.",
  "ref.claimedToast": "Msimbo umetumika: begi lako la karibu linakuja baada ya mechi yako ya kwanza",
  "ref.err.already": "Tayari una aliyekualika",
  "ref.err.unknown": "Hakuna msimbo kama huo",
  "ref.err.self": "Huwezi kujialika mwenyewe",
  "ref.err.late": "Misimbo inafanya kazi kabla ya mechi yako ya kwanza tu",
  "ref.err.linked": "Msimbo huo ni kutoka mtandao au kifaa chako mwenyewe",
  "ref.err.busy": "Aliyekualika amefikia kikomo cha leo. Jaribu kesho",
  "err.guard_seat": "Akaunti nyingine kutoka mtandao au kifaa chako tayari iko kwenye meza hii",
  "err.guard_new": "Akaunti mpya nyingi mno kutoka mtandao wako leo. Rudi kesho",
  "err.guard_faucet": "Mtandao wako umeshapata tokeni zake za majaribio leo",
  "res.practiceNoXp": "Mazoezi ni bure: hakuna XP wala zawadi. Cheza mtandaoni ili upande cheo.",
  "online.only": "Mtandaoni tu. Mazoezi ni bure, kwa hivyo hayahesabiwi kwa pasi ya vita wala jedwali la ranked. Badilisha kwenda Mtandaoni kwenye ukurasa wa Cheza.",
  "err.online_only": "Hii inafanya kazi kwenye mchezo wa mtandaoni tu",
  "tour.skipped": "Mafunzo yamerukwa. Unaweza kumwita Nyx tena kwenye Mipangilio.",
  "shop.demo": "Onyesho",
  "shop.demoNote": "Onyesho: hakuna kilichotozwa wala kutolewa. Mtandaoni, unafungua mabegi kwa $ ya duka na unabaki na kinachotoka.",
  "acct.signin": "Ingia",
  "acct.copy": "Nakili anwani",
  "acct.explorer": "Kichunguzi",
  "acct.inWallet": "Kwenye pochi",
  "acct.inGame": "Ndani ya mchezo",
  "acct.deposit": "Weka",
  "acct.withdraw": "Toa",
  "acct.cartridge": "Fungua pochi ya Cartridge",
  "acct.signout": "Toka",
  "acct.copied": "Anwani imenakiliwa",
  "br.tab": "Nunua na madaraja",
  "br.buy": "Nunua kwa kadi",
  "br.buySub": "Kadi, Apple Pay au uhamisho wa benki, moja kwa moja kwenye pochi yako ya Starknet",
  "br.intro": "Leta sarafu Starknet: zinunue kwa kadi, au zihamishe kutoka mtandao mwingine kwenye tovuti ya daraja lenyewe. Zinafika kwenye pochi yako ya Starknet; kisha Weka (kwa siri, ikiwa pochi yako inaweza) inazipeleka mchezoni.",
  "br.yourAddr": "Anwani yako ya Starknet:",
  "br.in": "Kuingia Starknet",
  "br.out": "Kutoka Starknet",
  "br.fromNet": "Kutoka mtandao",
  "br.toNet": "Kwenda mtandao",
  "br.youSend": "Unatuma",
  "br.youGet": "Unapata",
  "br.amount": "Kiasi",
  "br.refund": "Anwani yako ya {c} (kwa marejesho)",
  "br.refundPh": "Marejesho yanakwenda wapi ubadilishaji ukishindwa",
  "br.recipient": "Anwani ya {c} inayopokea",
  "br.recipientPh": "Anwani inayopokea kwenye mnyororo huo",
  "br.landsIn": "Inafika kwenye pochi yako ya Starknet {a}; kisha Weka inaihamishia kwenye mchezo.",
  "br.fromWallet": "Imetumwa kutoka pochi yako ya Starknet {a}.",
  "br.fee": "Inajumuisha ada yetu ya {p}%.",
  "br.getAddr": "Pata anwani ya kuweka",
  "br.send": "Tuma kutoka pochi yangu",
  "br.estimate": "Unapata takriban {a} ({u}), ndani ya ~{s} s",
  "br.needAmount": "Andika kiasi.",
  "br.needRefund": "Andika anwani yako kwenye mnyororo unaotuma kutoka, kwa marejesho.",
  "br.needRecipient": "Andika anwani inayopokea.",
  "br.sent": "Imetumwa. Daraja linaendelea kuanzia hapa.",
  "br.sendExactly": "Tuma {a} kamili kwenye {c} kwenda anwani hii:",
  "br.memo": "Memo (inahitajika)",
  "br.copyMemo": "Nakili memo",
  "br.outSent": "{a} imetumwa kwenye daraja kwa {c}.",
  "br.youGetAbout": "Unapata takriban {a} kwenye {c}.",
  "br.deadline": "Marejesho yasipokamilika kufikia {t}.",
  "br.toGame": "Iweke kwenye mchezo",
  "br.new": "Daraja jipya",
  "br.others": "Madaraja mengine",
  "br.othersNote": "Inafungua tovuti ya daraja lenyewe; hakuna ada yetu huko. Tuma kwenye anwani yako ya Starknet inayoonyeshwa kwenye paneli ya pochi.",
  "br.lsSub": "Minyororo na masoko 40+",
  "br.avnuSub": "Badilisha tokeni kwenye Starknet",
  "br.mainnetOnly": "Kuvuka minyororo kunafanya kazi na sarafu halisi kwenye Starknet mainnet. Kwenye testnet, tumia madaraja hapa chini.",
  "br.s.wait": "Inasubiri amana yako",
  "br.s.seen": "Amana imeonekana, inathibitisha",
  "br.s.partial": "Amana ni ndogo mno; tuma iliyobaki au subiri marejesho",
  "br.s.proc": "Inavusha…",
  "br.s.ok": "Imekamilika: iko kwenye pochi yako",
  "br.s.refund": "Imerejeshwa",
  "br.s.fail": "Imeshindwa; hakuna kilichochukuliwa",
  "nav.mail": "Barua",
  "mail.claim": "Dai",
  "mail.claimed": "Imedaiwa: {g}",
  "mail.creditNote": "$ ya duka: itumie dukani. Haiwezi kutolewa wala kuuzwa.",
  "mail.empty": "Bado hakuna barua.",
  "mail.g.credit": "{v} ya duka",
  "mail.g.spin": "Mzunguko {n} wa gurudumu",
  "mail.g.trial": "{n} kwa saa 1",
  "mail.newToast": "Barua mpya!",
  "mail.noSpins": "Hakuna mizunguko iliyobaki",
  "mail.pick": "Chagua barua uisome.",
  "mail.signin": "Ingia upate barua zako.",
  "mail.spinBtn": "Zungusha gurudumu ({n})",
  "mail.spinNow": "Zungusha!",
  "mail.taken": "Imedaiwa",
  "mail.welcomeToast": "Bonasi ya karibu! Cheo chako cha Mwanzilishi kimewashwa, na mzunguko wa gurudumu unakusubiri kwenye Barua.",
  "mail.wheel": "Gurudumu la bahati",
  "mail.wheelNote": "Skini ya saa 1 kwa mkimbiaji wako, skini ya silaha ya saa 1, au hadi $2 ya duka.",
  "mail.trial72": "Ni chako kwa saa 1. Kivae kutoka kwenye hifadhi.",
  "mail.welcome.t": "♛ Karibu, Mwanzilishi!",
  "mail.welcome.b": "Wewe ni mmoja wa wa kwanza kuunga mkono DARK BAGS kwa kuongeza salio halisi, na hatutasahau. Asante!\n\nKuanzia leo unavaa cheo cha premium cha Mwanzilishi kwa dhahabu yenye uhuishaji: ni wakimbiaji walioamini mchezo tangu mwanzo tu watakaokibeba.\n\nZawadi yako iko hapa chini: mzunguko wa gurudumu la bahati. Bahati njema huko nje, na tuonane gizani.\n\nTimu ya DARK BAGS",
  "ach.founder": "Mwanzilishi",
  "achd.deposits": "Ongeza salio kwa mara ya kwanza",
  "r.premium": "Premium",
  "mail.jackpot.t": "🎰 Jackpot ya bahati!",
  "mail.jackpot.b": "Benki ya bahati ilikuwa yako: sarafu ziko njiani kwako (au tayari kwenye salio lako la mchezo). Hongera!",
  "fw.bank": "Benki ya bahati",
  "fw.coin": "Lipa kwa",
  "fw.inBalance": "Imewekwa kwenye salio lako la mchezo: itoe wakati wowote.",
  "fw.jackpot": "JACKPOT",
  "fw.kicker": "$0.05 kwa mzunguko",
  "fw.lead": "Aina 18 za zawadi: skini za saa 1, skini halisi za kudumu, mtindo, masanduku ya zawadi, $ ya duka, XP ya pasi, nyongeza za XP, mizunguko ya ziada. Kila mzunguko unaolipiwa pia unajaza benki: mzunguko unaofikia alama unashinda yote kwa sarafu halisi.",
  "fw.next": "inalipa kwa {m}",
  "fw.noCoins": "Weka sarafu yoyote ili kuzungusha.",
  "fw.odds": "Kinachoweza kutoka",
  "fw.real": "Skini halisi ya {r}",
  "fw.realKeep": "Ni yako kudumu, milele.",
  "fw.rules": "30% ya kila mzunguko inaenda kwenye benki ya bahati. Ikifikia alama yake ($0.50, kisha $1, $1.50, $2… hadi $5), mzunguko unaoifikia unashinda benki nzima kwa USDC (au USDT, au STRK). Skini za majaribio zinadumu saa 1. Vitu vya duka haviwezi kutolewa wala kuuzwa.",
  "fw.sentChain": "Imetumwa kwenye pochi yako kwenye Starknet.",
  "fw.share": "Shiriki ushindi",
  "fw.spin": "Zungusha",
  "fw.title": "Gurudumu la bahati",
  "fw.trial": "Skini ya mkimbiaji ya saa 1",
  "fw.wtrial": "Skini ya silaha ya saa 1",
  "coin.import": "Ingiza sarafu",
  "coin.search": "Tafuta: alama, jina au anwani",
  "coin.added": "imeongezwa",
  "coin.add": "Ongeza",
  "coin.none": "Hakuna kilichopatikana",
  "coin.note": "Sarafu yoyote ya Starknet kwenye orodha iliyothibitishwa ya AVNU au orodha ya Ekubo. Ikishaongezwa, iweke na uwekee dau kama sarafu nyingine yoyote; ushindi unarudi kwayo.",
  "coin.done": "{s} imeongezwa: iweke na uichague kwa dau lako.",
  "coin.noPrice": "{s} imeongezwa; bei yake inaonekana baada ya dakika moja.",
};
