export default {
  'lobby.tagline': 'Bahis koy. Yağmala. Fırtınadan önce çık. <b>Çantanda ne olduğunu kimse görmez.</b>',
  'lobby.namePh': 'Koşucunun adı',
  'lobby.locker': 'Dolap · skinler · çantalar',
  'lobby.refill': 'Test coinlerini doldur',
  'lobby.online': 'Çevrimiçi',
  'lobby.practice': 'Botlara karşı antrenman',
  'lobby.stakePer': 'Baskın başına bahis',
  'lobby.stakeWith': 'Bahis coin’i <span class="fine">herhangi bir coin · $ olarak gösterilir · kazanç aynı coin ile döner</span>',
  'lobby.play': 'Oyna · {s} bahis',
  'lobby.signIn': 'Oynamak için giriş yap',
  'lobby.how': 'Nasıl oynanır',
  'lobby.gore': '<b>18+ modu.</b> Uzuvlar kopar, kan yerde kalır.',
  'lobby.fine': 'Antrenman tarayıcında çalışır. Buradaki tüm para oyun parasıdır.',
  'how.1': '<b>Bahis koy ve hazır ol.</b> Herkes bir bıçak ve 100 canla birlikte girer. Bahsinin yarısı çantanda, yarısı ganimet olarak saçılır.',
  'how.2': '<b>Turuncu ganimeti topla.</b> Çantana gider. Öldürmeler silahını yükseltir: bıçak → tabanca → pompalı → SMG → tüfek → lazer keskin nişancı.',
  'how.3': '<b>Canlı çık.</b> Fırtına kapatmadan önce yeşil bir çıkışta 3 saniye dur. Bütün çanta senin. Ölürsen başkasına düşer.',
  'how.keys': '<kbd>WASD</kbd> hareket · <kbd>fare</kbd> nişan · <kbd>tık</kbd> saldırı · <kbd>Boşluk</kbd> atılma · <kbd>Q</kbd> çanta boyutunu blöfle · <kbd>M</kbd> ses · <kbd>N</kbd> müzik',
  'how.fine': 'Her baskın ve her başarım rütbe XP’si verir. Her rütbe atlayışı sana 3 günlüğüne yeni bir skin verir.',
  'net.practice': 'Sadece sen ve botlar, çevrimdışı.',
  'net.open': 'Bağlandı. İnsanlar ve botlar aynı baskında.',
  'net.connecting': 'Sunucuya bağlanılıyor…',
  'net.down': 'Sunucuya ulaşılamıyor. Yeniden deneniyor… Antrenman çevrimdışı çalışır.',
  'net.lost': 'Bağlantı koptu. Masalara dönülüyor.',
  'q.pick': 'Bahis için bir coin seç.',
  'q.short': '{s} bahis için yeterli {c} yok. Başka bir coin ya da daha küçük bahis seç.',
  'q.shortDeposit': '{s} bahis için yeterli {c} yok. Başka bir coin, daha küçük bahis seç ya da yatır.',
  'q.stable': '{c} ile {s} bahis koyuyorsun. Canlı çık, taşıdığın her şey senin.',
  'q.coin': 'Bugünkü fiyattan {a} = {s} bahis koyuyorsun. Kazanç aynı kurla {c} olarak döner.',
  'tb.live': 'Baskın sürüyor · {t}',
  'tb.ready': '{n} hazır · {s}sn',
  'tb.waiting': '{n} bekliyor',
  'tb.golden': 'Sıradaki: altın baskın',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Antrenman ayarları',
  'pcfg.difficulty': 'Botlar',
  'pcfg.easy': 'Kolay',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Zor',
  'pcfg.runners': 'Baskındaki koşucular',
  'pcfg.time': 'Baskın süresi',
  'rk.max': 'en yüksek rütbe',
  'rk.toNext': 'Rütbe {r} için {x} XP',
  'rk.of': 'Rütbe {r} / 90',
  'rk.rank': 'Rütbe',
  'rk.up': 'Rütbe atladın',
  'rk.xp': 'rütbe XP’si',
  'xp.Raid': 'Baskın',
  'xp.kills': '{n} öldürme',
  'xp.Damage': 'Hasar',
  'xp.Time alive': 'Hayatta kalma',
  'xp.First blood': 'İlk kan',
  'xp.Double kill': 'Çifte öldürme',
  'xp.Triple kill': 'Üçlü öldürme',
  'xp.Rampage': 'Katliam',
  'xp.Godlike': 'Tanrısal',
  'xp.Full arsenal': 'Tam cephanelik',
  'xp.Extracted': 'Tahliye',
  'xp.Profit': 'Kâr',
  'xp.Practice ×0.5': 'Antrenman ×0.5',
  'rw.title': 'Rütbe ödülü',
  'rw.trial': '72 saat boyunca senin',
  'rw.try': 'Dene',
  'rw.share': 'Rütbeyi paylaş',
  'prep.raid': 'Baskın {n} · {s} bahis',
  'prep.readyUp': 'Hazır mısın?',
  'prep.first': 'İlk koşucu hazır olunca geri sayım başlar.',
  'prep.live': 'Bir baskın sürüyor. Şimdi hazır ol, sonrakine herkesle birlikte gir.',
  'prep.over': 'Baskın bitti. Hazırlık odası birazdan açılır.',
  'prep.many': 'Burada herkes bıçakla başlar. Botlar son saniyelerde katılır.',
  'prep.bots': 'Botlar boş yerleri son saniyelerde doldurur.',
  'prep.open': 'boş',
  'prep.pot': 'Pot',
  'prep.cancel': 'İptal · {v} iade',
  'prep.ready': 'Hazır · {v} bahis',
  'prep.back': 'Masalara dön',
  'hud.bagPrivate': 'Çantan · gizli',
  'hud.golden': 'Altın baskın',
  'hud.goldenStart': 'Altın baskın · içeride jackpot ganimeti',
  'hud.start': 'Bıçak elde · turuncuyu topla · çıkış bul',
  'hud.bagOpened': 'Çanta açıldı · +{v}',
  'hud.arsenal': 'Cephanelik tamam · yine bıçak ★',
  'hud.unlocked': '{w} açıldı',
  'hud.pnl': '{s} bahse karşı {d}',
  'hud.alive': 'İçeride {n}',
  'hud.next': 'Sıradaki: {w}',
  'hud.final': 'Son çember · son çıkış',
  'hud.closing': 'Fırtına daralıyor · {t}',
  'hud.stormIn': 'Fırtına {t} sonra ilerliyor',
  'hud.dash': 'Atıl',
  'hud.bagLook': 'Çanta görünümü',
  'hud.extracting': 'Tahliye',
  'hud.holdStill': 'Kıpırdama. Bir isabet sıfırlar.',
  'hud.sound': 'Ses',
  'hud.music': 'Müzik',
  'bluff.0': 'küçük',
  'bluff.1': 'orta',
  'bluff.2': 'şişkin',
  'touch.move': 'hareket',
  'touch.aim': 'nişan · ateş',
  'touch.bag': 'Çanta',
  'w.Knife': 'Bıçak',
  'w.Pistol': 'Tabanca',
  'w.Shotgun': 'Pompalı',
  'w.SMG': 'SMG',
  'w.Rifle': 'Tüfek',
  'w.Laser sniper': 'Lazer keskin nişancı',
  'streak.1': 'İlk kan',
  'streak.2': 'Çifte öldürme',
  'streak.3': 'Üçlü öldürme',
  'streak.4': 'Katliam',
  'streak.5': 'Tanrısal',
  'streak.you1': 'İlk kanı sen döktün',
  'feed.storm': 'Fırtına seni aldı',
  'feed.droppedYou': '{name} seni indirdi',
  'coach.storm': 'Fırtınadasın · çemberin içine dön',
  'coach.touch': 'Sol başparmak hareket · sağ başparmak nişan ve saldırı',
  'coach.keys': 'WASD hareket · fare nişan · tık saldırı',
  'coach.exit': 'Çıkma zamanı · yeşil bir ÇIKIŞTA 3 saniye dur · kenardaki oklar yolu gösterir',
  'coach.loot': 'Turuncu ganimeti topla · çantana gider',
  'coach.kills': 'Öldürmeler silahını yükseltir · Boşluk ile atıl',
  'coach.killsTouch': 'Öldürmeler silahını yükseltir · kaçmak için Atıl’a dokun',
  'spect.watching': '{name} izleniyor · ◀ ▶ değiştir',
  'spect.down': 'Düştün',
  'spect.results': 'Sonuçlar',
  'res.extracted': 'Tahliye edildi',
  'res.storm': 'Fırtına yuttu',
  'res.dropped': 'İndirildin',
  'res.sealed': 'İçeride kaldın',
  'res.inside': '{k} öldürme · içeride {t}',
  'res.out': '{s} bahisle {p} ile çıktın: {d}.',
  'res.paid': 'Giriş kurundan {v} ödendi.',
  'res.killer': 'Çantan artık {n} kişisinde. İçinde {v} vardı ve bunu sadece ikiniz bileceksiniz.',
  'res.inStorm': 'Çantan, {v}, cesaret edene fırtınada duruyor.',
  'res.sealedText': 'Baskın sen içerideyken kapandı. {v} sonraki baskının ganimetine geçti.',
  'res.again': 'Tekrar oyna',
  'res.tables': 'Masalar',
  'res.share': 'Paylaş',
  'share.title': 'Paylaş',
  'share.x': '𝕏’te paylaş',
  'share.copy': 'Görseli kopyala',
  'share.save': 'PNG kaydet',
  'share.close': 'Kapat',
  'lk.title': 'Dolap',
  'lk.outfits': 'Kıyafetler',
  'lk.shop': 'Mağaza',
  'lk.bags': 'Şans çantaları',
  'lk.all': 'Tümü',
  'lk.owned': 'Benimkiler',
  'lk.him': 'Erkek',
  'lk.her': 'Kadın',
  'lk.shopUsd': 'Mağaza $',
  'lk.shopNote': 'Mağaza $’ını USDC veya USDT ile doldur (büyük paketler bonuslu). Mağaza $ sadece burada harcanır, çekilemez. Yetmiyor mu? Fark USDC/USDT’nden alınır.',
  'lk.bagsNote': 'Kesin oranlar, sunucuda çekilir. Bir nadirliği tamamlayana kadar kopya yok; kopya fiyatının %10’unu mağaza $ olarak geri verir. Garanti: 15 açılışta Destansı+, 60’ta Efsanevi+.',
  'lk.topupFrom': 'Doldurmak için + {v} USDC/USDT',
  'lk.collected': '{a} / {b} toplandı',
  'lk.equipped': 'Giyili',
  'lk.equip': 'Giy',
  'lk.buy': 'Satın al',
  'lk.trialLeft': 'Deneme · {t} kaldı',
  'lk.trialHow': 'Rütbe denemesi: {t} daha senin. Saklamak için satın al.',
  'lk.free': 'Herkese ücretsiz.',
  'lk.inCollection': 'Koleksiyonunda.',
  'lk.buyOrBag': 'Buradan al ya da bir çantayla şansını dene.',
  'lk.tryingOn': 'Deniyorsun.',
  'lk.bonus': '+%{n} bonus',
  'lk.pay': '{v} öde',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Destansı+ için',
  'lk.legIn': 'Efsanevi+ için',
  'lk.openFree': 'Aç · ücretsiz',
  'lk.buyOpen': 'Al ve aç',
  'lk.pityDrop': 'garanti',
  'lk.dup': 'Zaten senin · {v} iade',
  'lk.new': 'Koleksiyonunda <b>yeni</b>',
  'lk.jackpotIs': 'jackpot {r}',
  'lk.showOff': 'X’te gösteriş yap',
  'lk.postMiss': 'Iskalamayı X’te paylaş',
  'lk.another': 'Bir tane daha aç',
  'lk.free1': 'ücretsiz',
  'lk.back': 'Dolaba dön',
  'lk.yours': '{n} artık senin.',
  'r.common': 'Sıradan',
  'r.rare': 'Nadir',
  'r.epic': 'Destansı',
  'r.legendary': 'Efsanevi',
  'r.mythic': 'Mitik',
  'ach.title': 'Başarımlar',
  'ach.button': 'Başarımlar',
  'ach.intro': 'Her biri bir kez rütbe XP’si verir ve adını takabileceğin bir unvan olarak açar.',
  'ach.wear': 'Unvanı tak',
  'ach.worn': 'Takılı',
  'ach.wearing': 'Unvan:',
  'ach.takeOff': 'çıkar',
  'ach.noTitle': 'Unvan yok',
  'ach.unlocked': 'Başarım açıldı',
  'ach.seeAll': 'Tüm başarımlar',
  'achd.raids': '{n} baskın oyna',
  'achd.extracts': '{n} kez tahliye ol',
  'achd.kills': '{n} öldürme yap',
  'achd.bestKills': 'Tek baskında {n} öldürme',
  'achd.bestMulti': '×{n} çoklu öldürme',
  'achd.prestige': 'Cephaneliği {n} kez bitir',
  'achd.firstBloods': '{n} kez ilk kanı dök',
  'achd.secs': 'Baskınlarda {n} saat geçir',
  'achd.bestReturn': 'Bahsinin {n} katıyla çık',
  'achd.golden': 'Altın baskından tahliye ol',
  'achd.lastExit': 'Son çıkıştan çık',
  'achd.pacifist': 'Hiç öldürmeden tahliye ol',
  'achd.rank': '{n}. rütbeye ulaş',
  'achd.outfits': '{n} kıyafete sahip ol',
  'ach.rookie': 'Acemi',
  'ach.regular': 'Müdavim',
  'ach.veteran': 'Kıdemli',
  'ach.lifer': 'Emektar',
  'ach.eternal': 'Ebedi',
  'ach.escape_artist': 'Kaçış ustası',
  'ach.ghost': 'Hayalet',
  'ach.smuggler': 'Kaçakçı',
  'ach.phantom': 'Fantom',
  'ach.first_kill': 'İlk öldürme',
  'ach.hunter': 'Avcı',
  'ach.butcher': 'Kasap',
  'ach.reaper': 'Azrail',
  'ach.apex': 'Zirve',
  'ach.rampage': 'Katliam',
  'ach.one_man_army': 'Tek kişilik ordu',
  'ach.double_tap': 'Çift atış',
  'ach.triple_threat': 'Üçlü tehdit',
  'ach.godlike': 'Tanrısal',
  'ach.full_arsenal': 'Tam cephanelik',
  'ach.arsenal_master': 'Cephanelik ustası',
  'ach.first_blood': 'İlk kan',
  'ach.opener': 'Açılışçı',
  'ach.night_shift': 'Gece vardiyası',
  'ach.insomniac': 'Uykusuz',
  'ach.double_up': 'İkiye katla',
  'ach.big_bag': 'Dolu çanta',
  'ach.gold_rush': 'Altına hücum',
  'ach.last_one_out': 'Son çıkan',
  'ach.pacifist': 'Barışçıl',
  'ach.seasoned': 'Pişmiş',
  'ach.officer': 'Subay',
  'ach.commander': 'Komutan',
  'ach.legend': 'Efsane',
  'ach.collector': 'Koleksiyoncu',
  'ach.curator': 'Küratör',
  'ach.hoarder': 'İstifçi',
};
