export default {
  'lobby.tagline': 'Bahis koy. Yağmala. Fırtınadan önce çık. <b>Çantanda ne olduğunu kimse görmez.</b>',
  'lobby.namePh': 'Koşucunun adı',
  'lobby.locker': 'Dolap · skinler · çantalar',
  'lobby.refill': 'Test coinlerini doldur',
  'lobby.online': 'Çevrimiçi',
  'lobby.practice': 'Botlara karşı antrenman',
  'lobby.stakePer': 'Baskın başına bahis',
  'lobby.stakeWith': 'Bahis coin’i <span class="fine">herhangi bir coin · $ olarak gösterilir · kazanç aynı coin ile döner</span>',
  'lobby.play': 'Oyna · {s} bahis',
  'lobby.signIn': 'Oynamak için giriş yap',
  'lobby.how': 'Nasıl oynanır',
  'lobby.gore': '<b>18+ modu.</b> Uzuvlar kopar, kan yerde kalır.',
  'lobby.fine': 'Antrenman tarayıcında çalışır. Buradaki tüm para oyun parasıdır.',
  'how.1': '<b>Bahis koy ve hazır ol.</b> Herkes bir bıçak ve 100 canla birlikte girer. Bahsinin yarısı çantanda, yarısı ganimet olarak saçılır.',
  'how.2': '<b>Turuncu ganimeti topla.</b> Çantana gider. Öldürmeler silahını yükseltir: bıçak → tabanca → pompalı → SMG → tüfek → lazer keskin nişancı.',
  'how.3': '<b>Canlı çık.</b> Fırtına kapatmadan önce yeşil bir çıkışta 3 saniye dur. Bütün çanta senin. Ölürsen başkasına düşer.',
  'how.keys': "<kbd>WASD</kbd> hareket · <kbd>fare</kbd> nişan · <kbd>tık</kbd> saldırı · <kbd>Boşluk</kbd> atılma · <kbd>Q</kbd> çanta boyutunu blöfle · <kbd>M</kbd> ses · <kbd>N</kbd> müzik",
  'how.fine': 'Her baskın ve her başarım rütbe XP’si verir. Her rütbe atlayışı sana 3 günlüğüne yeni bir skin verir.',
  'net.practice': 'Sadece sen ve botlar, çevrimdışı.',
  'net.open': 'Bağlandı. Çevrimiçi yalnızca gerçek oyuncular.',
  'reg.title': "Sunucu",
  'reg.auto': "En yakın",
  'reg.eu': "Avrupa",
  'reg.us': "Amerika",
  'reg.asia': "Asya",
  'wel.name.t': "Koşucu adını seç",
  'wel.name.b': "Selam, ben Nyx, operatörün! Atlamadan önce sana nasıl hitap edeceğimi söyle. Maçtaki herkes bu adı başının üstünde, skor tablosunda ve sohbette görür.",
  'wel.name.ph': "Koşucunun adı",
  'wel.name.rules': "3 ile 16 harf ya da rakam. Sonra Oyna sayfasından değiştirebilirsin.",
  'wel.name.dice': "Rastgele bir ad",
  'wel.next': "İleri",
  'wel.back': "Geri",
  'wel.go': "Hadi",
  'wel.region.t': "Bölgeni seç",
  'wel.region.b': "Maçlar sana yakın bir sunucuda oynanır. Ping (ms) ne kadar düşükse oyun o kadar akıcı. Hepsini senin için test ettim: yeşil olan en hızlısı.",
  'wel.region.best': "Senin için en iyisi",
  'wel.region.off': "yanıt vermiyor",
  'wel.region.players': "{n} çevrimiçi",
  'wel.region.auto': "Otomatik",
  'wel.region.autoD': "her zaman senin için en hızlısı",
  'wel.region.note': "Bölgeyi istediğin zaman Oyna sayfasından değiştirebilirsin.",
  'tut.hello.t': "DARK BAGS'e hoş geldin!",
  'tut.hello': "Ben Nyx. Birkaç dakika içinde sana **oyunun her bölümünü** göstereceğim, hiçbir şey kafanı karıştırmasın; sonra **ilk maçını birlikte** oynayacağız.\nFikir basit: maça bir **çanta** dolusu parayla (bahsinle) girersin, ganimet toplarsın, diğer koşucularla dövüşürsün ve taşıdığını almak için **canlı çıkarsın**.\nİlerlemek için **İleri** (veya → tuşu), tekrar okumak için **Geri**.",
  'tut.menu.t': "Menü",
  'tut.menu': "Her şey burada, dört grupta:\n**Oyna**: maçlar, Dereceli ve Savaş Bileti. **Mağaza**: mağaza, envanterin ve coin takası. **Sosyal**: sohbet, arkadaşlar, loncalar, posta ve davetler. **Sen**: görevler ve ayarlar.\nHer adın altındaki satır seni neyin beklediğini söyler (görevler, kasalar, mağaza sayacı). Kırmızı sayı yeni bir şey demek. Alttaki kartın rütbeni ve VIP seviyeni gösterir.",
  'tut.profile.t': "Koşucun",
  'tut.profile': "Bu sensin. **Dolabı** açmak için koşucuna dokun: kıyafetler, silah skinleri ve stil.\nAdının altında: **rütben** (1–90). Her maç rütbe XP'si verir: öldürmeler, hayatta kalmak, çıkmak, kazanmak. Başarımlar takabileceğin **unvanlar** açar.\n**Çevrimiçi**: gerçek oyunculara karşı gerçek bahisler. **Antrenman**: oyun parasıyla botlara karşı; ücretsiz ve öğrenmek için ideal.",
  'tut.goals.t': "Bugünün hedefleri",
  'tut.goals': "Günlük listen: **takvim hediyesi**, **günlük görevler**, **günün ilk galibiyeti** (+300 XP), **pass seviyen** ve **ücretsiz çevirmeler**.\nParlayan kart bir ödülün beklediği anlamına gelir: dokun, seni oraya götürsün. Her gün gel: takvim 30 gün boyunca büyür.",
  'tut.modes.t': "Oyun modları",
  'tut.modes': "5 grupta 17 mod: **Klasik**, **Silahlar**, **Takımlar**, **Etkinlikler** (Dereceli, Zombiler, Altın Hücumu) veya **Tümü**.\nHer kart kaç kişinin oynadığını, maçın ne kadar sürdüğünü, **şu an** kimin içeride ve kimin **beklediğini** gösterir. 🔥 en kalabalığı işaretler. Seçmek için karta dokun.",
  'tut.modeInfo.t': "Seçili mod",
  'tut.modeInfo': "Seçtiğin mod hakkında her şey: **nasıl kazanılır**, benden bir **ipucu** ve **ne kazandırdığı**; ayrıca oyuncular, süre ve şu an içeride kim olduğu.\nNe oynayacağını bilmiyor musun? Önce bu kutuyu oku. İlk maç için en iyisi **Raid**.",
  'tut.stake.t': "Bahsin",
  'tut.stake': "Maça ne kadar getirdiğin: **$0.10, $1, $10, $100** ya da **kendi tutarın** ($0.10 – $10.000).\n**Raid**'de bahsinin yarısı çantanda, yarısı haritaya ganimet olarak saçılır. Canlı çık, çantandaki her şey senin. **Pot modlarında** herkesin bahsi tek bir ödül olur: kazanan alır.\nKasa %5 alır. Küçük başla: $0.10 veya $1.",
  'tut.coins.t': "Her coinle bahis",
  'tut.coins': "Elindeki her coinle öde: USDC, USDT, STRK, ETH, BTC ve daha fazlası. Tutarlar dolar olarak gösterilir, neyi riske attığını hep bilirsin.\nKazancın **aynı coinle, girdiğin fiyattan** geri gelir: maç sırasındaki fiyat oynamaları hiçbir şeyi değiştirmez.",
  'tut.wallet.t': "Cüzdanın ve mağaza $'ı",
  'tut.wallet': "Üstte: **Wallet** gerçek coinlerin (istediğin zaman yatır ve çek). **Shop $** kasalar ve teklifler için mağaza kredisidir: çekilemez.\nGerçek bahisle çevrimiçi oynamak için cüzdanla ya da sadece e-postayla giriş yap. Çekimler sadece **kendi adresine** gider. Antrenman hiçbir şey gerektirmez.",
  'tut.shop.t': "Mağaza: teklifler",
  'tut.shop': "Mağazanın en üstünde:\n**Başlangıç paketi** (bir kez): Epik kıyafet, 3 kasa, 5 çevirme ve çerçeve, $1.99. **Günün mağazası**: günde altı skin, doğrudan satın al, çark yok. **Insider kart**: 30 gün boyunca günlük mağaza $ ve çevirme, +%25 pass XP. **VIP**: ne kadar ödediysen yükleme bonusun ve günlük çevirmelerin o kadar büyük.\nHer satın alma ikinci bir dokunuş ister, yanlışlıkla hiçbir şey alınmaz.",
  'tut.cases.t': "Kasalar",
  'tut.cases': "**Çantalar** kıyafet, **sandıklar** silah skini, **stil kasaları** çerçeve, afiş, öldürme efekti ve isim rengi verir. Pahalı kasaların şansı daha iyidir.\nHer kasa **tam olasılıklarını** gösterir, çekiliş sunucuda yapılır. **Garantiler**: 15 açılışta Epik veya daha iyisi, 60'ta Efsanevi. Her 10. kasa bedava. Kopya, mağaza $ olarak geri öder. Tek seferde 100'e kadar al ve aç.",
  'tut.wheel.t': "Şans çarkı",
  'tut.wheel': "Çevirme başına $0.05 ya da görevlerden, takvimden, postadan ve VIP'ten gelen çevirmelerle ücretsiz. **18 ödül**: 1 saatlik skinler, gerçek skinler, stil, hediye kasalar, mağaza $, pass XP, XP takviyeleri ve ekstra çevirmeler.\nHer ücretli çevirme **şans kasasını** doldurur: işarete ulaşan çevirme kasanın tamamını **gerçek coinle** kazanır. **Hepsini çevir** tüm ücretsiz çevirmeleri birden kullanır.",
  'tut.inventory.t': "Envanter",
  'tut.inventory': "Sahip olduğun her şey: cüzdandaki coinler, mağaza $, **açılmamış kasalar** (hepsini birden açmak için **Hepsini aç**), **ücretsiz çevirmeler**, **stilin** (çerçeve, afiş, öldürme efekti, isim rengi: burada tak), koleksiyonun ve kariyer istatistiklerin.",
  'tut.swap.t': "Takas",
  'tut.swap': "Oyun içinde bir coini diğerine küçük bir ücretle çevir. Başka bir coinle bahis yapmak ya da çekmek istediğinde işe yarar.",
  'tut.pass.t': "Savaş Bileti",
  'tut.pass': "Her ay **50 seviyeli** yeni bir sezon. Her maç onu XP ile doldurur. **Ücretsiz yol** herkese ödül verir; **premium** ($9.99) her seviyeye bir ödül ekler: zırhlar, silah ve taret skinleri, Mitik stil.\nAcelen mi var? Seviye satın al. Ödüllerini pass sayfasından al.",
  'tut.ranked.t': "Dereceli",
  'tut.ranked': "Bahisli bir battle royale; **sezon reytingini** de değiştirir. Sıralama ve öldürmeler ne kadar yükseleceğini belirler: Bronz, Gümüş, Altın, Platin, Elmas, Usta, **Neon Efsane**.\nHer yeni lig sezonda bir kez **ödül** verir (Efsanevi, Mitik, hatta Egzotik stil) ve maçtan sonra bir kasa çekilişi çıkabilir.",
  'tut.tasks.t': "Görevler",
  'tut.tasks': "**30 günlük takvim**: her geri dönüşte bir hediye (bir gün kaçırırsan baştan başlar), en büyükleri 7., 14., 21. ve 30. günlerde. **3 günlük** ve **haftalık görevler** kasa, çevirme, mağaza $ ve XP takviyesi verir.\n**Başarımlar**: 96 hedef; her biri XP, ödül ve takabileceğin bir **unvan** verir.",
  'tut.social.t': "Arkadaşlar, loncalar, sohbet",
  'tut.social': "**Arkadaş** ekle, kimin çevrimiçi olduğunu gör, mesaj at ve masana davet et. Kendi sohbeti olan bir **loncaya** katıl veya kur. **Sohbet** herkesle konuşur.\nMaçta: **Tab** skor tablosunu açar, **K** **sesli sohbet** mikrofonunu açıp kapatır (takımlar kendi takımıyla konuşur).",
  'tut.mail.t': "Posta ve davetler",
  'tut.mail': "**Posta**: oyundan hediyeli mektuplar (kasayı aç ya da çarkı doğrudan mektuptan çevir).\n**Davet et**: bağlantını paylaş. Arkadaşların hoş geldin çantası alır, sen de onlar her oynadığında mağaza $ kazanırsın.",
  'tut.settings.t': "Ayarlar",
  'tut.settings': "Ses, müzik, grafik ve efektler, kontroller, dil ve sesli sohbet. Bu turu tekrar mı istiyorsun? Burada: **Ayarlar → Tur**.",
  'tut.match.t': "İlk maçın!",
  'tut.match': "Oyunun tamamı bu. Şimdi eğlenceli kısım: **ilk maçını birlikte** oynayalım. Botlara karşı ücretsiz antrenman, kaybedecek bir şey yok. Her adımda ne yapacağını söyleyeceğim.",
  'tut.practice.t': "Antrenman'a dokun",
  'tut.practice': "**Antrenman**'a dokun (vurgulu). Botlar ve oyun parası: ücretsiz ve öğrenmek için ideal.",
  'tut.raidPick.t': "Raid'e dokun",
  'tut.raidPick': "**Raid** kartına dokun: ganimet, dövüş ve çıkış. Klasik.",
  'tut.bag.t': "Çantan",
  'tut.bag': "**$1 antrenman parası** için oynuyoruz. Bu para **çantanda**. Ganimet toplayıp onu ağırlaştır. Bir koşucuyu indir, çantası sana düşer. Sen düşersen seninki ona düşer.\nSaklamak için bir **yeşil çıkışa** ulaş ve içinde 3 saniye dur.",
  'tut.play.t': "Oyna'ya dokun",
  'tut.play': "**Oyna**'ya dokun. Hazırlık odasına gideceksin.",
  'tut.ready.t': "Hazır'a bas",
  'tut.ready': "**Hazır**'a bas, atlıyoruz!\nKontroller: **WASD** hareket, **fare** nişan, **tık** ateş, **Space** atılma, **Q** çanta boyutunu blöf yapar, **Tab** skor tablosu. Telefonda: sol başparmak hareket ettirir, sağdaki **Ateş**'i basılı tut, nişanı kendisi alır.",
  'tut.resultWon.t': "Çıktın!",
  'tut.resultWon': "İlk raid'ini kazandın! Yapabileceğini biliyordum. Antrenman parası sadece öğrenmek için. Menüye dönmek için **Masalar**'a dokun.",
  'tut.retry.t': "Tekrar dene",
  'tut.retry': "Düştün: olur, antrenman ücretsiz! **Tekrar oyna**'ya dokun. Bu sefer biraz ganimet topla, sonra bir **yeşil çıkışa** koş ve içinde 3 saniye dur.",
  'tut.bye.t': "Hazırsın, koşucu!",
  'tut.bye': "Artık oyunun tamamını biliyorsun. İpuçları: küçük bahislerle başla, **günlük görevleri** yap, **takvimi** her gün al ve **arkadaşlarla** oyna.\nBana ihtiyacın olursa: **Ayarlar → Tur**. Bol şans!",
  'nav.g.play': "Oyna",
  'nav.g.store': "Mağaza",
  'nav.g.social': "Sosyal",
  'nav.g.you': "Sen",
  'nav.s.ranked': "Liglerde yüksel",
  'nav.s.pass': "Sezon ödülleri",
  'nav.s.shop': "Kasalar, teklifler, çark",
  'nav.s.inventory': "Skinler, kasalar, stil",
  'nav.s.swap': "Coin takası",
  'nav.s.chat': "Herkesle konuş",
  'nav.s.friends': "Birlikte oynayın",
  'nav.s.guilds': "Klanlar ve sohbet",
  'nav.s.mail': "Mektuplar ve hediyeler",
  'nav.s.invite': "Arkadaşlarla kazan",
  'nav.s.achievements': "Takvim, görevler, başarımlar",
  'nav.s.settings': "Ses, kontroller, dil",
  'nav.d.pass': "Seviye {n}/50",
  'nav.d.store': "Yeni mağaza {t} sonra",
  'nav.d.inv': "{b} kasa · {s} çevirme",
  'nav.d.mail': "{n} okunmamış",
  'nav.d.tasks': "{n} alınmaya hazır",
  'mcat.all': "Tümü",
  'mcat.classic': "Klasik",
  'mcat.weapons': "Silahlar",
  'mcat.teams': "Takımlar",
  'mcat.events': "Etkinlikler",
  'mc.hot': "Popüler",
  'mc.season': "Sezon",
  'mi.waves': "Dalgalar",
  'mi.rounds': "{n} raunt × {s}",
  'mi.win': "Nasıl kazanılır:",
  'mi.tip': "İpucu:",
  'mi.pays': "Kazandırır:",
  'mi.rew': "Her öldürme ve bitiş için XP; günlük görevlere ve pass'e sayılır.",
  'mi.players': "Oyuncu",
  'mi.time': "Maç",
  'mi.now': "Şimdi",
  'mi.win.raid': "Yeşil çıkışa ulaş ve fırtına kapatmadan 3 saniye bekle: çantandaki her şey senin.",
  'mi.win.br': "Ayakta kalan son kişi ol: pot senin.",
  'mi.win.duel': "Rakibi 90 saniyede yen: iki bahsi de al.",
  'mi.win.dm': "Süre bitince en çok öldüren potu alır. Ölünce yeniden doğarsın.",
  'mi.win.gl': "Sonunda en çok öldüren kazanır. Öldürmeler medkit, taret ve lazer mayın kredisi verir.",
  'mi.win.hardcore': "Ayakta kalan son kişi potu alır. Tek isabet yeter.",
  'mi.win.weapon': "Herkes tek silahla; ayakta kalan son kişi potu alır.",
  'mi.win.team': "Takımla 3 rauntun 2'sini kazan: takım potu paylaşır.",
  'mi.win.ranked': "Üst sıralar ve öldürmeler: reytingin liglerde yükselir, her yeni lig ödül verir.",
  'mi.win.zombies': "3 arkadaşla dalgalardan sağ çık. Her dalga XP verir.",
  'mi.win.gold': "Süre bitmeden en çok altın çantayı topla: kazanan mağaza $ alır.",
  'mi.tip.raid': "Önce ganimet, sonra kavga.",
  'mi.tip.br': "Güvenli bölgede kal, diğerleri dövüşsün.",
  'mi.tip.duel': "Atılarak (Space) mermilerden kaç, durma.",
  'mi.tip.dm': "Öldürmeye devam: her öldürme silahını yükseltir.",
  'mi.tip.gl': "Kredileri erken harca: koridordaki taret senin için kazanır.",
  'mi.tip.hardcore': "Siperden sipere geç: tek atış yeter.",
  'mi.tip.weapon': "Silahın menzilini öğren, güçlü olduğu yerde dövüş.",
  'mi.tip.team': "Takımınla kal: bir düşmana iki silah kazanır.",
  'mi.tip.ranked': "Önce hayatta kal: sıralama öldürmeler kadar değerli.",
  'mi.tip.zombies': "Sırt sırta durun, medkitleri büyük dalgalara saklayın.",
  'mi.tip.gold': "Yakın çantaları al, doluyken kavgaya girme.",
  'goal.title': "Bugün",
  'goal.cal': "{d}. gün hediyesi hazır",
  'goal.claim': "Almak için dokun",
  'goal.tasks': "Görevler {a}/{b}",
  'goal.tasksS': "günlük görevler",
  'goal.first': "Bugünün ilk galibiyeti",
  'goal.firstS': "+300 XP bekliyor",
  'goal.pass': "Pass seviyesi {n}",
  'goal.passP': "premium pass",
  'goal.passF': "ücretsiz yol: premium ol",
  'goal.card': "Insider: bugünün hediyesi",
  'goal.vip': "VIP {n}: günlük çevirmeler",
  'goal.spins': "{n} ücretsiz çevirme",
  'goal.spinsS': "çarkı çevir",
  'vip.toNext': "VIP {n} için {v} daha",
  'vip.max': "En yüksek VIP",
  'vip.how': "VIP gerçek ödemelerle büyür (yüklemeler ve USDC/USDT ödemeleri), asla ücretsiz mağaza $ ile değil.",
  'vip.claim': "{n} çevirmeyi al",
  'vip.perks': "Tüm seviyeler",
  'vip.paid': "Ödenen",
  'vip.bonus': "Yükleme bonusu",
  'vip.daily': "Her gün",
  'vip.frame': "Çerçeve",
  'vip.note': "VIP avantajları konfor ve statüdür: maçta asla daha fazla güç değil.",
  'vip.got': "+{n} çevirme",
  'fw.all': "Hepsini çevir ×{n}",
  'fw.allGot': "{n} çevirme: kazandığın her şey",
  'inv.openAll': "Hepsini aç ({n})",
  'inv.openN': "Aç ×{n}",
  'bp.buyTier': "+{n} seviye · {v}",
  'bp.tiersGot': "+{n} seviye: şimdi {t}",
  'of.confirm': "Tekrar dokun: {v}",
  'of.once': "Sadece bir kez",
  'of.starter': "Başlangıç paketi",
  'of.st.outfit': "Kalıcı Epik kıyafet",
  'of.st.boxes': "2 Vault çanta + Armory kasa (tam şans)",
  'of.st.spins': "{n} çark çevirme",
  'of.buy': "Satın al · {v}",
  'of.k.outfit': "Kıyafet",
  'of.k.wskin': "Silah",
  'of.k.style': "Stil",
  'of.owned': "Sende var",
  'of.card': "Insider kart",
  'of.cardOn': "Insider · {n} gün kaldı",
  'of.cardDaily': "Her gün: {v} mağaza $ + {n} çevirme",
  'of.claimed': "Bugün alındı",
  'of.claim': "Bugünkünü al",
  'of.extend': "+30 gün · {v}",
  'of.cardTitle': "Insider kart · {d} gün",
  'of.c.now': "Hemen {v} mağaza $",
  'of.c.pass': "+%{n} pass XP",
  'of.c.frame': "{n} çerçevesi, sadece kartla",
  'of.c.value': "Her gün alırsan ayda {v} mağaza $ ve {s} çevirme.",
  'of.kicker': "Doğrudan satın al, çark yok",
  'of.store': "Günün mağazası",
  'of.newIn': "Yeni set",
  'of.storeNote': "Günde altı skin, herkes için aynı. Asla sınırlı veya Egzotik değil.",
  'of.got': "Senin: {x}",
  'of.cardGot': "Insider kart aktif: {n} gün",
  'of.claimGot': "+{v} mağaza $ ve {n} çevirme",
  'of.starterGot': "Başlangıç paketi senin: çantaları envanterden aç",
  'fw.k.credit': "{v} mağaza $",
  'fw.k.pass': "+{v} pass XP",
  'fw.k.boost': "{n} maç ×2 XP",
  'fw.k.spin': "+1 ücretsiz çevirme",
  'fw.k.box': "Hediye: {name}",
  'fw.k.style': "{r} stil öğesi",
  'fw.free': "Ücretsiz çevirme ×{n}",
  'fw.freeNote': "Görevler, günlük takvim ve postadan gelen ücretsiz çevirmeler bu çarkı döndürür. Çevirmek için çarka dokun.",
  'fw.again': "Tekrar çevir",
  'fw.styleNote': "Kalıcı bir stil öğesi: Envanter → Stil'den tak.",
  'fw.passNote': "Pass seviyene sayılır.",
  'fw.boostNote': "Sonraki maçın çift XP verir.",
  'fw.spinNote': "Bir tur daha, bizden.",
  'fw.boxNote': "Envanterinde hediye kasa: Epik'e kadar çıkar.",
  'dl.openBox': "{name} aç",
  'dl.spinNow': "Çarkı çevir",
  'inv.spins': "Ücretsiz çevirmeler",
  'vc.toggle': "Mikrofon aç/kapat (K)",
  'vc.peers': "ses: {n}",
  'vc.micOn': "Mikrofon açık: seni duyuyorlar. Kapatmak için K.",
  'vc.noMic': "Mikrofon yok: konuşmak için tarayıcıda izin ver.",
  'set.vchat': "Sesli sohbet",
  'set.vchatNote': "Maçındaki oyuncuları duy (takım modlarında takımını). K mikrofonunu açıp kapatır.",
  'sb.open': "Skor tablosu (Tab)",
  'sb.title': "Skor tablosu",
  'sb.hint': "Tab'a basılı tut",
  'sb.player': "Oyuncu",
  'sb.k': "Ö",
  'sb.d': "Ö",
  'sb.ping': "Ping",
  'sb.bot': "bot",
  'sb.zk': "Zombiler",
  'sb.gb': "Altın",
  'sb.yours': "Takımın",
  'sb.theirs': "Rakipler",
  'rd.divPrize': "Lig ödülü",
  'rd.divPrizes': "Lig ödülleri",
  'rd.divPrizesNote': "Bir lige ulaş, ödülünü sezonda bir kez kazan. Efsanevi ve Mitik stil burada ve sezon kartında kazanılır.",
  'rd.styleOf': "{r} stil",
  'inv.giftCap': "{n} hediye: en fazla Epik",
  'shop.style': "Stil",
  'shop.styleNote': "Animasyonlu çerçeveler, afişler, öldürme efektleri ve isim renkleri. Kopyalar mağaza $ iade eder.",
  'sty.title': "Stil",
  'sty.frame': "Çerçeveler",
  'sty.banner': "Afişler",
  'sty.killfx': "Öldürme efektleri",
  'sty.namefx': "İsimler",
  'sty.none': "Yok",
  'sty.worn': "takılı",
  'sty.empty': "Henüz yok: stil kasalarında, günlük takvimde ve görevlerde bulunacak {n} parça var.",
  'sty.get': "Stil al",
  'box.s-street': "Sokak Stili Kasası",
  'box.s-neon': "Neon Stil Kasası",
  'box.s-icon': "İkon Stil Kasası",
  'ach.listTitle': "Başarımlar",
  'dl.g.credit': "{v} mağaza",
  'dl.g.spin': "{n}× çark çevirme",
  'dl.g.pass': "+{n} sezon XP",
  'dl.g.xp': "+{n} XP",
  'dl.g.boost': "{n} maç boyunca ×2 XP",
  'dl.days': "{d}g {h}s",
  'dl.t.raids': "{n} maç oyna",
  'dl.t.kills': "{n} leş al",
  'dl.t.secs': "Maçlarda {n} dk geçir",
  'dl.t.firstBloods': "{n}× ilk kan",
  'dl.t.extracts': "{n}× tahliye ol",
  'dl.t.pvpKills': "{n} oyuncu öldür",
  'dl.t.headshots': "{n} kafa vuruşu yap",
  'dl.t.zKills': "{n} zombi öldür",
  'dl.t.goldBags': "{n} altın torba topla",
  'dl.t.wins': "{n}× kazan",
  'dl.t.kKnife': "Bıçakla {n} leş al",
  'dl.t.kSniper': "Keskin nişancıyla {n} leş al",
  'dl.t.rankedGames': "{n} dereceli maç oyna",
  'dl.t.zClears': "{n} zombi turunu bitir",
  'dl.calendar': "Günlük ödüller · 30 gün",
  'dl.dayOf': "Gün {d} / 30",
  'dl.lost': "Seri bozuldu: yeniden 1. gün.",
  'dl.calNote': "Her gün üst üste gel: hediyeler büyür, her 7. gün büyük.",
  'dl.best': "en iyi seri {n}",
  'dl.next': "Sonraki hediye {t} sonra",
  'dl.claim': "Al",
  'dl.done': "Tamam",
  'dl.today': "Günün görevleri",
  'dl.resets': "yenileri {t} sonra",
  'dl.sweep': "Bugün üçü birden:",
  'dl.sweepGot': "Üçü de tamam! Bonus:",
  'dl.week': "Bu hafta",
  'dl.boostLeft': "{n} maç kaldı",
  'dl.boostNone': "henüz takviye yok: görev ve takvimden kazan",
  'dl.fwDone': "Günün ilk galibiyeti: alındı",
  'dl.fwReady': "Günün ilk galibiyeti: +300 XP bekliyor",
  'dl.todayDone': "bugün biten görev",
  'dl.offline': "Günlük ödül ve görevler yalnızca çevrimiçi.",
  'dl.signIn': "Günlük ödül ve görevler için giriş yap.",
  'dl.dayGot': "Gün {d}: alındı!",
  'dl.achGot': "Başarım ödülü",
  'dl.taskGot': "Görev tamam!",
  'dl.reward': "Ödül",
  'dl.nice': "Süper!",
  'dl.streak': "{n} gün üst üste",
  'dl.seeAll': "Tüm görevler",
  'dl.taskDone': "{n} görev tamam: ödülü Görevler sayfasından al",
  'ach.habit': "Alışkanlık",
  'ach.devoted': "Sadık Dost",
  'ach.loyal': "Vefalı",
  'ach.regular_face': "Müdavim",
  'ach.dutiful': "Görev Bilinci",
  'ach.workhorse': "Çalışkan",
  'ach.taskmaster': "Görev Ustası",
  'achd.streak': "{n} gün üst üste gel",
  'achd.calDays': "{n} günlük ödül al",
  'achd.tasksDone': "{n} görev tamamla",
  'map.title': "Harita",
  'map.any': "Herhangi",
  'map.hint': "En çok oy alan kazanır, eşitlikte kura",
  'map.hintNone': "Haritaya oy ver: en çok oy alan kazanır",
  'map.now': "Harita: {m}",
  'map.docks': "Gece Rıhtımı",
  'map.chain': "Blokzincir",
  'map.lego': "Tuğla Kasaba",
  'map.dunes': "Kızıl Kumullar",
  'map.snow': "Ayaz",
  'map.lava': "Lav Ocağı",
  'map.city': "Şehir Merkezi",
  'map.neon': "Neon Atari",
  'map.blackout': "Karartma",
  'map.fantasy': "Ejder Kalesi",
  'map.toon': "Çizgi Kasaba",
  'map.gravity': "Gravity Pisti",
  'swap.rate': "Kur",
  'swap.impactK': "Fiyat etkisi",
  'swap.minGet': "En az alacağın (%{p} kayma)",
  'swap.highImpact': "Yüksek fiyat etkisi: piyasa fiyatından çok daha azını alırsın. Daha küçük bir miktar dene.",
  'swap.pick': "Bir coin seç",
  'swap.youPay': "Ödersin",
  'swap.youGet': "Alırsın",
  'swap.balance': "Bakiye",
  'swap.inGame': "oyunda",
  'swap.listNote': "AVNU doğrulanmış listesi ve Ekubo listesindeki coinler.",
  'swap.empty': "Oyun bakiyende henüz bir şey yok.",
  'rd.tabAll': "Tüm oyuncular",
  'rd.tabSeason': "Dereceli sezon",
  'rd.kd': "K/D",
  'rd.deaths': "Ölümler",
  'rd.myPvp': "PvP istatistiklerin",
  'rd.noPvp': "K/D almak için çevrimiçi bir PvP maçı oyna.",
  'rd.emptyAll': 'Henüz çevrimiçi PvP maçı yok. Bir maç oyna ve zirveye çık.',
  'rd.kdNote': "K/D = çevrimiçi PvP maçlarında öldürme ÷ ölüm (zombiler sayılmaz). K/D sıralamasına girmek için 3 maç.",
  'rd.sortBy': "Sırala",
  'rd.by.kd': "K/D",
  'rd.by.kills': "Öldürme",
  'rd.by.xp': "Rütbe XP",
  'reg.table': "Sunucu: {r}",
  'reg.closer': "Sana daha yakın: {r} ({ms} ms). Lobide onu seç ve oradakilerle oyna.",
  'net.connecting': 'Sunucuya bağlanılıyor…',
  'net.down': 'Sunucuya ulaşılamıyor. Yeniden deneniyor… Antrenman çevrimdışı çalışır.',
  'net.lost': 'Bağlantı koptu. Masalara dönülüyor.',
  'q.pick': 'Bahis için bir coin seç.',
  'q.short': '{s} bahis için yeterli {c} yok. Başka bir coin ya da daha küçük bahis seç.',
  'q.shortDeposit': '{s} bahis için yeterli {c} yok. Başka bir coin, daha küçük bahis seç ya da yatır.',
  'q.stable': '{c} ile {s} bahis koyuyorsun. Canlı çık, taşıdığın her şey senin.',
  'q.coin': 'Bugünkü fiyattan {a} = {s} bahis koyuyorsun. Kazanç aynı kurla {c} olarak döner.',
  'tb.live': 'Baskın sürüyor · {t}',
  'tb.ready': '{n} hazır · {s}sn',
  'tb.waiting': '{n} bekliyor',
  'tb.golden': 'Sıradaki: altın baskın',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Antrenman ayarları',
  'pcfg.difficulty': 'Botlar',
  'pcfg.easy': 'Kolay',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Zor',
  'pcfg.runners': 'Baskındaki koşucular',
  'pcfg.time': 'Baskın süresi',
  'rk.max': 'en yüksek rütbe',
  'rk.toNext': 'Rütbe {r} için {x} XP',
  'rk.of': 'Rütbe {r} / 90',
  'rk.rank': 'Rütbe',
  'rk.up': 'Rütbe atladın',
  'rk.xp': 'rütbe XP’si',
  'xp.Raid': 'Baskın',
  'xp.kills': '{n} öldürme',
  'xp.Damage': 'Hasar',
  'xp.Time alive': 'Hayatta kalma',
  'xp.First blood': 'İlk kan',
  'xp.Double kill': 'Çifte öldürme',
  'xp.Triple kill': 'Üçlü öldürme',
  'xp.Rampage': 'Katliam',
  'xp.Godlike': 'Tanrısal',
  'xp.Full arsenal': 'Tam cephanelik',
  'xp.Extracted': 'Tahliye',
  'xp.Profit': 'Kâr',
  'xp.Practice ×0.5': 'Antrenman ×0.5',
  'rk.newRank': "Yeni rütbe",
  'rw.continue': "Devam",
  'rw.title': 'Rütbe ödülü',
  'rw.trial': '1 saat boyunca senin',
  'rw.try': 'Dene',
  'rw.share': 'Rütbeyi paylaş',
  'prep.raid': 'Baskın {n} · {s} bahis',
  'prep.readyUp': 'Hazır mısın?',
  'prep.first': 'İlk koşucu hazır olunca geri sayım başlar.',
  'prep.live': 'Bir baskın sürüyor. Şimdi hazır ol, sonrakine herkesle birlikte gir.',
  'prep.over': 'Baskın bitti. Hazırlık odası birazdan açılır.',
  'prep.many': 'Burada herkes bıçakla başlar. Botlar son saniyelerde katılır.',
  'prep.bots': 'Botlar boş yerleri son saniyelerde doldurur.',
  'prep.open': 'boş',
  'prep.pot': 'Pot',
  'prep.cancel': 'İptal · {v} iade',
  'prep.ready': 'Hazır · {v} bahis',
  'prep.back': 'Masalara dön',
  'hud.bagPrivate': 'Çantan · gizli',
  'hud.lag': 'Sunucu yanıt vermiyor · yeniden bağlanılıyor…',
  'hud.golden': 'Altın baskın',
  'hud.goldenStart': 'Altın baskın · içeride jackpot ganimeti',
  'hud.start': 'Bıçak elde · turuncuyu topla · çıkış bul',
  'hud.bagOpened': 'Çanta açıldı · +{v}',
  'hud.arsenal': "Cephanelik tamam · yine tabanca ★",
  'hud.unlocked': '{w} açıldı',
  'hud.pnl': '{s} bahse karşı {d}',
  'hud.alive': 'İçeride {n}',
  'hud.next': 'Sıradaki: {w}',
  'hud.final': 'Son çember · son çıkış',
  'hud.closing': 'Fırtına daralıyor · {t}',
  'hud.stormIn': 'Fırtına {t} sonra ilerliyor',
  'hud.dash': 'Atıl',
  'hud.bagLook': 'Çanta görünümü',
  'hud.extracting': 'Tahliye',
  'hud.holdStill': 'Kıpırdama. Bir isabet sıfırlar.',
  'hud.sound': 'Ses',
  'hud.music': 'Müzik',
  'bluff.0': 'küçük',
  'bluff.1': 'orta',
  'bluff.2': 'şişkin',
  'touch.move': 'hareket',
  'touch.aim': 'nişan · ateş',
  'touch.bag': 'Çanta',
  'w.Knife': 'Bıçak',
  'w.Pistol': 'Tabanca',
  'w.Shotgun': 'Pompalı',
  'w.SMG': 'SMG',
  'w.Rifle': 'Tüfek',
  'w.Laser sniper': 'Lazer keskin nişancı',
  'w.Hand Cannon': "El topu",
  'w.Auto Shotgun': "Otomatik pompalı",
  'w.PDW': "PDW",
  'w.Carbine': "Karabina",
  'w.Scout': "İzci",
  'w.Machine Gun': "Makineli tüfek",
  'w.Magnum Sniper': "Magnum keskin nişancı",
  'hud.reloading': "Şarjör değişiyor",
  'streak.1': 'İlk kan',
  'streak.2': 'Çifte öldürme',
  'streak.3': 'Üçlü öldürme',
  'streak.4': 'Katliam',
  'streak.5': 'Tanrısal',
  'streak.you1': 'İlk kanı sen döktün',
  'feed.storm': 'Fırtına seni aldı',
  'feed.droppedYou': '{name} seni indirdi',
  'coach.storm': 'Fırtınadasın · çemberin içine dön',
  'coach.touch': "Sol başparmak hareket · Ateş'e basılı tut: en yakın düşmana kendisi nişan alır",
  'coach.keys': 'WASD hareket · fare nişan · tık saldırı',
  'coach.exit': 'Çıkma zamanı · yeşil bir ÇIKIŞTA 3 saniye dur · kenardaki oklar yolu gösterir',
  'coach.loot': 'Turuncu ganimeti topla · çantana gider',
  'coach.kills': 'Öldürmeler silahını yükseltir · Boşluk ile atıl',
  'coach.killsTouch': 'Öldürmeler silahını yükseltir · kaçmak için Atıl’a dokun',
  'spect.watching': '{name} izleniyor · ◀ ▶ değiştir',
  'spect.down': 'Düştün',
  'spect.results': 'Sonuçlar',
  'res.extracted': 'Tahliye edildi',
  'res.storm': 'Fırtına yuttu',
  'res.dropped': 'İndirildin',
  'res.sealed': 'İçeride kaldın',
  'res.inside': '{k} öldürme · içeride {t}',
  'res.out': '{s} bahisle {p} ile çıktın: {d}.',
  'res.paid': 'Giriş kurundan {v} ödendi.',
  'res.killer': 'Çantan artık {n} kişisinde. İçinde {v} vardı ve bunu sadece ikiniz bileceksiniz.',
  'res.inStorm': 'Çantan, {v}, cesaret edene fırtınada duruyor.',
  'res.sealedText': 'Baskın sen içerideyken kapandı. {v} sonraki baskının ganimetine geçti.',
  'res.again': 'Tekrar oyna',
  'res.tables': 'Masalar',
  'res.share': 'Paylaş',
  'share.title': 'Paylaş',
  'share.x': '𝕏’te paylaş',
  'share.copy': 'Görseli kopyala',
  'share.save': 'PNG kaydet',
  'share.close': 'Kapat',
  'lk.title': 'Dolap',
  'lk.outfits': 'Kıyafetler',
  'lk.shop': 'Mağaza',
  'lk.bags': 'Şans çantaları',
  'lk.sortDesc': "Önce en nadir ↓",
  'lk.sortAsc': "Önce en yaygın ↑",
  'lk.allGuns': "Tüm silahlar",
  'lk.takeOff': "Çıkar",
  'lk.empty': "Henüz boş: mağazadaki çanta ve kasalar koleksiyonunu doldurur.",
  'lk.emptyTurrets': "Henüz taret görünümün yok: savaş biletinden gelir.",
  'lk.pickSkin': "Önizlemek için bir görünüme dokun, sonra kuşan.",
  'lk.all': 'Tümü',
  'lk.owned': 'Benimkiler',
  'lk.him': 'Erkek',
  'lk.her': 'Kadın',
  'lk.shopUsd': 'Mağaza $',
  'lk.shopNote': 'Mağaza $’ını USDC veya USDT ile doldur (büyük paketler bonuslu). Mağaza $ sadece burada harcanır, çekilemez. Yetmiyor mu? Fark USDC/USDT’nden alınır.',
  'lk.bagsNote': 'Kesin oranlar, sunucuda çekilir. Bir nadirliği tamamlayana kadar kopya yok; kopya fiyatının %10’unu mağaza $ olarak geri verir. Garanti: 15 açılışta Destansı+, 60’ta Efsanevi+.',
  'lk.topupFrom': 'Doldurmak için + {v} USDC/USDT',
  'lk.collected': '{a} / {b} toplandı',
  'lk.equipped': 'Giyili',
  'lk.equip': 'Giy',
  'lk.buy': 'Satın al',
  'lk.trialLeft': 'Deneme · {t} kaldı',
  'lk.trialHow': 'Rütbe denemesi: {t} daha senin. Saklamak için satın al.',
  'lk.free': 'Herkese ücretsiz.',
  'lk.inCollection': 'Koleksiyonunda.',
  'lk.buyOrBag': 'Buradan al ya da bir çantayla şansını dene.',
  'lk.tryingOn': 'Deniyorsun.',
  'lk.bonus': '+%{n} bonus',
  'lk.pay': '{v} öde',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Destansı+ için',
  'lk.legIn': 'Efsanevi+ için',
  'lk.openFree': 'Aç · ücretsiz',
  'lk.buyOpen': 'Al ve aç',
  'lk.pityDrop': 'garanti',
  'lk.dup': 'Zaten senin · {v} iade',
  'lk.new': 'Koleksiyonunda <b>yeni</b>',
  'lk.jackpotIs': 'jackpot {r}',
  'lk.showOff': 'X’te gösteriş yap',
  'lk.postMiss': 'Iskalamayı X’te paylaş',
  'lk.another': 'Bir tane daha aç',
  'lk.free1': 'ücretsiz',
  'lk.back': 'Dolaba dön',
  'lk.yours': '{n} artık senin.',
  'r.common': 'Sıradan',
  'r.rare': 'Nadir',
  'r.epic': 'Destansı',
  'r.legendary': 'Efsanevi',
  'r.mythic': 'Mitik',
  'r.exotic': 'Egzotik',
  'ach.title': "Görevler ve başarımlar",
  'ach.button': 'Başarımlar',
  'ach.intro': 'Her biri bir kez rütbe XP’si verir ve adını takabileceğin bir unvan olarak açar.',
  'ach.wear': 'Unvanı tak',
  'ach.worn': 'Takılı',
  'ach.wearing': 'Unvan:',
  'ach.takeOff': 'çıkar',
  'ach.noTitle': 'Unvan yok',
  'ach.unlocked': 'Başarım açıldı',
  'ach.seeAll': 'Tüm başarımlar',
  'achd.raids': '{n} baskın oyna',
  'achd.extracts': '{n} kez tahliye ol',
  'achd.kills': '{n} öldürme yap',
  'achd.bestKills': 'Tek baskında {n} öldürme',
  'achd.bestMulti': '×{n} çoklu öldürme',
  'achd.prestige': 'Cephaneliği {n} kez bitir',
  'achd.firstBloods': '{n} kez ilk kanı dök',
  'achd.secs': 'Baskınlarda {n} saat geçir',
  'achd.bestReturn': 'Bahsinin {n} katıyla çık',
  'achd.golden': 'Altın baskından tahliye ol',
  'achd.lastExit': 'Son çıkıştan çık',
  'achd.pacifist': 'Hiç öldürmeden tahliye ol',
  'achd.rank': '{n}. rütbeye ulaş',
  'achd.outfits': '{n} kıyafete sahip ol',
  'ach.gunslinger': "Silahşor",
  'ach.close_quarters': "Yakın dövüş",
  'ach.spray_and_pray': "Mermi yağmuru",
  'ach.rifleman': "Tüfekçi",
  'ach.marksman': "Nişancı",
  'ach.deadeye': "Şahin gözü",
  'ach.blade_dancer': "Bıçak dansçısı",
  'ach.shadow_blade': "Gölge bıçak",
  'ach.deathmatch_king': "Ölüm maçı kralı",
  'ach.duelist': "Düellocu",
  'ach.squad_goals': "Takım ruhu",
  'ach.one_shot_one_kill': "Tek atış tek leş",
  'ach.specialist': "Uzman",
  'ach.engineer': "Mühendis",
  'ach.ranked_debut': "Dereceli ilk maç",
  'ach.ranked_grinder': "Dereceli emekçi",
  'ach.ranked_victor': "Dereceli galip",
  'ach.gold_league': "Altın lig",
  'ach.diamond_league': "Elmas lig",
  'ach.neon_legend': "Neon Efsane",
  'ach.unboxer': "Kutu açıcı",
  'ach.case_hunter': "Kasa avcısı",
  'ach.case_lord': "Kasaların efendisi",
  'ach.armory': "Cephanelik",
  'ach.arsenal_baron': "Silah baronu",
  'ach.pass_holder': "Bilet sahibi",
  'ach.pass_maxed': "Bilet tamam",
  'ach.neon_bearer': "Neon taşıyıcı",
  'ach.by_a_thread': "Kıl payı",
  'ach.untouchable': "Dokunulmaz",
  'ach.ghost_walker': "Hayalet adım",
  'ach.one_tap': "Tek dokunuş",
  'achd.kHandgun': "Tabancayla {n} leş al",
  'achd.kShotgun': "Pompalıyla {n} leş al",
  'achd.kSmg': "SMG ile {n} leş al",
  'achd.kRifle': "Tüfek ve makineliyle {n} leş al",
  'achd.kSniper': "Keskin nişancıyla {n} leş al",
  'achd.kKnife': "Bıçakla {n} leş al",
  'achd.dmWins': "{n} ölüm maçı kazan",
  'achd.duelWins': "{n} düello kazan",
  'achd.teamWins': "{n} takım maçı kazan",
  'achd.hcWins': "{n} hardcore maç kazan",
  'achd.weaponWins': "{n} tek silah maçı kazan",
  'achd.turretKills': "Silahlar + Lazerler’de taretlerle {n} leş al",
  'achd.rankedGames': "{n} dereceli maç oyna",
  'achd.rankedWins': "{n} dereceli maç kazan",
  'achd.bestDiv': "Derecelide {n} ligine ulaş",
  'achd.opened': "{n} kasa ve çanta aç",
  'achd.wskins': "{n} silah görünümüne sahip ol",
  'achd.passTier': "Savaş biletinde {n}. seviyeye ulaş",
  'achd.stitles': "Bir sezon unvanı kazan",
  'achd.clutch': "10 veya daha az canla çık",
  'achd.flawless': "2+ dakika hiç vurulmadan çık",
  'achd.ninjaWin': "Bir pot modunu tek leş almadan kazan",
  'achd.oneShots': "{n} koşucuyu tam candan tek vuruşta indir",
  'ach.secret': "Gizli",
  'ach.secretDesc': "Oynamaya devam et: kazandığında ortaya çıkar.",
  'r.mystery': "Gizem",
  'ach.rookie': 'Acemi',
  'ach.regular': 'Müdavim',
  'ach.veteran': 'Kıdemli',
  'ach.lifer': 'Emektar',
  'ach.eternal': 'Ebedi',
  'ach.escape_artist': 'Kaçış ustası',
  'ach.ghost': 'Hayalet',
  'ach.smuggler': 'Kaçakçı',
  'ach.phantom': 'Fantom',
  'ach.first_kill': 'İlk öldürme',
  'ach.hunter': 'Avcı',
  'ach.butcher': 'Kasap',
  'ach.reaper': 'Azrail',
  'ach.apex': 'Zirve',
  'ach.rampage': 'Katliam',
  'ach.one_man_army': 'Tek kişilik ordu',
  'ach.double_tap': 'Çift atış',
  'ach.triple_threat': 'Üçlü tehdit',
  'ach.godlike': 'Tanrısal',
  'ach.full_arsenal': 'Tam cephanelik',
  'ach.arsenal_master': 'Cephanelik ustası',
  'ach.first_blood': 'İlk kan',
  'ach.opener': 'Açılışçı',
  'ach.night_shift': 'Gece vardiyası',
  'ach.insomniac': 'Uykusuz',
  'ach.double_up': 'İkiye katla',
  'ach.big_bag': 'Dolu çanta',
  'ach.gold_rush': 'Altına hücum',
  'ach.last_one_out': 'Son çıkan',
  'ach.pacifist': 'Barışçıl',
  'ach.seasoned': 'Pişmiş',
  'ach.officer': 'Subay',
  'ach.commander': 'Komutan',
  'ach.legend': 'Efsane',
  'ach.collector': 'Koleksiyoncu',
  'ach.curator': 'Küratör',
  'ach.hoarder': 'İstifçi',
  'intro.tag': "Bahis koy. Yağmala. Çık.",
  'intro.go': "Gir",
  'intro.fonts': "Bıçaklar biliniyor…",
  'intro.world': "Karanlık çiziliyor…",
  'intro.connect': "Baskın aranıyor…",
  'intro.profile': "Çantan hazırlanıyor…",
  'intro.ready': "Hazır",
  'tb.wallet': "Cüzdan",
  'tb.shop': "Mağaza $",
  'nav.play': "Oyna",
  'nav.shop': "Mağaza",
  'nav.inventory': "Envanter",
  'nav.swap': "Takas",
  'nav.chat': "Sohbet",
  'nav.achievements': "Görevler",
  'nav.pass': "Bilet",
  'bp.season': "Sezon {n}",
  'bp.ends': "{d}g {h}s sonra bitiyor",
  'bp.tier': "Seviye {n}/{m}",
  'bp.xp': "Sonraki seviyeye {a}/{b} XP",
  'bp.maxed': "Tüm seviyeler tamam",
  'bp.how': "Her baskın, bileti rütben kadar XP ile doldurur.",
  'bp.free': "Ücretsiz",
  'bp.premium': "Premium",
  'bp.buy': "Premium bilet · {v}",
  'bp.owned': "Premium aktif",
  'bp.perks': "50 seviyenin tüm ödülleri: Savaş Lordu ve Zirve zırhları, 2 taret görünümü, 5 sezonluk silah görünümü, kasalar ve $.",
  'bp.claim': "Al",
  'bp.claimAll': "Hepsini al ({n})",
  'bp.claimed': "Alındı",
  'bp.limited': "Yalnızca bu sezon",
  'bp.turrets': "Taret görünümleri",
  'bp.turretsNote': "Silahlar + Lazerler modundaki taretlerin.",
  'bp.equip': "Kuşan",
  'bp.equipped': "Kuşanıldı",
  'bp.none': "Sade",
  'bp.up': "Savaş bileti: seviye {n}!",
  'bp.got': "Alındı: {x}",
  'bp.credit': "+{v} mağaza",
  'mode.ranked': "Dereceli",
  'mode.ranked.d': "Sezon puanın için battle royale. Bronzdan Neon Efsane'ye tırman; üst sıralar bonus çark kazanır.",
  'nav.ranked': "Dereceli",
  'rd.title': "Dereceli · Sezon {n}",
  'rd.pos': "#{n} / {m}",
  'rd.unranked': "Tabloya girmek için bir dereceli maç oyna.",
  'rd.play': "Dereceli oyna",
  'rd.games': "Maçlar",
  'rd.wins': "Galibiyet",
  'rd.top3': "İlk 3",
  'rd.kills': "Leş",
  'rd.winrate': "Kazanma oranı",
  'rd.player': "Oyuncu",
  'rd.div': "Lig",
  'rd.div.bronze': "Bronz",
  'rd.div.silver': "Gümüş",
  'rd.div.gold': "Altın",
  'rd.div.platinum': "Platin",
  'rd.div.diamond': "Elmas",
  'rd.div.master': "Usta",
  'rd.div.legend': "Neon Efsane",
  'rd.titles': "Sezon unvanları",
  'rd.titlesNote': "Dereceli bonus çarkından çıkar. Adının üstünde neonla parlar, sezon bitene kadar XP bonusu verir.",
  'rd.wear': "Tak",
  'rd.off': "Çıkar",
  'rd.bonus': "+{p}% XP",
  'rd.expired': "sezon bitti",
  'rd.board': "Sezon tablosu",
  'rd.empty': "Bu sezon henüz kimse dereceli oynamadı. İlk sen ol.",
  'rd.place': "Sıra #{p} / {n}",
  'rd.promoted': "terfi!",
  'rd.demoted': "düşüş",
  'rd.practice': "Antrenman: puanın değişmez.",
  'rd.spin': "Bonus çark",
  'rd.spinWhy': "#{p}. sıra için",
  'rd.won': "Kazandın:",
  'rd.wornNow': "Yeni unvanın şimdiden parlıyor.",
  'st.contender': "Aday",
  'st.elite': "Elit",
  'st.champion': "Şampiyon",
  'xp.Season title': "Sezon unvanı",
  'news.title': "Yenilikler",
  'news.ok': "Anladım",
  'news.note': "Her güncelleme, tarih ve saatiyle.",
  'news.open': "Aç",
  'stake.own': "Kendi bahsin",
  'stake.range': "Bahis $0.10 ile $10.000 arası",
  'nav.settings': "Ayarlar",
  'nav.more': "Daha",
  'modes.title': "Oyun modu",
  'kind.raid': "tahliye",
  'kind.br': "kazanan potu alır",
  'kind.team': "takım potu",
  'mode.raid': "Baskın",
  'mode.raid.d': "Yağmala, savaş, bir çıkıştan çık. Taşıdığın senin.",
  'mode.br': "Battle Royale",
  'mode.br.d': "20 koşucuya kadar. Ayakta kalan son kişi tüm potu alır.",
  'mode.duel': "Düello",
  'mode.duel.d': "Bire bir. Kazanan iki bahsi de alır.",
  'mode.knives': "Sadece bıçak",
  'mode.knives.d': "Tüm baskın boyunca sadece bıçak. Ayakta kalan son kişi kazanır.",
  'mode.pistols': "Sadece tabanca",
  'mode.pistols.d': "Sadece tabancalar. Ayakta kalan son kişi kazanır.",
  'mode.shotguns': "Sadece pompalı",
  'mode.shotguns.d': "Yakın ve gürültülü. Ayakta kalan son kişi kazanır.",
  'mode.rifles': "Sadece tüfek",
  'mode.rifles.d': "Orta menzilli çatışmalar. Ayakta kalan son kişi kazanır.",
  'mode.snipers': "Sadece keskin nişancı",
  'mode.snipers.d': "Her yerde lazer nişangâh. Ayakta kalan son kişi kazanır.",
  'mode.team2': "Takım 2'ye 2",
  'mode.team2.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'mode.team4': "Takım 4'e 4",
  'mode.team4.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'mode.team8': "Takım 8'e 8",
  'mode.team8.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'hud.pot': "Ödül potu",
  'hud.left': "{n} kaldı · {s} bahis",
  'hud.teamsLeft': "{n} takım kaldı · {s} bahis",
  'hud.startPot': "Ayakta kalan son kişi potu alır",
  'hud.startTeam': "Takımınla kal · diğer tarafı sil",
  'hud.goldenPot': "Altın baskın · jackpot pota eklendi",
  'coach.pot': "Burada çıkış yok · çemberde kal · son ayakta kalan kazanır",
  'coach.team': "Yeşil isimler takımın · kırmızılar düşman",
  'warn.exit30': "30sn · açık bir çıkışa ulaş",
  'warn.exit10': "10sn · tahliye ol ya da hepsini kaybet",
  'warn.pot30': "30sn · fırtına daralıyor",
  'warn.pot10': "10sn · en çok hayatta kalan kazanır",
  'storm.final': "Son çöküş · sadece son çıkış",
  'storm.finalPot': "Son çöküş · saklanacak yer yok",
  'storm.closing': "Fırtına yaklaşıyor",
  'storm.in5': "Fırtına 5sn sonra ilerliyor",
  'feed.youDropped': "{name} kişisini indirdin",
  'feed.stormTook': "{name} fırtınaya yem oldu",
  'feed.dropped': "{a}, {b} kişisini indirdi",
  'feed.down': "{name} düştü",
  'feed.extracted': "{name} tahliye oldu",
  'feed.exitClosed': "{name} çıkışı kapandı",
  'spect.settling': "Sonucun baskın bitince gelecek.",
  'res.victory': "Zafer",
  'res.teamWon': "Takımın kazandı",
  'res.defeated': "Yenilgi",
  'res.wonText': "{s} bahisle {p} kazandın.",
  'res.lostPot': "Pot ayakta kalan son kişiye gitti.",
  'res.teamLost': "Potu diğer takım aldı.",
  'xp.Victory': "Zafer",
  'ach.champion': "Şampiyon",
  'ach.warlord': "Savaş lordu",
  'achd.wins': "{n} pot baskını kazan",
  'lk.weapons': "Silah skinleri",
  'lk.onlyBags': "Skinler sadece mağazadaki çanta ve sandıklardan çıkar.",
  'lk.toShop': "Mağazayı aç",
  'lk.toOpen': "{n} açılmayı bekliyor",
  'lk.limited': "Sınırlı · {n}",
  'lk.minted': "{b} adetin {a} tanesi basıldı",
  'lk.plain': "Standart",
  'lk.fromBags': "Mağazadaki kıyafet çantalarından çıkar.",
  'lk.fromCrates': "Mağazadaki silah sandıklarından çıkar.",
  'lk.trialHow2': "Rütbe denemesi: {t} daha senin.",
  'lk.weaponHow': "Giymek için sahip olduğun bir kaplamayı seç. Baskındaki herkes görür.",
  'fx.glow': "aura",
  'fx.pulse': "nabız gibi aura",
  'fx.ghost': "hayaletimsi",
  'fx.laser': "lazer gözler",
  'fx.rainbow': "prizmatik",
  'fx.fire': "alevli",
  'fx.gold': "sıvı altın",
  'fx.holo': "hologram",
  'fx.glitch': "glitch",
  'fx.lightning': "şimşek",
  'fx.galaxy': "galaksi",
  'fx.sparks': "kıvılcım",
  'fx.frost': "kırağı",
  'fx.money': "para yağmuru",
  'fx.matrix': "kod yağmuru",
  'fx.shadow': "gölge dumanı",
  'fx.cape': "pelerin",
  'box.c-samurai': "Siber Samuray Kasası",
  'box.c-neon': "Neon Geceler Kasası",
  'box.c-arctic': "Arktik Kasası",
  'box.c-inferno': "Cehennem Kasası",
  'box.c-crypto': "Kripto Krallar Kasası",
  'box.c-toxic': "Zehirli Çorak Kasası",
  'box.c-toon': "Çizgi Kasaba Kasası",
  'box.c-knife': "Bıçak Kasası",
  'box.c-pistol': "Tabanca Kasası",
  'box.c-smg': "SMG Kasası",
  'box.c-rifle': "Tüfek Kasası",
  'box.c-heavy': "Ağır Kasa",
  'box.c-sniper': "Keskin Nişancı Kasası",
  'box.b-crypto': "Kripto Mimler Çantası",
  'box.b-heroes': "Çoklu Evren Kahramanları Çantası",
  'box.b-monsters': "Canavarlar ve Mitler Çantası",
  'box.b-cyber': "Siber Sokak Çantası",
  'box.b-toon': "Çizgi Dostlar Çantası",
  'shop.g.theme': "Koleksiyonlar",
  'shop.g.class': "Silah sınıfı kasaları",
  'shop.g.tier': "Seviye kasaları",
  'shop.contents': "İçerik · {n} eşya",
  'box.street': "Sokak Çantası",
  'box.vault': "Kasa Çantası",
  'box.golden': "Altın Çanta",
  'box.elite': "Elit Çanta",
  'box.diamond': "Elmas Çanta",
  'box.obsidian': "Obsidyen Çanta",
  'box.royal': "Kraliyet Çantası",
  'box.apex': "Apex Çanta",
  'box.genesis': "Genesis Çanta",
  'box.w-scrap': "Hurda Sandığı",
  'box.w-armory': "Cephanelik Sandığı",
  'box.w-brass': "Pirinç Sandık",
  'box.w-specops': "Özel Harekât Sandığı",
  'box.w-diamond': "Elmas Sandık",
  'box.w-obsidian': "Obsidyen Sandık",
  'box.w-royal': "Kraliyet Sandığı",
  'box.w-apex': "Apex Sandık",
  'box.w-genesis': "Genesis Sandık",
  'shop.topup': "Mağaza $ yükle",
  'shop.bags': "Kıyafet çantaları",
  'shop.crates': "Silah sandıkları",
  'shop.bagsNote': "Koşucun için kıyafetler. Dokuz seviye: çanta ne kadar pahalıysa şans o kadar iyi.",
  'shop.cratesNote': "Silahların ve bıçağın için skinler, kıyafetlerden ayrı satılır. Dokuz seviye.",
  'shop.fair': "Kesin oranlar, sunucuda çekilir. Garanti: {e} açılışta Destansı+, {l} açılışta Efsanevi+.",
  'shop.odds': "Oranlar ve garanti",
  'shop.qty': "Adet",
  'shop.open': "Aç ×{n}",
  'shop.limited': "Sınırlı sürümler",
  'shop.soldOut': "Tükendi",
  'shop.dup': "Kopya · +{v}",
  'shop.new': "Yeni",
  'shop.back': "{v} iade",
  'shop.equipBest': "{n} giy",
  'inv.wallet': "Cüzdan",
  'inv.deposit': "Yatır · çek",
  'inv.walletNote': "Evin senin için tuttuğu gerçek tokenlar. Giriş yaptığın adrese istediğin zaman çek.",
  'inv.playNote': "Bu tarayıcıda oyun parası. İstediğin zaman doldur.",
  'inv.shopNote': "USDC/USDT ile alınır, sadece çanta ve sandıklara harcanır. Çekilemez.",
  'inv.unopened': "Açılmamış",
  'inv.collection': "Koleksiyon",
  'inv.opened': "Açılan",
  'inv.career': "Kariyer",
  'inv.raids': "Baskınlar",
  'inv.kills': "Öldürmeler",
  'inv.extracts': "Tahliyeler",
  'inv.wins': "Pot zaferleri",
  'inv.best': "En iyi baskın (öldürme)",
  'inv.time': "İçeride geçen süre",
  'swap.game': "Oyun bakiyesi",
  'swap.gameNote': "Anında, güncel fiyattan, %{f} ücret.",
  'swap.gameOff': "Bu sunucuda oyun içi takas kapalı. Aşağıdaki cüzdan takasını kullan.",
  'swap.from': "Verdiğin",
  'swap.to': "Aldığın",
  'swap.have': "Sende",
  'swap.flip': "Yönü çevir",
  'swap.go': "Takas et",
  'swap.short': "Yetersiz bakiye",
  'swap.done': "{a}, {b} ile takas edildi.",
  'swap.wallet': "Cüzdanın",
  'swap.signIn': "AVNU ile orada takas yapmak için bir Starknet cüzdanıyla giriş yap.",
  'swap.needChain': "AVNU takasları çevrimiçi modda gerçek bir Starknet cüzdanıyla çalışır.",
  'swap.slippage': "Maks. kayma",
  'swap.quoting': "En iyi rota aranıyor…",
  'swap.impact': "fiyat etkisi %{p}",
  'swap.goAvnu': "AVNU ile takas et",
  'swap.noQuote': "Bu çift için şu an rota yok.",
  'swap.sent': "Takas gönderildi: {tx}",
  'swap.walletNote': "AVNU, Starknet borsaları arasında rota bulur. Sen cüzdanında imzalarsın; oyun bu tokenları asla tutmaz.",
  'chat.ph': "Bir şey yaz…",
  'chat.send': "Gönder",
  'chat.empty': "Henüz mesaj yok. gm de.",
  'chat.online': "Lobideki herkes bunu görür. Kibar ol.",
  'chat.practice': "Antrenman çevrimdışı: sadece botlar dinliyor.",
  'set.graphics': "Grafik",
  'set.quality': "Kalite",
  'set.qualityNote': "Otomatik, kareler yavaşlayınca detayı düşürür.",
  'set.auto': "Otomatik",
  'set.high': "Yüksek",
  'set.medium': "Orta",
  'set.low': "Düşük",
  'set.shake': "Ekran sarsıntısı",
  'set.motion': "Menü animasyonları",
  'set.display': "Görünüm",
  'set.skins': "Skinler",
  'set.skinsNote': "Kimin kıyafet ve silah skinleri çizilsin.",
  'set.skinsAll': "Herkesin",
  'set.skinsMine': "Sadece benimkiler",
  'set.skinsNone': "Hiçbiri",
  'set.names': "Koşucuların üstünde isimler",
  'set.titles': "İsimlerin üstünde unvanlar",
  'set.controls': "Kontroller",
  'set.stick': "Dokunmatik çubuk boyutu",
  'set.lefty': "Solak (dokunmatik)",
  'set.leftyNote': "Hareket ve nişan çubuklarının yerini değiştirir.",
  'set.audio': "Ses",
  'set.sound': "Efekt sesi",
  'set.music': "Müzik sesi",
  'set.track': "Müzik",
  'set.trackAuto': "Karışık",
  'set.trackNote': "Her maçta farklı bir parça ya da en sevdiğin hep çalsın.",
  'pause.nextTrack': "Sonraki parça ⏭",
  'set.language': "Dil",
  'shop.exoticIn': "Egzotik için",
  'shop.guarantee': "{n} açılışta garantili Egzotik",
  'set.voice': "Spiker",
  'mode.dm': "Ölüm Maçı",
  'mode.dm.d': "Herkes kendi için, her ölümden sonra yeniden doğ. Süre bittiğinde en çok leşi alan potu kazanır.",
  'mode.gl': "Silahlar + Lazerler",
  'mode.gl.d': "Mağazalı ölüm maçı: leşler ilk yardım çantası, taret ve lazer mayını için kredi kazandırır.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "En az can: tek kurşun ve düşersin. Ayakta kalan son kişi potu alır.",
  'kind.dm': "en çok leş potu alır",
  'hud.startDm': "Süre sıfırlandığında en çok leşi alan potu kazanır",
  'hud.startGl': "Leşler kredi kazandırır · 1 ilk yardım · 2 taret · 3 lazer mayını",
  'hud.startHc': "Tek isabet ve düşersin. Her atışı değerlendir.",
  'hud.respawned': "Geri döndün",
  'hud.respawnIn': "{s}sn içinde geri dönüş",
  'hud.tookLead': "Liderliği aldın",
  'hud.lostLead': "Liderliği kaybettin",
  'hud.dmScore': "{k} leş · {d} ölüm · #{p}",
  'hud.dmGoal': "İlk leş liderliği alır",
  'hud.oneHit': "1 İSABET",
  'feed.leader': "{name} {k} leşle liderliği aldı",
  'gl.medkit': "İlk yardım",
  'gl.turret': "Taret",
  'gl.mine': "Lazer mayını",
  'gl.revive': "Takımı dirilt",
  'gl.no.none': "Düşen kimse yok",
  'gl.no.mode': "Sadece zombi modunda",
  'gl.revived': "{name} takımdan {n} kişiyi diriltti",
  'gl.you': "Sen",
  'gl.no.cash': "Yetersiz kredi",
  'gl.no.full': "Canın zaten dolu",
  'gl.no.limit': "Sınıra ulaşıldı",
  'gl.no.wall': "Duvara çok yakın",
  'res.dmLost': "#{p}. oldun",
  'res.dmText': "{k} leş, {d} ölüm. Kazananın {top} leşi vardı.",
  'coach.dm': "Yeniden doğarsın · süre bitince en çok leşi olan kazanır",
  'coach.gl': "Leşler kredi kazandırır · ilk yardım ✚, taret ◈ ya da lazer mayını ⌁ al",
  'set.voiceNote': "Kayıtlı spiker (İngilizce, Ukraynaca, İspanyolca, Fransızca, Portekizce; diğer diller için İngilizce).",
  'net.waking': "Sunucu uyanıyor (ücretsiz barındırma kimse oynamazken uyur, bir dakikaya kadar)… Bu sırada antrenman çalışır.",
  'shop.bulk': "Her {n}. kutu bedava",
  'shop.bulkOn': "Dahil bedava kutu: {n}",
  'net.online': "{n} çevrimiçi",
  'st.title': "İlk adımlar",
  'st.signin': "Giriş yap",
  'st.signin.d': "Starknet cüzdanın, Cartridge ya da e-posta ile.",
  'st.signin.go': "Giriş yap",
  'st.fund': "Bakiye ekle",
  'st.fund.d': "Cüzdanından oyun bakiyene biraz token gönder. İstediğin zaman çekebilirsin.",
  'st.fundTest': "Test ağı: starknet-faucet.vercel.app adresinde ücretsiz STRK.",
  'st.fund.go': "Yatır",
  'st.coin': "Coinini seç",
  'st.coin.d': "Aşağıdan hangi coinle bahis yapacağını seç. Kazanç aynı coinle döner.",
  'st.coin.go': "Coinleri göster",
  'st.play': "İlk maçını oyna",
  'st.play.d': "Mod ve bahis seç, Oyna'ya ve sonra Hazır'a bas.",
  'st.play.go': "Oyna",
  'touch.fire': "Ateş",
  'rot.title': "Telefonunu yan çevir",
  'rot.sub': "Baskın yatay oynanınca daha iyi: solda hareket, sağda ateş.",
  'rot.anyway': "Dikey oyna",
  'prep.waiting': "Oyuncular bekleniyor",
  'prep.waitingMe': "Süre yok: arkadaşlarını çağır, hazır olunca Başlat'a bas. Boş yerlere botlar gelir. {of} yerden {n} dolu.",
  'prep.waitingJoin': "{of} yerden {n} dolu. Katılmak için bahis yap ve Hazır'a bas.",
  'prep.firstWait': "Hazır'a bas: oda herkesi bekler, süre yok.",
  'prep.start': "Şimdi başlat",
  'nav.friends': "Arkadaşlar",
  'nav.guilds': "Loncalar",
  'so.now': "şimdi",
  'so.min': "{n} dk önce",
  'so.hr': "{n} sa önce",
  'so.day': "{n} g önce",
  'so.seen': "Son görülme {t}",
  'so.st.lobby': "Çevrimiçi",
  'so.st.waiting': "Odada bekliyor",
  'so.st.raid': "Baskında",
  'so.friend': "Arkadaş",
  'so.sent': "İstek gönderildi",
  'so.accept': "Kabul et",
  'so.add': "Arkadaş ekle",
  'so.invited': "Davet edildi",
  'so.invite': "Davet et",
  'so.message': "Mesaj",
  'so.onlineOnly': "Arkadaşlar, mesajlar ve loncalar çevrimiçi oynarken çalışır.",
  'so.gInvite': "Loncaya",
  'so.gInvited': "Davet edildi",
  'so.gInviteSent': "Lonca daveti gönderildi",
  'so.gInvitesYou': "seni loncasına davet ediyor",
  'so.gMembers': "{n} üye",
  'so.gJoin': "Loncaya katıl",
  'so.more': "Daha fazla ({n})",
  'so.players': "Oyuncular",
  'so.friends': "Arkadaşlar",
  'so.messages': "Mesajlar",
  'so.search': "Oyuncuları isimle ara",
  'so.count': "{n} oyuncu · {on} çevrimiçi",
  'so.none': "Kimse bulunamadı.",
  'so.wants': "arkadaşın olmak istiyor",
  'so.requests': "Arkadaşlık istekleri",
  'so.noFriends': "Henüz arkadaş yok. Oyuncular sekmesinde bul.",
  'so.pending': "Gönderilen istekler",
  'so.cancel': "İptal",
  'so.decline': "Reddet",
  'so.sayHi': "Merhaba de 👋",
  'so.noMsgs': "Henüz mesaj yok.",
  'so.remove': "Arkadaşlıktan çıkar",
  'so.onlineNow': "Şimdi çevrimiçi",
  'so.nobody': "Şu an boşta çevrimiçi kimse yok.",
  'so.invitesYou': "seni bir baskına davet ediyor",
  'so.waitingN': "{n} bekliyor",
  'so.join': "Katıl",
  'so.later': "Sonra",
  'so.reqToast': "{n} arkadaşın olmak istiyor",
  'so.nowFriends': "Artık {n} ile arkadaşsınız",
  'so.invSent': "Davet gönderildi",
  'so.invitePlayers': "Oyuncu davet et",
  'so.inviteHint': "Onları bu odaya getiren Katıl düğmeli bir kart alırlar.",
  'gd.members': "{n} üye",
  'gd.leave': "Loncadan ayrıl",
  'gd.join': "Katıl",
  'gd.all': "Tüm loncalar",
  'gd.needRank': "Rütbe {n} veya üstü (sen: {have})",
  'gd.needBuy': "USDC/USDT ile en az bir satın alma",
  'gd.create': "Lonca kur",
  'gd.name': "Lonca adı",
  'gd.tag': "Etiket (2-5)",
  'gd.desc': "Kısa açıklama (isteğe bağlı)",
  'gd.found': "Loncayı kur",
  'gd.count': "{n} üye · {on} çevrimiçi",
  'gd.yours': "Loncan",
  'gd.list': "Loncalar",
  'gd.none': "Henüz lonca yok. İlk sen ol.",
  'gd.err.signin': "Önce giriş yap.",
  'gd.err.member': "Önce loncandan ayrıl.",
  'gd.err.purchase': "Lonca kurmak için USDC/USDT ile bir satın alma gerekir.",
  'gd.err.rank': "Lonca kurmak için rütbe 20 gerekir.",
  'gd.err.name': "Ad: 3-24 harf, rakam veya boşluk.",
  'gd.err.tag': "Etiket: 2-5 harf veya rakam.",
  'gd.err.taken': "Bu ad veya etiket alınmış.",
  'pf.title': "Oyuncu",
  'pf.rank': "Rütbe {n}",
  'pf.guild': "Lonca: {g}",
  'pf.raids': "Baskın",
  'pf.wins': "Galibiyet",
  'pf.kills': "Leş",
  'pf.extracts': "Tahliye",
  'pf.best': "En çok leş",
  'pf.time': "Oynama süresi",
  'pf.ach': "Başarım",
  'pf.multi': "En iyi seri",
  'pf.since': "Oynuyor",
  'tb.readyWait': "{n} bekliyor",
  'mc.waiting': "{n} bekliyor",
  'pause.open': "Menü (Esc)",
  'pause.title': "Menü",
  'pause.resume': "Devam et",
  'pause.settings': "Ayarlar",
  'pause.leave': "Maçtan çık",
  'pause.leaveLose': "Maçtan çık (bahis kaybolur)",
  'pause.leaveSure': "Çıkmak için tekrar dokun",
  'pause.keys': "Esc: maça dön",
  'pause.back': "← Geri",
  'pause.on': "açık",
  'pause.off': "kapalı",
  'pause.practice': "Antrenman duraklatıldı.",
  'pause.practiceDead': "Elendin. İstediğin zaman çıkabilirsin.",
  'pause.alive': "Menü açıkken maç devam eder. Şimdi çıkarsan koşucun haritada kalır ve bahis maçta kalır.",
  'pause.dead': "Elendin. İstediğin zaman çık: kazandığın bir şey varsa yine bakiyene gelir.",
  'gd.chat': "Sohbet",
  'gd.chatEmpty': "Henüz mesaj yok. Loncana merhaba de.",
  'gd.chatPh': "Loncana yaz…",
  'swap.min': "En küçük takas: {v}",
  'prep.waitingPeople': "Süre yok: arkadaşlarını çağır, en az {min} oyuncu hazır olunca baskın başlayabilir. Herkes gerçek oyuncu. {of} yerden {n} dolu.",
  'prep.people': "Sadece gerçek oyuncular: burada herkes bıçakla başlar.",
  'shop.firstTopup': "İlk yükleme ikiye katlanır: mağaza $ olarak aynısını tekrar al, en fazla {v} ekstra.",
  'tour.who': "yöneticin",
  'tour.voice': "Ses aç/kapa",
  'tour.skip': "Geç",
  'tour.next': "İleri",
  'tour.done': "Hadi",
  'set.tour': "Tanıtım",
  'set.tourNote': "Nyx oyunu sana yeniden gösterir.",
  'set.tourBtn': "Tanıtımı tekrarla",
  'nyx.hello': "Selaaam koşucu! Ben Nyx, bu gece rehberinim! Benimle kal, ilk baskınından... zengin çıkacaksın!",
  'nyx.name': "Önce ilk iş! Koşucun için bir isim yaz ve Tamam'a dokun. Herkes onu başının üstünde görecek!",
  'nyx.nameOk': "Ay, ne tatlı bir isim! Beğendim!",
  'nyx.practice': "Şimdi Antrenman'a dokun! Ücretsiz, sadece botlar. İlk oyunun için mükemmel!",
  'nyx.practiceOk': "Eveet! İyi seçim!",
  'nyx.modes': "Bunlar oyun modları! Bugün klasik olanı, Baskın'ı oynuyoruz. Yağmala, savaş ve çık! Baskın'a dokun!",
  'nyx.modeOk': "Baskın olsun! Hadi!",
  'nyx.bag': "Olay şu! Bahsin çantana girer. Birini indir, çantası senin! Sen düşersen... seninki onun. Iıh!",
  'nyx.shop': "Kıyafetler ve silah görünümleri çantalardan ve sandıklardan çıkar, tam burada, mağazada! Ve pışt... seni bekleyen ücretsiz bir tane var!",
  'nyx.social': "Arkadaşlar, mesajlar, loncalar! Ekibini getir. Birlikte her şey daha eğlenceli!",
  'nyx.wallet': "Gerçek bahis mi istiyorsun? Cüzdanla ya da sadece e-postayla giriş yap! Çekimler yalnızca kendi adresine gider. Güvende!",
  'nyx.play': "Hazır mısın? Oyna'ya bas!",
  'nyx.ready': "Burası bekleme odası! Hazır'a bas, ve iniyoruz! Vuhu!",
  'nyx.start': "İçerideyiz! W, A, S, D ile hareket et. Fareyle nişan al, ateş etmek için tıkla! Atılma için Boşluk!",
  'nyx.startTouch': "İçerideyiz! Sol başparmağın seni hareket ettirir. Sağdaki Ateş'e basılı tut, senin için nişan alır!",
  'nyx.loot': "O turuncu parıltıyı görüyor musun? O para! Üstünden koşarak geç!",
  'nyx.pickup': "Yaşasın! Çantan ağırlaştı!",
  'nyx.kill': "İlk kan! Güzel atış! Düşürdüklerini al. Oo, bir de daha iyi bir silah!",
  'nyx.hurt': "Ah, yaralandın! Çatışmada can geri gelmez, dikkatli ol!",
  'nyx.storm': "Fırtına geliyor! Çemberin içinde kal, çabuk!",
  'nyx.exit': "Oo, o çanta sana yakıştı! Yeşil bir çıkış halkası bul ve içinde dur!",
  'nyx.extracting': "Kıpırdama! Üç saniye! Vurulma!",
  'nyx.won': "Çıktın! Yapabileceğini biliyordum! Sonraki baskında görüşürüz, koşucu!",
  'nyx.dead': "Ah, olur böyle! Antrenman ücretsiz, hadi tekrar!",
  'tour.yourMove': "Sıra sende",
  'tour.skipStep': "Bu adımı geç",
  'tour.again': "Tekrar duymak için Nyx'e dokun",
  'tour.replayHint': "Tanıtımı tekrar ister misin? Ayarlar → Tanıtım.",
  'mode.zombies': "Zombiler",
  'mode.zombies.d': "Ortak oyun, tek başına ya da 3 arkadaşla: her yönden 20 ölü dalgası, her biri daha zor, 10 ve 20'de boss. Süre yok. Öldürmeler taret, lazer mayın ve ilk yardım için kredi verir.",
  'mode.gold': "Altın Hücumu",
  'mode.gold.d': "Taş ocağının her yerine altın torbaları düşer. Rastgele silahlar, hızlı yeniden doğma. En çok torbayı toplayan tüm potu mağaza kredisi olarak alır.",
  'kind.zombie': "ortak · XP",
  'kind.gold': "tek kazanan · mağaza kredisi",
  'tb.zFee': "giriş · XP, unvanlar",
  'tb.goldFee': "giriş · kazanan hepsini alır",
  'prep.zFee': "giriş {v}",
  'prep.zSquad': "Ekip",
  'prep.goldPot': "Ödül (mağaza kredisi)",
  'zp.title': "Bu maç için silahın",
  'zp.power': "Saniye başına hasar",
  'zp.melee': "şarjör yok",
  'hud.waveK': "Dalga",
  'hud.goldK': "Altın torbaları",
  'hud.startZ': "Mezarlığı tut. Her yönden geliyorlar",
  'hud.startGold': "Altını kap. En çok torba hepsini alır",
  'hud.wave': "Dalga {n} / {of}",
  'hud.bossWave': "SON DALGA · BOSS GELDİ",
  'hud.waveClear': "{n}. dalga temizlendi",
  'hud.patched': "+35 HP",
  'hud.summon': "Boss sürüyü çağırıyor",
  'hud.bossDown': "BOSS DÜŞTÜ · KOŞU TAMAM",
  'hud.bagsShort': "altın",
  'hud.waveN': "{n} / {of}",
  'hud.nextWave': "sonraki dalga {s} sn",
  'hud.zLeft': "{n} kaldı · {k} düştü",
  'hud.goldPlace': "{p}. sıra · {d} ölüm · ödül {s}",
  'hud.bossHp': "BOSS %{p}",
  'hud.zBreak': "Doldur ve toparlan: {s} sn",
  'hud.zGoal': "20 dalga hayatta kal · 10 ve 20'de boss",
  'hud.goldGoal': "Düdükte en çok torbası olan kazanır",
  'hud.zDown': "Düştün. Ekibin dayanırsa sonraki dalgada kalkarsın",
  'feed.zYou': "Ölüler seni yakaladı",
  'feed.zDown': "{name} parçalandı",
  'coach.z': "Meydanda kalın, sırt sırta. Öldürmeler kredi verir: taret (2), lazer mayın (3), ilk yardım (1) al",
  'coach.gold': "Torbaları almak için üstlerinden geç. Ölürsen yarısı düşer; topla ve hayatta kal",
  'warn.z60': "Bir dakika kaldı",
  'warn.z10': "10 saniye: boss'u öldür!",
  'warn.gold30': "30 saniye: ne kapabilirsen",
  'warn.gold10': "10 saniye kaldı",
  'res.zCleared': "Koşu tamamlandı",
  'res.zFell': "{n}. dalgada ezildiniz",
  'res.zWaves': "{n} / {of} dalga",
  'res.zWonText': "On dalga ve boss'ları, {s} kişilik ekiple. {k} ölü düşürdün.",
  'res.zText': "{k} ölü düşürdün ({s} kişilik ekip). Ne kadar ilerlersen o kadar XP.",
  'res.zTime': "süre {t}",
  'res.goldWon': "Altın hücumu kazanıldı",
  'res.goldLost': "Altın hücumunda {p}. sıra",
  'res.goldWonText': "{b} torba altın, herkesten fazla. {c} mağaza bakiyende.",
  'res.goldText': "{b} torba topladın; kazananın {top} vardı. Sadece birinci kazanır.",
  'xp.Waves survived': "Atlatılan dalgalar",
  'xp.Zombies': "Zombiler",
  'xp.Boss slain': "Boss öldürüldü",
  'xp.Run cleared': "Koşu tamamlandı",
  'xp.Gold bags': "Altın torbaları",
  'ach.graveyard_shift': "Mezarlık Vardiyası",
  'ach.hold_the_line': "Hattı Tut",
  'ach.undertaker': "Mezarcı",
  'ach.exterminator': "İmha Uzmanı",
  'ach.giant_slayer': "Dev Avcısı",
  'ach.zombie_slayer': "Zombi Avcısı",
  'ach.top_of_the_horde': "Ordunun Zirvesi",
  'ach.nightmare_walker': "Kâbus Yolcusu",
  'ach.army_of_one': "Tek Kişilik Ordu",
  'ach.prospector': "Maden Arayıcı",
  'ach.gold_fever': "Altın Ateşi",
  'ach.mother_lode': "Ana Damar",
  'ach.bag_hoarder': "Torba İstifçisi",
  'ach.midas': "Midas",
  'achd.zRuns': "Bir zombi koşusu oyna",
  'achd.bestWave': "Ölülerin {n}. dalgasını temizle",
  'achd.zKills': "{n} zombi öldür",
  'achd.zBoss': "Boss'a son darbeyi vur",
  'achd.zClears': "Zombi koşusunu {n} kez bitir",
  'achd.zMvp': "Ekibinde en çok öldürmeyle bir koşu bitir",
  'achd.zSolo': "Zombi koşusunu tek başına bitir",
  'achd.goldRuns': "Bir altın hücumu oyna",
  'achd.goldWins': "{n} altın hücumu kazan",
  'achd.bestGold': "Bir hücumu {n} torbayla bitir",
  'achd.goldBags': "Toplam {n} altın torbası topla",
  'tour.nameDone': "Tamam",
  'tour.finish': "Hadi oynayalım!",
  'nyx.stake': "Bu senin bahsin: çantana koyduğun şey. Antrenmanda oyun parası, kaybedecek bir şey yok. Bir dolarına oynuyoruz!",
  'nyx.retry': "Ah, düştün! Olur böyle, antrenman ücretsiz! Tekrar oyna'ya dokun. Bu sefer biraz ganimet topla, sonra yeşil bir çıkışa koş!",
  'nyx.resultWon': "Çıktın! Kazandın! Yapabileceğini biliyordum! Antrenman parası sadece eğlence için. Masalar'a dokun, sana mağazayı göstereyim!",
  'nyx.shopGo': "Şimdi Mağaza'ya dokun!",
  'nyx.shopCase': "Mağazaya hoş geldin! Antrenmanda bu sadece bir demo, hiçbir şey ödenmez. Bu çantada Demo'ya dokun ve açılışını izle!",
  'nyx.shopEquip': "Bak ne çıktı! Çevrim içi, mağaza $'ınla bu senin olurdu. Kapat'a dokun!",
  'nyx.bye': "Hepsi bu! Oynamayı, kazanmayı ve alışverişi biliyorsun. Hadi koşucu! Beni istediğin zaman Ayarlar'dan çağırabilirsin.",
  'hud.headshot': "KAFADAN",
  'inv.open': "Aç",
  'bp.later': "Sonra",
  'ach.sharpshooter': "Keskin Nişancı",
  'ach.headhunter': "Kafa Avcısı",
  'achd.headshots': "{n} kafadan vuruş yap",
  'hud.demoted': "Öldün: {w} silahına düştün",
  'hud.crit': "KRİTİK",
  'hud.roundStart': "Raunt {n} / {of}",
  'hud.roundWon': "{n}. raunt senin!",
  'hud.roundLost': "{n}. raunt kaybedildi",
  'hud.roundDraw': "{n}. raunt: berabere",
  'hud.roundTo': "{n}. raunt {name} oyuncusunun",
  'hud.roundNext': "Sonraki raunt {s} sn",
  'hud.roundScore': "Raunt {n}/{of} · {a} : {b}",
  'hud.roundDown': "Düştün. Sonraki rauntta dönersin",
  'mc.rounds': "{n} rauntta {w}",
  'hud.midBossWave': "DALGA 10 · ÇİTİN ÜSTÜNDEN BİR BOSS GELİYOR",
  'hud.midBossDown': "Boss düştü! On dalga daha",
  'ach.last_stand': "Son Direniş",
  'gl.upTurret': "Taret yükseltildi: seviye {lv}",
  'gl.upMine': "Lazer mayın yükseltildi: {lv} ışın",
  'gl.upHint': "Boşluk: {what} → seviye {lv} · {c} CR",
  'gl.upHintTouch': "⬆ {what} → seviye {lv} · {c} CR",
  'gl.no.max': "Zaten en üst seviyede",
  'gl.no.near': "Taretinin ya da mayının yanına git",
  'nav.invite': "Davet et",
  'ref.title': "Arkadaşlarını davet et",
  'ref.lead': "Arkadaşlarını bağlantınla getir. {d} gün boyunca oynadıkları her bahisten kasa payının %{p}'si mağaza $'ı olarak senin.",
  'ref.yourCode': "Kodun",
  'ref.link': "Davet bağlantın",
  'ref.copy': "Kopyala",
  'ref.share': "Paylaş",
  'ref.copied': "Bağlantı kopyalandı",
  'ref.shareText': "DARK BAGS'te benimle baskına gel. Kodum: {c}",
  'ref.invited': "Davet edilen",
  'ref.active': "Maç oynayan",
  'ref.earned': "Kazancın",
  'ref.how': "Nasıl çalışır",
  'ref.step1': "Arkadaşın ilk maçından önce bağlantını açar (ya da kodunu yazar)",
  'ref.step2': "İlk bahisli maçından sonra hoş geldin çantası alır",
  'ref.step3': "Oynadığı her bahis {d} gün boyunca sana kasa payının %{p}'sini mağaza $'ı olarak getirir",
  'ref.step4': "{m} maç bitirdiğinde sen bir bonus çanta alırsın",
  'ref.fair': "Adil oyun: seninle aynı ağdaki ya da cihazdaki hesaplar sayılmaz, günlük bir sınır var ve hile tüm ödülleri iptal eder.",
  'ref.by': "{c} koduyla geldin",
  'ref.have': "Arkadaşından kod mu aldın?",
  'ref.apply': "Uygula",
  'ref.online': "Davetler çevrim içi oyunda çalışır. Ayarlar'dan çevrim içine geç.",
  'ref.signin': "Davet bağlantını almak için giriş yap.",
  'ref.claimedToast': "Kod uygulandı: hoş geldin çantan ilk maçından sonra gelir",
  'ref.err.already': "Zaten bir davet edenin var",
  'ref.err.unknown': "Böyle bir kod yok",
  'ref.err.self': "Kendini davet edemezsin",
  'ref.err.late': "Kodlar yalnızca ilk maçından önce geçerli",
  'ref.err.linked': "Bu kod senin ağından ya da cihazından",
  'ref.err.busy': "Bu oyuncu bugünkü sınıra ulaştı. Yarın dene",
  'err.guard_seat': "Ağından ya da cihazından başka bir hesap zaten bu masada",
  'err.guard_new': "Bugün ağından çok fazla yeni hesap açıldı. Yarın gel",
  'err.guard_faucet': "Ağın bugünkü test jetonlarını aldı",
  'res.practiceNoXp': "Antrenman ücretsiz: XP ya da ödül yok. Rütbe atlamak için çevrim içi oyna.",
  'online.only': "Yalnızca çevrim içi. Antrenman ücretsiz olduğu için savaş biletine ve derecelendirmeye sayılmaz. Oyna sayfasında Çevrim içi'ne geç.",
  'err.online_only': "Bu yalnızca çevrim içi çalışır",
  'tour.skip': "Eğitimi atla",
  'tour.skipped': "Eğitim atlandı. Nyx'i Ayarlar'dan tekrar çağırabilirsin.",
  'shop.demo': "Demo",
  'shop.demoNote': "Bir demo: hiçbir şey ödenmedi ya da verilmedi. Çevrim içi, çantaları mağaza $'ıyla açarsın ve çıkan senin olur.",
  'acct.signin': "Giriş",
  'acct.copy': "Adresi kopyala",
  'acct.explorer': "Gezgin",
  'acct.inWallet': "Cüzdanda",
  'acct.inGame': "Oyunda",
  'acct.deposit': "Yatır",
  'acct.withdraw': "Çek",
  'acct.cartridge': "Cartridge cüzdanını aç",
  'acct.signout': "Çıkış",
  'acct.copied': "Adres kopyalandı",
  'br.tab': "Köprü",
  'br.in': "Starknet'e",
  'br.out': "Starknet'ten",
  'br.fromNet': "Kaynak ağ",
  'br.toNet': "Hedef ağ",
  'br.youSend': "Gönderdiğin",
  'br.youGet': "Alacağın",
  'br.amount': "Miktar",
  'br.refund': "{c} adresin (iade için)",
  'br.refundPh': "Takas başarısız olursa iadenin gideceği yer",
  'br.recipient': "Alacak {c} adresi",
  'br.recipientPh': "O ağdaki alıcı adres",
  'br.landsIn': "Starknet cüzdanına {a} gelir; sonra Yatır ile oyuna aktarılır.",
  'br.fromWallet': "Starknet cüzdanından {a} gönderilir.",
  'br.fee': "%{p} komisyonumuz dahil.",
  'br.getAddr': "Yatırma adresi al",
  'br.send': "Cüzdanımdan gönder",
  'br.estimate': "Yaklaşık {a} ({u}) alırsın, ~{s} sn",
  'br.needAmount': "Bir miktar yaz.",
  'br.needRefund': "İade için gönderdiğin ağdaki adresini yaz.",
  'br.needRecipient': "Alıcı adresi yaz.",
  'br.sent': "Gönderildi. Gerisini köprü halleder.",
  'br.sendExactly': "{c} ağında bu adrese tam {a} gönder:",
  'br.memo': "Memo (zorunlu)",
  'br.copyMemo': "Memo'yu kopyala",
  'br.outSent': "{a} köprüye {c} için gönderildi.",
  'br.youGetAbout': "{c} üzerinde yaklaşık {a} alırsın.",
  'br.deadline': "{t} tarihine kadar tamamlanmazsa iade.",
  'br.toGame': "Oyuna yatır",
  'br.new': "Yeni köprü",
  'br.others': "Diğer köprüler",
  'br.othersNote': "Köprünün kendi sitesini açar; orada komisyon almayız. Cüzdan panelindeki Starknet adresine gönder.",
  'br.lsSub': "40+ ağ ve borsa",
  'br.avnuSub': "Starknet'te token takası",
  'br.mainnetOnly': "Köprüler Starknet ana ağında gerçek coinlerle çalışır. Test ağında aşağıdakileri kullan.",
  'br.s.wait': "Yatırımın bekleniyor",
  'br.s.seen': "Yatırım görüldü, onaylanıyor",
  'br.s.partial': "Yatırım az; kalanı gönder ya da iadeyi bekle",
  'br.s.proc': "Aktarılıyor…",
  'br.s.ok': "Tamam: cüzdanında",
  'br.s.refund': "İade edildi",
  'br.s.fail': "Başarısız; hiçbir şey alınmadı",
  'nav.mail': "Posta",
  'mail.claim': "Al",
  'mail.claimed': "Alındı: {g}",
  'mail.creditNote': "Mağaza $'ı: mağazada harca. Çekilemez ve satılamaz.",
  'mail.empty': "Henüz posta yok.",
  'mail.g.credit': "{v} mağaza $'ı",
  'mail.g.spin': "{n} çark çevirme",
  'mail.g.trial': "{n}, 1 saat",
  'mail.newToast': "Yeni posta!",
  'mail.noSpins': "Çevirme hakkın kalmadı",
  'mail.pick': "Okumak için bir mektup seç.",
  'mail.signin': "Posta almak için giriş yap.",
  'mail.spinBtn': "Çarkı çevir ({n})",
  'mail.spinNow': "Çevir!",
  'mail.taken': "Alındı",
  'mail.welcomeToast': "Hoş geldin bonusu! Kurucu unvanı sende, Posta'da bir çark çevirme seni bekliyor.",
  'mail.wheel': "Şans çarkı",
  'mail.wheelNote': "1 saatlik koşucu kostümü, 1 saatlik silah kaplaması ya da 2$'a kadar mağaza $'ı.",
  'mail.trial72': "1 saat senin. Envanterden giy.",
  'mail.welcome.t': "♛ Hoş geldin, Kurucu!",
  'mail.welcome.b': "DARK BAGS'i gerçek bir yüklemeyle ilk destekleyenlerdensin ve bunu unutmayacağız. Teşekkürler!\n\nBugünden itibaren canlı altın renginde premium Kurucu unvanını taşıyorsun: onu yalnızca oyuna en baştan inananlar taşıyacak.\n\nHediyen aşağıda: bir şans çarkı çevirmesi. Bol şans, karanlıkta görüşürüz.\n\nDARK BAGS ekibi",
  'ach.founder': "Kurucu",
  'achd.deposits': "İlk yüklemeni yap",
  'r.premium': "Premium",
  'mail.jackpot.t': "🎰 Şans çarkı jackpot!",
  'mail.jackpot.b': "Şans kasası senindi: coinler yolda (ya da oyun bakiyende). Tebrikler!",
  'fw.bank': "Şans kasası",
  'fw.coin': "Öde",
  'fw.inBalance': "Oyun bakiyene eklendi: istediğin zaman çek.",
  'fw.jackpot': "JACKPOT",
  'fw.kicker': "Çevirme başı 0,05 $",
  'fw.lead': "18 çeşit ödül: 1 saatlik skinler, kalıcı skinler, stil, hediye kasalar, mağaza $, pass XP, XP takviyeleri, ekstra çevirmeler. Her ücretli çevirme kasayı doldurur: işarete ulaşan çevirme hepsini gerçek coinle kazanır.",
  'fw.next': "{m} olunca öder",
  'fw.noCoins': "Çevirmek için herhangi bir coin yatır.",
  'fw.odds': "Neler çıkabilir",
  'fw.real': "Gerçek kostüm ({r})",
  'fw.realKeep': "Kalıcı olarak senin.",
  'fw.rules': "Her çevirmenin %30'u kasaya gider. Kasa işarete ulaşınca (0,50 $, sonra 1 $, 1,50 $, 2 $… 5 $'a kadar), ona ulaşan çevirme tüm kasayı USDC (ya da USDT veya STRK) olarak kazanır. Deneme kostümleri 1 saat sürer. Mağaza öğeleri çekilemez ve satılamaz.",
  'fw.sentChain': "Starknet cüzdanına gönderildi.",
  'fw.share': "Kazancı paylaş",
  'fw.spin': "Çevir",
  'fw.title': "Şans çarkı",
  'fw.trial': "1 saatlik koşucu kostümü",
  'fw.wtrial': "1 saatlik silah kaplaması",
  'coin.import': "Coin içe aktar",
  'coin.search': "Ara: sembol, ad ya da adres",
  'coin.added': "eklendi",
  'coin.add': "Ekle",
  'coin.none': "Hiçbir şey bulunamadı",
  'coin.note': "AVNU'nun doğrulanmış listesindeki ya da Ekubo listesindeki her Starknet coini. Ekledikten sonra yatır ve diğerleri gibi bahis yap; kazanç aynı coinle döner.",
  'coin.done': "{s} eklendi: yatır ve bahis için seç.",
  'coin.noPrice': "{s} eklendi; fiyatı bir dakika içinde görünür.",
};
