export default {
  'lobby.tagline': 'Bahis koy. Yağmala. Fırtınadan önce çık. <b>Çantanda ne olduğunu kimse görmez.</b>',
  'lobby.namePh': 'Koşucunun adı',
  'lobby.locker': 'Dolap · skinler · çantalar',
  'lobby.refill': 'Test coinlerini doldur',
  'lobby.online': 'Çevrimiçi',
  'lobby.practice': 'Botlara karşı antrenman',
  'lobby.stakePer': 'Baskın başına bahis',
  'lobby.stakeWith': 'Bahis coin’i <span class="fine">herhangi bir coin · $ olarak gösterilir · kazanç aynı coin ile döner</span>',
  'lobby.play': 'Oyna · {s} bahis',
  'lobby.signIn': 'Oynamak için giriş yap',
  'lobby.how': 'Nasıl oynanır',
  'lobby.gore': '<b>18+ modu.</b> Uzuvlar kopar, kan yerde kalır.',
  'lobby.fine': 'Antrenman tarayıcında çalışır. Buradaki tüm para oyun parasıdır.',
  'how.1': '<b>Bahis koy ve hazır ol.</b> Herkes bir bıçak ve 100 canla birlikte girer. Bahsinin yarısı çantanda, yarısı ganimet olarak saçılır.',
  'how.2': '<b>Turuncu ganimeti topla.</b> Çantana gider. Öldürmeler silahını yükseltir: bıçak → tabanca → pompalı → SMG → tüfek → lazer keskin nişancı.',
  'how.3': '<b>Canlı çık.</b> Fırtına kapatmadan önce yeşil bir çıkışta 3 saniye dur. Bütün çanta senin. Ölürsen başkasına düşer.',
  'how.keys': '<kbd>WASD</kbd> hareket · <kbd>fare</kbd> nişan · <kbd>tık</kbd> saldırı · <kbd>Boşluk</kbd> atılma · <kbd>Q</kbd> çanta boyutunu blöfle · <kbd>M</kbd> ses · <kbd>N</kbd> müzik',
  'how.fine': 'Her baskın ve her başarım rütbe XP’si verir. Her rütbe atlayışı sana 3 günlüğüne yeni bir skin verir.',
  'net.practice': 'Sadece sen ve botlar, çevrimdışı.',
  'net.open': 'Bağlandı. İnsanlar ve botlar aynı baskında.',
  'net.connecting': 'Sunucuya bağlanılıyor…',
  'net.down': 'Sunucuya ulaşılamıyor. Yeniden deneniyor… Antrenman çevrimdışı çalışır.',
  'net.lost': 'Bağlantı koptu. Masalara dönülüyor.',
  'q.pick': 'Bahis için bir coin seç.',
  'q.short': '{s} bahis için yeterli {c} yok. Başka bir coin ya da daha küçük bahis seç.',
  'q.shortDeposit': '{s} bahis için yeterli {c} yok. Başka bir coin, daha küçük bahis seç ya da yatır.',
  'q.stable': '{c} ile {s} bahis koyuyorsun. Canlı çık, taşıdığın her şey senin.',
  'q.coin': 'Bugünkü fiyattan {a} = {s} bahis koyuyorsun. Kazanç aynı kurla {c} olarak döner.',
  'tb.live': 'Baskın sürüyor · {t}',
  'tb.ready': '{n} hazır · {s}sn',
  'tb.waiting': '{n} bekliyor',
  'tb.golden': 'Sıradaki: altın baskın',
  'tb.jackpot': 'Jackpot {v}',
  'pcfg.title': 'Antrenman ayarları',
  'pcfg.difficulty': 'Botlar',
  'pcfg.easy': 'Kolay',
  'pcfg.normal': 'Normal',
  'pcfg.hard': 'Zor',
  'pcfg.runners': 'Baskındaki koşucular',
  'pcfg.time': 'Baskın süresi',
  'rk.max': 'en yüksek rütbe',
  'rk.toNext': 'Rütbe {r} için {x} XP',
  'rk.of': 'Rütbe {r} / 90',
  'rk.rank': 'Rütbe',
  'rk.up': 'Rütbe atladın',
  'rk.xp': 'rütbe XP’si',
  'xp.Raid': 'Baskın',
  'xp.kills': '{n} öldürme',
  'xp.Damage': 'Hasar',
  'xp.Time alive': 'Hayatta kalma',
  'xp.First blood': 'İlk kan',
  'xp.Double kill': 'Çifte öldürme',
  'xp.Triple kill': 'Üçlü öldürme',
  'xp.Rampage': 'Katliam',
  'xp.Godlike': 'Tanrısal',
  'xp.Full arsenal': 'Tam cephanelik',
  'xp.Extracted': 'Tahliye',
  'xp.Profit': 'Kâr',
  'xp.Practice ×0.5': 'Antrenman ×0.5',
  'rw.title': 'Rütbe ödülü',
  'rw.trial': '72 saat boyunca senin',
  'rw.try': 'Dene',
  'rw.share': 'Rütbeyi paylaş',
  'prep.raid': 'Baskın {n} · {s} bahis',
  'prep.readyUp': 'Hazır mısın?',
  'prep.first': 'İlk koşucu hazır olunca geri sayım başlar.',
  'prep.live': 'Bir baskın sürüyor. Şimdi hazır ol, sonrakine herkesle birlikte gir.',
  'prep.over': 'Baskın bitti. Hazırlık odası birazdan açılır.',
  'prep.many': 'Burada herkes bıçakla başlar. Botlar son saniyelerde katılır.',
  'prep.bots': 'Botlar boş yerleri son saniyelerde doldurur.',
  'prep.open': 'boş',
  'prep.pot': 'Pot',
  'prep.cancel': 'İptal · {v} iade',
  'prep.ready': 'Hazır · {v} bahis',
  'prep.back': 'Masalara dön',
  'hud.bagPrivate': 'Çantan · gizli',
  'hud.golden': 'Altın baskın',
  'hud.goldenStart': 'Altın baskın · içeride jackpot ganimeti',
  'hud.start': 'Bıçak elde · turuncuyu topla · çıkış bul',
  'hud.bagOpened': 'Çanta açıldı · +{v}',
  'hud.arsenal': 'Cephanelik tamam · yine bıçak ★',
  'hud.unlocked': '{w} açıldı',
  'hud.pnl': '{s} bahse karşı {d}',
  'hud.alive': 'İçeride {n}',
  'hud.next': 'Sıradaki: {w}',
  'hud.final': 'Son çember · son çıkış',
  'hud.closing': 'Fırtına daralıyor · {t}',
  'hud.stormIn': 'Fırtına {t} sonra ilerliyor',
  'hud.dash': 'Atıl',
  'hud.bagLook': 'Çanta görünümü',
  'hud.extracting': 'Tahliye',
  'hud.holdStill': 'Kıpırdama. Bir isabet sıfırlar.',
  'hud.sound': 'Ses',
  'hud.music': 'Müzik',
  'bluff.0': 'küçük',
  'bluff.1': 'orta',
  'bluff.2': 'şişkin',
  'touch.move': 'hareket',
  'touch.aim': 'nişan · ateş',
  'touch.bag': 'Çanta',
  'w.Knife': 'Bıçak',
  'w.Pistol': 'Tabanca',
  'w.Shotgun': 'Pompalı',
  'w.SMG': 'SMG',
  'w.Rifle': 'Tüfek',
  'w.Laser sniper': 'Lazer keskin nişancı',
  'streak.1': 'İlk kan',
  'streak.2': 'Çifte öldürme',
  'streak.3': 'Üçlü öldürme',
  'streak.4': 'Katliam',
  'streak.5': 'Tanrısal',
  'streak.you1': 'İlk kanı sen döktün',
  'feed.storm': 'Fırtına seni aldı',
  'feed.droppedYou': '{name} seni indirdi',
  'coach.storm': 'Fırtınadasın · çemberin içine dön',
  'coach.touch': 'Sol başparmak hareket · sağ başparmak nişan ve saldırı',
  'coach.keys': 'WASD hareket · fare nişan · tık saldırı',
  'coach.exit': 'Çıkma zamanı · yeşil bir ÇIKIŞTA 3 saniye dur · kenardaki oklar yolu gösterir',
  'coach.loot': 'Turuncu ganimeti topla · çantana gider',
  'coach.kills': 'Öldürmeler silahını yükseltir · Boşluk ile atıl',
  'coach.killsTouch': 'Öldürmeler silahını yükseltir · kaçmak için Atıl’a dokun',
  'spect.watching': '{name} izleniyor · ◀ ▶ değiştir',
  'spect.down': 'Düştün',
  'spect.results': 'Sonuçlar',
  'res.extracted': 'Tahliye edildi',
  'res.storm': 'Fırtına yuttu',
  'res.dropped': 'İndirildin',
  'res.sealed': 'İçeride kaldın',
  'res.inside': '{k} öldürme · içeride {t}',
  'res.out': '{s} bahisle {p} ile çıktın: {d}.',
  'res.paid': 'Giriş kurundan {v} ödendi.',
  'res.killer': 'Çantan artık {n} kişisinde. İçinde {v} vardı ve bunu sadece ikiniz bileceksiniz.',
  'res.inStorm': 'Çantan, {v}, cesaret edene fırtınada duruyor.',
  'res.sealedText': 'Baskın sen içerideyken kapandı. {v} sonraki baskının ganimetine geçti.',
  'res.again': 'Tekrar oyna',
  'res.tables': 'Masalar',
  'res.share': 'Paylaş',
  'share.title': 'Paylaş',
  'share.x': '𝕏’te paylaş',
  'share.copy': 'Görseli kopyala',
  'share.save': 'PNG kaydet',
  'share.close': 'Kapat',
  'lk.title': 'Dolap',
  'lk.outfits': 'Kıyafetler',
  'lk.shop': 'Mağaza',
  'lk.bags': 'Şans çantaları',
  'lk.all': 'Tümü',
  'lk.owned': 'Benimkiler',
  'lk.him': 'Erkek',
  'lk.her': 'Kadın',
  'lk.shopUsd': 'Mağaza $',
  'lk.shopNote': 'Mağaza $’ını USDC veya USDT ile doldur (büyük paketler bonuslu). Mağaza $ sadece burada harcanır, çekilemez. Yetmiyor mu? Fark USDC/USDT’nden alınır.',
  'lk.bagsNote': 'Kesin oranlar, sunucuda çekilir. Bir nadirliği tamamlayana kadar kopya yok; kopya fiyatının %10’unu mağaza $ olarak geri verir. Garanti: 15 açılışta Destansı+, 60’ta Efsanevi+.',
  'lk.topupFrom': 'Doldurmak için + {v} USDC/USDT',
  'lk.collected': '{a} / {b} toplandı',
  'lk.equipped': 'Giyili',
  'lk.equip': 'Giy',
  'lk.buy': 'Satın al',
  'lk.trialLeft': 'Deneme · {t} kaldı',
  'lk.trialHow': 'Rütbe denemesi: {t} daha senin. Saklamak için satın al.',
  'lk.free': 'Herkese ücretsiz.',
  'lk.inCollection': 'Koleksiyonunda.',
  'lk.buyOrBag': 'Buradan al ya da bir çantayla şansını dene.',
  'lk.tryingOn': 'Deniyorsun.',
  'lk.bonus': '+%{n} bonus',
  'lk.pay': '{v} öde',
  'lk.jackpot': 'Jackpot',
  'lk.epicIn': 'Destansı+ için',
  'lk.legIn': 'Efsanevi+ için',
  'lk.openFree': 'Aç · ücretsiz',
  'lk.buyOpen': 'Al ve aç',
  'lk.pityDrop': 'garanti',
  'lk.dup': 'Zaten senin · {v} iade',
  'lk.new': 'Koleksiyonunda <b>yeni</b>',
  'lk.jackpotIs': 'jackpot {r}',
  'lk.showOff': 'X’te gösteriş yap',
  'lk.postMiss': 'Iskalamayı X’te paylaş',
  'lk.another': 'Bir tane daha aç',
  'lk.free1': 'ücretsiz',
  'lk.back': 'Dolaba dön',
  'lk.yours': '{n} artık senin.',
  'r.common': 'Sıradan',
  'r.rare': 'Nadir',
  'r.epic': 'Destansı',
  'r.legendary': 'Efsanevi',
  'r.mythic': 'Mitik',
  'r.exotic': 'Egzotik',
  'ach.title': 'Başarımlar',
  'ach.button': 'Başarımlar',
  'ach.intro': 'Her biri bir kez rütbe XP’si verir ve adını takabileceğin bir unvan olarak açar.',
  'ach.wear': 'Unvanı tak',
  'ach.worn': 'Takılı',
  'ach.wearing': 'Unvan:',
  'ach.takeOff': 'çıkar',
  'ach.noTitle': 'Unvan yok',
  'ach.unlocked': 'Başarım açıldı',
  'ach.seeAll': 'Tüm başarımlar',
  'achd.raids': '{n} baskın oyna',
  'achd.extracts': '{n} kez tahliye ol',
  'achd.kills': '{n} öldürme yap',
  'achd.bestKills': 'Tek baskında {n} öldürme',
  'achd.bestMulti': '×{n} çoklu öldürme',
  'achd.prestige': 'Cephaneliği {n} kez bitir',
  'achd.firstBloods': '{n} kez ilk kanı dök',
  'achd.secs': 'Baskınlarda {n} saat geçir',
  'achd.bestReturn': 'Bahsinin {n} katıyla çık',
  'achd.golden': 'Altın baskından tahliye ol',
  'achd.lastExit': 'Son çıkıştan çık',
  'achd.pacifist': 'Hiç öldürmeden tahliye ol',
  'achd.rank': '{n}. rütbeye ulaş',
  'achd.outfits': '{n} kıyafete sahip ol',
  'ach.rookie': 'Acemi',
  'ach.regular': 'Müdavim',
  'ach.veteran': 'Kıdemli',
  'ach.lifer': 'Emektar',
  'ach.eternal': 'Ebedi',
  'ach.escape_artist': 'Kaçış ustası',
  'ach.ghost': 'Hayalet',
  'ach.smuggler': 'Kaçakçı',
  'ach.phantom': 'Fantom',
  'ach.first_kill': 'İlk öldürme',
  'ach.hunter': 'Avcı',
  'ach.butcher': 'Kasap',
  'ach.reaper': 'Azrail',
  'ach.apex': 'Zirve',
  'ach.rampage': 'Katliam',
  'ach.one_man_army': 'Tek kişilik ordu',
  'ach.double_tap': 'Çift atış',
  'ach.triple_threat': 'Üçlü tehdit',
  'ach.godlike': 'Tanrısal',
  'ach.full_arsenal': 'Tam cephanelik',
  'ach.arsenal_master': 'Cephanelik ustası',
  'ach.first_blood': 'İlk kan',
  'ach.opener': 'Açılışçı',
  'ach.night_shift': 'Gece vardiyası',
  'ach.insomniac': 'Uykusuz',
  'ach.double_up': 'İkiye katla',
  'ach.big_bag': 'Dolu çanta',
  'ach.gold_rush': 'Altına hücum',
  'ach.last_one_out': 'Son çıkan',
  'ach.pacifist': 'Barışçıl',
  'ach.seasoned': 'Pişmiş',
  'ach.officer': 'Subay',
  'ach.commander': 'Komutan',
  'ach.legend': 'Efsane',
  'ach.collector': 'Koleksiyoncu',
  'ach.curator': 'Küratör',
  'ach.hoarder': 'İstifçi',
  'intro.tag': "Bahis koy. Yağmala. Çık.",
  'intro.go': "Gir",
  'intro.fonts': "Bıçaklar biliniyor…",
  'intro.world': "Karanlık çiziliyor…",
  'intro.connect': "Baskın aranıyor…",
  'intro.profile': "Çantan hazırlanıyor…",
  'intro.ready': "Hazır",
  'tb.wallet': "Cüzdan",
  'tb.shop': "Mağaza $",
  'nav.play': "Oyna",
  'nav.shop': "Mağaza",
  'nav.inventory': "Envanter",
  'nav.swap': "Takas",
  'nav.chat': "Sohbet",
  'nav.achievements': "Başarımlar",
  'nav.settings': "Ayarlar",
  'modes.title': "Oyun modu",
  'kind.raid': "tahliye",
  'kind.br': "kazanan potu alır",
  'kind.team': "takım potu",
  'mode.raid': "Baskın",
  'mode.raid.d': "Yağmala, savaş, bir çıkıştan çık. Taşıdığın senin.",
  'mode.br': "Battle Royale",
  'mode.br.d': "20 koşucuya kadar. Ayakta kalan son kişi tüm potu alır.",
  'mode.duel': "Düello",
  'mode.duel.d': "Bire bir. Kazanan iki bahsi de alır.",
  'mode.knives': "Sadece bıçak",
  'mode.knives.d': "Tüm baskın boyunca sadece bıçak. Ayakta kalan son kişi kazanır.",
  'mode.pistols': "Sadece tabanca",
  'mode.pistols.d': "Sadece tabancalar. Ayakta kalan son kişi kazanır.",
  'mode.shotguns': "Sadece pompalı",
  'mode.shotguns.d': "Yakın ve gürültülü. Ayakta kalan son kişi kazanır.",
  'mode.rifles': "Sadece tüfek",
  'mode.rifles.d': "Orta menzilli çatışmalar. Ayakta kalan son kişi kazanır.",
  'mode.snipers': "Sadece keskin nişancı",
  'mode.snipers.d': "Her yerde lazer nişangâh. Ayakta kalan son kişi kazanır.",
  'mode.team2': "Takım 2'ye 2",
  'mode.team2.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'mode.team4': "Takım 4'e 4",
  'mode.team4.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'mode.team8': "Takım 8'e 8",
  'mode.team8.d': "Her bahis tek bir potu büyütür. Ayakta kalan son takım paylaşır.",
  'hud.pot': "Ödül potu",
  'hud.left': "{n} kaldı · {s} bahis",
  'hud.teamsLeft': "{n} takım kaldı · {s} bahis",
  'hud.startPot': "Ayakta kalan son kişi potu alır",
  'hud.startTeam': "Takımınla kal · diğer tarafı sil",
  'hud.goldenPot': "Altın baskın · jackpot pota eklendi",
  'coach.pot': "Burada çıkış yok · çemberde kal · son ayakta kalan kazanır",
  'coach.team': "Yeşil isimler takımın · kırmızılar düşman",
  'warn.exit30': "30sn · açık bir çıkışa ulaş",
  'warn.exit10': "10sn · tahliye ol ya da hepsini kaybet",
  'warn.pot30': "30sn · fırtına daralıyor",
  'warn.pot10': "10sn · en çok hayatta kalan kazanır",
  'storm.final': "Son çöküş · sadece son çıkış",
  'storm.finalPot': "Son çöküş · saklanacak yer yok",
  'storm.closing': "Fırtına yaklaşıyor",
  'storm.in5': "Fırtına 5sn sonra ilerliyor",
  'feed.youDropped': "{name} kişisini indirdin",
  'feed.stormTook': "{name} fırtınaya yem oldu",
  'feed.dropped': "{a}, {b} kişisini indirdi",
  'feed.down': "{name} düştü",
  'feed.extracted': "{name} tahliye oldu",
  'feed.exitClosed': "{name} çıkışı kapandı",
  'spect.settling': "Sonucun baskın bitince gelecek.",
  'res.victory': "Zafer",
  'res.teamWon': "Takımın kazandı",
  'res.defeated': "Yenilgi",
  'res.wonText': "{s} bahisle {p} kazandın.",
  'res.lostPot': "Pot ayakta kalan son kişiye gitti.",
  'res.teamLost': "Potu diğer takım aldı.",
  'xp.Victory': "Zafer",
  'ach.champion': "Şampiyon",
  'ach.warlord': "Savaş lordu",
  'achd.wins': "{n} pot baskını kazan",
  'lk.weapons': "Silah skinleri",
  'lk.onlyBags': "Skinler sadece mağazadaki çanta ve sandıklardan çıkar.",
  'lk.toShop': "Mağazayı aç",
  'lk.toOpen': "{n} açılmayı bekliyor",
  'lk.limited': "Sınırlı · {n}",
  'lk.minted': "{b} adetin {a} tanesi basıldı",
  'lk.plain': "Standart",
  'lk.fromBags': "Mağazadaki kıyafet çantalarından çıkar.",
  'lk.fromCrates': "Mağazadaki silah sandıklarından çıkar.",
  'lk.trialHow2': "Rütbe denemesi: {t} daha senin.",
  'lk.weaponHow': "Giymek için sahip olduğun bir kaplamayı seç. Baskındaki herkes görür.",
  'fx.glow': "aura",
  'fx.pulse': "nabız gibi aura",
  'fx.ghost': "hayaletimsi",
  'fx.laser': "lazer gözler",
  'fx.rainbow': "prizmatik",
  'fx.fire': "alevli",
  'fx.gold': "sıvı altın",
  'fx.holo': "hologram",
  'fx.glitch': "glitch",
  'fx.lightning': "şimşek",
  'fx.galaxy': "galaksi",
  'fx.sparks': "kıvılcım",
  'fx.frost': "kırağı",
  'fx.money': "para yağmuru",
  'fx.matrix': "kod yağmuru",
  'fx.shadow': "gölge dumanı",
  'fx.cape': "pelerin",
  'box.street': "Sokak Çantası",
  'box.vault': "Kasa Çantası",
  'box.golden': "Altın Çanta",
  'box.elite': "Elit Çanta",
  'box.diamond': "Elmas Çanta",
  'box.obsidian': "Obsidyen Çanta",
  'box.royal': "Kraliyet Çantası",
  'box.apex': "Apex Çanta",
  'box.genesis': "Genesis Çanta",
  'box.w-scrap': "Hurda Sandığı",
  'box.w-armory': "Cephanelik Sandığı",
  'box.w-brass': "Pirinç Sandık",
  'box.w-specops': "Özel Harekât Sandığı",
  'box.w-diamond': "Elmas Sandık",
  'box.w-obsidian': "Obsidyen Sandık",
  'box.w-royal': "Kraliyet Sandığı",
  'box.w-apex': "Apex Sandık",
  'box.w-genesis': "Genesis Sandık",
  'shop.topup': "Mağaza $ yükle",
  'shop.bags': "Kıyafet çantaları",
  'shop.crates': "Silah sandıkları",
  'shop.bagsNote': "Koşucun için kıyafetler. Dokuz seviye: çanta ne kadar pahalıysa şans o kadar iyi.",
  'shop.cratesNote': "Silahların ve bıçağın için skinler, kıyafetlerden ayrı satılır. Dokuz seviye.",
  'shop.fair': "Kesin oranlar, sunucuda çekilir. Garanti: {e} açılışta Destansı+, {l} açılışta Efsanevi+.",
  'shop.odds': "Oranlar ve garanti",
  'shop.qty': "Adet",
  'shop.open': "Aç ×{n}",
  'shop.limited': "Sınırlı sürümler",
  'shop.soldOut': "Tükendi",
  'shop.dup': "Kopya · +{v}",
  'shop.new': "Yeni",
  'shop.back': "{v} iade",
  'shop.equipBest': "{n} giy",
  'inv.wallet': "Cüzdan",
  'inv.deposit': "Yatır · çek",
  'inv.walletNote': "Evin senin için tuttuğu gerçek tokenlar. Giriş yaptığın adrese istediğin zaman çek.",
  'inv.playNote': "Bu tarayıcıda oyun parası. İstediğin zaman doldur.",
  'inv.shopNote': "USDC/USDT ile alınır, sadece çanta ve sandıklara harcanır. Çekilemez.",
  'inv.unopened': "Açılmamış",
  'inv.collection': "Koleksiyon",
  'inv.opened': "Açılan",
  'inv.career': "Kariyer",
  'inv.raids': "Baskınlar",
  'inv.kills': "Öldürmeler",
  'inv.extracts': "Tahliyeler",
  'inv.wins': "Pot zaferleri",
  'inv.best': "En iyi baskın (öldürme)",
  'inv.time': "İçeride geçen süre",
  'swap.game': "Oyun bakiyesi",
  'swap.gameNote': "Anında, güncel fiyattan, %{f} ücret.",
  'swap.gameOff': "Bu sunucuda oyun içi takas kapalı. Aşağıdaki cüzdan takasını kullan.",
  'swap.from': "Verdiğin",
  'swap.to': "Aldığın",
  'swap.have': "Sende",
  'swap.flip': "Yönü çevir",
  'swap.go': "Takas et",
  'swap.short': "Yetersiz bakiye",
  'swap.done': "{a}, {b} ile takas edildi.",
  'swap.wallet': "Cüzdanın",
  'swap.signIn': "AVNU ile orada takas yapmak için bir Starknet cüzdanıyla giriş yap.",
  'swap.needChain': "AVNU takasları çevrimiçi modda gerçek bir Starknet cüzdanıyla çalışır.",
  'swap.slippage': "Maks. kayma",
  'swap.quoting': "En iyi rota aranıyor…",
  'swap.impact': "fiyat etkisi %{p}",
  'swap.goAvnu': "AVNU ile takas et",
  'swap.noQuote': "Bu çift için şu an rota yok.",
  'swap.sent': "Takas gönderildi: {tx}",
  'swap.walletNote': "AVNU, Starknet borsaları arasında rota bulur. Sen cüzdanında imzalarsın; oyun bu tokenları asla tutmaz.",
  'chat.ph': "Bir şey yaz…",
  'chat.send': "Gönder",
  'chat.empty': "Henüz mesaj yok. gm de.",
  'chat.online': "Lobideki herkes bunu görür. Kibar ol.",
  'chat.practice': "Antrenman çevrimdışı: sadece botlar dinliyor.",
  'set.graphics': "Grafik",
  'set.quality': "Kalite",
  'set.qualityNote': "Otomatik, kareler yavaşlayınca detayı düşürür.",
  'set.auto': "Otomatik",
  'set.high': "Yüksek",
  'set.medium': "Orta",
  'set.low': "Düşük",
  'set.shake': "Ekran sarsıntısı",
  'set.motion': "Menü animasyonları",
  'set.display': "Görünüm",
  'set.skins': "Skinler",
  'set.skinsNote': "Kimin kıyafet ve silah skinleri çizilsin.",
  'set.skinsAll': "Herkesin",
  'set.skinsMine': "Sadece benimkiler",
  'set.skinsNone': "Hiçbiri",
  'set.names': "Koşucuların üstünde isimler",
  'set.titles': "İsimlerin üstünde unvanlar",
  'set.controls': "Kontroller",
  'set.stick': "Dokunmatik çubuk boyutu",
  'set.lefty': "Solak (dokunmatik)",
  'set.leftyNote': "Hareket ve nişan çubuklarının yerini değiştirir.",
  'set.audio': "Ses",
  'set.sound': "Efekt sesi",
  'set.music': "Müzik sesi",
  'set.language': "Dil",
  'shop.exoticIn': "Egzotik için",
  'shop.guarantee': "{n} açılışta garantili Egzotik",
  'set.voice': "Spiker",
  'mode.dm': "Ölüm Maçı",
  'mode.dm.d': "Herkes kendi için, her ölümden sonra yeniden doğ. Süre bittiğinde en çok leşi alan potu kazanır.",
  'mode.gl': "Silahlar + Lazerler",
  'mode.gl.d': "Mağazalı ölüm maçı: leşler ilk yardım çantası, taret ve lazer mayını için kredi kazandırır.",
  'mode.hardcore': "Hardcore",
  'mode.hardcore.d': "En az can: tek kurşun ve düşersin. Ayakta kalan son kişi potu alır.",
  'kind.dm': "en çok leş potu alır",
  'hud.startDm': "Süre sıfırlandığında en çok leşi alan potu kazanır",
  'hud.startGl': "Leşler kredi kazandırır · 1 ilk yardım · 2 taret · 3 lazer mayını",
  'hud.startHc': "Tek isabet ve düşersin. Her atışı değerlendir.",
  'hud.respawned': "Geri döndün",
  'hud.respawnIn': "{s}sn içinde geri dönüş",
  'hud.tookLead': "Liderliği aldın",
  'hud.lostLead': "Liderliği kaybettin",
  'hud.dmScore': "{k} leş · {d} ölüm · #{p}",
  'hud.dmGoal': "İlk leş liderliği alır",
  'hud.oneHit': "1 İSABET",
  'feed.leader': "{name} {k} leşle liderliği aldı",
  'gl.medkit': "İlk yardım",
  'gl.turret': "Taret",
  'gl.mine': "Lazer mayını",
  'gl.no.cash': "Yetersiz kredi",
  'gl.no.full': "Canın zaten dolu",
  'gl.no.limit': "Sınıra ulaşıldı",
  'gl.no.wall': "Duvara çok yakın",
  'res.dmLost': "#{p}. oldun",
  'res.dmText': "{k} leş, {d} ölüm. Kazananın {top} leşi vardı.",
  'coach.dm': "Yeniden doğarsın · süre bitince en çok leşi olan kazanır",
  'coach.gl': "Leşler kredi kazandırır · ilk yardım ✚, taret ◈ ya da lazer mayını ⌁ al",
  'set.voiceNote': "Kayıtlı spiker (İngilizce, Ukraynaca, İspanyolca, Fransızca, Portekizce; diğer diller için İngilizce).",
  'net.waking': "Sunucu uyanıyor (ücretsiz barındırma kimse oynamazken uyur, bir dakikaya kadar)… Bu sırada antrenman çalışır.",
  'shop.bulk': "Her {n}. kutu bedava",
  'shop.bulkOn': "Dahil bedava kutu: {n}",
  'net.online': "{n} çevrimiçi",
  'st.title': "İlk adımlar",
  'st.signin': "Giriş yap",
  'st.signin.d': "Starknet cüzdanın, Cartridge ya da e-posta ile.",
  'st.signin.go': "Giriş yap",
  'st.fund': "Bakiye ekle",
  'st.fund.d': "Cüzdanından oyun bakiyene biraz token gönder. İstediğin zaman çekebilirsin.",
  'st.fundTest': "Test ağı: starknet-faucet.vercel.app adresinde ücretsiz STRK.",
  'st.fund.go': "Yatır",
  'st.coin': "Coinini seç",
  'st.coin.d': "Aşağıdan hangi coinle bahis yapacağını seç. Kazanç aynı coinle döner.",
  'st.coin.go': "Coinleri göster",
  'st.play': "İlk maçını oyna",
  'st.play.d': "Mod ve bahis seç, Oyna'ya ve sonra Hazır'a bas.",
  'st.play.go': "Oyna",
};
