export default {
  'lobby.tagline': '下注。搜刮。在风暴来临前撤离。<b>没人知道你包里有什么。</b>',
  'lobby.namePh': '你的跑者名字',
  'lobby.locker': '储物柜 · 皮肤 · 福袋',
  'lobby.refill': '补充测试币',
  'lobby.online': '在线',
  'lobby.practice': '人机练习',
  'lobby.stakePer': '每局下注',
  'lobby.stakeWith': '下注币种 <span class="fine">任意币种 · 以 $ 显示 · 奖金以同一币种返还</span>',
  'lobby.play': '开始 · 下注 {s}',
  'lobby.signIn': '登录后开始',
  'lobby.how': '玩法',
  'lobby.gore': '<b>18+ 模式。</b>肢体会被打飞，血迹会留在地上。',
  'lobby.fine': '练习模式在浏览器中运行。这里的钱都是游戏币。',
  'how.1': '<b>下注并准备。</b>所有人带着一把刀和 100 点生命同时进场。一半赌注在你的包里，一半作为战利品撒在地图上。',
  'how.2': '<b>捡起橙色战利品。</b>它会进入你的包。击杀会升级武器：刀 → 手枪 → 霰弹枪 → 冲锋枪 → 步枪 → 激光狙击枪。',
  'how.3': '<b>活着出去。</b>在风暴关闭前，在绿色出口站立 3 秒。整个包都归你。死了，包就掉给别人。',
  'how.keys': '<kbd>WASD</kbd> 移动 · <kbd>鼠标</kbd> 瞄准 · <kbd>点击</kbd> 攻击 · <kbd>空格</kbd> 冲刺 · <kbd>Q</kbd> 伪装包的大小 · <kbd>M</kbd> 音效 · <kbd>N</kbd> 音乐',
  'how.fine': '每局和每个成就都会给军衔经验。每次晋升都会借给你一套新皮肤，为期 3 天。',
  'net.practice': '只有你和机器人，离线。',
  'net.open': '已连接。真人和机器人同场。',
  'net.connecting': '正在连接服务器…',
  'net.down': '无法连接服务器，正在重试… 练习模式可离线游玩。',
  'net.lost': '连接断开，返回牌桌。',
  'q.pick': '选择一种币来下注。',
  'q.short': '{c} 不足以支付 {s} 的赌注。换一种币或降低赌注。',
  'q.shortDeposit': '{c} 不足以支付 {s} 的赌注。换一种币、降低赌注或充值。',
  'q.stable': '你以 {c} 下注 {s}。活着出去，带走你背着的一切。',
  'q.coin': '按今日价格下注 {a} = {s}。奖金按相同汇率以 {c} 返还。',
  'tb.live': '对局中 · {t}',
  'tb.ready': '{n} 人就绪 · {s}秒',
  'tb.waiting': '{n} 人等待',
  'tb.golden': '下一局：黄金局',
  'tb.jackpot': '奖池 {v}',
  'pcfg.title': '练习设置',
  'pcfg.difficulty': '机器人',
  'pcfg.easy': '简单',
  'pcfg.normal': '普通',
  'pcfg.hard': '困难',
  'pcfg.runners': '本局人数',
  'pcfg.time': '对局时长',
  'rk.max': '最高军衔',
  'rk.toNext': '距军衔 {r} 还需 {x} XP',
  'rk.of': '军衔 {r} / 90',
  'rk.rank': '军衔',
  'rk.up': '晋升',
  'rk.xp': '军衔经验',
  'xp.Raid': '参局',
  'xp.kills': '{n} 次击杀',
  'xp.Damage': '伤害',
  'xp.Time alive': '存活时间',
  'xp.First blood': '第一滴血',
  'xp.Double kill': '双杀',
  'xp.Triple kill': '三杀',
  'xp.Rampage': '暴走',
  'xp.Godlike': '超神',
  'xp.Full arsenal': '武器全通',
  'xp.Extracted': '撤离成功',
  'xp.Profit': '盈利',
  'xp.Practice ×0.5': '练习 ×0.5',
  'rw.title': '晋升奖励',
  'rw.trial': '可穿戴 72 小时',
  'rw.try': '试穿',
  'rw.share': '分享晋升',
  'prep.raid': '第 {n} 局 · 下注 {s}',
  'prep.readyUp': '准备',
  'prep.first': '第一位跑者准备后开始倒计时。',
  'prep.live': '有一局正在进行。现在准备，下一局和大家一起进场。',
  'prep.over': '本局结束，准备室马上开放。',
  'prep.many': '这里所有人都从刀开始。机器人在最后几秒加入。',
  'prep.bots': '机器人会在最后几秒补满空位。',
  'prep.open': '空位',
  'prep.pot': '奖池',
  'prep.cancel': '取消 · 退回 {v}',
  'prep.ready': '准备 · 下注 {v}',
  'prep.back': '返回牌桌',
  'hud.bagPrivate': '你的包 · 私密',
  'hud.golden': '黄金局',
  'hud.goldenStart': '黄金局 · 奖池战利品就在里面',
  'hud.start': '拿起刀 · 捡橙色 · 找出口',
  'hud.bagOpened': '包被打开 · +{v}',
  'hud.arsenal': '武器全通 · 回到刀 ★',
  'hud.unlocked': '已解锁 {w}',
  'hud.pnl': '{d}（赌注 {s}）',
  'hud.alive': '场内 {n} 人',
  'hud.next': '下一把：{w}',
  'hud.final': '最终圈 · 最后出口',
  'hud.closing': '风暴收缩 · {t}',
  'hud.stormIn': '风暴 {t} 后推进',
  'hud.dash': '冲刺',
  'hud.bagLook': '包的外观',
  'hud.extracting': '撤离中',
  'hud.holdStill': '别动。被击中会重置。',
  'hud.sound': '音效',
  'hud.music': '音乐',
  'bluff.0': '小',
  'bluff.1': '中',
  'bluff.2': '鼓',
  'touch.move': '移动',
  'touch.aim': '瞄准 · 开火',
  'touch.bag': '包',
  'w.Knife': '刀',
  'w.Pistol': '手枪',
  'w.Shotgun': '霰弹枪',
  'w.SMG': '冲锋枪',
  'w.Rifle': '步枪',
  'w.Laser sniper': '激光狙击枪',
  'streak.1': '第一滴血',
  'streak.2': '双杀',
  'streak.3': '三杀',
  'streak.4': '暴走',
  'streak.5': '超神',
  'streak.you1': '你拿下了第一滴血',
  'feed.storm': '你被风暴吞没',
  'feed.droppedYou': '{name} 击倒了你',
  'coach.storm': '你在风暴中 · 回到圈内',
  'coach.touch': '左手拇指移动 · 右手拇指瞄准和攻击',
  'coach.keys': 'WASD 移动 · 鼠标瞄准 · 点击攻击',
  'coach.exit': '该撤了 · 在绿色出口站 3 秒 · 屏幕边缘箭头指路',
  'coach.loot': '捡起橙色战利品 · 会进入你的包',
  'coach.kills': '击杀升级武器 · 空格冲刺',
  'coach.killsTouch': '击杀升级武器 · 点冲刺躲避',
  'spect.watching': '正在观战 {name} · ◀ ▶ 切换',
  'spect.down': '你倒下了',
  'spect.results': '结果',
  'res.extracted': '撤离成功',
  'res.storm': '被风暴吞没',
  'res.dropped': '被击倒',
  'res.sealed': '被困在内',
  'res.inside': '{k} 次击杀 · 场内 {t}',
  'res.out': '以 {s} 下注带出 {p}：{d}。',
  'res.paid': '按入场汇率支付 {v}。',
  'res.killer': '你的包现在在 {n} 手里。里面有 {v}，只有你们俩知道。',
  'res.inStorm': '你的包（{v}）躺在风暴里，等胆大的人来拿。',
  'res.sealedText': '对局结束时你还在里面。你的 {v} 进入了下一局的战利品。',
  'res.again': '再来一局',
  'res.tables': '牌桌',
  'res.share': '分享卡片',
  'share.title': '分享',
  'share.x': '发到 𝕏',
  'share.copy': '复制图片',
  'share.save': '保存 PNG',
  'share.close': '关闭',
  'lk.title': '储物柜',
  'lk.outfits': '外观',
  'lk.shop': '商店',
  'lk.bags': '幸运袋',
  'lk.all': '全部',
  'lk.owned': '已拥有',
  'lk.him': '男',
  'lk.her': '女',
  'lk.shopUsd': '商店 $',
  'lk.shopNote': '用 USDC 或 USDT 充值商店 $（大礼包有赠送）。商店 $ 只能在这里消费，不能提现。不够？差额从你的 USDC/USDT 扣除。',
  'lk.bagsNote': '概率公开，由服务器抽取。集齐一个稀有度之前不会重复，重复物品返还 10% 价格的商店 $。保底：15 次内必出史诗+，60 次内必出传说+。',
  'lk.topupFrom': '+ {v} USDC/USDT 可用于充值',
  'lk.collected': '已收集 {a} / {b}',
  'lk.equipped': '已装备',
  'lk.equip': '装备',
  'lk.buy': '购买',
  'lk.trialLeft': '试用 · 剩 {t}',
  'lk.trialHow': '晋升试用：还能用 {t}。购买即可永久保留。',
  'lk.free': '所有人免费。',
  'lk.inCollection': '已在你的收藏中。',
  'lk.buyOrBag': '在这里购买，或用幸运袋碰碰运气。',
  'lk.tryingOn': '试穿中。',
  'lk.bonus': '+{n}% 赠送',
  'lk.pay': '支付 {v}',
  'lk.jackpot': '大奖',
  'lk.epicIn': '史诗+ 还需',
  'lk.legIn': '传说+ 还需',
  'lk.openFree': '打开 · 免费',
  'lk.buyOpen': '购买并打开',
  'lk.pityDrop': '保底掉落',
  'lk.dup': '已拥有 · 返还 {v}',
  'lk.new': '收藏<b>新增</b>',
  'lk.jackpotIs': '大奖是 {r}',
  'lk.showOff': '在 X 上炫耀',
  'lk.postMiss': '在 X 上晒失手',
  'lk.another': '再开一个',
  'lk.free1': '免费',
  'lk.back': '返回储物柜',
  'lk.yours': '{n} 归你了。',
  'r.common': '普通',
  'r.rare': '稀有',
  'r.epic': '史诗',
  'r.legendary': '传说',
  'r.mythic': '神话',
  'r.exotic': '异域',
  'ach.title': '成就',
  'ach.button': '成就',
  'ach.intro': '每个成就只发放一次军衔经验，并解锁同名称号供你佩戴。',
  'ach.wear': '佩戴称号',
  'ach.worn': '佩戴中',
  'ach.wearing': '称号：',
  'ach.takeOff': '取下',
  'ach.noTitle': '无称号',
  'ach.unlocked': '成就解锁',
  'ach.seeAll': '全部成就',
  'achd.raids': '参加 {n} 局',
  'achd.extracts': '撤离 {n} 次',
  'achd.kills': '击杀 {n} 次',
  'achd.bestKills': '单局击杀 {n} 次',
  'achd.bestMulti': '一次 {n} 连杀',
  'achd.prestige': '武器全通 {n} 次',
  'achd.firstBloods': '拿下第一滴血 {n} 次',
  'achd.secs': '在对局中累计 {n} 小时',
  'achd.bestReturn': '以赌注 {n} 倍撤离',
  'achd.golden': '从黄金局撤离',
  'achd.lastExit': '从最后出口撤离',
  'achd.pacifist': '零击杀撤离',
  'achd.rank': '达到军衔 {n}',
  'achd.outfits': '拥有 {n} 套外观',
  'ach.rookie': '新兵',
  'ach.regular': '常客',
  'ach.veteran': '老兵',
  'ach.lifer': '终身兵',
  'ach.eternal': '永恒',
  'ach.escape_artist': '逃脱大师',
  'ach.ghost': '幽灵',
  'ach.smuggler': '走私者',
  'ach.phantom': '魅影',
  'ach.first_kill': '首杀',
  'ach.hunter': '猎手',
  'ach.butcher': '屠夫',
  'ach.reaper': '死神',
  'ach.apex': '顶点',
  'ach.rampage': '暴走',
  'ach.one_man_army': '一人成军',
  'ach.double_tap': '双击',
  'ach.triple_threat': '三重威胁',
  'ach.godlike': '超神',
  'ach.full_arsenal': '武器全通',
  'ach.arsenal_master': '军械大师',
  'ach.first_blood': '第一滴血',
  'ach.opener': '开局者',
  'ach.night_shift': '夜班',
  'ach.insomniac': '失眠者',
  'ach.double_up': '翻倍',
  'ach.big_bag': '大包',
  'ach.gold_rush': '淘金热',
  'ach.last_one_out': '最后离场',
  'ach.pacifist': '和平主义者',
  'ach.seasoned': '老练',
  'ach.officer': '军官',
  'ach.commander': '指挥官',
  'ach.legend': '传奇',
  'ach.collector': '收藏家',
  'ach.curator': '策展人',
  'ach.hoarder': '囤积者',
  'intro.tag': "下注。搜刮。撤离。",
  'intro.go': "进入",
  'intro.fonts': "正在磨刀…",
  'intro.world': "正在绘制黑暗…",
  'intro.connect': "正在寻找对局…",
  'intro.profile': "正在打包你的包…",
  'intro.ready': "就绪",
  'tb.wallet': "钱包",
  'tb.shop': "商店 $",
  'nav.play': "开始",
  'nav.shop': "商店",
  'nav.inventory': "库存",
  'nav.swap': "兑换",
  'nav.chat': "聊天",
  'nav.achievements': "成就",
  'nav.settings': "设置",
  'modes.title': "游戏模式",
  'kind.raid': "撤离",
  'kind.br': "赢家通吃奖池",
  'kind.team': "团队奖池",
  'mode.raid': "突袭",
  'mode.raid.d': "搜刮、战斗，从出口撤离。带走你身上的一切。",
  'mode.br': "大逃杀",
  'mode.br.d': "最多 20 名跑者。最后存活者拿走整个奖池。",
  'mode.duel': "决斗",
  'mode.duel.d': "一对一。胜者拿走双方赌注。",
  'mode.knives': "只用刀",
  'mode.knives.d': "全局只有刀。最后存活者获胜。",
  'mode.pistols': "只用手枪",
  'mode.pistols.d': "只有手枪。最后存活者获胜。",
  'mode.shotguns': "只用霰弹枪",
  'mode.shotguns.d': "近距离硬碰硬。最后存活者获胜。",
  'mode.rifles': "只用步枪",
  'mode.rifles.d': "中距离交火。最后存活者获胜。",
  'mode.snipers': "只用狙击枪",
  'mode.snipers.d': "到处都是激光瞄准。最后存活者获胜。",
  'mode.team2': "团队 2 对 2",
  'mode.team2.d': "每份赌注都汇入同一个奖池。最后存活的队伍平分。",
  'mode.team4': "团队 4 对 4",
  'mode.team4.d': "每份赌注都汇入同一个奖池。最后存活的队伍平分。",
  'mode.team8': "团队 8 对 8",
  'mode.team8.d': "每份赌注都汇入同一个奖池。最后存活的队伍平分。",
  'hud.pot': "奖池",
  'hud.left': "剩余 {n} · 赌注 {s}",
  'hud.teamsLeft': "剩余 {n} 队 · 赌注 {s}",
  'hud.startPot': "最后存活者拿走奖池",
  'hud.startTeam': "跟紧队友 · 消灭对面",
  'hud.goldenPot': "黄金局 · 大奖已加入奖池",
  'coach.pot': "这里没有出口 · 待在圈内 · 最后存活者获胜",
  'coach.team': "绿色名字是队友 · 红色是敌人",
  'warn.exit30': "30 秒 · 赶到开放的出口",
  'warn.exit10': "10 秒 · 撤离，否则全部失去",
  'warn.pot30': "30 秒 · 风暴正在收缩",
  'warn.pot10': "10 秒 · 存活人数最多的一方获胜",
  'storm.final': "最终坍塌 · 只剩最后出口",
  'storm.finalPot': "最终坍塌 · 无处可躲",
  'storm.closing': "风暴正在逼近",
  'storm.in5': "风暴 5 秒后推进",
  'feed.youDropped': "你击倒了 {name}",
  'feed.stormTook': "{name} 被风暴吞没",
  'feed.dropped': "{a} 击倒了 {b}",
  'feed.down': "{name} 倒下了",
  'feed.extracted': "{name} 撤离成功",
  'feed.exitClosed': "出口 {name} 已关闭",
  'spect.settling': "对局结算后显示你的结果。",
  'res.victory': "胜利",
  'res.teamWon': "你的队伍赢了",
  'res.defeated': "失败",
  'res.wonText': "以 {s} 的赌注拿走了 {p}。",
  'res.lostPot': "奖池归最后存活者所有。",
  'res.teamLost': "对方队伍拿走了奖池。",
  'xp.Victory': "胜利",
  'ach.champion': "冠军",
  'ach.warlord': "军阀",
  'achd.wins': "赢得 {n} 场奖池对局",
  'lk.weapons': "武器皮肤",
  'lk.onlyBags': "皮肤只能从商店的福袋和箱子里获得。",
  'lk.toShop': "打开商店",
  'lk.toOpen': "{n} 个待开",
  'lk.limited': "限量 · {n}",
  'lk.minted': "已铸造 {a} / {b}",
  'lk.plain': "标准",
  'lk.fromBags': "从商店的外观福袋掉落。",
  'lk.fromCrates': "从商店的武器箱掉落。",
  'lk.trialHow2': "晋升试用：还能用 {t}。",
  'lk.weaponHow': "选择你拥有的涂装进行装备。对局中所有人都能看到。",
  'fx.glow': "光环",
  'fx.pulse': "脉动光环",
  'fx.ghost': "幽灵",
  'fx.laser': "激光眼",
  'fx.rainbow': "棱彩",
  'fx.fire': "燃烧",
  'fx.gold': "流金",
  'fx.holo': "全息",
  'fx.glitch': "故障",
  'fx.lightning': "闪电",
  'fx.galaxy': "星河",
  'fx.sparks': "火花",
  'fx.frost': "冰霜",
  'fx.money': "钞票雨",
  'fx.matrix': "代码雨",
  'fx.shadow': "暗影烟雾",
  'fx.cape': "披风",
  'box.street': "街头福袋",
  'box.vault': "金库福袋",
  'box.golden': "黄金福袋",
  'box.elite': "精英福袋",
  'box.diamond': "钻石福袋",
  'box.obsidian': "黑曜石福袋",
  'box.royal': "皇家福袋",
  'box.apex': "巅峰福袋",
  'box.genesis': "创世福袋",
  'box.w-scrap': "废料箱",
  'box.w-armory': "军械箱",
  'box.w-brass': "黄铜箱",
  'box.w-specops': "特种作战箱",
  'box.w-diamond': "钻石箱",
  'box.w-obsidian': "黑曜石箱",
  'box.w-royal': "皇家箱",
  'box.w-apex': "巅峰箱",
  'box.w-genesis': "创世箱",
  'shop.topup': "充值商店 $",
  'shop.bags': "外观福袋",
  'shop.crates': "武器箱",
  'shop.bagsNote': "跑者外观。九个档次：福袋越贵，概率越好。",
  'shop.cratesNote': "枪和刀的皮肤，与外观分开出售。九个档次。",
  'shop.fair': "概率公开，由服务器抽取。保底：{e} 次内史诗+，{l} 次内传说+。",
  'shop.odds': "概率与保底",
  'shop.qty': "数量",
  'shop.open': "打开 ×{n}",
  'shop.limited': "限量版",
  'shop.soldOut': "已售罄",
  'shop.dup': "重复 · +{v}",
  'shop.new': "新",
  'shop.back': "返还 {v}",
  'shop.equipBest': "装备 {n}",
  'inv.wallet': "钱包",
  'inv.deposit': "充值 · 提现",
  'inv.walletNote': "平台为你保管的真实代币。随时提现到你登录的地址。",
  'inv.playNote': "本浏览器中的游戏币。随时补充。",
  'inv.shopNote': "用 USDC/USDT 购买，只能用于福袋和箱子，无法提现。",
  'inv.unopened': "未打开",
  'inv.collection': "收藏",
  'inv.opened': "已打开",
  'inv.career': "生涯",
  'inv.raids': "对局",
  'inv.kills': "击杀",
  'inv.extracts': "撤离",
  'inv.wins': "奖池胜利",
  'inv.best': "最佳对局（击杀）",
  'inv.time': "对局时长",
  'swap.game': "游戏余额",
  'swap.gameNote': "即时按实时价格兑换，手续费 {f}%。",
  'swap.gameOff': "此服务器关闭了游戏内兑换。请使用下方的钱包兑换。",
  'swap.from': "支付",
  'swap.to': "获得",
  'swap.have': "你有",
  'swap.flip': "反转方向",
  'swap.go': "兑换",
  'swap.short': "余额不足",
  'swap.done': "已将 {a} 兑换为 {b}。",
  'swap.wallet': "你的钱包",
  'swap.signIn': "登录 Starknet 钱包，即可通过 AVNU 在钱包内兑换。",
  'swap.needChain': "AVNU 兑换需要在线模式下的真实 Starknet 钱包。",
  'swap.slippage': "最大滑点",
  'swap.quoting': "正在寻找最佳路径…",
  'swap.impact': "价格影响 {p}%",
  'swap.goAvnu': "用 AVNU 兑换",
  'swap.noQuote': "该交易对暂时没有路径。",
  'swap.sent': "兑换已发送：{tx}",
  'swap.walletNote': "AVNU 在 Starknet 各交易所之间寻找路径。你在钱包里签名，游戏从不持有这些代币。",
  'chat.ph': "说点什么…",
  'chat.send': "发送",
  'chat.empty': "还没有消息。说声 gm 吧。",
  'chat.online': "大厅里所有人都能看到。请友善。",
  'chat.practice': "练习模式离线：只有机器人在听。",
  'set.graphics': "图形",
  'set.quality': "画质",
  'set.qualityNote': "自动模式会在帧率下降时降低细节。",
  'set.auto': "自动",
  'set.high': "高",
  'set.medium': "中",
  'set.low': "低",
  'set.shake': "屏幕震动",
  'set.motion': "菜单动画",
  'set.display': "显示",
  'set.skins': "皮肤",
  'set.skinsNote': "显示谁的外观和武器皮肤。",
  'set.skinsAll': "所有人",
  'set.skinsMine': "只有我的",
  'set.skinsNone': "都不显示",
  'set.names': "跑者头顶名字",
  'set.titles': "名字上方称号",
  'set.controls': "操作",
  'set.stick': "触控摇杆大小",
  'set.lefty': "左手触控",
  'set.leftyNote': "交换移动和瞄准摇杆。",
  'set.audio': "音频",
  'set.sound': "音效音量",
  'set.music': "音乐音量",
  'set.language': "语言",
  'shop.exoticIn': "异域还需",
  'shop.guarantee': "{n} 次内必出异域",
  'set.voice': "播报员",
  'mode.dm': "死亡竞赛",
  'mode.dm.d': "各自为战，每次阵亡后复活。时间结束时击杀最多者赢得奖池。",
  'mode.gl': "枪械 + 激光",
  'mode.gl.d': "带商店的死亡竞赛：击杀获得积分，可购买医疗包、哨戒炮塔和激光绊雷。",
  'mode.hardcore': "硬核",
  'mode.hardcore.d': "极低生命值：一发子弹就倒下。最后幸存者赢得奖池。",
  'kind.dm': "击杀最多者赢得奖池",
  'hud.startDm': "计时归零时击杀最多者赢得奖池",
  'hud.startGl': "击杀获得积分 · 1 医疗包 · 2 炮塔 · 3 激光雷",
  'hud.startHc': "一击即倒。每一枪都要算数。",
  'hud.respawned': "重返战场",
  'hud.respawnIn': "{s} 秒后复活",
  'hud.tookLead': "你已取得领先",
  'hud.lostLead': "你失去了领先",
  'hud.dmScore': "{k} 击杀 · {d} 阵亡 · 第 {p} 名",
  'hud.dmGoal': "第一个击杀即取得领先",
  'hud.oneHit': "一击",
  'feed.leader': "{name} 以 {k} 击杀领先",
  'gl.medkit': "医疗包",
  'gl.turret': "哨戒炮塔",
  'gl.mine': "激光绊雷",
  'gl.no.cash': "积分不足",
  'gl.no.full': "生命值已满",
  'gl.no.limit': "已达上限",
  'gl.no.wall': "离墙太近",
  'res.dmLost': "第 {p} 名",
  'res.dmText': "{k} 击杀，{d} 阵亡。冠军击杀 {top}。",
  'coach.dm': "你会复活 · 结束时击杀最多者获胜",
  'coach.gl': "击杀获得积分 · 购买医疗包 ✚、炮塔 ◈ 或激光雷 ⌁",
  'set.voiceNote': "录制播报（英语、乌克兰语、西班牙语、法语、葡萄牙语；其他语言使用英语）。",
  'net.waking': "正在唤醒服务器（免费主机无人游玩时会休眠，最多一分钟）…… 练习模式可以照常游玩。",
  'shop.bulk': "每 {n} 个箱子送 1 个",
  'shop.bulkOn': "已含免费箱子：{n}",
  'net.online': "{n} 人在线",
};
